# encoding: UTF-8
def airp_13
  {"LAK"=>
  {:iata=>"LAK",
   :name=>"Aklavik Airport",
   :icao=>"CYKD",
   :city=>"Aklavik",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Aklavik, Northwest Territories, Canada"},
 "LRQ"=>
  {:iata=>"LRQ",
   :name=>"Laurie River Airport",
   :icao=>"",
   :city=>"Laurie River",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Laurie River, Manitoba, Canada"},
 "LLU"=>
  {:iata=>"LLU",
   :name=>"Alluitsup Paa Heliport",
   :icao=>"BGAP",
   :city=>"Alluitsup Paa",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Alluitsup Paa, Greenland"},
 "LAP"=>
  {:iata=>"LAP",
   :name=>"Manuel Márquez de León International Airport",
   :icao=>"MMLP",
   :city=>"La Paz",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"La Paz, Baja California Sur, Mexico"},
 "LZC"=>
  {:iata=>"LZC",
   :name=>"Lázaro Cárdenas Airport",
   :icao=>"MMLC",
   :city=>"Lázaro Cárdenas",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Lázaro Cárdenas, Michoacán, Mexico"},
 "LTO"=>
  {:iata=>"LTO",
   :name=>"Loreto International Airport",
   :icao=>"MMLT",
   :city=>"Loreto",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Loreto, Baja California Sur, Mexico"},
 "LMM"=>
  {:iata=>"LMM",
   :name=>"Federal del Valle del Fuerte International Airport",
   :icao=>"MMLM",
   :city=>"Los Mochis",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Los Mochis, Sinaloa, Mexico"},
 "LOV"=>
  {:iata=>"LOV",
   :name=>"Venustiano Carranza International Airport",
   :icao=>"MMMV",
   :city=>"Monclova",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Monclova, Coahuila, Mexico"},
 "LOM"=>
  {:iata=>"LOM",
   :name=>"Francisco P.V. y R. Airport",
   :icao=>"",
   :city=>"Lagos de Moreno",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Lagos de Moreno, Jalisco, Mexico"},
 "LAR"=>
  {:iata=>"LAR",
   :name=>"Laramie Regional Airport",
   :icao=>"KLAR",
   :city=>"Laramie",
   :country=>'United States', :country_code=>'US',

   :location=>"Laramie, Wyoming, United States"},
 "LND"=>
  {:iata=>"LND",
   :name=>"Hunt Field",
   :icao=>"KLND",
   :city=>"Lander",
   :country=>'United States', :country_code=>'US',

   :location=>"Lander, Wyoming, United States"},
 "LSK"=>
  {:iata=>"LSK",
   :name=>"Lusk Municipal Airport",
   :icao=>"KLSK",
   :city=>"Lusk",
   :country=>'United States', :country_code=>'US',

   :location=>"Lusk, Wyoming, United States"},
 "LPG"=>
  {:iata=>"LPG",
   :name=>"La Plata International Airport",
   :icao=>"SADL",
   :city=>"La Plata",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"La Plata, Buenos Aires, Argentina"},
 "LGS"=>
  {:iata=>"LGS",
   :name=>"Comodoro D. Ricardo Salomón Airport (Malargüe Airport)",
   :icao=>"SAMM",
   :city=>"Malargüe",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Malargüe, Mendoza, Argentina"},
 "LUQ"=>
  {:iata=>"LUQ",
   :name=>"San Luis Airport",
   :icao=>"SAOU",
   :city=>"San Luis",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Luis, Argentina"},
 "LCM"=>
  {:iata=>"LCM",
   :name=>"La Cumbre Airport",
   :icao=>"SACC",
   :city=>"La Cumbre",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"La Cumbre, Córdoba, Argentina"},
 "LHS"=>
  {:iata=>"LHS",
   :name=>"Las Heras Airport",
   :icao=>"SAVH",
   :city=>"Las Heras",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Las Heras, Santa Cruz, Argentina"},
 "LLS"=>
  {:iata=>"LLS",
   :name=>"Alferez Armando Rodriguez",
   :icao=>"SATK",
   :city=>"Las Lomitas",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Las Lomitas, Formosa, Argentina"},
 "LCP"=>
  {:iata=>"LCP",
   :name=>"Loncopué Airport",
   :icao=>"",
   :city=>"Loncopué",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Loncopué, Neuquén, Argentina"},
 "LMD"=>
  {:iata=>"LMD",
   :name=>"Los Menucos Airport",
   :icao=>"",
   :city=>"Los Menucos",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Los Menucos, Río Negro, Argentina"},
 "LPB"=>
  {:iata=>"LPB",
   :name=>"El Alto International Airport",
   :icao=>"SLLP",
   :city=>"La Paz",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"La Paz, Bolivia"},
 "LBR"=>
  {:iata=>"LBR",
   :name=>"Lábrea Airport",
   :icao=>"SWLB",
   :city=>"Lábrea",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Lábrea, Amazonas, Brazil"},
 "LEC"=>
  {:iata=>"LEC",
   :name=>"Chapada Diamantina Airport",
   :icao=>"SBLE",
   :city=>"Lençõis",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Lençõis, Bahia, Brazil"},
 "LDB"=>
  {:iata=>"LDB",
   :name=>"Londrina Airport",
   :icao=>"SBLO",
   :city=>"Londrina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Londrina, Paraná, Brazil"},
 "LAZ"=>
  {:iata=>"LAZ",
   :name=>"Bom Jesus da Lapa Airport",
   :icao=>"SBLP",
   :city=>"Bom Jesus da Lapa",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Bom Jesus da Lapa, Bahia, Brazil"},
 "LAJ"=>
  {:iata=>"LAJ",
   :name=>"Lages Airport",
   :icao=>"SBLJ",
   :city=>"Lages",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Lages, Santa Catarina, Brazil"},
 "LEP"=>
  {:iata=>"LEP",
   :name=>"Leopoldina Airport",
   :icao=>"SNDN",
   :city=>"Leopoldina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Leopoldina, Minas Gerais, Brazil"},
 "LIP"=>
  {:iata=>"LIP",
   :name=>"Lins Airport",
   :icao=>"SBLN",
   :city=>"Lins",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Lins, São Paulo, Brazil"},
 "LVB"=>
  {:iata=>"LVB",
   :name=>"Dos Galpoes Airport",
   :icao=>"SSLI",
   :city=>"Santana do Livramento",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santana do Livramento, Rio Grande do Sul, Brazil"},
 "LOI"=>
  {:iata=>"LOI",
   :name=>"Helmuth Baungartem Airport",
   :icao=>"",
   :city=>"Lontras",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Lontras, Santa Catarina, Brazil"},
 "LCB"=>
  {:iata=>"LCB",
   :name=>"Pontes e Lacerda Airport",
   :icao=>"",
   :city=>"Pontes e Lacerda",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pontes e Lacerda, Mato Grosso, Brazil"},
 "LSC"=>
  {:iata=>"LSC",
   :name=>"La Florida Airport",
   :icao=>"SCSE",
   :city=>"La Serena",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"La Serena, Chile"},
 "LGR"=>
  {:iata=>"LGR",
   :name=>"Cochrane Airport",
   :icao=>"SCHR",
   :city=>"Cochrane",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Cochrane, Chile"},
 "LOB"=>
  {:iata=>"LOB",
   :name=>"Los Andes Airport",
   :icao=>"",
   :city=>"Los Andes",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Los Andes, Chile"},
 "LSQ"=>
  {:iata=>"LSQ",
   :name=>"Maria Dolores Airport",
   :icao=>"SCGE",
   :city=>"Los Ángeles",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Los Ángeles, Biobío, Chile"},
 "LCR"=>
  {:iata=>"LCR",
   :name=>"La Chorrera Airport",
   :icao=>"",
   :city=>"La Chorrera",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"La Chorrera, Colombia"},
 "LPD"=>
  {:iata=>"LPD",
   :name=>"La Pedrera Airport",
   :icao=>"SKLP",
   :city=>"La Pedrera",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"La Pedrera, Colombia"},
 "LMC"=>
  {:iata=>"LMC",
   :name=>"La Macarena Airport",
   :icao=>"",
   :city=>"La Macarena",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"La Macarena, Colombia"},
 "LET"=>
  {:iata=>"LET",
   :name=>"Alfredo Vásquez Cobo International Airport",
   :icao=>"SKLT",
   :city=>"Leticia",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Leticia, Colombia"},
 "LQM"=>
  {:iata=>"LQM",
   :name=>"Caucayá Airport",
   :icao=>"SKLG",
   :city=>"Puerto Leguízamo",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Leguízamo, Colombia"},
 "LPE"=>
  {:iata=>"LPE",
   :name=>"La Primavera Airport",
   :icao=>"",
   :city=>"La Primavera",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"La Primavera, Vichada, Colombia"},
 "LGT"=>
  {:iata=>"LGT",
   :name=>"Gaviotas Airport",
   :icao=>"SKGA",
   :city=>"Gaviotas",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Gaviotas, Vichada, Colombia"},
 "LMX"=>
  {:iata=>"LMX",
   :name=>"Lopez de Micay Airport",
   :icao=>"",
   :city=>"Lopez de Micay",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Lopez de Micay, Colombia"},
 "LRI"=>
  {:iata=>"LRI",
   :name=>"Lorica Airport",
   :icao=>"",
   :city=>"Lorica",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Lorica, Colombia"},
 "LGQ"=>
  {:iata=>"LGQ",
   :name=>"Lago Agrio Airport",
   :icao=>"SENL",
   :city=>"Nueva Loja",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Nueva Loja, Ecuador"},
 "LTX"=>
  {:iata=>"LTX",
   :name=>"Cotopaxi International Airport",
   :icao=>"",
   :city=>"Latacunga",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Latacunga, Ecuador"},
 "LOH"=>
  {:iata=>"LOH",
   :name=>"Camilo Ponce Enriquez Airport",
   :icao=>"SETM",
   :city=>"Loja",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Loja, Ecuador"},
 "LDX"=>
  {:iata=>"LDX",
   :name=>"St-Laurent du Maroni Airport",
   :icao=>"SOOM",
   :city=>"St-Laurent du Maroni",
   :country=>'French Guiana', :country_code=>'GF',
   :location=>"St-Laurent du Maroni, French Guiana"},
 "LTM"=>
  {:iata=>"LTM",
   :name=>"Lethem Airport",
   :icao=>"SYLT",
   :city=>"Lethem",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Lethem, Guyana"},
 "LUB"=>
  {:iata=>"LUB",
   :name=>"Lumid Pau Airport",
   :icao=>"SYLP",
   :city=>"Lumid Pau",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Lumid Pau, Guyana"},
 "LIM"=>
  {:iata=>"LIM",
   :name=>"Jorge Chávez International Airport",
   :icao=>"SPIM",
   :city=>"Callao (near Lima)",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Callao (near Lima), Peru"},
 "LDO"=>
  {:iata=>"LDO",
   :name=>"Ladouanie Airport",
   :icao=>"",
   :city=>"Ladouanie",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Ladouanie, Suriname"},
 "LFR"=>
  {:iata=>"LFR",
   :name=>"La Fria Airport",
   :icao=>"SVLF",
   :city=>"La Fria",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"La Fria, Venezuela"},
 "LSP"=>
  {:iata=>"LSP",
   :name=>"Josefa Camejo International Airport",
   :icao=>"SVJC",
   :city=>"Las Piedras",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Las Piedras, Venezuela"},
 "LRV"=>
  {:iata=>"LRV",
   :name=>"Los Roques Airport",
   :icao=>"SVRS",
   :city=>"Los Roques",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Los Roques, Venezuela"},
 "LAG"=>
  {:iata=>"LAG",
   :name=>"La Guaira Airport",
   :icao=>"",
   :city=>"La Guaira",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"La Guaira, Venezuela"},
 "LGY"=>
  {:iata=>"LGY",
   :name=>"Lagunillas Airport",
   :icao=>"",
   :city=>"Lagunillas",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Lagunillas, Zulia, Venezuela"},
 "LPJ"=>
  {:iata=>"LPJ",
   :name=>"Armando Schwarck Airport",
   :icao=>"SVAS",
   :city=>"Pijiguaos",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Pijiguaos, Venezuela"},
 "LST"=>
  {:iata=>"LST",
   :name=>"Launceston Airport",
   :icao=>"YMLT",
   :city=>"Launceston",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Launceston, Tasmania, Australia"},
 "LEA"=>
  {:iata=>"LEA",
   :name=>"Learmonth Airport (RAAF Learmonth)",
   :icao=>"YPLM",
   :city=>"Exmouth",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Exmouth, Western Australia, Australia"},
 "LSY"=>
  {:iata=>"LSY",
   :name=>"Lismore Airport",
   :icao=>"YLIS",
   :city=>"Lismore",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lismore, New South Wales, Australia"},
 "LRE"=>
  {:iata=>"LRE",
   :name=>"Longreach Airport",
   :icao=>"YLRE",
   :city=>"Longreach",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Longreach, Queensland, Australia"},
 "LDH"=>
  {:iata=>"LDH",
   :name=>"Lord Howe Island Airport",
   :icao=>"YLHI",
   :city=>"Lord Howe Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lord Howe Island, New South Wales, Australia"},
 "LCN"=>
  {:iata=>"LCN",
   :name=>"Balcanoona Airport",
   :icao=>"YBLC",
   :city=>"Balcanoona",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Balcanoona, South Australia, Australia"},
 "LLG"=>
  {:iata=>"LLG",
   :name=>"Chillagoe Airport",
   :icao=>"YCGO",
   :city=>"Chillagoe",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Chillagoe, Queensland, Australia"},
 "LYT"=>
  {:iata=>"LYT",
   :name=>"Lady Elliot Island Airport",
   :icao=>"",
   :city=>"Lady Elliot Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lady Elliot Island, Queensland, Australia"},
 "LEL"=>
  {:iata=>"LEL",
   :name=>"Lake Evella Airport",
   :icao=>"YLEV",
   :city=>"Gapuwiyak (Lake Evella)",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gapuwiyak (Lake Evella), Northern Territory, Australia"},
 "LGE"=>
  {:iata=>"LGE",
   :name=>"Lake Gregory Airport",
   :icao=>"",
   :city=>"Lake Gregory",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lake Gregory, Western Australia, Australia"},
 "LNH"=>
  {:iata=>"LNH",
   :name=>"Lake Nash Airport",
   :icao=>"YLKN",
   :city=>"Lake Nash",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lake Nash, Northern Territory, Australia"},
 "LFP"=>
  {:iata=>"LFP",
   :name=>"Lakefield Airport",
   :icao=>"YLFD",
   :city=>"Lakefield",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lakefield, Queensland, Australia"},
 "LKD"=>
  {:iata=>"LKD",
   :name=>"Lakeland Downs Airport",
   :icao=>"YLND",
   :city=>"Lakeland Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lakeland Downs, Queensland, Australia"},
 "LDW"=>
  {:iata=>"LDW",
   :name=>"Lansdowne Airport",
   :icao=>"",
   :city=>"Lansdowne",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lansdowne, Western Australia, Australia"},
 "LTB"=>
  {:iata=>"LTB",
   :name=>"Latrobe Airport",
   :icao=>"",
   :city=>"Latrobe",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Latrobe, Tasmania, Australia"},
 "LUU"=>
  {:iata=>"LUU",
   :name=>"Laura Airport",
   :icao=>"YLRA",
   :city=>"Laura",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Laura, Queensland, Australia"},
 "LUT"=>
  {:iata=>"LUT",
   :name=>"Laura Station Airport",
   :icao=>"YLRS",
   :city=>"Laura Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Laura Station, Queensland, Australia"},
 "LVO"=>
  {:iata=>"LVO",
   :name=>"Laverton Airport",
   :icao=>"YLTN",
   :city=>"Laverton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Laverton, Western Australia, Australia"},
 "LWH"=>
  {:iata=>"LWH",
   :name=>"Lawn Hill Airport",
   :icao=>"YLAH",
   :city=>"Lawn Hill",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lawn Hill, Queensland, Australia"},
 "LGH"=>
  {:iata=>"LGH",
   :name=>"Leigh Creek Airport",
   :icao=>"YLEC",
   :city=>"Leigh Creek",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Leigh Creek, South Australia, Australia"},
 "LER"=>
  {:iata=>"LER",
   :name=>"Leinster Airport",
   :icao=>"YLST",
   :city=>"Leinster",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Leinster, Western Australia, Australia"},
 "LNO"=>
  {:iata=>"LNO",
   :name=>"Leonora Airport",
   :icao=>"YLEO",
   :city=>"Leonora",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Leonora, Western Australia, Australia"},
 "LHG"=>
  {:iata=>"LHG",
   :name=>"Lightning Ridge Airport",
   :icao=>"YLRD",
   :city=>"Lightning Ridge",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lightning Ridge, New South Wales, Australia"},
 "LIB"=>
  {:iata=>"LIB",
   :name=>"Limbunya Airport",
   :icao=>"",
   :city=>"Limbunya",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Limbunya, Northern Territory, Australia"},
 "LLP"=>
  {:iata=>"LLP",
   :name=>"Linda Downs Airport",
   :icao=>"",
   :city=>"Linda Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Linda Downs, Queensland, Australia"},
 "LDC"=>
  {:iata=>"LDC",
   :name=>"Lindeman Island Airport",
   :icao=>"YLIN",
   :city=>"Lindeman Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lindeman Island, Queensland, Australia"},
 "LLL"=>
  {:iata=>"LLL",
   :name=>"Lissadell Airport",
   :icao=>"",
   :city=>"Lissadell",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lissadell, Western Australia, Australia"},
 "LZR"=>
  {:iata=>"LZR",
   :name=>"Lizard Island Airport",
   :icao=>"YLZI",
   :city=>"Lizard Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lizard Island, Queensland, Australia"},
 "LOC"=>
  {:iata=>"LOC",
   :name=>"Lock Airport",
   :icao=>"YLOK",
   :city=>"Lock",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lock, South Australia, Australia"},
 "LOA"=>
  {:iata=>"LOA",
   :name=>"Lorraine Airport",
   :icao=>"YLOR",
   :city=>"Lorraine",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lorraine, Queensland, Australia"},
 "LTV"=>
  {:iata=>"LTV",
   :name=>"Lotus Vale Station Airport",
   :icao=>"YLOV",
   :city=>"Lotus Vale Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lotus Vale Station, Queensland, Australia"},
 "LTP"=>
  {:iata=>"LTP",
   :name=>"Lyndhurst Airport",
   :icao=>"YLHS",
   :city=>"Lyndhurst",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lyndhurst, Shire of Etheridge, Queensland, Australia"},
 "LBH"=>
  {:iata=>"LBH",
   :name=>"Palm Beach Seaplane Base",
   :icao=>"",
   :city=>"Palm Beach",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Palm Beach, New South Wales, Australia"},
 "LEV"=>
  {:iata=>"LEV",
   :name=>"Levuka Airfield",
   :icao=>"NFNB",
   :city=>"Bureta",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Bureta, Ovalau Island, Fiji"},
 "LBS"=>
  {:iata=>"LBS",
   :name=>"Labasa Airport",
   :icao=>"NFNL",
   :city=>"Labasa",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Labasa, Fiji"},
 "LKB"=>
  {:iata=>"LKB",
   :name=>"Lakeba Island Airport",
   :icao=>"NFNK",
   :city=>"Lakeba Island",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Lakeba Island, Fiji"},
 "LUC"=>
  {:iata=>"LUC",
   :name=>"Laucala Island Airport",
   :icao=>"NFNH",
   :city=>"Laucala Island",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Laucala Island, Fiji"},
 "LML"=>
  {:iata=>"LML",
   :name=>"Lae Airport",
   :icao=>"",
   :city=>"Lae Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Lae Atoll, Marshall Islands"},
 "LIK"=>
  {:iata=>"LIK",
   :name=>"Likiep Airport",
   :icao=>"",
   :city=>"Likiep Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Likiep Atoll, Marshall Islands"},
 "LOF"=>
  {:iata=>"LOF",
   :name=>"Loen Airport",
   :icao=>"",
   :city=>"Loen",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Loen, Marshall Islands"},
 "LIF"=>
  {:iata=>"LIF",
   :name=>"Ouanaham Airport",
   :icao=>"NWWL",
   :city=>"Lifou",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Lifou, Loyalty Islands, New Caledonia"},
 "LAV"=>
  {:iata=>"LAV",
   :name=>"Lalomalava Airport",
   :icao=>"",
   :city=>"Lalomalava",
   :country=>"Samoa",
:country_code=>"WS",
   :location=>"Lalomalava, Samoa"},
 "LPM"=>
  {:iata=>"LPM",
   :name=>"Malekoula Island Airport (Lamap Airport)",
   :icao=>"NVSL",
   :city=>"Lamap",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Lamap, Malampa, Vanuatu"},
 "LNB"=>
  {:iata=>"LNB",
   :name=>"Lamen Bay Airport",
   :icao=>"NVSM",
   :city=>"Lamen Bay",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Lamen Bay, Epi Island, Shéfa Province, Vanuatu"},
 "LOD"=>
  {:iata=>"LOD",
   :name=>"Longana Airport (Ambae Airport)",
   :icao=>"NVSG",
   :city=>"Longana",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Longana, Ambae Island, Pénama Province, Vanuatu"},
 "LNE"=>
  {:iata=>"LNE",
   :name=>"Lonorore Airport",
   :icao=>"NVSO",
   :city=>"Lonorore",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Lonorore, Pentecost Island, Pénama Province, Vanuatu"},
 "LGI"=>
  {:iata=>"LGI",
   :name=>"Deadman's Cay Airport",
   :icao=>"MYLD",
   :city=>"Deadman's Cay",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Deadman's Cay, Long Island, Bahamas"},
 "LYB"=>
  {:iata=>"LYB",
   :name=>"Edward Bodden Airfield",
   :icao=>"MWCL",
   :city=>"Little Cayman",
   :country=>'Cayman Islands', :country_code=>'KY',
   :location=>"Little Cayman, Cayman Islands"},
 "LCL"=>
  {:iata=>"LCL",
   :name=>"La Coloma Airport",
   :icao=>"MULM",
   :city=>"La Coloma",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"La Coloma, Cuba"},
 "LRM"=>
  {:iata=>"LRM",
   :name=>
    "La Romana International Airport (Casa de Campo International Airport)",
   :icao=>"MDLR",
   :city=>"La Romana",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"La Romana, Dominican Republic"},
 "LSS"=>
  {:iata=>"LSS",
   :name=>"Terre-de-Haut Airport",
   :icao=>"TFFS",
   :city=>"Terre-de-Haut Island",
   :country=>'Guadeloupe', :country_code=>'GP',
   :location=>"Terre-de-Haut Island, Les Saintes, Guadeloupe"},
 "LOO"=>
  {:iata=>"LOO",
   :name=>"Laghouat Airport (L'Mekrareg Airport)",
   :icao=>"DAUL",
   :city=>"Laghouat",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Laghouat, Algeria"},
 "LAD"=>
  {:iata=>"LAD",
   :name=>"Quatro de Fevereiro Airport",
   :icao=>"FNLU",
   :city=>"Luanda",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Luanda, Angola"},
 "LUO"=>
  {:iata=>"LUO",
   :name=>"Luena Airport",
   :icao=>"FNUE",
   :city=>"Luena",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Luena, Moxico Province, Angola"},
 "LBZ"=>
  {:iata=>"LBZ",
   :name=>"Lukapa Airport",
   :icao=>"FNLK",
   :city=>"Lukapa",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Lukapa, Angola"},
 "LZM"=>
  {:iata=>"LZM",
   :name=>"Luzamba Airport",
   :icao=>"FNLZ",
   :city=>"Luzamba",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Luzamba, Angola"},
 "LOQ"=>
  {:iata=>"LOQ",
   :name=>"Lobatse Airport",
   :icao=>"FBLO",
   :city=>"Lobatse",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Lobatse, Botswana"},
 "LTC"=>
  {:iata=>"LTC",
   :name=>"Laï Airport",
   :icao=>"FTTH",
   :city=>"Laï",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Laï, Chad"},
 "LCO"=>
  {:iata=>"LCO",
   :name=>"Lague Airport",
   :icao=>"FCBL",
   :city=>"Lague",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Lague, Republic of Congo"},
 "LKC"=>
  {:iata=>"LKC",
   :name=>"Lekana Airport",
   :icao=>"",
   :city=>"Lekana",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Lekana, Republic of Congo"},
 "LKT"=>
  {:iata=>"LKT",
   :name=>"Lakota Airport",
   :icao=>"",
   :city=>"Lakota",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Lakota, Côte d'Ivoire"},
 "LLI"=>
  {:iata=>"LLI",
   :name=>"Lalibela Airport",
   :icao=>"HALL",
   :city=>"Lalibela",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Lalibela, Ethiopia"},
 "LFO"=>
  {:iata=>"LFO",
   :name=>"Kelafo Airport (Kelafo Airport)",
   :icao=>"HAKL",
   :city=>"Kelafo",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Kelafo, Ethiopia"},
 "LBV"=>
  {:iata=>"LBV",
   :name=>"Libreville International Airport",
   :icao=>"FOOL",
   :city=>"Libreville",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Libreville, Gabon"},
 "LBQ"=>
  {:iata=>"LBQ",
   :name=>"Lambaréné Airport",
   :icao=>"FOGR",
   :city=>"Lambaréné",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Lambaréné, Gabon"},
 "LTL"=>
  {:iata=>"LTL",
   :name=>"Lastourville Airport",
   :icao=>"FOOR",
   :city=>"Lastourville",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Lastourville, Gabon"},
 "LEO"=>
  {:iata=>"LEO",
   :name=>"Lekoni Airport",
   :icao=>"",
   :city=>"Lekoni",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Lekoni, Gabon"},
 "LEK"=>
  {:iata=>"LEK",
   :name=>"Tata Airport (Labé Airport)",
   :icao=>"GULB",
   :city=>"Labé",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Labé, Guinea"},
 "LAU"=>
  {:iata=>"LAU",
   :name=>"Mwana Airport",
   :icao=>"HKLU",
   :city=>"Lamu",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Lamu, Kenya"},
 "LOK"=>
  {:iata=>"LOK",
   :name=>"Lodwar Airport",
   :icao=>"HKLO",
   :city=>"Lodwar",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Lodwar, Kenya"},
 "LKG"=>
  {:iata=>"LKG",
   :name=>"Lokichoggio Airport",
   :icao=>"HKLK",
   :city=>"Lokichoggio",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Lokichoggio, Kenya"},
 "LBN"=>
  {:iata=>"LBN",
   :name=>"Lake Baringo Airport",
   :icao=>"",
   :city=>"Lake Baringo",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Lake Baringo, Kenya"},
 "LKU"=>
  {:iata=>"LKU",
   :name=>"Lake Rudolf Airport",
   :icao=>"",
   :city=>"Lake Rudolf",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Lake Rudolf, Kenya"},
 "LBK"=>
  {:iata=>"LBK",
   :name=>"Liboi Airport",
   :icao=>"",
   :city=>"Liboi",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Liboi, Kenya"},
 "LOY"=>
  {:iata=>"LOY",
   :name=>"Loyangalani Airport",
   :icao=>"HKLY",
   :city=>"Loyangalani",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Loyangalani, Kenya"},
 "LEF"=>
  {:iata=>"LEF",
   :name=>"Lebakeng Airport",
   :icao=>"FXLK",
   :city=>"Lebakeng",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Lebakeng, Lesotho"},
 "LRB"=>
  {:iata=>"LRB",
   :name=>"Leribe Airport",
   :icao=>"FXLR",
   :city=>"Leribe",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Leribe, Lesotho"},
 "LES"=>
  {:iata=>"LES",
   :name=>"Lesobeng Airport",
   :icao=>"FXLS",
   :city=>"Lesobeng",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Lesobeng, Lesotho"},
 "LAQ"=>
  {:iata=>"LAQ",
   :name=>"La Braq Airport",
   :icao=>"HLLQ",
   :city=>"Bayda",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Bayda, Libya"},
 "LTD"=>
  {:iata=>"LTD",
   :name=>"Ghadames Airport",
   :icao=>"HLTD",
   :city=>"Ghadames",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Ghadames, Libya"},
 "LMQ"=>
  {:iata=>"LMQ",
   :name=>"Marsa Brega Airport",
   :icao=>"HLMB",
   :city=>"Brega",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Brega, Libya"},
 "LIX"=>
  {:iata=>"LIX",
   :name=>"Likoma Island Airport (Likoma Airport)",
   :icao=>"FWLK",
   :city=>"Likoma Island",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Likoma Island, Malawi"},
 "LLW"=>
  {:iata=>"LLW",
   :name=>"Lilongwe International Airport (Kumuzu Airport)",
   :icao=>"FWKI",
   :city=>"Lilongwe",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Lilongwe, Malawi"},
 "LMB"=>
  {:iata=>"LMB",
   :name=>"Salima Airport",
   :icao=>"FWSM",
   :city=>"Salima",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Salima, Malawi"},
 "LEG"=>
  {:iata=>"LEG",
   :name=>"Aleg Airport",
   :icao=>"",
   :city=>"Aleg",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Aleg, Mauritania"},
 "LBM"=>
  {:iata=>"LBM",
   :name=>"Luabo Airport",
   :icao=>"",
   :city=>"Luabo",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Luabo, Mozambique"},
 "LFB"=>
  {:iata=>"LFB",
   :name=>"Lumbo Airport",
   :city=>"Lumbo",
   :icao=>"FQLU",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Lumbo, Mozambique"},
 "LMZ"=>
  {:iata=>"LMZ",
   :name=>"Palma Airport",
   :icao=>"",
   :city=>"Palma",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Palma, Mozambique"},
 "LUD"=>
  {:iata=>"LUD",
   :name=>"Luderitz Airport (Diaz Point Airport)",
   :icao=>"FYLZ",
   :city=>"Luderitz",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Luderitz, Namibia"},
 "LHU"=>
  {:iata=>"LHU",
   :name=>"Lianshulu Airport",
   :city=>"Caprivi",
   :icao=>"KLHU",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Caprivi, Namibia"},
 "LOS"=>
  {:iata=>"LOS",
   :name=>"Murtala Muhammed International Airport",
   :icao=>"DNMM",
   :city=>"Lagos",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Lagos, Nigeria"},
 "LKR"=>
  {:iata=>"LKR",
   :name=>"Las Khoreh Airport",
   :icao=>"",
   :city=>"Las Khoreh",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Las Khoreh, Somalia"},
 "LGX"=>
  {:iata=>"LGX",
   :name=>"Lugh Ganane Airport",
   :icao=>"HCMJ",
   :city=>"Lugh Ganane",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Lugh Ganane, Somalia"},
 "LUJ"=>
  {:iata=>"LUJ",
   :name=>"Lusikisiki Airport",
   :city=>"Lusikisiki",
   :icao=>"FALK",
   :country=>'Africa', :country_code=>'',
   :location=>"Lusikisiki, Africa"},
 "LAY"=>
  {:iata=>"LAY",
   :name=>"Ladysmith Airport",
   :icao=>"FALY",
   :city=>"Ladysmith",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Ladysmith, KwaZulu-Natal, South Africa"},
 "LMR"=>
  {:iata=>"LMR",
   :name=>"Finsch Mine Airport",
   :icao=>"FALC",
   :city=>"Lime Acres",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Lime Acres, South Africa"},
 "LDZ"=>
  {:iata=>"LDZ",
   :name=>"Londolozi Airport",
   :icao=>"",
   :city=>"Londolozi",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Londolozi, South Africa"},
 "LCD"=>
  {:iata=>"LCD",
   :name=>"Louis Trichardt Airport",
   :icao=>"FALO",
   :city=>"Louis Trichardt",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Louis Trichardt, South Africa"},
 "LLE"=>
  {:iata=>"LLE",
   :name=>"Malelane Airport",
   :icao=>"FAMN",
   :city=>"Malelane",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Malelane, South Africa"},
 "LTA"=>
  {:iata=>"LTA",
   :name=>"Tzaneen Airport (Letaba Airport)",
   :icao=>"FATZ",
   :city=>"Tzaneen",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Tzaneen, South Africa"},
 "LIQ"=>
  {:iata=>"LIQ",
   :name=>"Lisala Airport",
   :icao=>"FZGA",
   :city=>"Lisala",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Lisala, Democratic Republic of the Congo"},
 "LJA"=>
  {:iata=>"LJA",
   :name=>"Lodja Airport",
   :icao=>"FZVA",
   :city=>"Lodja",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Lodja, Democratic Republic of the Congo"},
 "LUS"=>
  {:iata=>"LUS",
   :name=>"Lusanga Airport",
   :icao=>"FZCE",
   :city=>"Lusanga",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Lusanga, Democratic Republic of the Congo"},
 "LIE"=>
  {:iata=>"LIE",
   :name=>"Libenge Airport",
   :icao=>"FZFA",
   :city=>"Libenge",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Libenge, Democratic Republic of the Congo"},
 "LZA"=>
  {:iata=>"LZA",
   :name=>"Luiza Airport",
   :icao=>"FZUG",
   :city=>"Luiza",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Luiza, Democratic Republic of the Congo"},
 "LZI"=>
  {:iata=>"LZI",
   :name=>"Luozi Airport",
   :icao=>"FZAL",
   :city=>"Luozi",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Luozi, Democratic Republic of the Congo"},
 "LBO"=>
  {:iata=>"LBO",
   :name=>"Lusambo Airport",
   :icao=>"FZVI",
   :city=>"Lusambo",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Lusambo, Democratic Republic of the Congo"},
 "LFW"=>
  {:iata=>"LFW",
   :name=>"Lomé-Tokoin Airport",
   :icao=>"DXXX",
   :city=>"Lomé",
   :country=>'Togo', :country_code=>'TG',
   :location=>"Lomé, Togo"},
 "LRL"=>
  {:iata=>"LRL",
   :name=>"Niamtougou International Airport",
   :icao=>"DXNG",
   :city=>"Niamtougou",
   :country=>'Togo', :country_code=>'TG',
   :location=>"Niamtougou, Togo"},
 "LKY"=>
  {:iata=>"LKY",
   :name=>"Lake Manyara Airport",
   :icao=>"HTLM",
   :city=>"Lake Manyara",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Lake Manyara, Tanzania"},
 "LDI"=>
  {:iata=>"LDI",
   :name=>"Kikwetu Airport",
   :icao=>"HTLI",
   :city=>"Lindi",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Lindi, Tanzania"},
 "LVI"=>
  {:iata=>"LVI",
   :name=>"Livingstone Airport",
   :icao=>"FLLI",
   :city=>"Livingstone",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Livingstone, Zambia"},
 "LUN"=>
  {:iata=>"LUN",
   :name=>"Lusaka International Airport",
   :icao=>"FLLS",
   :city=>"Lusaka",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Lusaka, Zambia"},
 "LXU"=>
  {:iata=>"LXU",
   :name=>"Lukulu Airport",
   :icao=>"FLLK",
   :city=>"Lukulu",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Lukulu, Zambia"},
 "LNZ"=>
  {:iata=>"LNZ",
   :name=>"Linz Airport (Blue Danube Airport)",
   :icao=>"LOWL",
   :city=>"Linz",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Linz, Austria"},
 "LGG"=>
  {:iata=>"LGG",
   :name=>"Liège Airport (Bierset Airport)",
   :icao=>"EBLG",
   :city=>"Liège",
   :country=>'Belgium', :country_code=>'BE',
   :location=>"Liège, Wallonia, Belgium"},
 "LSZ"=>
  {:iata=>"LSZ",
   :name=>"Mali Losinj Airport",
   :icao=>"LDLO",
   :city=>"Mali Lošinj",
   :country=>'Croatia', :country_code=>'HR',
   :location=>"Mali Lošinj, Lošinj, Croatia"},
 "LCA"=>
  {:iata=>"LCA",
   :name=>"Larnaca International Airport",
   :icao=>"LCLK",
   :city=>"Larnaca",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Larnaca, Cyprus"},
 "LPP"=>
  {:iata=>"LPP",
   :name=>"Lappeenranta Airport",
   :icao=>"EFLP",
   :city=>"Lappeenranta",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Lappeenranta, Finland"},
 "LYS"=>
  {:iata=>"LYS",
   :name=>"Lyon-Saint Exupéry Airport (formerly Satolas Airport)",
   :icao=>"LFLL",
   :city=>"Lyon",
   :country=>'France', :country_code=>'FR',
   :location=>"Lyon, France"},
 "LRH"=>
  {:iata=>"LRH",
   :name=>"La Rochelle - Île de Ré Airport",
   :icao=>"LFBH",
   :city=>"La Rochelle / Île de Ré",
   :country=>'France', :country_code=>'FR',
   :location=>"La Rochelle / Île de Ré, Charente-Maritime, France"},
 "LAI"=>
  {:iata=>"LAI",
   :name=>"Lannion - Côte de Granit Airport",
   :icao=>"LFRO",
   :city=>"Lannion",
   :country=>'France', :country_code=>'FR',
   :location=>"Lannion, France"},
 "LEH"=>
  {:iata=>"LEH",
   :name=>"Le Havre Octeville Airport",
   :icao=>"LFOH",
   :city=>"Le Havre",
   :country=>'France', :country_code=>'FR',
   :location=>"Le Havre, France"},
 "LPY"=>
  {:iata=>"LPY",
   :name=>"Loudes Airport",
   :icao=>"LFHP",
   :city=>"Le Puy-en-Velay / Loudes",
   :country=>'France', :country_code=>'FR',
   :location=>"Le Puy-en-Velay / Loudes, Haute-Loire, France"},
 "LTQ"=>
  {:iata=>"LTQ",
   :name=>"Le Touquet-Paris-Plage Airport",
   :icao=>"LFAT",
   :city=>"Le Touquet-Paris-Plage",
   :country=>'France', :country_code=>'FR',
   :location=>"Le Touquet-Paris-Plage, France"},
 "LIL"=>
  {:iata=>"LIL",
   :name=>"Lille Lesquin International Airport",
   :icao=>"LFQQ",
   :city=>"Lille",
   :country=>'France', :country_code=>'FR',
   :location=>"Lille, France"},
 "LIG"=>
  {:iata=>"LIG",
   :name=>"Bellegarde Airport",
   :icao=>"LFBL",
   :city=>"Limoges",
   :country=>'France', :country_code=>'FR',
   :location=>"Limoges, France"},
 "LRT"=>
  {:iata=>"LRT",
   :name=>"Lorient South Brittany Airport",
   :icao=>"LFRH",
   :city=>"Lorient",
   :country=>'France', :country_code=>'FR',
   :location=>"Lorient, France"},
 "LDE"=>
  {:iata=>"LDE",
   :name=>"Tarbes - Lourdes Pyrenees Airport",
   :icao=>"LFBT",
   :city=>"Lourdes",
   :country=>'France', :country_code=>'FR',
   :location=>"Lourdes, France"},
 "LBG"=>
  {:iata=>"LBG",
   :name=>"Paris - Le Bourget Airport",
   :icao=>"LFPB",
   :city=>"Le Bourget (near Paris)",
   :country=>'France', :country_code=>'FR',
   :location=>"Le Bourget (near Paris), France"},
 "LTT"=>
  {:iata=>"LTT",
   :name=>"La Môle - Saint-Tropez Airport",
   :icao=>"LFTZ",
   :city=>"La Môle / Saint-Tropez",
   :country=>'France', :country_code=>'FR',
   :location=>"La Môle / Saint-Tropez, France"},
 "LBI"=>
  {:iata=>"LBI",
   :name=>"Le Sequestre Airport",
   :icao=>"LFCI",
   :city=>"Albi",
   :country=>'France', :country_code=>'FR',
   :location=>"Albi, France"},
 "LBY"=>
  {:iata=>"LBY",
   :name=>"La Baule-Escoublac Airport (Montoir Airport)",
   :icao=>"LFRE",
   :city=>"La Baule-Escoublac",
   :country=>'France', :country_code=>'FR',
   :location=>"La Baule-Escoublac, France"},
 "LDV"=>
  {:iata=>"LDV",
   :name=>"Landivisiau Airport",
   :icao=>"LFRJ",
   :city=>"Landivisiau",
   :country=>'France', :country_code=>'FR',
   :location=>"Landivisiau, France"},
 "LVA"=>
  {:iata=>"LVA",
   :name=>"Laval Entrammes Airport",
   :icao=>"LFOV",
   :city=>"Laval",
   :country=>'France', :country_code=>'FR',
   :location=>"Laval, France"},
 "LME"=>
  {:iata=>"LME",
   :name=>"Le Mans Arnage Airport",
   :icao=>"LFRM",
   :city=>"Le Mans",
   :country=>'France', :country_code=>'FR',
   :location=>"Le Mans, France"},
 "LSO"=>
  {:iata=>"LSO",
   :name=>"Talmont Airport",
   :icao=>"LFOO",
   :city=>"Les Sables d'Olonne",
   :country=>'France', :country_code=>'FR',
   :location=>"Les Sables d'Olonne, France"},
 "LYN"=>
  {:iata=>"LYN",
   :name=>"Lyon Bron Airport",
   :icao=>"LFLY",
   :city=>"Lyon",
   :country=>'France', :country_code=>'FR',
   :location=>"Lyon, France"},
 "LBC"=>
  {:iata=>"LBC",
   :name=>"Lübeck Airport (Blankensee Airport)",
   :icao=>"EDHL",
   :city=>"Lübeck (near Hamburg)",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Lübeck (near Hamburg), Schleswig-Holstein, Germany"},
 "LHA"=>
  {:iata=>"LHA",
   :name=>"Black Forest Airport (Lahr Airport)",
   :icao=>"EDTL",
   :city=>"Lahr",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Lahr, Baden-Württemberg, Germany"},
 "LEJ"=>
  {:iata=>"LEJ",
   :name=>"Leipzig/Halle Airport",
   :icao=>"EDDP",
   :city=>"Leipzig",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Leipzig, Germany"},
 "LGO"=>
  {:iata=>"LGO",
   :name=>"Langeoog Airport",
   :icao=>"EDWL",
   :city=>"Langeoog",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Langeoog, Lower Saxony, Germany"},
 "LRS"=>
  {:iata=>"LRS",
   :name=>"Leros Island National Airport",
   :icao=>"LGLE",
   :city=>"Leros",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Leros, Greece"},
 "LXS"=>
  {:iata=>"LXS",
   :name=>"Lemnos Airport",
   :icao=>"LGLM",
   :city=>"Lemnos",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Lemnos, Greece"},
 "LRA"=>
  {:iata=>"LRA",
   :name=>"Larisa Airport",
   :icao=>"LGLR",
   :city=>"Larisa",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Larisa, Greece"},
 "LTR"=>
  {:iata=>"LTR",
   :name=>"Letterkenny Airport",
   :icao=>"EILT",
   :city=>"Letterkenny",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Letterkenny, Ireland"},
 "LIN"=>
  {:iata=>"LIN",
   :name=>"Linate Airport",
   :icao=>"LIML",
   :city=>"Milan",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Milan, Italy"},
 "LMP"=>
  {:iata=>"LMP",
   :name=>"Lampedusa Airport",
   :icao=>"LICD",
   :city=>"Lampedusa",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Lampedusa, Italy"},
 "LCC"=>
  {:iata=>"LCC",
   :name=>"Lecce Galatina Airport",
   :icao=>"LIBN",
   :city=>"Lecce",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Lecce, Italy"},
 "LIU"=>
  {:iata=>"LIU",
   :name=>"Linosa Heliport",
   :icao=>"",
   :city=>"Linosa",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Linosa, Linosa Island, Italy"},
 "LCV"=>
  {:iata=>"LCV",
   :name=>"Tassignano Airport",
   :icao=>"LIQL",
   :city=>"Lucca",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Lucca, Italy"},
 "LPX"=>
  {:iata=>"LPX",
   :name=>"Liepāja International Airport",
   :icao=>"EVLA",
   :city=>"Liepāja",
   :country=>'Latvia', :country_code=>'LV',
   :location=>"Liepāja, Latvia"},
 "LUX"=>
  {:iata=>"LUX",
   :name=>"Luxembourg Findel Airport",
   :icao=>"ELLX",
   :city=>"Luxembourg-Findel",
   :country=>'Luxembourg', :country_code=>'LU',
   :location=>"Luxembourg-Findel, Luxembourg"},
 "LWR"=>
  {:iata=>"LWR",
   :name=>"Leeuwarden Airport",
   :icao=>"EHLW",
   :city=>"Leeuwarden",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Leeuwarden, Netherlands"},
 "LID"=>
  {:iata=>"LID",
   :name=>"Valkenburg Airport",
   :icao=>"EHVB",
   :city=>"Leiden",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Leiden, Netherlands"},
 "LEY"=>
  {:iata=>"LEY",
   :name=>"Lelystad Airport",
   :icao=>"EHLE",
   :city=>"Lelystad",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Lelystad, Netherlands"},
 "LKL"=>
  {:iata=>"LKL",
   :name=>"Lakselv Airport, Banak",
   :icao=>"ENNA",
   :city=>"Lakselv",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Lakselv, Norway"},
 "LKN"=>
  {:iata=>"LKN",
   :name=>"Leknes Airport",
   :icao=>"ENLK",
   :city=>"Leknes",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Leknes, Norway"},
 "LCJ"=>
  {:iata=>"LCJ",
   :name=>"Łódź Władysław Reymont Airport",
   :icao=>"EPLL",
   :city=>"Łódź",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Łódź, Poland"},
 "LUZ"=>
  {:iata=>"LUZ",
   :name=>"Lublin Airport",
   :icao=>"EPLB",
   :city=>"Lublin",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Lublin, Poland"},
 "LIS"=>
  {:iata=>"LIS",
   :name=>"Lisbon Portela Airport",
   :icao=>"LPPT",
   :city=>"Lisbon",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Lisbon, Portugal"},
 "LED"=>
  {:iata=>"LED",
   :name=>"Pulkovo Airport",
   :icao=>"ULLI",
   :city=>"Saint Petersburg",
   :country=>"Russia (formerly Leningrad between 1924 and 1991)",
   :country_code=>"RU",
   :location=>
    "Saint Petersburg, Russia (formerly Leningrad between 1924 and 1991)"},
 "LDG"=>
  {:iata=>"LDG",
   :name=>"Leshukonskoye Airport",
   :icao=>"ULAL",
   :city=>"Leshukonskoye",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Leshukonskoye, Russia"},
 "LPK"=>
  {:iata=>"LPK",
   :name=>"Lipetsk Airport",
   :icao=>"UUOL",
   :city=>"Lipetsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Lipetsk, Russia"},
 "LNX"=>
  {:iata=>"LNX",
   :name=>"Smolensk Airport",
   :icao=>"",
   :city=>"Smolensk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Smolensk, Russia"},
 "LUE"=>
  {:iata=>"LUE",
   :name=>"Lučenec Airport",
   :icao=>"LZLU",
   :city=>"Lučenec",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Lučenec, Slovakia"},
 "LJU"=>
  {:iata=>"LJU",
   :name=>"Ljubljana Jože Pučnik Airport (Brnik Airport)",
   :icao=>"LJLJ",
   :city=>"Ljubljana",
   :country=>'Slovenia', :country_code=>'SI',
   :location=>"Ljubljana, Slovenia"},
 "LPA"=>
  {:iata=>"LPA",
   :name=>"Gran Canaria International Airport",
   :icao=>"GCLP",
   :city=>"Las Palmas",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Las Palmas, Canary Islands, Spain"},
 "LEI"=>
  {:iata=>"LEI",
   :name=>"Almería International Airport",
   :icao=>"LEAM",
   :city=>"Almería",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Almería, Spain"},
 "LCG"=>
  {:iata=>"LCG",
   :name=>"A Coruña Airport",
   :icao=>"LECO",
   :city=>"A Coruña",
   :country=>'Spain', :country_code=>'ES',
   :location=>"A Coruña, Spain"},
 "LEN"=>
  {:iata=>"LEN",
   :name=>"León Airport",
   :icao=>"LELN",
   :city=>"León",
   :country=>'Spain', :country_code=>'ES',
   :location=>"León, Spain"},
 "LUY"=>
  {:iata=>"LUY",
   :name=>"Lugo Railway Station",
   :icao=>"",
   :city=>"Lugo",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Lugo, Spain"},
 "LEU"=>
  {:iata=>"LEU",
   :name=>"La Seu d'Urgell Airport",
   :icao=>"LESU",
   :city=>"La Seu d'Urgell",
   :country=>'Spain', :country_code=>'ES',
   :location=>"La Seu d'Urgell, Spain"},
 "LYR"=>
  {:iata=>"LYR",
   :name=>"Svalbard Airport, Longyear",
   :icao=>"ENSB",
   :city=>"Longyearbyen",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Longyearbyen, Svalbard, Norway"},
 "LPI"=>
  {:iata=>"LPI",
   :name=>"SAAB Airport",
   :icao=>"ESSL",
   :city=>"Linköping",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Linköping, Sweden"},
 "LLA"=>
  {:iata=>"LLA",
   :name=>"Luleå Airport (Kallax Airport)",
   :icao=>"ESPA",
   :city=>"Luleå",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Luleå, Sweden"},
 "LYC"=>
  {:iata=>"LYC",
   :name=>"Lycksele Airport",
   :icao=>"ESNL",
   :city=>"Lycksele",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Lycksele, Sweden"},
 "LDK"=>
  {:iata=>"LDK",
   :name=>"Lidköping-Hovby Airport",
   :icao=>"ESGL",
   :city=>"Lidköping",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Lidköping, Sweden"},
 "LUG"=>
  {:iata=>"LUG",
   :name=>"Lugano Airport",
   :icao=>"LSZA",
   :city=>"Lugano",
   :country=>'Switzerland', :country_code=>'CH',
   :location=>"Lugano, Agno, Switzerland"},
 "LWO"=>
  {:iata=>"LWO",
   :name=>"Lviv Danylo Halytskyi International Airport",
   :icao=>"UKLL",
   :city=>"Lviv",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Lviv, Ukraine"},
 "LCY"=>
  {:iata=>"LCY",
   :name=>"London City Airport",
   :icao=>"EGLC",
   :city=>"London",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"London, England, United Kingdom"},
 "LGW"=>
  {:iata=>"LGW",
   :name=>"London Gatwick Airport",
   :icao=>"EGKK",
   :city=>"London",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"London, England, United Kingdom"},
 "LHR"=>
  {:iata=>"LHR",
   :name=>"London Heathrow Airport",
   :icao=>"EGLL",
   :city=>"London",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"London, England, United Kingdom"},
 "LTN"=>
  {:iata=>"LTN",
   :name=>"London Luton Airport",
   :icao=>"EGGW",
   :city=>"Luton (near London)",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Luton (near London), England, United Kingdom"},
 "LDY"=>
  {:iata=>"LDY",
   :name=>"City of Derry Airport (Londonderry Eglinton Airport)",
   :icao=>"EGAE",
   :city=>"Derry",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Derry, Northern Ireland, United Kingdom"},
 "LEQ"=>
  {:iata=>"LEQ",
   :name=>"Land's End Airport",
   :icao=>"EGHC",
   :city=>"Land's End",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Land's End, Cornwall, England, United Kingdom"},
 "LBA"=>
  {:iata=>"LBA",
   :name=>"Leeds Bradford International Airport",
   :icao=>"EGNM",
   :city=>"Leeds / Bradford",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Leeds / Bradford, West Yorkshire, England, United Kingdom"},
 "LPL"=>
  {:iata=>"LPL",
   :name=>"Liverpool John Lennon Airport",
   :icao=>"EGGP",
   :city=>"Liverpool",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Liverpool, England, United Kingdom"},
 "LYX"=>
  {:iata=>"LYX",
   :name=>"London Ashford International Airport (Ferryfield)",
   :icao=>"EGMD",
   :city=>"Lydd",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lydd, England, United Kingdom"},
 "LSI"=>
  {:iata=>"LSI",
   :name=>"Sumburgh Airport",
   :icao=>"EGPB",
   :city=>"Shetland",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Shetland, Scotland, United Kingdom"},
 "LKZ"=>
  {:iata=>"LKZ",
   :name=>"RAF Lakenheath",
   :icao=>"EGUL",
   :city=>"Lakenheath",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lakenheath, England, United Kingdom"},
 "LPH"=>
  {:iata=>"LPH",
   :name=>"Lochgilphead Heliport",
   :icao=>"",
   :city=>"Lochgilphead",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lochgilphead, Scotland, United Kingdom"},
 "LMO"=>
  {:iata=>"LMO",
   :name=>"RAF Lossiemouth",
   :icao=>"EGQS",
   :city=>"Lossiemouth",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lossiemouth, Scotland, United Kingdom"},
 "LYE"=>
  {:iata=>"LYE",
   :name=>"RAF Lyneham",
   :icao=>"EGDL",
   :city=>"Wiltshire",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Wiltshire, England, United Kingdom"},
 "LWK"=>
  {:iata=>"LWK",
   :name=>"Tingwall Airport",
   :icao=>"EGET",
   :city=>"Lerwick",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lerwick, Scotland, United Kingdom"},
 "LQN"=>
  {:iata=>"LQN",
   :name=>"Qala i Naw Airport",
   :icao=>"OAQN",
   :city=>"Qala i Naw",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Qala i Naw, Afghanistan"},
 "LWN"=>
  {:iata=>"LWN",
   :name=>"Shirak Airport",
   :icao=>"UDSG",
   :city=>"Gyumri",
   :country=>'Armenia', :country_code=>'AM',
   :location=>"Gyumri, Armenia"},
 "LLK"=>
  {:iata=>"LLK",
   :name=>"Lankaran International Airport",
   :icao=>"UBBL",
   :city=>"Lankaran",
   :country=>'Azerbaijan', :country_code=>'AZ',
   :location=>"Lankaran, Azerbaijan"},
 "LHW"=>
  {:iata=>"LHW",
   :name=>"Lanzhou Zhongchuan Airport",
   :icao=>"ZLLL",
   :city=>"Lanzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Lanzhou, Gansu, China"},
 "LXA"=>
  {:iata=>"LXA",
   :name=>"Lhasa Gonggar Airport",
   :icao=>"ZULS",
   :city=>"Lhasa",
   :country=>'China', :country_code=>'CN',
   :location=>"Lhasa, Tibet Autonomous Region, China"},
 "LYG"=>
  {:iata=>"LYG",
   :name=>"Lianyungang Baitabu Airport",
   :icao=>"ZSLG",
   :city=>"Lianyungang",
   :country=>'China', :country_code=>'CN',
   :location=>"Lianyungang, Jiangsu, China"},
 "LLB"=>
  {:iata=>"LLB",
   :name=>"Libo Airport",
   :icao=>"ZULB",
   :city=>"Libo County",
   :country=>'China', :country_code=>'CN',
   :location=>"Libo County, Guizhou, China"},
 "LJG"=>
  {:iata=>"LJG",
   :name=>"Lijiang Sanyi Airport",
   :icao=>"ZPLJ",
   :city=>"Lijiang City",
   :country=>'China', :country_code=>'CN',
   :location=>"Lijiang City, Yunnan, China"},
 "LNJ"=>
  {:iata=>"LNJ",
   :name=>"Lincang Airport",
   :icao=>"ZPLC",
   :city=>"Lincang",
   :country=>'China', :country_code=>'CN',
   :location=>"Lincang, Yunnan, China"},
 "LYI"=>
  {:iata=>"LYI",
   :name=>"Linyi Shubuling Airport",
   :icao=>"ZSLY",
   :city=>"Linyi",
   :country=>'China', :country_code=>'CN',
   :location=>"Linyi, Shandong, China"},
 "LZH"=>
  {:iata=>"LZH",
   :name=>"Liuzhou Bailian Airport",
   :icao=>"ZGZH",
   :city=>"Liuzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Liuzhou, Guangxi, China"},
 "LCX"=>
  {:iata=>"LCX",
   :name=>"Longyan Guanzhishan Airport",
   :icao=>"ZSLO",
   :city=>"Longyan",
   :country=>'China', :country_code=>'CN',
   :location=>"Longyan, Fujian, China"},
 "LLV"=>
  {:iata=>"LLV",
   :name=>"Lüliang Airport",
   :icao=>"",
   :city=>"Lüliang",
   :country=>'China', :country_code=>'CN',
   :location=>"Lüliang, Shanxi, China"},
 "LYA"=>
  {:iata=>"LYA",
   :name=>"Luoyang Beijiao Airport",
   :icao=>"ZHLY",
   :city=>"Luoyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Luoyang, Henan, China"},
 "LZO"=>
  {:iata=>"LZO",
   :name=>"Luzhou Lantian Airport",
   :icao=>"ZULZ",
   :city=>"Luzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Luzhou, Sichuan, China"},
 "LUM"=>
  {:iata=>"LUM",
   :name=>"Dehong Mangshi Airport",
   :icao=>"ZPMS",
   :city=>"Mang City",
   :country=>'China', :country_code=>'CN',
   :location=>"Mang City, Yunnan, China"},
 "LZN"=>
  {:iata=>"LZN",
   :name=>"Matsu Nangan Airport",
   :icao=>"RCFG",
   :city=>"Nangan",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Nangan, Matsu Islands, Taiwan"},
 "LZY"=>
  {:iata=>"LZY",
   :name=>"Nyingchi Airport",
   :icao=>"ZUNZ",
   :city=>"Nyingchi",
   :country=>'China', :country_code=>'CN',
   :location=>"Nyingchi, Tibet Autonomous Region, China"},
 "LDS"=>
  {:iata=>"LDS",
   :name=>"Yichun Shi Airport",
   :city=>"Yichun",
   :icao=>"ZYLD",
   :country=>'China', :country_code=>'CN',
   :location=>"Yichun, China"},
 "LLF"=>
  {:iata=>"LLF",
   :name=>"Yongzhou Lingling Airport",
   :icao=>"ZGLG",
   :city=>"Yongzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Yongzhou, Hunan, China"},
 "LHK"=>
  {:iata=>"LHK",
   :name=>"Guanghua Airport",
   :icao=>"ZHGH",
   :city=>"Guanghua",
   :country=>'China', :country_code=>'CN',
   :location=>"Guanghua, Hubei, China"},
 "LZD"=>
  {:iata=>"LZD",
   :name=>"Lanzhou East Airport",
   :icao=>"ZLLD",
   :city=>"Lanzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Lanzhou, Gansu, China"},
 "LIA"=>
  {:iata=>"LIA",
   :name=>"Liangping Airport",
   :icao=>"ZULP",
   :city=>"Liangping",
   :country=>'China', :country_code=>'CN',
   :location=>"Liangping, Chongqing, China"},
 "LXI"=>
  {:iata=>"LXI",
   :name=>"Linxi Airport",
   :icao=>"ZBLX",
   :city=>"Linxi",
   :country=>'China', :country_code=>'CN',
   :location=>"Linxi, China"},
 "LTU"=>
  {:iata=>"LTU",
   :name=>"Latur Airport",
   :icao=>"VALT",
   :city=>"Latur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Latur, Maharashtra, India"},
 "LKO"=>
  {:iata=>"LKO",
   :name=>"Amausi Airport",
   :icao=>"VILK",
   :city=>"Lucknow",
   :country=>"India",
:country_code=>"IN",
   :location=>"Lucknow, India"},
 "LUH"=>
  {:iata=>"LUH",
   :name=>"Ludhiana Airport",
   :icao=>"VILD",
   :city=>"Ludhiana",
   :country=>"India",
:country_code=>"IN",
   :location=>"Ludhiana, India"},
 "LDA"=>
  {:iata=>"LDA",
   :name=>"Malda Airport",
   :icao=>"VEMH",
   :city=>"Malda",
   :country=>"India",
:country_code=>"IN",
   :location=>"Malda, India"},
 "LBJ"=>
  {:iata=>"LBJ",
   :name=>"Komodo Airport (Mutiara II Airport)",
   :icao=>"WATO",
   :city=>"Labuan Bajo",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Labuan Bajo, Flores Island, Indonesia"},
 "LUV"=>
  {:iata=>"LUV",
   :name=>"Dumatubin Airport",
   :icao=>"WAPL",
   :city=>"Langgur",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Langgur, Kai Islands, Indonesia"},
 "LKA"=>
  {:iata=>"LKA",
   :name=>"Gewayenta Airport",
   :icao=>"WRKL",
   :city=>"Larantuka",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Larantuka, Indonesia"},
 "LWE"=>
  {:iata=>"LWE",
   :name=>"Wonopito Airport",
   :icao=>"WATW",
   :city=>"Lewoleba",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Lewoleba, Indonesia"},
 "LSW"=>
  {:iata=>"LSW",
   :name=>"Malikus Saleh Airport",
   :icao=>"WITM",
   :city=>"Lhoksumawe",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Lhoksumawe, Sumatra, Indonesia"},
 "LPU"=>
  {:iata=>"LPU",
   :name=>"Long Apung Airport",
   :icao=>"WRLP",
   :city=>"Long Apung",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Long Apung, Indonesia"},
 "LUW"=>
  {:iata=>"LUW",
   :name=>"Syukuran Aminuddin Amir Airport",
   :icao=>"WAMW",
   :city=>"Luwuk",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Luwuk, Central Sulawesi, Indonesia"},
 "LLO"=>
  {:iata=>"LLO",
   :name=>"Palopo Lagaligo Airport",
   :icao=>"",
   :city=>"Palopo",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Palopo, Indonesia"},
 "LOP"=>
  {:iata=>"LOP",
   :name=>"Lombok International Airport (Bandara Internasional Lombok)",
   :icao=>"WADL",
   :city=>"Mataram (near Praya)",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Mataram (near Praya), Lombok, Indonesia"},
 "LLN"=>
  {:iata=>"LLN",
   :name=>"Kelila Airport",
   :icao=>"WAJV",
   :city=>"Kelila",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kelila, Indonesia"},
 "LAH"=>
  {:iata=>"LAH",
   :name=>"Labuha Airport",
   :icao=>"",
   :city=>"Labuha",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Labuha, Indonesia"},
 "LHI"=>
  {:iata=>"LHI",
   :name=>"Lereh Airport",
   :icao=>"WAJL",
   :city=>"Lereh",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Lereh, Indonesia"},
 "LSX"=>
  {:iata=>"LSX",
   :name=>"Lhok Sukon Airport",
   :icao=>"WITL",
   :city=>"Lhok Sukon",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Lhok Sukon, Sumatra, Indonesia"},
 "LBW"=>
  {:iata=>"LBW",
   :name=>"Juvai Semaring Airport (Long Bawan Airport)",
   :icao=>"WRLB",
   :city=>"Long Bawan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Long Bawan, East Kalimantan, Indonesia"},
 "LYK"=>
  {:iata=>"LYK",
   :name=>"Lunyuk Airport",
   :icao=>"",
   :city=>"Lunyuk",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Lunyuk, Indonesia"},
 "LII"=>
  {:iata=>"LII",
   :name=>"Mulia Airport",
   :icao=>"WAJM",
   :city=>"Mulia",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Mulia, Indonesia"},
 "LFM"=>
  {:iata=>"LFM",
   :name=>"Lamerd Airport",
   :city=>"Lamerd",
   :icao=>"OISR",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Lamerd, Iran"},
 "LRR"=>
  {:iata=>"LRR",
   :name=>"Lar Airport",
   :icao=>"OISL",
   :city=>"Lar",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Lar, Iran"},
 "LVP"=>
  {:iata=>"LVP",
   :name=>"Lavan Airport",
   :icao=>"OIBV",
   :city=>"Lavan Island",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Lavan Island, Iran"},
 "LXG"=>
  {:iata=>"LXG",
   :name=>"Luang Namtha Airport",
   :icao=>"VLLN",
   :city=>"Luang Namtha",
   :country=>'Laos', :country_code=>'',
   :location=>"Luang Namtha, Laos"},
 "LPQ"=>
  {:iata=>"LPQ",
   :name=>"Luang Prabang International Airport",
   :icao=>"VLLB",
   :city=>"Luang Prabang",
   :country=>'Laos', :country_code=>'',
   :location=>"Luang Prabang, Laos"},
 "LBU"=>
  {:iata=>"LBU",
   :name=>"Labuan Airport",
   :icao=>"WBKL",
   :city=>"Labuan",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Labuan, Sabah, Malaysia"},
 "LDU"=>
  {:iata=>"LDU",
   :name=>"Lahad Datu Airport",
   :icao=>"WBKD",
   :city=>"Lahad Datu",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Lahad Datu, Sabah, Malaysia"},
 "LGK"=>
  {:iata=>"LGK",
   :name=>"Langkawi International Airport",
   :icao=>"WMKL",
   :city=>"Langkawi",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Langkawi, Kedah, Malaysia"},
 "LWY"=>
  {:iata=>"LWY",
   :name=>"Lawas Airport",
   :icao=>"WBGW",
   :city=>"Lawas",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Lawas, Sarawak, Malaysia"},
 "LMN"=>
  {:iata=>"LMN",
   :name=>"Limbang Airport",
   :icao=>"WBGJ",
   :city=>"Limbang",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Limbang, Sarawak, Malaysia"},
 "LKH"=>
  {:iata=>"LKH",
   :name=>"Long Akah Airport",
   :city=>"Long Akah",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Akah, Malaysia"},
 "LBP"=>
  {:iata=>"LBP",
   :name=>"Long Banga Airport",
   :icao=>"",
   :city=>"Long Banga",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Banga, Sarawak, Malaysia"},
 "LGL"=>
  {:iata=>"LGL",
   :name=>"Long Lellang Airport",
   :icao=>"WBGF",
   :city=>"Long Lellang",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Lellang, Sarawak, Malaysia"},
 "LLM"=>
  {:iata=>"LLM",
   :name=>"Long Lama Airport",
   :icao=>"",
   :city=>"Long Lama",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Lama, Sarawak, Malaysia"},
 "LSM"=>
  {:iata=>"LSM",
   :name=>"Long Semado Airport",
   :icao=>"WBGD",
   :city=>"Long Semado",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Semado, Sarawak, Malaysia"},
 "LSU"=>
  {:iata=>"LSU",
   :name=>"Long Sukang Airport",
   :icao=>"WBGU",
   :city=>"Long Sukang",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Sukang, Sarawak, Malaysia"},
 "LAC"=>
  {:iata=>"LAC",
   :name=>"Layang Layang Airport (Swallow Reef Airport)",
   :icao=>"",
   :city=>"Layang Layang (Swallow Reef)",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Layang Layang (Swallow Reef), Sabah, Malaysia"},
 "LTI"=>
  {:iata=>"LTI",
   :name=>"Altai Airport",
   :icao=>"ZMAT",
   :city=>"Altai",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Altai, Govi-Altai, Mongolia"},
 "LSH"=>
  {:iata=>"LSH",
   :name=>"Lashio Airport",
   :icao=>"VYLS",
   :city=>"Lashio",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Lashio, Myanmar (Burma)"},
 "LIW"=>
  {:iata=>"LIW",
   :name=>"Loikaw Airport",
   :icao=>"VYLK",
   :city=>"Loikaw",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Loikaw, Myanmar (Burma)"},
 "LDN"=>
  {:iata=>"LDN",
   :name=>"Lamidanda Airport",
   :icao=>"VNLD",
   :city=>"Lamidanda",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Lamidanda, Nepal"},
 "LUA"=>
  {:iata=>"LUA",
   :name=>"Lukla Airport (Tenzing-Hillary Airport)",
   :icao=>"VNLK",
   :city=>"Lukla",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Lukla, Nepal"},
 "LTG"=>
  {:iata=>"LTG",
   :name=>"Langtang Airport",
   :icao=>"VNLT",
   :city=>"Langtang",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Langtang, Nepal"},
 "LYP"=>
  {:iata=>"LYP",
   :name=>"Faisalabad International Airport",
   :icao=>"OPFA",
   :city=>"Faisalabad",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Faisalabad, Pakistan"},
 "LHE"=>
  {:iata=>"LHE",
   :name=>"Allama Iqbal International Airport",
   :icao=>"OPLA",
   :city=>"Lahore",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Lahore, Pakistan"},
 "LRG"=>
  {:iata=>"LRG",
   :name=>"Loralai Airport",
   :icao=>"OPLL",
   :city=>"Loralai",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Loralai, Pakistan"},
 "LAE"=>
  {:iata=>"LAE",
   :name=>"Lae Nadzab Airport",
   :icao=>"AYNZ",
   :city=>"Lae",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lae, Papua New Guinea, Papua New Guinea"},
 "LMY"=>
  {:iata=>"LMY",
   :name=>"Lake Murray Airport",
   :icao=>"",
   :city=>"Lake Murray",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lake Murray, Papua New Guinea"},
 "LNV"=>
  {:iata=>"LNV",
   :name=>"Lihir Island Airport",
   :icao=>"AYKY",
   :city=>"Londolovit",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Londolovit, Lihir Island, Papua New Guinea"},
 "LSA"=>
  {:iata=>"LSA",
   :name=>"Losuia Airport (Kiriwina Airfield)",
   :icao=>"AYKA",
   :city=>"Losuia",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Losuia, Kiriwina Island, Papua New Guinea"},
 "LAB"=>
  {:iata=>"LAB",
   :name=>"Lablab Airport",
   :icao=>"",
   :city=>"Lablab",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lablab, Papua New Guinea"},
 "LGM"=>
  {:iata=>"LGM",
   :name=>"Laiagam Airport",
   :icao=>"",
   :city=>"Laiagam",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Laiagam, Papua New Guinea"},
 "LMG"=>
  {:iata=>"LMG",
   :name=>"Lamassa Airport",
   :icao=>"",
   :city=>"Lamassa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lamassa, Papua New Guinea"},
 "LNM"=>
  {:iata=>"LNM",
   :name=>"Langimar Airport",
   :icao=>"",
   :city=>"Langimar",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Langimar, Papua New Guinea"},
 "LHP"=>
  {:iata=>"LHP",
   :name=>"Lehu Airport",
   :icao=>"",
   :city=>"Lehu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lehu, Papua New Guinea"},
 "LTF"=>
  {:iata=>"LTF",
   :name=>"Leitre Airport",
   :icao=>"",
   :city=>"Leitre",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Leitre, Papua New Guinea"},
 "LNC"=>
  {:iata=>"LNC",
   :name=>"Lengbati Airport",
   :icao=>"",
   :city=>"Lengbati",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lengbati, Papua New Guinea"},
 "LNG"=>
  {:iata=>"LNG",
   :name=>"Lese Airport",
   :icao=>"",
   :city=>"Lese",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lese, Papua New Guinea"},
 "LGN"=>
  {:iata=>"LGN",
   :name=>"Linga Linga Airport",
   :icao=>"",
   :city=>"Linga Linga",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Linga Linga, Papua New Guinea"},
 "LNQ"=>
  {:iata=>"LNQ",
   :name=>"Loani Airport",
   :icao=>"",
   :city=>"Loani",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Loani, Papua New Guinea"},
 "LSJ"=>
  {:iata=>"LSJ",
   :name=>"Long Island Airport",
   :icao=>"",
   :city=>"Long Island",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Long Island, Papua New Guinea"},
 "LWI"=>
  {:iata=>"LWI",
   :name=>"Lowai Airport",
   :icao=>"",
   :city=>"Lowai",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lowai, Papua New Guinea"},
 "LMI"=>
  {:iata=>"LMI",
   :name=>"Lumi Airport",
   :icao=>"",
   :city=>"Lumi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Lumi, Papua New Guinea"},
 "LNF"=>
  {:iata=>"LNF",
   :name=>"Munbil Airport",
   :icao=>"",
   :city=>"Munbil",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Munbil, Papua New Guinea"},
 "LAO"=>
  {:iata=>"LAO",
   :name=>"Laoag International Airport",
   :icao=>"RPLI",
   :city=>"Laoag City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Laoag City, Ilocos Norte, Philippines"},
 "LGP"=>
  {:iata=>"LGP",
   :name=>"Legazpi Airport",
   :icao=>"RPLP",
   :city=>"Legazpi City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Legazpi City, Albay, Philippines"},
 "LBX"=>
  {:iata=>"LBX",
   :name=>"Lubang Airport",
   :icao=>"RPLU",
   :city=>"Lubang",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Lubang, Occidental Mindoro, Philippines"},
 "LWA"=>
  {:iata=>"LWA",
   :name=>"Lebak Airport",
   :icao=>"",
   :city=>"Lebak",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Lebak, Sultan Kudarat, Philippines"},
 "LHN"=>
  {:iata=>"LHN",
   :name=>"Lishan Airport",
   :icao=>"RCLS",
   :city=>"Lishan",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Lishan, Taiwan"},
 "LBD"=>
  {:iata=>"LBD",
   :name=>"Khujand Airport",
   :icao=>"UTDL",
   :city=>"Khujand",
   :country=>'Tajikistan', :country_code=>'TJ',
   :location=>"Khujand, Tajikistan"},
 "LPT"=>
  {:iata=>"LPT",
   :name=>"Lampang Airport",
   :icao=>"VTCL",
   :city=>"Lampang",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Lampang, Thailand"},
 "LOE"=>
  {:iata=>"LOE",
   :name=>"Loei Airport",
   :icao=>"VTUL",
   :city=>"Loei",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Loei, Thailand"},
 "LIR"=>
  {:iata=>"LIR",
   :name=>"Daniel Oduber Quirós International Airport",
   :icao=>"MRLB",
   :city=>"Liberia",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Liberia, Costa Rica"},
 "LCS"=>
  {:iata=>"LCS",
   :name=>"Las Canas Airport",
   :icao=>"",
   :city=>"Las Canas",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Las Canas, Costa Rica"},
 "LIO"=>
  {:iata=>"LIO",
   :name=>"Puerto Limón International Airport",
   :icao=>"MRLM",
   :city=>"Puerto Limón",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Puerto Limón, Costa Rica"},
 "LSL"=>
  {:iata=>"LSL",
   :name=>"Los Chiles Airport",
   :icao=>"MRLC",
   :city=>"Los Chiles",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Los Chiles, Costa Rica"},
 "LCF"=>
  {:iata=>"LCF",
   :name=>"Río Dulce Airport (Las Vegas Airport)",
   :icao=>"",
   :city=>"Río Dulce",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Río Dulce, Izabal, Guatemala"},
 "LCE"=>
  {:iata=>"LCE",
   :name=>"Golosón International Airport",
   :icao=>"MHLC",
   :city=>"La Ceiba",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"La Ceiba, Honduras"},
 "LEZ"=>
  {:iata=>"LEZ",
   :name=>"La Esperanza Airport",
   :icao=>"MHLE",
   :city=>"La Esperanza",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"La Esperanza, Honduras"},
 "LUI"=>
  {:iata=>"LUI",
   :name=>"La Unión Airport",
   :icao=>"",
   :city=>"La Unión",
   :country=>"Honduras[disambiguation needed]", :country_code=>'HN',
   :location=>"La Unión, Honduras[disambiguation needed]"},
 "LLH"=>
  {:iata=>"LLH",
   :name=>"Las Limas Airport",
   :icao=>"",
   :city=>"Las Limas",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Las Limas, Honduras"},
 "LMH"=>
  {:iata=>"LMH",
   :name=>"Limón Airport",
   :icao=>"",
   :city=>"Limón",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Limón, Colón, Honduras"},
 "LXR"=>
  {:iata=>"LXR",
   :name=>"Luxor International Airport",
   :icao=>"HELX",
   :city=>"Luxor",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Luxor, Egypt"},
 "LDR"=>
  {:iata=>"LDR",
   :name=>"Lodar Airport",
   :icao=>"",
   :city=>"Lodar",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Lodar, Yemen"},
 "LTK"=>
  {:iata=>"LTK",
   :name=>"Bassel Al-Assad International Airport",
   :icao=>"OSLK",
   :city=>"Latakia",
   :country=>'Syria', :country_code=>'SY',
   :location=>"Latakia, Syria"},
 "LAA"=>
  {:iata=>"LAA",
   :name=>"Lamar Municipal Airport",
   :icao=>"KLAA",
   :city=>"Lamar",
   :country=>'United States', :country_code=>'US',

   :location=>"Lamar, Colorado, United States"},
 "LAF"=>
  {:iata=>"LAF",
   :name=>"Purdue University Airport",
   :icao=>"KLAF",
   :city=>"West Lafayette",
   :country=>'United States', :country_code=>'US',

   :location=>"West Lafayette, Indiana, United States"},
 "LAL"=>
  {:iata=>"LAL",
   :name=>"Lakeland Linder Regional Airport",
   :icao=>"KLAL",
   :city=>"Lakeland",
   :country=>'United States', :country_code=>'US',

   :location=>"Lakeland, Florida, United States"},
 "LAM"=>
  {:iata=>"LAM",
   :name=>"Los Alamos County Airport",
   :icao=>"KLAM",
   :city=>"Los Alamos",
   :country=>'United States', :country_code=>'US',

   :location=>"Los Alamos, New Mexico, United States"},
 "LAN"=>
  {:iata=>"LAN",
   :name=>"Capital Region International Airport",
   :icao=>"KLAN",
   :city=>"Lansing",
   :country=>'United States', :country_code=>'US',

   :location=>"Lansing, Michigan, United States"},
 "LAS"=>
  {:iata=>"LAS",
   :name=>"McCarran International Airport",
   :icao=>"KLAS",
   :city=>"Las Vegas",
   :country=>'United States', :country_code=>'US',

   :location=>"Las Vegas, Nevada, United States"},
 "LAW"=>
  {:iata=>"LAW",
   :name=>"Lawton-Fort Sill Regional Airport",
   :icao=>"KLAW",
   :city=>"Lawton",
   :country=>'United States', :country_code=>'US',

   :location=>"Lawton, Oklahoma, United States"},
 "LAX"=>
  {:iata=>"LAX",
   :name=>"Los Angeles International Airport",
   :icao=>"KLAX",
   :city=>"Los Angeles",
   :country=>'United States', :country_code=>'US',

   :location=>"Los Angeles, California, United States"},
 "LBB"=>
  {:iata=>"LBB",
   :name=>"Lubbock Preston Smith International Airport",
   :icao=>"KLBB",
   :city=>"Lubbock",
   :country=>'United States', :country_code=>'US',

   :location=>"Lubbock, Texas, United States"},
 "LBE"=>
  {:iata=>"LBE",
   :name=>"Arnold Palmer Regional Airport",
   :icao=>"KLBE",
   :city=>"Latrobe (near Pittsburgh)",
   :country=>'United States', :country_code=>'US',

   :location=>"Latrobe (near Pittsburgh), Pennsylvania, United States"},
 "LBF"=>
  {:iata=>"LBF",
   :name=>"North Platte Regional Airport (Lee Bird Field)",
   :icao=>"KLBF",
   :city=>"North Platte",
   :country=>'United States', :country_code=>'US',

   :location=>"North Platte, Nebraska, United States"},
 "LBL"=>
  {:iata=>"LBL",
   :name=>"Liberal Municipal Airport",
   :icao=>"KLBL",
   :city=>"Liberal",
   :country=>'United States', :country_code=>'US',

   :location=>"Liberal, Kansas, United States"},
 "LBT"=>
  {:iata=>"LBT",
   :name=>"Lumberton Municipal Airport",
   :icao=>"KLBT",
   :city=>"Lumberton",
   :country=>'United States', :country_code=>'US',

   :location=>"Lumberton, North Carolina, United States"},
 "LCH"=>
  {:iata=>"LCH",
   :name=>"Lake Charles Regional Airport",
   :icao=>"KLCH",
   :city=>"Lake Charles",
   :country=>'United States', :country_code=>'US',

   :location=>"Lake Charles, Louisiana, United States"},
 "LCI"=>
  {:iata=>"LCI",
   :name=>"Laconia Municipal Airport",
   :icao=>"KLCI",
   :city=>"Laconia",
   :country=>'United States', :country_code=>'US',

   :location=>"Laconia, New Hampshire, United States"},
 "LCK"=>
  {:iata=>"LCK",
   :name=>"Rickenbacker International Airport",
   :icao=>"KLCK",
   :city=>"Columbus",
   :country=>'United States', :country_code=>'US',

   :location=>"Columbus, Ohio, United States"},
 "LCQ"=>
  {:iata=>"LCQ",
   :name=>"Lake City Gateway Airport",
   :icao=>"KLCQ",
   :city=>"Lake City",
   :country=>'United States', :country_code=>'US',

   :location=>"Lake City, Florida, United States"},
 "LDJ"=>
  {:iata=>"LDJ",
   :name=>"Linden Airport",
   :icao=>"KLDJ",
   :city=>"Linden",
   :country=>'United States', :country_code=>'US',

   :location=>"Linden, New Jersey, United States"},
 "LDM"=>
  {:iata=>"LDM",
   :name=>"Mason County Airport",
   :icao=>"KLDM",
   :city=>"Ludington",
   :country=>'United States', :country_code=>'US',

   :location=>"Ludington, Michigan, United States"},
 "LEB"=>
  {:iata=>"LEB",
   :name=>"Lebanon Municipal Airport",
   :icao=>"KLEB",
   :city=>"Lebanon",
   :country=>'United States', :country_code=>'US',

   :location=>"Lebanon, New Hampshire, United States"},
 "LEE"=>
  {:iata=>"LEE",
   :name=>"Leesburg International Airport",
   :icao=>"KLEE",
   :city=>"Leesburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Leesburg, Florida, United States"},
 "LEM"=>
  {:iata=>"LEM",
   :name=>"Lemmon Municipal Airport",
   :icao=>"KLEM",
   :city=>"Lemmon",
   :country=>'United States', :country_code=>'US',

   :location=>"Lemmon, South Dakota, United States"},
 "LEW"=>
  {:iata=>"LEW",
   :name=>"Auburn/Lewiston Municipal Airport",
   :icao=>"KLEW",
   :city=>"Auburn/Lewiston",
   :country=>'United States', :country_code=>'US',

   :location=>"Auburn/Lewiston, Maine, United States"},
 "LEX"=>
  {:iata=>"LEX",
   :name=>"Blue Grass Airport",
   :icao=>"KLEX",
   :city=>"Lexington",
   :country=>'United States', :country_code=>'US',

   :location=>"Lexington, Kentucky, United States"},
 "LFI"=>
  {:iata=>"LFI",
   :name=>"Langley Air Force Base",
   :icao=>"KLFI",
   :city=>"Hampton",
   :country=>'United States', :country_code=>'US',

   :location=>"Hampton, Virginia, United States"},
 "LFK"=>
  {:iata=>"LFK",
   :name=>"Angelina County Airport",
   :icao=>"KLFK",
   :city=>"Lufkin",
   :country=>'United States', :country_code=>'US',

   :location=>"Lufkin, Texas, United States"},
 "LFN"=>
  {:iata=>"LFN",
   :name=>
    "Triangle North Executive Airport (Franklin County Airport) (FAA: LHZ)",
   :icao=>"KLHZ",
   :city=>"Louisburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Louisburg, North Carolina, United States"},
 "LFT"=>
  {:iata=>"LFT",
   :name=>"Lafayette Regional Airport",
   :icao=>"KLFT",
   :city=>"Lafayette",
   :country=>'United States', :country_code=>'US',

   :location=>"Lafayette, Louisiana, United States"},
 "LGA"=>
  {:iata=>"LGA",
   :name=>"LaGuardia Airport",
   :icao=>"KLGA",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "LGB"=>
  {:iata=>"LGB",
   :name=>"Long Beach Airport",
   :icao=>"KLGB",
   :city=>"Long Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Long Beach, California, United States"},
 "LGC"=>
  {:iata=>"LGC",
   :name=>"LaGrange-Callaway Airport",
   :icao=>"KLGC",
   :city=>"LaGrange",
   :country=>'United States', :country_code=>'US',

   :location=>"LaGrange, Georgia, United States"},
 "LGD"=>
  {:iata=>"LGD",
   :name=>"La Grande/Union County Airport",
   :icao=>"KLGD",
   :city=>"La Grande",
   :country=>'United States', :country_code=>'US',

   :location=>"La Grande, Oregon, United States"},
 "LGF"=>
  {:iata=>"LGF",
   :name=>"Laguna Army Airfield",
   :icao=>"KLGF",
   :city=>"Yuma Proving Ground",
   :country=>'United States', :country_code=>'US',

   :location=>"Yuma Proving Ground, Arizona, United States"},
 "LGU"=>
  {:iata=>"LGU",
   :name=>"Logan-Cache Airport",
   :icao=>"KLGU",
   :city=>"Logan",
   :country=>'United States', :country_code=>'US',

   :location=>"Logan, Utah, United States"},
 "LGZ"=>
  {:iata=>"LGZ",
   :name=>"Leguizamo Airport",
   :icao=>"",
   :city=>"Puerto Leguizamo",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Leguizamo, Colombia"},
 "LHV"=>
  {:iata=>"LHV",
   :name=>"William T. Piper Memorial Airport",
   :icao=>"KLHV",
   :city=>"Lock Haven",
   :country=>'United States', :country_code=>'US',

   :location=>"Lock Haven, Pennsylvania, United States"},
 "LIC"=>
  {:iata=>"LIC",
   :name=>"Limon Municipal Airport",
   :icao=>"KLIC",
   :city=>"Limon",
   :country=>'United States', :country_code=>'US',

   :location=>"Limon, Colorado, United States"},
 "LIH"=>
  {:iata=>"LIH",
   :name=>"Lihue Airport",
   :icao=>"PHLI",
   :city=>"Lihue",
   :country=>'United States', :country_code=>'US',

   :location=>"Lihue, Hawaii, United States"},
 "LIT"=>
  {:iata=>"LIT",
   :name=>"Little Rock National Airport (Adams Field)",
   :icao=>"KLIT",
   :city=>"Little Rock",
   :country=>'United States', :country_code=>'US',

   :location=>"Little Rock, Arkansas, United States"},
 "LIV"=>
  {:iata=>"LIV",
   :name=>"Livengood Camp Airport (FAA: 4AK)",
   :icao=>"",
   :city=>"Livengood",
   :country=>'United States', :country_code=>'US',

   :location=>"Livengood, Alaska, United States"},
 "LIY"=>
  {:iata=>"LIY",
   :name=>"MidCoast Regional Airport at Wright Army Airfield (FAA: LHW)",
   :icao=>"KLHW",
   :city=>"Fort Stewart",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Stewart, Hinesville, Georgia, United States"},
 "LIZ"=>
  {:iata=>"LIZ",
   :name=>"Loring International Airport (was Loring AFB) (FAA: ME16)",
   :icao=>"",
   :city=>"Limestone",
   :country=>'United States', :country_code=>'US',

   :location=>"Limestone, Maine, United States"},
 "LJN"=>
  {:iata=>"LJN",
   :name=>"Brazoria County Airport (FAA: LBX)",
   :icao=>"KLBX",
   :city=>"Angleton / Lake Jackson",
   :country=>'United States', :country_code=>'US',

   :location=>"Angleton / Lake Jackson, Texas, United States"},
 "LKE"=>
  {:iata=>"LKE",
   :name=>"Kenmore Air Harbor Seaplane Base (FAA: W55)",
   :icao=>"",
   :city=>"Seattle",
   :country=>'United States', :country_code=>'US',

   :location=>"Seattle, Washington, United States"},
 "LKK"=>
  {:iata=>"LKK",
   :name=>"Kulik Lake Airport",
   :icao=>"PAKL",
   :city=>"Kulik Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Kulik Lake, Bristol Bay Borough, Alaska, United States"},
 "LKP"=>
  {:iata=>"LKP",
   :name=>"Lake Placid Airport",
   :icao=>"KLKP",
   :city=>"Lake Placid",
   :country=>'United States', :country_code=>'US',

   :location=>"Lake Placid, New York, United States"},
 "LKV"=>
  {:iata=>"LKV",
   :name=>"Lake County Airport",
   :icao=>"KLKV",
   :city=>"Lakeview",
   :country=>'United States', :country_code=>'US',

   :location=>"Lakeview, Oregon, United States"},
 "LLJ"=>
  {:iata=>"LLJ",
   :name=>"Lalmonirhat Airport",
   :icao=>"VGLM",
   :city=>"Lalmonirhat",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Lalmonirhat, Bangladesh"},
 "LLX"=>
  {:iata=>"LLX",
   :name=>"Caledonia County Airport (FAA: CDA)",
   :icao=>"KCDA",
   :city=>"Lyndonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Lyndonville, Vermont, United States"},
 "LLY"=>
  {:iata=>"LLY",
   :name=>"South Jersey Regional Airport (FAA: VAY)",
   :icao=>"KVAY",
   :city=>"Mount Holly",
   :country=>'United States', :country_code=>'US',

   :location=>"Mount Holly, New Jersey, United States"},
 "LMA"=>
  {:iata=>"LMA",
   :name=>"Lake Minchumina Airport (FAA: MHM)",
   :icao=>"",
   :city=>"Lake Minchumina",
   :country=>'United States', :country_code=>'US',

   :location=>"Lake Minchumina, Alaska, United States"},
 "LMS"=>
  {:iata=>"LMS",
   :name=>"Louisville Winston County Airport",
   :icao=>"KLMS",
   :city=>"Louisville",
   :country=>'United States', :country_code=>'US',

   :location=>"Louisville, Mississippi, United States"},
 "LMT"=>
  {:iata=>"LMT",
   :name=>"Klamath Falls Airport",
   :icao=>"KLMT",
   :city=>"Klamath Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Klamath Falls, Oregon, United States"},
 "LNA"=>
  {:iata=>"LNA",
   :name=>"Palm Beach County Park Airport",
   :icao=>"KLNA",
   :city=>"West Palm Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"West Palm Beach, Florida, United States"},
 "LNI"=>
  {:iata=>"LNI",
   :name=>"Lonely Air Station (FAA: AK71)",
   :icao=>"PALN",
   :city=>"Lonely",
   :country=>'United States', :country_code=>'US',

   :location=>"Lonely, North Slope Borough, Alaska, United States"},
 "LNK"=>
  {:iata=>"LNK",
   :name=>"Lincoln Airport",
   :icao=>"KLNK",
   :city=>"Lincoln",
   :country=>'United States', :country_code=>'US',

   :location=>"Lincoln, Nebraska, United States"},
 "LNN"=>
  {:iata=>"LNN",
   :name=>"Willoughby Lost Nation Municipal Airport",
   :icao=>"KLNN",
   :city=>"Willoughby",
   :country=>'United States', :country_code=>'US',

   :location=>"Willoughby, Ohio, United States"},
 "LNP"=>
  {:iata=>"LNP",
   :name=>"Lonesome Pine Airport",
   :icao=>"KLNP",
   :city=>"Wise",
   :country=>'United States', :country_code=>'US',

   :location=>"Wise, Virginia, United States"},
 "LNR"=>
  {:iata=>"LNR",
   :name=>"Tri-County Regional Airport",
   :icao=>"KLNR",
   :city=>"Lone Rock",
   :country=>'United States', :country_code=>'US',

   :location=>"Lone Rock, Wisconsin, United States"},
 "LNS"=>
  {:iata=>"LNS",
   :name=>"Lancaster Airport",
   :icao=>"KLNS",
   :city=>"Lancaster",
   :country=>'United States', :country_code=>'US',

   :location=>"Lancaster, Pennsylvania, United States"},
 "LNY"=>
  {:iata=>"LNY",
   :name=>"Lanai Airport",
   :icao=>"PHNY",
   :city=>"Lanai City",
   :country=>'United States', :country_code=>'US',

   :location=>"Lanai City, Hawaii, United States"},
 "LOL"=>
  {:iata=>"LOL",
   :name=>"Derby Field",
   :icao=>"KLOL",
   :city=>"Lovelock",
   :country=>'United States', :country_code=>'US',

   :location=>"Lovelock, Nevada, United States"},
 "LON"=>
  {:iata=>"LON",
   :name=>"All airports",
   :icao=>"",
   :city=>"London",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"London, England, United Kingdom"},
 "LOR"=>
  {:iata=>"LOR",
   :name=>"Lowe Army Heliport (Fort Rucker)",
   :icao=>"KLOR",
   :city=>"Fort Rucker / Ozark",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Rucker / Ozark, Alabama, United States"},
 "LOT"=>
  {:iata=>"LOT",
   :name=>"Lewis University Airport",
   :icao=>"KLOT",
   :city=>"Chicago / Romeoville",
   :country=>'United States', :country_code=>'US',

   :location=>"Chicago / Romeoville, Illinois, United States"},
 "LOU"=>
  {:iata=>"LOU",
   :name=>"Bowman Field",
   :icao=>"KLOU",
   :city=>"Louisville",
   :country=>'United States', :country_code=>'US',

   :location=>"Louisville, Kentucky, United States"},
 "LOW"=>
  {:iata=>"LOW",
   :name=>"Louisa County Airport (Freeman Field) (FAA: LKU)",
   :icao=>"KLKU",
   :city=>"Louisa",
   :country=>'United States', :country_code=>'US',

   :location=>"Louisa, Virginia, United States"},
 "LOX"=>
  {:iata=>"LOX",
   :name=>"Los Tablones Airport",
   :icao=>"",
   :city=>"Los Tablones",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Los Tablones, El Progreso, Guatemala"},
 "LOZ"=>
  {:iata=>"LOZ",
   :name=>"London-Corbin Airport (Magee Field)",
   :icao=>"KLOZ",
   :city=>"London",
   :country=>'United States', :country_code=>'US',

   :location=>"London, Kentucky, United States"},
 "LPC"=>
  {:iata=>"LPC",
   :name=>"Lompoc Airport",
   :icao=>"KLPC",
   :city=>"Lompoc",
   :country=>'United States', :country_code=>'US',

   :location=>"Lompoc, California, United States"},
 "LPO"=>
  {:iata=>"LPO",
   :name=>"La Porte Municipal Airport (FAA: PPO)",
   :icao=>"KPPO",
   :city=>"La Porte",
   :country=>'United States', :country_code=>'US',

   :location=>"La Porte, Indiana, United States"},
 "LPR"=>
  {:iata=>"LPR",
   :name=>"Lorain County Regional Airport",
   :icao=>"KLPR",
   :city=>"Lorain / Elyria",
   :country=>'United States', :country_code=>'US',

   :location=>"Lorain / Elyria, Ohio, United States"},
 "LPS"=>
  {:iata=>"LPS",
   :name=>"Fishermans Bay/LPS Seaplane Base",
   :icao=>"",
   :city=>"Lopez Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Lopez Island, Washington, United States"},
 "LQK"=>
  {:iata=>"LQK",
   :name=>"Pickens County Airport",
   :icao=>"KLQK",
   :city=>"Pickens",
   :country=>'United States', :country_code=>'US',

   :location=>"Pickens, South Carolina, United States"},
 "LQR"=>
  {:iata=>"LQR",
   :name=>"Larned-Pawnee County Airport",
   :icao=>"KLQR",
   :city=>"Larned",
   :country=>'United States', :country_code=>'US',

   :location=>"Larned, Kansas, United States"},
 "LRD"=>
  {:iata=>"LRD",
   :name=>"Laredo International Airport",
   :icao=>"KLRD",
   :city=>"Laredo",
   :country=>'United States', :country_code=>'US',

   :location=>"Laredo, Texas, United States"},
 "LRF"=>
  {:iata=>"LRF",
   :name=>"Little Rock Air Force Base",
   :icao=>"KLRF",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Arkansas, United States"},
 "LRJ"=>
  {:iata=>"LRJ",
   :name=>"Le Mars Municipal Airport",
   :icao=>"KLRJ",
   :city=>"Le Mars",
   :country=>'United States', :country_code=>'US',

   :location=>"Le Mars, Iowa, United States"},
 "LRU"=>
  {:iata=>"LRU",
   :name=>"Las Cruces International Airport",
   :icao=>"KLRU",
   :city=>"Las Cruces",
   :country=>'United States', :country_code=>'US',

   :location=>"Las Cruces, New Mexico, United States"},
 "LSB"=>
  {:iata=>"LSB",
   :name=>"Lordsburg Municipal Airport",
   :icao=>"KLSB",
   :city=>"Lordsburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Lordsburg, New Mexico, United States"},
 "LSE"=>
  {:iata=>"LSE",
   :name=>"La Crosse Regional Airport",
   :icao=>"KLSE",
   :city=>"La Crosse",
   :country=>'United States', :country_code=>'US',

   :location=>"La Crosse, Wisconsin, United States"},
 "LSF"=>
  {:iata=>"LSF",
   :name=>"Lawson Army Airfield",
   :icao=>"KLSF",
   :city=>"Fort Benning",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Benning, Columbus, Georgia, United States"},
 "LSN"=>
  {:iata=>"LSN",
   :name=>"Los Banos Municipal Airport",
   :icao=>"KLSN",
   :city=>"Los Banos",
   :country=>'United States', :country_code=>'US',

   :location=>"Los Banos, California, United States"},
 "LSR"=>
  {:iata=>"LSR",
   :name=>"Lost River 1 Airport (closed 2009)",
   :icao=>"",
   :city=>"Lost River",
   :country=>'United States', :country_code=>'US',

   :location=>"Lost River, Alaska, United States"},
 "LSV"=>
  {:iata=>"LSV",
   :name=>"Nellis Air Force Base",
   :icao=>"KLSV",
   :city=>"Las Vegas",
   :country=>'United States', :country_code=>'US',

   :location=>"Las Vegas, Nevada, United States"},
 "LTS"=>
  {:iata=>"LTS",
   :name=>"Altus Air Force Base",
   :icao=>"KLTS",
   :city=>"Altus",
   :country=>'United States', :country_code=>'US',

   :location=>"Altus, Oklahoma, United States"},
 "LTW"=>
  {:iata=>"LTW",
   :name=>"St. Mary's County Regional Airport (FAA: 2W6)",
   :icao=>"",
   :city=>"Leonardtown",
   :country=>'United States', :country_code=>'US',

   :location=>"Leonardtown, Maryland, United States"},
 "LUF"=>
  {:iata=>"LUF",
   :name=>"Luke Air Force Base",
   :icao=>"KLUF",
   :city=>"Glendale",
   :country=>'United States', :country_code=>'US',

   :location=>"Glendale, Arizona, United States"},
 "LUK"=>
  {:iata=>"LUK",
   :name=>"Cincinnati Municipal Airport (Lunken Field)",
   :icao=>"KLUK",
   :city=>"Cincinnati",
   :country=>'United States', :country_code=>'US',

   :location=>"Cincinnati, Ohio, United States"},
 "LUL"=>
  {:iata=>"LUL",
   :name=>"Hesler-Noble Field",
   :icao=>"KLUL",
   :city=>"Laurel",
   :country=>'United States', :country_code=>'US',

   :location=>"Laurel, Mississippi, United States"},
 "LUP"=>
  {:iata=>"LUP",
   :name=>"Kalaupapa Airport",
   :icao=>"PHLU",
   :city=>"Kalaupapa",
   :country=>'United States', :country_code=>'US',

   :location=>"Kalaupapa, Hawaii, United States"},
 "LUR"=>
  {:iata=>"LUR",
   :name=>"Cape Lisburne LRRS Airport",
   :icao=>"PALU",
   :city=>"Cape Lisburne",
   :country=>'United States', :country_code=>'US',

   :location=>"Cape Lisburne, Alaska, United States"},
 "LVD"=>
  {:iata=>"LVD",
   :name=>"Lime Village Airport (FAA: 2AK)",
   :icao=>"",
   :city=>"Lime Village",
   :country=>'United States', :country_code=>'US',

   :location=>"Lime Village, Alaska, United States"},
 "LVK"=>
  {:iata=>"LVK",
   :name=>"Livermore Municipal Airport",
   :icao=>"KLVK",
   :city=>"Livermore",
   :country=>'United States', :country_code=>'US',

   :location=>"Livermore, California, United States"},
 "LVL"=>
  {:iata=>"LVL",
   :name=>"Lawrenceville/Brunswick Municipal Airport",
   :icao=>"KLVL",
   :city=>"Lawrenceville",
   :country=>'United States', :country_code=>'US',

   :location=>"Lawrenceville, Virginia, United States"},
 "LVM"=>
  {:iata=>"LVM",
   :name=>"Mission Field",
   :icao=>"KLVM",
   :city=>"Livingston",
   :country=>'United States', :country_code=>'US',

   :location=>"Livingston, Montana, United States"},
 "LVS"=>
  {:iata=>"LVS",
   :name=>"Las Vegas Municipal Airport",
   :icao=>"KLVS",
   :city=>"Las Vegas",
   :country=>'United States', :country_code=>'US',

   :location=>"Las Vegas, New Mexico, United States"},
 "LWB"=>
  {:iata=>"LWB",
   :name=>"Greenbrier Valley Airport",
   :icao=>"KLWB",
   :city=>"Lewisburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Lewisburg, West Virginia, United States"},
 "LWC"=>
  {:iata=>"LWC",
   :name=>"Lawrence Municipal Airport",
   :icao=>"KLWC",
   :city=>"Lawrence",
   :country=>'United States', :country_code=>'US',

   :location=>"Lawrence, Kansas, United States"},
 "LWL"=>
  {:iata=>"LWL",
   :name=>"Wells Municipal Airport (Harriet Field)",
   :icao=>"KLWL",
   :city=>"Wells",
   :country=>'United States', :country_code=>'US',

   :location=>"Wells, Nevada, United States"},
 "LWM"=>
  {:iata=>"LWM",
   :name=>"Lawrence Municipal Airport",
   :icao=>"KLWM",
   :city=>"Lawrence",
   :country=>'United States', :country_code=>'US',

   :location=>"Lawrence, Massachusetts, United States"},
 "LWS"=>
  {:iata=>"LWS",
   :name=>"Lewiston-Nez Perce County Airport",
   :icao=>"KLWS",
   :city=>"Lewiston",
   :country=>'United States', :country_code=>'US',

   :location=>"Lewiston, Idaho, United States"},
 "LWT"=>
  {:iata=>"LWT",
   :name=>"Lewistown Municipal Airport",
   :icao=>"KLWT",
   :city=>"Lewistown",
   :country=>'United States', :country_code=>'US',

   :location=>"Lewistown, Montana, United States"},
 "LWV"=>
  {:iata=>"LWV",
   :name=>"Lawrenceville-Vincennes International Airport",
   :icao=>"KLWV",
   :city=>"Lawrenceville",
   :country=>'United States', :country_code=>'US',

   :location=>"Lawrenceville, Illinois, United States"},
 "LXN"=>
  {:iata=>"LXN",
   :name=>"Jim Kelly Field",
   :icao=>"KLXN",
   :city=>"Lexington",
   :country=>'United States', :country_code=>'US',

   :location=>"Lexington, Nebraska, United States"},
 "LXV"=>
  {:iata=>"LXV",
   :name=>"Lake County Airport",
   :icao=>"KLXV",
   :city=>"Leadville",
   :country=>'United States', :country_code=>'US',

   :location=>"Leadville, Colorado, United States"},
 "LYH"=>
  {:iata=>"LYH",
   :name=>"Lynchburg Regional Airport (Preston Glenn Field)",
   :icao=>"KLYH",
   :city=>"Lynchburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Lynchburg, Virginia, United States"},
 "LYM"=>
  {:iata=>"LYM",
   :name=>"Lympne Airport",
   :icao=>"EGMK",
   :city=>"Lympne",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lympne, Kent, England, United Kingdom"},
 "LYO"=>
  {:iata=>"LYO",
   :name=>"Lyons-Rice County Municipal Airport",
   :icao=>"KLYO",
   :city=>"Lyons",
   :country=>'United States', :country_code=>'US',

   :location=>"Lyons, Kansas, United States"},
 "LYU"=>
  {:iata=>"LYU",
   :name=>"Ely Municipal Airport (FAA: ELO)",
   :icao=>"KELO",
   :city=>"Ely",
   :country=>'United States', :country_code=>'US',

   :location=>"Ely, Minnesota, United States"}}

end
