# encoding: UTF-8
def airp_6
  {"ESE"=>
  {:iata=>"ESE",
   :name=>"Ensenada Airport",
   :icao=>"MMES",
   :city=>"Ensenada",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Ensenada, Baja California, Mexico"},
 "EVW"=>
  {:iata=>"EVW",
   :name=>"Evanston-Uinta County Burns Field",
   :icao=>"KEVW",
   :city=>"Evanston",
   :country=>'United States', :country_code=>'US',

   :location=>"Evanston, Wyoming, United States"},
 "EMM"=>
  {:iata=>"EMM",
   :name=>"Kemmerer Municipal Airport",
   :icao=>"KEMM",
   :city=>"Kemmerer",
   :country=>'United States', :country_code=>'US',

   :location=>"Kemmerer, Wyoming, United States"},
 "ECS"=>
  {:iata=>"ECS",
   :name=>"Mondell Field",
   :icao=>"KECS",
   :city=>"Newcastle",
   :country=>'United States', :country_code=>'US',

   :location=>"Newcastle, Wyoming, United States"},
 "EAN"=>
  {:iata=>"EAN",
   :name=>"Phifer Airfield",
   :icao=>"KEAN",
   :city=>"Wheatland",
   :country=>'United States', :country_code=>'US',

   :location=>"Wheatland, Wyoming, United States"},
 "EZE"=>
  {:iata=>"EZE",
   :name=>"Ministro Pistarini International Airport",
   :icao=>"SAEZ",
   :city=>"Ezeiza (near Buenos Aires)",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Ezeiza (near Buenos Aires), Argentina"},
 "EPA"=>
  {:iata=>"EPA",
   :name=>"El Palomar Airport",
   :city=>"El Palomar",
   :icao=>"SADP",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"El Palomar, Argentina"},
 "EQS"=>
  {:iata=>"EQS",
   :name=>"Esquel Airport",
   :icao=>"SAVE",
   :city=>"Esquel",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Esquel, Chubut Province, Argentina"},
 "EHL"=>
  {:iata=>"EHL",
   :name=>"El Bolson Airport",
   :icao=>"SAVB",
   :city=>"El Bolsón",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"El Bolsón, Río Negro, Argentina"},
 "EMX"=>
  {:iata=>"EMX",
   :name=>"El Maitén Airport",
   :icao=>"SAVD",
   :city=>"El Maitén",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"El Maitén, Neuquén, Argentina"},
 "ELO"=>
  {:iata=>"ELO",
   :name=>"Eldorado Airport",
   :icao=>"SATD",
   :city=>"Eldorado",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Eldorado, Misiones, Argentina"},
 "ERN"=>
  {:iata=>"ERN",
   :name=>"Eirunepe Airport",
   :icao=>"SWEI",
   :city=>"Eirunepe",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Eirunepe, Amazonas, Brazil"},
 "ERM"=>
  {:iata=>"ERM",
   :name=>"Erechim Airport",
   :icao=>"SSER",
   :city=>"Erechim",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Erechim, Rio Grande do Sul, Brazil"},
 "ESI"=>
  {:iata=>"ESI",
   :name=>"Espinosa Airport",
   :icao=>"",
   :city=>"Espinosa",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Espinosa, Minas Gerais, Brazil"},
 "ESR"=>
  {:iata=>"ESR",
   :name=>"El Salvador Bajo Airport",
   :icao=>"SCES",
   :city=>"El Salvador",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"El Salvador, Chile"},
 "EOH"=>
  {:iata=>"EOH",
   :name=>"Olaya Herrera Airport",
   :icao=>"SKMD",
   :city=>"Medellín",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Medellín, Colombia"},
 "EJA"=>
  {:iata=>"EJA",
   :name=>"Yarigüies Airport",
   :icao=>"SKEJ",
   :city=>"Barrancabermeja",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Barrancabermeja, Colombia"},
 "EYP"=>
  {:iata=>"EYP",
   :name=>"El Alcaraván Airport",
   :icao=>"SKYP",
   :city=>"Yopal",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Yopal, Colombia"},
 "EBG"=>
  {:iata=>"EBG",
   :name=>"El Bagre Airport",
   :icao=>"SKEB",
   :city=>"El Bagre",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"El Bagre, Colombia"},
 "ELB"=>
  {:iata=>"ELB",
   :name=>"Las Flores Airport",
   :icao=>"SKBC",
   :city=>"El Banco",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"El Banco, Colombia"},
 "ECR"=>
  {:iata=>"ECR",
   :name=>"El Charco Airport",
   :icao=>"",
   :city=>"El Charco",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"El Charco, Colombia"},
 "ECO"=>
  {:iata=>"ECO",
   :name=>"El Encanto Airport",
   :icao=>"",
   :city=>"El Encanto",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"El Encanto, Colombia"},
 "ELJ"=>
  {:iata=>"ELJ",
   :name=>"El Recreo Airport",
   :icao=>"",
   :city=>"El Recreo",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"El Recreo, Colombia"},
 "ESM"=>
  {:iata=>"ESM",
   :name=>"General Rivadeneira Airport",
   :icao=>"SETN",
   :city=>"Esmeraldas",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Esmeraldas, Ecuador"},
 "ETR"=>
  {:iata=>"ETR",
   :name=>"Santa Rosa Airport",
   :icao=>"SERO",
   :city=>"Santa Rosa",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Santa Rosa, El Oro, Ecuador"},
 "EKE"=>
  {:iata=>"EKE",
   :name=>"Ekereku Airport",
   :icao=>"",
   :city=>"Ekereku",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Ekereku, Guyana"},
 "ENO"=>
  {:iata=>"ENO",
   :name=>"Teniente Primero Alarcon Airport",
   :icao=>"SGEN",
   :city=>"Encarnacion",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Encarnacion, Paraguay"},
 "ESG"=>
  {:iata=>"ESG",
   :name=>"Dr. Luis Maria Argaña International Airport",
   :icao=>"SGME",
   :city=>"Mariscal Estigarribia",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Mariscal Estigarribia, Paraguay"},
 "EOR"=>
  {:iata=>"EOR",
   :name=>"El Dorado Airport",
   :icao=>"SVED",
   :city=>"El Dorado",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"El Dorado, Venezuela"},
 "ELX"=>
  {:iata=>"ELX",
   :name=>"El Tigre Airport",
   :icao=>"",
   :city=>"El Tigre",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"El Tigre, Venezuela"},
 "EOZ"=>
  {:iata=>"EOZ",
   :name=>"Elorza Airport",
   :icao=>"SVEZ",
   :city=>"Elorza",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Elorza, Venezuela"},
 "EDR"=>
  {:iata=>"EDR",
   :name=>"Edward River Airport",
   :icao=>"YPMP",
   :city=>"Edward River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Edward River, Queensland, Australia"},
 "ELC"=>
  {:iata=>"ELC",
   :name=>"Elcho Island Airport",
   :icao=>"YELD",
   :city=>"Elcho Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Elcho Island, Northern Territory, Australia"},
 "ERQ"=>
  {:iata=>"ERQ",
   :name=>"Elrose Airport",
   :icao=>"YESE",
   :city=>"Eloise Copper Mine",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Eloise Copper Mine, Queensland, Australia"},
 "EMD"=>
  {:iata=>"EMD",
   :name=>"Emerald Airport",
   :icao=>"YEML",
   :city=>"Emerald",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Emerald, Queensland, Australia"},
 "EPR"=>
  {:iata=>"EPR",
   :name=>"Esperance Airport",
   :icao=>"YESP",
   :city=>"Esperance",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Esperance, Australia"},
 "ECH"=>
  {:iata=>"ECH",
   :name=>"Echuca Airport",
   :icao=>"YECH",
   :city=>"Echuca",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Echuca, Victoria, Australia"},
 "EIH"=>
  {:iata=>"EIH",
   :name=>"Einasleigh Airport",
   :icao=>"",
   :city=>"Einasleigh",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Einasleigh, Queensland, Australia"},
 "EKD"=>
  {:iata=>"EKD",
   :name=>"Elkedra Airport",
   :icao=>"",
   :city=>"Elkedra",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Elkedra, Northern Territory, Australia"},
 "ENB"=>
  {:iata=>"ENB",
   :name=>"Eneabba Airport",
   :icao=>"YEEB",
   :city=>"Eneabba",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Eneabba, Western Australia, Australia"},
 "EDD"=>
  {:iata=>"EDD",
   :name=>"Erldunda Airport",
   :icao=>"",
   :city=>"Erldunda",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Erldunda, Northern Territory, Australia"},
 "ERB"=>
  {:iata=>"ERB",
   :name=>"Pukatja Airport (Ernabella Airport)",
   :icao=>"YERN",
   :city=>"Pukatja",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Pukatja, South Australia, Australia"},
 "ETD"=>
  {:iata=>"ETD",
   :name=>"Etadunna Airport",
   :icao=>"YEDA",
   :city=>"Etadunna",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Etadunna, South Australia, Australia"},
 "EUC"=>
  {:iata=>"EUC",
   :name=>"Eucla Airport",
   :icao=>"YECL",
   :city=>"Eucla",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Eucla, Western Australia, Australia"},
 "EVD"=>
  {:iata=>"EVD",
   :name=>"Eva Downs Airport",
   :icao=>"",
   :city=>"Eva Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Eva Downs, Northern Territory, Australia"},
 "EVH"=>
  {:iata=>"EVH",
   :name=>"Evans Head Memorial Aerodrome",
   :icao=>"YEVD",
   :city=>"Evans Head",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Evans Head, New South Wales, Australia"},
 "EXM"=>
  {:iata=>"EXM",
   :name=>"Exmouth Airport",
   :icao=>"YEXM",
   :city=>"Exmouth",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Exmouth, Western Australia, Australia"},
 "EAL"=>
  {:iata=>"EAL",
   :name=>"Elenak Airport",
   :icao=>"",
   :city=>"Elenak",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Elenak, Marshall Islands"},
 "EBN"=>
  {:iata=>"EBN",
   :name=>"Ebadon Airstrip",
   :icao=>"",
   :city=>"Kwajalein Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Kwajalein Atoll, Marshall Islands"},
 "EBO"=>
  {:iata=>"EBO",
   :name=>"Ebon Airport",
   :icao=>"",
   :city=>"Ebon Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Ebon Atoll, Marshall Islands"},
 "ENT"=>
  {:iata=>"ENT",
   :name=>"Enewetak Auxiliary Airfield",
   :icao=>"PKMA",
   :city=>"Enewetak",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Enewetak, Marshall Islands"},
 "EJT"=>
  {:iata=>"EJT",
   :name=>"Enejit Airport",
   :icao=>"",
   :city=>"Enejit",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Enejit, Marshall Islands"},
 "EGM"=>
  {:iata=>"EGM",
   :name=>"Sege Airport",
   :icao=>"AGGS",
   :city=>"Sege",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Sege, Solomon Islands"},
 "EUA"=>
  {:iata=>"EUA",
   :name=>"Kaufana Airport",
   :icao=>"NFTE",
   :city=>"Eua",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Eua, Tonga"},
 "EAE"=>
  {:iata=>"EAE",
   :name=>"Siwo Airport",
   :icao=>"NVSE",
   :city=>"Sangafa",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Sangafa, Emae, Shéfa, Vanuatu"},
 "EPI"=>
  {:iata=>"EPI",
   :name=>"Épi Island Airport",
   :icao=>"",
   :city=>"Épi Island",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Épi Island, Shéfa, Vanuatu"},
 "ELH"=>
  {:iata=>"ELH",
   :name=>"North Eleuthera Airport",
   :icao=>"MYEH",
   :city=>"North Eleuthera",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"North Eleuthera, Eleuthera Island, Bahamas"},
 "EIS"=>
  {:iata=>"EIS",
   :name=>"Terrance B. Lettsome International Airport",
   :icao=>"TUPJ",
   :city=>"Beef Island (near Tortola)",
   :country=>'British Virgin Islands', :country_code=>'',
   :location=>"Beef Island (near Tortola), British Virgin Islands"},
 "EUX"=>
  {:iata=>"EUX",
   :name=>"F.D. Roosevelt Airport",
   :icao=>"TNCE",
   :city=>"Sint Eustatius",
   :country=>'Caribbean Netherlands', :country_code=>'',
   :location=>"Sint Eustatius, Caribbean Netherlands"},
 "EPS"=>
  {:iata=>"EPS",
   :name=>"Arroyo Barril International Airport",
   :icao=>"MDAB",
   :city=>"Samaná",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"Samaná, Dominican Republic"},
 "EBH"=>
  {:iata=>"EBH",
   :name=>"El Bayadh Airport",
   :city=>"El Bayadh",
   :icao=>"DAOY",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"El Bayadh, Algeria"},
 "ELG"=>
  {:iata=>"ELG",
   :name=>"El Golea Airport",
   :icao=>"DAUE",
   :city=>"El Golea",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"El Golea, Algeria"},
 "ELU"=>
  {:iata=>"ELU",
   :name=>"Guemar Airport",
   :icao=>"DAUO",
   :city=>"El Oued",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"El Oued, Algeria"},
 "EBW"=>
  {:iata=>"EBW",
   :name=>"Ebolowa Airport",
   :icao=>"FKKW",
   :city=>"Ebolowa",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Ebolowa, Cameroon"},
 "EPN"=>
  {:iata=>"EPN",
   :name=>"Epéna Airport",
   :icao=>"",
   :city=>"Epéna",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Epéna, Republic of Congo"},
 "EWO"=>
  {:iata=>"EWO",
   :name=>"Ewo Airport",
   :icao=>"FCOE",
   :city=>"Ewo",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Ewo, Republic of Congo"},
 "ETE"=>
  {:iata=>"ETE",
   :name=>"Genda Wuha Airport",
   :icao=>"HAMM",
   :city=>"Genda Wuha",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Genda Wuha, Ethiopia"},
 "EGL"=>
  {:iata=>"EGL",
   :name=>"Neghele Airport",
   :icao=>"HANG",
   :city=>"Negele Boran",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Negele Boran, Ethiopia"},
 "EDL"=>
  {:iata=>"EDL",
   :name=>"Eldoret International Airport",
   :icao=>"HKEL",
   :city=>"Eldoret",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Eldoret, Kenya"},
 "EYS"=>
  {:iata=>"EYS",
   :name=>"Eliye Springs Airport",
   :icao=>"HKES",
   :city=>"Eliye Springs",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Eliye Springs, Kenya"},
 "EYL"=>
  {:iata=>"EYL",
   :name=>"Yélimané Airport",
   :icao=>"GAYE",
   :city=>"Yélimané",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Yélimané, Mali"},
 "EMN"=>
  {:iata=>"EMN",
   :name=>"Nema Airport",
   :icao=>"GQNI",
   :city=>"Nema",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Nema, Mauritania"},
 "ERH"=>
  {:iata=>"ERH",
   :name=>"Moulay Ali Cherif Airport",
   :icao=>"GMFK",
   :city=>"Er-Rachidia (Errachidia)",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Er-Rachidia (Errachidia), Morocco"},
 "ESU"=>
  {:iata=>"ESU",
   :name=>"Essaouira Airport",
   :icao=>"GMMI",
   :city=>"Essaouira",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Essaouira, Morocco"},
 "EUN"=>
  {:iata=>"EUN",
   :name=>"Hassan I Airport",
   :icao=>"GMML",
   :city=>"El Aaiún (Laayoune)",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"El Aaiún (Laayoune), Morocco"},
 "ERS"=>
  {:iata=>"ERS",
   :name=>"Eros Airport",
   :icao=>"FYWE",
   :city=>"Windhoek",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Windhoek, Namibia"},
 "ENU"=>
  {:iata=>"ENU",
   :name=>"Enugu Airport",
   :icao=>"DNEN",
   :city=>"Enugu",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Enugu, Nigeria"},
 "ERA"=>
  {:iata=>"ERA",
   :name=>"Erigavo Airport",
   :icao=>"HCMU",
   :city=>"Erigavo",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Erigavo, Somalia"},
 "ELS"=>
  {:iata=>"ELS",
   :name=>"East London Airport",
   :icao=>"FAEL",
   :city=>"East London",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"East London, South Africa"},
 "ELL"=>
  {:iata=>"ELL",
   :name=>"Ellisras Airport",
   :icao=>"FAER",
   :city=>"Ellisras",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Ellisras, South Africa"},
 "EMG"=>
  {:iata=>"EMG",
   :name=>"Empangeni Airport",
   :icao=>"FAEM",
   :city=>"Empangeni",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Empangeni, South Africa"},
 "ELF"=>
  {:iata=>"ELF",
   :name=>"El Fasher Airport",
   :icao=>"HSFS",
   :city=>"El Fasher",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"El Fasher, Sudan"},
 "EBD"=>
  {:iata=>"EBD",
   :name=>"El Obeid Airport",
   :icao=>"HSOB",
   :city=>"El Obeid",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"El Obeid, Sudan"},
 "EGN"=>
  {:iata=>"EGN",
   :name=>"Geneina Airport",
   :icao=>"HSGN",
   :city=>"Geneina",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Geneina, Sudan"},
 "EDB"=>
  {:iata=>"EDB",
   :name=>"El Debba Airport",
   :icao=>"HSDB",
   :city=>"El Debba (Al Dabbah)",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"El Debba (Al Dabbah), Sudan"},
 "EBM"=>
  {:iata=>"EBM",
   :name=>"El Borma Airport",
   :icao=>"DTTR",
   :city=>"El Borma",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"El Borma, Tunisia"},
 "EBB"=>
  {:iata=>"EBB",
   :name=>"Entebbe International Airport",
   :icao=>"HUEN",
   :city=>"Entebbe",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Entebbe, Uganda"},
 "ECN"=>
  {:iata=>"ECN",
   :name=>"Ercan Airport",
   :city=>"Ercan",
   :icao=>"LCEN",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Ercan, Cyprus"},
 "EPK"=>
  {:iata=>"EPK",
   :name=>"Episkopi Airport",
   :icao=>"",
   :city=>"Episkopi",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Episkopi, Cyprus"},
 "EBJ"=>
  {:iata=>"EBJ",
   :name=>"Esbjerg Airport",
   :icao=>"EKEB",
   :city=>"Esbjerg",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Esbjerg, Denmark"},
 "EPU"=>
  {:iata=>"EPU",
   :name=>"Pärnu Airport",
   :icao=>"EEPU",
   :city=>"Pärnu",
   :country=>'Estonia', :country_code=>'EE',
   :location=>"Pärnu, Estonia"},
 "ENF"=>
  {:iata=>"ENF",
   :name=>"Enontekiö Airport",
   :icao=>"EFET",
   :city=>"Enontekiö",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Enontekiö, Finland"},
 "EGC"=>
  {:iata=>"EGC",
   :name=>"Bergerac-Roumanière Airport",
   :icao=>"LFBE",
   :city=>"Bergerac",
   :country=>'France', :country_code=>'FR',
   :location=>"Bergerac, France"},
 "EPL"=>
  {:iata=>"EPL",
   :name=>"Épinal - Mirecourt Airport",
   :icao=>"LFSG",
   :city=>"Juvaincourt",
   :country=>'France', :country_code=>'FR',
   :location=>"Juvaincourt, Vosges, France"},
 "ETZ"=>
  {:iata=>"ETZ",
   :name=>"Metz-Nancy-Lorraine Airport",
   :icao=>"LFJL",
   :city=>"Lorraine",
   :country=>'France', :country_code=>'FR',
   :location=>"Lorraine, France"},
 "EBU"=>
  {:iata=>"EBU",
   :name=>"Saint-Étienne - Bouthéon Airport",
   :icao=>"LFMH",
   :city=>"Saint-Étienne / Bouthéon",
   :country=>'France', :country_code=>'FR',
   :location=>"Saint-Étienne / Bouthéon, France"},
 "EVX"=>
  {:iata=>"EVX",
   :name=>"Évreux-Fauville Air Base",
   :icao=>"LFOE",
   :city=>"Évreux / Fauville",
   :country=>'France', :country_code=>'FR',
   :location=>"Évreux / Fauville, France"},
 "EDM"=>
  {:iata=>"EDM",
   :name=>"La Roche-sur-Yon Aerodrome",
   :icao=>"LFRI",
   :city=>"La Roche-sur-Yon / Les Ajoncs",
   :country=>'France', :country_code=>'FR',
   :location=>"La Roche-sur-Yon / Les Ajoncs, France"},
 "ENC"=>
  {:iata=>"ENC",
   :name=>"Essey Airport",
   :icao=>"LFSN",
   :city=>"Nancy",
   :country=>'France', :country_code=>'FR',
   :location=>"Nancy, France"},
 "ERF"=>
  {:iata=>"ERF",
   :name=>"Erfurt Airport",
   :icao=>"EDDE",
   :city=>"Erfurt",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Erfurt, Germany"},
 "ESS"=>
  {:iata=>"ESS",
   :name=>"Essen/Mülheim Airport",
   :icao=>"EDLE",
   :city=>"Essen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Essen, Germany"},
 "EIB"=>
  {:iata=>"EIB",
   :name=>"Eisenach Airport",
   :city=>"Eisenach",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Eisenach, Germany"},
 "EME"=>
  {:iata=>"EME",
   :name=>"Emden Airport",
   :icao=>"EDWE",
   :city=>"Emden",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Emden, Lower Saxony, Germany"},
 "EUM"=>
  {:iata=>"EUM",
   :name=>"Wasbek Airport",
   :icao=>"EDHN",
   :city=>"Neumünster",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Neumünster, Schleswig-Holstein, Germany"},
 "EFL"=>
  {:iata=>"EFL",
   :name=>"Argostolion Airport",
   :icao=>"LGKF",
   :city=>"Kefallinia Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kefallinia Island, Greece"},
 "EGS"=>
  {:iata=>"EGS",
   :name=>"Egilsstaðir Airport",
   :icao=>"BIEG",
   :city=>"Egilsstaðir",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Egilsstaðir, Iceland"},
 "EBA"=>
  {:iata=>"EBA",
   :name=>"Marina di Campo Airport",
   :icao=>"LIRJ",
   :city=>"Elba",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Elba, Italy"},
 "EIN"=>
  {:iata=>"EIN",
   :name=>"Eindhoven Airport",
   :icao=>"EHEH",
   :city=>"Eindhoven",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Eindhoven, Netherlands"},
 "ENS"=>
  {:iata=>"ENS",
   :name=>"Enschede Airport Twente",
   :icao=>"EHTW",
   :city=>"Enschede",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Enschede, Netherlands"},
 "EVE"=>
  {:iata=>"EVE",
   :name=>"Harstad/Narvik Airport, Evenes",
   :icao=>"ENEV",
   :city=>"Evenes",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Evenes, Norway"},
 "EGO"=>
  {:iata=>"EGO",
   :name=>"Belgorod Airport",
   :icao=>"UUOB",
   :city=>"Belgorod",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Belgorod, Russia"},
 "EYK"=>
  {:iata=>"EYK",
   :name=>"Beloyarsk Airport",
   :icao=>"USHQ",
   :city=>"Khanty-Mansi Autonomous Okrug",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Khanty-Mansi Autonomous Okrug, Russia"},
 "EZV"=>
  {:iata=>"EZV",
   :name=>"Beryozovo Airport",
   :city=>"Beryozovo",
   :icao=>"USHB",
   :country=>'Federation', :country_code=>'',
   :location=>"Beryozovo, Federation"},
 "ESL"=>
  {:iata=>"ESL",
   :name=>"Elista Airport",
   :icao=>"URWI",
   :city=>"Elista",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Elista, Kalmykia, Russia"},
 "EIE"=>
  {:iata=>"EIE",
   :name=>"Yeniseysk Airport",
   :icao=>"UNII",
   :city=>"Yeniseysk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Yeniseysk, Russia"},
 "ERG"=>
  {:iata=>"ERG",
   :name=>"Erbogachen Airport",
   :icao=>"UIKE",
   :city=>"Yerbogachen",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Yerbogachen, Katangsky District, Irkutsk Oblast, Russia"},
 "EKS"=>
  {:iata=>"EKS",
   :name=>"Shakhtyorsk Airport",
   :city=>"Shakhtyorsk",
   :icao=>"UHSK",
   :country=>'Federation', :country_code=>'',
   :location=>"Shakhtyorsk, Federation"},
 "EAS"=>
  {:iata=>"EAS",
   :name=>"San Sebastián Airport (or Fuenterrabia Airport)",
   :icao=>"LESO",
   :city=>"San Sebastián",
   :country=>'Spain', :country_code=>'ES',
   :location=>"San Sebastián, Spain"},
 "EVG"=>
  {:iata=>"EVG",
   :name=>"Sveg Airport",
   :icao=>"ESND",
   :city=>"Sveg",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Sveg, Sweden"},
 "EKT"=>
  {:iata=>"EKT",
   :name=>"Eskilstuna Airport",
   :icao=>"ESSU",
   :city=>"Eskilstuna",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Eskilstuna, Sweden"},
 "EML"=>
  {:iata=>"EML",
   :name=>"Emmen Air Base",
   :icao=>"LSME",
   :city=>"Emmen",
   :country=>'Switzerland', :country_code=>'CH',
   :location=>"Emmen, Lucerne, Switzerland"},
 "ESB"=>
  {:iata=>"ESB",
   :name=>"Esenboğa International Airport",
   :icao=>"LTAC",
   :city=>"Ankara",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Ankara, Turkey"},
 "EDO"=>
  {:iata=>"EDO",
   :name=>"Edremit Körfez Airport",
   :icao=>"LTFD",
   :city=>"Balıkesir",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Balıkesir, Turkey"},
 "EZS"=>
  {:iata=>"EZS",
   :name=>"Elazığ Airport",
   :icao=>"LTCA",
   :city=>"Elazığ",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Elazığ, Turkey"},
 "ERC"=>
  {:iata=>"ERC",
   :name=>"Erzincan Airport",
   :icao=>"LTCD",
   :city=>"Erzincan",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Erzincan, Turkey"},
 "ERZ"=>
  {:iata=>"ERZ",
   :name=>"Erzurum Airport",
   :icao=>"LTCE",
   :city=>"Erzurum",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Erzurum, Turkey"},
 "ESK"=>
  {:iata=>"ESK",
   :name=>"Eskişehir Airport",
   :icao=>"LTBI",
   :city=>"Eskişehir",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Eskişehir, Turkey"},
 "ERD"=>
  {:iata=>"ERD",
   :name=>"Berdyansk Airport",
   :icao=>"UKDB",
   :city=>"Berdyansk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Berdyansk, Ukraine"},
 "EDI"=>
  {:iata=>"EDI",
   :name=>"Edinburgh Airport",
   :icao=>"EGPH",
   :city=>"Edinburgh",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Edinburgh, United Kingdom"},
 "EOI"=>
  {:iata=>"EOI",
   :name=>"Eday Airport",
   :icao=>"EGED",
   :city=>"Eday",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Eday, Scotland, United Kingdom"},
 "EXT"=>
  {:iata=>"EXT",
   :name=>"Exeter International Airport",
   :icao=>"EGTE",
   :city=>"Exeter",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Exeter, United Kingdom"},
 "EMA"=>
  {:iata=>"EMA",
   :name=>"East Midlands Airport",
   :icao=>"EGNX",
   :city=>"Castle Donington",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Castle Donington, Leicestershire, United Kingdom"},
 "ENK"=>
  {:iata=>"ENK",
   :name=>"Enniskillen/St Angelo Airport",
   :icao=>"EGAB",
   :city=>"Enniskillen",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Enniskillen, Co Fermanagh, Northern Ireland, United Kingdom"},
 "EWY"=>
  {:iata=>"EWY",
   :name=>"Greenham Royal Air Force",
   :city=>"Newbury",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Newbury, Kingdom"},
 "ESH"=>
  {:iata=>"ESH",
   :name=>"Shoreham Airport",
   :icao=>"EGKA",
   :city=>"Lancing",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Lancing, West Sussex, United Kingdom"},
 "EVN"=>
  {:iata=>"EVN",
   :name=>"Zvartnots International Airport",
   :icao=>"UDYZ",
   :city=>"Yerevan",
   :country=>'Armenia', :country_code=>'AM',
   :location=>"Yerevan, Armenia"},
 "EJN"=>
  {:iata=>"EJN",
   :name=>"Ejin Banner Taolai Airport",
   :icao=>"",
   :city=>"Ejin Banner",
   :country=>'China', :country_code=>'CN',
   :location=>"Ejin Banner, Inner Mongolia, China"},
 "ENH"=>
  {:iata=>"ENH",
   :name=>"Enshi Airport",
   :icao=>"ZHES",
   :city=>"Enshi",
   :country=>'China', :country_code=>'CN',
   :location=>"Enshi, Hubei, China"},
 "ERL"=>
  {:iata=>"ERL",
   :name=>"Erenhot Saiwusu International Airport",
   :icao=>"ZBER",
   :city=>"Erenhot",
   :country=>'China', :country_code=>'CN',
   :location=>"Erenhot, Inner Mongolia, China"},
 "ENY"=>
  {:iata=>"ENY",
   :name=>"Yan'an Ershilibao Airport",
   :icao=>"ZLYA",
   :city=>"Yan'an",
   :country=>'China', :country_code=>'CN',
   :location=>"Yan'an, Shaanxi, China"},
 "ENE"=>
  {:iata=>"ENE",
   :name=>"H. Hasan Aroeboesman Airport",
   :icao=>"WATE",
   :city=>"Ende",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ende, Flores, Indonesia"},
 "ELR"=>
  {:iata=>"ELR",
   :name=>"Irian Jaya Airport (Elelim Airport)",
   :icao=>"",
   :city=>"Elelim",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Elelim, Indonesia"},
 "EWI"=>
  {:iata=>"EWI",
   :name=>"Enarotali Airport",
   :icao=>"WABT",
   :city=>"Enarotali",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Enarotali, Indonesia"},
 "EWE"=>
  {:iata=>"EWE",
   :name=>"Ewer Airport",
   :icao=>"",
   :city=>"Ewer",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ewer, Indonesia"},
 "EKB"=>
  {:iata=>"EKB",
   :name=>"Ekibastuz Airport",
   :icao=>"UASB",
   :city=>"Ekibastuz",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Ekibastuz, Kazakhstan"},
 "ERT"=>
  {:iata=>"ERT",
   :name=>"Erdenet Airport",
   :icao=>"",
   :city=>"Erdenet",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Erdenet, Mongolia"},
 "EFG"=>
  {:iata=>"EFG",
   :name=>"Efogi Airport",
   :icao=>"AYEF",
   :city=>"Efogi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Efogi, Papua New Guinea"},
 "EIA"=>
  {:iata=>"EIA",
   :name=>"Popondetta Airport",
   :icao=>"",
   :city=>"Eia",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Eia, Papua New Guinea"},
 "EPT"=>
  {:iata=>"EPT",
   :name=>"Eliptamin Airport",
   :icao=>"AYEL",
   :city=>"Eliptamin",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Eliptamin, Papua New Guinea"},
 "EMS"=>
  {:iata=>"EMS",
   :name=>"Embessa Airport",
   :icao=>"AYEB",
   :city=>"Embessa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Embessa, Papua New Guinea"},
 "EMI"=>
  {:iata=>"EMI",
   :name=>"Emirau Airport",
   :icao=>"AYEE",
   :city=>"Emirau",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Emirau, Papua New Guinea"},
 "EMO"=>
  {:iata=>"EMO",
   :name=>"Emo Airport",
   :icao=>"AYEO",
   :city=>"Emo",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Emo, Papua New Guinea"},
 "EGA"=>
  {:iata=>"EGA",
   :name=>"Engati Airport",
   :icao=>"AYEN",
   :city=>"Engati",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Engati, Papua New Guinea"},
 "ERE"=>
  {:iata=>"ERE",
   :name=>"Erave Airport",
   :icao=>"AYEV",
   :city=>"Erave",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Erave, Papua New Guinea"},
 "ERU"=>
  {:iata=>"ERU",
   :name=>"Erume Airport",
   :icao=>"AYER",
   :city=>"Erume",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Erume, Papua New Guinea"},
 "ESA"=>
  {:iata=>"ESA",
   :name=>"Esa'ala Airport",
   :icao=>"",
   :city=>"Esa'ala",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Esa'ala, Papua New Guinea"},
 "ENI"=>
  {:iata=>"ENI",
   :name=>"El Nido Airport",
   :icao=>"RPEN",
   :city=>"El Nido",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"El Nido, Palawan, Philippines"},
 "EUQ"=>
  {:iata=>"EUQ",
   :name=>"Evelio Javier (Antique) Airport",
   :icao=>"RPVS",
   :city=>"San Jose de Buenavista",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"San Jose de Buenavista, Antique, Philippines"},
 "ENJ"=>
  {:iata=>"ENJ",
   :name=>"El Naranjo Airport",
   :icao=>"",
   :city=>"El Naranjo",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"El Naranjo, El Petén, Guatemala"},
 "ENQ"=>
  {:iata=>"ENQ",
   :name=>"Coronel Enrique Soto Cano AB Airport",
   :city=>"Coronel Enrique Soto Cano AB",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Coronel Enrique Soto Cano AB, Honduras"},
 "EDQ"=>
  {:iata=>"EDQ",
   :name=>"Erandique Airport",
   :icao=>"",
   :city=>"Erandique",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Erandique, Honduras"},
 "ELE"=>
  {:iata=>"ELE",
   :name=>"El Real Airport",
   :icao=>"",
   :city=>"El Real",
   :country=>'Panama', :country_code=>'PA',
   :location=>"El Real, Panama"},
 "EMY"=>
  {:iata=>"EMY",
   :name=>"El Minya Airport",
   :icao=>"HEMN",
   :city=>"El Minya",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"El Minya, Egypt"},
 "ELT"=>
  {:iata=>"ELT",
   :name=>"Tour Sinai City Airport",
   :icao=>"HETR",
   :city=>"El Tor",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"El Tor, Egypt"},
 "EBL"=>
  {:iata=>"EBL",
   :name=>"Erbil International Airport",
   :icao=>"ORER",
   :city=>"Erbil",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Erbil, Kurdistan, Iraq"},
 "ETH"=>
  {:iata=>"ETH",
   :name=>"J. Hozman Airport",
   :icao=>"LLET",
   :city=>"Eilat",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Eilat, Israel"},
 "EIY"=>
  {:iata=>"EIY",
   :name=>"Ein Yahav Airfield",
   :icao=>"LLEY",
   :city=>"Ein Yahav",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Ein Yahav, Israel"},
 "EAB"=>
  {:iata=>"EAB",
   :name=>"Abbse Airport",
   :icao=>"ODAS",
   :city=>"Abbse",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Abbse, Yemen"},
 "ELQ"=>
  {:iata=>"ELQ",
   :name=>"Gassim Regional Airport",
   :icao=>"OEGS",
   :city=>"Buraidah",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Buraidah, Saudi Arabia"},
 "EAM"=>
  {:iata=>"EAM",
   :name=>"Najran Domestic Airport",
   :icao=>"OENG",
   :city=>"Najran (Nejran)",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Najran (Nejran), Saudi Arabia"},
 "EJH"=>
  {:iata=>"EJH",
   :name=>"Wejh Airport",
   :icao=>"OEWJ",
   :city=>"Wejh",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Wejh, Saudi Arabia"},
 "EAA"=>
  {:iata=>"EAA",
   :name=>"Eagle Airport",
   :icao=>"PAEG",
   :city=>"Eagle",
   :country=>'United States', :country_code=>'US',

   :location=>"Eagle, Alaska, United States"},
 "EAP"=>
  {:iata=>"EAP",
   :name=>"All airports",
   :icao=>"",
   :city=>"Mulhouse",
   :country=>'Switzerland', :country_code=>'CH',
   :location=>"Mulhouse, France / Basel, Switzerland"},
 "EAR"=>
  {:iata=>"EAR",
   :name=>"Kearney Regional Airport",
   :icao=>"KEAR",
   :city=>"Kearney",
   :country=>'United States', :country_code=>'US',

   :location=>"Kearney, Nebraska, United States"},
 "EAT"=>
  {:iata=>"EAT",
   :name=>"Pangborn Memorial Airport",
   :icao=>"KEAT",
   :city=>"Wenatchee",
   :country=>'United States', :country_code=>'US',

   :location=>"Wenatchee, Washington, United States"},
 "EAU"=>
  {:iata=>"EAU",
   :name=>"Chippewa Valley Regional Airport",
   :icao=>"KEAU",
   :city=>"Eau Claire",
   :country=>'United States', :country_code=>'US',

   :location=>"Eau Claire, Wisconsin, United States"},
 "EBS"=>
  {:iata=>"EBS",
   :name=>"Webster City Municipal Airport",
   :icao=>"KEBS",
   :city=>"Webster City",
   :country=>'United States', :country_code=>'US',

   :location=>"Webster City, Iowa, United States"},
 "ECA"=>
  {:iata=>"ECA",
   :name=>"Iosco County Airport (FAA: 6D9)",
   :icao=>"",
   :city=>"East Tawas",
   :country=>'United States', :country_code=>'US',

   :location=>"East Tawas, Michigan, United States"},
 "ECG"=>
  {:iata=>"ECG",
   :name=>"Elizabeth City Regional Airport / Elizabeth City CGAS",
   :icao=>"KECG",
   :city=>"Elizabeth City",
   :country=>'United States', :country_code=>'US',

   :location=>"Elizabeth City, North Carolina, United States"},
 "ECP"=>
  {:iata=>"ECP",
   :name=>"Northwest Florida Beaches International Airport",
   :icao=>"KECP",
   :city=>"Panama City",
   :country=>'United States', :country_code=>'US',

   :location=>"Panama City, Florida, United States"},
 "EDA"=>
  {:iata=>"EDA",
   :name=>"Edna Bay Municipal Airport (or Seaplane Base?)",
   :icao=>"",
   :city=>"Edna Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Edna Bay, Alaska, United States"},
 "EDC"=>
  {:iata=>"EDC",
   :name=>"Austin Executive Airport",
   :icao=>"KEDC",
   :city=>"Austin",
   :country=>'United States', :country_code=>'US',

   :location=>"Austin, Texas, United States"},
 "EDE"=>
  {:iata=>"EDE",
   :name=>"Northeastern Regional Airport",
   :icao=>"KEDE",
   :city=>"Edenton",
   :country=>'United States', :country_code=>'US',

   :location=>"Edenton, North Carolina, United States"},
 "EDF"=>
  {:iata=>"EDF",
   :name=>"Elmendorf Air Force Base",
   :icao=>"PAED",
   :city=>"Anchorage",
   :country=>'United States', :country_code=>'US',

   :location=>"Anchorage, Alaska, United States"},
 "EDG"=>
  {:iata=>"EDG",
   :name=>"Weide Army Airfield",
   :icao=>"KEDG",
   :city=>"Edgewood Arsenal",
   :country=>'United States', :country_code=>'US',

   :location=>"Edgewood Arsenal, Maryland, United States"},
 "EDK"=>
  {:iata=>"EDK",
   :name=>"Captain Jack Thomas/El Dorado Airport (FAA: EQA)",
   :icao=>"KEQA",
   :city=>"El Dorado",
   :country=>'United States', :country_code=>'US',

   :location=>"El Dorado, Kansas, United States"},
 "EDW"=>
  {:iata=>"EDW",
   :name=>"Edwards Air Force Base",
   :icao=>"KEDW",
   :city=>"Edwards",
   :country=>'United States', :country_code=>'US',

   :location=>"Edwards, California, United States"},
 "EED"=>
  {:iata=>"EED",
   :name=>"Needles Airport",
   :icao=>"KEED",
   :city=>"Needles",
   :country=>'United States', :country_code=>'US',

   :location=>"Needles, California, United States"},
 "EEK"=>
  {:iata=>"EEK",
   :name=>"Eek Airport",
   :icao=>"PAEE",
   :city=>"Eek",
   :country=>'United States', :country_code=>'US',

   :location=>"Eek, Alaska, United States"},
 "EEN"=>
  {:iata=>"EEN",
   :name=>"Dillant-Hopkins Airport",
   :icao=>"KEEN",
   :city=>"Keene",
   :country=>'United States', :country_code=>'US',

   :location=>"Keene, New Hampshire, United States"},
 "EFD"=>
  {:iata=>"EFD",
   :name=>"Ellington Field",
   :icao=>"KEFD",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "EFK"=>
  {:iata=>"EFK",
   :name=>"Newport State Airport",
   :icao=>"KEFK",
   :city=>"Newport",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport, Vermont, United States"},
 "EFW"=>
  {:iata=>"EFW",
   :name=>"Jefferson Municipal Airport",
   :icao=>"KEFW",
   :city=>"Jefferson",
   :country=>'United States', :country_code=>'US',

   :location=>"Jefferson, Iowa, United States"},
 "EGE"=>
  {:iata=>"EGE",
   :name=>"Eagle County Regional Airport",
   :icao=>"KEGE",
   :city=>"Eagle",
   :country=>'United States', :country_code=>'US',

   :location=>"Eagle, Colorado (near Vail), United States"},
 "EGI"=>
  {:iata=>"EGI",
   :name=>"Duke Field (Eglin Auxiliary Field 3)",
   :icao=>"KEGI",
   :city=>"Crestview",
   :country=>'United States', :country_code=>'US',

   :location=>"Crestview, Florida, United States"},
 "EGP"=>
  {:iata=>"EGP",
   :name=>"Maverick County Airport",
   :icao=>"",
   :city=>"Eagle Pass",
   :country=>'United States', :country_code=>'US',

   :location=>"Eagle Pass, Texas, United States"},
 "EGV"=>
  {:iata=>"EGV",
   :name=>"Eagle River Union Airport",
   :icao=>"KEGV",
   :city=>"Eagle River",
   :country=>'United States', :country_code=>'US',

   :location=>"Eagle River, Wisconsin, United States"},
 "EGX"=>
  {:iata=>"EGX",
   :name=>"Egegik Airport (FAA: EII)",
   :icao=>"PAII",
   :city=>"Egegik",
   :country=>'United States', :country_code=>'US',

   :location=>"Egegik, Alaska, United States"},
 "EHM"=>
  {:iata=>"EHM",
   :name=>"Cape Newenham LRRS Airport",
   :icao=>"PAEH",
   :city=>"Cape Newenham",
   :country=>'United States', :country_code=>'US',

   :location=>"Cape Newenham, Alaska, United States"},
 "EHT"=>
  {:iata=>"EHT",
   :name=>"Rentschler Heliport (FAA: CT88)",
   :icao=>"",
   :city=>"East Hartford",
   :country=>'United States', :country_code=>'US',

   :location=>"East Hartford, Connecticut, United States"},
 "EIL"=>
  {:iata=>"EIL",
   :name=>"Eielson Air Force Base",
   :icao=>"PAEI",
   :city=>"Fairbanks",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairbanks, Alaska, United States"},
 "EKA"=>
  {:iata=>"EKA",
   :name=>"Murray Field",
   :icao=>"KEKA",
   :city=>"Eureka",
   :country=>'United States', :country_code=>'US',

   :location=>"Eureka, California, United States"},
 "EKI"=>
  {:iata=>"EKI",
   :name=>"Elkhart Municipal Airport (FAA: EKM)",
   :icao=>"KEKM",
   :city=>"Elkhart",
   :country=>'United States', :country_code=>'US',

   :location=>"Elkhart, Indiana, United States"},
 "EKN"=>
  {:iata=>"EKN",
   :name=>"Elkins-Randolph Co.-Jennings Randolph Field",
   :icao=>"KEKN",
   :city=>"Elkins",
   :country=>'United States', :country_code=>'US',

   :location=>"Elkins, West Virginia, United States"},
 "EKO"=>
  {:iata=>"EKO",
   :name=>"Elko Regional Airport",
   :icao=>"KEKO",
   :city=>"Elko",
   :country=>'United States', :country_code=>'US',

   :location=>"Elko, Nevada, United States"},
 "EKX"=>
  {:iata=>"EKX",
   :name=>"Addington Field (Elizabethtown Regional Airport)",
   :icao=>"KEKX",
   :city=>"Elizabethtown",
   :country=>'United States', :country_code=>'US',

   :location=>"Elizabethtown, Kentucky, United States"},
 "ELA"=>
  {:iata=>"ELA",
   :name=>"Eagle Lake Airport",
   :icao=>"KELA",
   :city=>"Eagle Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Eagle Lake, Texas, United States"},
 "ELD"=>
  {:iata=>"ELD",
   :name=>"South Arkansas Regional Airport at Goodwin Field",
   :icao=>"KELD",
   :city=>"El Dorado",
   :country=>'United States', :country_code=>'US',

   :location=>"El Dorado, Arkansas, United States"},
 "ELI"=>
  {:iata=>"ELI",
   :name=>"Elim Airport",
   :icao=>"PFEL",
   :city=>"Elim",
   :country=>'United States', :country_code=>'US',

   :location=>"Elim, Alaska, United States"},
 "ELK"=>
  {:iata=>"ELK",
   :name=>"Elk City Municipal Airport",
   :icao=>"KELK",
   :city=>"Elk City",
   :country=>'United States', :country_code=>'US',

   :location=>"Elk City, Oklahoma, United States"},
 "ELM"=>
  {:iata=>"ELM",
   :name=>"Elmira/Corning Regional Airport",
   :icao=>"KELM",
   :city=>"Elmira/Big Flats",
   :country=>'United States', :country_code=>'US',

   :location=>"Elmira/Big Flats, New York, United States"},
 "ELN"=>
  {:iata=>"ELN",
   :name=>"Bowers Field",
   :icao=>"KELN",
   :city=>"Ellensburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Ellensburg, Washington, United States"},
 "ELP"=>
  {:iata=>"ELP",
   :name=>"El Paso International Airport",
   :icao=>"KELP",
   :city=>"El Paso",
   :country=>'United States', :country_code=>'US',

   :location=>"El Paso, Texas, United States"},
 "ELV"=>
  {:iata=>"ELV",
   :name=>"Elfin Cove Seaplane Base",
   :icao=>"PAEL",
   :city=>"Elfin Cove",
   :country=>'United States', :country_code=>'US',

   :location=>"Elfin Cove, Alaska, United States"},
 "ELW"=>
  {:iata=>"ELW",
   :name=>"Ellamar Seaplane Base (FAA: 1Z9)",
   :icao=>"",
   :city=>"Ellamar",
   :country=>'United States', :country_code=>'US',

   :location=>"Ellamar, Alaska, United States"},
 "ELY"=>
  {:iata=>"ELY",
   :name=>"Ely Airport",
   :icao=>"KELY",
   :city=>"Ely",
   :country=>'United States', :country_code=>'US',

   :location=>"Ely, Nevada, United States"},
 "ELZ"=>
  {:iata=>"ELZ",
   :name=>"Wellsville Municipal Airport (Tarantine Field)",
   :icao=>"KELZ",
   :city=>"Wellsville",
   :country=>'United States', :country_code=>'US',

   :location=>"Wellsville, New York, United States"},
 "EMK"=>
  {:iata=>"EMK",
   :name=>"Emmonak Airport (FAA: ENM)",
   :icao=>"PAEM",
   :city=>"Emmonak",
   :country=>'United States', :country_code=>'US',

   :location=>"Emmonak, Alaska, United States"},
 "EMP"=>
  {:iata=>"EMP",
   :name=>"Emporia Municipal Airport",
   :icao=>"KEMP",
   :city=>"Emporia",
   :country=>'United States', :country_code=>'US',

   :location=>"Emporia, Kansas, United States"},
 "EMT"=>
  {:iata=>"EMT",
   :name=>"El Monte Airport",
   :icao=>"KEMT",
   :city=>"El Monte",
   :country=>'United States', :country_code=>'US',

   :location=>"El Monte, California, United States"},
 "ENA"=>
  {:iata=>"ENA",
   :name=>"Kenai Municipal Airport",
   :icao=>"PAEN",
   :city=>"Kenai",
   :country=>'United States', :country_code=>'US',

   :location=>"Kenai, Alaska, United States"},
 "END"=>
  {:iata=>"END",
   :name=>"Vance Air Force Base",
   :icao=>"KEND",
   :city=>"Enid",
   :country=>'United States', :country_code=>'US',

   :location=>"Enid, Oklahoma, United States"},
 "ENL"=>
  {:iata=>"ENL",
   :name=>"Centralia Municipal Airport",
   :icao=>"KENL",
   :city=>"Centralia",
   :country=>'United States', :country_code=>'US',

   :location=>"Centralia, Illinois, United States"},
 "ENN"=>
  {:iata=>"ENN",
   :name=>"Nenana Municipal Airport",
   :icao=>"PANN",
   :city=>"Nenana",
   :country=>'United States', :country_code=>'US',

   :location=>"Nenana, Alaska, United States"},
 "ENV"=>
  {:iata=>"ENV",
   :name=>"Wendover Airport",
   :icao=>"KENV",
   :city=>"Wendover",
   :country=>'United States', :country_code=>'US',

   :location=>"Wendover, Utah, United States"},
 "ENW"=>
  {:iata=>"ENW",
   :name=>"Kenosha Regional Airport",
   :icao=>"KENW",
   :city=>"Kenosha",
   :country=>'United States', :country_code=>'US',

   :location=>"Kenosha, Wisconsin, United States"},
 "EOK"=>
  {:iata=>"EOK",
   :name=>"Keokuk Municipal Airport",
   :icao=>"KEOK",
   :city=>"Keokuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Keokuk, Iowa, United States"},
 "EOS"=>
  {:iata=>"EOS",
   :name=>"Neosho Hugh Robinson Airport",
   :icao=>"KEOS",
   :city=>"Neosho",
   :country=>'United States', :country_code=>'US',

   :location=>"Neosho, Missouri, United States"},
 "EPG"=>
  {:iata=>"EPG",
   :name=>"Browns Airport (FAA: NE69)",
   :icao=>"",
   :city=>"Weeping Water",
   :country=>'United States', :country_code=>'US',

   :location=>"Weeping Water, Nebraska, United States"},
 "EPH"=>
  {:iata=>"EPH",
   :name=>"Ephrata Municipal Airport",
   :icao=>"KEPH",
   :city=>"Ephrata",
   :country=>'United States', :country_code=>'US',

   :location=>"Ephrata, Washington, United States"},
 "ERI"=>
  {:iata=>"ERI",
   :name=>"Erie International Airport (Tom Ridge Field)",
   :icao=>"KERI",
   :city=>"Erie",
   :country=>'United States', :country_code=>'US',

   :location=>"Erie, Pennsylvania, United States"},
 "ERR"=>
  {:iata=>"ERR",
   :name=>"Errol Airport",
   :icao=>"KERR",
   :city=>"Errol",
   :country=>'United States', :country_code=>'US',

   :location=>"Errol, New Hampshire, United States"},
 "ERV"=>
  {:iata=>"ERV",
   :name=>"Kerrville Municipal Airport (Louis Schreiner Field)",
   :icao=>"KERV",
   :city=>"Kerrville",
   :country=>'United States', :country_code=>'US',

   :location=>"Kerrville, Texas, United States"},
 "ESC"=>
  {:iata=>"ESC",
   :name=>"Delta County Airport",
   :icao=>"KESC",
   :city=>"Escanaba",
   :country=>'United States', :country_code=>'US',

   :location=>"Escanaba, Michigan, United States"},
 "ESD"=>
  {:iata=>"ESD",
   :name=>"Orcas Island Airport (FAA: ORS)",
   :icao=>"KORS",
   :city=>"Eastsound",
   :country=>'United States', :country_code=>'US',

   :location=>"Eastsound, Washington, United States"},
 "ESF"=>
  {:iata=>"ESF",
   :name=>"Esler Regional Airport",
   :icao=>"KESF",
   :city=>"Alexandria",
   :country=>'United States', :country_code=>'US',

   :location=>"Alexandria, Louisiana, United States"},
 "ESN"=>
  {:iata=>"ESN",
   :name=>"Easton/Newnam Field",
   :icao=>"KESN",
   :city=>"Easton",
   :country=>'United States', :country_code=>'US',

   :location=>"Easton, Maryland, United States"},
 "ESO"=>
  {:iata=>"ESO",
   :name=>"Ohkay Owingeh Airport (FAA: E14)",
   :icao=>"",
   :city=>"Española",
   :country=>'United States', :country_code=>'US',

   :location=>"Española, New Mexico, United States"},
 "ESP"=>
  {:iata=>"ESP",
   :name=>"Stroudsburg-Pocono Airport (FAA: N53)",
   :icao=>"",
   :city=>"East Stroudsburg",
   :country=>'United States', :country_code=>'US',

   :location=>"East Stroudsburg, Pennsylvania, United States"},
 "EST"=>
  {:iata=>"EST",
   :name=>"Estherville Municipal Airport",
   :icao=>"KEST",
   :city=>"Estherville",
   :country=>'United States', :country_code=>'US',

   :location=>"Estherville, Iowa, United States"},
 "ESW"=>
  {:iata=>"ESW",
   :name=>"Easton State Airport",
   :icao=>"KESW",
   :city=>"Easton",
   :country=>'United States', :country_code=>'US',

   :location=>"Easton, Washington, United States"},
 "ETB"=>
  {:iata=>"ETB",
   :name=>"West Bend Municipal Airport",
   :icao=>"KETB",
   :city=>"West Bend",
   :country=>'United States', :country_code=>'US',

   :location=>"West Bend, Wisconsin, United States"},
 "ETN"=>
  {:iata=>"ETN",
   :name=>"Eastland Municipal Airport",
   :icao=>"KETN",
   :city=>"Eastland",
   :country=>'United States', :country_code=>'US',

   :location=>"Eastland, Texas, United States"},
 "ETS"=>
  {:iata=>"ETS",
   :name=>"Enterprise Municipal Airport (FAA: EDN)",
   :icao=>"KEDN",
   :city=>"Enterprise",
   :country=>'United States', :country_code=>'US',

   :location=>"Enterprise, Alabama, United States"},
 "EUE"=>
  {:iata=>"EUE",
   :name=>"Eureka Airport (FAA: 05U)",
   :icao=>"",
   :city=>"Eureka",
   :country=>'United States', :country_code=>'US',

   :location=>"Eureka, Nevada, United States"},
 "EUF"=>
  {:iata=>"EUF",
   :name=>"Weedon Field",
   :icao=>"KEUF",
   :city=>"Eufaula",
   :country=>'United States', :country_code=>'US',

   :location=>"Eufaula, Alabama, United States"},
 "EUG"=>
  {:iata=>"EUG",
   :name=>"Eugene Airport / Mahlon Sweet Field",
   :icao=>"KEUG",
   :city=>"Eugene",
   :country=>'United States', :country_code=>'US',

   :location=>"Eugene, Oregon, United States"},
 "EVA"=>
  {:iata=>"EVA",
   :name=>"Ben Bruce Memorial Airpark (FAA: 4TE8)",
   :icao=>"",
   :city=>"Evadale",
   :country=>'United States', :country_code=>'US',

   :location=>"Evadale, Texas, United States"},
 "EVM"=>
  {:iata=>"EVM",
   :name=>"Eveleth-Virginia Municipal Airport",
   :icao=>"KEVM",
   :city=>"Eveleth",
   :country=>'United States', :country_code=>'US',

   :location=>"Eveleth, Minnesota, United States"},
 "EVV"=>
  {:iata=>"EVV",
   :name=>"Evansville Regional Airport",
   :icao=>"KEVV",
   :city=>"Evansville",
   :country=>'United States', :country_code=>'US',

   :location=>"Evansville, Indiana, United States"},
 "EWB"=>
  {:iata=>"EWB",
   :name=>"New Bedford Regional Airport",
   :icao=>"KEWB",
   :city=>"New Bedford",
   :country=>'United States', :country_code=>'US',

   :location=>"New Bedford, Massachusetts, United States"},
 "EWK"=>
  {:iata=>"EWK",
   :name=>"Newton City/County Airport",
   :icao=>"KEWK",
   :city=>"Newton",
   :country=>'United States', :country_code=>'US',

   :location=>"Newton, Kansas, United States"},
 "EWN"=>
  {:iata=>"EWN",
   :name=>"Craven County Regional Airport",
   :icao=>"KEWN",
   :city=>"New Bern",
   :country=>'United States', :country_code=>'US',

   :location=>"New Bern, North Carolina, United States"},
 "EWR"=>
  {:iata=>"EWR",
   :name=>"Newark Liberty International Airport",
   :icao=>"KEWR",
   :city=>"Newark/Elizabeth",
   :country=>'United States', :country_code=>'US',

   :location=>"Newark/Elizabeth, New Jersey, United States"},
 "EXI"=>
  {:iata=>"EXI",
   :name=>"Excursion Inlet Seaplane Base",
   :icao=>"",
   :city=>"Excursion Inlet",
   :country=>'United States', :country_code=>'US',

   :location=>"Excursion Inlet, Alaska, United States"},
 "EYW"=>
  {:iata=>"EYW",
   :name=>"Key West International Airport",
   :icao=>"KEYW",
   :city=>"Key West",
   :country=>'United States', :country_code=>'US',

   :location=>"Key West, Florida, United States"}}

end
