# encoding: UTF-8
def airp_21
  {"TUX"=>
  {:iata=>"TUX",
   :name=>"Tumbler Ridge Airport",
   :city=>"Tumbler Ridge",
   :icao=>"CBX7",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Tumbler Ridge, Canada"},
 "TNS"=>
  {:iata=>"TNS",
   :name=>"Tungsten Airport",
   :city=>"Tungsten",
   :icao=>"CBX5",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Tungsten, Canada"},
 "THU"=>
  {:iata=>"THU",
   :name=>"Thule Air Base",
   :icao=>"BGTL",
   :city=>"Pituffik",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Pituffik, Greenland"},
 "TQA"=>
  {:iata=>"TQA",
   :name=>"Tasiusaq Heliport (Qaasuitsup)",
   :icao=>"BGTA",
   :city=>"Tasiusaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Tasiusaq, Qaasuitsup, Greenland"},
 "TQI"=>
  {:iata=>"TQI",
   :name=>"Tiniteqilaaq Heliport",
   :icao=>"BGTN",
   :city=>"Tiniteqilaaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Tiniteqilaaq, Greenland"},
 "TAM"=>
  {:iata=>"TAM",
   :name=>"General Francisco Javier Mina International Airport",
   :icao=>"MMTM",
   :city=>"Tampico",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tampico, Tamaulipas, Mexico"},
 "TAP"=>
  {:iata=>"TAP",
   :name=>"Tapachula International Airport",
   :icao=>"MMTP",
   :city=>"Tapachula",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tapachula, Chiapas, Mexico"},
 "TPQ"=>
  {:iata=>"TPQ",
   :name=>"Amado Nervo National Airport",
   :icao=>"MMEP",
   :city=>"Tepic",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tepic, Nayarit, Mexico"},
 "TIJ"=>
  {:iata=>"TIJ",
   :name=>"General Abelardo L. Rodríguez International Airport",
   :icao=>"MMTJ",
   :city=>"Tijuana",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tijuana, Baja California, Mexico"},
 "TLC"=>
  {:iata=>"TLC",
   :name=>"Lic. Adolfo López Mateos International Airport",
   :icao=>"MMTO",
   :city=>"Toluca",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Toluca, Estado de México, Mexico"},
 "TRC"=>
  {:iata=>"TRC",
   :name=>"Francisco Sarabia International Airport (Torreón Int'l)",
   :icao=>"MMTC",
   :city=>"Torreón",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Torreón, Coahuila, Mexico"},
 "TGZ"=>
  {:iata=>"TGZ",
   :name=>"Angel Albino Corzo International Airport",
   :icao=>"MMTG",
   :city=>"Tuxtla Gutiérrez",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tuxtla Gutiérrez, Chiapas, Mexico"},
 "TSL"=>
  {:iata=>"TSL",
   :name=>"Tamuín National Airport",
   :icao=>"MMTN",
   :city=>"Tamuín",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tamuín, San Luis Potosí, Mexico"},
 "TCN"=>
  {:iata=>"TCN",
   :name=>"Tehuacán Airport",
   :icao=>"MMHC",
   :city=>"Tehuacán",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tehuacán, Puebla, Mexico"},
 "TZM"=>
  {:iata=>"TZM",
   :name=>"Cupul National Airport",
   :icao=>"",
   :city=>"Tizimín",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tizimín, Yucatan, Mexico"},
 "TUY"=>
  {:iata=>"TUY",
   :name=>"Tulum Airport",
   :icao=>"",
   :city=>"Tulum",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Tulum, Quintana Roo, Mexico"},
 "THP"=>
  {:iata=>"THP",
   :name=>"Hot Springs County-Thermopolis Municipal Airport",
   :icao=>"KTHP",
   :city=>"Thermopolis",
   :country=>'United States', :country_code=>'US',

   :location=>"Thermopolis, Wyoming, United States"},
 "TOR"=>
  {:iata=>"TOR",
   :name=>"Torrington Municipal Airport",
   :icao=>"KTOR",
   :city=>"Torrington",
   :country=>'United States', :country_code=>'US',

   :location=>"Torrington, Wyoming, United States"},
 "TUC"=>
  {:iata=>"TUC",
   :name=>"Teniente General Benjamín Matienzo International Airport",
   :icao=>"SANT",
   :city=>"San Miguel de Tucumán",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Miguel de Tucumán, Argentina"},
 "TDL"=>
  {:iata=>"TDL",
   :name=>"Tandil Airport",
   :icao=>"SAZT",
   :city=>"Tandil",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Tandil, Argentina"},
 "TTG"=>
  {:iata=>"TTG",
   :name=>"Tartagal Airport",
   :icao=>"SAST",
   :city=>"Tartagal",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Tartagal, Salta, Argentina"},
 "TJA"=>
  {:iata=>"TJA",
   :name=>"Capitán Oriel Lea Plaza Airport",
   :icao=>"SLTJ",
   :city=>"Tarija",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Tarija, Bolivia"},
 "TDD"=>
  {:iata=>"TDD",
   :name=>"Teniente Jorge Henrich Arauz Airport",
   :icao=>"SLTR",
   :city=>"Trinidad",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Trinidad, Bolivia"},
 "TBT"=>
  {:iata=>"TBT",
   :name=>"Tabatinga International Airport",
   :icao=>"SBTT",
   :city=>"Tabatinga",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tabatinga, Amazonas, Brazil"},
 "TFF"=>
  {:iata=>"TFF",
   :name=>"Tefé Airport",
   :icao=>"SBTF",
   :city=>"Tefé",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tefé, Amazonas, Brazil"},
 "THE"=>
  {:iata=>"THE",
   :name=>"Teresina Airport",
   :icao=>"SBTE",
   :city=>"Teresina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Teresina, Piauí, Brazil"},
 "TJL"=>
  {:iata=>"TJL",
   :name=>"Tres Lagoas Regional Airport",
   :icao=>"SSTL",
   :city=>"Tres Lagoas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tres Lagoas, Brazil"},
 "TMT"=>
  {:iata=>"TMT",
   :name=>"Porto Trombetas Airport",
   :icao=>"SBTB",
   :city=>"Porto Trombetas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto Trombetas, Oriximiná, Pará, Brazil"},
 "TUR"=>
  {:iata=>"TUR",
   :name=>"Tucurui Airport",
   :city=>"Tucurui",
   :icao=>"SBTU",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tucurui, Brazil"},
 "TLZ"=>
  {:iata=>"TLZ",
   :name=>"Catalao Airport",
   :city=>"Catalao",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Catalao, Brazil"},
 "TGQ"=>
  {:iata=>"TGQ",
   :name=>"Tangara Da Serra Airport",
   :city=>"Tangara da Serra",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tangara da Serra, Brazil"},
 "TRQ"=>
  {:iata=>"TRQ",
   :name=>"Tarauaca Airport",
   :city=>"Tarauaca",
   :icao=>"SBTK",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tarauaca, Brazil"},
 "TXF"=>
  {:iata=>"TXF",
   :name=>"Teixeira de Freitas Airport",
   :city=>"Teixeira de Freitas",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Teixeira de Freitas, Brazil"},
 "TEC"=>
  {:iata=>"TEC",
   :name=>"Telemaco Borba Airport",
   :city=>"Telemaco Borba",
   :icao=>"SBTL",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Telemaco Borba, Brazil"},
 "TFL"=>
  {:iata=>"TFL",
   :name=>"Teofilo Otoni Airport",
   :city=>"Teofilo Otoni",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Teofilo Otoni, Brazil"},
 "TOW"=>
  {:iata=>"TOW",
   :name=>"Toledo Airport",
   :city=>"Toledo",
   :icao=>"SBTD",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Toledo, Brazil"},
 "TSQ"=>
  {:iata=>"TSQ",
   :name=>"Torres Airport",
   :city=>"Torres",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Torres, Brazil"},
 "TUZ"=>
  {:iata=>"TUZ",
   :name=>"Tucuma Airport",
   :city=>"Tucuma",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Tucuma, Brazil"},
 "TLX"=>
  {:iata=>"TLX",
   :name=>"Talca Airport",
   :city=>"Talca",
   :icao=>"SCTL",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Talca, Chile"},
 "TTC"=>
  {:iata=>"TTC",
   :name=>"Taltal Airport",
   :city=>"Taltal",
   :icao=>"SCTT",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Taltal, Chile"},
 "TOQ"=>
  {:iata=>"TOQ",
   :name=>"Barriles Airport",
   :city=>"Tocopilla",
   :icao=>"SCBE",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Tocopilla, Chile"},
 "TME"=>
  {:iata=>"TME",
   :name=>"Gabriel Vargas Santos Airport",
   :icao=>"SKTM",
   :city=>"Tame",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tame, Arauca, Colombia"},
 "TCD"=>
  {:iata=>"TCD",
   :name=>"Tarapaca Airport",
   :city=>"Tarapaca",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tarapaca, Colombia"},
 "TCO"=>
  {:iata=>"TCO",
   :name=>"La Florida Airport",
   :city=>"Tumaco",
   :icao=>"SKCO",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tumaco, Colombia"},
 "TTM"=>
  {:iata=>"TTM",
   :name=>"Tablón de Tamara Airport",
   :icao=>"",
   :city=>"Tablón de Tamara",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tablón de Tamara, Colombia"},
 "TAU"=>
  {:iata=>"TAU",
   :name=>"Tauramena Airport",
   :city=>"Tauramena",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tauramena, Colombia"},
 "TIB"=>
  {:iata=>"TIB",
   :name=>"Tibu Airport",
   :city=>"Tibu",
   :icao=>"SKTB",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tibu, Colombia"},
 "TBD"=>
  {:iata=>"TBD",
   :name=>"Timbiqui Airport",
   :city=>"Timbiqui",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Timbiqui, Colombia"},
 "TLU"=>
  {:iata=>"TLU",
   :name=>"Tolu Airport",
   :city=>"Tolu",
   :icao=>"SKTL",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tolu, Colombia"},
 "TQS"=>
  {:iata=>"TQS",
   :name=>"Tres Esquinas Airport",
   :city=>"Tres Esquinas",
   :icao=>"SKTQ",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tres Esquinas, Colombia"},
 "TDA"=>
  {:iata=>"TDA",
   :name=>"Trinidad Airport",
   :city=>"Trinidad",
   :icao=>"SKTD",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Trinidad, Colombia"},
 "TRB"=>
  {:iata=>"TRB",
   :name=>"Gonzalo Airport",
   :city=>"Turbo",
   :icao=>"SKTU",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Turbo, Colombia"},
 "TNW"=>
  {:iata=>"TNW",
   :name=>"Jumandy Airport",
   :city=>"Tena",
   :icao=>"SEJD",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Tena, Ecuador"},
 "TUA"=>
  {:iata=>"TUA",
   :name=>"Teniente Coronel Luis a Mantilla International Airport",
   :icao=>"SETU",
   :city=>"Tulcán",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Tulcán, Ecuador"},
 "TSC"=>
  {:iata=>"TSC",
   :name=>"Taisha Airport",
   :city=>"Taisha",
   :icao=>"SETH",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Taisha, Ecuador"},
 "TPC"=>
  {:iata=>"TPC",
   :name=>"Tarapoa Airport",
   :city=>"Tarapoa",
   :icao=>"SETR",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Tarapoa, Ecuador"},
 "TPN"=>
  {:iata=>"TPN",
   :name=>"Tiputini Airport",
   :city=>"Tiputini",
   :icao=>"SETI",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Tiputini, Ecuador"},
 "TCQ"=>
  {:iata=>"TCQ",
   :name=>"Tacna Airport",
   :city=>"Tacna",
   :icao=>"SPTN",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Tacna, Peru"},
 "TYL"=>
  {:iata=>"TYL",
   :name=>"Cap. FAP Víctor Montes Arias Airport",
   :icao=>"SPYL",
   :city=>"Talara",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Talara, Peru"},
 "TPP"=>
  {:iata=>"TPP",
   :name=>"Tarapoto Airport",
   :city=>"Tarapoto",
   :icao=>"SPST",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Tarapoto, Peru"},
 "TGI"=>
  {:iata=>"TGI",
   :name=>"Tingo María Airport",
   :icao=>"SPGM",
   :city=>"Tingo María",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Tingo María, Peru"},
 "TRU"=>
  {:iata=>"TRU",
   :name=>"Cap. FAP Carlos Martínez de Pinillos International Airport",
   :icao=>"SPRU",
   :city=>"Trujillo",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Trujillo, Peru"},
 "TBP"=>
  {:iata=>"TBP",
   :name=>"Cap. FAP Pedro Canga Rodríguez Airport",
   :icao=>"SPME",
   :city=>"Tumbes",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Tumbes, Peru"},
 "TOT"=>
  {:iata=>"TOT",
   :name=>"Coronie Airport",
   :icao=>"SMCO",
   :city=>"Totness",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Totness, Coronie, Suriname"},
 "TAW"=>
  {:iata=>"TAW",
   :name=>"Tacuarembó Airport",
   :icao=>"SUTB",
   :city=>"Tacuarembó",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Tacuarembó, Tacuarembó, Uruguay"},
 "TYT"=>
  {:iata=>"TYT",
   :name=>"Treinta y Tres Airport",
   :icao=>"SUTR",
   :city=>"Treinta y Tres",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Treinta y Tres, Treinta y Tres, Uruguay"},
 "TUV"=>
  {:iata=>"TUV",
   :name=>"Tucupita Airport",
   :city=>"Tucupita",
   :icao=>"SVTC",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Tucupita, Venezuela"},
 "TMO"=>
  {:iata=>"TMO",
   :name=>"Tumeremo Airport",
   :city=>"Tumeremo",
   :icao=>"SVTM",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Tumeremo, Venezuela"},
 "TNM"=>
  {:iata=>"TNM",
   :name=>"Teniente R. Marsh Airport",
   :icao=>"SCRM",
   :city=>"Villa Las Estrellas",
   :country=>'Antarctica', :country_code=>'AQ',
   :location=>"Villa Las Estrellas, Antarctica"},
 "TAV"=>
  {:iata=>"TAV",
   :name=>"Tau Airport",
   :icao=>"",
   :city=>"Tau",
   :country=>'American Samoa', :country_code=>'AS',
   :location=>"Tau, American Samoa"},
 "TMW"=>
  {:iata=>"TMW",
   :name=>"Tamworth Airport",
   :icao=>"YSTW",
   :city=>"Tamworth",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tamworth, New South Wales, Australia"},
 "TRO"=>
  {:iata=>"TRO",
   :name=>"Taree Airport",
   :city=>"Taree",
   :icao=>"YTRE",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Taree, Australia"},
 "THG"=>
  {:iata=>"THG",
   :name=>"Thangool Airport",
   :city=>"Thangool",
   :icao=>"YTNG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Thangool, Australia"},
 "TWB"=>
  {:iata=>"TWB",
   :name=>"Toowoomba Airport",
   :city=>"Toowoomba",
   :icao=>"YTWB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Toowoomba, Australia"},
 "TSV"=>
  {:iata=>"TSV",
   :name=>"Townsville Airport",
   :icao=>"YBTL",
   :city=>"Townsville",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Townsville, Queensland, Australia"},
 "TBL"=>
  {:iata=>"TBL",
   :name=>"Tableland Airport",
   :city=>"Tableland",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tableland, Australia"},
 "TXR"=>
  {:iata=>"TXR",
   :name=>"Tanbar Airport",
   :city=>"Tanbar",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tanbar, Australia"},
 "TAN"=>
  {:iata=>"TAN",
   :name=>"Tangalooma Airport",
   :icao=>"YTGA",
   :city=>"Tangalooma",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tangalooma, Queensland, Australia"},
 "TAQ"=>
  {:iata=>"TAQ",
   :name=>"Tarcoola Airport",
   :city=>"Tarcoola",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tarcoola, Australia"},
 "TEF"=>
  {:iata=>"TEF",
   :name=>"Telfer Airport",
   :city=>"Telfer",
   :icao=>"YTEF",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Telfer, Australia"},
 "TEM"=>
  {:iata=>"TEM",
   :name=>"Temora Airport",
   :city=>"Temora",
   :icao=>"YTEM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Temora, Australia"},
 "TCA"=>
  {:iata=>"TCA",
   :name=>"Tennant Creek Airport",
   :city=>"Tennant Creek",
   :icao=>"YTNK",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tennant Creek, Australia"},
 "TWN"=>
  {:iata=>"TWN",
   :name=>"Tewantin Airport",
   :city=>"Tewantin",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tewantin, Australia"},
 "TDN"=>
  {:iata=>"TDN",
   :name=>"Theda Station Airport",
   :city=>"Theda",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Theda, Australia"},
 "TDR"=>
  {:iata=>"TDR",
   :name=>"Theodore Airport",
   :city=>"Theodore",
   :icao=>"YTDR",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Theodore, Australia"},
 "TIS"=>
  {:iata=>"TIS",
   :name=>"Thursday Island Airport",
   :city=>"Thursday Island",
   :icao=>"YTUD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Thursday Island, Australia"},
 "TYG"=>
  {:iata=>"TYG",
   :name=>"Thylungra Airport",
   :city=>"Thylungra",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Thylungra, Australia"},
 "TYB"=>
  {:iata=>"TYB",
   :name=>"Tibooburra Airport",
   :city=>"Tibooburra",
   :icao=>"YTIB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tibooburra, Australia"},
 "TBK"=>
  {:iata=>"TBK",
   :name=>"Timber Creek Airport",
   :city=>"Timber Creek",
   :icao=>"YTBR",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Timber Creek, Australia"},
 "TYP"=>
  {:iata=>"TYP",
   :name=>"Tobermorey Airport",
   :city=>"Tobermorey",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tobermorey, Australia"},
 "TCW"=>
  {:iata=>"TCW",
   :name=>"Tocumwal Airport",
   :city=>"Tocumwal",
   :icao=>"YTOC",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tocumwal, Australia"},
 "TPR"=>
  {:iata=>"TPR",
   :name=>"Tom Price Airport",
   :icao=>"",
   :city=>"Tom Price",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tom Price, Western Australia, Australia"},
 "TWP"=>
  {:iata=>"TWP",
   :name=>"Torwood Airport",
   :city=>"Torwood",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Torwood, Australia"},
 "TGN"=>
  {:iata=>"TGN",
   :name=>"La Trobe Regional Airport",
   :city=>"Traralgon",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Traralgon, Australia"},
 "TQP"=>
  {:iata=>"TQP",
   :name=>"Trepell Airport",
   :icao=>"YTEE",
   :city=>"Trapell",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Trapell, Queensland, Australia"},
 "TUM"=>
  {:iata=>"TUM",
   :name=>"Tumut Airport",
   :city=>"Tumut",
   :icao=>"YTMU",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tumut, Australia"},
 "TKY"=>
  {:iata=>"TKY",
   :name=>"Turkey Creek Airport",
   :city=>"Turkey Creek",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Turkey Creek, Australia"},
 "TVU"=>
  {:iata=>"TVU",
   :name=>"Matei Airport",
   :city=>"Taveuni",
   :icao=>"NFNM",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Taveuni, Fiji"},
 "TTL"=>
  {:iata=>"TTL",
   :name=>"Turtle Island Airport",
   :city=>"Turtle Island",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Turtle Island, Fiji"},
 "TKP"=>
  {:iata=>"TKP",
   :name=>"Takapoto Airport",
   :city=>"Takapoto",
   :icao=>"NTGT",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Takapoto, Polynesia"},
 "TKX"=>
  {:iata=>"TKX",
   :name=>"Takaroa Airport",
   :city=>"Takaroa",
   :icao=>"NTKR",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Takaroa, Polynesia"},
 "TJN"=>
  {:iata=>"TJN",
   :name=>"Takume Airport",
   :city=>"Takume",
   :icao=>"NTKM",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Takume, Polynesia"},
 "TKV"=>
  {:iata=>"TKV",
   :name=>"Tuamoto  Airport",
   :city=>"Tatakoto",
   :icao=>"",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Tatakoto, Polynesia"},
 "TIH"=>
  {:iata=>"TIH",
   :name=>"Tikehau Atoll Airport",
   :city=>"Tikehau Atoll",
   :icao=>"NTGC",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Tikehau Atoll, Polynesia"},
 "TUB"=>
  {:iata=>"TUB",
   :name=>"Tubuai Island Airport",
   :city=>"Tubuai Island",
   :icao=>"NTAT",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Tubuai Island, Polynesia"},
 "TTI"=>
  {:iata=>"TTI",
   :name=>"Tetiaroa Island Airport",
   :city=>"Tetiaroa Island",
   :icao=>"",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Tetiaroa Island, Polynesia"},
 "TPX"=>
  {:iata=>"TPX",
   :name=>"Tupai Airport",
   :city=>"Tupai",
   :icao=>"",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Tupai, Polynesia"},
 "TRW"=>
  {:iata=>"TRW",
   :name=>"Bonriki International Airport",
   :icao=>"NGTA",
   :city=>"Tarawa",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Tarawa, Kiribati"},
 "TBF"=>
  {:iata=>"TBF",
   :name=>"Tabiteuea Airport",
   :city=>"Tabiteuea",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Tabiteuea, Kiribati"},
 "TSU"=>
  {:iata=>"TSU",
   :name=>"Tabiteuea South Airport",
   :city=>"Tabiteuea South",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Tabiteuea South, Kiribati"},
 "TNV"=>
  {:iata=>"TNV",
   :name=>"Fanning Island Airport",
   :city=>"Tabuaeran",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Tabuaeran, Kiribati"},
 "TMN"=>
  {:iata=>"TMN",
   :name=>"Tamana Island Airport",
   :city=>"Tamana Island",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Tamana Island, Kiribati"},
 "TNQ"=>
  {:iata=>"TNQ",
   :name=>"Teraina Airport",
   :icao=>"",
   :city=>"Teraina",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Teraina, Kiribati"},
 "TBV"=>
  {:iata=>"TBV",
   :name=>"Tabal Airport",
   :city=>"Tabal",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Tabal, Islands"},
 "TIC"=>
  {:iata=>"TIC",
   :name=>"Tinak Airport (FAA: N18)",
   :icao=>"",
   :city=>"Tinak",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Tinak, Arno Atoll, Marshall Islands"},
 "TKK"=>
  {:iata=>"TKK",
   :name=>"Chuuk International Airport",
   :icao=>"PTKK",
   :city=>"Weno",
   :country=>'Federated States of Micronesia', :country_code=>'FM',
   :location=>"Weno, Federated States of Micronesia"},
 "TGJ"=>
  {:iata=>"TGJ",
   :name=>"Tiga Airport",
   :city=>"Tiga",
   :icao=>"NWWA",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Tiga, Caledonia"},
 "TOU"=>
  {:iata=>"TOU",
   :name=>"Touho Airport",
   :city=>"Touho",
   :icao=>"NWWU",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Touho, Caledonia"},
 "TUO"=>
  {:iata=>"TUO",
   :name=>"Taupo Airport",
   :icao=>"NZAP",
   :city=>"Taupo",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Taupo, New Zealand"},
 "TRG"=>
  {:iata=>"TRG",
   :name=>"Tauranga Airport",
   :icao=>"NZTG",
   :city=>"Tauranga",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Tauranga, New Zealand"},
 "TIU"=>
  {:iata=>"TIU",
   :name=>"Richard Pearse Airport",
   :icao=>"NZTU",
   :city=>"Timaru",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Timaru, New Zealand"},
 "TWZ"=>
  {:iata=>"TWZ",
   :name=>"Pukaki/Twizel Airport",
   :city=>"Mount Cook",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Mount Cook, Zealand"},
 "THH"=>
  {:iata=>"THH",
   :name=>"Taharoa Aerodrome",
   :city=>"Taharoa",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Taharoa, Zealand"},
 "TEU"=>
  {:iata=>"TEU",
   :name=>"Manapouri Airport",
   :city=>"Te Anau",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Te Anau, Zealand"},
 "TMZ"=>
  {:iata=>"TMZ",
   :name=>"Thames Aerodrome",
   :icao=>"NZTH",
   :city=>"Thames",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Thames, New Zealand"},
 "TKZ"=>
  {:iata=>"TKZ",
   :name=>"Tokoroa Airfield",
   :city=>"Tokoroa",
   :icao=>"NZTO",
   :country=>'Zealand', :country_code=>'',
   :location=>"Tokoroa, Zealand"},
 "TIQ"=>
  {:iata=>"TIQ",
   :name=>"Tinian International Airport (West Tinian) (FAA: TNI)",
   :icao=>"PGWT",
   :city=>"Tinian Island",
   :country=>'Northern Mariana Islands', :country_code=>'MP',
   :location=>"Tinian Island, Northern Mariana Islands"},
 "TAA"=>
  {:iata=>"TAA",
   :name=>"Tarapaina Airport",
   :city=>"Tarapaina",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Tarapaina, Islands"},
 "TLG"=>
  {:iata=>"TLG",
   :name=>"Tulaghi Airport",
   :city=>"Tulaghi",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Tulaghi, Islands"},
 "TBU"=>
  {:iata=>"TBU",
   :name=>"Fuaʻamotu International Airport",
   :icao=>"NFTF",
   :city=>"Nukuʻalofa",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Nukuʻalofa, Tongatapu, Tonga"},
 "TAH"=>
  {:iata=>"TAH",
   :name=>"Tanna Airport",
   :city=>"Tanna",
   :icao=>"",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Tanna, Vanuatu"},
 "TGH"=>
  {:iata=>"TGH",
   :name=>"Tongoa Airport",
   :icao=>"NVST",
   :city=>"Tongoa",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Tongoa, Shefa Province, Vanuatu"},
 "TOH"=>
  {:iata=>"TOH",
   :name=>"Torres Airstrip",
   :city=>"Torres",
   :icao=>"",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Torres, Vanuatu"},
 "TBI"=>
  {:iata=>"TBI",
   :name=>"New Bight Airport",
   :icao=>"MYCB",
   :city=>"New Bight",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"New Bight, Cat Island, Bahamas"},
 "TCB"=>
  {:iata=>"TCB",
   :name=>"Treasure Cay Airport",
   :icao=>"MYAT",
   :city=>"Treasure Cay",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Treasure Cay, Abaco Islands, Bahamas"},
 "TZN"=>
  {:iata=>"TZN",
   :name=>"South Andros Airport",
   :icao=>"MYAK",
   :city=>"Congo Town",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Congo Town, Andros Island, Bahamas"},
 "TYM"=>
  {:iata=>"TYM",
   :name=>"Staniel Cay Airport",
   :city=>"Staniel Cay",
   :icao=>"MYES",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Staniel Cay, Bahamas"},
 "TOV"=>
  {:iata=>"TOV",
   :name=>"West End Sea Plane Base",
   :city=>"Tortola",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Tortola, Islands"},
 "TND"=>
  {:iata=>"TND",
   :name=>"Trinidad Airport",
   :city=>"Trinidad",
   :icao=>"",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Trinidad, Cuba"},
 "TAB"=>
  {:iata=>"TAB",
   :name=>
    "A.N.R. Robinson International Airport (formerly, Crown Point International Airport)",
   :icao=>"TTCP",
   :city=>"Scarborough",
   :country=>'Trinidad and Tobago', :country_code=>'TT',
   :location=>"Scarborough, Tobago, Trinidad and Tobago"},
 "TMR"=>
  {:iata=>"TMR",
   :name=>"Tamanrasset Airport",
   :icao=>"DAAT",
   :city=>"Tamanrasset",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Tamanrasset, Algeria"},
 "TEE"=>
  {:iata=>"TEE",
   :name=>"Cheikh Larbi Tebessi Airport",
   :city=>"Tebessa",
   :icao=>"DABS",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Tebessa, Algeria"},
 "TID"=>
  {:iata=>"TID",
   :name=>"Bouchekif Airport",
   :city=>"Tiaret",
   :icao=>"DAOB",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Tiaret, Algeria"},
 "TMX"=>
  {:iata=>"TMX",
   :name=>"Timimoun Airport",
   :city=>"Timimoun",
   :icao=>"DAUT",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Timimoun, Algeria"},
 "TIN"=>
  {:iata=>"TIN",
   :name=>"Tindouf Airport",
   :city=>"Tindouf",
   :icao=>"DAOF",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Tindouf, Algeria"},
 "TLM"=>
  {:iata=>"TLM",
   :name=>"Zenata Airport",
   :city=>"Tlemcen",
   :icao=>"DAON",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Tlemcen, Algeria"},
 "TGR"=>
  {:iata=>"TGR",
   :name=>"Touggourt Airport",
   :city=>"Touggourt",
   :icao=>"DAUK",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Touggourt, Algeria"},
 "TAF"=>
  {:iata=>"TAF",
   :name=>"Oran Tafaraoui Airport",
   :icao=>"DAOL",
   :city=>"Oran",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Oran, Algeria"},
 "TBY"=>
  {:iata=>"TBY",
   :name=>"Tsabong Airport",
   :city=>"Tsabong",
   :icao=>"FBTS",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Tsabong, Botswana"},
 "TLD"=>
  {:iata=>"TLD",
   :name=>"Limpopo Valley Airfield",
   :city=>"Tuli Block",
   :icao=>"FBTL",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Tuli Block, Botswana"},
 "TMQ"=>
  {:iata=>"TMQ",
   :name=>"Tambao Airport",
   :icao=>"DFEM",
   :city=>"Tambao",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Tambao, Burkina Faso"},
 "TEG"=>
  {:iata=>"TEG",
   :name=>"Tenkodogo Airport",
   :icao=>"DFET",
   :city=>"Tenkodogo",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Tenkodogo, Burkina Faso"},
 "TUQ"=>
  {:iata=>"TUQ",
   :name=>"Tougan Airport",
   :icao=>"DFOT",
   :city=>"Tougan",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Tougan, Burkina Faso"},
 "TKC"=>
  {:iata=>"TKC",
   :name=>"Tiko Airport",
   :city=>"Tiko",
   :icao=>"FKKC",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Tiko, Cameroon"},
 "TXU"=>
  {:iata=>"TXU",
   :name=>"Tabou Airport",
   :city=>"Tabou",
   :icao=>"DITB",
   :country=>"d'Ivoire", :country_code=>'CI',
   :location=>"Tabou, d'Ivoire"},
 "TGX"=>
  {:iata=>"TGX",
   :name=>"Tingrela Airport",
   :city=>"Tingrela",
   :icao=>"",
   :country=>"d'Ivoire", :country_code=>'CI',
   :location=>"Tingrela, d'Ivoire"},
 "TOZ"=>
  {:iata=>"TOZ",
   :name=>"Touba Airport",
   :city=>"Touba",
   :icao=>"DITM",
   :country=>"d'Ivoire", :country_code=>'CI',
   :location=>"Touba, d'Ivoire"},
 "TDJ"=>
  {:iata=>"TDJ",
   :name=>"Tadjoura Airport",
   :city=>"Tadjoura",
   :icao=>"HDTJ",
   :country=>'Djibouti', :country_code=>'DJ',
   :location=>"Tadjoura, Djibouti"},
 "TES"=>
  {:iata=>"TES",
   :name=>"Tessenei Airport",
   :city=>"Tessenei",
   :icao=>"HHTS",
   :country=>'Eritrea', :country_code=>'ER',
   :location=>"Tessenei, Eritrea"},
 "TIE"=>
  {:iata=>"TIE",
   :name=>"Tippi Airport",
   :city=>"Tippi",
   :icao=>"HATP",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Tippi, Ethiopia"},
 "TUJ"=>
  {:iata=>"TUJ",
   :name=>"Tum Airport",
   :city=>"Tum",
   :icao=>"",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Tum, Ethiopia"},
 "TCH"=>
  {:iata=>"TCH",
   :name=>"Tchibanga Airport",
   :city=>"Tchibanga",
   :icao=>"FOOT",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Tchibanga, Gabon"},
 "TKD"=>
  {:iata=>"TKD",
   :name=>"Takoradi Airport",
   :icao=>"DGTK",
   :city=>"Sekondi-Takoradi",
   :country=>'Ghana', :country_code=>'GH',
   :location=>"Sekondi-Takoradi, Ghana"},
 "TML"=>
  {:iata=>"TML",
   :name=>"Tamale Airport",
   :icao=>"DGLE",
   :city=>"Tamale",
   :country=>'Ghana', :country_code=>'GH',
   :location=>"Tamale, Northern Region, Ghana"},
 "THB"=>
  {:iata=>"THB",
   :name=>"Thaba-Tseka Airport",
   :city=>"Thaba-Tseka",
   :icao=>"",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Thaba-Tseka, Lesotho"},
 "TKO"=>
  {:iata=>"TKO",
   :name=>"Tlokoeng Airport",
   :city=>"Tlokoeng",
   :icao=>"",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Tlokoeng, Lesotho"},
 "TPT"=>
  {:iata=>"TPT",
   :name=>"Tapeta Airport",
   :city=>"Tapeta",
   :icao=>"",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Tapeta, Liberia"},
 "THC"=>
  {:iata=>"THC",
   :name=>"Tchien Airport",
   :icao=>"GLTN",
   :city=>"Tchien",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Tchien, Liberia"},
 "TOB"=>
  {:iata=>"TOB",
   :name=>"Gamal Abdel Nasser Airport",
   :icao=>"HLGN",
   :city=>"Tobruk",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Tobruk, Libya"},
 "TIP"=>
  {:iata=>"TIP",
   :name=>"Tripoli International Airport",
   :icao=>"HLLT",
   :city=>"Tripoli",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Tripoli, Libya"},
 "TNR"=>
  {:iata=>"TNR",
   :name=>"Ivato Airport",
   :icao=>"FMMI",
   :city=>"Antananarivo",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Antananarivo, Madagascar"},
 "TVA"=>
  {:iata=>"TVA",
   :name=>"Morafenobe Airport",
   :city=>"Morafenobe",
   :icao=>"FMMR",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Morafenobe, Madagascar"},
 "TMM"=>
  {:iata=>"TMM",
   :name=>"Toamasina Airport",
   :icao=>"FMMT",
   :city=>"Toamasina",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Toamasina, Madagascar"},
 "TLE"=>
  {:iata=>"TLE",
   :name=>"Tulear Airport",
   :city=>"Tulear",
   :icao=>"FMST",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Tulear, Madagascar"},
 "TDV"=>
  {:iata=>"TDV",
   :name=>"Tanandava Airport",
   :city=>"Tanandava",
   :icao=>"FMSN",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Tanandava, Madagascar"},
 "TTS"=>
  {:iata=>"TTS",
   :name=>"Tsaratanana Airport",
   :icao=>"",
   :city=>"Tsaratanana",
   :country=>"Madagascar",
   :country_code=>"MG",
   :location=>"Tsaratanana, Madagascar."},
 "TOM"=>
  {:iata=>"TOM",
   :name=>"Timbuktu Airport",
   :icao=>"GATB",
   :city=>"Timbuktu",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Timbuktu, Mali"},
 "THT"=>
  {:iata=>"THT",
   :name=>"Tamchakett Airport",
   :icao=>"GQNT",
   :city=>"Tamchakett",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Tamchakett, Mauritania"},
 "THI"=>
  {:iata=>"THI",
   :name=>"Tichitt Airport",
   :icao=>"GQNC",
   :city=>"Tichitt",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Tichitt, Mauritania"},
 "TIY"=>
  {:iata=>"TIY",
   :name=>"Tidjikja Airport",
   :icao=>"GQND",
   :city=>"Tidjikja",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Tidjikja, Mauritania"},
 "TMD"=>
  {:iata=>"TMD",
   :name=>"Timbedra Airport",
   :icao=>"GQNH",
   :city=>"Timbedra",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Timbedra, Mauritania"},
 "TTA"=>
  {:iata=>"TTA",
   :name=>"Tan Tan Airport (Plage Blanche Airport)",
   :icao=>"GMAT",
   :city=>"Tan-Tan",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Tan-Tan, Morocco"},
 "TNG"=>
  {:iata=>"TNG",
   :name=>"Ibn Batouta International Airport",
   :icao=>"GMTT",
   :city=>"Tangier",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Tangier, Morocco"},
 "TTU"=>
  {:iata=>"TTU",
   :name=>"Sania Ramel Airport",
   :icao=>"",
   :city=>"Tétouan",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Tétouan, Morocco"},
 "TFY"=>
  {:iata=>"TFY",
   :name=>"Tarfaya Airport",
   :city=>"Tarfaya",
   :icao=>"",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Tarfaya, Morocco"},
 "TET"=>
  {:iata=>"TET",
   :name=>"Chingozi Airport",
   :icao=>"FQTT",
   :city=>"Tete",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Tete, Mozambique"},
 "TGS"=>
  {:iata=>"TGS",
   :name=>"Chokwe Airport",
   :city=>"Chokwe",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Chokwe, Mozambique"},
 "TCV"=>
  {:iata=>"TCV",
   :name=>"Chingozi Airport",
   :icao=>"",
   :city=>"Tete",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Tete, Mozambique"},
 "TCY"=>
  {:iata=>"TCY",
   :name=>"Terrace Bay Airport",
   :city=>"Terrace Bay",
   :icao=>"",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Terrace Bay, Namibia"},
 "TSB"=>
  {:iata=>"TSB",
   :name=>"Tsumeb Airport",
   :city=>"Tsumeb",
   :icao=>"FYTM",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Tsumeb, Namibia"},
 "THZ"=>
  {:iata=>"THZ",
   :name=>"Tahoua Airport",
   :icao=>"DRRT",
   :city=>"Tahoua",
   :country=>'Niger', :country_code=>'NE',
   :location=>"Tahoua, Niger"},
 "TMS"=>
  {:iata=>"TMS",
   :name=>"São Tomé International Airport",
   :icao=>"FPST",
   :city=>"São Tomé",
   :country=>'São Tomé and Príncipe', :country_code=>'ST',
   :location=>"São Tomé, São Tomé and Príncipe"},
 "TUD"=>
  {:iata=>"TUD",
   :name=>"Tambacounda Airport",
   :icao=>"GOTT",
   :city=>"Tambacounda",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Tambacounda, Senegal"},
 "TDT"=>
  {:iata=>"TDT",
   :name=>"Tanda Tula Airport",
   :city=>"Tanda Tula",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Tanda Tula, Africa"},
 "TCU"=>
  {:iata=>"TCU",
   :name=>"Thaba Nchu Airport",
   :city=>"Thaba Nchu",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Thaba Nchu, Africa"},
 "THY"=>
  {:iata=>"THY",
   :name=>"Thohoyandou Airport",
   :city=>"Thohoyandou",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Thohoyandou, Africa"},
 "TSD"=>
  {:iata=>"TSD",
   :name=>"Tshipise Airport",
   :city=>"Tshipise",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Tshipise, Africa"},
 "TSH"=>
  {:iata=>"TSH",
   :name=>"Tshikapa Airport",
   :city=>"Tshikapa",
   :icao=>"FZUK",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Tshikapa, Congo"},
 "TBJ"=>
  {:iata=>"TBJ",
   :name=>"Tabarka - 7 Novembre International Airport",
   :icao=>"DTKA",
   :city=>"Tabarka",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Tabarka, Tunisia"},
 "TOE"=>
  {:iata=>"TOE",
   :name=>"Tozeur, Tunisia (Aeroport International Tozeur Nefta)",
   :icao=>"DTTZ",
   :city=>"Tozeur",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Tozeur, Tunisia, Tunisia"},
 "TUN"=>
  {:iata=>"TUN",
   :name=>"Tunis–Carthage International Airport",
   :icao=>"DTTA",
   :city=>"Tunis / Carthage",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Tunis / Carthage, Tunisia"},
 "TRY"=>
  {:iata=>"TRY",
   :name=>"Tororo Airport",
   :city=>"Tororo",
   :icao=>"HUTO",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Tororo, Uganda"},
 "TKQ"=>
  {:iata=>"TKQ",
   :name=>"Kigoma Airport",
   :icao=>"HTKA",
   :city=>"Kigoma",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Kigoma, Tanzania"},
 "TBO"=>
  {:iata=>"TBO",
   :name=>"Tabora Airport",
   :city=>"Tabora",
   :icao=>"HTTB",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Tabora, Tanzania"},
 "TGT"=>
  {:iata=>"TGT",
   :name=>"Tanga Airport",
   :city=>"Tanga",
   :icao=>"HTTG",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Tanga, Tanzania"},
 "TIA"=>
  {:iata=>"TIA",
   :name=>"Tirana International Airport Nënë Tereza",
   :icao=>"LATI",
   :city=>"Tirana",
   :country=>'Albania', :country_code=>'AL',
   :location=>"Tirana, Albania"},
 "TZL"=>
  {:iata=>"TZL",
   :name=>"Tuzla International Airport",
   :icao=>"LQTZ",
   :city=>"Tuzla",
   :country=>'Bosnia and Herzegovina', :country_code=>'BO',
   :location=>"Tuzla, Bosnia and Herzegovina"},
 "TGV"=>
  {:iata=>"TGV",
   :name=>"Targovishte Airport",
   :city=>"Targovishte",
   :icao=>"",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Targovishte, Bulgaria"},
 "TED"=>
  {:iata=>"TED",
   :name=>"Thisted Airport",
   :icao=>"EKTS",
   :city=>"Thisted",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Thisted, Denmark"},
 "TLL"=>
  {:iata=>"TLL",
   :name=>"Lennart Meri Tallinn Airport",
   :icao=>"EETN",
   :city=>"Tallinn",
   :country=>'Estonia', :country_code=>'EE',
   :location=>"Tallinn, Estonia"},
 "TAY"=>
  {:iata=>"TAY",
   :name=>"Tartu-Ülenurme Airport",
   :icao=>"EETU",
   :city=>"Tartu",
   :country=>'Estonia', :country_code=>'EE',
   :location=>"Tartu, Estonia"},
 "TMP"=>
  {:iata=>"TMP",
   :name=>"Tampere-Pirkkala Airport",
   :icao=>"EFTP",
   :city=>"Tampere / Pirkkala",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Tampere / Pirkkala, Finland"},
 "TKU"=>
  {:iata=>"TKU",
   :name=>"Turku Airport",
   :icao=>"EFTU",
   :city=>"Turku",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Turku, Finland"},
 "TLS"=>
  {:iata=>"TLS",
   :name=>"Toulouse Blagnac International Airport",
   :icao=>"LFBO",
   :city=>"Toulouse",
   :country=>'France', :country_code=>'FR',
   :location=>"Toulouse, France"},
 "TLN"=>
  {:iata=>"TLN",
   :name=>"Toulon-Hyères Airport",
   :icao=>"LFTH",
   :city=>"Toulon",
   :country=>'France', :country_code=>'FR',
   :location=>"Toulon, France"},
 "TUF"=>
  {:iata=>"TUF",
   :name=>"Tours Val de Loire Airport",
   :icao=>"LFOT",
   :city=>"Tours",
   :country=>'France', :country_code=>'FR',
   :location=>"Tours, France"},
 "TGF"=>
  {:iata=>"TGF",
   :name=>"Tignes Airport",
   :city=>"Tignes",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Tignes, France"},
 "TNF"=>
  {:iata=>"TNF",
   :name=>"Toussus-le-Noble Airport",
   :icao=>"LFPN",
   :city=>"Toussus-le-Noble",
   :country=>'France', :country_code=>'FR',
   :location=>"Toussus-le-Noble, France"},
 "TBS"=>
  {:iata=>"TBS",
   :name=>"Tbilisi International Airport",
   :icao=>"UGTB",
   :city=>"Tbilisi",
   :country=>'Georgia', :country_code=>'GE',
   :location=>"Tbilisi, Georgia"},
 "TXL"=>
  {:iata=>"TXL",
   :name=>"Berlin Tegel Airport",
   :icao=>"EDDT",
   :city=>"Tegel / Berlin",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Tegel / Berlin, Germany"},
 "THF"=>
  {:iata=>"THF",
   :name=>"Tempelhof International Airport (closed 2008)",
   :icao=>"EDDI",
   :city=>"Berlin",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Berlin, Germany"},
 "THO"=>
  {:iata=>"THO",
   :name=>"Thorshofn Airport",
   :icao=>"BITN",
   :city=>"Þórshöfn",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Þórshöfn, Iceland"},
 "TEY"=>
  {:iata=>"TEY",
   :name=>"Thingeyri Airport",
   :city=>"Thingeyri",
   :icao=>"BITE",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Thingeyri, Iceland"},
 "TQR"=>
  {:iata=>"TQR",
   :name=>"San Domino Island Heliport",
   :city=>"San Domino Island",
   :icao=>"",
   :country=>'Italy', :country_code=>'IT',
   :location=>"San Domino Island, Italy"},
 "TAR"=>
  {:iata=>"TAR",
   :name=>"Taranto-Grottaglie Airport",
   :icao=>"LIBG",
   :city=>"Grottaglie",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Grottaglie, Puglia, Italy"},
 "TTB"=>
  {:iata=>"TTB",
   :name=>"Tortolì Airport",
   :icao=>"LIET",
   :city=>"Sardinia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Sardinia, Italy"},
 "TPS"=>
  {:iata=>"TPS",
   :name=>"Trapani-Birgi Airport",
   :icao=>"LICT",
   :city=>"Trapani",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Trapani, Italy"},
 "TRS"=>
  {:iata=>"TRS",
   :name=>"Friuli Venezia Giulia Airport",
   :icao=>"LIPQ",
   :city=>"Trieste",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Trieste, Italy"},
 "TRN"=>
  {:iata=>"TRN",
   :name=>"Turin International Airport",
   :icao=>"LIMF",
   :city=>"Turin",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Turin, Italy"},
 "TSF"=>
  {:iata=>"TSF",
   :name=>"Treviso Airport",
   :icao=>"LIPH",
   :city=>"Treviso",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Treviso, Italy"},
 "TGD"=>
  {:iata=>"TGD",
   :name=>"Podgorica Airport",
   :icao=>"LYPG",
   :city=>"Golubovci (near Podgorica)",
   :country=>'Montenegro', :country_code=>'ME',
   :location=>"Golubovci (near Podgorica), Montenegro"},
 "TIV"=>
  {:iata=>"TIV",
   :name=>"Tivat Airport",
   :icao=>"LYTV",
   :city=>"Tivat",
   :country=>'Montenegro', :country_code=>'ME',
   :location=>"Tivat, Montenegro"},
 "TRD"=>
  {:iata=>"TRD",
   :name=>"Trondheim Airport, Værnes",
   :icao=>"ENVA",
   :city=>"Trondheim",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Trondheim, Sør-Trøndelag, Norway"},
 "TRF"=>
  {:iata=>"TRF",
   :name=>"Sandefjord Airport, Torp",
   :icao=>"ENTO",
   :city=>"Sandefjord / Stokke",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Sandefjord / Stokke, Norway"},
 "TOS"=>
  {:iata=>"TOS",
   :name=>"Tromsø Airport",
   :icao=>"ENTC",
   :city=>"Tromsø",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Tromsø, Norway"},
 "TER"=>
  {:iata=>"TER",
   :name=>"Lajes Field",
   :icao=>"LPLA",
   :city=>"Lajes",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Lajes, Azores, Portugal"},
 "TSR"=>
  {:iata=>"TSR",
   :name=>"Traian Vuia International Airport",
   :icao=>"LRTR",
   :city=>"Timişoara",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Timişoara, Romania"},
 "TGM"=>
  {:iata=>"TGM",
   :name=>"Târgu Mureş International Airport",
   :icao=>"LRTM",
   :city=>"Târgu-Mureş",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Târgu-Mureş, Romania"},
 "TCE"=>
  {:iata=>"TCE",
   :name=>"Tulcea Airport",
   :city=>"Tulcea",
   :icao=>"LRTC",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Tulcea, Romania"},
 "TGP"=>
  {:iata=>"TGP",
   :name=>"Podkamennaya Tunguska Airport",
   :icao=>"UNIP",
   :city=>"Podkamennaya Tunguska",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Podkamennaya Tunguska, Krasnoyarsk, Russia"},
 "TLY"=>
  {:iata=>"TLY",
   :name=>"Plastun Airport",
   :city=>"Plastun",
   :icao=>"UHWP",
   :country=>'Federation', :country_code=>'',
   :location=>"Plastun, Federation"},
 "TGK"=>
  {:iata=>"TGK",
   :name=>"Taganrog Yuzhny Airport",
   :city=>"Taganrog",
   :icao=>"URRT",
   :country=>'Federation', :country_code=>'',
   :location=>"Taganrog, Federation"},
 "TLK"=>
  {:iata=>"TLK",
   :name=>"Talakan Airport",
   :icao=>"UECT",
   :city=>"Talakan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Talakan, Bureysky District, Russia"},
 "TBW"=>
  {:iata=>"TBW",
   :name=>"Tambov Donskoye Airport",
   :icao=>"UUOT",
   :city=>"Tambov",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tambov, Russia"},
 "TQL"=>
  {:iata=>"TQL",
   :name=>"Tarko-Sale Airport",
   :city=>"Tarko-Sale",
   :icao=>"USDS",
   :country=>'Federation', :country_code=>'',
   :location=>"Tarko-Sale, Federation"},
 "TOF"=>
  {:iata=>"TOF",
   :name=>"Bogashevo Airport",
   :icao=>"UNTT",
   :city=>"Tomsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tomsk, Russia"},
 "THX"=>
  {:iata=>"THX",
   :name=>"Turukhansk Airport",
   :icao=>"UOTT",
   :city=>"Turukhansk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Turukhansk, Russia"},
 "TJM"=>
  {:iata=>"TJM",
   :name=>"Roschino Airport",
   :icao=>"USTR",
   :city=>"Tyumen",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tyumen, Russia"},
 "TOX"=>
  {:iata=>"TOX",
   :name=>"Tobolsk Airport",
   :city=>"Tobolsk",
   :icao=>"",
   :country=>'Federation', :country_code=>'',
   :location=>"Tobolsk, Federation"},
 "TYA"=>
  {:iata=>"TYA",
   :name=>"Yalova Airport",
   :icao=>"LTBP",
   :city=>"Yalova",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Yalova, Turkey"},
 "TYD"=>
  {:iata=>"TYD",
   :name=>"Tynda Airport",
   :icao=>"UHBW",
   :city=>"Tynda",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tynda, Amur Oblast, Russia"},
 "TAT"=>
  {:iata=>"TAT",
   :name=>"Poprad-Tatry Airport",
   :icao=>"LZTT",
   :city=>"Poprad",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Poprad, Slovakia"},
 "TFN"=>
  {:iata=>"TFN",
   :name=>"Tenerife North Airport (Los Rodeos Airport)",
   :icao=>"GCXO",
   :city=>"Tenerife",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Tenerife, Canary Islands, Spain"},
 "TFS"=>
  {:iata=>"TFS",
   :name=>"Tenerife South Airport (Reina Sofia Airport)",
   :icao=>"GCTS",
   :city=>"Tenerife",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Tenerife, Canary Islands, Spain"},
 "TOJ"=>
  {:iata=>"TOJ",
   :name=>"Madrid-Torrejón Airport",
   :icao=>"LETO",
   :city=>"Torrejón de Ardoz",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Torrejón de Ardoz, Spain"},
 "TYF"=>
  {:iata=>"TYF",
   :name=>"Torsby Airport",
   :city=>"Torsby",
   :icao=>"ESST",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Torsby, Sweden"},
 "THN"=>
  {:iata=>"THN",
   :name=>"Trollhättan-Vänersborg Airport",
   :icao=>"ESGT",
   :city=>"Trollhättan / Vänersborg",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Trollhättan / Vänersborg, Sweden"},
 "TEQ"=>
  {:iata=>"TEQ",
   :name=>"Çorlu Airport",
   :icao=>"LTBU",
   :city=>"Tekirdag",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Tekirdag, Turkey"},
 "TJK"=>
  {:iata=>"TJK",
   :name=>"Tokat Airport",
   :icao=>"LTAW",
   :city=>"Tokat",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Tokat, Turkey"},
 "TZX"=>
  {:iata=>"TZX",
   :name=>"Trabzon Airport",
   :icao=>"LTCG",
   :city=>"Trabzon",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Trabzon, Turkey"},
 "TNL"=>
  {:iata=>"TNL",
   :name=>"Ternopil Airport",
   :icao=>"UKLT",
   :city=>"Ternopil",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Ternopil, Ukraine"},
 "TSO"=>
  {:iata=>"TSO",
   :name=>"Tresco Heliport",
   :icao=>"EGHT",
   :city=>"Tresco",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Tresco, Isles of Scilly, United Kingdom"},
 "TRE"=>
  {:iata=>"TRE",
   :name=>"Tiree Airport",
   :icao=>"EGPU",
   :city=>"Tiree",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Tiree, Scotland, United Kingdom"},
 "TTK"=>
  {:iata=>"TTK",
   :name=>"Tottenham Hale Station",
   :city=>"Tottenham Hale Station",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Tottenham Hale Station, Kingdom"},
 "TII"=>
  {:iata=>"TII",
   :name=>"Tarin Kowt Airport",
   :icao=>"OATN",
   :city=>"Tarin Kowt",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Tarin Kowt, Afghanistan"},
 "TQN"=>
  {:iata=>"TQN",
   :name=>"Taloqan Airport",
   :icao=>"OATQ",
   :city=>"Taloqan",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Taloqan, Afghanistan"},
 "TKR"=>
  {:iata=>"TKR",
   :name=>"Thakurgaon Airport",
   :city=>"Thakurgaon",
   :icao=>"",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Thakurgaon, Bangladesh"},
 "TNX"=>
  {:iata=>"TNX",
   :name=>"Stung Treng Airport",
   :city=>"Stung Treng",
   :icao=>"VDST",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Stung Treng, Cambodia"},
 "TNA"=>
  {:iata=>"TNA",
   :name=>"Jinan Yaoqiang International Airport",
   :icao=>"ZSJN",
   :city=>"Jinan",
   :country=>'China', :country_code=>'CN',
   :location=>"Jinan, Shandong, China"},
 "TAO"=>
  {:iata=>"TAO",
   :name=>"Qingdao Liuting International Airport",
   :icao=>"ZSQD",
   :city=>"Qingdao",
   :country=>'China', :country_code=>'CN',
   :location=>"Qingdao, Shandong, China"},
 "TYN"=>
  {:iata=>"TYN",
   :name=>"Taiyuan Wusu International Airport",
   :icao=>"ZBYN",
   :city=>"Taiyuan",
   :country=>'China', :country_code=>'CN',
   :location=>"Taiyuan, Shanxi, China"},
 "TSN"=>
  {:iata=>"TSN",
   :name=>"Tianjin Binhai International Airport",
   :icao=>"ZBTJ",
   :city=>"Tianjin",
   :country=>'China', :country_code=>'CN',
   :location=>"Tianjin, China"},
 "TNH"=>
  {:iata=>"TNH",
   :name=>"Tonghua Sanyuanpu Airport",
   :icao=>"ZYTN",
   :city=>"Tonghua",
   :country=>'China', :country_code=>'CN',
   :location=>"Tonghua, Jilin, China"},
 "TCG"=>
  {:iata=>"TCG",
   :name=>"Tacheng Airport",
   :city=>"Tacheng",
   :icao=>"ZWTC",
   :country=>'China', :country_code=>'CN',
   :location=>"Tacheng, China"},
 "TVS"=>
  {:iata=>"TVS",
   :name=>"Tangshan Sannühe Airport",
   :icao=>"",
   :city=>"Tangshan",
   :country=>'China', :country_code=>'CN',
   :location=>"Tangshan, Hebei, China"},
 "TCZ"=>
  {:iata=>"TCZ",
   :name=>"Tengchong Tuofeng Airport",
   :icao=>"ZUTC",
   :city=>"Tengchong",
   :country=>'China', :country_code=>'CN',
   :location=>"Tengchong, Yunnan, China"},
 "THQ"=>
  {:iata=>"THQ",
   :name=>"Tianshui Maijishan Airport",
   :city=>"Tianshui",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Tianshui, China"},
 "TGO"=>
  {:iata=>"TGO",
   :name=>"Tongliao Airport",
   :city=>"Tongliao",
   :icao=>"ZBTL",
   :country=>'China', :country_code=>'CN',
   :location=>"Tongliao, China"},
 "TEN"=>
  {:iata=>"TEN",
   :name=>"Tongren Fenghuang Airport",
   :icao=>"ZUTR",
   :city=>"Tongren",
   :country=>'China', :country_code=>'CN',
   :location=>"Tongren, Guizhou, China"},
 "TXN"=>
  {:iata=>"TXN",
   :name=>"Tunxi Airport",
   :city=>"Tunxi",
   :icao=>"ZSTX",
   :country=>'China', :country_code=>'CN',
   :location=>"Tunxi, China"},
 "TLQ"=>
  {:iata=>"TLQ",
   :name=>"Turpan Jiaohe Airport",
   :icao=>"ZWTP",
   :city=>"Turpan",
   :country=>'China', :country_code=>'CN',
   :location=>"Turpan, Xinjiang, China"},
 "TEZ"=>
  {:iata=>"TEZ",
   :name=>"Tezpur Airport",
   :icao=>"VETZ",
   :city=>"Tezpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Tezpur, Assam, India"},
 "TRV"=>
  {:iata=>"TRV",
   :name=>"Trivandrum International Airport",
   :icao=>"VOTV",
   :city=>"Trivandrum",
   :country=>"India",
:country_code=>"IN",
   :location=>"Trivandrum, Kerala, India"},
 "TRZ"=>
  {:iata=>"TRZ",
   :name=>"Tiruchirapalli international Airport",
   :icao=>"VOTR",
   :city=>"Tiruchirapalli (Trichy)",
   :country=>"India",
:country_code=>"IN",
   :location=>"Tiruchirapalli (Trichy), Tamil Nadu, India"},
 "TIR"=>
  {:iata=>"TIR",
   :name=>"Tirupati Airport",
   :icao=>"VOTP",
   :city=>"Tirupati",
   :country=>"India",
:country_code=>"IN",
   :location=>"Tirupati, Andhra Pradesh, India"},
 "TCR"=>
  {:iata=>"TCR",
   :name=>"Tuticorin Airport",
   :city=>"Tuticorin",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Tuticorin, India"},
 "TNI"=>
  {:iata=>"TNI",
   :name=>"Satna Airport",
   :icao=>"VIST",
   :city=>"Satna",
   :country=>"India",
:country_code=>"IN",
   :location=>"Satna, India"},
 "TEI"=>
  {:iata=>"TEI",
   :name=>"Tezu Airport",
   :icao=>"VETJ",
   :city=>"Tezu",
   :country=>"India",
:country_code=>"IN",
   :location=>"Tezu, Arunachal Pradesh, India"},
 "TJV"=>
  {:iata=>"TJV",
   :name=>"Thanjavur Airport",
   :city=>"Thanjavur",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Thanjavur, India"},
 "TKG"=>
  {:iata=>"TKG",
   :name=>"Radin Inten II Airport",
   :icao=>"WICT",
   :city=>"Bandar Lampung",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Bandar Lampung, Sumatra, Indonesia"},
 "TMC"=>
  {:iata=>"TMC",
   :name=>"Tambolaka Airport",
   :city=>"Tambolaka",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tambolaka, Indonesia"},
 "TTR"=>
  {:iata=>"TTR",
   :name=>"Pongtiku Airport",
   :city=>"Tana Toraja",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tana Toraja, Indonesia"},
 "TJQ"=>
  {:iata=>"TJQ",
   :name=>"Buluh Tumbang Airport",
   :icao=>"WIKD",
   :city=>"Tanjung Pandan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Pandan, Bangka-Belitung, Indonesia"},
 "TNJ"=>
  {:iata=>"TNJ",
   :name=>"Raja Haji Fisabilillah International Airport",
   :icao=>"WIDN",
   :city=>"Tanjung Pinang",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Pinang, Riau Islands, Indonesia"},
 "TRK"=>
  {:iata=>"TRK",
   :name=>"Juwata Airport",
   :icao=>"WALR",
   :city=>"Tarakan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tarakan, East Kalimantan, Indonesia"},
 "TIM"=>
  {:iata=>"TIM",
   :name=>"Mozes Kilangin Airport",
   :icao=>"WABP",
   :city=>"Timika",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Timika, Papua, Indonesia"},
 "TTE"=>
  {:iata=>"TTE",
   :name=>"Babullah Airport",
   :city=>"Ternate",
   :icao=>"WAMT",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ternate, Indonesia"},
 "TLI"=>
  {:iata=>"TLI",
   :name=>"Sultan Bantilan Airport",
   :city=>"Toli Toli",
   :icao=>"WAMI",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Toli Toli, Indonesia"},
 "TBM"=>
  {:iata=>"TBM",
   :name=>"Tumbang Samba Airport",
   :city=>"Tumbang Samba",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tumbang Samba, Indonesia"},
 "TAX"=>
  {:iata=>"TAX",
   :name=>"Taliabu Island Airport",
   :icao=>"WAPT",
   :city=>"Taliabu",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Taliabu, Indonesia"},
 "TNB"=>
  {:iata=>"TNB",
   :name=>"Tanahgrogot Airport",
   :city=>"Tanahgrogot",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanahgrogot, Indonesia"},
 "TMH"=>
  {:iata=>"TMH",
   :name=>"Tanahmerah Airport",
   :city=>"Tanahmerah",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanahmerah, Indonesia"},
 "TJB"=>
  {:iata=>"TJB",
   :name=>"Tanjung Balai Airport",
   :city=>"Tanjung Balai",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Balai, Indonesia"},
 "TSX"=>
  {:iata=>"TSX",
   :name=>"Tanjung Santan Airport",
   :city=>"Tanjung Santan",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Santan, Indonesia"},
 "TJS"=>
  {:iata=>"TJS",
   :name=>"Tanjung Selor Airport",
   :city=>"Tanjung Selor",
   :icao=>"WRLG",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Selor, Indonesia"},
 "TJG"=>
  {:iata=>"TJG",
   :name=>"Tanjung Warukin Airport",
   :city=>"Tanjung Warukin",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tanjung Warukin, Indonesia"},
 "TPK"=>
  {:iata=>"TPK",
   :name=>"Tapaktuan Airport",
   :city=>"Tapaktuan",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tapaktuan, Indonesia"},
 "TSY"=>
  {:iata=>"TSY",
   :name=>"Tasikmalaya Airport",
   :icao=>"WICM",
   :city=>"Tasikmalaya",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tasikmalaya, West Java, Indonesia"},
 "TXM"=>
  {:iata=>"TXM",
   :name=>"Teminabuan Airport",
   :city=>"Teminabuan",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Teminabuan, Indonesia"},
 "TMY"=>
  {:iata=>"TMY",
   :name=>"Tiom Airport",
   :city=>"Tiom",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tiom, Indonesia"},
 "THR"=>
  {:iata=>"THR",
   :name=>"Mehrabad International Airport",
   :icao=>"OIII",
   :city=>"Tehran",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Tehran, Iran"},
 "TCX"=>
  {:iata=>"TCX",
   :name=>"Tabas Airport",
   :icao=>"OIMT",
   :city=>"Tabas",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Tabas, Iran"},
 "TBZ"=>
  {:iata=>"TBZ",
   :name=>"Tabriz International Airport",
   :icao=>"OITT",
   :city=>"Tabriz",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Tabriz, Iran"},
 "TNE"=>
  {:iata=>"TNE",
   :name=>"New Tanegashima Airport",
   :city=>"Nakatane",
   :icao=>"RJFG",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Nakatane, Japan"},
 "TAK"=>
  {:iata=>"TAK",
   :name=>"Takamatsu Airport",
   :icao=>"RJOT",
   :city=>"Takamatsu",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Takamatsu, Kagawa, Japan"},
 "TKN"=>
  {:iata=>"TKN",
   :name=>"Tokunoshima Airport",
   :city=>"Tokunoshima",
   :icao=>"RJKN",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tokunoshima, Japan"},
 "TKS"=>
  {:iata=>"TKS",
   :name=>"Tokushima Airport",
   :city=>"Tokushima",
   :icao=>"RJOS",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tokushima, Japan"},
 "TTJ"=>
  {:iata=>"TTJ",
   :name=>"Tottori Airport",
   :city=>"Tottori",
   :icao=>"RJOR",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tottori, Japan"},
 "TOY"=>
  {:iata=>"TOY",
   :name=>"Toyama Airport",
   :icao=>"RJNT",
   :city=>"Toyama",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Toyama, Toyama, Japan"},
 "TJH"=>
  {:iata=>"TJH",
   :name=>"Tajima Airport",
   :city=>"Toyooka",
   :icao=>"RJBT",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Toyooka, Japan"},
 "TSJ"=>
  {:iata=>"TSJ",
   :name=>"Tsushima Airport",
   :city=>"Tsushima",
   :icao=>"RJDT",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tsushima, Japan"},
 "TRA"=>
  {:iata=>"TRA",
   :name=>"Tarama Airport",
   :city=>"Taramajima",
   :icao=>"RORT",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Taramajima, Japan"},
 "TSE"=>
  {:iata=>"TSE",
   :name=>"Astana Airport",
   :icao=>"UACC",
   :city=>"Astana",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Astana, Kazakhstan"},
 "TDK"=>
  {:iata=>"TDK",
   :name=>"Taldykorgan Airport",
   :icao=>"",
   :city=>"Taldykorgan",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Taldykorgan, Kazakhstan"},
 "THK"=>
  {:iata=>"THK",
   :name=>"Thakhek Airport",
   :city=>"Thakhek",
   :icao=>"VLTK",
   :country=>'Republic', :country_code=>'',
   :location=>"Thakhek, Republic"},
 "TGG"=>
  {:iata=>"TGG",
   :name=>"Sultan Mahmood Airport",
   :city=>"Kuala Terengganu",
   :icao=>"WMKN",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kuala Terengganu, Malaysia"},
 "TGC"=>
  {:iata=>"TGC",
   :name=>"Sarikei Airport",
   :city=>"Sarikei",
   :icao=>"WBGT",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Sarikei, Malaysia"},
 "TWU"=>
  {:iata=>"TWU",
   :name=>"Tawau Airport",
   :icao=>"WBKW",
   :city=>"Tawau",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Tawau, Sabah, Malaysia"},
 "TOD"=>
  {:iata=>"TOD",
   :name=>"Tioman Airport",
   :icao=>"WMBT",
   :city=>"Tioman Island",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Tioman Island, Malaysia"},
 "TPG"=>
  {:iata=>"TPG",
   :name=>"Taiping Airport",
   :city=>"Taiping",
   :icao=>"WMBI",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Taiping, Malaysia"},
 "TEL"=>
  {:iata=>"TEL",
   :name=>"Telupid Airport",
   :city=>"Telupid",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Telupid, Malaysia"},
 "TMG"=>
  {:iata=>"TMG",
   :name=>"Tomanggong Airport",
   :city=>"Tomanggong",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Tomanggong, Malaysia"},
 "TMF"=>
  {:iata=>"TMF",
   :name=>"Thimarafushi Airport",
   :icao=>"",
   :city=>"Thimarafushi",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Thimarafushi, Thaa Atoll, Maldives"},
 "TNZ"=>
  {:iata=>"TNZ",
   :name=>"Tosontsengel Airport",
   :city=>"Tosontsengel",
   :icao=>"",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Tosontsengel, Mongolia"},
 "TSZ"=>
  {:iata=>"TSZ",
   :name=>"Tsetserleg Airport",
   :icao=>"ZMTG",
   :city=>"Tsetserleg",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Tsetserleg, Arkhangai, Mongolia"},
 "TVY"=>
  {:iata=>"TVY",
   :name=>"Dawei Airport",
   :icao=>"VYDW",
   :city=>"Dawei",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Dawei, Myanmar (Burma)"},
 "THL"=>
  {:iata=>"THL",
   :name=>"Tachilek Airport",
   :icao=>"VYTL",
   :city=>"Tachilek",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Tachilek, Myanmar (Burma)"},
 "TIO"=>
  {:iata=>"TIO",
   :name=>"Tilin Airport",
   :city=>"Tilin",
   :icao=>"",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Tilin, Myanmar"},
 "TPU"=>
  {:iata=>"TPU",
   :name=>"Tikapur Airport",
   :city=>"Tikapur",
   :icao=>"",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Tikapur, Nepal"},
 "TMI"=>
  {:iata=>"TMI",
   :name=>"Tumling Tar Airport",
   :city=>"Tumling Tar",
   :icao=>"VNTR",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Tumling Tar, Nepal"},
 "TPJ"=>
  {:iata=>"TPJ",
   :name=>"Taplejung Airport",
   :city=>"Taplejung",
   :icao=>"",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Taplejung, Nepal"},
 "TUK"=>
  {:iata=>"TUK",
   :name=>"Turbat Airport",
   :city=>"Turbat",
   :icao=>"OPTU",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Turbat, Pakistan"},
 "TFT"=>
  {:iata=>"TFT",
   :name=>"Taftan Airport",
   :city=>"Taftan",
   :icao=>"",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Taftan, Pakistan"},
 "TLB"=>
  {:iata=>"TLB",
   :name=>"Tarbela Airport",
   :city=>"Tarbela",
   :icao=>"",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Tarbela, Pakistan"},
 "TBG"=>
  {:iata=>"TBG",
   :name=>"Tabubil Airport",
   :city=>"Tabubil",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tabubil, Guinea"},
 "TPI"=>
  {:iata=>"TPI",
   :name=>"Tapini Airport",
   :city=>"Tapini",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tapini, Guinea"},
 "TIZ"=>
  {:iata=>"TIZ",
   :name=>"Tari Airport",
   :city=>"Tari",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tari, Guinea"},
 "TFI"=>
  {:iata=>"TFI",
   :name=>"Tufi Airport",
   :city=>"Tufi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tufi, Guinea"},
 "TAJ"=>
  {:iata=>"TAJ",
   :name=>"Tadji Airport",
   :icao=>"",
   :city=>"Aitape",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Aitape, Papua New Guinea"},
 "TBA"=>
  {:iata=>"TBA",
   :name=>"Tabibuga Airport",
   :city=>"Tabibuga",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tabibuga, Guinea"},
 "TGL"=>
  {:iata=>"TGL",
   :name=>"Tagula Airport",
   :city=>"Tagula",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tagula, Guinea"},
 "TLW"=>
  {:iata=>"TLW",
   :name=>"Talasea Airport",
   :city=>"Talasea",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Talasea, Guinea"},
 "TRJ"=>
  {:iata=>"TRJ",
   :name=>"Tarakbits Airport",
   :city=>"Tarakbits",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tarakbits, Guinea"},
 "TSK"=>
  {:iata=>"TSK",
   :name=>"Taskul Airport",
   :city=>"Taskul",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Taskul, Guinea"},
 "TUT"=>
  {:iata=>"TUT",
   :name=>"Tauta Airport",
   :city=>"Tauta",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tauta, Guinea"},
 "TWY"=>
  {:iata=>"TWY",
   :name=>"Tawa Airport",
   :city=>"Tawa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tawa, Guinea"},
 "TKB"=>
  {:iata=>"TKB",
   :name=>"Tekadu Airport",
   :city=>"Tekadu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tekadu, Guinea"},
 "TKW"=>
  {:iata=>"TKW",
   :name=>"Tekin Airport",
   :city=>"Tekin",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tekin, Guinea"},
 "TFM"=>
  {:iata=>"TFM",
   :name=>"Telefomin Airport",
   :city=>"Telefomin",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Telefomin, Guinea"},
 "TEP"=>
  {:iata=>"TEP",
   :name=>"Teptep Airport",
   :city=>"Teptep",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Teptep, Guinea"},
 "TEO"=>
  {:iata=>"TEO",
   :name=>"Terapo Airport",
   :city=>"Terapo",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Terapo, Guinea"},
 "TDB"=>
  {:iata=>"TDB",
   :name=>"Tetabedi Airport",
   :city=>"Tetabedi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tetabedi, Guinea"},
 "TFB"=>
  {:iata=>"TFB",
   :name=>"Tifalmin Airport",
   :city=>"Tifalmin",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tifalmin, Guinea"},
 "TBE"=>
  {:iata=>"TBE",
   :name=>"Timbunke Airport",
   :city=>"Timbunke",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Timbunke, Guinea"},
 "TCK"=>
  {:iata=>"TCK",
   :name=>"Tinboli Airport",
   :city=>"Tinboli",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tinboli, Guinea"},
 "TIG"=>
  {:iata=>"TIG",
   :name=>"Tingwon Airport",
   :city=>"Tingwon",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tingwon, Guinea"},
 "TLO"=>
  {:iata=>"TLO",
   :name=>"Tol Airport",
   :city=>"Tol",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tol, Guinea"},
 "TON"=>
  {:iata=>"TON",
   :name=>"Tonu Airport",
   :city=>"Tonu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tonu, Guinea"},
 "TCJ"=>
  {:iata=>"TCJ",
   :name=>"Torembi Airport",
   :city=>"Torembi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Torembi, Guinea"},
 "TOK"=>
  {:iata=>"TOK",
   :name=>"Torokina Airport",
   :city=>"Torokina",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Torokina, Guinea"},
 "TSW"=>
  {:iata=>"TSW",
   :name=>"Tsewi Airport",
   :city=>"Tsewi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tsewi, Guinea"},
 "TSI"=>
  {:iata=>"TSI",
   :name=>"Tsili Tsili Airport",
   :city=>"Tsili Tsili",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tsili Tsili, Guinea"},
 "TLP"=>
  {:iata=>"TLP",
   :name=>"Tumolbil Airport",
   :city=>"Tumolbil",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Tumolbil, Guinea"},
 "TWT"=>
  {:iata=>"TWT",
   :name=>"Sanga-Sanga Airport",
   :icao=>"RPMN",
   :city=>"Bongao",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Bongao, Tawi-Tawi, Philippines"},
 "TBH"=>
  {:iata=>"TBH",
   :name=>"Romblon Airport (Tablas Airport)",
   :icao=>"RPVU",
   :city=>"Alcantara",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Alcantara, Romblon, Philippines"},
 "TAC"=>
  {:iata=>"TAC",
   :name=>"Daniel Z. Romualdez Airport (Tacloban Airport)",
   :icao=>"RPVA",
   :city=>"Tacloban City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Tacloban City, Philippines"},
 "TAG"=>
  {:iata=>"TAG",
   :name=>"Tagbilaran Airport",
   :icao=>"RPVT",
   :city=>"Tagbilaran City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Tagbilaran City, Bohol, Philippines"},
 "TDG"=>
  {:iata=>"TDG",
   :name=>"Tandag Airport",
   :icao=>"RPMW",
   :city=>"Tandag",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Tandag, Surigao del Sur, Philippines"},
 "TUG"=>
  {:iata=>"TUG",
   :name=>"Tuguegarao Airport",
   :icao=>"RPUT",
   :city=>"Tuguegarao City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Tuguegarao City, Cagayan, Philippines"},
 "TGB"=>
  {:iata=>"TGB",
   :name=>"Tagbita Airport",
   :icao=>"",
   :city=>"Rizal",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Rizal, Palawan, Philippines"},
 "TPE"=>
  {:iata=>"TPE",
   :name=>"Taiwan Taoyuan International Airport",
   :icao=>"RCTP",
   :city=>"Taoyuan County (near Taipei)",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Taoyuan County (near Taipei), Taiwan, Republic of China"},
 "TNN"=>
  {:iata=>"TNN",
   :name=>"Tainan Airport",
   :icao=>"RCNN",
   :city=>"Tainan City",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Tainan City, Taiwan, Republic of China"},
 "TSA"=>
  {:iata=>"TSA",
   :name=>"Taipei Songshan Airport",
   :icao=>"RCSS",
   :city=>"Taipei City",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Taipei City, Taiwan, Republic of China"},
 "TTT"=>
  {:iata=>"TTT",
   :name=>"Taitung Airport",
   :icao=>"",
   :city=>"Taitung",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Taitung, Taiwan, Republic of China"},
 "TXG"=>
  {:iata=>"TXG",
   :name=>"Taichung Ching Chuang Kang Airport",
   :icao=>"RCLG",
   :city=>"Taichung",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Taichung, Taiwan, Republic of China"},
 "TAE"=>
  {:iata=>"TAE",
   :name=>"Daegu International Airport",
   :icao=>"RKTN",
   :city=>"Daegu",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Daegu, South Korea"},
 "TGA"=>
  {:iata=>"TGA",
   :name=>"Tengah Air Base",
   :icao=>"WSAT",
   :city=>"Tengah",
   :country=>'Singapore', :country_code=>'SG',
   :location=>"Tengah, Singapore"},
 "THW"=>
  {:iata=>"THW",
   :name=>"Trincomalee Harbour Seaplane Base",
   :city=>"Trincomalee",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Trincomalee, Lanka"},
 "TRR"=>
  {:iata=>"TRR",
   :name=>"China Bay Airport",
   :icao=>"VCCT",
   :city=>"Trincomalee",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Trincomalee, Sri Lanka"},
 "TJU"=>
  {:iata=>"TJU",
   :name=>"Kulyab Airport",
   :city=>"Kulyab",
   :icao=>"UTDK",
   :country=>'Tajikistan', :country_code=>'TJ',
   :location=>"Kulyab, Tajikistan"},
 "THS"=>
  {:iata=>"THS",
   :name=>"Sukhothai Airport",
   :icao=>"VTPO",
   :city=>"Sukhothai",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Sukhothai, Thailand"},
 "TST"=>
  {:iata=>"TST",
   :name=>"Trang Airport",
   :icao=>"VTST",
   :city=>"Trang",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Trang, Thailand"},
 "TDX"=>
  {:iata=>"TDX",
   :name=>"Trat Airport",
   :icao=>"VTBO",
   :city=>"Trat",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Trat, Thailand"},
 "TKT"=>
  {:iata=>"TKT",
   :name=>"Tak Airport",
   :icao=>"VTPT",
   :city=>"Tak",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Tak, Thailand"},
 "TKH"=>
  {:iata=>"TKH",
   :name=>"Takhli Airport",
   :city=>"Takhli",
   :icao=>"VTPI",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Takhli, Thailand"},
 "TAZ"=>
  {:iata=>"TAZ",
   :name=>"Dashoguz Airport",
   :icao=>"UTAT",
   :city=>"Daşoguz",
   :country=>'Turkmenistan', :country_code=>'TM',
   :location=>"Daşoguz, Turkmenistan"},
 "TAS"=>
  {:iata=>"TAS",
   :name=>"Tashkent International Airport",
   :icao=>"UTTT",
   :city=>"Tashkent",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Tashkent, Uzbekistan"},
 "TMJ"=>
  {:iata=>"TMJ",
   :name=>"Termez Airport",
   :icao=>"UTST",
   :city=>"Termez",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Termez, Uzbekistan"},
 "THD"=>
  {:iata=>"THD",
   :name=>"Tho Xuan Airport",
   :icao=>"",
   :city=>"Thanh Hoa",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Thanh Hoa, Vietnam"},
 "TBB"=>
  {:iata=>"TBB",
   :name=>"Tuy Hoa Airport",
   :city=>"Tuy Hoa",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Tuy Hoa, Nam"},
 "TMK"=>
  {:iata=>"TMK",
   :name=>"Tamky Airport",
   :city=>"Tamky",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Tamky, Nam"},
 "TZA"=>
  {:iata=>"TZA",
   :name=>"Belize City Municipal Airport",
   :icao=>"",
   :city=>"Belize City",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Belize City, Belize"},
 "TNO"=>
  {:iata=>"TNO",
   :name=>"Tamarindo Airport",
   :icao=>"MRTM",
   :city=>"Tamarindo",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Tamarindo, Costa Rica"},
 "TMU"=>
  {:iata=>"TMU",
   :name=>"Tambor Airport",
   :icao=>"MRTR",
   :city=>"Tambor",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Tambor, Costa Rica"},
 "TTQ"=>
  {:iata=>"TTQ",
   :name=>"Tortuguero Airport",
   :icao=>"MRAO",
   :city=>"Tortuguero",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Tortuguero, Costa Rica"},
 "TOO"=>
  {:iata=>"TOO",
   :name=>"San Vito Airport",
   :city=>"San Vito",
   :icao=>"MRSV",
   :country=>'Rica', :country_code=>'',
   :location=>"San Vito, Rica"},
 "TKM"=>
  {:iata=>"TKM",
   :name=>"El Peten Airport",
   :city=>"Tikal",
   :icao=>"",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Tikal, Guatemala"},
 "TGU"=>
  {:iata=>"TGU",
   :name=>"Toncontín International Airport",
   :icao=>"MHTG",
   :city=>"Tegucigalpa",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Tegucigalpa, Honduras"},
 "TEA"=>
  {:iata=>"TEA",
   :name=>"Tela Airport",
   :city=>"Tela",
   :icao=>"MHTE",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Tela, Honduras"},
 "TCF"=>
  {:iata=>"TCF",
   :name=>"Tocoa Airport",
   :city=>"Tocoa",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Tocoa, Honduras"},
 "TJI"=>
  {:iata=>"TJI",
   :name=>"Capiro Airport",
   :city=>"Trujillo",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Trujillo, Honduras"},
 "TUW"=>
  {:iata=>"TUW",
   :name=>"Tubala Airport",
   :city=>"Tubala",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Tubala, Panama"},
 "TUE"=>
  {:iata=>"TUE",
   :name=>"Tupile Airport",
   :city=>"Tupile",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Tupile, Panama"},
 "TJC"=>
  {:iata=>"TJC",
   :name=>"Ticantiki Airport",
   :city=>"Ticantiki",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Ticantiki, Panama"},
 "TCP"=>
  {:iata=>"TCP",
   :name=>"Taba International Airport",
   :icao=>"HETB",
   :city=>"Taba",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Taba, Egypt"},
 "TFR"=>
  {:iata=>"TFR",
   :name=>"Wadi al Jandali Airport",
   :city=>"Ramadan City",
   :icao=>"",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Ramadan City, Egypt"},
 "TLV"=>
  {:iata=>"TLV",
   :name=>"Ben Gurion International Airport",
   :icao=>"LLBG",
   :city=>"Lod (near Tel Aviv)",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Lod (near Tel Aviv), Israel"},
 "TTH"=>
  {:iata=>"TTH",
   :name=>"Thumrait Airport",
   :city=>"Thumrait",
   :icao=>"OOTH",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Thumrait, Oman"},
 "TAI"=>
  {:iata=>"TAI",
   :name=>"Ta'izz International Airport",
   :icao=>"OYTZ",
   :city=>"Ta'izz",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Ta'izz, Yemen"},
 "TUU"=>
  {:iata=>"TUU",
   :name=>"Tabuk Regional Airport",
   :icao=>"OETB",
   :city=>"Tabuk",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Tabuk, Saudi Arabia"},
 "TIF"=>
  {:iata=>"TIF",
   :name=>"Ta'if Airport",
   :icao=>"OETF",
   :city=>"Ta'if",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Ta'if, Saudi Arabia"},
 "TUI"=>
  {:iata=>"TUI",
   :name=>"Turaif Airport",
   :city=>"Turaif",
   :icao=>"OETR",
   :country=>'Arabia', :country_code=>'',
   :location=>"Turaif, Arabia"},
 "TAD"=>
  {:iata=>"TAD",
   :name=>"Perry Stokes Airport",
   :icao=>"KTAD",
   :city=>"Trinidad",
   :country=>'United States', :country_code=>'US',

   :location=>"Trinidad, Colorado, United States"},
 "TAL"=>
  {:iata=>"TAL",
   :name=>"Ralph M. Calhoun Memorial Airport",
   :icao=>"PATA",
   :city=>"Tanana",
   :country=>'United States', :country_code=>'US',

   :location=>"Tanana, Alaska, United States"},
 "TBN"=>
  {:iata=>"TBN",
   :name=>"Waynesville-St. Robert Regional Airport (Forney Field)",
   :icao=>"KTBN",
   :city=>"Fort Leonard Wood",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Leonard Wood, Missouri, United States"},
 "TBR"=>
  {:iata=>"TBR",
   :name=>"Statesboro-Bulloch County Airport",
   :icao=>"KTBR",
   :city=>"Statesboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Statesboro, Georgia, United States"},
 "TCC"=>
  {:iata=>"TCC",
   :name=>"Tucumcari Municipal Airport",
   :icao=>"KTCC",
   :city=>"Tucumcari",
   :country=>'United States', :country_code=>'US',

   :location=>"Tucumcari, New Mexico, United States"},
 "TCI"=>
  {:iata=>"TCI",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Tenerife",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Tenerife, Canary Islands, Spain"},
 "TCL"=>
  {:iata=>"TCL",
   :name=>"Tuscaloosa Regional Airport",
   :icao=>"KTCL",
   :city=>"Tuscaloosa",
   :country=>'United States', :country_code=>'US',

   :location=>"Tuscaloosa, Alabama, United States"},
 "TCM"=>
  {:iata=>"TCM",
   :name=>"McChord Air Force Base",
   :icao=>"KTCM",
   :city=>"Tacoma",
   :country=>'United States', :country_code=>'US',

   :location=>"Tacoma, Washington, United States"},
 "TCS"=>
  {:iata=>"TCS",
   :name=>"Truth or Consequences Municipal Airport",
   :icao=>"KTCS",
   :city=>"Truth or Consequences",
   :country=>'United States', :country_code=>'US',

   :location=>"Truth or Consequences, New Mexico, United States"},
 "TCT"=>
  {:iata=>"TCT",
   :name=>"Takotna Airport",
   :icao=>"",
   :city=>"Takotna",
   :country=>'United States', :country_code=>'US',

   :location=>"Takotna, Alaska, United States"},
 "TDO"=>
  {:iata=>"TDO",
   :name=>"South Lewis County Airport (Ed Carlson Memorial Field)",
   :icao=>"KTDO",
   :city=>"Toledo",
   :country=>'United States', :country_code=>'US',

   :location=>"Toledo, Washington, United States"},
 "TDS"=>
  {:iata=>"TDS",
   :name=>"Sasereme Airport",
   :icao=>"",
   :city=>"Sasereme",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Sasereme, Papua New Guinea"},
 "TDW"=>
  {:iata=>"TDW",
   :name=>"Tradewind Airport",
   :icao=>"KTDW",
   :city=>"Amarillo",
   :country=>'United States', :country_code=>'US',

   :location=>"Amarillo, Texas, United States"},
 "TDZ"=>
  {:iata=>"TDZ",
   :name=>"Metcalf Field",
   :icao=>"KTDZ",
   :city=>"Toledo",
   :country=>'United States', :country_code=>'US',

   :location=>"Toledo, Ohio, United States"},
 "TEB"=>
  {:iata=>"TEB",
   :name=>"Teterboro Airport",
   :icao=>"KTEB",
   :city=>"Teterboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Teterboro, New Jersey, United States"},
 "TEK"=>
  {:iata=>"TEK",
   :name=>"Tatitlek Airport (FAA: 7KA)",
   :icao=>"",
   :city=>"Tatitlek",
   :country=>'United States', :country_code=>'US',

   :location=>"Tatitlek, Alaska, United States"},
 "TEX"=>
  {:iata=>"TEX",
   :name=>"Telluride Regional Airport",
   :icao=>"KTEX",
   :city=>"Telluride",
   :country=>'United States', :country_code=>'US',

   :location=>"Telluride, Colorado, United States"},
 "TGE"=>
  {:iata=>"TGE",
   :name=>"Sharpe Field (FAA: AL73)",
   :icao=>"",
   :city=>"Tuskegee",
   :country=>'United States', :country_code=>'US',

   :location=>"Tuskegee, Alabama, United States"},
 "THA"=>
  {:iata=>"THA",
   :name=>"Tullahoma Regional Airport (William Northern Field)",
   :icao=>"KTHA",
   :city=>"Tullahoma",
   :country=>'United States', :country_code=>'US',

   :location=>"Tullahoma, Tennessee, United States"},
 "THV"=>
  {:iata=>"THV",
   :name=>"York Airport",
   :icao=>"KTHV",
   :city=>"York",
   :country=>'United States', :country_code=>'US',

   :location=>"York, Pennsylvania, United States"},
 "TIK"=>
  {:iata=>"TIK",
   :name=>"Tinker Air Force Base",
   :icao=>"KTIK",
   :city=>"Oklahoma City",
   :country=>'United States', :country_code=>'US',

   :location=>"Oklahoma City, Oklahoma, United States"},
 "TIW"=>
  {:iata=>"TIW",
   :name=>"Tacoma Narrows Airport",
   :icao=>"KTIW",
   :city=>"Tacoma",
   :country=>'United States', :country_code=>'US',

   :location=>"Tacoma, Washington, United States"},
 "TIX"=>
  {:iata=>"TIX",
   :name=>"Space Coast Regional Airport",
   :icao=>"KTIX",
   :city=>"Titusville",
   :country=>'United States', :country_code=>'US',

   :location=>"Titusville, Florida, United States"},
 "TKA"=>
  {:iata=>"TKA",
   :name=>"Talkeetna Airport",
   :icao=>"PATK",
   :city=>"Talkeetna",
   :country=>'United States', :country_code=>'US',

   :location=>"Talkeetna, Alaska, United States"},
 "TKF"=>
  {:iata=>"TKF",
   :name=>"Truckee-Tahoe Airport (FAA: TRK)",
   :icao=>"KTRK",
   :city=>"Truckee",
   :country=>'United States', :country_code=>'US',

   :location=>"Truckee, California, United States"},
 "TKI"=>
  {:iata=>"TKI",
   :name=>"Tokeen Seaplane Base (FAA: 57A)",
   :icao=>"",
   :city=>"Tokeen",
   :country=>'United States', :country_code=>'US',

   :location=>"Tokeen, Alaska, United States"},
 "TKJ"=>
  {:iata=>"TKJ",
   :name=>"Tok Airport",
   :icao=>"PATJ",
   :city=>"Tok",
   :country=>'United States', :country_code=>'US',

   :location=>"Tok, Alaska, United States"},
 "TLA"=>
  {:iata=>"TLA",
   :name=>"Teller Airport (FAA: TER)",
   :icao=>"PATE",
   :city=>"Teller",
   :country=>'United States', :country_code=>'US',

   :location=>"Teller, Alaska, United States"},
 "TLF"=>
  {:iata=>"TLF",
   :name=>"Telida Airport (FAA: 2K5)",
   :icao=>"",
   :city=>"Telida",
   :country=>'United States', :country_code=>'US',

   :location=>"Telida, Alaska, United States"},
 "TLH"=>
  {:iata=>"TLH",
   :name=>"Tallahassee Regional Airport",
   :icao=>"KTLH",
   :city=>"Tallahassee",
   :country=>'United States', :country_code=>'US',

   :location=>"Tallahassee, Florida, United States"},
 "TLJ"=>
  {:iata=>"TLJ",
   :name=>"Tatalina LRRS Airport",
   :icao=>"PATL",
   :city=>"Takotna",
   :country=>'United States', :country_code=>'US',

   :location=>"Takotna, Alaska, United States"},
 "TLR"=>
  {:iata=>"TLR",
   :name=>"Mefford Field",
   :icao=>"KTLR",
   :city=>"Tulare",
   :country=>'United States', :country_code=>'US',

   :location=>"Tulare, California, United States"},
 "TLT"=>
  {:iata=>"TLT",
   :name=>"Tuluksak Airport",
   :icao=>"",
   :city=>"Tuluksak",
   :country=>'United States', :country_code=>'US',

   :location=>"Tuluksak, Alaska, United States"},
 "TMA"=>
  {:iata=>"TMA",
   :name=>"Henry Tift Myers Airport",
   :icao=>"KTMA",
   :city=>"Tifton",
   :country=>'United States', :country_code=>'US',

   :location=>"Tifton, Georgia, United States"},
 "TMB"=>
  {:iata=>"TMB",
   :name=>"Kendall-Tamiami Executive Airport",
   :icao=>"KTMB",
   :city=>"Miami",
   :country=>'United States', :country_code=>'US',

   :location=>"Miami, Florida, United States"},
 "TNC"=>
  {:iata=>"TNC",
   :name=>"Tin City LRRS Airport",
   :icao=>"PATC",
   :city=>"Tin City",
   :country=>'United States', :country_code=>'US',

   :location=>"Tin City, Alaska, United States"},
 "TNK"=>
  {:iata=>"TNK",
   :name=>"Tununak Airport (FAA: 4KA)",
   :icao=>"",
   :city=>"Tununak",
   :country=>'United States', :country_code=>'US',

   :location=>"Tununak, Alaska, United States"},
 "TNP"=>
  {:iata=>"TNP",
   :name=>"Twentynine Palms Airport",
   :icao=>"KTNP",
   :city=>"Twentynine Palms",
   :country=>'United States', :country_code=>'US',

   :location=>"Twentynine Palms, California, United States"},
 "TNT"=>
  {:iata=>"TNT",
   :name=>"Dade-Collier Training and Transition Airport",
   :icao=>"KTNT",
   :city=>"Miami",
   :country=>'United States', :country_code=>'US',

   :location=>"Miami, Florida, United States"},
 "TNU"=>
  {:iata=>"TNU",
   :name=>"Newton Municipal Airport",
   :icao=>"KTNU",
   :city=>"Newton",
   :country=>'United States', :country_code=>'US',

   :location=>"Newton, Iowa, United States"},
 "TOA"=>
  {:iata=>"TOA",
   :name=>"Zamperini Field",
   :icao=>"KTOA",
   :city=>"Torrance",
   :country=>'United States', :country_code=>'US',

   :location=>"Torrance, California, United States"},
 "TOC"=>
  {:iata=>"TOC",
   :name=>"Toccoa Airport (R.G. LeTourneau Field)",
   :icao=>"KTOC",
   :city=>"Toccoa",
   :country=>'United States', :country_code=>'US',

   :location=>"Toccoa, Georgia, United States"},
 "TOG"=>
  {:iata=>"TOG",
   :name=>"Togiak Airport",
   :icao=>"PATG",
   :city=>"Togiak Village",
   :country=>'United States', :country_code=>'US',

   :location=>"Togiak Village, Alaska, United States"},
 "TOI"=>
  {:iata=>"TOI",
   :name=>"Troy Municipal Airport",
   :icao=>"KTOI",
   :city=>"Troy",
   :country=>'United States', :country_code=>'US',

   :location=>"Troy, Alabama, United States"},
 "TOL"=>
  {:iata=>"TOL",
   :name=>"Toledo Express Airport",
   :icao=>"KTOL",
   :city=>"Toledo",
   :country=>'United States', :country_code=>'US',

   :location=>"Toledo, Ohio, United States"},
 "TOP"=>
  {:iata=>"TOP",
   :name=>"Philip Billard Municipal Airport",
   :icao=>"KTOP",
   :city=>"Topeka",
   :country=>'United States', :country_code=>'US',

   :location=>"Topeka, Kansas, United States"},
 "TPA"=>
  {:iata=>"TPA",
   :name=>"Tampa International Airport",
   :icao=>"KTPA",
   :city=>"Tampa",
   :country=>'United States', :country_code=>'US',

   :location=>"Tampa, Florida, United States"},
 "TPF"=>
  {:iata=>"TPF",
   :name=>"Peter O. Knight Airport",
   :icao=>"KTPF",
   :city=>"Tampa",
   :country=>'United States', :country_code=>'US',

   :location=>"Tampa, Florida, United States"},
 "TPH"=>
  {:iata=>"TPH",
   :name=>"Tonopah Airport",
   :icao=>"KTPH",
   :city=>"Tonopah",
   :country=>'United States', :country_code=>'US',

   :location=>"Tonopah, Nevada, United States"},
 "TPL"=>
  {:iata=>"TPL",
   :name=>"Draughon-Miller Central Texas Regional Airport",
   :icao=>"KTPL",
   :city=>"Temple",
   :country=>'United States', :country_code=>'US',

   :location=>"Temple, Texas, United States"},
 "TRH"=>
  {:iata=>"TRH",
   :name=>"Trona Airport (FAA: L72)",
   :icao=>"",
   :city=>"Trona",
   :country=>'United States', :country_code=>'US',

   :location=>"Trona, California, United States"},
 "TRI"=>
  {:iata=>"TRI",
   :name=>"Tri-Cities Regional Airport",
   :icao=>"KTRI",
   :city=>"Blountville",
   :country=>'United States', :country_code=>'US',

   :location=>"Blountville, Tennessee (Tri-Cities area), United States"},
 "TRL"=>
  {:iata=>"TRL",
   :name=>"Terrell Municipal Airport",
   :icao=>"KTRL",
   :city=>"Terrell",
   :country=>'United States', :country_code=>'US',

   :location=>"Terrell, Texas, United States"},
 "TRM"=>
  {:iata=>"TRM",
   :name=>"Jacqueline Cochran Regional Airport",
   :icao=>"KTRM",
   :city=>"Palm Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Palm Springs, California, United States"},
 "TRX"=>
  {:iata=>"TRX",
   :name=>"Trenton Municipal Airport",
   :icao=>"KTRX",
   :city=>"Trenton",
   :country=>'United States', :country_code=>'US',

   :location=>"Trenton, Missouri, United States"},
 "TSG"=>
  {:iata=>"TSG",
   :name=>"Tanacross Airport",
   :icao=>"",
   :city=>"Tanacross",
   :country=>'United States', :country_code=>'US',

   :location=>"Tanacross, Alaska, United States"},
 "TSM"=>
  {:iata=>"TSM",
   :name=>"Taos Regional Airport (FAA: SKX)",
   :icao=>"KSKX",
   :city=>"Taos",
   :country=>'United States', :country_code=>'US',

   :location=>"Taos, New Mexico, United States"},
 "TSP"=>
  {:iata=>"TSP",
   :name=>"Tehachapi Municipal Airport",
   :icao=>"KTSP",
   :city=>"Tehachapi",
   :country=>'United States', :country_code=>'US',

   :location=>"Tehachapi, California, United States"},
 "TSS"=>
  {:iata=>"TSS",
   :name=>"East 34th Street Heliport (FAA: 6N5)",
   :icao=>"",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, United States"},
 "TTD"=>
  {:iata=>"TTD",
   :name=>"Portland-Troutdale Airport",
   :icao=>"KTTD",
   :city=>"Portland",
   :country=>'United States', :country_code=>'US',

   :location=>"Portland, Oregon, United States"},
 "TTN"=>
  {:iata=>"TTN",
   :name=>"Trenton-Mercer Airport",
   :icao=>"KTTN",
   :city=>"Trenton",
   :country=>'United States', :country_code=>'US',

   :location=>"Trenton, New Jersey, United States"},
 "TTO"=>
  {:iata=>"TTO",
   :name=>"Britton Municipal Airport (FAA: BTN)",
   :icao=>"KBTN",
   :city=>"Britton",
   :country=>'United States', :country_code=>'US',

   :location=>"Britton, South Dakota, United States"},
 "TUL"=>
  {:iata=>"TUL",
   :name=>"Tulsa International Airport",
   :icao=>"KTUL",
   :city=>"Tulsa",
   :country=>'United States', :country_code=>'US',

   :location=>"Tulsa, Oklahoma, United States"},
 "TUP"=>
  {:iata=>"TUP",
   :name=>"Tupelo Regional Airport",
   :icao=>"KTUP",
   :city=>"Tupelo",
   :country=>'United States', :country_code=>'US',

   :location=>"Tupelo, Mississippi, United States"},
 "TUS"=>
  {:iata=>"TUS",
   :name=>"Tucson International Airport",
   :icao=>"KTUS",
   :city=>"Tucson",
   :country=>'United States', :country_code=>'US',

   :location=>"Tucson, Arizona, United States"},
 "TVC"=>
  {:iata=>"TVC",
   :name=>"Cherry Capital Airport",
   :icao=>"KTVC",
   :city=>"Traverse City",
   :country=>'United States', :country_code=>'US',

   :location=>"Traverse City, Michigan, United States"},
 "TVF"=>
  {:iata=>"TVF",
   :name=>"Thief River Falls Regional Airport",
   :icao=>"KTVF",
   :city=>"Thief River Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Thief River Falls, Minnesota, United States"},
 "TVI"=>
  {:iata=>"TVI",
   :name=>"Thomasville Regional Airport",
   :icao=>"KTVI",
   :city=>"Thomasville",
   :country=>'United States', :country_code=>'US',

   :location=>"Thomasville, Georgia, United States"},
 "TVL"=>
  {:iata=>"TVL",
   :name=>"Lake Tahoe Airport",
   :icao=>"KTVL",
   :city=>"South Lake Tahoe",
   :country=>'United States', :country_code=>'US',

   :location=>"South Lake Tahoe, California, United States"},
 "TWA"=>
  {:iata=>"TWA",
   :name=>"Twin Hills Airport (FAA: A63)",
   :icao=>"",
   :city=>"Twin Hills",
   :country=>'United States', :country_code=>'US',

   :location=>"Twin Hills, Alaska, United States"},
 "TWD"=>
  {:iata=>"TWD",
   :name=>"Jefferson County International Airport (FAA: 0S9)",
   :icao=>"",
   :city=>"Port Townsend",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Townsend, Washington, United States"},
 "TWE"=>
  {:iata=>"TWE",
   :name=>"Taylor Airport (FAA: AK49)",
   :icao=>"",
   :city=>"Taylor",
   :country=>'United States', :country_code=>'US',

   :location=>"Taylor, Alaska, United States"},
 "TWF"=>
  {:iata=>"TWF",
   :name=>"Magic Valley Regional Airport (Joslin Field)",
   :icao=>"KTWF",
   :city=>"Twin Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Twin Falls, Idaho, United States"},
 "TXK"=>
  {:iata=>"TXK",
   :name=>"Texarkana Regional Airport (Webb Field)",
   :icao=>"KTXK",
   :city=>"Texarkana",
   :country=>'United States', :country_code=>'US',

   :location=>"Texarkana, Arkansas, United States"},
 "TYE"=>
  {:iata=>"TYE",
   :name=>"Tyonek Airport",
   :icao=>"",
   :city=>"Tyonek",
   :country=>'United States', :country_code=>'US',

   :location=>"Tyonek, Alaska, United States"},
 "TYO"=>
  {:iata=>"TYO",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Tokyo",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tokyo, Japan"},
 "TYR"=>
  {:iata=>"TYR",
   :name=>"Tyler Pounds Regional Airport",
   :icao=>"KTYR",
   :city=>"Tyler",
   :country=>'United States', :country_code=>'US',

   :location=>"Tyler, Texas, United States"},
 "TYS"=>
  {:iata=>"TYS",
   :name=>"McGhee Tyson Airport",
   :icao=>"KTYS",
   :city=>"Knoxville",
   :country=>'United States', :country_code=>'US',

   :location=>"Knoxville, Tennessee, United States"},
 "TYZ"=>
  {:iata=>"TYZ",
   :name=>"Taylor Airport (FAA: TYL)",
   :icao=>"KTYL",
   :city=>"Taylor",
   :country=>'United States', :country_code=>'US',

   :location=>"Taylor, Arizona, United States"}}

end
