# encoding: UTF-8
def airp_23
  {"VER"=>
  {:iata=>"VER",
   :name=>"General Heriberto Jara International Airport",
   :icao=>"MMVR",
   :city=>"Veracruz",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Veracruz, Veracruz, Mexico"},
 "VSA"=>
  {:iata=>"VSA",
   :name=>"Carlos Rovirosa Pérez International Airport",
   :icao=>"MMVA",
   :city=>"Villahermosa",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Villahermosa, Tabasco, Mexico"},
 "VIB"=>
  {:iata=>"VIB",
   :name=>"Villa Constitucion Airport",
   :city=>"Villa Constitucion",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Villa Constitucion, Mexico"},
 "VDM"=>
  {:iata=>"VDM",
   :name=>"Gobernador Edgardo Castello Airport",
   :icao=>"SAVV",
   :city=>"Viedma",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Viedma, Argentina"},
 "VLG"=>
  {:iata=>"VLG",
   :name=>"Villa Gesell - Pinamar International Airport",
   :icao=>"SAZV",
   :city=>"Villa Gesell",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Villa Gesell, Buenos Aires, Argentina"},
 "VME"=>
  {:iata=>"VME",
   :name=>"Pringles Airport",
   :icao=>"SAOR",
   :city=>"Villa Mercedes",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Villa Mercedes, San Luis, Argentina"},
 "VGS"=>
  {:iata=>"VGS",
   :name=>"General Villegas Airport",
   :city=>"General Villegas",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"General Villegas, Argentina"},
 "VCF"=>
  {:iata=>"VCF",
   :name=>"Valcheta Airport",
   :city=>"Valcheta",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Valcheta, Argentina"},
 "VDR"=>
  {:iata=>"VDR",
   :name=>"Villa Dolores Airport",
   :icao=>"SAOD",
   :city=>"Villa Dolores",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Villa Dolores, Córdoba, Argentina"},
 "VVI"=>
  {:iata=>"VVI",
   :name=>"Viru Viru International Airport",
   :icao=>"SLVR",
   :city=>"Santa Cruz",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Santa Cruz, Bolivia"},
 "VAH"=>
  {:iata=>"VAH",
   :name=>"Vallegrande Airport",
   :city=>"Vallegrande",
   :icao=>"SLVG",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Vallegrande, Bolivia"},
 "VLM"=>
  {:iata=>"VLM",
   :name=>"Villamontes Airport",
   :city=>"Villamontes",
   :icao=>"SLVM",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Villamontes, Bolivia"},
 "VCP"=>
  {:iata=>"VCP",
   :name=>"Viracopos-Campinas International Airport",
   :icao=>"SBKP",
   :city=>"Campinas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Campinas, São Paulo State, Brazil"},
 "VAL"=>
  {:iata=>"VAL",
   :name=>"Valenca Airport",
   :city=>"Valenca",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Valenca, Brazil"},
 "VAG"=>
  {:iata=>"VAG",
   :name=>"Major Brigadeiro Trompowsky Airport",
   :icao=>"SBVG",
   :city=>"Varginha",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Varginha, Minas Gerais, Brazil"},
 "VIX"=>
  {:iata=>"VIX",
   :name=>"Eurico de Aguiar Salles Airport",
   :icao=>"SBVT",
   :city=>"Vitória",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Vitória, Espírito Santo, Brazil"},
 "VDC"=>
  {:iata=>"VDC",
   :name=>"Vitória da Conquista Airport",
   :icao=>"SBQV",
   :city=>"Vitória da Conquista",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Vitória da Conquista, Brazil"},
 "VIA"=>
  {:iata=>"VIA",
   :name=>"Videira Airport",
   :icao=>"SSVI",
   :city=>"Videira",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Videira, Santa Catarina, Brazil"},
 "VLP"=>
  {:iata=>"VLP",
   :name=>"Vila Rica Municipal Airport",
   :city=>"Vila Rica",
   :icao=>"SWVC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Vila Rica, Brazil"},
 "VOT"=>
  {:iata=>"VOT",
   :name=>"Votuporanga Airport",
   :city=>"Votuporanga",
   :icao=>"SDVG",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Votuporanga, Brazil"},
 "VLR"=>
  {:iata=>"VLR",
   :name=>"Vallenar Airport",
   :city=>"Vallenar",
   :icao=>"SCLL",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Vallenar, Chile"},
 "VAP"=>
  {:iata=>"VAP",
   :name=>"Valparaiso Airport",
   :city=>"Valparaiso",
   :icao=>"",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Valparaiso, Chile"},
 "VUP"=>
  {:iata=>"VUP",
   :name=>"Alfonso López Pumarejo Airport",
   :icao=>"SKVP",
   :city=>"Valledupar",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Valledupar, Colombia"},
 "VGZ"=>
  {:iata=>"VGZ",
   :name=>"Villa Garzón Airport",
   :icao=>"SKVG",
   :city=>"Villa Garzón",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Villa Garzón, Colombia"},
 "VVC"=>
  {:iata=>"VVC",
   :name=>"La Vanguardia Airport",
   :city=>"Villavicencio",
   :icao=>"SKVV",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Villavicencio, Colombia"},
 "VAB"=>
  {:iata=>"VAB",
   :name=>"Yavarate Airport",
   :city=>"Yavarate",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Yavarate, Colombia"},
 "VEG"=>
  {:iata=>"VEG",
   :name=>"Maikwak Airport",
   :city=>"Maikwak",
   :icao=>"",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Maikwak, Guyana"},
 "VMI"=>
  {:iata=>"VMI",
   :name=>"Vallemi Airport",
   :city=>"Vallemi",
   :icao=>"",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Vallemi, Paraguay"},
 "VCH"=>
  {:iata=>"VCH",
   :name=>"Vichadero Airport",
   :icao=>"SUVO",
   :city=>"Vichadero",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Vichadero, Rivera, Uruguay"},
 "VIG"=>
  {:iata=>"VIG",
   :name=>"Juan Pablo Perez Alfonso Airport",
   :icao=>"SVVG",
   :city=>"El Vigía",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"El Vigía, Venezuela"},
 "VLN"=>
  {:iata=>"VLN",
   :name=>"Arturo Michelena International Airport",
   :icao=>"SVVA",
   :city=>"Valencia",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Valencia, Carabobo, Venezuela"},
 "VLV"=>
  {:iata=>"VLV",
   :name=>"Dr. Antonio Nicolás Briceno Airport",
   :icao=>"SVVL",
   :city=>"Valera",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Valera, Venezuela"},
 "VCR"=>
  {:iata=>"VCR",
   :name=>"Carora Airport",
   :city=>"Carora",
   :icao=>"SVCO",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Carora, Venezuela"},
 "VDP"=>
  {:iata=>"VDP",
   :name=>"Valle de la Pascua Airport",
   :icao=>"SVVP",
   :city=>"Valle de la Pascua",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Valle de la Pascua, Guárico, Venezuela"},
 "VNR"=>
  {:iata=>"VNR",
   :name=>"Vanrook Airport",
   :city=>"Vanrook",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Vanrook, Australia"},
 "VCD"=>
  {:iata=>"VCD",
   :name=>"Victoria River Downs Airport",
   :city=>"Victoria River Downs",
   :icao=>"YVRD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Victoria River Downs, Australia"},
 "VBV"=>
  {:iata=>"VBV",
   :name=>"Vanuabalavu Airport",
   :city=>"Vanuabalavu",
   :icao=>"NFVB",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Vanuabalavu, Fiji"},
 "VAU"=>
  {:iata=>"VAU",
   :name=>"Vatukoula Airport",
   :city=>"Vatukoula",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Vatukoula, Fiji"},
 "VTF"=>
  {:iata=>"VTF",
   :name=>"Vatulele Airport",
   :city=>"Vatulele",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Vatulele, Fiji"},
 "VHZ"=>
  {:iata=>"VHZ",
   :name=>"Vahitahi Airport",
   :city=>"Vahitahi",
   :icao=>"NTUV",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Vahitahi, Polynesia"},
 "VAO"=>
  {:iata=>"VAO",
   :name=>"Suavanao Airport",
   :city=>"Suavanao",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Suavanao, Islands"},
 "VEV"=>
  {:iata=>"VEV",
   :name=>"Barakoma Airport",
   :city=>"Barakoma",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Barakoma, Islands"},
 "VIU"=>
  {:iata=>"VIU",
   :name=>"Viru Harbour Airstrip",
   :city=>"Viru",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Viru, Islands"},
 "VAV"=>
  {:iata=>"VAV",
   :name=>"Lupepau'u Airport",
   :city=>"Vava'u",
   :icao=>"NFTV",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Vava'u, Tonga"},
 "VLI"=>
  {:iata=>"VLI",
   :name=>"Bauerfield International Airport",
   :icao=>"NVVV",
   :city=>"Port Vila",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Port Vila, Vanuatu"},
 "VLS"=>
  {:iata=>"VLS",
   :name=>"Valesdir Airport",
   :city=>"Valesdir",
   :icao=>"NVSV",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Valesdir, Vanuatu"},
 "VIJ"=>
  {:iata=>"VIJ",
   :name=>"Virgin Gorda Airport",
   :icao=>"TUPW",
   :city=>"Virgin Gorda",
   :country=>'British Virgin Islands', :country_code=>'',
   :location=>"Virgin Gorda, British Virgin Islands"},
 "VTU"=>
  {:iata=>"VTU",
   :name=>"Las Tunas Airport",
   :city=>"Las Tunas",
   :icao=>"MUVT",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Las Tunas, Cuba"},
 "VRA"=>
  {:iata=>"VRA",
   :name=>"Juan Gualberto Gómez Airport",
   :icao=>"MUVR",
   :city=>"Varadero",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Varadero, Matanzas Province, Cuba"},
 "VRO"=>
  {:iata=>"VRO",
   :name=>"Kawama Airport",
   :icao=>"MUKW",
   :city=>"Varadero",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Varadero, Matanzas Province, Cuba"},
 "VQS"=>
  {:iata=>"VQS",
   :name=>"Antonio Rivera Rodriguez Airport",
   :icao=>"TJVQ",
   :city=>"Vieques",
   :country=>'United States', :country_code=>'US',

   :location=>"Vieques, Puerto Rico, United States"},
 "VVZ"=>
  {:iata=>"VVZ",
   :name=>"Illizi Airport",
   :city=>"Illizi",
   :icao=>"DAAP",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Illizi, Algeria"},
 "VPE"=>
  {:iata=>"VPE",
   :name=>"Ongiva Airport",
   :city=>"Ongiva",
   :icao=>"",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Ongiva, Angola"},
 "VHC"=>
  {:iata=>"VHC",
   :name=>"Saurimo Airport",
   :city=>"Saurimo",
   :icao=>"FNSA",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Saurimo, Angola"},
 "VCC"=>
  {:iata=>"VCC",
   :name=>"Limbe Airport",
   :icao=>"",
   :city=>"Limbe",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Limbe, Cameroon"},
 "VXE"=>
  {:iata=>"VXE",
   :name=>"Sao Pedro Airport",
   :icao=>"GVSV",
   :city=>"São Vicente",
   :country=>'Cape Verde', :country_code=>'CV',
   :location=>"São Vicente, Cape Verde"},
 "VPG"=>
  {:iata=>"VPG",
   :name=>"Vipingo Airport",
   :city=>"Vipingo",
   :icao=>"",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Vipingo, Kenya"},
 "VOI"=>
  {:iata=>"VOI",
   :name=>"Voinjama Airport",
   :icao=>"GLVA",
   :city=>"Voinjama",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Voinjama, Liberia"},
 "VVB"=>
  {:iata=>"VVB",
   :name=>"Mahanoro Airport",
   :city=>"Mahanoro",
   :icao=>"FMMH",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Mahanoro, Madagascar"},
 "VND"=>
  {:iata=>"VND",
   :name=>"Vangaindrano Airport",
   :city=>"Vangaindrano",
   :icao=>"FMSU",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Vangaindrano, Madagascar"},
 "VAT"=>
  {:iata=>"VAT",
   :name=>"Vatomandry Airport",
   :city=>"Vatomandry",
   :icao=>"FMMY",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Vatomandry, Madagascar"},
 "VOH"=>
  {:iata=>"VOH",
   :name=>"Vohemar Airport",
   :city=>"Vohemar",
   :icao=>"FMNV",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Vohemar, Madagascar"},
 "VUU"=>
  {:iata=>"VUU",
   :name=>"MVUU Camp",
   :city=>"Blantyre",
   :icao=>"",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Blantyre, Malawi"},
 "VIL"=>
  {:iata=>"VIL",
   :name=>"Dakhla Airport",
   :icao=>"GMMH",
   :city=>"Dakhla",
   :country=>'Western Sahara', :country_code=>'EH',
   :location=>"Dakhla, Western Sahara"},
 "VPY"=>
  {:iata=>"VPY",
   :name=>"Chimoio Airport",
   :icao=>"FQCH",
   :city=>"Chimoio",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Chimoio, Mozambique"},
 "VXC"=>
  {:iata=>"VXC",
   :name=>"Lichinga Airport",
   :icao=>"FQLC",
   :city=>"Lichinga",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Lichinga, Mozambique"},
 "VNX"=>
  {:iata=>"VNX",
   :name=>"Vilankulo Airport",
   :icao=>"FQVL",
   :city=>"Vilanculos",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Vilanculos, Mozambique"},
 "VJQ"=>
  {:iata=>"VJQ",
   :name=>"Gurue Airport",
   :city=>"Gurue",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Gurue, Mozambique"},
 "VHO"=>
  {:iata=>"VHO",
   :name=>"Vila Coutinho Airport",
   :city=>"Vila Coutinho",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Vila Coutinho, Mozambique"},
 "VJB"=>
  {:iata=>"VJB",
   :name=>"Xai Xai Airport",
   :icao=>"FQXA",
   :city=>"Xai Xai",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Xai Xai, Mozambique"},
 "VIR"=>
  {:iata=>"VIR",
   :name=>"Virginia Airport",
   :city=>"Durban",
   :icao=>"FAVG",
   :country=>'Africa', :country_code=>'',
   :location=>"Durban, Africa"},
 "VRE"=>
  {:iata=>"VRE",
   :name=>"Vredendal Airport",
   :city=>"Vredendal",
   :icao=>"FAVR",
   :country=>'Africa', :country_code=>'',
   :location=>"Vredendal, Africa"},
 "VRU"=>
  {:iata=>"VRU",
   :name=>"Vryburg Airport",
   :city=>"Vryburg",
   :icao=>"FAVB",
   :country=>'Africa', :country_code=>'',
   :location=>"Vryburg, Africa"},
 "VYD"=>
  {:iata=>"VYD",
   :name=>"Vryheid Airport",
   :icao=>"FAVY",
   :city=>"Vryheid",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Vryheid, South Africa"},
 "VFA"=>
  {:iata=>"VFA",
   :name=>"Victoria Falls Airport",
   :icao=>"FVFA",
   :city=>"Victoria Falls",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Victoria Falls, Zimbabwe"},
 "VIE"=>
  {:iata=>"VIE",
   :name=>"Vienna International Airport",
   :icao=>"LOWW",
   :city=>"Vienna",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Vienna, Austria"},
 "VDD"=>
  {:iata=>"VDD",
   :name=>"Vienna Danubepier Airport",
   :city=>"Vienna",
   :icao=>"",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Vienna, Austria"},
 "VTB"=>
  {:iata=>"VTB",
   :name=>"Vitebsk Airport",
   :city=>"Vitebsk",
   :icao=>"UMII",
   :country=>'Belarus', :country_code=>'BY',
   :location=>"Vitebsk, Belarus"},
 "VAR"=>
  {:iata=>"VAR",
   :name=>"Varna Airport",
   :icao=>"LBWN",
   :city=>"Varna",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Varna, Bulgaria"},
 "VID"=>
  {:iata=>"VID",
   :name=>"Vidin Airport",
   :icao=>"LBVD",
   :city=>"Vidin",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Vidin, Bulgaria"},
 "VEJ"=>
  {:iata=>"VEJ",
   :name=>"Vejle Airport",
   :city=>"Vejle",
   :icao=>"",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Vejle, Denmark"},
 "VAA"=>
  {:iata=>"VAA",
   :name=>"Vaasa Airport",
   :icao=>"EFVA",
   :city=>"Vaasa",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Vaasa, Finland"},
 "VRK"=>
  {:iata=>"VRK",
   :name=>"Varkaus Airport",
   :icao=>"EFVR",
   :city=>"Joroinen",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Joroinen, Finland"},
 "VAZ"=>
  {:iata=>"VAZ",
   :name=>"Val D'Isere Airport",
   :city=>"Val D'Isere",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Val D'Isere, France"},
 "VAF"=>
  {:iata=>"VAF",
   :name=>"Valence-Chabeuil Airport",
   :icao=>"LFLU",
   :city=>"Valence",
   :country=>'France', :country_code=>'FR',
   :location=>"Valence, France"},
 "VNE"=>
  {:iata=>"VNE",
   :name=>"Vannes-Meucon Airport",
   :icao=>"LFRV",
   :city=>"Vannes",
   :country=>'France', :country_code=>'FR',
   :location=>"Vannes, France"},
 "VHY"=>
  {:iata=>"VHY",
   :name=>"Charmeil Airport",
   :city=>"Vichy",
   :icao=>"LFLV",
   :country=>'France', :country_code=>'FR',
   :location=>"Vichy, France"},
 "VIY"=>
  {:iata=>"VIY",
   :name=>"Villa Coublay Airport",
   :city=>"Villa Coublay",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Villa Coublay, France"},
 "VTL"=>
  {:iata=>"VTL",
   :name=>"Vittel Airport",
   :city=>"Vittel",
   :icao=>"LFSZ",
   :country=>'France', :country_code=>'FR',
   :location=>"Vittel, France"},
 "VAC"=>
  {:iata=>"VAC",
   :name=>"Varrelbusch Airport",
   :city=>"Varrelbusch",
   :icao=>"EDWU",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Varrelbusch, Germany"},
 "VOL"=>
  {:iata=>"VOL",
   :name=>"International Airport of Central Greece",
   :icao=>"LGBL",
   :city=>"Volos",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Volos, Greece"},
 "VEY"=>
  {:iata=>"VEY",
   :name=>"Vestmannaeyjar Airport",
   :icao=>"BIVM",
   :city=>"Vestmannaeyjar",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Vestmannaeyjar, Iceland"},
 "VPN"=>
  {:iata=>"VPN",
   :name=>"Vopnafjörður Airport",
   :icao=>"BIVO",
   :city=>"Vopnafjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Vopnafjörður, Iceland"},
 "VCE"=>
  {:iata=>"VCE",
   :name=>"Venice Marco Polo Airport",
   :icao=>"LIPZ",
   :city=>"Venice",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Venice, Italy"},
 "VBS"=>
  {:iata=>"VBS",
   :name=>"Brescia Montichiari International Airport",
   :icao=>"LIPO",
   :city=>"Brescia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Brescia, Italy"},
 "VRN"=>
  {:iata=>"VRN",
   :name=>"Verona Airport",
   :icao=>"LIPX",
   :city=>"Verona",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Verona, Italy"},
 "VIC"=>
  {:iata=>"VIC",
   :name=>"Vicenza Airport",
   :icao=>"LIPT",
   :city=>"Vicenza",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Vicenza, Italy"},
 "VIF"=>
  {:iata=>"VIF",
   :name=>"Vieste Airport",
   :icao=>"",
   :city=>"Vieste",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Vieste, Italy"},
 "VNO"=>
  {:iata=>"VNO",
   :name=>"Vilnius International Airport",
   :icao=>"EYVI",
   :city=>"Vilnius",
   :country=>'Lithuania', :country_code=>'LT',
   :location=>"Vilnius, Lithuania"},
 "VDB"=>
  {:iata=>"VDB",
   :name=>"Fagernes Airport, Leirin",
   :icao=>"ENFG",
   :city=>"Fagernes",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Fagernes, Norway"},
 "VDS"=>
  {:iata=>"VDS",
   :name=>"Vadsø Airport",
   :icao=>"ENVD",
   :city=>"Vadsø",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Vadsø, Finnmark, Norway"},
 "VRY"=>
  {:iata=>"VRY",
   :name=>"Værøy Heliport",
   :icao=>"ENVR",
   :city=>"Værøy",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Værøy, Nordland, Norway"},
 "VAW"=>
  {:iata=>"VAW",
   :name=>"Vardø Airport, Svartnes",
   :icao=>"ENSS",
   :city=>"Vardø",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Vardø, Norway"},
 "VRL"=>
  {:iata=>"VRL",
   :name=>"Vila Real Airport",
   :icao=>"LPVR",
   :city=>"Vila Real",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Vila Real, Portugal"},
 "VSE"=>
  {:iata=>"VSE",
   :name=>"Viseu Airport",
   :city=>"Viseu",
   :icao=>"LPVZ",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Viseu, Portugal"},
 "VKO"=>
  {:iata=>"VKO",
   :name=>"Vnukovo International Airport",
   :icao=>"UUWW",
   :city=>"Moscow",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Moscow, Russia"},
 "VHV"=>
  {:iata=>"VHV",
   :name=>"Verkhnevilyuysk Airport",
   :icao=>"",
   :city=>"Verkhnevilyuysk",
   :country=>'Russia', :country_code=>'RU',
   :location=>
    "Verkhnevilyuysk, Woehee Bueluue District, Sakha Republic, Russia"},
 "VYI"=>
  {:iata=>"VYI",
   :name=>"Vilyuysk Airport",
   :icao=>"UENW",
   :city=>"Vilyuysk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Vilyuysk, Sakha Republic, Russia"},
 "VVO"=>
  {:iata=>"VVO",
   :name=>"Vladivostok International Airport (Knevichi Airport)",
   :icao=>"UHWW",
   :city=>"Vladivostok",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Vladivostok, Russia"},
 "VOG"=>
  {:iata=>"VOG",
   :name=>"Gumrak Airport",
   :icao=>"URWW",
   :city=>"Volgograd",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Volgograd, Russia"},
 "VKT"=>
  {:iata=>"VKT",
   :name=>"Vorkuta Airport",
   :icao=>"UUYW",
   :city=>"Vorkuta",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Vorkuta, Russia"},
 "VOZ"=>
  {:iata=>"VOZ",
   :name=>"Voronezh International Airport",
   :icao=>"UUOO",
   :city=>"Voronezh",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Voronezh, Russia"},
 "VUS"=>
  {:iata=>"VUS",
   :name=>"Velikiy Ustyug Airport",
   :icao=>"",
   :city=>"Veliky Ustyug",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Veliky Ustyug, Vologda, Russia"},
 "VLU"=>
  {:iata=>"VLU",
   :name=>"Velikiye Luki Airport",
   :icao=>"ULOL",
   :city=>"Velikiye Luki",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Velikiye Luki, Pskov Oblast, Russia"},
 "VLK"=>
  {:iata=>"VLK",
   :name=>"Volgodonsk Airport",
   :city=>"Volgodonsk",
   :icao=>"",
   :country=>'Federation', :country_code=>'',
   :location=>"Volgodonsk, Federation"},
 "VGD"=>
  {:iata=>"VGD",
   :name=>"Vologda Airport",
   :icao=>"ULWW",
   :city=>"Vologda",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Vologda, Russia"},
 "VLC"=>
  {:iata=>"VLC",
   :name=>"Valencia Airport",
   :icao=>"LEVC",
   :city=>"Valencia",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Valencia, Valencian Community, Spain"},
 "VLL"=>
  {:iata=>"VLL",
   :name=>"Valladolid Airport",
   :icao=>"LEVD",
   :city=>"Valladolid",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Valladolid, Spain"},
 "VDE"=>
  {:iata=>"VDE",
   :name=>"Hierro Airport",
   :city=>"Valverde",
   :icao=>"GCHI",
   :country=>'Islands', :country_code=>'',
   :location=>"Valverde, Islands"},
 "VGO"=>
  {:iata=>"VGO",
   :name=>"Vigo-Peinador Airport",
   :icao=>"LEVX",
   :city=>"Vigo",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Vigo, Galicia, Spain"},
 "VIT"=>
  {:iata=>"VIT",
   :name=>"Vitoria Foronda International Airport",
   :icao=>"LEVT",
   :city=>"Vitoria-Gasteiz",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Vitoria-Gasteiz, Spain"},
 "VST"=>
  {:iata=>"VST",
   :name=>"Stockholm-Västerås Airport",
   :icao=>"ESOW",
   :city=>"Stockholm",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Stockholm, Sweden"},
 "VXO"=>
  {:iata=>"VXO",
   :name=>"Växjö Airport (Kronoberg Airport)",
   :icao=>"ESMX",
   :city=>"Växjö",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Växjö, Sweden"},
 "VHM"=>
  {:iata=>"VHM",
   :name=>"Vilhelmina Airport",
   :icao=>"ESNV",
   :city=>"Vilhelmina",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Vilhelmina, Sweden"},
 "VBY"=>
  {:iata=>"VBY",
   :name=>"Visby Airport",
   :icao=>"ESSV",
   :city=>"Visby",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Visby, Sweden"},
 "VVK"=>
  {:iata=>"VVK",
   :name=>"Vastervik Airport",
   :city=>"Vastervik",
   :icao=>"ESSW",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Vastervik, Sweden"},
 "VAS"=>
  {:iata=>"VAS",
   :name=>"Sivas Airport",
   :icao=>"LTAR",
   :city=>"Sivas",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Sivas, Turkey"},
 "VAN"=>
  {:iata=>"VAN",
   :name=>"Ferit Melen Airport",
   :icao=>"LTCI",
   :city=>"Van",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Van, Turkey"},
 "VSG"=>
  {:iata=>"VSG",
   :name=>"Luhansk Airport",
   :icao=>"UKCW",
   :city=>"Luhansk (Lugansk)",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Luhansk (Lugansk), Ukraine"},
 "VIN"=>
  {:iata=>"VIN",
   :name=>"Gavryshivka International",
   :icao=>"UKWW",
   :city=>"Vinnytsia",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Vinnytsia, Ukraine"},
 "VLY"=>
  {:iata=>"VLY",
   :name=>"Royal Air Force Station Valley",
   :city=>"Valley",
   :icao=>"EGOV",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Valley, Kingdom"},
 "VNS"=>
  {:iata=>"VNS",
   :name=>"Varanasi Airport",
   :icao=>"VIBN",
   :city=>"Varanasi",
   :country=>"India",
:country_code=>"IN",
   :location=>"Varanasi, Uttar Pradesh, India"},
 "VGA"=>
  {:iata=>"VGA",
   :name=>"Vijayawada Airport",
   :icao=>"VBOZ",
   :city=>"Vijayawada",
   :country=>"India",
:country_code=>"IN",
   :location=>"Vijayawada, Andhra Pradesh, India"},
 "VTZ"=>
  {:iata=>"VTZ",
   :name=>"Visakhapatnam Airport",
   :icao=>"VEVZ",
   :city=>"Visakhapatnam",
   :country=>"India",
:country_code=>"IN",
   :location=>"Visakhapatnam, Andhra Pradesh, India"},
 "VIQ"=>
  {:iata=>"VIQ",
   :name=>"Viqueque Airport",
   :icao=>"WPVQ",
   :city=>"Viqueque",
   :country=>'East Timor', :country_code=>'',
   :location=>"Viqueque, East Timor"},
 "VTE"=>
  {:iata=>"VTE",
   :name=>"Wattay International Airport",
   :icao=>"VLVT",
   :city=>"Vientiane",
   :country=>'Laos', :country_code=>'',
   :location=>"Vientiane, Laos"},
 "VNA"=>
  {:iata=>"VNA",
   :name=>"Saravane Airport",
   :city=>"Saravane",
   :icao=>"VLSV",
   :country=>'Republic', :country_code=>'',
   :location=>"Saravane, Republic"},
 "VNG"=>
  {:iata=>"VNG",
   :name=>"Viengxay Airport",
   :city=>"Viengxay",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Viengxay, Republic"},
 "VAI"=>
  {:iata=>"VAI",
   :name=>"Vanimo Airport",
   :city=>"Vanimo",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Vanimo, Guinea"},
 "VMU"=>
  {:iata=>"VMU",
   :name=>"Baimuru Airport",
   :icao=>"",
   :city=>"Baimuru",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Baimuru, Papua New Guinea"},
 "VIV"=>
  {:iata=>"VIV",
   :name=>"Vivigani Airfield",
   :icao=>"",
   :city=>"Vivigani",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Vivigani, Goodenough Island, Papua New Guinea"},
 "VRC"=>
  {:iata=>"VRC",
   :name=>"Virac Airport",
   :icao=>"RPUV",
   :city=>"Virac",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Virac, Catanduanes, Philippines"},
 "VCA"=>
  {:iata=>"VCA",
   :name=>"Tra Noc International Airport",
   :icao=>"VVCT",
   :city=>"Can Tho",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Can Tho, Vietnam"},
 "VCS"=>
  {:iata=>"VCS",
   :name=>"Co Ong Airport",
   :icao=>"VVCS",
   :city=>"Con Son",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Con Son, Con Dao, Ba Ria - Vung Tau, Vietnam"},
 "VDH"=>
  {:iata=>"VDH",
   :name=>"Dong Hoi Airport",
   :city=>"Dong Hoi",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Dong Hoi, Nam"},
 "VKG"=>
  {:iata=>"VKG",
   :name=>"Rach Gia Airport",
   :icao=>"VVRG",
   :city=>"Rach Gia",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Rach Gia, Kien Giang, Vietnam"},
 "VCL"=>
  {:iata=>"VCL",
   :name=>"Chu Lai Airport",
   :icao=>"",
   :city=>"Chu Lai",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Chu Lai, Quang Nam, Vietnam"},
 "VII"=>
  {:iata=>"VII",
   :name=>"Vinh Airport",
   :icao=>"VVVH",
   :city=>"Vinh",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Vinh, Nghe An, Vietnam"},
 "VSO"=>
  {:iata=>"VSO",
   :name=>"Phuoc-long Airport",
   :city=>"Phuoc-long",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Phuoc-long, Nam"},
 "VTG"=>
  {:iata=>"VTG",
   :name=>"Vung Tau Airport",
   :icao=>"VVVT",
   :city=>"Vung Tau",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Vung Tau, Ba Ria - Vung Tau, Vietnam"},
 "VTA"=>
  {:iata=>"VTA",
   :name=>"Victoria Airport",
   :icao=>"",
   :city=>"Victoria",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Victoria, Honduras"},
 "VTM"=>
  {:iata=>"VTM",
   :name=>"Nevatim Air Force Base",
   :city=>"Nevatim",
   :icao=>"LLNV",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Nevatim, Israel"},
 "VDA"=>
  {:iata=>"VDA",
   :name=>"Ovda International Airport",
   :icao=>"LLOV",
   :city=>"Ovda",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Ovda, Israel"},
 "VAD"=>
  {:iata=>"VAD",
   :name=>"Moody Air Force Base",
   :icao=>"KVAD",
   :city=>"Valdosta",
   :country=>'United States', :country_code=>'US',

   :location=>"Valdosta, Georgia, United States"},
 "VAK"=>
  {:iata=>"VAK",
   :name=>"Chevak Airport",
   :icao=>"PAVA",
   :city=>"Chevak",
   :country=>'United States', :country_code=>'US',

   :location=>"Chevak, Alaska, United States"},
 "VAM"=>
  {:iata=>"VAM",
   :name=>"Maamigili Airport",
   :icao=>"VRMV",
   :city=>"Maamigili",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Maamigili, Maldives"},
 "VBG"=>
  {:iata=>"VBG",
   :name=>"Vandenberg Air Force Base",
   :icao=>"KVBG",
   :city=>"Lompoc",
   :country=>'United States', :country_code=>'US',

   :location=>"Lompoc, California, United States"},
 "VCB"=>
  {:iata=>"VCB",
   :name=>"Nut Tree Airport",
   :icao=>"KVCB",
   :city=>"Vacaville",
   :country=>'United States', :country_code=>'US',

   :location=>"Vacaville, California, United States"},
 "VCT"=>
  {:iata=>"VCT",
   :name=>"Victoria Regional Airport",
   :icao=>"KVCT",
   :city=>"Victoria",
   :country=>'United States', :country_code=>'US',

   :location=>"Victoria, Texas, United States"},
 "VCV"=>
  {:iata=>"VCV",
   :name=>"Southern California Logistics Airport",
   :icao=>"KVCV",
   :city=>"Victorville",
   :country=>'United States', :country_code=>'US',

   :location=>"Victorville, California, United States"},
 "VDI"=>
  {:iata=>"VDI",
   :name=>"Vidalia Regional Airport",
   :icao=>"KVDI",
   :city=>"Vidalia",
   :country=>'United States', :country_code=>'US',

   :location=>"Vidalia, Georgia, United States"},
 "VDZ"=>
  {:iata=>"VDZ",
   :name=>"Valdez Airport (Pioneer Field)",
   :icao=>"PAVD",
   :city=>"Valdez",
   :country=>'United States', :country_code=>'US',

   :location=>"Valdez, Alaska, United States"},
 "VEE"=>
  {:iata=>"VEE",
   :name=>"Venetie Airport",
   :icao=>"PAVE",
   :city=>"Venetie",
   :country=>'United States', :country_code=>'US',

   :location=>"Venetie, Alaska, United States"},
 "VEL"=>
  {:iata=>"VEL",
   :name=>"Vernal Airport",
   :icao=>"KVEL",
   :city=>"Vernal",
   :country=>'United States', :country_code=>'US',

   :location=>"Vernal, Utah, United States"},
 "VEX"=>
  {:iata=>"VEX",
   :name=>"Tioga Municipal Airport (FAA: D60)",
   :icao=>"",
   :city=>"Tioga",
   :country=>'United States', :country_code=>'US',

   :location=>"Tioga, North Dakota, United States"},
 "VGT"=>
  {:iata=>"VGT",
   :name=>"North Las Vegas Airport",
   :icao=>"KVGT",
   :city=>"North Las Vegas",
   :country=>'United States', :country_code=>'US',

   :location=>"North Las Vegas, Nevada, United States"},
 "VHN"=>
  {:iata=>"VHN",
   :name=>"Culberson County Airport",
   :icao=>"KVHN",
   :city=>"Van Horn",
   :country=>'United States', :country_code=>'US',

   :location=>"Van Horn, Texas, United States"},
 "VIH"=>
  {:iata=>"VIH",
   :name=>"Rolla National Airport",
   :icao=>"KVIH",
   :city=>"Rolla",
   :country=>'United States', :country_code=>'US',

   :location=>"Rolla, Missouri, United States"},
 "VIS"=>
  {:iata=>"VIS",
   :name=>"Visalia Municipal Airport",
   :icao=>"KVIS",
   :city=>"Visalia",
   :country=>'United States', :country_code=>'US',

   :location=>"Visalia, California, United States"},
 "VJI"=>
  {:iata=>"VJI",
   :name=>"Virginia Highlands Airport",
   :icao=>"KVJI",
   :city=>"Abingdon",
   :country=>'United States', :country_code=>'US',

   :location=>"Abingdon, Virginia, United States"},
 "VKS"=>
  {:iata=>"VKS",
   :name=>"Vicksburg Municipal Airport",
   :icao=>"KVKS",
   :city=>"Vicksburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Vicksburg, Mississippi, United States"},
 "VLA"=>
  {:iata=>"VLA",
   :name=>"Vandalia Municipal Airport",
   :icao=>"KVLA",
   :city=>"Vandalia",
   :country=>'United States', :country_code=>'US',

   :location=>"Vandalia, Illinois, United States"},
 "VLD"=>
  {:iata=>"VLD",
   :name=>"Valdosta Regional Airport",
   :icao=>"KVLD",
   :city=>"Valdosta",
   :country=>'United States', :country_code=>'US',

   :location=>"Valdosta, Georgia, United States"},
 "VLE"=>
  {:iata=>"VLE",
   :name=>"Valle Airport (FAA: 40G)",
   :icao=>"",
   :city=>"Grand Canyon",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Canyon, Arizona, United States"},
 "VNC"=>
  {:iata=>"VNC",
   :name=>"Venice Municipal Airport",
   :icao=>"KVNC",
   :city=>"Venice",
   :country=>'United States', :country_code=>'US',

   :location=>"Venice, Florida, United States"},
 "VNT"=>
  {:iata=>"VNT",
   :name=>"Ventspils International Airport",
   :icao=>"EVVA",
   :city=>"Ventspils",
   :country=>'Latvia', :country_code=>'LV',
   :location=>"Ventspils, Latvia"},
 "VNY"=>
  {:iata=>"VNY",
   :name=>"Van Nuys Airport",
   :icao=>"KVNY",
   :city=>"Van Nuys",
   :country=>'United States', :country_code=>'US',

   :location=>"Van Nuys, California, United States"},
 "VOD"=>
  {:iata=>"VOD",
   :name=>"Vodochody Airport",
   :icao=>"LKVO",
   :city=>"Vodochody",
   :country=>'Czech republic', :country_code=>'CZ',
   :location=>"Vodochody, Czech republic"},
 "VOK"=>
  {:iata=>"VOK",
   :name=>"Volk Field",
   :icao=>"KVOK",
   :city=>"Camp Douglas",
   :country=>'United States', :country_code=>'US',

   :location=>"Camp Douglas, Wisconsin, United States"},
 "VPS"=>
  {:iata=>"VPS",
   :name=>"Northwest Florida Regional Airport / Eglin Air Force Base",
   :icao=>"KVPS",
   :city=>"Valaparaiso (near Fort Walton Beach)",
   :country=>'United States', :country_code=>'US',

   :location=>"Valaparaiso (near Fort Walton Beach), Florida, United States"},
 "VPZ"=>
  {:iata=>"VPZ",
   :name=>"Porter County Regional Airport",
   :icao=>"KVPZ",
   :city=>"Valparaiso",
   :country=>'United States', :country_code=>'US',

   :location=>"Valparaiso, Indiana, United States"},
 "VRB"=>
  {:iata=>"VRB",
   :name=>"Vero Beach Municipal Airport",
   :icao=>"KVRB",
   :city=>"Vero Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Vero Beach, Florida, United States"},
 "VRI"=>
  {:iata=>"VRI",
   :name=>"Varandey Airport",
   :icao=>"",
   :city=>"Nenets Autonomous Okrug",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nenets Autonomous Okrug, Russia"},
 "VRS"=>
  {:iata=>"VRS",
   :name=>"Roy Otten Memorial Airfield (FAA: 3VS)",
   :icao=>"",
   :city=>"Versailles",
   :country=>'United States', :country_code=>'US',

   :location=>"Versailles, Missouri, United States"},
 "VSF"=>
  {:iata=>"VSF",
   :name=>"Hartness State Airport",
   :icao=>"KVSF",
   :city=>"Springfield",
   :country=>'United States', :country_code=>'US',

   :location=>"Springfield, Vermont, United States"},
 "VTN"=>
  {:iata=>"VTN",
   :name=>"Miller Field",
   :icao=>"KVTN",
   :city=>"Valentine",
   :country=>'United States', :country_code=>'US',

   :location=>"Valentine, Nebraska, United States"},
 "VYS"=>
  {:iata=>"VYS",
   :name=>"Illinois Valley Regional Airport (Walter A. Duncan Field)",
   :icao=>"KVYS",
   :city=>"Peru",
   :country=>'United States', :country_code=>'US',

   :location=>"Peru, Illinois, United States"}}

end
