# encoding: UTF-8
def airp_16
  {"OBY"=>
  {:iata=>"OBY",
   :name=>"Ittoqqortoormiit Heliport",
   :icao=>"BGSC",
   :city=>"Ittoqqortoormiit",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Ittoqqortoormiit, Greenland"},
 "OAX"=>
  {:iata=>"OAX",
   :name=>"Xoxocotlán International Airport",
   :icao=>"MMOX",
   :city=>"Oaxaca",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Oaxaca, Mexico"},
 "OES"=>
  {:iata=>"OES",
   :name=>"Antoine de Saint Exupéry Airport",
   :icao=>"SAVN",
   :city=>"San Antonio Oeste",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Antonio Oeste, Argentina"},
 "OYA"=>
  {:iata=>"OYA",
   :name=>"Goya Airport",
   :city=>"Goya",
   :icao=>"SATG",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Goya, Argentina"},
 "OVR"=>
  {:iata=>"OVR",
   :name=>"Olavarría Airport",
   :icao=>"SAZF",
   :city=>"Olavarría",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Olavarría, Argentina"},
 "ORA"=>
  {:iata=>"ORA",
   :name=>"Orán Airport",
   :icao=>"SASO",
   :city=>"Orán",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Orán, Salta Province, Argentina"},
 "OYO"=>
  {:iata=>"OYO",
   :name=>"Tres Arroyos Airport",
   :icao=>"SAZH",
   :city=>"Tres Arroyos",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Tres Arroyos, Buenos Aires Province, Argentina"},
 "ORU"=>
  {:iata=>"ORU",
   :name=>"Oruro Airport",
   :icao=>"",
   :city=>"Oruro",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Oruro, Bolivia"},
 "OAL"=>
  {:iata=>"OAL",
   :name=>"Cacoal Airport",
   :city=>"Cacoal",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Cacoal, Brazil"},
 "OLC"=>
  {:iata=>"OLC",
   :name=>"Sao Paulo De Olivenca Airport",
   :city=>"Sao Paulo De Olivenca",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Sao Paulo De Olivenca, Brazil"},
 "OPS"=>
  {:iata=>"OPS",
   :name=>"Aeroporto de Sinop Airport",
   :icao=>"SWSI",
   :city=>"Sinop",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Sinop, Mato Grosso, Brazil"},
 "OTT"=>
  {:iata=>"OTT",
   :name=>"Andre Maggi Airport",
   :city=>"Cotriguacu",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Cotriguacu, Brazil"},
 "OBI"=>
  {:iata=>"OBI",
   :name=>"Obidos Airport",
   :city=>"Obidos",
   :icao=>"SNTI",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Obidos, Brazil"},
 "OYK"=>
  {:iata=>"OYK",
   :name=>"Oiapoque Airport",
   :icao=>"SBOI",
   :city=>"Oiapoque",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Oiapoque, Amapa, Brazil"},
 "ORX"=>
  {:iata=>"ORX",
   :name=>"Oriximina Airport",
   :city=>"Oriximina",
   :icao=>"SNOX",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Oriximina, Brazil"},
 "OIA"=>
  {:iata=>"OIA",
   :name=>"Ourilandia Airport",
   :city=>"Ourilandia",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ourilandia, Brazil"},
 "OUS"=>
  {:iata=>"OUS",
   :name=>"Ourinhos Airport",
   :city=>"Ourinhos",
   :icao=>"SDOU",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ourinhos, Brazil"},
 "OVL"=>
  {:iata=>"OVL",
   :name=>"Olivia Regional Airport",
   :icao=>"KOVL",
   :city=>"Olivia",
   :country=>'United States', :country_code=>'US',

   :location=>"Olivia, Minnesota, United States"},
 "OCV"=>
  {:iata=>"OCV",
   :name=>"Aguasclaras Airport",
   :city=>"Ocana",
   :icao=>"SKOC",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Ocana, Colombia"},
 "ORC"=>
  {:iata=>"ORC",
   :name=>"Orange City Municipal Airport",
   :icao=>"KORC",
   :city=>"Orange City",
   :country=>'United States', :country_code=>'US',

   :location=>"Orange City, Iowa, United States"},
 "OTU"=>
  {:iata=>"OTU",
   :name=>"Otu Airport",
   :city=>"Otu",
   :icao=>"SKOT",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Otu, Colombia"},
 "OCC"=>
  {:iata=>"OCC",
   :name=>"Francisco de Orellana Airport",
   :icao=>"SECO",
   :city=>"Coca",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Coca, Ecuador"},
 "OYP"=>
  {:iata=>"OYP",
   :name=>"St. Georges de L/Oyapock Airport",
   :city=>"Saint Georges de L/Oyapock",
   :icao=>"SOOG",
   :country=>'Guiana', :country_code=>'',
   :location=>"Saint Georges de L/Oyapock, Guiana"},
 "OGL"=>
  {:iata=>"OGL",
   :name=>"Ogle Airport",
   :icao=>"SYGO",
   :city=>"Georgetown",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Georgetown, Guyana"},
 "ORJ"=>
  {:iata=>"ORJ",
   :name=>"Orinduik Airport",
   :icao=>"SYDR",
   :city=>"Orinduik",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Orinduik, Guyana"},
 "OLK"=>
  {:iata=>"OLK",
   :name=>"Fuerte Olimpo Airport",
   :icao=>"",
   :city=>"Fuerte Olimpo",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Fuerte Olimpo, Paraguay"},
 "OEM"=>
  {:iata=>"OEM",
   :name=>"Vincent Fayks Airport",
   :icao=>"SMPA",
   :city=>"Paloemeu",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Paloemeu, Suriname"},
 "ORG"=>
  {:iata=>"ORG",
   :name=>"Zorg en Hoop Airport",
   :icao=>"SMZO",
   :city=>"Paramaribo",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Paramaribo, Suriname"},
 "OFU"=>
  {:iata=>"OFU",
   :name=>"Ofu Airport",
   :icao=>"",
   :city=>"Ofu",
   :country=>'American Samoa', :country_code=>'AS',
   :location=>"Ofu, American Samoa"},
 "OCM"=>
  {:iata=>"OCM",
   :name=>"Boolgeeda Airport",
   :city=>"Boolgeeda",
   :icao=>"YBGD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Boolgeeda, Australia"},
 "OOL"=>
  {:iata=>"OOL",
   :name=>"Gold Coast Airport",
   :icao=>"YBCG",
   :city=>"Coolangatta",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Coolangatta, Queensland, Australia"},
 "OOM"=>
  {:iata=>"OOM",
   :name=>"Cooma Airport",
   :city=>"Cooma",
   :icao=>"YCOM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Cooma, Australia"},
 "ONG"=>
  {:iata=>"ONG",
   :name=>"Mornington Airport",
   :city=>"Mornington",
   :icao=>"YMTI",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mornington, Australia"},
 "OLP"=>
  {:iata=>"OLP",
   :name=>"Olympic Dam Airport",
   :city=>"Olympic Dam",
   :icao=>"YOLD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Olympic Dam, Australia"},
 "ONS"=>
  {:iata=>"ONS",
   :name=>"Onslow Airport",
   :city=>"Onslow",
   :icao=>"YOLW",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Onslow, Australia"},
 "OAG"=>
  {:iata=>"OAG",
   :name=>"Springhill Airport",
   :city=>"Orange",
   :icao=>"YORG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Orange, Australia"},
 "ODL"=>
  {:iata=>"ODL",
   :name=>"Cordillo Downs Airport",
   :city=>"Cordillo Downs",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Cordillo Downs, Australia"},
 "ONR"=>
  {:iata=>"ONR",
   :name=>"Monkira Airport",
   :city=>"Monkira",
   :icao=>"YMNK",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Monkira, Australia"},
 "OOR"=>
  {:iata=>"OOR",
   :name=>"Mooraberree Airport",
   :city=>"Mooraberree",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mooraberree, Australia"},
 "OXY"=>
  {:iata=>"OXY",
   :name=>"Morney Airport",
   :city=>"Morney",
   :icao=>"YMNY",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Morney, Australia"},
 "OKY"=>
  {:iata=>"OKY",
   :name=>"Oakey Airport",
   :city=>"Oakey",
   :icao=>"YBOK",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Oakey, Australia"},
 "OBA"=>
  {:iata=>"OBA",
   :name=>"Oban Airport",
   :city=>"Oban",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Oban, Australia"},
 "OPI"=>
  {:iata=>"OPI",
   :name=>"Oenpelli Airport",
   :city=>"Oenpelli",
   :icao=>"YOEN",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Oenpelli, Australia"},
 "ODD"=>
  {:iata=>"ODD",
   :name=>"Oodnadatta Airport",
   :city=>"Oodnadatta",
   :icao=>"YOOD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Oodnadatta, Australia"},
 "OKB"=>
  {:iata=>"OKB",
   :name=>"Orchid Beach",
   :icao=>"",
   :city=>"Fraser Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Fraser Island, Queensland, Australia"},
 "ODR"=>
  {:iata=>"ODR",
   :name=>"Ord River Airport",
   :city=>"Ord River",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ord River, Australia"},
 "OXO"=>
  {:iata=>"OXO",
   :name=>"Orientos Airport",
   :city=>"Orientos",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Orientos, Australia"},
 "ORS"=>
  {:iata=>"ORS",
   :name=>"Waterport Airport",
   :icao=>"",
   :city=>"Orpheus",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Orpheus, Queensland, Australia"},
 "OYN"=>
  {:iata=>"OYN",
   :name=>"Ouyen Airport",
   :city=>"Ouyen",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ouyen, Australia"},
 "OKR"=>
  {:iata=>"OKR",
   :name=>"Yorke Island Airport",
   :city=>"Yorke Island",
   :icao=>"YYKI",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Yorke Island, Australia"},
 "ORR"=>
  {:iata=>"ORR",
   :name=>"Yorketown Airport",
   :icao=>"",
   :city=>"Yorketown",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Yorketown, South Australia, Australia"},
 "ONU"=>
  {:iata=>"ONU",
   :name=>"Ono I Lau Airport",
   :city=>"Ono I Lau",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Ono I Lau, Fiji"},
 "OOT"=>
  {:iata=>"OOT",
   :name=>"Onotoa Airport",
   :city=>"Onotoa",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Onotoa, Kiribati"},
 "OAM"=>
  {:iata=>"OAM",
   :name=>"Oamaru Airport",
   :icao=>"NZOU",
   :city=>"Oamaru",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Oamaru, North Otago, New Zealand"},
 "OHA"=>
  {:iata=>"OHA",
   :name=>"Royal Air Force Base",
   :city=>"Ohakea",
   :icao=>"NZOH",
   :country=>'Zealand', :country_code=>'',
   :location=>"Ohakea, Zealand"},
 "ONE"=>
  {:iata=>"ONE",
   :name=>"Onepusu Airport",
   :city=>"Onepusu",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Onepusu, Islands"},
 "OTV"=>
  {:iata=>"OTV",
   :name=>"Ontong Java Airport",
   :city=>"Ontong Java",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Ontong Java, Islands"},
 "OLJ"=>
  {:iata=>"OLJ",
   :name=>"West Cost Santo Airport",
   :city=>"Olpoi",
   :icao=>"",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Olpoi, Vanuatu"},
 "OCJ"=>
  {:iata=>"OCJ",
   :name=>"Boscobel Aerodrome",
   :icao=>"MKBS",
   :city=>"Ocho Rios",
   :country=>'Jamaica', :country_code=>'JM',
   :location=>"Ocho Rios, Jamaica"},
 "ORN"=>
  {:iata=>"ORN",
   :name=>"Oran Es Sénia Airport",
   :icao=>"DAOO",
   :city=>"Oran",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Oran, Algeria"},
 "OGX"=>
  {:iata=>"OGX",
   :name=>"Ain Beida Airport",
   :city=>"Ouargla",
   :icao=>"DAUU",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Ouargla, Algeria"},
 "ORP"=>
  {:iata=>"ORP",
   :name=>"Orapa Airport",
   :city=>"Orapa",
   :icao=>"FBOR",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Orapa, Botswana"},
 "OUA"=>
  {:iata=>"OUA",
   :name=>"Ouagadougou Airport",
   :icao=>"DFFD",
   :city=>"Ouagadougou",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Ouagadougou, Burkina Faso"},
 "OUG"=>
  {:iata=>"OUG",
   :name=>"Ouahigouya Airport",
   :icao=>"DFCC",
   :city=>"Ouahigouya",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Ouahigouya, Burkina Faso"},
 "OUR"=>
  {:iata=>"OUR",
   :name=>"Batouri Airport",
   :icao=>"FKKI",
   :city=>"Batouri",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Batouri, Cameroon"},
 "ODA"=>
  {:iata=>"ODA",
   :name=>"Ouadda Airport",
   :city=>"Ouadda",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Ouadda, Republic"},
 "ODJ"=>
  {:iata=>"ODJ",
   :name=>"Ouanda Djalle Airport",
   :city=>"Ouanda Djalle",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Ouanda Djalle, Republic"},
 "OTC"=>
  {:iata=>"OTC",
   :name=>"Bol Airport",
   :icao=>"FTTL",
   :city=>"Bol",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Bol, Chad"},
 "OGR"=>
  {:iata=>"OGR",
   :name=>"Bongor Airport",
   :icao=>"FTTB",
   :city=>"Bongor",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Bongor, Chad"},
 "OUT"=>
  {:iata=>"OUT",
   :name=>"Bousso Airport",
   :icao=>"FTTS",
   :city=>"Bousso",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Bousso, Chad"},
 "OUM"=>
  {:iata=>"OUM",
   :name=>"Oum Hadjer Airport",
   :icao=>"",
   :city=>"Oum Hadjer",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Oum Hadjer, Chad"},
 "OLL"=>
  {:iata=>"OLL",
   :name=>"Oyo Ollombo Airport",
   :icao=>"",
   :city=>"Oyo",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Oyo, Republic of the Congo, Republic of the Congo"},
 "OKG"=>
  {:iata=>"OKG",
   :name=>"Okoyo Airport",
   :city=>"Okoyo",
   :icao=>"",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Okoyo, Congo"},
 "OUE"=>
  {:iata=>"OUE",
   :name=>"Ouesso Airport",
   :city=>"Ouesso",
   :icao=>"FCOU",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Ouesso, Congo"},
 "OFI"=>
  {:iata=>"OFI",
   :name=>"Ouango Fitini Airport",
   :city=>"Ouango Fitini",
   :icao=>"DIOF",
   :country=>"d'Ivoire", :country_code=>'CI',
   :location=>"Ouango Fitini, d'Ivoire"},
 "OGO"=>
  {:iata=>"OGO",
   :name=>"Abengourou Airport",
   :city=>"Abengourou",
   :icao=>"DIAU",
   :country=>"d'Ivoire", :country_code=>'CI',
   :location=>"Abengourou, d'Ivoire"},
 "OBC"=>
  {:iata=>"OBC",
   :name=>"Obock Airport",
   :icao=>"HDOB",
   :city=>"Obock",
   :country=>'Djibouti', :country_code=>'DJ',
   :location=>"Obock, Djibouti"},
 "OTA"=>
  {:iata=>"OTA",
   :name=>"Mota Airport",
   :city=>"Mota",
   :icao=>"",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Mota, Ethiopia"},
 "OYE"=>
  {:iata=>"OYE",
   :name=>"Oyem Airport",
   :city=>"Oyem",
   :icao=>"FOGO",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Oyem, Gabon"},
 "OKN"=>
  {:iata=>"OKN",
   :name=>"Okondja Airport",
   :city=>"Okondja",
   :icao=>"FOGQ",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Okondja, Gabon"},
 "OMB"=>
  {:iata=>"OMB",
   :name=>"Omboue Airport",
   :city=>"Omboue",
   :icao=>"FOOH",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Omboue, Gabon"},
 "OUU"=>
  {:iata=>"OUU",
   :name=>"Ouanga Airport",
   :city=>"Ouanga",
   :icao=>"",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Ouanga, Gabon"},
 "OWE"=>
  {:iata=>"OWE",
   :name=>"Owendo Airport",
   :city=>"Owendo",
   :icao=>"",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Owendo, Gabon"},
 "OXB"=>
  {:iata=>"OXB",
   :name=>"Osvaldo Vieiro International Airport",
   :icao=>"GGOV",
   :city=>"Bissau",
   :country=>'Guinea-Bissau', :country_code=>'GW',
   :location=>"Bissau, Guinea-Bissau"},
 "OYL"=>
  {:iata=>"OYL",
   :name=>"Moyale Airport",
   :city=>"Moyale",
   :icao=>"HKMY",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Moyale, Kenya"},
 "OVA"=>
  {:iata=>"OVA",
   :name=>"Bekily Airport",
   :city=>"Bekily",
   :icao=>"FMSL",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Bekily, Madagascar"},
 "OUZ"=>
  {:iata=>"OUZ",
   :name=>"Tazadit Airport",
   :icao=>"GQPZ",
   :city=>"Zouerate",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Zouerate, Mauritania"},
 "OTL"=>
  {:iata=>"OTL",
   :name=>"Boutilimit Airport",
   :icao=>"GQNB",
   :city=>"Boutilimit",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Boutilimit, Mauritania"},
 "OZZ"=>
  {:iata=>"OZZ",
   :name=>"Ouarzazate Airport",
   :icao=>"GMMZ",
   :city=>"Ouarzazate",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Ouarzazate, Morocco"},
 "OUD"=>
  {:iata=>"OUD",
   :name=>"Angads Airport",
   :icao=>"GMFO",
   :city=>"Oujda",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Oujda, Morocco"},
 "OZG"=>
  {:iata=>"OZG",
   :name=>"Zagora Airport",
   :city=>"Zagora",
   :icao=>"GMAZ",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Zagora, Morocco"},
 "OND"=>
  {:iata=>"OND",
   :name=>"Ondangwa Airport",
   :city=>"Ondangwa",
   :icao=>"FAOA",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Ondangwa, Namibia"},
 "OMD"=>
  {:iata=>"OMD",
   :name=>"Oranjemund Airport",
   :city=>"Oranjemund",
   :icao=>"FYOG",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Oranjemund, Namibia"},
 "OKU"=>
  {:iata=>"OKU",
   :name=>"Mokuti Lodge Airport",
   :city=>"Mokuti Lodge",
   :icao=>"FYMO",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Mokuti Lodge, Namibia"},
 "OKF"=>
  {:iata=>"OKF",
   :name=>"Okaukuejo Airport",
   :city=>"Okaukuejo",
   :icao=>"FYOO",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Okaukuejo, Namibia"},
 "OMG"=>
  {:iata=>"OMG",
   :name=>"Omega Airport",
   :city=>"Omega",
   :icao=>"",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Omega, Namibia"},
 "OPW"=>
  {:iata=>"OPW",
   :name=>"Opuwa Airport",
   :city=>"Opuwa",
   :icao=>"",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Opuwa, Namibia"},
 "OHI"=>
  {:iata=>"OHI",
   :name=>"Oshakati Airport",
   :city=>"Oshakati",
   :icao=>"",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Oshakati, Namibia"},
 "OTJ"=>
  {:iata=>"OTJ",
   :name=>"Otjiwarongo Airport",
   :city=>"Otjiwarongo",
   :icao=>"FYOW",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Otjiwarongo, Namibia"},
 "OUH"=>
  {:iata=>"OUH",
   :name=>"Oudtshoorn Airport",
   :city=>"Oudtshoorn",
   :icao=>"FAOH",
   :country=>'Africa', :country_code=>'',
   :location=>"Oudtshoorn, Africa"},
 "OVG"=>
  {:iata=>"OVG",
   :name=>"Overberg (FAOB)",
   :city=>"Overberg",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Overberg, Africa"},
 "OYG"=>
  {:iata=>"OYG",
   :name=>"Moyo Airport",
   :city=>"Moyo",
   :icao=>"",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Moyo, Uganda"},
 "OST"=>
  {:iata=>"OST",
   :name=>"Ostend-Bruges International Airport",
   :icao=>"EBOS",
   :city=>"Flanders",
   :country=>'Belgium', :country_code=>'BE',
   :location=>"Flanders, Belgium"},
 "OBL"=>
  {:iata=>"OBL",
   :name=>"Zoersel-Oostmalle Airfield",
   :icao=>"EBZR",
   :city=>"Zoersel / Oostmalle",
   :country=>'Belgium', :country_code=>'BE',
   :location=>"Zoersel / Oostmalle, Belgium"},
 "OMO"=>
  {:iata=>"OMO",
   :name=>"Mostar International Airport",
   :icao=>"LQMO",
   :city=>"Mostar",
   :country=>'Bosnia and Herzegovina', :country_code=>'BO',
   :location=>"Mostar, Bosnia and Herzegovina"},
 "OSI"=>
  {:iata=>"OSI",
   :name=>"Osijek Airport",
   :icao=>"LDOS",
   :city=>"Osijek",
   :country=>'Croatia', :country_code=>'HR',
   :location=>"Osijek, Croatia"},
 "OSR"=>
  {:iata=>"OSR",
   :name=>"Ostrava-Mosnov International Airport",
   :icao=>"LKMT",
   :city=>"Ostrava",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Ostrava, Czech Republic"},
 "OLO"=>
  {:iata=>"OLO",
   :name=>"Olomouc Airport",
   :icao=>"LKOL",
   :city=>"Olomouc",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Olomouc, Czech Republic"},
 "ODE"=>
  {:iata=>"ODE",
   :name=>"Odense Airport",
   :icao=>"EKOD",
   :city=>"Odense",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Odense, Denmark"},
 "OUL"=>
  {:iata=>"OUL",
   :name=>"Oulu Airport",
   :icao=>"EFOU",
   :city=>"Oulu",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Oulu, Finland"},
 "ORY"=>
  {:iata=>"ORY",
   :name=>"Orly International Airport",
   :icao=>"LFPO",
   :city=>"Paris-Orly",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris-Orly, Paris, France"},
 "OBS"=>
  {:iata=>"OBS",
   :name=>"Vals-Lanas Airport",
   :city=>"Aubenas",
   :icao=>"LFHO",
   :country=>'France', :country_code=>'FR',
   :location=>"Aubenas, France"},
 "ORE"=>
  {:iata=>"ORE",
   :name=>"Orléans - Bricy Air Base",
   :icao=>"LFOJ",
   :city=>"Orléans",
   :country=>'France', :country_code=>'FR',
   :location=>"Orléans, France"},
 "OBF"=>
  {:iata=>"OBF",
   :name=>"Oberpfaffenhofen Airport",
   :icao=>"EDMO",
   :city=>"Oberpfaffenhofen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Oberpfaffenhofen, Germany"},
 "OHR"=>
  {:iata=>"OHR",
   :name=>"Wyk Airport",
   :city=>"Wyk",
   :icao=>"EDXY",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Wyk, Germany"},
 "OPA"=>
  {:iata=>"OPA",
   :name=>"Kopasker Airport",
   :city=>"Kopasker",
   :icao=>"",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Kopasker, Iceland"},
 "OFJ"=>
  {:iata=>"OFJ",
   :name=>"Olafsfjordur Airport",
   :city=>"Olafsfjordur",
   :icao=>"",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Olafsfjordur, Iceland"},
 "OLI"=>
  {:iata=>"OLI",
   :name=>"Rif Airport",
   :city=>"Olafsvik",
   :icao=>"",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Olafsvik, Iceland"},
 "ORK"=>
  {:iata=>"ORK",
   :name=>"Cork Airport",
   :icao=>"EICK",
   :city=>"Cork",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Cork, Ireland"},
 "OLB"=>
  {:iata=>"OLB",
   :name=>"Olbia – Costa Smeralda Airport",
   :icao=>"LIEO",
   :city=>"Olbia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Olbia, Italy"},
 "OHD"=>
  {:iata=>"OHD",
   :name=>"Ohrid Airport",
   :icao=>"LWOH",
   :city=>"Ohrid",
   :country=>'Republic of Macedonia', :country_code=>'MK',
   :location=>"Ohrid, Republic of Macedonia"},
 "OSL"=>
  {:iata=>"OSL",
   :name=>"Oslo Airport, Gardermoen (succeeding Oslo Airport, Fornebu)",
   :icao=>"ENGM",
   :city=>"Ullensaker (near Oslo)",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Ullensaker (near Oslo), Norway"},
 "OSY"=>
  {:iata=>"OSY",
   :name=>"Namsos Airport, Høknesøra",
   :icao=>"ENNM",
   :city=>"Namsos",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Namsos, Norway"},
 "OLA"=>
  {:iata=>"OLA",
   :name=>"Orland Airport",
   :city=>"Orland",
   :icao=>"ENOL",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Orland, Norway"},
 "OSZ"=>
  {:iata=>"OSZ",
   :name=>"Koszalin Airport",
   :city=>"Koszalin",
   :icao=>"",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Koszalin, Poland"},
 "OSP"=>
  {:iata=>"OSP",
   :name=>"Redzikowo Airport",
   :city=>"Slupsk",
   :icao=>"EPSK",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Slupsk, Poland"},
 "OPO"=>
  {:iata=>"OPO",
   :name=>"Francisco Sá Carneiro Airport",
   :icao=>"LPPR",
   :city=>"Porto",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Porto, Portugal"},
 "OTP"=>
  {:iata=>"OTP",
   :name=>"Henri Coandă International Airport",
   :icao=>"LROP",
   :city=>"Otopeni (near Bucharest)",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Otopeni (near Bucharest), Romania"},
 "OMR"=>
  {:iata=>"OMR",
   :name=>"Oradea International Airport",
   :icao=>"LROD",
   :city=>"Oradea",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Oradea, Romania"},
 "ODO"=>
  {:iata=>"ODO",
   :name=>"Bodaybo Airport",
   :city=>"Bodaybo",
   :icao=>"",
   :country=>'Federation', :country_code=>'',
   :location=>"Bodaybo, Federation"},
 "OSF"=>
  {:iata=>"OSF",
   :name=>"Ostafyevo International Airport",
   :icao=>"UUMO",
   :city=>"Podolsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Podolsk, Russia"},
 "OVB"=>
  {:iata=>"OVB",
   :name=>"Novosibirsk Tolmachevo Airport",
   :icao=>"UNNT",
   :city=>"Novosibirsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Novosibirsk, Russia"},
 "OHH"=>
  {:iata=>"OHH",
   :name=>"Okha Airport",
   :icao=>"UHSH",
   :city=>"Okha",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Okha, Russia"},
 "ONK"=>
  {:iata=>"ONK",
   :name=>"Olenyok Airport",
   :icao=>"UERO",
   :city=>"Olenyok",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Olenyok, Sakha Republic, Russia"},
 "OLZ"=>
  {:iata=>"OLZ",
   :name=>"Olyokminsk Airport",
   :icao=>"",
   :city=>"Olyokminsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Olyokminsk, Sakha Republic, Russia"},
 "OMS"=>
  {:iata=>"OMS",
   :name=>"Omsk Airport",
   :icao=>"UNOO",
   :city=>"Omsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Omsk, Russia"},
 "OSW"=>
  {:iata=>"OSW",
   :name=>"Orsk Airport",
   :icao=>"UWOR",
   :city=>"Orsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Orsk, Orenburg Oblast, Russia"},
 "OVS"=>
  {:iata=>"OVS",
   :name=>"Sovetsky Airport",
   :icao=>"USHS",
   :city=>"Sovetsky",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Sovetsky, Khanty–Mansi Autonomous Okrug, Russia"},
 "OGZ"=>
  {:iata=>"OGZ",
   :name=>"Beslan Airport",
   :icao=>"URMO",
   :city=>"Beslan / Vladikavkaz",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Beslan / Vladikavkaz, North Ossetia–Alania, Russia"},
 "OHO"=>
  {:iata=>"OHO",
   :name=>"Okhotsk Airport",
   :icao=>"",
   :city=>"Okhotsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Okhotsk, Khabarovsk Krai, Russia"},
 "OKT"=>
  {:iata=>"OKT",
   :name=>"Oktyabrsky Airport",
   :icao=>"UWUK",
   :city=>"Oktyabrsky",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Oktyabrsky, Bashkortostan, Russia"},
 "OEL"=>
  {:iata=>"OEL",
   :name=>"Oryol Yuzhny Airport",
   :icao=>"",
   :city=>"Oryol",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Oryol, Russia"},
 "OVD"=>
  {:iata=>"OVD",
   :name=>"Asturias Airport (Oviedo Airport)",
   :icao=>"LEAS",
   :city=>"Oviedo",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Oviedo, Asturias, Spain"},
 "OZP"=>
  {:iata=>"OZP",
   :name=>"Moron Air Base",
   :city=>"Moron",
   :icao=>"LEMO",
   :country=>'Islands', :country_code=>'',
   :location=>"Moron, Islands"},
 "OZI"=>
  {:iata=>"OZI",
   :name=>"Bobadilla Airport",
   :city=>"Bobadilla",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Bobadilla, Islands"},
 "ODB"=>
  {:iata=>"ODB",
   :name=>"Córdoba Airport",
   :icao=>"LEBA",
   :city=>"Córdoba",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Córdoba, Spain"},
 "OZU"=>
  {:iata=>"OZU",
   :name=>"Montilla Airport",
   :city=>"Montilla",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Montilla, Islands"},
 "ORB"=>
  {:iata=>"ORB",
   :name=>"Örebro Airport",
   :icao=>"ESOE",
   :city=>"Örebro",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Örebro, Sweden"},
 "OER"=>
  {:iata=>"OER",
   :name=>"Örnsköldsvik Airport",
   :icao=>"ESNO",
   :city=>"Örnsköldsvik",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Örnsköldsvik, Sweden"},
 "OSK"=>
  {:iata=>"OSK",
   :name=>"Oskarshamn Airport",
   :icao=>"ESMO",
   :city=>"Oskarshamn",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Oskarshamn, Sweden"},
 "OSD"=>
  {:iata=>"OSD",
   :name=>"Åre Östersund Airport",
   :icao=>"ESNZ",
   :city=>"Östersund",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Östersund, Sweden"},
 "ONQ"=>
  {:iata=>"ONQ",
   :name=>"Zonguldak Airport",
   :icao=>"LTAS",
   :city=>"Zonguldak",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Zonguldak, Turkey"},
 "ODS"=>
  {:iata=>"ODS",
   :name=>"Odessa International Airport",
   :icao=>"UKOO",
   :city=>"Odessa",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Odessa, Ukraine"},
 "OZH"=>
  {:iata=>"OZH",
   :name=>"Zaporizhia International Airport",
   :icao=>"UKDE",
   :city=>"Zaporizhia",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Zaporizhia, Ukraine"},
 "OXF"=>
  {:iata=>"OXF",
   :name=>"London Oxford Airport",
   :icao=>"EGTK",
   :city=>"Oxford",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Oxford, England, United Kingdom"},
 "ORM"=>
  {:iata=>"ORM",
   :name=>"Sywell Aerodrome",
   :icao=>"EGBK",
   :city=>"Northampton / Peterborough",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Northampton / Peterborough, United Kingdom"},
 "OKH"=>
  {:iata=>"OKH",
   :name=>"RAF Cottesmore",
   :icao=>"EGXJ",
   :city=>"Oakham",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Oakham, England, United Kingdom"},
 "OBN"=>
  {:iata=>"OBN",
   :name=>"Connel Airport",
   :city=>"Oban",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Oban, Kingdom"},
 "OHP"=>
  {:iata=>"OHP",
   :name=>"Oban Heliport",
   :city=>"Oban",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Oban, Kingdom"},
 "ODH"=>
  {:iata=>"ODH",
   :name=>"RAF Odiham",
   :icao=>"EGVO",
   :city=>"Odiham",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Odiham, United Kingdom"},
 "OUK"=>
  {:iata=>"OUK",
   :name=>"Outer Skerries Airport",
   :city=>"Outer Skerries",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Outer Skerries, Kingdom"},
 "OAI"=>
  {:iata=>"OAI",
   :name=>"Bagram Airfield",
   :icao=>"OAIX",
   :city=>"Bagram",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Bagram, Afghanistan"},
 "OAZ"=>
  {:iata=>"OAZ",
   :name=>"Camp Bastion",
   :city=>"Lashkar Gah",
   :icao=>"OAZI",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Lashkar Gah, Afghanistan"},
 "OMY"=>
  {:iata=>"OMY",
   :name=>"Oddor Meanche Airport",
   :city=>"Oddor Meanche",
   :icao=>"",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Oddor Meanche, Cambodia"},
 "OHE"=>
  {:iata=>"OHE",
   :name=>"Mohe Gulian Airport",
   :icao=>"ZYMH",
   :city=>"Mohe",
   :country=>'China', :country_code=>'CN',
   :location=>"Mohe, Heilongjiang, China"},
 "OMN"=>
  {:iata=>"OMN",
   :name=>"Osmanabad Airport",
   :icao=>"",
   :city=>"Osmanabad",
   :country=>"India",
:country_code=>"IN",
   :location=>"Osmanabad, India"},
 "OKL"=>
  {:iata=>"OKL",
   :name=>"Gunung Bintang Airport",
   :city=>"Oksibil",
   :icao=>"WAJO",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Oksibil, Indonesia"},
 "ONI"=>
  {:iata=>"ONI",
   :name=>"Moanamani Airport",
   :city=>"Moanamani",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Moanamani, Indonesia"},
 "OTI"=>
  {:iata=>"OTI",
   :name=>"Morotai Island Airport",
   :city=>"Morotai Island",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Morotai Island, Indonesia"},
 "OBD"=>
  {:iata=>"OBD",
   :name=>"Obano Airport",
   :icao=>"LEBA",
   :city=>"Obano",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Obano, Indonesia"},
 "OEC"=>
  {:iata=>"OEC",
   :name=>"Ocussi Airport",
   :icao=>"",
   :city=>"Ocussi",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ocussi, Indonesia"},
 "OKQ"=>
  {:iata=>"OKQ",
   :name=>"Okaba Airport",
   :city=>"Okaba",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Okaba, Indonesia"},
 "OMH"=>
  {:iata=>"OMH",
   :name=>"Orange County Airport",
   :icao=>"OITR",
   :city=>"Orange",
   :country=>'United States', :country_code=>'US',

   :location=>"Orange, Virginia, United States"},
 "OMI"=>
  {:iata=>"OMI",
   :name=>"Omidiyeh Air Base",
   :icao=>"OIAJ",
   :city=>"Omidiyeh",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Omidiyeh, Iran"},
 "OKA"=>
  {:iata=>"OKA",
   :name=>"Naha Airport",
   :icao=>"ROAH",
   :city=>"Okinawa",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Okinawa, Japan"},
 "OBO"=>
  {:iata=>"OBO",
   :name=>"Tokachi-Obihiro Airport",
   :icao=>"RJCB",
   :city=>"Obihiro",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Obihiro, Tokachi Subprefecture, Hokkaido, Japan"},
 "ONJ"=>
  {:iata=>"ONJ",
   :name=>"Odate-Noshiro Airport",
   :icao=>"RJSR",
   :city=>"Kitaakita",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kitaakita, Akita, Japan"},
 "OIT"=>
  {:iata=>"OIT",
   :name=>"Oita Airport",
   :icao=>"RJFO",
   :city=>"Oita",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Oita, Japan"},
 "OKJ"=>
  {:iata=>"OKJ",
   :name=>"Okayama Airport",
   :icao=>"RJOB",
   :city=>"Okayama",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Okayama, Japan"},
 "OKI"=>
  {:iata=>"OKI",
   :name=>"Oki Island Airport",
   :city=>"Oki Island",
   :icao=>"RJNO",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Oki Island, Japan"},
 "OIM"=>
  {:iata=>"OIM",
   :name=>"Oshima Airport",
   :city=>"Oshima",
   :icao=>"RJTO",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Oshima, Japan"},
 "OKD"=>
  {:iata=>"OKD",
   :name=>"Okadama Airport",
   :city=>"Sapporo",
   :icao=>"RJCO",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Sapporo, Japan"},
 "OKO"=>
  {:iata=>"OKO",
   :name=>"Yokota Air Force Base",
   :city=>"Tokyo",
   :icao=>"RJTY",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tokyo, Japan"},
 "OKE"=>
  {:iata=>"OKE",
   :name=>"Okino Erabu Airport",
   :city=>"Wadomari",
   :icao=>"RJKB",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Wadomari, Japan"},
 "OGN"=>
  {:iata=>"OGN",
   :name=>"Yonaguni Airport",
   :icao=>"ROYN",
   :city=>"Yonaguni",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Yonaguni, Okinawa, Japan"},
 "OIR"=>
  {:iata=>"OIR",
   :name=>"Okushiri Airport",
   :icao=>"RJEO",
   :city=>"Okushiri",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Okushiri, Okushiri Island, Hokkaido, Japan"},
 "OMJ"=>
  {:iata=>"OMJ",
   :name=>"Omura Airport",
   :city=>"Omura",
   :icao=>"",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Omura, Japan"},
 "OSS"=>
  {:iata=>"OSS",
   :name=>"Osh Airport",
   :icao=>"UAFO",
   :city=>"Osh",
   :country=>'Kyrgyzstan', :country_code=>'KG',
   :location=>"Osh, Kyrgyzstan"},
 "ODY"=>
  {:iata=>"ODY",
   :name=>"Oudomsay Airport",
   :icao=>"VLOS",
   :city=>"Muang Xay",
   :country=>'Laos', :country_code=>'',
   :location=>"Muang Xay, Laos"},
 "OUI"=>
  {:iata=>"OUI",
   :name=>"Ban Houel Airport",
   :city=>"Ban Houel",
   :icao=>"VLHS",
   :country=>'Republic', :country_code=>'',
   :location=>"Ban Houel, Republic"},
 "ODN"=>
  {:iata=>"ODN",
   :name=>"Long Seridan Airport",
   :city=>"Long Seridan",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Seridan, Malaysia"},
 "OHT"=>
  {:iata=>"OHT",
   :name=>"Kohat Airport",
   :icao=>"OPKT",
   :city=>"Kohat",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Kohat, Pakistan"},
 "ORW"=>
  {:iata=>"ORW",
   :name=>"Ormara Airport",
   :city=>"Ormara",
   :icao=>"OPOR",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Ormara, Pakistan"},
 "OPU"=>
  {:iata=>"OPU",
   :name=>"Balimo Airport",
   :city=>"Balimo",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Balimo, Guinea"},
 "OBX"=>
  {:iata=>"OBX",
   :name=>"Obo Airport (Papua New Guinea)",
   :icao=>"",
   :city=>"Obo",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Obo, Papua New Guinea, Papua New Guinea"},
 "OBM"=>
  {:iata=>"OBM",
   :name=>"Morobe Airport",
   :city=>"Morobe",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Morobe, Guinea"},
 "OGE"=>
  {:iata=>"OGE",
   :name=>"Ogeranang Airport",
   :city=>"Ogeranang",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Ogeranang, Guinea"},
 "OKV"=>
  {:iata=>"OKV",
   :name=>"Okao Airport",
   :city=>"Okao",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Okao, Guinea"},
 "OKP"=>
  {:iata=>"OKP",
   :name=>"Oksapmin Airport",
   :city=>"Oksapmin",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Oksapmin, Guinea"},
 "OLQ"=>
  {:iata=>"OLQ",
   :name=>"Olsobip Airport",
   :city=>"Olsobip",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Olsobip, Guinea"},
 "OML"=>
  {:iata=>"OML",
   :name=>"Omkalai Airport",
   :city=>"Omkalai",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Omkalai, Guinea"},
 "OSE"=>
  {:iata=>"OSE",
   :name=>"Omora Airport",
   :city=>"Omora",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Omora, Guinea"},
 "ONB"=>
  {:iata=>"ONB",
   :name=>"Ononge Airport",
   :city=>"Ononge",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Ononge, Guinea"},
 "OPB"=>
  {:iata=>"OPB",
   :name=>"Open Bay Airport",
   :city=>"Open Bay",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Open Bay, Guinea"},
 "OTY"=>
  {:iata=>"OTY",
   :name=>"Oria Airport",
   :city=>"Oria",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Oria, Guinea"},
 "OSG"=>
  {:iata=>"OSG",
   :name=>"Ossima Airport",
   :city=>"Ossima",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Ossima, Guinea"},
 "OMC"=>
  {:iata=>"OMC",
   :name=>"Ormoc Airport",
   :icao=>"RPVO",
   :city=>"Ormoc City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Ormoc City, Philippines"},
 "OZC"=>
  {:iata=>"OZC",
   :name=>"Labo Airport",
   :icao=>"RPMO",
   :city=>"Ozamiz City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Ozamiz City, Misamis Occidental, Philippines"},
 "OSN"=>
  {:iata=>"OSN",
   :name=>"Osan Air Base",
   :city=>"Osan",
   :icao=>"RKSO",
   :country=>'Korea', :country_code=>'',
   :location=>"Osan, Korea"},
 "ORZ"=>
  {:iata=>"ORZ",
   :name=>"Orange Walk Airport",
   :city=>"Orange Walk",
   :icao=>"",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Orange Walk, Belize"},
 "OTR"=>
  {:iata=>"OTR",
   :name=>"Coto 47 Airport",
   :icao=>"MRCC",
   :city=>"Coto 47",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Coto 47, Costa Rica"},
 "OAN"=>
  {:iata=>"OAN",
   :name=>"Olanchito Airport",
   :city=>"Olanchito",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Olanchito, Honduras"},
 "ORO"=>
  {:iata=>"ORO",
   :name=>"Yoro Airport",
   :city=>"Yoro",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Yoro, Honduras"},
 "OTD"=>
  {:iata=>"OTD",
   :name=>"Contadora Airport",
   :icao=>"",
   :city=>"Contadora Island",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Contadora Island, Panama"},
 "OGM"=>
  {:iata=>"OGM",
   :name=>"Ogobsucum Airport",
   :city=>"Ustupu Island",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Ustupu Island, Panama"},
 "ONX"=>
  {:iata=>"ONX",
   :name=>"Enrique Adolfo Jiménez Airport",
   :icao=>"MPEJ",
   :city=>"Colón",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Colón, Panama"},
 "OSM"=>
  {:iata=>"OSM",
   :name=>"Mosul Airport",
   :city=>"Mosul",
   :icao=>"",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Mosul, Iraq"},
 "OMF"=>
  {:iata=>"OMF",
   :name=>"King Hussein Air Base",
   :icao=>"OJMF",
   :city=>"Mafraq",
   :country=>'Jordan', :country_code=>'JO',
   :location=>"Mafraq, Mafraq Governorate, Jordan"},
 "OMM"=>
  {:iata=>"OMM",
   :name=>"Marmul Airport",
   :city=>"Marmul",
   :icao=>"OONR",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Marmul, Oman"},
 "OAJ"=>
  {:iata=>"OAJ",
   :name=>"Albert J. Ellis Airport",
   :icao=>"KOAJ",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, North Carolina, United States"},
 "OAK"=>
  {:iata=>"OAK",
   :name=>"Oakland International Airport",
   :icao=>"KOAK",
   :city=>"Oakland (near San Francisco)",
   :country=>'United States', :country_code=>'US',

   :location=>"Oakland (near San Francisco), California, United States"},
 "OBE"=>
  {:iata=>"OBE",
   :name=>"Okeechobee County Airport",
   :icao=>"KOBE",
   :city=>"Okeechobee",
   :country=>'United States', :country_code=>'US',

   :location=>"Okeechobee, Florida, United States"},
 "OBT"=>
  {:iata=>"OBT",
   :name=>"Oakland/coliseum Stat Airport",
   :icao=>"",
   :city=>"Oakland",
   :country=>'United States', :country_code=>'US',

   :location=>"Oakland, Maryland, United States"},
 "OBU"=>
  {:iata=>"OBU",
   :name=>"Kobuk Airport",
   :icao=>"",
   :city=>"Kobuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Kobuk, Alaska, United States"},
 "OCA"=>
  {:iata=>"OCA",
   :name=>"Ocean Reef Club Airport (FAA: 07FA)",
   :icao=>"",
   :city=>"Key Largo",
   :country=>'United States', :country_code=>'US',

   :location=>"Key Largo, Florida, United States"},
 "OCE"=>
  {:iata=>"OCE",
   :name=>"Ocean City Municipal Airport (FAA: OXB)",
   :icao=>"KOXB",
   :city=>"Ocean City",
   :country=>'United States', :country_code=>'US',

   :location=>"Ocean City, Maryland, United States"},
 "OCF"=>
  {:iata=>"OCF",
   :name=>"Ocala International Airport (Jim Taylor Field)",
   :icao=>"KOCF",
   :city=>"Ocala",
   :country=>'United States', :country_code=>'US',

   :location=>"Ocala, Florida, United States"},
 "OCH"=>
  {:iata=>"OCH",
   :name=>"A. L. Mangham Jr. Regional Airport",
   :icao=>"KOCH",
   :city=>"Nacogdoches",
   :country=>'United States', :country_code=>'US',

   :location=>"Nacogdoches, Texas, United States"},
 "OCN"=>
  {:iata=>"OCN",
   :name=>"Oceanside Municipal Airport (FAA: OKB)",
   :icao=>"KOKB",
   :city=>"Oceanside",
   :country=>'United States', :country_code=>'US',

   :location=>"Oceanside, California, United States"},
 "OCW"=>
  {:iata=>"OCW",
   :name=>"Warren Field",
   :icao=>"KOCW",
   :city=>"Washington",
   :country=>'United States', :country_code=>'US',

   :location=>"Washington, North Carolina, United States"},
 "ODW"=>
  {:iata=>"ODW",
   :name=>"A.J. Eisenberg Airport (FAA: OKH)",
   :icao=>"KOKH",
   :city=>"Oak Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Oak Harbor, Washington, United States"},
 "OEA"=>
  {:iata=>"OEA",
   :name=>"O'Neal Airport",
   :icao=>"KOEA",
   :city=>"Vincennes",
   :country=>'United States', :country_code=>'US',

   :location=>"Vincennes, Indiana, United States"},
 "OEO"=>
  {:iata=>"OEO",
   :name=>"L.O. Simenstad Municipal Airport",
   :icao=>"KOEO",
   :city=>"Osceola",
   :country=>'United States', :country_code=>'US',

   :location=>"Osceola, Wisconsin, United States"},
 "OFF"=>
  {:iata=>"OFF",
   :name=>"Offutt Air Force Base",
   :icao=>"KOFF",
   :city=>"Omaha",
   :country=>'United States', :country_code=>'US',

   :location=>"Omaha, Nebraska, United States"},
 "OFK"=>
  {:iata=>"OFK",
   :name=>"Karl Stefan Memorial Airport",
   :icao=>"KOFK",
   :city=>"Norfolk",
   :country=>'United States', :country_code=>'US',

   :location=>"Norfolk, Nebraska, United States"},
 "OGA"=>
  {:iata=>"OGA",
   :name=>"Searle Field",
   :icao=>"KOGA",
   :city=>"Ogallala",
   :country=>'United States', :country_code=>'US',

   :location=>"Ogallala, Nebraska, United States"},
 "OGB"=>
  {:iata=>"OGB",
   :name=>"Orangeburg Municipal Airport",
   :icao=>"KOGB",
   :city=>"Orangeburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Orangeburg, South Carolina, United States"},
 "OGD"=>
  {:iata=>"OGD",
   :name=>"Ogden-Hinckley Airport",
   :icao=>"KOGD",
   :city=>"Ogden",
   :country=>'United States', :country_code=>'US',

   :location=>"Ogden, Utah, United States"},
 "OGG"=>
  {:iata=>"OGG",
   :name=>"Kahului Airport",
   :icao=>"PHOG",
   :city=>"Kahului",
   :country=>'United States', :country_code=>'US',

   :location=>"Kahului, Hawaii, United States"},
 "OGS"=>
  {:iata=>"OGS",
   :name=>"Ogdensburg International Airport",
   :icao=>"KOGS",
   :city=>"Ogdensburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Ogdensburg, New York, United States"},
 "OIC"=>
  {:iata=>"OIC",
   :name=>"Norwich Lt. Warren Eaton Airport",
   :icao=>"KOIC",
   :city=>"Norwich",
   :country=>'United States', :country_code=>'US',

   :location=>"Norwich, New York, United States"},
 "OIZ"=>
  {:iata=>"OIZ",
   :name=>"Bizerte-Sidi Ahmed Air Base",
   :icao=>"DTTP",
   :city=>"Bizerte",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Bizerte, Tunisia"},
 "OJC"=>
  {:iata=>"OJC",
   :name=>"Johnson County Executive Airport",
   :icao=>"KOJC",
   :city=>"Olathe",
   :country=>'United States', :country_code=>'US',

   :location=>"Olathe, Kansas, United States"},
 "OKC"=>
  {:iata=>"OKC",
   :name=>"Will Rogers World Airport",
   :icao=>"KOKC",
   :city=>"Oklahoma City",
   :country=>'United States', :country_code=>'US',

   :location=>"Oklahoma City, Oklahoma, United States"},
 "OKK"=>
  {:iata=>"OKK",
   :name=>"Kokomo Municipal Airport",
   :icao=>"KOKK",
   :city=>"Kokomo",
   :country=>'United States', :country_code=>'US',

   :location=>"Kokomo, Indiana, United States"},
 "OKM"=>
  {:iata=>"OKM",
   :name=>"Okmulgee Regional Airport",
   :icao=>"KOKM",
   :city=>"Okmulgee",
   :country=>'United States', :country_code=>'US',

   :location=>"Okmulgee, Oklahoma, United States"},
 "OKS"=>
  {:iata=>"OKS",
   :name=>"Garden County Airport",
   :icao=>"KOKS",
   :city=>"Oshkosh",
   :country=>'United States', :country_code=>'US',

   :location=>"Oshkosh, Nebraska, United States"},
 "OLD"=>
  {:iata=>"OLD",
   :name=>"Old Town Municipal Airport and Seaplane Base (DeWitt Field)",
   :icao=>"KOLD",
   :city=>"Old Town",
   :country=>'United States', :country_code=>'US',

   :location=>"Old Town, Maine, United States"},
 "OLE"=>
  {:iata=>"OLE",
   :name=>"Cattaraugus County-Olean Airport",
   :icao=>"KOLE",
   :city=>"Olean",
   :country=>'United States', :country_code=>'US',

   :location=>"Olean, New York, United States"},
 "OLF"=>
  {:iata=>"OLF",
   :name=>"L. M. Clayton Airport",
   :icao=>"KOLF",
   :city=>"Wolf Point",
   :country=>'United States', :country_code=>'US',

   :location=>"Wolf Point, Montana, United States"},
 "OLH"=>
  {:iata=>"OLH",
   :name=>"Old Harbor Airport (FAA: 6R7)",
   :icao=>"",
   :city=>"Old Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Old Harbor, Alaska, United States"},
 "OLM"=>
  {:iata=>"OLM",
   :name=>"Olympia Airport",
   :icao=>"KOLM",
   :city=>"Olympia",
   :country=>'United States', :country_code=>'US',

   :location=>"Olympia, Washington, United States"},
 "OLS"=>
  {:iata=>"OLS",
   :name=>"Nogales International Airport",
   :icao=>"KOLS",
   :city=>"Nogales",
   :country=>'United States', :country_code=>'US',

   :location=>"Nogales, Arizona, United States"},
 "OLU"=>
  {:iata=>"OLU",
   :name=>"Columbus Municipal Airport (Nebraska)",
   :icao=>"KOLU",
   :city=>"Columbus",
   :country=>'United States', :country_code=>'US',

   :location=>"Columbus, Nebraska, United States"},
 "OLV"=>
  {:iata=>"OLV",
   :name=>"Olive Branch Airport",
   :icao=>"KOLV",
   :city=>"Olive Branch",
   :country=>'United States', :country_code=>'US',

   :location=>"Olive Branch, Mississippi, United States"},
 "OLY"=>
  {:iata=>"OLY",
   :name=>"Olney-Noble Airport",
   :icao=>"KOLY",
   :city=>"Olney-Noble",
   :country=>'United States', :country_code=>'US',

   :location=>"Olney-Noble, Illinois, United States"},
 "OMA"=>
  {:iata=>"OMA",
   :name=>"Eppley Airfield",
   :icao=>"KOMA",
   :city=>"Omaha",
   :country=>'United States', :country_code=>'US',

   :location=>"Omaha, Nebraska, United States"},
 "OME"=>
  {:iata=>"OME",
   :name=>"Nome Airport",
   :icao=>"PAOM",
   :city=>"Nome",
   :country=>'United States', :country_code=>'US',

   :location=>"Nome, Alaska, United States"},
 "OMK"=>
  {:iata=>"OMK",
   :name=>"Omak Airport",
   :icao=>"KOMK",
   :city=>"Omak",
   :country=>'United States', :country_code=>'US',

   :location=>"Omak, Washington, United States"},
 "ONA"=>
  {:iata=>"ONA",
   :name=>"Winona Municipal Airport (Max Conrad Field)",
   :icao=>"KONA",
   :city=>"Winona",
   :country=>'United States', :country_code=>'US',

   :location=>"Winona, Minnesota, United States"},
 "ONH"=>
  {:iata=>"ONH",
   :name=>"Oneonta Municipal Airport (FAA: N66)",
   :icao=>"",
   :city=>"Oneonta",
   :country=>'United States', :country_code=>'US',

   :location=>"Oneonta, New York, United States"},
 "ONL"=>
  {:iata=>"ONL",
   :name=>"O'Neill Municipal Airport (John L. Baker Field)",
   :icao=>"KONL",
   :city=>"O'Neill",
   :country=>'United States', :country_code=>'US',

   :location=>"O'Neill, Nebraska, United States"},
 "ONM"=>
  {:iata=>"ONM",
   :name=>"Socorro Municipal Airport",
   :icao=>"KONM",
   :city=>"Socorro",
   :country=>'United States', :country_code=>'US',

   :location=>"Socorro, New Mexico, United States"},
 "ONN"=>
  {:iata=>"ONN",
   :name=>"Onion Bay Airport",
   :icao=>"",
   :city=>"Onion Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Onion Bay, Alaska, United States"},
 "ONO"=>
  {:iata=>"ONO",
   :name=>"Ontario Municipal Airport",
   :icao=>"KONO",
   :city=>"Ontario",
   :country=>'United States', :country_code=>'US',

   :location=>"Ontario, Oregon, United States"},
 "ONP"=>
  {:iata=>"ONP",
   :name=>"Newport Municipal Airport",
   :icao=>"KONP",
   :city=>"Newport",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport, Oregon, United States"},
 "ONT"=>
  {:iata=>"ONT",
   :name=>"Ontario International Airport",
   :icao=>"KONT",
   :city=>"Ontario (near Los Angeles)",
   :country=>'United States', :country_code=>'US',

   :location=>"Ontario (near Los Angeles), California, United States"},
 "ONY"=>
  {:iata=>"ONY",
   :name=>"Olney Municipal Airport",
   :icao=>"KONY",
   :city=>"Olney",
   :country=>'United States', :country_code=>'US',

   :location=>"Olney, Texas, United States"},
 "OOA"=>
  {:iata=>"OOA",
   :name=>"Oskaloosa Municipal Airport",
   :icao=>"KOOA",
   :city=>"Oskaloosa",
   :country=>'United States', :country_code=>'US',

   :location=>"Oskaloosa, Iowa, United States"},
 "OOK"=>
  {:iata=>"OOK",
   :name=>"Toksook Bay Airport",
   :icao=>"PAOO",
   :city=>"Toksook Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Toksook Bay, Alaska, United States"},
 "OPF"=>
  {:iata=>"OPF",
   :name=>"Opa-locka Airport",
   :icao=>"KOPF",
   :city=>"Miami",
   :country=>'United States', :country_code=>'US',

   :location=>"Miami, Florida, United States"},
 "OPL"=>
  {:iata=>"OPL",
   :name=>"St. Landry Parish Airport (Ahart Field)",
   :icao=>"KOPL",
   :city=>"Opelousas",
   :country=>'United States', :country_code=>'US',

   :location=>"Opelousas, Louisiana, United States"},
 "OQN"=>
  {:iata=>"OQN",
   :name=>"Brandywine Airport",
   :icao=>"KOQN",
   :city=>"West Chester",
   :country=>'United States', :country_code=>'US',

   :location=>"West Chester, Pennsylvania, United States"},
 "ORD"=>
  {:iata=>"ORD",
   :name=>"O'Hare International Airport (formerly Orchard Depot Field)",
   :icao=>"KORD",
   :city=>"Chicago",
   :country=>'United States', :country_code=>'US',

   :location=>"Chicago, Illinois, United States"},
 "ORF"=>
  {:iata=>"ORF",
   :name=>"Norfolk International Airport",
   :icao=>"KORF",
   :city=>"Norfolk",
   :country=>'United States', :country_code=>'US',

   :location=>
    "Norfolk, Virginia (near Virginia Beach and Williamsburg), United States"},
 "ORH"=>
  {:iata=>"ORH",
   :name=>"Worcester Regional Airport",
   :icao=>"KORH",
   :city=>"Worcester",
   :country=>'United States', :country_code=>'US',

   :location=>"Worcester, Massachusetts, United States"},
 "ORI"=>
  {:iata=>"ORI",
   :name=>"Port Lions Airport",
   :icao=>"KORI",
   :city=>"Port Lions",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Lions, Alaska, United States"},
 "ORL"=>
  {:iata=>"ORL",
   :name=>"Orlando Executive Airport",
   :icao=>"KORL",
   :city=>"Orlando",
   :country=>'United States', :country_code=>'US',

   :location=>"Orlando, Florida, United States"},
 "ORT"=>
  {:iata=>"ORT",
   :name=>"Northway Airport",
   :icao=>"PAOR",
   :city=>"Northway",
   :country=>'United States', :country_code=>'US',

   :location=>"Northway, Alaska, United States"},
 "ORV"=>
  {:iata=>"ORV",
   :name=>"Robert (Bob) Curtis Memorial Airport (FAA: D76)",
   :icao=>"PFNO",
   :city=>"Noorvik",
   :country=>'United States', :country_code=>'US',

   :location=>"Noorvik, Alaska, United States"},
 "OSA"=>
  {:iata=>"OSA",
   :name=>"All Airports (was used for Osaka International Airport)",
   :icao=>"",
   :city=>"Osaka",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Osaka, Japan"},
 "OSB"=>
  {:iata=>"OSB",
   :name=>"Grand Glaize-Osage Beach Airport (FAA: K15)",
   :icao=>"",
   :city=>"Osage Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Osage Beach, Missouri, United States"},
 "OSC"=>
  {:iata=>"OSC",
   :name=>"Oscoda-Wurtsmith Airport",
   :icao=>"KOSC",
   :city=>"Oscoda",
   :country=>'United States', :country_code=>'US',

   :location=>"Oscoda, Michigan, United States"},
 "OSH"=>
  {:iata=>"OSH",
   :name=>"Wittman Regional Airport",
   :icao=>"KOSH",
   :city=>"Oshkosh",
   :country=>'United States', :country_code=>'US',

   :location=>"Oshkosh, Wisconsin, United States"},
 "OSU"=>
  {:iata=>"OSU",
   :name=>"Ohio State University Airport",
   :icao=>"KOSU",
   :city=>"Columbus",
   :country=>'United States', :country_code=>'US',

   :location=>"Columbus, Ohio, United States"},
 "OSX"=>
  {:iata=>"OSX",
   :name=>"Kosciusko-Attala County Airport",
   :icao=>"KOSX",
   :city=>"Kosciusko",
   :country=>'United States', :country_code=>'US',

   :location=>"Kosciusko, Mississippi, United States"},
 "OTG"=>
  {:iata=>"OTG",
   :name=>"Worthington Municipal Airport",
   :icao=>"KOTG",
   :city=>"Worthington",
   :country=>'United States', :country_code=>'US',

   :location=>"Worthington, Minnesota, United States"},
 "OTH"=>
  {:iata=>"OTH",
   :name=>"North Bend Municipal Airport",
   :icao=>"KOTH",
   :city=>"North Bend",
   :country=>'United States', :country_code=>'US',

   :location=>"North Bend, Oregon, United States"},
 "OTM"=>
  {:iata=>"OTM",
   :name=>"Ottumwa Industrial Airport",
   :icao=>"KOTM",
   :city=>"Ottumwa",
   :country=>'United States', :country_code=>'US',

   :location=>"Ottumwa, Iowa, United States"},
 "OTN"=>
  {:iata=>"OTN",
   :name=>"Ed-Air Airport (FAA: 2IG4)",
   :icao=>"",
   :city=>"Oaktown",
   :country=>'United States', :country_code=>'US',

   :location=>"Oaktown, Indiana, United States"},
 "OTS"=>
  {:iata=>"OTS",
   :name=>"Anacortes Airport (FAA: 74S)",
   :icao=>"",
   :city=>"Anacortes",
   :country=>'United States', :country_code=>'US',

   :location=>"Anacortes, Washington, United States"},
 "OTZ"=>
  {:iata=>"OTZ",
   :name=>"Ralph Wien Memorial Airport",
   :icao=>"PAOT",
   :city=>"Kotzebue",
   :country=>'United States', :country_code=>'US',

   :location=>"Kotzebue, Alaska, United States"},
 "OUN"=>
  {:iata=>"OUN",
   :name=>"University of Oklahoma Westheimer Airport",
   :icao=>"KOUN",
   :city=>"Norman",
   :country=>'United States', :country_code=>'US',

   :location=>"Norman, Oklahoma, United States"},
 "OVE"=>
  {:iata=>"OVE",
   :name=>"Oroville Municipal Airport",
   :icao=>"KOVE",
   :city=>"Oroville",
   :country=>'United States', :country_code=>'US',

   :location=>"Oroville, California, United States"},
 "OWA"=>
  {:iata=>"OWA",
   :name=>"Owatonna Degner Regional Airport",
   :icao=>"KOWA",
   :city=>"Owatonna",
   :country=>'United States', :country_code=>'US',

   :location=>"Owatonna, Minnesota, United States"},
 "OWB"=>
  {:iata=>"OWB",
   :name=>"Owensboro-Daviess County Airport",
   :icao=>"KOWB",
   :city=>"Owensboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Owensboro, Kentucky, United States"},
 "OWD"=>
  {:iata=>"OWD",
   :name=>"Norwood Memorial Airport",
   :icao=>"KOWD",
   :city=>"Norwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Norwood, Massachusetts, United States"},
 "OWK"=>
  {:iata=>"OWK",
   :name=>"Central Maine Airport of Norridgewock",
   :icao=>"KOWK",
   :city=>"Norridgewock",
   :country=>'United States', :country_code=>'US',

   :location=>"Norridgewock, Maine, United States"},
 "OXC"=>
  {:iata=>"OXC",
   :name=>"Waterbury-Oxford Airport",
   :icao=>"KOXC",
   :city=>"Oxford",
   :country=>'United States', :country_code=>'US',

   :location=>"Oxford, Connecticut, United States"},
 "OXD"=>
  {:iata=>"OXD",
   :name=>"Miami University Airport",
   :icao=>"KOXD",
   :city=>"Oxford",
   :country=>'United States', :country_code=>'US',

   :location=>"Oxford, Ohio, United States"},
 "OXR"=>
  {:iata=>"OXR",
   :name=>"Oxnard Airport",
   :icao=>"KOXR",
   :city=>"Oxnard",
   :country=>'United States', :country_code=>'US',

   :location=>"Oxnard, California, United States"},
 "OZA"=>
  {:iata=>"OZA",
   :name=>"Ozona Municipal Airport",
   :icao=>"KOZA",
   :city=>"Ozona",
   :country=>'United States', :country_code=>'US',

   :location=>"Ozona, Texas, United States"},
 "OZR"=>
  {:iata=>"OZR",
   :name=>"Cairns Army Airfield (Fort Rucker)",
   :icao=>"KOZR",
   :city=>"Fort Rucker/Ozark",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Rucker/Ozark, Alabama, United States"}}

end
