# encoding: UTF-8
def airp_15
  {"NWP"=>
  {:iata=>"NWP",
   :name=>"Naval Station",
   :city=>"Argentia",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Argentia, Canada"},
 "NIQ"=>
  {:iata=>"NIQ",
   :name=>"Niaqornat Heliport",
   :icao=>"BGNT",
   :city=>"Niaqornat",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Niaqornat, Greenland"},
 "NSQ"=>
  {:iata=>"NSQ",
   :name=>"Nuussuaq Heliport",
   :icao=>"BGNU",
   :city=>"Nuussuaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Nuussuaq, Greenland"},
 "NAQ"=>
  {:iata=>"NAQ",
   :name=>"Qaanaaq Airport",
   :city=>"Qaanaaq",
   :icao=>"",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qaanaaq, Greenland"},
 "NLD"=>
  {:iata=>"NLD",
   :name=>"Quetzalcóatl International Airport",
   :icao=>"MMNL",
   :city=>"Nuevo Laredo",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Nuevo Laredo, Mexico"},
 "NLU"=>
  {:iata=>"NLU",
   :name=>"Santa Lucía Air Force Base Num 1",
   :icao=>"MMSM",
   :city=>"Zumpango",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Zumpango, State of Mexico, Mexico"},
 "NTR"=>
  {:iata=>"NTR",
   :name=>"Del Norte International Airport",
   :city=>"Monterrey",
   :icao=>"MMAN",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Monterrey, Mexico"},
 "NOG"=>
  {:iata=>"NOG",
   :name=>"Nogales International Airport",
   :icao=>"MMNG",
   :city=>"Nogales",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Nogales, Sonora, Mexico"},
 "NCG"=>
  {:iata=>"NCG",
   :name=>"Nuevo Casas Grandes Municipal Airport",
   :icao=>"MMCG",
   :city=>"Nuevo Casas Grandes",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Nuevo Casas Grandes, Chihuahua, Mexico"},
 "NEC"=>
  {:iata=>"NEC",
   :name=>"Necochea Airport",
   :icao=>"SAZO",
   :city=>"Necochea",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Necochea, Buenos Aires, Argentina"},
 "NQN"=>
  {:iata=>"NQN",
   :name=>"Presidente Perón International Airport",
   :icao=>"SAZN",
   :city=>"Neuquen",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Neuquen, Argentina"},
 "NAT"=>
  {:iata=>"NAT",
   :name=>"Aeroporto Internacional Governador Aluízio Alves",
   :icao=>"SBNT",
   :city=>"Natal",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Natal, Brazil"},
 "NVT"=>
  {:iata=>"NVT",
   :name=>"Ministro Victor Konder International Airport",
   :icao=>"SBNF",
   :city=>"Navegantes",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Navegantes, Santa Catarina, Brazil"},
 "NBV"=>
  {:iata=>"NBV",
   :name=>"Cana Brava Airport",
   :city=>"Cana Brava",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Cana Brava, Brazil"},
 "NTM"=>
  {:iata=>"NTM",
   :name=>"Miracena Do Norte Airport",
   :city=>"Miracena Do Norte",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Miracena Do Norte, Brazil"},
 "NNU"=>
  {:iata=>"NNU",
   :name=>"Nanuque Airport",
   :city=>"Nanuque",
   :icao=>"SNNU",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Nanuque, Brazil"},
 "NQL"=>
  {:iata=>"NQL",
   :name=>"Niquelandia Airport",
   :city=>"Niquelandia",
   :icao=>"SWNQ",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Niquelandia, Brazil"},
 "NOK"=>
  {:iata=>"NOK",
   :name=>"Nova Xavantina Airport",
   :city=>"Nova Xavantina",
   :icao=>"SWXV",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Nova Xavantina, Brazil"},
 "NVP"=>
  {:iata=>"NVP",
   :name=>"Novo Aripuana Airport",
   :city=>"Novo Aripuana",
   :icao=>"SWNA",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Novo Aripuana, Brazil"},
 "NVA"=>
  {:iata=>"NVA",
   :name=>"Benito Salas Airport",
   :icao=>"SKNV",
   :city=>"Neiva",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Neiva, Colombia"},
 "NQU"=>
  {:iata=>"NQU",
   :name=>"Reyes Murillo Airport",
   :icao=>"SKNQ",
   :city=>"Nuquí",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Nuquí, Colombia"},
 "NBB"=>
  {:iata=>"NBB",
   :name=>"Barrancominas Airport",
   :city=>"Barrancominas",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Barrancominas, Colombia"},
 "NAD"=>
  {:iata=>"NAD",
   :name=>"Macanal Airport",
   :city=>"Macanal",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Macanal, Colombia"},
 "NAR"=>
  {:iata=>"NAR",
   :name=>"Nare Airport",
   :city=>"Nare",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Nare, Colombia"},
 "NCI"=>
  {:iata=>"NCI",
   :name=>"Necocli Airport",
   :city=>"Necocli",
   :icao=>"SKNC",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Necocli, Colombia"},
 "NUH"=>
  {:iata=>"NUH",
   :name=>"Nunchia Airport",
   :city=>"Nunchia",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Nunchia, Colombia"},
 "NPU"=>
  {:iata=>"NPU",
   :name=>"San Pedro Uraba Airport",
   :city=>"San Pedro Uraba",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"San Pedro Uraba, Colombia"},
 "NAI"=>
  {:iata=>"NAI",
   :name=>"Annai Airport",
   :icao=>"SYAN",
   :city=>"Annai",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Annai, Guyana"},
 "NAC"=>
  {:iata=>"NAC",
   :name=>"Naracoorte Airport",
   :city=>"Naracoorte",
   :icao=>"YNRC",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Naracoorte, Australia"},
 "NAA"=>
  {:iata=>"NAA",
   :name=>"Narrabri Airport",
   :city=>"Narrabri",
   :icao=>"YNBR",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Narrabri, Australia"},
 "NRA"=>
  {:iata=>"NRA",
   :name=>"Narrandera Airport",
   :city=>"Narrandera",
   :icao=>"YNAR",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Narrandera, Australia"},
 "NTL"=>
  {:iata=>"NTL",
   :name=>"Newcastle Airport / RAAF Base Williamtown",
   :icao=>"YWLM",
   :city=>"Newcastle",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Newcastle, New South Wales, Australia"},
 "NTN"=>
  {:iata=>"NTN",
   :name=>"Normanton Airport",
   :city=>"Normanton",
   :icao=>"YNTN",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Normanton, Australia"},
 "NLF"=>
  {:iata=>"NLF",
   :name=>"Darnley Island Airport",
   :city=>"Darnley Island",
   :icao=>"YDNI",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Darnley Island, Australia"},
 "NBR"=>
  {:iata=>"NBR",
   :name=>"Nambour Airport",
   :city=>"Nambour",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nambour, Australia"},
 "NBH"=>
  {:iata=>"NBH",
   :name=>"Nambucca Heads Airport",
   :city=>"Nambucca Heads",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nambucca Heads, Australia"},
 "NMR"=>
  {:iata=>"NMR",
   :name=>"Nappamerry Airport",
   :city=>"Nappamerry",
   :icao=>"YNAP",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nappamerry, Australia"},
 "NPP"=>
  {:iata=>"NPP",
   :name=>"Napperby Airport",
   :city=>"Napperby",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Napperby, Australia"},
 "NRG"=>
  {:iata=>"NRG",
   :name=>"Narrogin Airport",
   :icao=>"YNRG",
   :city=>"Narrogin",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Narrogin, Western Australia, Australia"},
 "NMP"=>
  {:iata=>"NMP",
   :name=>"New Moon Airport",
   :city=>"New Moon",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"New Moon, Australia"},
 "NRY"=>
  {:iata=>"NRY",
   :name=>"Newry Airport",
   :city=>"Newry",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Newry, Australia"},
 "NLS"=>
  {:iata=>"NLS",
   :name=>"Nicholson Airport",
   :city=>"Nicholson",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nicholson, Australia"},
 "NIF"=>
  {:iata=>"NIF",
   :name=>"Nifty Airport",
   :city=>"Nifty",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nifty, Australia"},
 "NKB"=>
  {:iata=>"NKB",
   :name=>"Noonkanbah Airport",
   :city=>"Noonkanbah",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Noonkanbah, Australia"},
 "NSA"=>
  {:iata=>"NSA",
   :name=>"Noosa Airport",
   :city=>"Noosa",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Noosa, Australia"},
 "NSV"=>
  {:iata=>"NSV",
   :name=>"Noosa Airport",
   :city=>"Noosaville",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Noosaville, Australia"},
 "NSM"=>
  {:iata=>"NSM",
   :name=>"Norseman Airport",
   :city=>"Norseman",
   :icao=>"YNSM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Norseman, Australia"},
 "NOA"=>
  {:iata=>"NOA",
   :name=>"Nowra Airport",
   :city=>"Nowra",
   :icao=>"YSNW",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nowra, Australia"},
 "NLL"=>
  {:iata=>"NLL",
   :name=>"Nullagine Airport",
   :city=>"Nullagine",
   :icao=>"YNUL",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nullagine, Australia"},
 "NUR"=>
  {:iata=>"NUR",
   :name=>"Nullarbor Airport",
   :city=>"Nullarbor",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nullarbor, Australia"},
 "NUB"=>
  {:iata=>"NUB",
   :name=>"Numbulwar Airport",
   :city=>"Numbulwar",
   :icao=>"YNUM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Numbulwar, Australia"},
 "NYN"=>
  {:iata=>"NYN",
   :name=>"Nyngan Airport",
   :city=>"Nyngan",
   :icao=>"YNYN",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nyngan, Australia"},
 "NDS"=>
  {:iata=>"NDS",
   :name=>"Sandstone Airport",
   :city=>"Sandstone",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Sandstone, Australia"},
 "NSO"=>
  {:iata=>"NSO",
   :name=>"Scone Airport",
   :city=>"Scone",
   :icao=>"YSCO",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Scone, Australia"},
 "NGA"=>
  {:iata=>"NGA",
   :name=>"Young Airport",
   :city=>"Young",
   :icao=>"YYNG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Young, Australia"},
 "NAN"=>
  {:iata=>"NAN",
   :name=>"Nadi International Airport",
   :icao=>"NFFN",
   :city=>"Nadi",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Nadi, Fiji"},
 "NTA"=>
  {:iata=>"NTA",
   :name=>"Natadola Airport",
   :city=>"Natadola",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Natadola, Fiji"},
 "NGI"=>
  {:iata=>"NGI",
   :name=>"Ngau Island Airport",
   :city=>"Ngau Island",
   :icao=>"NFNG",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Ngau Island, Fiji"},
 "NIU"=>
  {:iata=>"NIU",
   :name=>"Niau Airport",
   :city=>"Fakarava Niau",
   :icao=>"NTKN",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Fakarava Niau, Polynesia"},
 "NAU"=>
  {:iata=>"NAU",
   :name=>"Napuka Island Airport",
   :city=>"Napuka Island",
   :icao=>"NTGN",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Napuka Island, Polynesia"},
 "NHV"=>
  {:iata=>"NHV",
   :name=>"Nuku Hiva Airport",
   :city=>"Nuku Hiva",
   :icao=>"NTMD",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Nuku Hiva, Polynesia"},
 "NUK"=>
  {:iata=>"NUK",
   :name=>"Nukutavake Airport",
   :icao=>"NTGW",
   :city=>"Nukutavake",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Nukutavake, Tuamotus, French Polynesia"},
 "NGM"=>
  {:iata=>"NGM",
   :name=>"Agana Naval Air Station",
   :city=>"Guam",
   :icao=>"",
   :country=>'Guam', :country_code=>'GU',
   :location=>"Guam, Guam"},
 "NRV"=>
  {:iata=>"NRV",
   :name=>"United States Coast Guard Shore Station",
   :city=>"Guam",
   :icao=>"",
   :country=>'Guam', :country_code=>'GU',
   :location=>"Guam, Guam"},
 "NIG"=>
  {:iata=>"NIG",
   :name=>"Nikunau Airport",
   :city=>"Nikunau",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Nikunau, Kiribati"},
 "NON"=>
  {:iata=>"NON",
   :name=>"Nonouti Airport",
   :city=>"Nonouti",
   :icao=>"",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Nonouti, Kiribati"},
 "NDK"=>
  {:iata=>"NDK",
   :name=>"Namorik Airport (FAA: 3N0)",
   :icao=>"",
   :city=>"Namorik Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Namorik Atoll, Marshall Islands"},
 "NMU"=>
  {:iata=>"NMU",
   :name=>"Namu Airport",
   :city=>"Namu",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Namu, Islands"},
 "NOU"=>
  {:iata=>"NOU",
   :name=>"La Tontouta International Airport",
   :icao=>"NWWW",
   :city=>"Noumea",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Noumea, New Caledonia"},
 "NPE"=>
  {:iata=>"NPE",
   :name=>"Napier Airport (Hastings Airport)",
   :icao=>"NZNR",
   :city=>"Napier",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Napier, New Zealand"},
 "NSN"=>
  {:iata=>"NSN",
   :name=>"Nelson Airport",
   :icao=>"NZNS",
   :city=>"Nelson",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Nelson, New Zealand"},
 "NPL"=>
  {:iata=>"NPL",
   :name=>"New Plymouth Airport",
   :icao=>"NZNP",
   :city=>"New Plymouth",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"New Plymouth, New Zealand"},
 "NLK"=>
  {:iata=>"NLK",
   :name=>"Norfolk Island Airport",
   :icao=>"YNSF",
   :city=>"Norfolk Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Norfolk Island, Australia"},
 "NNB"=>
  {:iata=>"NNB",
   :name=>"Santa Ana Airport",
   :city=>"Santa Ana",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Santa Ana, Islands"},
 "NFO"=>
  {:iata=>"NFO",
   :name=>"Mata'aho Airport",
   :icao=>"NFTO",
   :city=>"Niuafo'ou",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Niuafo'ou, Tonga"},
 "NTT"=>
  {:iata=>"NTT",
   :name=>"Kuini Lavenia Airport",
   :city=>"Niuatoputapu",
   :icao=>"NFTP",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Niuatoputapu, Tonga"},
 "NUS"=>
  {:iata=>"NUS",
   :name=>"Norsup Airport",
   :icao=>"NVSP",
   :city=>"Norsup",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Norsup, Malakula island, Vanuatu"},
 "NAS"=>
  {:iata=>"NAS",
   :name=>"Lynden Pindling International Airport",
   :icao=>"MYNN",
   :city=>"Nassau",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Nassau, Bahamas"},
 "NSB"=>
  {:iata=>"NSB",
   :name=>"North Seaplane Base",
   :city=>"Bimini",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Bimini, Bahamas"},
 "NMC"=>
  {:iata=>"NMC",
   :name=>"Norman's Cay Airport",
   :city=>"Norman's Cay",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Norman's Cay, Bahamas"},
 "NWU"=>
  {:iata=>"NWU",
   :name=>"Naval Air Station",
   :city=>"Bermuda",
   :icao=>"",
   :country=>'Bermuda', :country_code=>'BM',
   :location=>"Bermuda, Bermuda"},
 "NGD"=>
  {:iata=>"NGD",
   :name=>"Auguste George Airport",
   :city=>"Anegada",
   :icao=>"TUPA",
   :country=>'Islands', :country_code=>'',
   :location=>"Anegada, Islands"},
 "NSX"=>
  {:iata=>"NSX",
   :name=>"North Sound Virgin Gorda Hovercraft/Launch Point",
   :city=>"North Sound Virgin Gorda",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"North Sound Virgin Gorda, Islands"},
 "NBW"=>
  {:iata=>"NBW",
   :name=>"NAS Guantanamo Bay",
   :icao=>"KNBW",
   :city=>"Guantanamo Bay",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Guantanamo Bay, Cuba"},
 "NEG"=>
  {:iata=>"NEG",
   :name=>"Negril Aerodrome",
   :icao=>"MKNG",
   :city=>"Negril",
   :country=>'Jamaica', :country_code=>'JM',
   :location=>"Negril, Jamaica"},
 "NRR"=>
  {:iata=>"NRR",
   :name=>"Roosevelt Naval Air Station",
   :city=>"Roosevelt Roads",
   :icao=>"TJNR",
   :country=>'Rico', :country_code=>'',
   :location=>"Roosevelt Roads, Rico"},
 "NEV"=>
  {:iata=>"NEV",
   :name=>"Vance W. Amory International Airport",
   :icao=>"TKPN",
   :city=>"Nevis",
   :country=>'Federation of Saint Kitts and Nevis', :country_code=>'KN',
   :location=>"Nevis, Federation of Saint Kitts and Nevis"},
 "NCA"=>
  {:iata=>"NCA",
   :name=>"North Caicos Airport",
   :icao=>"MBNC",
   :city=>"North Caicos",
   :country=>'Turks and Caicos Islands', :country_code=>'TC',
   :location=>"North Caicos, Turks and Caicos Islands"},
 "NOV"=>
  {:iata=>"NOV",
   :name=>"Albano Machado Airport",
   :icao=>"FNHU",
   :city=>"Huambo",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Huambo, Angola"},
 "NDF"=>
  {:iata=>"NDF",
   :name=>"Ndalatandos Airport",
   :city=>"Ndalatandos",
   :icao=>"",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Ndalatandos, Angola"},
 "NGV"=>
  {:iata=>"NGV",
   :name=>"Ngiva Airport",
   :city=>"Ngiva",
   :icao=>"FNGI",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Ngiva, Angola"},
 "NZA"=>
  {:iata=>"NZA",
   :name=>"Nzagi Airport",
   :icao=>"FNZG",
   :city=>"Nzagi (Andrada)",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Nzagi (Andrada), Angola"},
 "NDD"=>
  {:iata=>"NDD",
   :name=>"Sumbe Airport",
   :city=>"Sumbe",
   :icao=>"FNSU",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Sumbe, Angola"},
 "NAE"=>
  {:iata=>"NAE",
   :name=>"Natitingou Airport",
   :icao=>"DBBN",
   :city=>"Natitingou",
   :country=>'Benin', :country_code=>'BJ',
   :location=>"Natitingou, Benin"},
 "NGE"=>
  {:iata=>"NGE",
   :name=>"Ngaoundere Airport",
   :city=>"Ngaoundere",
   :icao=>"FKKN",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Ngaoundere, Cameroon"},
 "NSI"=>
  {:iata=>"NSI",
   :name=>"Yaoundé Nsimalen International Airport",
   :icao=>"FKYS",
   :city=>"Yaoundé",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Yaoundé, Cameroon"},
 "NKS"=>
  {:iata=>"NKS",
   :name=>"Nkongsamba Airport",
   :city=>"Nkongsamba",
   :icao=>"",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Nkongsamba, Cameroon"},
 "NTO"=>
  {:iata=>"NTO",
   :name=>"Agostinho Neto Airport",
   :icao=>"GVAN",
   :city=>"Ponta do Sol",
   :country=>'Cape Verde', :country_code=>'CV',
   :location=>"Ponta do Sol, Santo Antão, Cape Verde"},
 "NDL"=>
  {:iata=>"NDL",
   :name=>"Ndele Airport",
   :city=>"Ndele",
   :icao=>"FEFN",
   :country=>'Republic', :country_code=>'',
   :location=>"Ndele, Republic"},
 "NDJ"=>
  {:iata=>"NDJ",
   :name=>"N'Djamena International Airport",
   :icao=>"FTTJ",
   :city=>"N'Djamena",
   :country=>'Chad', :country_code=>'TD',
   :location=>"N'Djamena, Chad"},
 "NWA"=>
  {:iata=>"NWA",
   :name=>"Bandar Es Eslam Airport",
   :city=>"Moheli",
   :icao=>"FMCI",
   :country=>'Comoros', :country_code=>'KM',
   :location=>"Moheli, Comoros"},
 "NKY"=>
  {:iata=>"NKY",
   :name=>"Nkayi Airport",
   :city=>"Nkayi",
   :icao=>"FCBY",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Nkayi, Congo"},
 "NDM"=>
  {:iata=>"NDM",
   :name=>"Mendi Airport",
   :icao=>"HAMN",
   :city=>"Mendi",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Mendi, Ethiopia"},
 "NEJ"=>
  {:iata=>"NEJ",
   :name=>"Nejjo Airport",
   :city=>"Nejjo",
   :icao=>"HANJ",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Nejjo, Ethiopia"},
 "NEK"=>
  {:iata=>"NEK",
   :name=>"Nekemt Airport",
   :city=>"Nekemt",
   :icao=>"HANK",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Nekemt, Ethiopia"},
 "NKA"=>
  {:iata=>"NKA",
   :name=>"Nkan Airport",
   :city=>"Nkan",
   :icao=>"",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Nkan, Gabon"},
 "NYI"=>
  {:iata=>"NYI",
   :name=>"Sunyani Airport",
   :icao=>"DGSN",
   :city=>"Sunyani",
   :country=>'Ghana', :country_code=>'GH',
   :location=>"Sunyani, Ghana"},
 "NZE"=>
  {:iata=>"NZE",
   :name=>"Nzérékoré Airport",
   :icao=>"GUNZ",
   :city=>"N'zerekore",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"N'zerekore, Guinea"},
 "NBO"=>
  {:iata=>"NBO",
   :name=>"Jomo Kenyatta International Airport",
   :icao=>"HKJK",
   :city=>"Nairobi",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nairobi, Kenya"},
 "NDE"=>
  {:iata=>"NDE",
   :name=>"Mandera Airport",
   :city=>"Mandera",
   :icao=>"HKMA",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Mandera, Kenya"},
 "NUU"=>
  {:iata=>"NUU",
   :name=>"Nakuru Airport",
   :city=>"Nakuru",
   :icao=>"HKNK",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nakuru, Kenya"},
 "NYK"=>
  {:iata=>"NYK",
   :name=>"Nanyuki Airport",
   :icao=>"HKNY",
   :city=>"Nanyuki",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nanyuki, Kenya"},
 "NYE"=>
  {:iata=>"NYE",
   :name=>"Nyeri Airport",
   :city=>"Nyeri",
   :icao=>"HKNI",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nyeri, Kenya"},
 "NZO"=>
  {:iata=>"NZO",
   :name=>"Nzoia Airport",
   :city=>"Nzoia",
   :icao=>"",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nzoia, Kenya"},
 "NKU"=>
  {:iata=>"NKU",
   :name=>"Nkaus Airport",
   :city=>"Nkaus",
   :icao=>"",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Nkaus, Lesotho"},
 "NIA"=>
  {:iata=>"NIA",
   :name=>"Nimba Airport",
   :icao=>"GLNA",
   :city=>"Nimba",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Nimba, Liberia"},
 "NFR"=>
  {:iata=>"NFR",
   :name=>"Nafoora Airport",
   :icao=>"",
   :city=>"Nafoora",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Nafoora, Libya"},
 "NOS"=>
  {:iata=>"NOS",
   :name=>"Fascene Airport",
   :city=>"Nossi-be",
   :icao=>"FMNN",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Nossi-be, Madagascar"},
 "NKO"=>
  {:iata=>"NKO",
   :name=>"Ankokoambo Airport",
   :city=>"Ankokoambo",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ankokoambo, Madagascar"},
 "NRM"=>
  {:iata=>"NRM",
   :name=>"Keibane Airport",
   :icao=>"GANK",
   :city=>"Nara",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Nara, Mali"},
 "NIX"=>
  {:iata=>"NIX",
   :name=>"Nioro Airport",
   :icao=>"GANR",
   :city=>"Nioro",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Nioro, Mali"},
 "NDB"=>
  {:iata=>"NDB",
   :name=>"Nouadhibou International Airport",
   :icao=>"GQPP",
   :city=>"Nouadhibou",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Nouadhibou, Mauritania"},
 "NKC"=>
  {:iata=>"NKC",
   :name=>"Nouakchott International Airport",
   :icao=>"GQNN",
   :city=>"Nouakchott",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Nouakchott, Mauritania"},
 "NDR"=>
  {:iata=>"NDR",
   :name=>"Arwi Airport",
   :icao=>"GMMW",
   :city=>"Nador",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Nador, Morocco"},
 "NNA"=>
  {:iata=>"NNA",
   :name=>"Kenitra Airport",
   :icao=>"GMMY",
   :city=>"Kenitra",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Kenitra, Morocco"},
 "NND"=>
  {:iata=>"NND",
   :name=>"Nangade Airport",
   :city=>"Nangade",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Nangade, Mozambique"},
 "NDU"=>
  {:iata=>"NDU",
   :name=>"Rundu Airport",
   :icao=>"FYRU",
   :city=>"Rundu",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Rundu, Okavango Region, Namibia"},
 "NNI"=>
  {:iata=>"NNI",
   :name=>"Namutoni Airport",
   :city=>"Namutoni",
   :icao=>"FYNA",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Namutoni, Namibia"},
 "NIM"=>
  {:iata=>"NIM",
   :name=>"Diori Hamani International Airport",
   :icao=>"DRRN",
   :city=>"Niamey",
   :country=>'Niger', :country_code=>'NE',
   :location=>"Niamey, Niger"},
 "NIK"=>
  {:iata=>"NIK",
   :name=>"Niokolo Koba Airport",
   :city=>"Niokolo Koba",
   :icao=>"",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Niokolo Koba, Senegal"},
 "NTY"=>
  {:iata=>"NTY",
   :name=>"Pilanesberg International Airport",
   :icao=>"FAPN",
   :city=>"Pilanesberg",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Pilanesberg, South Africa"},
 "NLP"=>
  {:iata=>"NLP",
   :name=>"Nelspruit Airport",
   :city=>"Nelspruit",
   :icao=>"FANS",
   :country=>'Africa', :country_code=>'',
   :location=>"Nelspruit, Africa"},
 "NCS"=>
  {:iata=>"NCS",
   :name=>"Newcastle Airport",
   :city=>"Newcastle",
   :icao=>"FANC",
   :country=>'Africa', :country_code=>'',
   :location=>"Newcastle, Africa"},
 "NGL"=>
  {:iata=>"NGL",
   :name=>"Ngala Airfield",
   :city=>"Ngala",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Ngala, Africa"},
 "NUD"=>
  {:iata=>"NUD",
   :name=>"En Nahud Airport",
   :city=>"En Nahud",
   :icao=>"HSNH",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"En Nahud, Sudan"},
 "NHF"=>
  {:iata=>"NHF",
   :name=>"New Halfa Airport",
   :city=>"New Halfa",
   :icao=>"HSNW",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"New Halfa, Sudan"},
 "NLO"=>
  {:iata=>"NLO",
   :name=>"N'Dolo Airport",
   :city=>"Kinshasa",
   :icao=>"FZAB",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Kinshasa, Congo"},
 "NIO"=>
  {:iata=>"NIO",
   :name=>"Nioki Airport",
   :icao=>"FZBI",
   :city=>"Nioki",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Nioki, Democratic Republic of the Congo"},
 "NKL"=>
  {:iata=>"NKL",
   :name=>"Nkolo Airport",
   :icao=>"",
   :city=>"Nkolo",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Nkolo, Democratic Republic of the Congo"},
 "NBE"=>
  {:iata=>"NBE",
   :name=>"Enfidha-Hammamet Airport",
   :icao=>"DTNH",
   :city=>"Enfidha",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Enfidha, Tunisia"},
 "NCH"=>
  {:iata=>"NCH",
   :name=>"Nachingwea Airport",
   :city=>"Nachingwea",
   :icao=>"HTNA",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Nachingwea, Tanzania"},
 "NLA"=>
  {:iata=>"NLA",
   :name=>"Ndola Airport",
   :icao=>"FLND",
   :city=>"Ndola",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Ndola, Zambia"},
 "NIC"=>
  {:iata=>"NIC",
   :name=>"Nicosia Airport",
   :city=>"Nicosia",
   :icao=>"",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Nicosia, Cyprus"},
 "NCE"=>
  {:iata=>"NCE",
   :name=>"Côte d'Azur International Airport",
   :icao=>"LFMN",
   :city=>"Nice",
   :country=>'France', :country_code=>'FR',
   :location=>"Nice, France"},
 "NCY"=>
  {:iata=>"NCY",
   :name=>"Meythet Airport",
   :icao=>"LFLP",
   :city=>"Annecy",
   :country=>'France', :country_code=>'FR',
   :location=>"Annecy, France"},
 "NTE"=>
  {:iata=>"NTE",
   :name=>"Nantes Atlantique Airport",
   :icao=>"LFRS",
   :city=>"Nantes",
   :country=>'France', :country_code=>'FR',
   :location=>"Nantes, France"},
 "NVS"=>
  {:iata=>"NVS",
   :name=>"Nevers Airport",
   :city=>"Nevers",
   :icao=>"LFQG",
   :country=>'France', :country_code=>'FR',
   :location=>"Nevers, France"},
 "NIT"=>
  {:iata=>"NIT",
   :name=>"Niort Airport",
   :city=>"Niort",
   :icao=>"LFBN",
   :country=>'France', :country_code=>'FR',
   :location=>"Niort, France"},
 "NRN"=>
  {:iata=>"NRN",
   :name=>"Weeze Airport (formerly Niederrhein Airport)",
   :icao=>"EDLV",
   :city=>"Weeze",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Weeze, Niederrhein, Germany"},
 "NRD"=>
  {:iata=>"NRD",
   :name=>"Norderney Airport",
   :icao=>"EDWY",
   :city=>"Norderney",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Norderney, Germany"},
 "NUE"=>
  {:iata=>"NUE",
   :name=>"Nuremberg Airport",
   :icao=>"EDDN",
   :city=>"Nuremberg",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Nuremberg, Germany"},
 "NOE"=>
  {:iata=>"NOE",
   :name=>"Norddeich Airport",
   :city=>"Norddeich",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Norddeich, Germany"},
 "NOD"=>
  {:iata=>"NOD",
   :name=>"Norden-Norddeich Airport",
   :icao=>"EDWS",
   :city=>"Norden",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Norden, Lower Saxony, Germany"},
 "NDZ"=>
  {:iata=>"NDZ",
   :name=>"Cuxhaven Airport",
   :icao=>"ETMN",
   :city=>"Nordholz-Spieka",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Nordholz-Spieka, Lower Saxony, Germany"},
 "NOR"=>
  {:iata=>"NOR",
   :name=>"Nordfjordur Airport",
   :city=>"Nordfjordur",
   :icao=>"BINF",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Nordfjordur, Iceland"},
 "NOC"=>
  {:iata=>"NOC",
   :name=>"Knock International Airport",
   :icao=>"EIKN",
   :city=>"Knock",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Knock, Ireland"},
 "NNR"=>
  {:iata=>"NNR",
   :name=>"Connemara Regional Airport",
   :icao=>"EICA",
   :city=>"Inverin",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Inverin, Ireland"},
 "NAP"=>
  {:iata=>"NAP",
   :name=>"Naples Airport",
   :icao=>"LIRN",
   :city=>"Naples",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Naples, Italy"},
 "NSY"=>
  {:iata=>"NSY",
   :name=>"Sigonella Airport",
   :icao=>"LICZ",
   :city=>"Catania",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Catania, Italy"},
 "NVK"=>
  {:iata=>"NVK",
   :name=>"Narvik Airport, Framnes",
   :icao=>"ENNK",
   :city=>"Narvik",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Narvik, Nordland, Norway"},
 "NTB"=>
  {:iata=>"NTB",
   :name=>"Notodden Airport, Tuven,",
   :icao=>"ENNO",
   :city=>"Notodden",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Notodden, Norway"},
 "NBC"=>
  {:iata=>"NBC",
   :name=>"Begishevo Airport",
   :icao=>"UWKE",
   :city=>"Nizhnekamsk/Naberezhnye Chelny",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nizhnekamsk/Naberezhnye Chelny, Tatarstan, Russia"},
 "NYM"=>
  {:iata=>"NYM",
   :name=>"Nadym Airport",
   :icao=>"USMM",
   :city=>"Nadym",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nadym, Yamalo-Nenets Autonomous Okrug, Russia"},
 "NAL"=>
  {:iata=>"NAL",
   :name=>"Nalchik Airport",
   :icao=>"URMN",
   :city=>"Nalchik",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nalchik, Kabardino-Balkaria, Russia"},
 "NNM"=>
  {:iata=>"NNM",
   :name=>"Naryan-Mar Airport",
   :icao=>"ULAM",
   :city=>"Naryan-Mar",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Naryan-Mar, Nenets Autonomous Okrug, Russia"},
 "NER"=>
  {:iata=>"NER",
   :name=>"Chulman Neryungri Airport",
   :icao=>"UELL",
   :city=>"Chulman",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Chulman, Russia"},
 "NJC"=>
  {:iata=>"NJC",
   :name=>"Nizhnevartovsk Airport",
   :icao=>"USNN",
   :city=>"Nizhnevartovsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nizhnevartovsk, Russia"},
 "NGK"=>
  {:iata=>"NGK",
   :name=>"Nogliki Airport",
   :city=>"Nogliki",
   :icao=>"UHSN",
   :country=>'Federation', :country_code=>'',
   :location=>"Nogliki, Federation"},
 "NOJ"=>
  {:iata=>"NOJ",
   :name=>"Noyabrsk Airport",
   :icao=>"USRO",
   :city=>"Noyabrsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Noyabrsk, Yamalo-Nenets Autonomous Okrug, Russia"},
 "NSK"=>
  {:iata=>"NSK",
   :name=>"Norilsk Alykel Airport",
   :icao=>"UOOO",
   :city=>"Norilsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Norilsk, Russia"},
 "NVR"=>
  {:iata=>"NVR",
   :name=>"Novgorod Airport",
   :icao=>"ULNN",
   :city=>"Veliky Novgorod",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Veliky Novgorod, Russia"},
 "NOZ"=>
  {:iata=>"NOZ",
   :name=>"Novokuznetsk Spichenkovo Airport (Prokopyevsk Southeast)",
   :icao=>"UNWW",
   :city=>"Prokopyevsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Prokopyevsk, Kemerovo Oblast, Russia"},
 "NUX"=>
  {:iata=>"NUX",
   :name=>"Novy Urengoy Airport",
   :icao=>"NSMU",
   :city=>"Novy Urengoy",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Novy Urengoy, Russia"},
 "NYA"=>
  {:iata=>"NYA",
   :name=>"Nyagan Airport",
   :icao=>"USHN",
   :city=>"Nyagan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nyagan, Tyumen Oblast, Russia"},
 "NYR"=>
  {:iata=>"NYR",
   :name=>"Nyurba Airport",
   :icao=>"UENN",
   :city=>"Nyurba",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nyurba, Sakha Republic, Russia"},
 "NEF"=>
  {:iata=>"NEF",
   :name=>"Neftekamsk Airport",
   :icao=>"UWUF",
   :city=>"Neftekamsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Neftekamsk, Bashkortostan, Russia"},
 "NFG"=>
  {:iata=>"NFG",
   :name=>"Nefteyugansk Airport",
   :icao=>"USRN",
   :city=>"Nefteyugansk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nefteyugansk, Khanty–Mansi Autonomous Okrug, Russia"},
 "NOI"=>
  {:iata=>"NOI",
   :name=>"Novorossijsk Airport",
   :city=>"Novorossijsk",
   :icao=>"",
   :country=>'Federation', :country_code=>'',
   :location=>"Novorossijsk, Federation"},
 "NDO"=>
  {:iata=>"NDO",
   :name=>"La Palma Del Condado Airport",
   :city=>"La Palma Del Condado",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"La Palma Del Condado, Islands"},
 "NRK"=>
  {:iata=>"NRK",
   :name=>"Norrköping Airport",
   :icao=>"ESSP",
   :city=>"Norrköping",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Norrköping, Sweden"},
 "NYO"=>
  {:iata=>"NYO",
   :name=>"Stockholm-Skavsta Airport",
   :icao=>"ESKN",
   :city=>"Nyköping",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Nyköping, Sweden"},
 "NKT"=>
  {:iata=>"NKT",
   :name=>"Şırnak Airport",
   :icao=>"LTCV",
   :city=>"Cizre",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Cizre, Turkey"},
 "NAV"=>
  {:iata=>"NAV",
   :name=>"Kapadokya Airport",
   :icao=>"LTAZ",
   :city=>"Nevsehir",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Nevsehir, Turkey"},
 "NOP"=>
  {:iata=>"NOP",
   :name=>"Sinop Airport (old IATA code was SIC)",
   :icao=>"LTCM",
   :city=>"Sinop",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Sinop, Turkey"},
 "NLV"=>
  {:iata=>"NLV",
   :name=>"Mykolaiv Airport",
   :icao=>"UKON",
   :city=>"Mykolaiv",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Mykolaiv, Ukraine"},
 "NCL"=>
  {:iata=>"NCL",
   :name=>"Newcastle Airport",
   :icao=>"EGNT",
   :city=>"Newcastle upon Tyne",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Newcastle upon Tyne, United Kingdom"},
 "NQY"=>
  {:iata=>"NQY",
   :name=>"Newquay Cornwall International Airport",
   :icao=>"EGDG",
   :city=>"Newquay",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Newquay, England, United Kingdom"},
 "NRL"=>
  {:iata=>"NRL",
   :name=>"North Ronaldsay Airport",
   :city=>"North Ronaldsay",
   :icao=>"EGEN",
   :country=>'Kingdom', :country_code=>'',
   :location=>"North Ronaldsay, Kingdom"},
 "NWI"=>
  {:iata=>"NWI",
   :name=>"Norwich International Airport",
   :icao=>"EGSH",
   :city=>"Norwich",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Norwich, England, United Kingdom"},
 "NDY"=>
  {:iata=>"NDY",
   :name=>"Sanday Airport",
   :icao=>"EGES",
   :city=>"Sanday",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Sanday, Scotland, United Kingdom"},
 "NHT"=>
  {:iata=>"NHT",
   :name=>"RAF Northolt",
   :icao=>"EGWU",
   :city=>"Ruislip",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Ruislip, England, United Kingdom"},
 "NQT"=>
  {:iata=>"NQT",
   :name=>"Nottingham Airport",
   :city=>"Nottingham",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Nottingham, Kingdom"},
 "NAJ"=>
  {:iata=>"NAJ",
   :name=>"Nakhichevan Airport",
   :city=>"Nakhichevan",
   :icao=>"",
   :country=>'Azerbaijan', :country_code=>'AZ',
   :location=>"Nakhichevan, Azerbaijan"},
 "NKG"=>
  {:iata=>"NKG",
   :name=>"Nanjing Lukou International Airport",
   :icao=>"ZSNJ",
   :city=>"Nanjing",
   :country=>'China', :country_code=>'CN',
   :location=>"Nanjing, China"},
 "NNG"=>
  {:iata=>"NNG",
   :name=>"Nanning Wuxu International Airport",
   :icao=>"ZGNN",
   :city=>"Nanning",
   :country=>'China', :country_code=>'CN',
   :location=>"Nanning, Guangxi, China"},
 "NBS"=>
  {:iata=>"NBS",
   :name=>"Changbaishan Airport",
   :icao=>"",
   :city=>"Baishan",
   :country=>'China', :country_code=>'CN',
   :location=>"Baishan, Jilin, China"},
 "NAY"=>
  {:iata=>"NAY",
   :name=>"Nanyuan Airport",
   :icao=>"ZBNY",
   :city=>"Beijing",
   :country=>'China', :country_code=>'CN',
   :location=>"Beijing, China"},
 "NZH"=>
  {:iata=>"NZH",
   :name=>"Manzhouli Airport",
   :city=>"Manzhouli",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Manzhouli, China"},
 "NAO"=>
  {:iata=>"NAO",
   :name=>"Nanchong Airport",
   :icao=>"ZUNC",
   :city=>"Nanchong",
   :country=>'China', :country_code=>'CN',
   :location=>"Nanchong, Sichuan, China"},
 "NTG"=>
  {:iata=>"NTG",
   :name=>"Nantong Airport",
   :city=>"Nantong",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Nantong, China"},
 "NNY"=>
  {:iata=>"NNY",
   :name=>"Nanyang Airport",
   :icao=>"ZHNY",
   :city=>"Nanyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Nanyang, Henan, China"},
 "NGB"=>
  {:iata=>"NGB",
   :name=>"Ningbo Lishe International Airport",
   :icao=>"ZSNB",
   :city=>"Ningbo",
   :country=>'China', :country_code=>'CN',
   :location=>"Ningbo, Zhejiang, China"},
 "NDG"=>
  {:iata=>"NDG",
   :name=>"Qiqihar Airport",
   :city=>"Qiqihar",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Qiqihar, China"},
 "NGQ"=>
  {:iata=>"NGQ",
   :name=>"Ngari Gunsa Airport",
   :icao=>"ZUAL",
   :city=>"Ngari Prefecture",
   :country=>'China', :country_code=>'CN',
   :location=>"Ngari Prefecture, Tibet Autonomous Region, China"},
 "NLT"=>
  {:iata=>"NLT",
   :name=>"Nalati Airport",
   :icao=>"ZWNL",
   :city=>"Künes",
   :country=>'China', :country_code=>'CN',
   :location=>"Künes, Xinjiang, China"},
 "NAG"=>
  {:iata=>"NAG",
   :name=>"Dr. Babasaheb Ambedkar International Airport",
   :icao=>"VANP",
   :city=>"Nagpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Nagpur, India"},
 "NDC"=>
  {:iata=>"NDC",
   :name=>"Nanded Airport",
   :icao=>"VAND",
   :city=>"Nanded",
   :country=>"India",
:country_code=>"IN",
   :location=>"Nanded, India"},
 "NMB"=>
  {:iata=>"NMB",
   :name=>"Daman Airport",
   :icao=>"VADN",
   :city=>"Daman",
   :country=>"India",
:country_code=>"IN",
   :location=>"Daman, India"},
 "NVY"=>
  {:iata=>"NVY",
   :name=>"Neyveli Airport",
   :icao=>"",
   :city=>"Neyveli",
   :country=>"India",
:country_code=>"IN",
   :location=>"Neyveli, India"},
 "NBX"=>
  {:iata=>"NBX",
   :name=>"Nabire Airport",
   :icao=>"WABI",
   :city=>"Nabire",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Nabire, Indonesia"},
 "NAH"=>
  {:iata=>"NAH",
   :name=>"Naha Airport",
   :icao=>"WAMH",
   :city=>"Tahuna",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Tahuna, Indonesia"},
 "NTX"=>
  {:iata=>"NTX",
   :name=>"Ranai Airport",
   :icao=>"WION",
   :city=>"Natuna",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Natuna, Riau Islands, Indonesia"},
 "NNX"=>
  {:iata=>"NNX",
   :name=>"Nunukan Airport",
   :icao=>"WRLF",
   :city=>"Nunukan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Nunukan, East Kalimantan, Indonesia"},
 "NAF"=>
  {:iata=>"NAF",
   :name=>"Banaina Airport",
   :city=>"Banaina",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Banaina, Indonesia"},
 "NDA"=>
  {:iata=>"NDA",
   :name=>"Bandanaira Airport",
   :city=>"Bandanaira",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Bandanaira, Indonesia"},
 "NTI"=>
  {:iata=>"NTI",
   :name=>"Bintuni Airport",
   :city=>"Bintuni",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Bintuni, Indonesia"},
 "NAM"=>
  {:iata=>"NAM",
   :name=>"Namlea Airport",
   :city=>"Namlea",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Namlea, Indonesia"},
 "NRE"=>
  {:iata=>"NRE",
   :name=>"Namrole Airport",
   :icao=>"WAPG",
   :city=>"Buru",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Buru, Indonesia"},
 "NPO"=>
  {:iata=>"NPO",
   :name=>"Nangapinoh Airport",
   :city=>"Nangapinoh",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Nangapinoh, Indonesia"},
 "NKD"=>
  {:iata=>"NKD",
   :name=>"Sinak, Irian Jaya Airport",
   :city=>"Sinak, Irian Jaya",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Sinak, Irian Jaya, Indonesia"},
 "NSH"=>
  {:iata=>"NSH",
   :name=>"Now Shahr Airport",
   :city=>"Now Shahr",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Now Shahr, Iran"},
 "NUJ"=>
  {:iata=>"NUJ",
   :name=>"Nojeh Airport",
   :city=>"Nojeh",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Nojeh, Iran"},
 "NGO"=>
  {:iata=>"NGO",
   :name=>"Chubu Centrair International Airport",
   :icao=>"RJGG",
   :city=>"Nagoya",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Nagoya, Japan"},
 "NRT"=>
  {:iata=>"NRT",
   :name=>"Narita International Airport (formerly New Tokyo International)",
   :icao=>"RJAA",
   :city=>"Narita (near Tokyo)",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Narita (near Tokyo), Japan"},
 "NGS"=>
  {:iata=>"NGS",
   :name=>"Nagasaki Airport",
   :icao=>"RJFU",
   :city=>"Nagasaki",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Nagasaki, Japan"},
 "NKM"=>
  {:iata=>"NKM",
   :name=>"Nagoya Airfield (formerly: NGO)",
   :icao=>"RJNA",
   :city=>"Nagoya",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Nagoya, Japan"},
 "NTQ"=>
  {:iata=>"NTQ",
   :name=>"Noto Airport",
   :city=>"Wajima",
   :icao=>"RJNW",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Wajima, Japan"},
 "NJA"=>
  {:iata=>"NJA",
   :name=>"Naval Air Station",
   :city=>"Atsugi",
   :icao=>"RJTA",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Atsugi, Japan"},
 "NEU"=>
  {:iata=>"NEU",
   :name=>"Sam Neua Airport",
   :city=>"Sam Neua",
   :icao=>"VLSN",
   :country=>'Republic', :country_code=>'',
   :location=>"Sam Neua, Republic"},
 "NYW"=>
  {:iata=>"NYW",
   :name=>"Monywa Airport",
   :city=>"Monywa",
   :icao=>"VYMY",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Monywa, Myanmar"},
 "NYT"=>
  {:iata=>"NYT",
   :name=>"Naypyidaw Airport",
   :icao=>"VYNT",
   :city=>"Naypyidaw",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Naypyidaw, Myanmar"},
 "NYU"=>
  {:iata=>"NYU",
   :name=>"Bagan Airport",
   :icao=>"VYBG",
   :city=>"Bagan",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Bagan, Myanmar (Burma)"},
 "NMS"=>
  {:iata=>"NMS",
   :name=>"Namsang Airport",
   :city=>"Namsang",
   :icao=>"VYNS",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Namsang, Myanmar"},
 "NMT"=>
  {:iata=>"NMT",
   :name=>"Namtu Airport",
   :city=>"Namtu",
   :icao=>"",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Namtu, Myanmar"},
 "NGX"=>
  {:iata=>"NGX",
   :name=>"Manang Airport",
   :city=>"Manang",
   :icao=>"VNMA",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Manang, Nepal"},
 "NHS"=>
  {:iata=>"NHS",
   :name=>"Nushki Airport",
   :city=>"Nushki",
   :icao=>"",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Nushki, Pakistan"},
 "NDN"=>
  {:iata=>"NDN",
   :name=>"Nadunumu Airport",
   :city=>"Nadunumu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nadunumu, Guinea"},
 "NBA"=>
  {:iata=>"NBA",
   :name=>"Nambaiyufa Airport",
   :city=>"Nambaiyufa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nambaiyufa, Guinea"},
 "NDI"=>
  {:iata=>"NDI",
   :name=>"Namudi Airport",
   :city=>"Namudi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Namudi, Guinea"},
 "NKN"=>
  {:iata=>"NKN",
   :name=>"Nankina Airport",
   :city=>"Nankina",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nankina, Guinea"},
 "NOO"=>
  {:iata=>"NOO",
   :name=>"Naoro Airport",
   :city=>"Naoro",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Naoro, Guinea"},
 "NGR"=>
  {:iata=>"NGR",
   :name=>"Ningerum Airport",
   :city=>"Ningerum",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Ningerum, Guinea"},
 "NPG"=>
  {:iata=>"NPG",
   :name=>"Nipa Airport",
   :city=>"Nipa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nipa, Guinea"},
 "NOM"=>
  {:iata=>"NOM",
   :name=>"Nomad River Airport",
   :city=>"Nomad River",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nomad River, Guinea"},
 "NMN"=>
  {:iata=>"NMN",
   :name=>"Nomane Airport",
   :city=>"Nomane",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nomane, Guinea"},
 "NWT"=>
  {:iata=>"NWT",
   :name=>"Nowata Airport",
   :city=>"Nowata",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nowata, Guinea"},
 "NUG"=>
  {:iata=>"NUG",
   :name=>"Nuguria Airport",
   :city=>"Nuguria",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nuguria, Guinea"},
 "NUT"=>
  {:iata=>"NUT",
   :name=>"Nutuve Airport",
   :city=>"Nutuve",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nutuve, Guinea"},
 "NIS"=>
  {:iata=>"NIS",
   :name=>"Simberi Airport",
   :icao=>"",
   :city=>"Simberi Island",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Simberi Island, Papua New Guinea"},
 "NCP"=>
  {:iata=>"NCP",
   :name=>"Cubi Pt Naval Air Station",
   :city=>"Luzon Island",
   :icao=>"",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Luzon Island, Philippines"},
 "NUA"=>
  {:iata=>"NUA",
   :name=>"Gregory Lake Sea Plane Base",
   :city=>"Nuwara Eliya",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Nuwara Eliya, Lanka"},
 "NST"=>
  {:iata=>"NST",
   :name=>"Nakhon Si Thammarat Airport",
   :city=>"Nakhon Si Thammarat",
   :icao=>"VTSN",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Nakhon Si Thammarat, Thailand"},
 "NNT"=>
  {:iata=>"NNT",
   :name=>"Nan Airport",
   :city=>"Nan",
   :icao=>"VTCN",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Nan, Thailand"},
 "NAW"=>
  {:iata=>"NAW",
   :name=>"Narathiwat Airport",
   :city=>"Narathiwat",
   :icao=>"VTSC",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Narathiwat, Thailand"},
 "NAK"=>
  {:iata=>"NAK",
   :name=>"Nakhon Ratchasima Airport",
   :icao=>"VTUQ",
   :city=>"Nakhon Ratchasima",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Nakhon Ratchasima, Thailand"},
 "NMA"=>
  {:iata=>"NMA",
   :name=>"Namangan Airport",
   :city=>"Namangan",
   :icao=>"",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Namangan, Uzbekistan"},
 "NVI"=>
  {:iata=>"NVI",
   :name=>"Navoi Airport",
   :city=>"Navoi",
   :icao=>"",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Navoi, Uzbekistan"},
 "NCU"=>
  {:iata=>"NCU",
   :name=>"Nukus Airport",
   :icao=>"UTNN",
   :city=>"Nukus",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Nukus, Uzbekistan"},
 "NHA"=>
  {:iata=>"NHA",
   :name=>"Nha Trang Airport",
   :city=>"Nha Trang",
   :icao=>"VVNT",
   :country=>'Nam', :country_code=>'',
   :location=>"Nha Trang, Nam"},
 "NOB"=>
  {:iata=>"NOB",
   :name=>"Nosara Airport",
   :icao=>"MRNS",
   :city=>"Nosara",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Nosara, Costa Rica"},
 "NCT"=>
  {:iata=>"NCT",
   :name=>"Guanacaste Airport",
   :city=>"Nicoya",
   :icao=>"",
   :country=>'Rica', :country_code=>'',
   :location=>"Nicoya, Rica"},
 "NVG"=>
  {:iata=>"NVG",
   :name=>"Nueva Guinea Airport",
   :city=>"Nueva Guinea",
   :icao=>"",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"Nueva Guinea, Nicaragua"},
 "NCR"=>
  {:iata=>"NCR",
   :name=>"San Carlos Airport",
   :city=>"San Carlos",
   :icao=>"",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"San Carlos, Nicaragua"},
 "NMG"=>
  {:iata=>"NMG",
   :name=>"San Miguel Airport",
   :city=>"San Miguel",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"San Miguel, Panama"},
 "NGN"=>
  {:iata=>"NGN",
   :name=>"Nargana Airport",
   :city=>"Nargana",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Nargana, Panama"},
 "NBL"=>
  {:iata=>"NBL",
   :name=>"San Blas Airport",
   :city=>"San Blas",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"San Blas, Panama"},
 "NJF"=>
  {:iata=>"NJF",
   :name=>"Al Najaf International Airport",
   :icao=>"ORNI",
   :city=>"Al Najaf",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Al Najaf, Iraq"},
 "NHD"=>
  {:iata=>"NHD",
   :name=>"Minhad Military Airport",
   :city=>"Minhad",
   :icao=>"",
   :country=>'Emirates', :country_code=>'',
   :location=>"Minhad, Emirates"},
 "NAX"=>
  {:iata=>"NAX",
   :name=>
    "Kalaeloa Airport (NAS Barbers Point) (John Rodgers Field) (FAA: JRF)",
   :icao=>"PHJR",
   :city=>"Kapolei",
   :country=>'United States', :country_code=>'US',

   :location=>"Kapolei, Hawaii, United States"},
 "NBG"=>
  {:iata=>"NBG",
   :name=>"NAS JRB New Orleans (Alvin Callender Field)",
   :icao=>"KNBG",
   :city=>"New Orleans",
   :country=>'United States', :country_code=>'US',

   :location=>"New Orleans, Louisiana, United States"},
 "NBK"=>
  {:iata=>"NBK",
   :name=>"Suvarnabhumi International Airport",
   :icao=>"VTBS",
   :city=>"Bangkok",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Bangkok, Thailand"},
 "NCN"=>
  {:iata=>"NCN",
   :name=>"Chenega Bay Airport (FAA: C05)",
   :icao=>"PFCB",
   :city=>"Chenega",
   :country=>'United States', :country_code=>'US',

   :location=>"Chenega, Alaska, United States"},
 "NEL"=>
  {:iata=>"NEL",
   :name=>"NAES Lakehurst (Maxfield Field)",
   :icao=>"KNEL",
   :city=>"Lakehurst",
   :country=>'United States', :country_code=>'US',

   :location=>"Lakehurst, New Jersey, United States"},
 "NEN"=>
  {:iata=>"NEN",
   :name=>"NOLF Whitehouse",
   :icao=>"KNEN",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Florida, United States"},
 "NET"=>
  {:iata=>"NET",
   :name=>"New Bight Airport",
   :icao=>"MYCB",
   :city=>"New Bight",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"New Bight, Cat Island, Bahamas"},
 "NEW"=>
  {:iata=>"NEW",
   :name=>"New Orleans Lakefront Airport",
   :icao=>"KNEW",
   :city=>"New Orleans",
   :country=>'United States', :country_code=>'US',

   :location=>"New Orleans, Louisiana, United States"},
 "NFL"=>
  {:iata=>"NFL",
   :name=>"NAS Fallon (Van Voorhis Field)",
   :icao=>"KNFL",
   :city=>"Fallon",
   :country=>'United States', :country_code=>'US',

   :location=>"Fallon, Nevada, United States"},
 "NGP"=>
  {:iata=>"NGP",
   :name=>"NAS Corpus Christi (Truax Field)",
   :icao=>"KNGP",
   :city=>"Corpus Christi",
   :country=>'United States', :country_code=>'US',

   :location=>"Corpus Christi, Texas, United States"},
 "NGU"=>
  {:iata=>"NGU",
   :name=>"NS Norfolk (Chambers Field)",
   :icao=>"KNGU",
   :city=>"Norfolk",
   :country=>'United States', :country_code=>'US',

   :location=>"Norfolk, Virginia, United States"},
 "NGW"=>
  {:iata=>"NGW",
   :name=>"NOLF Cabaniss",
   :icao=>"KNGW",
   :city=>"Corpus Christi",
   :country=>'United States', :country_code=>'US',

   :location=>"Corpus Christi, Texas, United States"},
 "NHK"=>
  {:iata=>"NHK",
   :name=>"NAS Patuxent River (Trapnell Field)",
   :icao=>"KNHK",
   :city=>"Patuxent River",
   :country=>'United States', :country_code=>'US',

   :location=>"Patuxent River, Maryland, United States"},
 "NHX"=>
  {:iata=>"NHX",
   :name=>"NOLF Barin (FAA: NBJ)",
   :icao=>"KNBJ",
   :city=>"Foley",
   :country=>'United States', :country_code=>'US',

   :location=>"Foley, Alabama, United States"},
 "NHZ"=>
  {:iata=>"NHZ",
   :name=>"NAS Brunswick",
   :icao=>"KNHZ",
   :city=>"Brunswick",
   :country=>'United States', :country_code=>'US',

   :location=>"Brunswick, Maine, United States"},
 "NIB"=>
  {:iata=>"NIB",
   :name=>"Nikolai Airport (FAA: FSP)",
   :icao=>"PAFS",
   :city=>"Nikolai",
   :country=>'United States', :country_code=>'US',

   :location=>"Nikolai, Alaska, United States"},
 "NIN"=>
  {:iata=>"NIN",
   :name=>"Ninilchik Airport",
   :icao=>"",
   :city=>"Ninilchik",
   :country=>'United States', :country_code=>'US',

   :location=>"Ninilchik, Alaska, United States"},
 "NIP"=>
  {:iata=>"NIP",
   :name=>"NAS Jacksonville (Towers Field)",
   :icao=>"KNIP",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Florida, United States"},
 "NJK"=>
  {:iata=>"NJK",
   :name=>"NAF El Centro",
   :icao=>"KNJK",
   :city=>"El Centro",
   :country=>'United States', :country_code=>'US',

   :location=>"El Centro, California, United States"},
 "NKX"=>
  {:iata=>"NKX",
   :name=>"MCAS Miramar",
   :icao=>"KNKX",
   :city=>"San Diego",
   :country=>'United States', :country_code=>'US',

   :location=>"San Diego, California, United States"},
 "NLC"=>
  {:iata=>"NLC",
   :name=>"NAS Lemoore (Reeves Field)",
   :icao=>"KNLC",
   :city=>"Lemoore",
   :country=>'United States', :country_code=>'US',

   :location=>"Lemoore, California, United States"},
 "NLE"=>
  {:iata=>"NLE",
   :name=>"Jerry Tyler Memorial Airport (FAA: 3TR)",
   :icao=>"",
   :city=>"Niles",
   :country=>'United States', :country_code=>'US',

   :location=>"Niles, Michigan, United States"},
 "NLG"=>
  {:iata=>"NLG",
   :name=>"Nelson Lagoon Airport (FAA: OUL)",
   :icao=>"PAOU",
   :city=>"Nelson Lagoon",
   :country=>'United States', :country_code=>'US',

   :location=>"Nelson Lagoon, Alaska, United States"},
 "NLI"=>
  {:iata=>"NLI",
   :name=>"Nikolayevsk-on-Amur Airport",
   :icao=>"",
   :city=>"Nikolayevsk-on-Amur",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nikolayevsk-on-Amur, Khabarovsk Krai, Russia"},
 "NME"=>
  {:iata=>"NME",
   :name=>"Nightmute Airport (FAA: IGT)",
   :icao=>"PAGT",
   :city=>"Nightmute",
   :country=>'United States', :country_code=>'US',

   :location=>"Nightmute, Alaska, United States"},
 "NNK"=>
  {:iata=>"NNK",
   :name=>"Naknek Airport (FAA: 5NK)",
   :icao=>"",
   :city=>"Naknek",
   :country=>'United States', :country_code=>'US',

   :location=>"Naknek, Alaska, United States"},
 "NNL"=>
  {:iata=>"NNL",
   :name=>"Nondalton Airport (FAA: 5NN)",
   :icao=>"PANO",
   :city=>"Nondalton",
   :country=>'United States', :country_code=>'US',

   :location=>"Nondalton, Alaska, United States"},
 "NOT"=>
  {:iata=>"NOT",
   :name=>"Gnoss Field (FAA: DVO)",
   :icao=>"KDVO",
   :city=>"Novato",
   :country=>'United States', :country_code=>'US',

   :location=>"Novato, California, United States"},
 "NOW"=>
  {:iata=>"NOW",
   :name=>"CGAS Port Angeles",
   :icao=>"KNOW",
   :city=>"Port Angeles",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Angeles, Washington, United States"},
 "NPA"=>
  {:iata=>"NPA",
   :name=>"NAS Pensacola (Forrest Sherman Field)",
   :icao=>"KNPA",
   :city=>"Pensacola",
   :country=>'United States', :country_code=>'US',

   :location=>"Pensacola, Florida, United States"},
 "NPH"=>
  {:iata=>"NPH",
   :name=>"Nephi Municipal Airport (FAA: U14)",
   :icao=>"",
   :city=>"Nephi",
   :country=>'United States', :country_code=>'US',

   :location=>"Nephi, Utah, United States"},
 "NPT"=>
  {:iata=>"NPT",
   :name=>"Newport State Airport (FAA: UUU)",
   :icao=>"KUUU",
   :city=>"Newport",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport, Rhode Island, United States"},
 "NQA"=>
  {:iata=>"NQA",
   :name=>"Millington Regional Jetport",
   :icao=>"KNQA",
   :city=>"Millington",
   :country=>'United States', :country_code=>'US',

   :location=>"Millington, Tennessee, United States"},
 "NQI"=>
  {:iata=>"NQI",
   :name=>"NAS Kingsville",
   :icao=>"KNQI",
   :city=>"Kingsville",
   :country=>'United States', :country_code=>'US',

   :location=>"Kingsville, Texas, United States"},
 "NQX"=>
  {:iata=>"NQX",
   :name=>"NAS Key West (Boca Chica Field)",
   :icao=>"KNQX",
   :city=>"Boca Chica Key",
   :country=>'United States', :country_code=>'US',

   :location=>"Boca Chica Key, Florida, United States"},
 "NRB"=>
  {:iata=>"NRB",
   :name=>"NS Mayport (Adm. David L. McDonald Field)",
   :icao=>"KNRB",
   :city=>"Mayport",
   :country=>'United States', :country_code=>'US',

   :location=>"Mayport, Florida, United States"},
 "NRC"=>
  {:iata=>"NRC",
   :name=>"NASA Crows Landing Airport (formerly NALF Crows Landing)",
   :icao=>"KNRC",
   :city=>"Crows Landing",
   :country=>'United States', :country_code=>'US',

   :location=>"Crows Landing, California, United States"},
 "NRS"=>
  {:iata=>"NRS",
   :name=>"NOLF Imperial Beach (Ream Field)",
   :icao=>"KNRS",
   :city=>"Imperial Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Imperial Beach, California, United States"},
 "NSE"=>
  {:iata=>"NSE",
   :name=>"NAS Whiting Field - North",
   :icao=>"KNSE",
   :city=>"Milton",
   :country=>'United States', :country_code=>'US',

   :location=>"Milton, Florida, United States"},
 "NTD"=>
  {:iata=>"NTD",
   :name=>"NAS Point Mugu (Naval Base Ventura County)",
   :icao=>"KNTD",
   :city=>"Point Mugu",
   :country=>'United States', :country_code=>'US',

   :location=>"Point Mugu, California, United States"},
 "NTJ"=>
  {:iata=>"NTJ",
   :name=>"Manti-Ephraim Airport (FAA: 41U)",
   :icao=>"",
   :city=>"Manti",
   :country=>'United States', :country_code=>'US',

   :location=>"Manti, Utah, United States"},
 "NTU"=>
  {:iata=>"NTU",
   :name=>"NAS Oceana (Apollo Soucek Field)",
   :icao=>"KNTU",
   :city=>"Virginia Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Virginia Beach, Virginia, United States"},
 "NUI"=>
  {:iata=>"NUI",
   :name=>"Nuiqsut Airport (FAA: AQT)",
   :icao=>"PAQT",
   :city=>"Nuiqsut",
   :country=>'United States', :country_code=>'US',

   :location=>"Nuiqsut, Alaska, United States"},
 "NUL"=>
  {:iata=>"NUL",
   :name=>"Nulato Airport",
   :icao=>"PANU",
   :city=>"Nulato",
   :country=>'United States', :country_code=>'US',

   :location=>"Nulato, Alaska, United States"},
 "NUN"=>
  {:iata=>"NUN",
   :name=>"NOLF Saufley",
   :icao=>"KNUN",
   :city=>"Pensacola",
   :country=>'United States', :country_code=>'US',

   :location=>"Pensacola, Florida, United States"},
 "NUP"=>
  {:iata=>"NUP",
   :name=>"Nunapitchuk Airport (FAA: 16A)",
   :icao=>"",
   :city=>"Nunapitchuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Nunapitchuk, Alaska, United States"},
 "NUQ"=>
  {:iata=>"NUQ",
   :name=>"Moffett Federal Airfield",
   :icao=>"KNUQ",
   :city=>"Mountain View",
   :country=>'United States', :country_code=>'US',

   :location=>"Mountain View, California, United States"},
 "NUW"=>
  {:iata=>"NUW",
   :name=>"NAS Whidbey Island (Ault Field)",
   :icao=>"KNUW",
   :city=>"Oak Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Oak Harbor, Washington, United States"},
 "NVD"=>
  {:iata=>"NVD",
   :name=>"Nevada Municipal Airport",
   :icao=>"KNVD",
   :city=>"Nevada",
   :country=>'United States', :country_code=>'US',

   :location=>"Nevada, Missouri, United States"},
 "NWH"=>
  {:iata=>"NWH",
   :name=>"Parlin Field (FAA: 2B3)",
   :icao=>"",
   :city=>"Newport",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport, New Hampshire, United States"},
 "NXX"=>
  {:iata=>"NXX",
   :name=>"NAS JRB Willow Grove",
   :icao=>"KNXX",
   :city=>"Willow Grove",
   :country=>'United States', :country_code=>'US',

   :location=>"Willow Grove, Pennsylvania, United States"},
 "NYC"=>
  {:iata=>"NYC",
   :name=>"All Airports",
   :icao=>"",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "NYG"=>
  {:iata=>"NYG",
   :name=>"MCAF Quantico (Turner Field)",
   :icao=>"KNYG",
   :city=>"Quantico",
   :country=>'United States', :country_code=>'US',

   :location=>"Quantico, Virginia, United States"},
 "NZC"=>
  {:iata=>"NZC",
   :name=>"Maria Reiche Neuman Airport",
   :icao=>"SPZA",
   :city=>"Nazca",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Nazca, Ica Region, Peru"},
 "NZJ"=>
  {:iata=>"NZJ",
   :name=>"MCAS El Toro",
   :icao=>"KNZJ",
   :city=>"Santa Ana",
   :country=>'United States', :country_code=>'US',

   :location=>"Santa Ana, California, United States"},
 "NZY"=>
  {:iata=>"NZY",
   :name=>"NAS North Island (Halsey Field)",
   :icao=>"KNZY",
   :city=>"San Diego",
   :country=>'United States', :country_code=>'US',

   :location=>"San Diego, California, United States"}}

end
