# encoding: UTF-8
def airp_5
  {"DVK"=>
  {:iata=>"DVK",
   :name=>"Diavik Airport",
   :city=>"Diavik",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Diavik, Canada"},
 "DUQ"=>
  {:iata=>"DUQ",
   :name=>"Duncan Airport",
   :icao=>"",
   :city=>"Duncan",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Duncan, British Columbia, Canada"},
 "DGF"=>
  {:iata=>"DGF",
   :name=>"Douglas Lake Airport",
   :city=>"Douglas Lake",
   :icao=>"CAL3",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Douglas Lake, Canada"},
 "DAS"=>
  {:iata=>"DAS",
   :name=>"Great Bear Lake Airport",
   :city=>"Great Bear Lake",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Great Bear Lake, Canada"},
 "DUN"=>
  {:iata=>"DUN",
   :name=>"Dundas Airport",
   :icao=>"BGDU",
   :city=>"Dundas",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Dundas, Greenland"},
 "DGO"=>
  {:iata=>"DGO",
   :name=>"General Guadalupe Victoria International Airport",
   :icao=>"MMDO",
   :city=>"Durango",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Durango, Durango, Mexico"},
 "DGW"=>
  {:iata=>"DGW",
   :name=>"Converse County Airport",
   :icao=>"KDGW",
   :city=>"Douglas",
   :country=>'United States', :country_code=>'US',

   :location=>"Douglas, Wyoming, United States"},
 "DTI"=>
  {:iata=>"DTI",
   :name=>"Diamantina Airport",
   :city=>"Diamantina",
   :icao=>"SNDT",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Diamantina, Brazil"},
 "DOU"=>
  {:iata=>"DOU",
   :name=>"Dourados Airport",
   :icao=>"SSDO",
   :city=>"Dourados",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Dourados, Minas Gerais, Brazil"},
 "DMT"=>
  {:iata=>"DMT",
   :name=>"Diamantino Airport",
   :icao=>"SWDM",
   :city=>"Diamantino",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Diamantino, Mato Grosso, Brazil"},
 "DNO"=>
  {:iata=>"DNO",
   :name=>"Dianopolis Airport",
   :icao=>"SWDN",
   :city=>"Dianopolis",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Dianopolis, Tocantins, Brazil"},
 "DIQ"=>
  {:iata=>"DIQ",
   :name=>"Divinópolis Airport",
   :icao=>"SNDV",
   :city=>"Divinópolis",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Divinópolis, Minas Gerais, Brazil"},
 "DZI"=>
  {:iata=>"DZI",
   :name=>"Codazzi Airport",
   :icao=>"",
   :city=>"Codazzi",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Codazzi, Colombia"},
 "DOE"=>
  {:iata=>"DOE",
   :name=>"Djumu Airport",
   :icao=>"",
   :city=>"Djumu (Djoemoe)",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Djumu (Djoemoe), Suriname"},
 "DRJ"=>
  {:iata=>"DRJ",
   :name=>"Drietabbetje Airport",
   :icao=>"SMDA",
   :city=>"Drietabbetje",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Drietabbetje, Suriname"},
 "DZO"=>
  {:iata=>"DZO",
   :name=>"Santa Bernardina International Airport",
   :icao=>"SUDU",
   :city=>"Durazno",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Durazno, Durazno, Uruguay"},
 "DCN"=>
  {:iata=>"DCN",
   :name=>"RAAF Base Curtin",
   :city=>"Curtin",
   :icao=>"YCIN",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Curtin, Australia"},
 "DRW"=>
  {:iata=>"DRW",
   :name=>"Darwin International Airport",
   :icao=>"YPDN",
   :city=>"Darwin",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Darwin, Northern Territory, Australia"},
 "DPO"=>
  {:iata=>"DPO",
   :name=>"Devonport Airport",
   :icao=>"YDPO",
   :city=>"Devonport",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Devonport, Tasmania, Australia"},
 "DMD"=>
  {:iata=>"DMD",
   :name=>"Doomadgee Mission Airport",
   :icao=>"YDMG",
   :city=>"Doomadgee Mission",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Doomadgee Mission, Queensland, Australia"},
 "DBO"=>
  {:iata=>"DBO",
   :name=>"Dubbo Airport",
   :icao=>"YSDU",
   :city=>"Dubbo",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dubbo, New South Wales, Australia"},
 "DGE"=>
  {:iata=>"DGE",
   :name=>"Mudgee Airport",
   :icao=>"YMDG",
   :city=>"Mudgee",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mudgee, New South Wales, Australia"},
 "DBY"=>
  {:iata=>"DBY",
   :name=>"Dalby Airport",
   :icao=>"YDAY",
   :city=>"Dalby",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dalby, Queensland, Australia"},
 "DGD"=>
  {:iata=>"DGD",
   :name=>"Dalgaranga Airport",
   :city=>"Dalgaranga",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dalgaranga, Australia"},
 "DVR"=>
  {:iata=>"DVR",
   :name=>"Daly River Airport",
   :icao=>"",
   :city=>"Daly River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Daly River, Northern Territory, Australia"},
 "DYW"=>
  {:iata=>"DYW",
   :name=>"Daly Waters Airport",
   :icao=>"",
   :city=>"Daly Waters",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Daly Waters, Northern Territory, Australia"},
 "DAJ"=>
  {:iata=>"DAJ",
   :name=>"Dauan Airport",
   :icao=>"",
   :city=>"Dauan",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dauan, Queensland, Australia"},
 "DVP"=>
  {:iata=>"DVP",
   :name=>"Davenport Downs Airport",
   :icao=>"YDPD",
   :city=>"Davenport Downs Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Davenport Downs Station, Queensland, Australia"},
 "DDI"=>
  {:iata=>"DDI",
   :name=>"Daydream Island Resort Airport",
   :icao=>"",
   :city=>"Daydream Island Resort",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Daydream Island Resort, Queensland, Australia"},
 "DLV"=>
  {:iata=>"DLV",
   :name=>"Delissaville Airport",
   :icao=>"YDLV",
   :city=>"Delissaville",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Delissaville, Northern Territory, Australia"},
 "DDN"=>
  {:iata=>"DDN",
   :name=>"Delta Downs Airport",
   :icao=>"YDLT",
   :city=>"Delta Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Delta Downs, Queensland, Australia"},
 "DNM"=>
  {:iata=>"DNM",
   :name=>"Denham Airport",
   :icao=>"",
   :city=>"Denham",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Denham, Western Australia, Australia"},
 "DNQ"=>
  {:iata=>"DNQ",
   :name=>"Deniliquin Airport",
   :icao=>"YDLQ",
   :city=>"Deniliquin",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Deniliquin, New South Wales, Australia"},
 "DRB"=>
  {:iata=>"DRB",
   :name=>"Derby Airport",
   :icao=>"YDBY",
   :city=>"Derby",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Derby, Western Australia, Australia"},
 "DYM"=>
  {:iata=>"DYM",
   :name=>"Diamantina Lakes Airport",
   :icao=>"",
   :city=>"Diamantina Lakes Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Diamantina Lakes Station, Queensland, Australia"},
 "DRN"=>
  {:iata=>"DRN",
   :name=>"Dirranbandi Airport",
   :icao=>"YDBI",
   :city=>"Dirranbandi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dirranbandi, Queensland, Australia"},
 "DXD"=>
  {:iata=>"DXD",
   :name=>"Dixie Airport",
   :icao=>"YDIX",
   :city=>"Dixie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dixie, Queensland, Australia"},
 "DKV"=>
  {:iata=>"DKV",
   :name=>"Docker River Airport",
   :icao=>"YDVR",
   :city=>"Docker River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Docker River, Northern Territory, Australia"},
 "DOX"=>
  {:iata=>"DOX",
   :name=>"Dongara Airport",
   :icao=>"YDRA",
   :city=>"Dongara",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dongara, Western Australia, Australia"},
 "DNG"=>
  {:iata=>"DNG",
   :name=>"Doongan Airport",
   :city=>"Doongan",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Doongan, Australia"},
 "DRD"=>
  {:iata=>"DRD",
   :name=>"Dorunda Airport",
   :icao=>"YDOR",
   :city=>"Dorunda",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dorunda, Queensland, Australia"},
 "DFP"=>
  {:iata=>"DFP",
   :name=>"Drumduff Airport",
   :icao=>"",
   :city=>"Drumduff",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Drumduff, Queensland, Australia"},
 "DRY"=>
  {:iata=>"DRY",
   :name=>"Drysdale River Airport",
   :city=>"Drysdale River",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Drysdale River, Australia"},
 "DLK"=>
  {:iata=>"DLK",
   :name=>"Dulkaninna Airport",
   :icao=>"YDLK",
   :city=>"Dulkaninna",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dulkaninna, South Australia, Australia"},
 "DNB"=>
  {:iata=>"DNB",
   :name=>"Dunbar Airport",
   :icao=>"YDBR",
   :city=>"Dunbar",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dunbar, Queensland, Australia"},
 "DKI"=>
  {:iata=>"DKI",
   :name=>"Dunk Island Airport",
   :icao=>"YDKI",
   :city=>"Dunk Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dunk Island, Queensland, Australia"},
 "DHD"=>
  {:iata=>"DHD",
   :name=>"Durham Downs Airport",
   :icao=>"YDRH",
   :city=>"Durham Downs Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Durham Downs Station, Queensland, Australia"},
 "DRR"=>
  {:iata=>"DRR",
   :name=>"Durrie Airport",
   :icao=>"YDRI",
   :city=>"Durrie Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Durrie Station, Queensland, Australia"},
 "DYA"=>
  {:iata=>"DYA",
   :name=>"Dysart Airport",
   :icao=>"YDYS",
   :city=>"Dysart",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dysart, Queensland, Australia"},
 "DIL"=>
  {:iata=>"DIL",
   :name=>"Presidente Nicolau Lobato International Airport",
   :icao=>"WPDL",
   :city=>"Dili",
   :country=>"East Timor (Timor-Leste)",
   :country_code=>"TL",
   :location=>"Dili, East Timor (Timor-Leste)"},
 "DUD"=>
  {:iata=>"DUD",
   :name=>"Dunedin Airport",
   :icao=>"NZDN",
   :city=>"Dunedin",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Dunedin, Otago, New Zealand"},
 "DGR"=>
  {:iata=>"DGR",
   :name=>"Dargaville Aerodrome",
   :icao=>"NZDA",
   :city=>"Dargaville",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Dargaville, New Zealand"},
 "DLY"=>
  {:iata=>"DLY",
   :name=>"Dillon's Bay Airport",
   :icao=>"NVVD",
   :city=>"Dillon's Bay",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Dillon's Bay, Erromango, Taféa, Vanuatu"},
 "DCT"=>
  {:iata=>"DCT",
   :name=>"Duncan Town Airport",
   :icao=>"MYRD",
   :city=>"Duncan Town",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Duncan Town, Ragged Island, Bahamas"},
 "DCF"=>
  {:iata=>"DCF",
   :name=>"Canefield Airport",
   :icao=>"TDCF",
   :city=>"Canefield",
   :country=>'Dominica', :country_code=>'DM',
   :location=>"Canefield, Dominica"},
 "DOM"=>
  {:iata=>"DOM",
   :name=>"Melville Hall Airport",
   :icao=>"TDPD",
   :city=>"Melville Hall (near Roseau)",
   :country=>'Dominica', :country_code=>'DM',
   :location=>"Melville Hall (near Roseau), Dominica"},
 "DSD"=>
  {:iata=>"DSD",
   :name=>"Grande Anse Airport",
   :icao=>"TFFA",
   :city=>"Grande Anse",
   :country=>'Guadeloupe', :country_code=>'GP',
   :location=>"Grande Anse, La Desirade, Guadeloupe"},
 "DDP"=>
  {:iata=>"DDP",
   :name=>"Dorado Beach Airport",
   :icao=>"",
   :city=>"Dorado",
   :country=>"Puerto Rico",
:country_code=>"PR",
   :location=>"Dorado, Puerto Rico"},
 "DJG"=>
  {:iata=>"DJG",
   :name=>"Tiska Airport",
   :icao=>"DAAJ",
   :city=>"Djanet",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Djanet, Algeria"},
 "DRC"=>
  {:iata=>"DRC",
   :name=>"Dirico Airport",
   :icao=>"",
   :city=>"Dirico",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Dirico, Angola"},
 "DUE"=>
  {:iata=>"DUE",
   :name=>"Dundo Airport",
   :icao=>"FNDU",
   :city=>"Dundo",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Dundo, Angola"},
 "DJA"=>
  {:iata=>"DJA",
   :name=>"Djougou Airport",
   :icao=>"DBBD",
   :city=>"Djougou",
   :country=>'Benin', :country_code=>'BJ',
   :location=>"Djougou, Benin"},
 "DGU"=>
  {:iata=>"DGU",
   :name=>"Dedougou Airport",
   :icao=>"DFOD",
   :city=>"Dédougou",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Dédougou, Burkina Faso"},
 "DIP"=>
  {:iata=>"DIP",
   :name=>"Diapaga Airport",
   :icao=>"DFED",
   :city=>"Diapaga",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Diapaga, Burkina Faso"},
 "DOR"=>
  {:iata=>"DOR",
   :name=>"Dori Airport",
   :icao=>"DFEE",
   :city=>"Dori",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Dori, Burkina Faso"},
 "DLA"=>
  {:iata=>"DLA",
   :name=>"Douala Airport",
   :icao=>"FKKD",
   :city=>"Douala",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Douala, Cameroon"},
 "DSC"=>
  {:iata=>"DSC",
   :name=>"Dschang Airport",
   :icao=>"FKKS",
   :city=>"Dschang",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Dschang, Cameroon"},
 "DJM"=>
  {:iata=>"DJM",
   :name=>"Djambala Airport",
   :icao=>"FCBD",
   :city=>"Djambala",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Djambala, Republic of Congo"},
 "DIS"=>
  {:iata=>"DIS",
   :name=>"Dolisie Airport",
   :icao=>"FCPL",
   :city=>"Dolisie",
   :country=>'Republic of Congo', :country_code=>'CD',
   :location=>"Dolisie, Republic of Congo"},
 "DJO"=>
  {:iata=>"DJO",
   :name=>"Daloa Airport",
   :icao=>"DIDL",
   :city=>"Daloa",
   :country=>"Côte d'Ivoire (Ivory Coast)", :country_code=>'CI',
   :location=>"Daloa, Côte d'Ivoire (Ivory Coast)"},
 "DNC"=>
  {:iata=>"DNC",
   :name=>"Danane Airport",
   :icao=>"",
   :city=>"Danane",
   :country=>"Côte d'Ivoire (Ivory Coast)", :country_code=>'CI',
   :location=>"Danane, Côte d'Ivoire (Ivory Coast)"},
 "DIM"=>
  {:iata=>"DIM",
   :name=>"Dimbokro Airport",
   :icao=>"DIDK",
   :city=>"Dimbokro",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Dimbokro, Côte d'Ivoire"},
 "DIV"=>
  {:iata=>"DIV",
   :name=>"Divo Airport",
   :icao=>"DIDV",
   :city=>"Divo",
   :country=>"Côte d'Ivoire (Ivory Coast)", :country_code=>'CI',
   :location=>"Divo, Côte d'Ivoire (Ivory Coast)"},
 "DIR"=>
  {:iata=>"DIR",
   :name=>"Aba Tenna Dejazmach Yilma International Airport",
   :icao=>"HADR",
   :city=>"Dire Dawa",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Dire Dawa, Ethiopia"},
 "DBM"=>
  {:iata=>"DBM",
   :name=>"Debre Marcos Airport",
   :icao=>"HADM",
   :city=>"Debre Marcos",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Debre Marcos, Ethiopia"},
 "DBT"=>
  {:iata=>"DBT",
   :name=>"Debre Tabor Airport",
   :icao=>"HADT",
   :city=>"Debre Tabor",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Debre Tabor, Ethiopia"},
 "DGC"=>
  {:iata=>"DGC",
   :name=>"Degahbur Airport",
   :icao=>"",
   :city=>"Degahbur",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Degahbur, Ethiopia"},
 "DEM"=>
  {:iata=>"DEM",
   :name=>"Dembidolo Airport",
   :icao=>"HADD",
   :city=>"Dembidolo",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Dembidolo, Ethiopia"},
 "DSE"=>
  {:iata=>"DSE",
   :name=>"Combolcha Airport",
   :icao=>"HADC",
   :city=>"Dessie / Kombolcha",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Dessie / Kombolcha, Ethiopia"},
 "DNF"=>
  {:iata=>"DNF",
   :name=>"Martubah Airport",
   :icao=>"",
   :city=>"Derna",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Derna, Libya"},
 "DVD"=>
  {:iata=>"DVD",
   :name=>"Andavadoaka Airport",
   :icao=>"",
   :city=>"Andavadoaka",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>
    "Andavadoaka, Toliara province, Atsimo-Andrefana region, Madagascar"},
 "DIE"=>
  {:iata=>"DIE",
   :name=>"Arrachart Airport",
   :icao=>"FMNA",
   :city=>"Antsiranana",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Antsiranana, Madagascar"},
 "DWB"=>
  {:iata=>"DWB",
   :name=>"Soalala Airport",
   :icao=>"FMNO",
   :city=>"Soalala",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Soalala, Madagascar"},
 "DOA"=>
  {:iata=>"DOA",
   :name=>"Doany Airport",
   :icao=>"",
   :city=>"Doany",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Doany, Madagascar"},
 "DWA"=>
  {:iata=>"DWA",
   :name=>"Dwangwa Airport",
   :icao=>"FWDW",
   :city=>"Dwangwa",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Dwangwa, Malawi"},
 "DZA"=>
  {:iata=>"DZA",
   :name=>"Dzaoudzi Pamandzi International Airport",
   :icao=>"FMCZ",
   :city=>"Dzaoudzi",
   :country=>'Mayotte', :country_code=>'YT',
   :location=>"Dzaoudzi, Mayotte"},
 "DKA"=>
  {:iata=>"DKA",
   :name=>"Katsina Airport",
   :city=>"Katsina",
   :icao=>"",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Katsina, Nigeria"},
 "DKR"=>
  {:iata=>"DKR",
   :name=>"Léopold Sédar Senghor International Airport",
   :icao=>"GOOY",
   :city=>"Dakar",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Dakar, Senegal"},
 "DEI"=>
  {:iata=>"DEI",
   :name=>"Denis Island Airport",
   :icao=>"FSSD",
   :city=>"Denis Island",
   :country=>'Seychelles', :country_code=>'SC',
   :location=>"Denis Island, Seychelles"},
 "DES"=>
  {:iata=>"DES",
   :name=>"Desroches Airport",
   :icao=>"FSDR",
   :city=>"Desroches Island",
   :country=>'Seychelles', :country_code=>'SC',
   :location=>"Desroches Island, Seychelles"},
 "DSL"=>
  {:iata=>"DSL",
   :name=>"Daru Airport",
   :icao=>"",
   :city=>"Daru",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Daru, Sierra Leone"},
 "DUR"=>
  {:iata=>"DUR",
   :name=>"King Shaka International Airport",
   :icao=>"FALE",
   :city=>"Durban",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Durban, KwaZulu-Natal, South Africa"},
 "DUK"=>
  {:iata=>"DUK",
   :name=>"Dukuduk Airport",
   :icao=>"FADK",
   :city=>"Dukuduk",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Dukuduk, South Africa"},
 "DOG"=>
  {:iata=>"DOG",
   :name=>"Dongola Airport",
   :icao=>"HSDN",
   :city=>"Dongola",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Dongola, Sudan"},
 "DNX"=>
  {:iata=>"DNX",
   :name=>"Galegu Airport",
   :icao=>"HSGG",
   :city=>"Dinder",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Dinder, Sudan"},
 "DNI"=>
  {:iata=>"DNI",
   :name=>"Wad Medani Airport",
   :icao=>"HSWD",
   :city=>"Wad Medani",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Wad Medani, Sudan"},
 "DIC"=>
  {:iata=>"DIC",
   :name=>"City Heliport",
   :icao=>"WPDH",
   :city=>"Dili",
   :country=>"East Timor (Timor-Leste)",
   :country_code=>"TL",
   :location=>"Dili, East Timor (Timor-Leste)"},
 "DJE"=>
  {:iata=>"DJE",
   :name=>"Zarzis Airport",
   :icao=>"DTTJ",
   :city=>"Djerba",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Djerba, Tunisia"},
 "DAR"=>
  {:iata=>"DAR",
   :name=>"Julius Nyerere International Airport",
   :icao=>"HTDA",
   :city=>"Dar es Salaam",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Dar es Salaam, Tanzania"},
 "DOD"=>
  {:iata=>"DOD",
   :name=>"Dodoma International Airport",
   :icao=>"HTDO",
   :city=>"Dodoma",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Dodoma, Tanzania"},
 "DBV"=>
  {:iata=>"DBV",
   :name=>"Dubrovnik Airport",
   :icao=>"LDDU",
   :city=>"Dubrovnik",
   :country=>'Croatia', :country_code=>'HR',
   :location=>"Dubrovnik, Dubrovnik-Neretva County, Croatia"},
 "DCM"=>
  {:iata=>"DCM",
   :name=>"Castres-Mazamet Airport",
   :icao=>"LFCK",
   :city=>"Castres",
   :country=>'France', :country_code=>'FR',
   :location=>"Castres, France"},
 "DOL"=>
  {:iata=>"DOL",
   :name=>"Deauville Saint-Gatien Airport",
   :icao=>"LFRG",
   :city=>"Deauville",
   :country=>'France', :country_code=>'FR',
   :location=>"Deauville, France"},
 "DIJ"=>
  {:iata=>"DIJ",
   :name=>"Dijon-Bourgogne Airport",
   :icao=>"LFSD",
   :city=>"Dijon",
   :country=>'France', :country_code=>'FR',
   :location=>"Dijon, France"},
 "DNR"=>
  {:iata=>"DNR",
   :name=>"Dinard - Pleurtuit - Saint-Malo Airport",
   :icao=>"LFRD",
   :city=>"Dinard",
   :country=>'France', :country_code=>'FR',
   :location=>"Dinard, France"},
 "DLE"=>
  {:iata=>"DLE",
   :name=>"Dôle-Tavaux Airport",
   :icao=>"LFGJ",
   :city=>"Dole",
   :country=>'France', :country_code=>'FR',
   :location=>"Dole, France"},
 "DXA"=>
  {:iata=>"DXA",
   :name=>"Deux Alpes Airport",
   :city=>"Deux Alpes",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Deux Alpes, France"},
 "DPE"=>
  {:iata=>"DPE",
   :name=>"St-Aubin Airport",
   :icao=>"LFAB",
   :city=>"Dieppe",
   :country=>'France', :country_code=>'FR',
   :location=>"Dieppe, France"},
 "DLP"=>
  {:iata=>"DLP",
   :name=>"Disneyland Resort Paris Airport",
   :icao=>"",
   :city=>"Disneyland Resort Paris",
   :country=>'France', :country_code=>'FR',
   :location=>"Disneyland Resort Paris, Paris, France"},
 "DUS"=>
  {:iata=>"DUS",
   :name=>"Düsseldorf International Airport",
   :icao=>"EDDL",
   :city=>"Düsseldorf",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Düsseldorf, North Rhine-Westphalia, Germany"},
 "DTM"=>
  {:iata=>"DTM",
   :name=>"Dortmund Airport",
   :icao=>"EDLW",
   :city=>"Dortmund",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Dortmund, North Rhine-Westphalia, Germany"},
 "DRS"=>
  {:iata=>"DRS",
   :name=>"Dresden Airport",
   :icao=>"EDDC",
   :city=>"Dresden",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Dresden, Germany"},
 "DRM"=>
  {:iata=>"DRM",
   :name=>"Drama Airport",
   :icao=>"",
   :city=>"Drama",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Drama, Greece"},
 "DEB"=>
  {:iata=>"DEB",
   :name=>"Debrecen Airport",
   :icao=>"LHDC",
   :city=>"Debrecen",
   :country=>'Hungary', :country_code=>'HU',
   :location=>"Debrecen, Hajdú-Bihar, Hungary"},
 "DJU"=>
  {:iata=>"DJU",
   :name=>"Djúpivogur Airport",
   :icao=>"BIDV",
   :city=>"Djúpivogur",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Djúpivogur, Iceland"},
 "DUB"=>
  {:iata=>"DUB",
   :name=>"Dublin Airport",
   :icao=>"EIDW",
   :city=>"Dublin",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Dublin, Ireland"},
 "DCI"=>
  {:iata=>"DCI",
   :name=>"Rafsu Decimomannu Airport",
   :icao=>"LIED",
   :city=>"Sardinia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Sardinia, Italy"},
 "DGP"=>
  {:iata=>"DGP",
   :name=>"Daugavpils International Airport",
   :icao=>"EVDA",
   :city=>"Daugavpils",
   :country=>'Latvia', :country_code=>'LV',
   :location=>"Daugavpils, Latvia"},
 "DHR"=>
  {:iata=>"DHR",
   :name=>"De Kooy Airport",
   :icao=>"EHKD",
   :city=>"Den Helder",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Den Helder, Netherlands"},
 "DLD"=>
  {:iata=>"DLD",
   :name=>"Dagali Airport",
   :city=>"Geilo",
   :icao=>"ENDI",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Geilo, Norway"},
 "DVA"=>
  {:iata=>"DVA",
   :name=>"Deva Airport",
   :icao=>"LRDV",
   :city=>"Deva",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Deva, Romania"},
 "DME"=>
  {:iata=>"DME",
   :name=>"Domodedovo International Airport",
   :icao=>"UUDD",
   :city=>"Moscow",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Moscow, Russia"},
 "DYR"=>
  {:iata=>"DYR",
   :name=>"Ugolny Airport",
   :icao=>"UHMA",
   :city=>"Anadyr",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Anadyr, Russia"},
 "DPT"=>
  {:iata=>"DPT",
   :name=>"Deputatsky Airport",
   :icao=>"",
   :city=>"Deputatsky",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Deputatsky, Sakha Republic, Russia"},
 "DEE"=>
  {:iata=>"DEE",
   :name=>"Mendeleyevo Airport",
   :city=>"Kunashir Island",
   :icao=>"UHSM",
   :country=>'Federation', :country_code=>'',
   :location=>"Kunashir Island, Federation"},
 "DKS"=>
  {:iata=>"DKS",
   :name=>"Dikson Airport",
   :icao=>"UODD",
   :city=>"Dikson",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Dikson, Russia"},
 "DLM"=>
  {:iata=>"DLM",
   :name=>"Dalaman Airport",
   :icao=>"LTBS",
   :city=>"Muğla",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Muğla, Turkey"},
 "DNZ"=>
  {:iata=>"DNZ",
   :name=>"Çardak Airport",
   :icao=>"LTAY",
   :city=>"Denizli",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Denizli, Turkey"},
 "DIY"=>
  {:iata=>"DIY",
   :name=>"Diyarbakır Airport",
   :icao=>"LTCC",
   :city=>"Diyarbakır",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Diyarbakır, Turkey"},
 "DNK"=>
  {:iata=>"DNK",
   :name=>"Dnipropetrovsk International Airport",
   :icao=>"UKDD",
   :city=>"Dnipropetrovsk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Dnipropetrovsk, Ukraine"},
 "DOK"=>
  {:iata=>"DOK",
   :name=>"Donetsk International Airport",
   :icao=>"UKCC",
   :city=>"Donetsk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Donetsk, Ukraine"},
 "DSA"=>
  {:iata=>"DSA",
   :name=>"Robin Hood Airport Doncaster Sheffield",
   :icao=>"EGCN",
   :city=>"Doncaster",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Doncaster, England, United Kingdom"},
 "DND"=>
  {:iata=>"DND",
   :name=>"Dundee Airport",
   :icao=>"EGPN",
   :city=>"Dundee",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Dundee, Scotland, United Kingdom"},
 "DOC"=>
  {:iata=>"DOC",
   :name=>"Dornoch Airport",
   :icao=>"",
   :city=>"Dornoch",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Dornoch, Scotland, United Kingdom"},
 "DAZ"=>
  {:iata=>"DAZ",
   :name=>"Darwaz Airport",
   :icao=>"OADZ",
   :city=>"Darwaz",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Darwaz, Badakhshan, Afghanistan"},
 "DAC"=>
  {:iata=>"DAC",
   :name=>"Shahjalal International Airport",
   :icao=>"VGHS",
   :city=>"Dhaka",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Dhaka, Bangladesh"},
 "DLC"=>
  {:iata=>"DLC",
   :name=>"Dalian Zhoushuizi International Airport",
   :icao=>"ZYTL",
   :city=>"Dalian",
   :country=>'China', :country_code=>'CN',
   :location=>"Dalian, Liaoning, China"},
 "DLU"=>
  {:iata=>"DLU",
   :name=>"Dali Airport",
   :icao=>"ZPDL",
   :city=>"Dali",
   :country=>'China', :country_code=>'CN',
   :location=>"Dali, Yunnan, China"},
 "DDG"=>
  {:iata=>"DDG",
   :name=>"Dandong Langtou Airport",
   :icao=>"ZYDD",
   :city=>"Dandong",
   :country=>'China', :country_code=>'CN',
   :location=>"Dandong, China"},
 "DCY"=>
  {:iata=>"DCY",
   :name=>"Daocheng Yading Airport",
   :icao=>"",
   :city=>"Daocheng",
   :country=>'China', :country_code=>'CN',
   :location=>"Daocheng, Sichuan, China"},
 "DQA"=>
  {:iata=>"DQA",
   :name=>"Daqing Sartu Airport",
   :icao=>"ZYDQ",
   :city=>"Daqing",
   :country=>'China', :country_code=>'CN',
   :location=>"Daqing, Heilongjiang, China"},
 "DAT"=>
  {:iata=>"DAT",
   :name=>"Datong Yungang Airport",
   :icao=>"ZBDT",
   :city=>"Datong",
   :country=>'China', :country_code=>'CN',
   :location=>"Datong, Shanxi, China"},
 "DAX"=>
  {:iata=>"DAX",
   :name=>"Dazhou Heshi Airport",
   :icao=>"ZUDX",
   :city=>"Dazhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Dazhou, Sichuan, China"},
 "DYG"=>
  {:iata=>"DYG",
   :name=>"Zhangjiajie Hehua Airport (formerly Dayong Airport)",
   :icao=>"ZGDY",
   :city=>"Zhangjiajie",
   :country=>'China', :country_code=>'CN',
   :location=>"Zhangjiajie, Hunan, China"},
 "DIG"=>
  {:iata=>"DIG",
   :name=>"Dêqên Shangri-La Airport",
   :icao=>"ZPDQ",
   :city=>"Shangri-La",
   :country=>'China', :country_code=>'CN',
   :location=>"Shangri-La, Yunnan, China"},
 "DSN"=>
  {:iata=>"DSN",
   :name=>"Ordos Ejin Horo Airport",
   :icao=>"ZBDS",
   :city=>"Ordos",
   :country=>'China', :country_code=>'CN',
   :location=>"Ordos, Inner Mongolia, China"},
 "DOY"=>
  {:iata=>"DOY",
   :name=>"Dongying Airport",
   :city=>"Dongying",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Dongying, China"},
 "DNH"=>
  {:iata=>"DNH",
   :name=>"Dunhuang Airport",
   :icao=>"ZLDH",
   :city=>"Dunhuang",
   :country=>'China', :country_code=>'CN',
   :location=>"Dunhuang, Gansu, China"},
 "DZU"=>
  {:iata=>"DZU",
   :name=>"Dazu Airport",
   :icao=>"ZUDZ",
   :city=>"Dazu District",
   :country=>'China', :country_code=>'CN',
   :location=>"Dazu District, China"},
 "DEL"=>
  {:iata=>"DEL",
   :name=>"Indira Gandhi International Airport",
   :icao=>"VIDP",
   :city=>"Delhi",
   :country=>"India",
:country_code=>"IN",
   :location=>"Delhi, India"},
 "DED"=>
  {:iata=>"DED",
   :name=>"Dehradun Airport",
   :icao=>"VIDN",
   :city=>"Dehradun",
   :country=>"India",
:country_code=>"IN",
   :location=>"Dehradun, Uttarakhand, India"},
 "DHM"=>
  {:iata=>"DHM",
   :name=>"Gaggal Airport",
   :icao=>"VIGG",
   :city=>"Kangra",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kangra, Himachal Pradesh, India"},
 "DIB"=>
  {:iata=>"DIB",
   :name=>"Dibrugarh Airport (Chabua Airport)",
   :icao=>"VEMN",
   :city=>"Dibrugarh",
   :country=>"India",
:country_code=>"IN",
   :location=>"Dibrugarh, India"},
 "DMU"=>
  {:iata=>"DMU",
   :name=>"Dimapur Airport",
   :icao=>"VEMR",
   :city=>"Dimapur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Dimapur, India"},
 "DIU"=>
  {:iata=>"DIU",
   :name=>"Diu Airport",
   :icao=>"",
   :city=>"Diu",
   :country=>"India",
:country_code=>"IN",
   :location=>"Diu, India"},
 "DAE"=>
  {:iata=>"DAE",
   :name=>"Daparizo Airport",
   :city=>"Daparizo",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Daparizo, India"},
 "DAI"=>
  {:iata=>"DAI",
   :name=>"Darjeeling Airport",
   :city=>"Darjeeling",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Darjeeling, India"},
 "DEP"=>
  {:iata=>"DEP",
   :name=>"Daporijo Airport",
   :icao=>"VEDZ",
   :city=>"Daporijo",
   :country=>"India",
:country_code=>"IN",
   :location=>"Daporijo, Arunachal Pradesh, India"},
 "DBD"=>
  {:iata=>"DBD",
   :name=>"Dhanbad Airport",
   :icao=>"VEDB",
   :city=>"Dhanbad",
   :country=>"India",
:country_code=>"IN",
   :location=>"Dhanbad, India"},
 "DPS"=>
  {:iata=>"DPS",
   :name=>"Ngurah Rai International Airport",
   :icao=>"WADD",
   :city=>"Denpasar",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Denpasar, Bali, Indonesia"},
 "DTD"=>
  {:iata=>"DTD",
   :name=>"Datadawai Airport",
   :icao=>"WALJ",
   :city=>"Long Pahangai",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Long Pahangai, West Kutai Regency, East Kalimantan, Indonesia"},
 "DOB"=>
  {:iata=>"DOB",
   :name=>"Dobo Airport",
   :icao=>"WAPD",
   :city=>"Dobo",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Dobo, Wamar Island, Indonesia"},
 "DJB"=>
  {:iata=>"DJB",
   :name=>"Sultan Thaha Airport (Sultan Taha Syarifudn Airport)",
   :icao=>"WIPA",
   :city=>"Jambi",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Jambi, Indonesia"},
 "DJJ"=>
  {:iata=>"DJJ",
   :name=>"Sentani Airport",
   :icao=>"WAJJ",
   :city=>"Jayapura",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Jayapura, Indonesia"},
 "DRH"=>
  {:iata=>"DRH",
   :name=>"Dabra Airport",
   :icao=>"",
   :city=>"Dabra",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Dabra, Indonesia"},
 "DUM"=>
  {:iata=>"DUM",
   :name=>"Pinang Kampai Airport",
   :icao=>"WIBD",
   :city=>"Dumai",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Dumai, Sumatra, Indonesia"},
 "DEF"=>
  {:iata=>"DEF",
   :name=>"Dezful Airport",
   :icao=>"OIAD",
   :city=>"Dezful",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Dezful, Iran"},
 "DNA"=>
  {:iata=>"DNA",
   :name=>"Kadena Air Base",
   :icao=>"RODN",
   :city=>"Okinawa Prefecture",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Okinawa Prefecture, Japan"},
 "DMB"=>
  {:iata=>"DMB",
   :name=>"Taraz Airport (Zhambul Airport)",
   :icao=>"UADD",
   :city=>"Taraz (formerly Dzhambul and Aulie-Ata)",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Taraz (formerly Dzhambul and Aulie-Ata), Kazakhstan"},
 "DZN"=>
  {:iata=>"DZN",
   :name=>"Zhezkazgan Airport",
   :icao=>"UAKD",
   :city=>"Jezkazgan",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Jezkazgan, Kazakhstan"},
 "DRV"=>
  {:iata=>"DRV",
   :name=>"Dharavandhoo AIrport",
   :city=>"Dharavandhoo Island",
   :icao=>"VRMD",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Dharavandhoo Island, Maldives"},
 "DLZ"=>
  {:iata=>"DLZ",
   :name=>"Omnogobi Airport",
   :icao=>"ZMDZ",
   :city=>"Dalanzadgad",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Dalanzadgad, Mongolia"},
 "DHI"=>
  {:iata=>"DHI",
   :name=>"Dhangarhi Airport",
   :icao=>"VNDH",
   :city=>"Dhangarhi",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Dhangarhi, Nepal"},
 "DOP"=>
  {:iata=>"DOP",
   :name=>"Dolpa Airport",
   :icao=>"VNDP",
   :city=>"Dolpa",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Dolpa, Nepal"},
 "DNP"=>
  {:iata=>"DNP",
   :name=>"Tulsipur Airport (Dang Airport)",
   :icao=>"VNDG",
   :city=>"Dang",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Dang, Nepal"},
 "DAP"=>
  {:iata=>"DAP",
   :name=>"Darchula Airport",
   :icao=>"VNDL",
   :city=>"Darchula",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Darchula, Nepal"},
 "DDU"=>
  {:iata=>"DDU",
   :name=>"Dadu Airport",
   :icao=>"OPDD",
   :city=>"Dadu",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Dadu, Pakistan"},
 "DBA"=>
  {:iata=>"DBA",
   :name=>"Dalbandin Airport",
   :icao=>"OPDB",
   :city=>"Dalbandin",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Dalbandin, Pakistan"},
 "DEA"=>
  {:iata=>"DEA",
   :name=>"Dera Ghazi Khan Airport",
   :icao=>"OPDG",
   :city=>"Dera Ghazi Khan",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Dera Ghazi Khan, Pakistan"},
 "DSK"=>
  {:iata=>"DSK",
   :name=>"Dera Ismail Khan Airport",
   :icao=>"OPDI",
   :city=>"Dera Ismail Khan",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Dera Ismail Khan, Pakistan"},
 "DAU"=>
  {:iata=>"DAU",
   :name=>"Daru Airport",
   :icao=>"AYDU",
   :city=>"Daru",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Daru, Western Province, Papua New Guinea"},
 "DAO"=>
  {:iata=>"DAO",
   :name=>"Dabo Airport",
   :city=>"Dabo",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Dabo, Guinea"},
 "DAF"=>
  {:iata=>"DAF",
   :name=>"Daup Airport",
   :icao=>"",
   :city=>"Daup",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Daup, Papua New Guinea"},
 "DBP"=>
  {:iata=>"DBP",
   :name=>"Debepare Airport",
   :icao=>"AYDB",
   :city=>"Debepare",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Debepare, Papua New Guinea"},
 "DER"=>
  {:iata=>"DER",
   :name=>"Derim Airport",
   :icao=>"AYDE",
   :city=>"Derim",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Derim, Papua New Guinea"},
 "DNU"=>
  {:iata=>"DNU",
   :name=>"Dinangat Airport",
   :icao=>"AYDN",
   :city=>"Dinangat",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dinangat, Papua New Guinea"},
 "DOS"=>
  {:iata=>"DOS",
   :name=>"Dios Airport",
   :icao=>"",
   :city=>"Dios",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dios, Papua New Guinea"},
 "DDM"=>
  {:iata=>"DDM",
   :name=>"Dodoima Airport",
   :icao=>"",
   :city=>"Dodoima",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dodoima, Papua New Guinea"},
 "DOI"=>
  {:iata=>"DOI",
   :name=>"Doini Airport",
   :icao=>"AYDO",
   :city=>"Doini",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Doini, Papua New Guinea"},
 "DOO"=>
  {:iata=>"DOO",
   :name=>"Dorobisoro Airport",
   :icao=>"AYDR",
   :city=>"Dorobisoro",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dorobisoro, Papua New Guinea"},
 "DPU"=>
  {:iata=>"DPU",
   :name=>"Dumpu Airport",
   :icao=>"",
   :city=>"Dumpu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dumpu, Papua New Guinea"},
 "DVO"=>
  {:iata=>"DVO",
   :name=>"Francisco Bangoy International Airport",
   :icao=>"RPMD",
   :city=>"Davao City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Davao City, Philippines"},
 "DPL"=>
  {:iata=>"DPL",
   :name=>"Dipolog Airport",
   :icao=>"RPMG",
   :city=>"Dipolog City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Dipolog City, Zamboanga del Norte, Philippines"},
 "DGT"=>
  {:iata=>"DGT",
   :name=>"Sibulan (Dumaguete) Airport",
   :icao=>"RPVD",
   :city=>"Sibulan",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Sibulan, Negros Oriental, Philippines"},
 "DTE"=>
  {:iata=>"DTE",
   :name=>"Bagasbas Airport",
   :icao=>"RPUD",
   :city=>"Daet",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Daet, Camarines Norte, Philippines"},
 "DSG"=>
  {:iata=>"DSG",
   :name=>"Dilasag Airport",
   :icao=>"",
   :city=>"Dilasag",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Dilasag, Aurora, Philippines"},
 "DGM"=>
  {:iata=>"DGM",
   :name=>"Dandugama Water Aerodrome",
   :city=>"Colombo",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Colombo, Lanka"},
 "DWO"=>
  {:iata=>"DWO",
   :name=>"Diyawanna Oya Seaplane Base",
   :city=>"Colombo",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Colombo, Lanka"},
 "DIW"=>
  {:iata=>"DIW",
   :name=>"Mawella Lagoon Airport",
   :city=>"Dikwella",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Dikwella, Lanka"},
 "DBU"=>
  {:iata=>"DBU",
   :name=>"Dambula Oya Tank Airport",
   :city=>"Dambula",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Dambula, Lanka"},
 "DYU"=>
  {:iata=>"DYU",
   :name=>"Dushanbe Airport",
   :icao=>"UTDD",
   :city=>"Dushanbe",
   :country=>'Tajikistan', :country_code=>'TJ',
   :location=>"Dushanbe, Tajikistan"},
 "DMK"=>
  {:iata=>"DMK",
   :name=>"Don Mueang International Airport",
   :icao=>"VTBD",
   :city=>"Don Muang",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Don Muang, Bangkok, Thailand"},
 "DAD"=>
  {:iata=>"DAD",
   :name=>"Da Nang International Airport",
   :icao=>"VVDN",
   :city=>"Da Nang",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Da Nang, Vietnam"},
 "DLI"=>
  {:iata=>"DLI",
   :name=>"Lien Khuong Airport",
   :icao=>"VVDL",
   :city=>"Da Lat",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Da Lat, Lam Dong, Vietnam"},
 "DIN"=>
  {:iata=>"DIN",
   :name=>"Dien Bien Phu Airport",
   :icao=>"VVDB",
   :city=>"Dien Bien Phu",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Dien Bien Phu, Vietnam"},
 "DGA"=>
  {:iata=>"DGA",
   :name=>"Dangriga Airport",
   :icao=>"",
   :city=>"Dangriga",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Dangriga, Belize"},
 "DRK"=>
  {:iata=>"DRK",
   :name=>"Drake Bay Airport",
   :icao=>"MRDK",
   :city=>"Drake Bay",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Drake Bay, Costa Rica"},
 "DON"=>
  {:iata=>"DON",
   :name=>"Dos Lagunas Airport",
   :icao=>"",
   :city=>"Dos Lagunas",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Dos Lagunas, El Petén, Guatemala"},
 "DAV"=>
  {:iata=>"DAV",
   :name=>"Enrique Malek International Airport",
   :icao=>"MPDA",
   :city=>"David",
   :country=>'Panama', :country_code=>'PA',
   :location=>"David, Chiriquí Province, Panama"},
 "DBB"=>
  {:iata=>"DBB",
   :name=>"Al Alamain International Airport",
   :city=>"Dabaa",
   :icao=>"HEAL",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Dabaa, Egypt"},
 "DAK"=>
  {:iata=>"DAK",
   :name=>"Dakhla Oasis Airport",
   :icao=>"HEDK",
   :city=>"Dakhla Oasis",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Dakhla Oasis, Egypt"},
 "DOH"=>
  {:iata=>"DOH",
   :name=>"Hamad International Airport",
   :icao=>"OTHH",
   :city=>"Doha",
   :country=>'Qatar', :country_code=>'QA',
   :location=>"Doha, Qatar"},
 "DAH"=>
  {:iata=>"DAH",
   :name=>"Dathina Airport",
   :icao=>"",
   :city=>"Dathina",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Dathina, Yemen"},
 "DHL"=>
  {:iata=>"DHL",
   :name=>"Dhala Airport",
   :icao=>"ODAL",
   :city=>"Dhala",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Dhala, Yemen"},
 "DMR"=>
  {:iata=>"DMR",
   :name=>"Dhamar Airport",
   :icao=>"",
   :city=>"Dhamar",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Dhamar, Yemen"},
 "DMM"=>
  {:iata=>"DMM",
   :name=>"King Fahd International Airport",
   :icao=>"OEDF",
   :city=>"Dammam",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Dammam, Saudi Arabia"},
 "DWD"=>
  {:iata=>"DWD",
   :name=>"Dawadmi Airport",
   :icao=>"OEDW",
   :city=>"Dawadmi",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Dawadmi, Saudi Arabia"},
 "DHA"=>
  {:iata=>"DHA",
   :name=>"Dhahran International Airport",
   :icao=>"OEDR",
   :city=>"Dhahran",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Dhahran, Saudi Arabia"},
 "DAM"=>
  {:iata=>"DAM",
   :name=>"Damascus International Airport",
   :icao=>"OSDI",
   :city=>"Damascus",
   :country=>'Syria', :country_code=>'SY',
   :location=>"Damascus, Syria"},
 "DEZ"=>
  {:iata=>"DEZ",
   :name=>"Deir ez-Zor Airport (Al Jafrah Airport)",
   :icao=>"OSDZ",
   :city=>"Deir ez-Zor (Deirezzor)",
   :country=>'Syria', :country_code=>'SY',
   :location=>"Deir ez-Zor (Deirezzor), Syria"},
 "DXB"=>
  {:iata=>"DXB",
   :name=>"Dubai International Airport",
   :icao=>"OMDB",
   :city=>"Dubai",
   :country=>"United Arab Emirates",
:country_code=>"AE",
   :location=>"Dubai, United Arab Emirates"},
 "DWC"=>
  {:iata=>"DWC",
   :name=>"Al Maktoum International Airport",
   :icao=>"OMDW",
   :city=>"Jebel Ali",
   :country=>"United Arab Emirates",
:country_code=>"AE",
   :location=>"Jebel Ali, Dubai, United Arab Emirates"},
 "DHF"=>
  {:iata=>"DHF",
   :name=>"Al Dhafra Airport",
   :icao=>"OMAM",
   :city=>"Al Dhafra",
   :country=>"United Arab Emirates",
:country_code=>"AE",
   :location=>"Al Dhafra, United Arab Emirates"},
 "DAA"=>
  {:iata=>"DAA",
   :name=>"Davison Army Airfield",
   :icao=>"KDAA",
   :city=>"Fort Belvoir",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Belvoir, Virginia, United States"},
 "DAB"=>
  {:iata=>"DAB",
   :name=>"Daytona Beach International Airport",
   :icao=>"KDAB",
   :city=>"Daytona Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Daytona Beach, Florida, United States"},
 "DAG"=>
  {:iata=>"DAG",
   :name=>"Barstow-Daggett Airport",
   :icao=>"KDAG",
   :city=>"Daggett",
   :country=>'United States', :country_code=>'US',

   :location=>"Daggett, California, United States"},
 "DAL"=>
  {:iata=>"DAL",
   :name=>"Dallas Love Field",
   :icao=>"KDAL",
   :city=>"Dallas",
   :country=>'United States', :country_code=>'US',

   :location=>"Dallas, Texas, United States"},
 "DAN"=>
  {:iata=>"DAN",
   :name=>"Danville Regional Airport",
   :icao=>"KDAN",
   :city=>"Danville",
   :country=>'United States', :country_code=>'US',

   :location=>"Danville, Virginia, United States"},
 "DAY"=>
  {:iata=>"DAY",
   :name=>"Dayton International Airport",
   :icao=>"KDAY",
   :city=>"Dayton",
   :country=>'United States', :country_code=>'US',

   :location=>"Dayton, Ohio, United States"},
 "DBN"=>
  {:iata=>"DBN",
   :name=>"W. H. 'Bud' Barron Airport",
   :icao=>"KDBN",
   :city=>"Dublin",
   :country=>'United States', :country_code=>'US',

   :location=>"Dublin, Georgia, United States"},
 "DBQ"=>
  {:iata=>"DBQ",
   :name=>"Dubuque Regional Airport",
   :icao=>"KDBQ",
   :city=>"Dubuque",
   :country=>'United States', :country_code=>'US',

   :location=>"Dubuque, Iowa, United States"},
 "DBS"=>
  {:iata=>"DBS",
   :name=>"Dubois Municipal Airport (FAA: U41)",
   :icao=>"",
   :city=>"Dubois",
   :country=>'United States', :country_code=>'US',

   :location=>"Dubois, Idaho, United States"},
 "DCA"=>
  {:iata=>"DCA",
   :name=>"Ronald Reagan Washington National Airport",
   :icao=>"KDCA",
   :city=>"Arlington County",
   :country=>'United States', :country_code=>'US',

   :location=>
    "Arlington County, Virginia (near Washington, D.C.), United States"},
 "DCK"=>
  {:iata=>"DCK",
   :name=>"Dahl Creek Airport",
   :icao=>"",
   :city=>"Dahl Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Dahl Creek, Alaska, United States"},
 "DCR"=>
  {:iata=>"DCR",
   :name=>"Decatur Hi-Way Airport (closed)",
   :icao=>"KDCR",
   :city=>"Decatur",
   :country=>'United States', :country_code=>'US',

   :location=>"Decatur, Indiana, United States"},
 "DCU"=>
  {:iata=>"DCU",
   :name=>"Pryor Field Regional Airport",
   :icao=>"KDCU",
   :city=>"Decatur",
   :country=>'United States', :country_code=>'US',

   :location=>"Decatur, Alabama, United States"},
 "DDC"=>
  {:iata=>"DDC",
   :name=>"Dodge City Regional Airport",
   :icao=>"KDDC",
   :city=>"Dodge City",
   :country=>'United States', :country_code=>'US',

   :location=>"Dodge City, Kansas, United States"},
 "DEC"=>
  {:iata=>"DEC",
   :name=>"Decatur Airport",
   :icao=>"KDEC",
   :city=>"Decatur",
   :country=>'United States', :country_code=>'US',

   :location=>"Decatur, Illinois, United States"},
 "DEH"=>
  {:iata=>"DEH",
   :name=>"Decorah Municipal Airport",
   :icao=>"KDEH",
   :city=>"Decorah",
   :country=>'United States', :country_code=>'US',

   :location=>"Decorah, Iowa, United States"},
 "DEN"=>
  {:iata=>"DEN",
   :name=>"Denver International Airport (succeeded Stapleton Airport)",
   :icao=>"KDEN",
   :city=>"Denver",
   :country=>'United States', :country_code=>'US',

   :location=>"Denver, Colorado, United States"},
 "DET"=>
  {:iata=>"DET",
   :name=>"Coleman A. Young International Airport",
   :icao=>"KDET",
   :city=>"Detroit",
   :country=>'United States', :country_code=>'US',

   :location=>"Detroit, Michigan, United States"},
 "DFI"=>
  {:iata=>"DFI",
   :name=>"Defiance Memorial Airport",
   :icao=>"KDFI",
   :city=>"Defiance",
   :country=>'United States', :country_code=>'US',

   :location=>"Defiance, Ohio, United States"},
 "DFW"=>
  {:iata=>"DFW",
   :name=>"Dallas/Fort Worth International Airport",
   :icao=>"KDFW",
   :city=>"Dallas and Fort Worth",
   :country=>'United States', :country_code=>'US',

   :location=>"Dallas and Fort Worth, Texas, United States"},
 "DGL"=>
  {:iata=>"DGL",
   :name=>"Douglas Municipal Airport",
   :icao=>"KDGL",
   :city=>"Douglas",
   :country=>'United States', :country_code=>'US',

   :location=>"Douglas, Arizona, United States"},
 "DGN"=>
  {:iata=>"DGN",
   :name=>"Dahlgren Naval Surface Warfare Center (FAA: NDY)",
   :icao=>"KNDY",
   :city=>"Dahlgren",
   :country=>'United States', :country_code=>'US',

   :location=>"Dahlgren, Virginia, United States"},
 "DGX"=>
  {:iata=>"DGX",
   :name=>"MOD St Athan",
   :icao=>"EGDX",
   :city=>"St Athan",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"St Athan, Wales, United Kingdom"},
 "DHN"=>
  {:iata=>"DHN",
   :name=>"Dothan Regional Airport",
   :icao=>"KDHN",
   :city=>"Dothan",
   :country=>'United States', :country_code=>'US',

   :location=>"Dothan, Alabama, United States"},
 "DHT"=>
  {:iata=>"DHT",
   :name=>"Dalhart Municipal Airport",
   :icao=>"KDHT",
   :city=>"Dalhart",
   :country=>'United States', :country_code=>'US',

   :location=>"Dalhart, Texas, United States"},
 "DIK"=>
  {:iata=>"DIK",
   :name=>"Theodore Roosevelt Regional Airport",
   :icao=>"KDIK",
   :city=>"Dickinson",
   :country=>'United States', :country_code=>'US',

   :location=>"Dickinson, North Dakota, United States"},
 "DIO"=>
  {:iata=>"DIO",
   :name=>"Diomede Heliport (FAA: DM2)",
   :icao=>"",
   :city=>"Diomede",
   :country=>'United States', :country_code=>'US',

   :location=>"Diomede, Alaska, United States"},
 "DJN"=>
  {:iata=>"DJN",
   :name=>"Delta Junction Airport (FAA: D66)",
   :icao=>"",
   :city=>"Delta Junction",
   :country=>'United States', :country_code=>'US',

   :location=>"Delta Junction, Alaska, United States"},
 "DJR"=>
  {:iata=>"DJR",
   :name=>"Dajarra Airport",
   :icao=>"YDAJ",
   :city=>"Dajarra",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Dajarra, Queensland, Australia"},
 "DKK"=>
  {:iata=>"DKK",
   :name=>"Chautauqua County/Dunkirk Airport",
   :icao=>"KDKK",
   :city=>"Dunkirk",
   :country=>'United States', :country_code=>'US',

   :location=>"Dunkirk, New York, United States"},
 "DLB"=>
  {:iata=>"DLB",
   :name=>"Dalbertis Airport",
   :icao=>"",
   :city=>"Dalbertis",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Dalbertis, Papua New Guinea"},
 "DLF"=>
  {:iata=>"DLF",
   :name=>"Laughlin Air Force Base",
   :icao=>"KDLF",
   :city=>"Del Rio",
   :country=>'United States', :country_code=>'US',

   :location=>"Del Rio, Texas, United States"},
 "DLG"=>
  {:iata=>"DLG",
   :name=>"Dillingham Airport",
   :icao=>"PADL",
   :city=>"Dillingham",
   :country=>'United States', :country_code=>'US',

   :location=>"Dillingham, Alaska, United States"},
 "DLH"=>
  {:iata=>"DLH",
   :name=>"Duluth International Airport",
   :icao=>"KDLH",
   :city=>"Duluth",
   :country=>'United States', :country_code=>'US',

   :location=>"Duluth, Minnesota, United States"},
 "DLL"=>
  {:iata=>"DLL",
   :name=>"Dillon County Airport (FAA: DLC)",
   :icao=>"KDLC",
   :city=>"Dillon",
   :country=>'United States', :country_code=>'US',

   :location=>"Dillon, South Carolina, United States"},
 "DLN"=>
  {:iata=>"DLN",
   :name=>"Dillon Airport",
   :icao=>"KDLN",
   :city=>"Dillon",
   :country=>'United States', :country_code=>'US',

   :location=>"Dillon, Montana, United States"},
 "DLS"=>
  {:iata=>"DLS",
   :name=>"Columbia Gorge Regional Airport (The Dalles Municipal Airport)",
   :icao=>"KDLS",
   :city=>"The Dalles",
   :country=>'United States', :country_code=>'US',

   :location=>"The Dalles, Oregon, United States"},
 "DMA"=>
  {:iata=>"DMA",
   :name=>"Davis Monthan Air Force Base",
   :icao=>"KDMA",
   :city=>"Tucson",
   :country=>'United States', :country_code=>'US',

   :location=>"Tucson, Arizona, United States"},
 "DMN"=>
  {:iata=>"DMN",
   :name=>"Deming Municipal Airport",
   :icao=>"KDMN",
   :city=>"Deming",
   :country=>'United States', :country_code=>'US',

   :location=>"Deming, New Mexico, United States"},
 "DMO"=>
  {:iata=>"DMO",
   :name=>"Sedalia Memorial Airport",
   :icao=>"KDMO",
   :city=>"Sedalia",
   :country=>'United States', :country_code=>'US',

   :location=>"Sedalia, Missouri, United States"},
 "DNL"=>
  {:iata=>"DNL",
   :name=>"Daniel Field",
   :icao=>"KDNL",
   :city=>"Augusta",
   :country=>'United States', :country_code=>'US',

   :location=>"Augusta, Georgia, United States"},
 "DNN"=>
  {:iata=>"DNN",
   :name=>"Dalton Municipal Airport",
   :icao=>"KDNN",
   :city=>"Dalton",
   :country=>'United States', :country_code=>'US',

   :location=>"Dalton, Georgia, United States"},
 "DNS"=>
  {:iata=>"DNS",
   :name=>"Denison Municipal Airport",
   :icao=>"KDNS",
   :city=>"Denison",
   :country=>'United States', :country_code=>'US',

   :location=>"Denison, Iowa, United States"},
 "DNV"=>
  {:iata=>"DNV",
   :name=>"Vermilion County Airport",
   :icao=>"KDNV",
   :city=>"Danville",
   :country=>'United States', :country_code=>'US',

   :location=>"Danville, Illinois, United States"},
 "DOT"=>
  {:iata=>"DOT",
   :name=>"Don Torcuato International Airport (closed)",
   :icao=>"SADD",
   :city=>"Buenos Aires",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Buenos Aires, Argentina"},
 "DOV"=>
  {:iata=>"DOV",
   :name=>"Dover Air Force Base",
   :icao=>"KDOV",
   :city=>"Dover",
   :country=>'United States', :country_code=>'US',

   :location=>"Dover, Delaware, United States"},
 "DPA"=>
  {:iata=>"DPA",
   :name=>"Dupage Airport",
   :icao=>"KDPA",
   :city=>"West Chicago",
   :country=>'United States', :country_code=>'US',

   :location=>"West Chicago, Illinois, United States"},
 "DPG"=>
  {:iata=>"DPG",
   :name=>"Michael Army Airfield",
   :icao=>"KDPG",
   :city=>"Dugway Proving Ground",
   :country=>'United States', :country_code=>'US',

   :location=>"Dugway Proving Ground, Utah, United States"},
 "DQH"=>
  {:iata=>"DQH",
   :name=>"Alpine Airstrip (FAA: AK15)",
   :icao=>"PALP",
   :city=>"Deadhorse",
   :country=>'United States', :country_code=>'US',

   :location=>"Deadhorse, Alaska, United States"},
 "DRA"=>
  {:iata=>"DRA",
   :name=>"Desert Rock Airport",
   :icao=>"KDRA",
   :city=>"Mercury",
   :country=>'United States', :country_code=>'US',

   :location=>"Mercury, Nevada, United States"},
 "DRE"=>
  {:iata=>"DRE",
   :name=>"Drummond Island Airport (FAA: DRM)",
   :icao=>"KDRM",
   :city=>"Drummond Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Drummond Island, Michigan, United States"},
 "DRG"=>
  {:iata=>"DRG",
   :name=>"Deering Airport (FAA: DEE)",
   :icao=>"PADE",
   :city=>"Deering",
   :country=>'United States', :country_code=>'US',

   :location=>"Deering, Alaska, United States"},
 "DRI"=>
  {:iata=>"DRI",
   :name=>"Beauregard Regional Airport",
   :icao=>"KDRI",
   :city=>"De Ridder",
   :country=>'United States', :country_code=>'US',

   :location=>"De Ridder, Louisiana, United States"},
 "DRO"=>
  {:iata=>"DRO",
   :name=>"Durango-La Plata County Airport",
   :icao=>"KDRO",
   :city=>"Durango",
   :country=>'United States', :country_code=>'US',

   :location=>"Durango, Colorado, United States"},
 "DRT"=>
  {:iata=>"DRT",
   :name=>"Del Rio International Airport",
   :icao=>"KDRT",
   :city=>"Del Rio",
   :country=>'United States', :country_code=>'US',

   :location=>"Del Rio, Texas, United States"},
 "DRU"=>
  {:iata=>"DRU",
   :name=>"Drummond Airport (FAA: M26)",
   :icao=>"",
   :city=>"Drummond",
   :country=>'United States', :country_code=>'US',

   :location=>"Drummond, Montana, United States"},
 "DSI"=>
  {:iata=>"DSI",
   :name=>"Destin-Fort Walton Beach Airport (FAA: DTS)",
   :icao=>"KDTS",
   :city=>"Destin",
   :country=>'United States', :country_code=>'US',

   :location=>"Destin, Florida, United States"},
 "DSM"=>
  {:iata=>"DSM",
   :name=>"Des Moines International Airport",
   :icao=>"KDSM",
   :city=>"Des Moines",
   :country=>'United States', :country_code=>'US',

   :location=>"Des Moines, Iowa, United States"},
 "DSV"=>
  {:iata=>"DSV",
   :name=>"Dansville Municipal Airport",
   :icao=>"KDSV",
   :city=>"Dansville",
   :country=>'United States', :country_code=>'US',

   :location=>"Dansville, New York, United States"},
 "DTA"=>
  {:iata=>"DTA",
   :name=>"Delta Municipal Airport",
   :icao=>"KDTA",
   :city=>"Delta",
   :country=>'United States', :country_code=>'US',

   :location=>"Delta, Utah, United States"},
 "DTH"=>
  {:iata=>"DTH",
   :name=>"Death Valley National Park Airport",
   :icao=>"",
   :city=>"Death Valley",
   :country=>'United States', :country_code=>'US',

   :location=>"Death Valley, United States"},
 "DTL"=>
  {:iata=>"DTL",
   :name=>"Detroit Lakes Airport (Wething Field)",
   :icao=>"KDTL",
   :city=>"Detroit Lakes",
   :country=>'United States', :country_code=>'US',

   :location=>"Detroit Lakes, Minnesota, United States"},
 "DTN"=>
  {:iata=>"DTN",
   :name=>"Shreveport Downtown Airport",
   :icao=>"KDTN",
   :city=>"Shreveport",
   :country=>'United States', :country_code=>'US',

   :location=>"Shreveport, Louisiana, United States"},
 "DTT"=>
  {:iata=>"DTT",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Detroit",
   :country=>'United States', :country_code=>'US',

   :location=>"Detroit, Michigan, United States"},
 "DTW"=>
  {:iata=>"DTW",
   :name=>"Detroit Metropolitan Wayne County Airport",
   :icao=>"KDTW",
   :city=>"Romulus (near Detroit)",
   :country=>'United States', :country_code=>'US',

   :location=>"Romulus (near Detroit), Michigan, United States"},
 "DUA"=>
  {:iata=>"DUA",
   :name=>"Eaker Field",
   :icao=>"KDUA",
   :city=>"Durant",
   :country=>'United States', :country_code=>'US',

   :location=>"Durant, Oklahoma, United States"},
 "DUC"=>
  {:iata=>"DUC",
   :name=>"Halliburton Field",
   :icao=>"KDUC",
   :city=>"Duncan",
   :country=>'United States', :country_code=>'US',

   :location=>"Duncan, Oklahoma, United States"},
 "DUF"=>
  {:iata=>"DUF",
   :name=>"Pine Island Airport (FAA: 7NC2)",
   :icao=>"",
   :city=>"Corolla",
   :country=>'United States', :country_code=>'US',

   :location=>"Corolla, North Carolina, United States"},
 "DUG"=>
  {:iata=>"DUG",
   :name=>"Bisbee-Douglas International Airport",
   :icao=>"KDUG",
   :city=>"Bisbee/Douglas",
   :country=>'United States', :country_code=>'US',

   :location=>"Bisbee/Douglas, Arizona, United States"},
 "DUJ"=>
  {:iata=>"DUJ",
   :name=>"DuBois Regional Airport (formerly DuBois-Jefferson County Airport)",
   :icao=>"KDUJ",
   :city=>"DuBois",
   :country=>'United States', :country_code=>'US',

   :location=>"DuBois, Pennsylvania, United States"},
 "DUT"=>
  {:iata=>"DUT",
   :name=>"Unalaska Airport",
   :icao=>"PADU",
   :city=>"Unalaska",
   :country=>'United States', :country_code=>'US',

   :location=>"Unalaska, Alaska, United States"},
 "DVL"=>
  {:iata=>"DVL",
   :name=>"Devils Lake Municipal Airport",
   :icao=>"KDVL",
   :city=>"Devils Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Devils Lake, North Dakota, United States"},
 "DVN"=>
  {:iata=>"DVN",
   :name=>"Davenport Municipal Airport",
   :icao=>"KDVN",
   :city=>"Davenport",
   :country=>'United States', :country_code=>'US',

   :location=>"Davenport, Iowa, United States"},
 "DVT"=>
  {:iata=>"DVT",
   :name=>"Phoenix Deer Valley Airport",
   :icao=>"KDVT",
   :city=>"Phoenix",
   :country=>'United States', :country_code=>'US',

   :location=>"Phoenix, Arizona, United States"},
 "DWH"=>
  {:iata=>"DWH",
   :name=>"David Wayne Hooks Memorial Airport",
   :icao=>"KDWH",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "DWN"=>
  {:iata=>"DWN",
   :name=>"Downtown Airpark (FAA: OK03)",
   :icao=>"",
   :city=>"Oklahoma City",
   :country=>'United States', :country_code=>'US',

   :location=>"Oklahoma City, Oklahoma, United States"},
 "DWS"=>
  {:iata=>"DWS",
   :name=>"Walt Disney World Airport (no FAA code)",
   :icao=>"",
   :city=>"Walt Disney World / Orlando",
   :country=>"United States",
   :country_code=>'US',
   :location=>"Walt Disney World / Orlando, Florida, United States"},
 "DXR"=>
  {:iata=>"DXR",
   :name=>"Danbury Municipal Airport",
   :icao=>"KDXR",
   :city=>"Danbury",
   :country=>'United States', :country_code=>'US',

   :location=>"Danbury, Connecticut, United States"},
 "DYL"=>
  {:iata=>"DYL",
   :name=>"Doylestown Airport",
   :icao=>"KDYL",
   :city=>"Doylestown",
   :country=>'United States', :country_code=>'US',

   :location=>"Doylestown, Pennsylvania, United States"},
 "DYS"=>
  {:iata=>"DYS",
   :name=>"Dyess Air Force Base",
   :icao=>"KDYS",
   :city=>"Abilene",
   :country=>'United States', :country_code=>'US',

   :location=>"Abilene, Texas, United States"}}

end
