# encoding: UTF-8
def airp_7
  {"FSP"=>
  {:iata=>"FSP",
   :name=>"Saint Pierre Airport",
   :icao=>"LFVP",
   :city=>"Saint-Pierre",
   :country=>'France', :country_code=>'FR',
   :location=>"Saint-Pierre, Saint Pierre and Miquelon, France"},
 "FEW"=>
  {:iata=>"FEW",
   :name=>"Francis E. Warren Air Force Base",
   :icao=>"KFEW",
   :city=>"Cheyenne",
   :country=>'United States', :country_code=>'US',

   :location=>"Cheyenne, Wyoming, United States"},
 "FBR"=>
  {:iata=>"FBR",
   :name=>"Fort Bridger Airport",
   :icao=>"KFBR",
   :city=>"Fort Bridger",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Bridger, Wyoming, United States"},
 "FTE"=>
  {:iata=>"FTE",
   :name=>"Comandante Armando Tola International Airport",
   :icao=>"SAWA",
   :city=>"El Calafate",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"El Calafate, Santa Cruz Province, Argentina"},
 "FMA"=>
  {:iata=>"FMA",
   :name=>"Formosa International Airport (El Pucú Airport)",
   :icao=>"SARF",
   :city=>"Formosa",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Formosa, Argentina"},
 "FEN"=>
  {:iata=>"FEN",
   :name=>"Fernando de Noronha Airport",
   :icao=>"SBFN",
   :city=>"Fernando de Noronha",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Fernando de Noronha, Pernambuco, Brazil"},
 "FLN"=>
  {:iata=>"FLN",
   :name=>"Hercílio Luz International Airport",
   :icao=>"SBFL",
   :city=>"Florianópolis",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Florianópolis, Santa Catarina, Brazil"},
 "FBA"=>
  {:iata=>"FBA",
   :name=>"Fonte Boa Airport",
   :city=>"Fonte Boa",
   :icao=>"SWOB",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Fonte Boa, Brazil"},
 "FOR"=>
  {:iata=>"FOR",
   :name=>"Pinto Martins International Airport",
   :icao=>"SBFZ",
   :city=>"Fortaleza",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Fortaleza, Ceará, Brazil"},
 "FEJ"=>
  {:iata=>"FEJ",
   :name=>"Feijó Airport",
   :icao=>"",
   :city=>"Feijó",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Feijó, Acre, Brazil"},
 "FEC"=>
  {:iata=>"FEC",
   :name=>"João Durval Carneiro Airport",
   :icao=>"SNJD",
   :city=>"Feira de Santana",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Feira de Santana, Bahia, Brazil"},
 "FLB"=>
  {:iata=>"FLB",
   :name=>"Cangapara Airport",
   :icao=>"SNQG",
   :city=>"Floriano",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Floriano, Piauí, Brazil"},
 "FRC"=>
  {:iata=>"FRC",
   :name=>"Franca Airport",
   :icao=>"SIMK",
   :city=>"Franca",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Franca, São Paulo, Brazil"},
 "FBE"=>
  {:iata=>"FBE",
   :name=>"Francisco Beltrão Airport",
   :icao=>"SSFB",
   :city=>"Francisco Beltrao",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Francisco Beltrao, Paraná, Brazil"},
 "FDB"=>
  {:iata=>"FDB",
   :name=>"Principe Da Beira Airport",
   :city=>"Principe Da Beira",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Principe Da Beira, Brazil"},
 "FRT"=>
  {:iata=>"FRT",
   :name=>"Frutillar Airport",
   :icao=>"SCFI",
   :city=>"Frutillar",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Frutillar, Chile"},
 "FFU"=>
  {:iata=>"FFU",
   :name=>"Futaleufu Airport",
   :icao=>"SCFT",
   :city=>"Futaleufu",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Futaleufu, Chile"},
 "FLA"=>
  {:iata=>"FLA",
   :name=>"Gustavo Artunduaga Paredes Airport",
   :icao=>"SKFL",
   :city=>"Florencia",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Florencia, Caquetá, Colombia"},
 "FLM"=>
  {:iata=>"FLM",
   :name=>"Fernheim Airport (Filadelfia Airport)",
   :icao=>"SGFI",
   :city=>"Filadelfia",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Filadelfia, Paraguay"},
 "FTI"=>
  {:iata=>"FTI",
   :name=>"Fitiuta Airport (FAA: FAQ)",
   :icao=>"NSFQ",
   :city=>"Fiti‘uta",
   :country=>'United States', :country_code=>'US',

   :location=>"Fiti‘uta, American Samoa, United States"},
 "FLS"=>
  {:iata=>"FLS",
   :name=>"Flinders Island Airport",
   :icao=>"YFLI",
   :city=>"Flinders Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Flinders Island, Tasmania, Australia"},
 "FLC"=>
  {:iata=>"FLC",
   :name=>"Falls Creek Airport",
   :icao=>"",
   :city=>"Falls Creek",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Falls Creek, Victoria, Australia"},
 "FIK"=>
  {:iata=>"FIK",
   :name=>"Finke Airport",
   :icao=>"YFNE",
   :city=>"Finke",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Finke, Northern Territory, Australia"},
 "FLY"=>
  {:iata=>"FLY",
   :name=>"Finley Airport",
   :icao=>"YFIL",
   :city=>"Finley",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Finley, New South Wales, Australia"},
 "FIZ"=>
  {:iata=>"FIZ",
   :name=>"Fitzroy Crossing Airport",
   :icao=>"YFTZ",
   :city=>"Fitzroy Crossing",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Fitzroy Crossing, Western Australia, Australia"},
 "FVL"=>
  {:iata=>"FVL",
   :name=>"Flora Valley Airport",
   :city=>"Flora Valley",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Flora Valley, Australia"},
 "FRB"=>
  {:iata=>"FRB",
   :name=>"Forbes Airport",
   :icao=>"YFBS",
   :city=>"Forbes",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Forbes, New South Wales, Australia"},
 "FOS"=>
  {:iata=>"FOS",
   :name=>"Forrest Airport",
   :icao=>"YFRT",
   :city=>"Forrest",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Forrest, Western Australia, Australia"},
 "FVR"=>
  {:iata=>"FVR",
   :name=>"Forrest River Airport",
   :city=>"Forrest River",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Forrest River, Australia"},
 "FOT"=>
  {:iata=>"FOT",
   :name=>"Rohnerville Airport",
   :icao=>"KFOT",
   :city=>"Fortuna",
   :country=>'United States', :country_code=>'US',

   :location=>"Fortuna, California, United States"},
 "FSL"=>
  {:iata=>"FSL",
   :name=>"Fossil Downs Airport",
   :icao=>"",
   :city=>"Fossil Downs Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Fossil Downs Station, Western Australia, Australia"},
 "FAC"=>
  {:iata=>"FAC",
   :name=>"Faaite Airport",
   :icao=>"NTKF",
   :city=>"Faaite",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Faaite, French Polynesia"},
 "FHZ"=>
  {:iata=>"FHZ",
   :name=>"Fakahina Airport",
   :icao=>"NTKH",
   :city=>"Fakahina",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Fakahina, French Polynesia"},
 "FAV"=>
  {:iata=>"FAV",
   :name=>"Fakarava Airport",
   :icao=>"NTGF",
   :city=>"Fakarava",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Fakarava, Society Islands, French Polynesia"},
 "FGU"=>
  {:iata=>"FGU",
   :name=>"Fangatau Airport",
   :icao=>"NTGB",
   :city=>"Fangatau",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Fangatau, French Polynesia"},
 "FGL"=>
  {:iata=>"FGL",
   :name=>"Fox Glacier Airport",
   :icao=>"NZFH",
   :city=>"Fox Glacier",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Fox Glacier, New Zealand"},
 "FGI"=>
  {:iata=>"FGI",
   :name=>"Fagali'i Airport",
   :icao=>"NSFI",
   :city=>"Apia",
   :country=>"Samoa",
:country_code=>"WS",
   :location=>"Apia, Samoa"},
 "FRE"=>
  {:iata=>"FRE",
   :name=>"Fera Airport (Fera/Maringe Airport)",
   :icao=>"AGGF",
   :city=>"Maringe",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Maringe, Fera Island, Isabel Province, Solomon Islands"},
 "FUN"=>
  {:iata=>"FUN",
   :name=>"Funafuti International Airport",
   :icao=>"NGFU",
   :city=>"Funafuti",
   :country=>'Tuvalu', :country_code=>'TV',
   :location=>"Funafuti, Tuvalu"},
 "FTA"=>
  {:iata=>"FTA",
   :name=>"Futuna Airport",
   :icao=>"NVVF",
   :city=>"Futuna Island",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Futuna Island, Taféa, Vanuatu"},
 "FUT"=>
  {:iata=>"FUT",
   :name=>"Pointe Vele Airport",
   :icao=>"NLWF",
   :city=>"Futuna Island",
   :country=>'Wallis and Futuna Islands', :country_code=>'WF',
   :location=>"Futuna Island, Wallis and Futuna Islands"},
 "FPO"=>
  {:iata=>"FPO",
   :name=>"Grand Bahama International Airport",
   :icao=>"MYGF",
   :city=>"Freeport",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Freeport, Grand Bahama, Bahamas"},
 "FDF"=>
  {:iata=>"FDF",
   :name=>"Martinique Aimé Césaire International Airport",
   :icao=>"TFFF",
   :city=>"Le Lamentin / Fort de France",
   :country=>'Martinique', :country_code=>'MQ',
   :location=>"Le Lamentin / Fort de France, Martinique"},
 "FAJ"=>
  {:iata=>"FAJ",
   :name=>"Diego Jimenez Torres Airport (FAA: X95)",
   :icao=>"TJFA",
   :city=>"Fajardo",
   :country=>'United States', :country_code=>'US',

   :location=>"Fajardo, Puerto Rico, United States"},
 "FRW"=>
  {:iata=>"FRW",
   :name=>"Francistown Airport",
   :icao=>"FBFT",
   :city=>"Francistown",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Francistown, Botswana"},
 "FNG"=>
  {:iata=>"FNG",
   :name=>"Fada N'gourma Airport",
   :icao=>"DFEF",
   :city=>"Fada N'gourma",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Fada N'gourma, Burkina Faso"},
 "FOM"=>
  {:iata=>"FOM",
   :name=>"Nkounja Airport",
   :icao=>"FKKM",
   :city=>"Foumban",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Foumban, Cameroon"},
 "FYT"=>
  {:iata=>"FYT",
   :name=>"Faya-Largeau Airport",
   :icao=>"FTTY",
   :city=>"Faya-Largeau",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Faya-Largeau, Chad"},
 "FTX"=>
  {:iata=>"FTX",
   :name=>"Owando Airport",
   :icao=>"FCOO",
   :city=>"Owando",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Owando, Republic of the Congo"},
 "FEK"=>
  {:iata=>"FEK",
   :name=>"Ferkessédougou Airport",
   :icao=>"DIFK",
   :city=>"Ferkessédougou",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Ferkessédougou, Côte d'Ivoire"},
 "FNH"=>
  {:iata=>"FNH",
   :name=>"Fincha Airport",
   :icao=>"HAFN",
   :city=>"Fincha",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Fincha, Ethiopia"},
 "FOU"=>
  {:iata=>"FOU",
   :name=>"Fougamou Airport",
   :icao=>"FOGF",
   :city=>"Fougamou",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Fougamou, Gabon"},
 "FIG"=>
  {:iata=>"FIG",
   :name=>"Fria Airport",
   :icao=>"GUFA",
   :city=>"Fria",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Fria, Guinea"},
 "FAA"=>
  {:iata=>"FAA",
   :name=>"Faranah Airport",
   :icao=>"GUFH",
   :city=>"Faranah",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Faranah, Guinea"},
 "FER"=>
  {:iata=>"FER",
   :name=>"Ferguson'S Gulf",
   :city=>"Kalokol",
   :icao=>"HKFG",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kalokol, Kenya"},
 "FOY"=>
  {:iata=>"FOY",
   :name=>"Foya Airport",
   :icao=>"",
   :city=>"Foya",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Foya, Liberia"},
 "FTU"=>
  {:iata=>"FTU",
   :name=>"Tôlanaro Airport (Marillac Airport)",
   :icao=>"FMSD",
   :city=>"Tôlanaro",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Tôlanaro, Madagascar"},
 "FGD"=>
  {:iata=>"FGD",
   :name=>"Fderik Airport (F'dérik Airport)",
   :icao=>"GQPF",
   :city=>"Fderik",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Fderik, Mauritania"},
 "FEZ"=>
  {:iata=>"FEZ",
   :name=>"Fes-Saïss Airport",
   :icao=>"GMFF",
   :city=>"Fes",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Fes, Morocco"},
 "FXO"=>
  {:iata=>"FXO",
   :name=>"Cuamba Airport",
   :icao=>"FQCB",
   :city=>"Cuamba",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Cuamba, Mozambique"},
 "FRK"=>
  {:iata=>"FRK",
   :name=>"Frégate Island Airport",
   :icao=>"FSSF",
   :city=>"Frégate Island",
   :country=>'Seychelles', :country_code=>'SC',
   :location=>"Frégate Island, Seychelles"},
 "FNA"=>
  {:iata=>"FNA",
   :name=>"Lungi International Airport",
   :icao=>"GFLL",
   :city=>"Freetown",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Freetown, Sierra Leone"},
 "FCB"=>
  {:iata=>"FCB",
   :name=>"Ficksburg Sentra Oes Airport",
   :icao=>"FAFB",
   :city=>"Ficksburg",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Ficksburg, South Africa"},
 "FMI"=>
  {:iata=>"FMI",
   :name=>"Kalemie Airport",
   :icao=>"FZRF",
   :city=>"Kalemie",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kalemie, Democratic Republic of the Congo"},
 "FIH"=>
  {:iata=>"FIH",
   :name=>"N'djili Airport (Kinshasa International)",
   :icao=>"FZAA",
   :city=>"Kinshasa",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kinshasa, Democratic Republic of the Congo"},
 "FKI"=>
  {:iata=>"FKI",
   :name=>"Bangoka International Airport",
   :icao=>"FZIC",
   :city=>"Kisangani",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kisangani, Democratic Republic of the Congo"},
 "FBM"=>
  {:iata=>"FBM",
   :name=>"Lubumbashi International Airport",
   :icao=>"FZQA",
   :city=>"Lubumbashi",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Lubumbashi, Democratic Republic of the Congo"},
 "FDU"=>
  {:iata=>"FDU",
   :name=>"Bandundu Airport",
   :icao=>"FZBO",
   :city=>"Bandundu",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Bandundu, Democratic Republic of the Congo"},
 "FAE"=>
  {:iata=>"FAE",
   :name=>"Vágar Airport",
   :icao=>"EKVG",
   :city=>"Sørvágur",
   :country=>'Faroe Islands', :country_code=>'FO',
   :location=>"Sørvágur, Faroe Islands"},
 "FSC"=>
  {:iata=>"FSC",
   :name=>"Sud Corse Airport",
   :icao=>"LFKF",
   :city=>"Figari",
   :country=>'France', :country_code=>'FR',
   :location=>"Figari, Corsica, France"},
 "FNI"=>
  {:iata=>"FNI",
   :name=>"Garons Airport",
   :icao=>"LFTW",
   :city=>"Nîmes-Arles-Camargue",
   :country=>'France', :country_code=>'FR',
   :location=>"Nîmes-Arles-Camargue, France"},
 "FRJ"=>
  {:iata=>"FRJ",
   :name=>"Frejus Saint-Raphael Airport",
   :icao=>"LFTU",
   :city=>"Fréjus / Saint-Raphaël",
   :country=>'France', :country_code=>'FR',
   :location=>"Fréjus / Saint-Raphaël, France"},
 "FRA"=>
  {:iata=>"FRA",
   :name=>"Frankfurt Airport",
   :icao=>"EDDF",
   :city=>"Frankfurt",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Frankfurt, Germany"},
 "FDH"=>
  {:iata=>"FDH",
   :name=>"Friedrichshafen Airport (Bodensee Airport)",
   :icao=>"EDNY",
   :city=>"Friedrichshafen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Friedrichshafen, Bodensee, Germany"},
 "FKB"=>
  {:iata=>"FKB",
   :name=>"Baden Airpark (Karlsruhe/Baden-Baden Airport)",
   :icao=>"EDSB",
   :city=>"Karlsruhe/Baden-Baden",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Karlsruhe/Baden-Baden, Baden-Württemberg, Germany"},
 "FMM"=>
  {:iata=>"FMM",
   :name=>"Allgäu Airport",
   :icao=>"EDJA",
   :city=>"Memmingen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Memmingen, Bavaria, Germany"},
 "FMO"=>
  {:iata=>"FMO",
   :name=>"Münster Osnabrück International Airport",
   :icao=>"EDDG",
   :city=>"Greven",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Greven, North Rhine-Westphalia, Germany"},
 "FCN"=>
  {:iata=>"FCN",
   :name=>"Fliegerhorst Nordholz",
   :icao=>"ETMN",
   :city=>"Nordholz",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Nordholz, Germany"},
 "FLF"=>
  {:iata=>"FLF",
   :name=>"Schäferhaus Airport",
   :icao=>"EDXF",
   :city=>"Flensburg",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Flensburg, Schleswig-Holstein, Germany"},
 "FRF"=>
  {:iata=>"FRF",
   :name=>"Oschersleben Airport",
   :icao=>"EDOL",
   :city=>"Oschersleben",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Oschersleben, Saxony-Anhalt, Germany"},
 "FRZ"=>
  {:iata=>"FRZ",
   :name=>"Fritzlar Air Base",
   :icao=>"ETHF",
   :city=>"Fritzlar",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Fritzlar, Hessen, Germany"},
 "FEL"=>
  {:iata=>"FEL",
   :name=>"Fürstenfeldbruck Air Base",
   :icao=>"ETSF",
   :city=>"Fürstenfeldbruck",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Fürstenfeldbruck, Bavaria, Germany"},
 "FNB"=>
  {:iata=>"FNB",
   :name=>"Neubrandenburg Airport",
   :icao=>"ETNU",
   :city=>"Neubrandenburg",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Neubrandenburg, Mecklenburg-Vorpommern, Germany"},
 "FAG"=>
  {:iata=>"FAG",
   :name=>"Fagurhólsmýri Airport",
   :icao=>"BIFM",
   :city=>"Fagurhólsmýri",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Fagurhólsmýri, Iceland"},
 "FAS"=>
  {:iata=>"FAS",
   :name=>"Fáskrúðsfjörður Airport",
   :icao=>"BIFF",
   :city=>"Fáskrúðsfjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Fáskrúðsfjörður, Iceland"},
 "FLI"=>
  {:iata=>"FLI",
   :name=>"Flateyri Airport",
   :icao=>"",
   :city=>"Flateyri",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Flateyri, Iceland"},
 "FCO"=>
  {:iata=>"FCO",
   :name=>"Leonardo da Vinci–Fiumicino Airport",
   :icao=>"LIRF",
   :city=>"Fiumicino (near Rome)",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Fiumicino (near Rome), Italy"},
 "FLR"=>
  {:iata=>"FLR",
   :name=>"Peretola Airport (Amerigo Vespucci Airport)",
   :icao=>"LIRQ",
   :city=>"Florence",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Florence, Italy"},
 "FOG"=>
  {:iata=>"FOG",
   :name=>"Gino Lisa Airport",
   :icao=>"LIBF",
   :city=>"Foggia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Foggia, Italy"},
 "FRL"=>
  {:iata=>"FRL",
   :name=>"Forlì \"Luigi Ridolfi\" Airport",
   :icao=>"LIPK",
   :city=>"Forlì",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Forlì, Emilia-Romagna, Italy"},
 "FRO"=>
  {:iata=>"FRO",
   :name=>"Florø Airport",
   :icao=>"ENFL",
   :city=>"Florø",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Florø, Sogn og Fjordane, Norway"},
 "FDE"=>
  {:iata=>"FDE",
   :name=>"Førde Airport, Bringeland",
   :icao=>"ENBL",
   :city=>"Førde / Bringeland",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Førde / Bringeland, Norway"},
 "FAN"=>
  {:iata=>"FAN",
   :name=>"Lista Airport",
   :icao=>"ENLI",
   :city=>"Farsund",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Farsund, Norway"},
 "FAO"=>
  {:iata=>"FAO",
   :name=>"Faro Airport",
   :icao=>"LPFR",
   :city=>"Faro",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Faro, Portugal"},
 "FLW"=>
  {:iata=>"FLW",
   :name=>"Flores Airport",
   :icao=>"LPFL",
   :city=>"Flores Island",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Flores Island, Azores, Portugal"},
 "FNC"=>
  {:iata=>"FNC",
   :name=>"Madeira Airport",
   :icao=>"LPMA",
   :city=>"Funchal",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Funchal, Madeira, Portugal"},
 "FUE"=>
  {:iata=>"FUE",
   :name=>"El Matorral Airport",
   :icao=>"GCFV",
   :city=>"Puerto del Rosario",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Puerto del Rosario, Fuerteventura, Canary Islands, Spain"},
 "FGR"=>
  {:iata=>"FGR",
   :name=>"Fuengirola Airport",
   :city=>"Fuengirola",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Fuengirola, Islands"},
 "FES"=>
  {:iata=>"FES",
   :name=>"San Fernando Airport",
   :city=>"San Fernando",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"San Fernando, Islands"},
 "FAB"=>
  {:iata=>"FAB",
   :name=>"Farnborough Airport",
   :icao=>"EGLF",
   :city=>"Farnborough",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Farnborough, United Kingdom"},
 "FZO"=>
  {:iata=>"FZO",
   :name=>"Bristol Filton Airport",
   :icao=>"EGTG",
   :city=>"Filton",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Filton, Bristol, United Kingdom"},
 "FIE"=>
  {:iata=>"FIE",
   :name=>"Fair Isle Airport",
   :icao=>"EGEF",
   :city=>"Fair Isle",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Fair Isle, Scotland, United Kingdom"},
 "FFD"=>
  {:iata=>"FFD",
   :name=>"RAF Fairford",
   :icao=>"EGVA",
   :city=>"Fairford",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Fairford, England, United Kingdom"},
 "FKH"=>
  {:iata=>"FKH",
   :name=>"Sculthorp Royal Air Force",
   :city=>"Fakenham",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Fakenham, Kingdom"},
 "FEA"=>
  {:iata=>"FEA",
   :name=>"Fetlar Airport",
   :icao=>"",
   :city=>"Fetlar",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Fetlar, Scotland, United Kingdom"},
 "FLH"=>
  {:iata=>"FLH",
   :name=>"Flotta Isle Airport",
   :icao=>"",
   :city=>"Flotta Isle",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Flotta Isle, Scotland, United Kingdom"},
 "FSS"=>
  {:iata=>"FSS",
   :name=>"RAF Kinloss",
   :icao=>"EGQK",
   :city=>"Forres",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Forres, Scotland, United Kingdom"},
 "FWM"=>
  {:iata=>"FWM",
   :name=>"Fort William Heliport",
   :icao=>"",
   :city=>"Fort William",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Fort William, Scotland, United Kingdom"},
 "FOA"=>
  {:iata=>"FOA",
   :name=>"Foula Airport",
   :icao=>"",
   :city=>"Foula",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Foula, Scotland, United Kingdom"},
 "FBD"=>
  {:iata=>"FBD",
   :name=>"Fayzabad Airport (Faizabad Airport)",
   :icao=>"OAFZ",
   :city=>"Fayzabad",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Fayzabad, Badakhshan, Afghanistan"},
 "FAH"=>
  {:iata=>"FAH",
   :name=>"Farah Airport",
   :icao=>"OAFR",
   :city=>"Farah",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Farah, Afghanistan"},
 "FOC"=>
  {:iata=>"FOC",
   :name=>"Fuzhou Changle International Airport",
   :icao=>"ZSFZ",
   :city=>"Fuzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Fuzhou, Fujian, China"},
 "FUO"=>
  {:iata=>"FUO",
   :name=>"Foshan Airport",
   :icao=>"ZGFS",
   :city=>"Foshan",
   :country=>'China', :country_code=>'CN',
   :location=>"Foshan, Guangdong, China"},
 "FUG"=>
  {:iata=>"FUG",
   :name=>"Fuyang Airport",
   :icao=>"ZSFY",
   :city=>"Fuyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Fuyang, Anhui, China"},
 "FYJ"=>
  {:iata=>"FYJ",
   :name=>"Fuyuan Airport",
   :city=>"Fuyuan County",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Fuyuan County, China"},
 "FYN"=>
  {:iata=>"FYN",
   :name=>"Fuyun Airport",
   :icao=>"ZWFY",
   :city=>"Fuyun",
   :country=>'China', :country_code=>'CN',
   :location=>"Fuyun, Xinjiang, China"},
 "FUD"=>
  {:iata=>"FUD",
   :name=>"Sui Fen He Airport",
   :city=>"Sui Fen He",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Sui Fen He, China"},
 "FNJ"=>
  {:iata=>"FNJ",
   :name=>"Pyongyang Sunan International Airport",
   :icao=>"ZKPY",
   :city=>"Pyongyang",
   :country=>'North Korea', :country_code=>'KP',
   :location=>"Pyongyang, North Korea"},
 "FKQ"=>
  {:iata=>"FKQ",
   :name=>"Fak Fak Airport",
   :icao=>"WASF",
   :city=>"Fak Fak",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Fak Fak, Irian Jaya, Indonesia"},
 "FLZ"=>
  {:iata=>"FLZ",
   :name=>"Ferdinand Lumban Tobing Airport",
   :city=>"Sibolga",
   :icao=>"WIMS",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Sibolga, Indonesia"},
 "FOO"=>
  {:iata=>"FOO",
   :name=>"Kornasoren Airport (Noemfoor Airport)",
   :icao=>"",
   :city=>"Noemfoor",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Noemfoor, Schouten Islands, Indonesia"},
 "FAZ"=>
  {:iata=>"FAZ",
   :name=>"Fasa Airport",
   :city=>"Fasa",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Fasa, Iran"},
 "FUK"=>
  {:iata=>"FUK",
   :name=>"Fukuoka Airport (Itazuke Air Base)",
   :icao=>"RJFF",
   :city=>"Fukuoka",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Fukuoka, Japan"},
 "FUJ"=>
  {:iata=>"FUJ",
   :name=>"Fukue Airport (Gotō Fukue Airport)",
   :icao=>"RJFE",
   :city=>"Gotō",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Gotō, Nagasaki, Japan"},
 "FKS"=>
  {:iata=>"FKS",
   :name=>"Fukushima Airport",
   :icao=>"RJSF",
   :city=>"Sugawa",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Sugawa, Fukushima, Japan"},
 "FSZ"=>
  {:iata=>"FSZ",
   :name=>"Mt. Fuji Shizuoka Airport",
   :icao=>"RJNS",
   :city=>"Shizuoka",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Shizuoka, Honshu, Japan"},
 "FKJ"=>
  {:iata=>"FKJ",
   :name=>"Fukui Airport",
   :icao=>"RJNF",
   :city=>"Fukui",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Fukui, Honshu, Japan"},
 "FRU"=>
  {:iata=>"FRU",
   :name=>"Manas International Airport",
   :icao=>"UAFM",
   :city=>"Bishkek",
   :country=>'Kyrgyzstan', :country_code=>'KG',
   :location=>"Bishkek, Kyrgyzstan"},
 "FVM"=>
  {:iata=>"FVM",
   :name=>"Fuvahmulah Airport",
   :icao=>"VRMF",
   :city=>"Fuvahmulah",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Fuvahmulah, Maldives"},
 "FEB"=>
  {:iata=>"FEB",
   :name=>"Sanfebagar Airport",
   :icao=>"VNSR",
   :city=>"Sanfebagar",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Sanfebagar, Nepal"},
 "FNE"=>
  {:iata=>"FNE",
   :name=>"Fane Airport",
   :icao=>"AYFA",
   :city=>"Fane",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Fane, Papua New Guinea"},
 "FRQ"=>
  {:iata=>"FRQ",
   :name=>"Feramin Airport",
   :icao=>"AYFE",
   :city=>"Feramin",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Feramin, Papua New Guinea"},
 "FIN"=>
  {:iata=>"FIN",
   :name=>"Finschhafen Airport",
   :icao=>"AYFI",
   :city=>"Finschhafen",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Finschhafen, Papua New Guinea"},
 "FAQ"=>
  {:iata=>"FAQ",
   :name=>"Frieda River Airport",
   :icao=>"AYFR",
   :city=>"Frieda River",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Frieda River, Papua New Guinea"},
 "FUB"=>
  {:iata=>"FUB",
   :name=>"Fulleborn Airport",
   :icao=>"",
   :city=>"Fulleborn",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Fulleborn, Papua New Guinea"},
 "FUM"=>
  {:iata=>"FUM",
   :name=>"Fuma Airport",
   :city=>"Fuma",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Fuma, Guinea"},
 "FEG"=>
  {:iata=>"FEG",
   :name=>"Fergana Airport",
   :icao=>"UTKF",
   :city=>"Fergana",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Fergana, Uzbekistan"},
 "FON"=>
  {:iata=>"FON",
   :name=>"La Fortuna Airport",
   :icao=>"MRAN",
   :city=>"La Fortuna",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"La Fortuna, Costa Rica"},
 "FMG"=>
  {:iata=>"FMG",
   :name=>"Flamingo Airport",
   :city=>"Flamingo",
   :icao=>"",
   :country=>'Rica', :country_code=>'',
   :location=>"Flamingo, Rica"},
 "FRS"=>
  {:iata=>"FRS",
   :name=>"Mundo Maya International Airport",
   :icao=>"MGTK",
   :city=>"Flores",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Flores, El Petén, Guatemala"},
 "FJR"=>
  {:iata=>"FJR",
   :name=>"Fujairah International Airport (cargo only)",
   :icao=>"OMFJ",
   :city=>"Fujairah",
   :country=>"United Arab Emirates",
:country_code=>"AE",
   :location=>"Fujairah, United Arab Emirates"},
 "FAF"=>
  {:iata=>"FAF",
   :name=>"Felker Army Airfield",
   :icao=>"KFAF",
   :city=>"Fort Eustis",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Eustis, Virginia, United States"},
 "FAI"=>
  {:iata=>"FAI",
   :name=>"Fairbanks International Airport",
   :icao=>"PAFA",
   :city=>"Fairbanks",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairbanks, Alaska, United States"},
 "FAK"=>
  {:iata=>"FAK",
   :name=>"False Island Seaplane Base (FAA: 2Z6)",
   :icao=>"",
   :city=>"False Island",
   :country=>'United States', :country_code=>'US',

   :location=>"False Island, Alaska, United States"},
 "FAM"=>
  {:iata=>"FAM",
   :name=>"Farmington Regional Airport",
   :icao=>"KFAM",
   :city=>"Farmington",
   :country=>'United States', :country_code=>'US',

   :location=>"Farmington, Missouri, United States"},
 "FAR"=>
  {:iata=>"FAR",
   :name=>"Hector International Airport",
   :icao=>"KFAR",
   :city=>"Fargo",
   :country=>'United States', :country_code=>'US',

   :location=>"Fargo, North Dakota, United States"},
 "FAT"=>
  {:iata=>"FAT",
   :name=>"Fresno Yosemite International Airport",
   :icao=>"KFAT",
   :city=>"Fresno",
   :country=>'United States', :country_code=>'US',

   :location=>"Fresno, California, United States"},
 "FAY"=>
  {:iata=>"FAY",
   :name=>"Fayetteville Regional Airport (Grannis Field)",
   :icao=>"KFAY",
   :city=>"Fayetteville",
   :country=>'United States', :country_code=>'US',

   :location=>"Fayetteville, North Carolina, United States"},
 "FBG"=>
  {:iata=>"FBG",
   :name=>"Simmons Army Airfield",
   :icao=>"KFBG",
   :city=>"Fort Bragg",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Bragg, North Carolina, United States"},
 "FBK"=>
  {:iata=>"FBK",
   :name=>"Wainwright Army Airfield",
   :icao=>"PAFB",
   :city=>"Fairbanks / Fort Wainwright",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairbanks / Fort Wainwright, Alaska, United States"},
 "FBL"=>
  {:iata=>"FBL",
   :name=>"Faribault Municipal Airport",
   :icao=>"KFBL",
   :city=>"Faribault",
   :country=>'United States', :country_code=>'US',

   :location=>"Faribault, Minnesota, United States"},
 "FBS"=>
  {:iata=>"FBS",
   :name=>"Friday Harbor Seaplane Base (FAA: W33)",
   :icao=>"",
   :city=>"Friday Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Friday Harbor, Washington, United States"},
 "FBU"=>
  {:iata=>"FBU",
   :name=>"Fornebu Airport (closed)",
   :icao=>"ENFB",
   :city=>"Oslo",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Oslo, Norway"},
 "FBY"=>
  {:iata=>"FBY",
   :name=>"Fairbury Municipal Airport",
   :icao=>"KFBY",
   :city=>"Fairbury",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairbury, Nebraska, United States"},
 "FCA"=>
  {:iata=>"FCA",
   :name=>"Glacier Park International Airport (FAA: GPI)",
   :icao=>"KGPI",
   :city=>"Kalispell",
   :country=>'United States', :country_code=>'US',

   :location=>"Kalispell, Montana, United States"},
 "FCH"=>
  {:iata=>"FCH",
   :name=>"Fresno Chandler Executive Airport",
   :icao=>"KFCH",
   :city=>"Fresno",
   :country=>'United States', :country_code=>'US',

   :location=>"Fresno, California, United States"},
 "FCM"=>
  {:iata=>"FCM",
   :name=>"Flying Cloud Airport",
   :icao=>"KFCM",
   :city=>"Eden Prairie",
   :country=>'United States', :country_code=>'US',

   :location=>"Eden Prairie, Minnesota, United States"},
 "FCS"=>
  {:iata=>"FCS",
   :name=>"Butts Army Airfield (Fort Carson)",
   :icao=>"KFCS",
   :city=>"Fort Carson",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Carson, Colorado, United States"},
 "FCT"=>
  {:iata=>"FCT",
   :name=>"Vagabond Army Airfield",
   :icao=>"KFCT",
   :city=>"Yakima",
   :country=>'United States', :country_code=>'US',

   :location=>"Yakima, Washington, United States"},
 "FCY"=>
  {:iata=>"FCY",
   :name=>"Forrest City Municipal Airport",
   :icao=>"KFCY",
   :city=>"Forrest City",
   :country=>'United States', :country_code=>'US',

   :location=>"Forrest City, Arkansas, United States"},
 "FDA"=>
  {:iata=>"FDA",
   :name=>"Fundación Airport",
   :icao=>"SKFU",
   :city=>"Fundación",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Fundación, Colombia"},
 "FDK"=>
  {:iata=>"FDK",
   :name=>"Frederick Municipal Airport",
   :icao=>"KFDK",
   :city=>"Frederick",
   :country=>'United States', :country_code=>'US',

   :location=>"Frederick, Maryland, United States"},
 "FDO"=>
  {:iata=>"FDO",
   :name=>"San Fernando Airport",
   :icao=>"SADF",
   :city=>"San Fernando",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Fernando, Buenos Aires, Argentina"},
 "FDR"=>
  {:iata=>"FDR",
   :name=>"Frederick Municipal Airport",
   :icao=>"KFDR",
   :city=>"Frederick",
   :country=>'United States', :country_code=>'US',

   :location=>"Frederick, Oklahoma, United States"},
 "FDY"=>
  {:iata=>"FDY",
   :name=>"Findlay Airport",
   :icao=>"KFDY",
   :city=>"Findlay",
   :country=>'United States', :country_code=>'US',

   :location=>"Findlay, Ohio, United States"},
 "FEP"=>
  {:iata=>"FEP",
   :name=>"Albertus Airport",
   :icao=>"KFEP",
   :city=>"Freeport",
   :country=>'United States', :country_code=>'US',

   :location=>"Freeport, Illinois, United States"},
 "FET"=>
  {:iata=>"FET",
   :name=>"Fremont Municipal Airport",
   :icao=>"KFET",
   :city=>"Fremont",
   :country=>'United States', :country_code=>'US',

   :location=>"Fremont, Nebraska, United States"},
 "FFA"=>
  {:iata=>"FFA",
   :name=>"First Flight Airport",
   :icao=>"KFFA",
   :city=>"Kill Devil Hills",
   :country=>'United States', :country_code=>'US',

   :location=>"Kill Devil Hills, North Carolina, United States"},
 "FFL"=>
  {:iata=>"FFL",
   :name=>"Fairfield Municipal Airport",
   :icao=>"KFFL",
   :city=>"Fairfield",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairfield, Iowa, United States"},
 "FFM"=>
  {:iata=>"FFM",
   :name=>"Fergus Falls Municipal Airport (Einar Mickelson Field)",
   :icao=>"KFFM",
   :city=>"Fergus Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Fergus Falls, Minnesota, United States"},
 "FFO"=>
  {:iata=>"FFO",
   :name=>"Wright-Patterson Air Force Base",
   :icao=>"KFFO",
   :city=>"Dayton",
   :country=>'United States', :country_code=>'US',

   :location=>"Dayton, Ohio, United States"},
 "FFT"=>
  {:iata=>"FFT",
   :name=>"Capital City Airport",
   :icao=>"KFFT",
   :city=>"Frankfort",
   :country=>'United States', :country_code=>'US',

   :location=>"Frankfort, Kentucky, United States"},
 "FHU"=>
  {:iata=>"FHU",
   :name=>"Sierra Vista Municipal Airport / Libby Army Airfield",
   :icao=>"KFHU",
   :city=>"Fort Huachuca",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Huachuca, Sierra Vista, Arizona, United States"},
 "FID"=>
  {:iata=>"FID",
   :name=>"Elizabeth Field (FAA: 0B8)",
   :icao=>"",
   :city=>"Fishers Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Fishers Island, New York, United States"},
 "FIL"=>
  {:iata=>"FIL",
   :name=>"Fillmore Municipal Airport (FAA: FOM)",
   :icao=>"KFOM",
   :city=>"Fillmore",
   :country=>'United States', :country_code=>'US',

   :location=>"Fillmore, Utah, United States"},
 "FIV"=>
  {:iata=>"FIV",
   :name=>"Five Finger Coast Guard Heliport (FAA: 2AK3)",
   :icao=>"",
   :city=>"Five Finger",
   :country=>'United States', :country_code=>'US',

   :location=>"Five Finger, Alaska, United States"},
 "FKL"=>
  {:iata=>"FKL",
   :name=>"Venango Regional Airport (Chess Lamberton Field)",
   :icao=>"KFKL",
   :city=>"Franklin",
   :country=>'United States', :country_code=>'US',

   :location=>"Franklin, Pennsylvania, United States"},
 "FKN"=>
  {:iata=>"FKN",
   :name=>"Franklin Municipal Airport (John Beverly Rose Field)",
   :icao=>"KFKN",
   :city=>"Franklin",
   :country=>'United States', :country_code=>'US',

   :location=>"Franklin, Virginia, United States"},
 "FLD"=>
  {:iata=>"FLD",
   :name=>"Fond du Lac County Airport",
   :icao=>"KFLD",
   :city=>"Fond du Lac",
   :country=>'United States', :country_code=>'US',

   :location=>"Fond du Lac, Wisconsin, United States"},
 "FLE"=>
  {:iata=>"FLE",
   :name=>"Fort Lee Army Airfield (FAA: VA35)",
   :icao=>"",
   :city=>"Fort Lee",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Lee, Virginia, United States"},
 "FLG"=>
  {:iata=>"FLG",
   :name=>"Flagstaff Pulliam Airport",
   :icao=>"KFLG",
   :city=>"Flagstaff",
   :country=>'United States', :country_code=>'US',

   :location=>"Flagstaff, Arizona, United States"},
 "FLL"=>
  {:iata=>"FLL",
   :name=>"Fort Lauderdale–Hollywood International Airport",
   :icao=>"KFLL",
   :city=>"Fort Lauderdale / Hollywood",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Lauderdale / Hollywood, Florida, United States"},
 "FLO"=>
  {:iata=>"FLO",
   :name=>"Florence Regional Airport",
   :icao=>"KFLO",
   :city=>"Florence",
   :country=>'United States', :country_code=>'US',

   :location=>"Florence, South Carolina, United States"},
 "FLP"=>
  {:iata=>"FLP",
   :name=>"Marion County Regional Airport",
   :icao=>"KFLP",
   :city=>"Flippin",
   :country=>'United States', :country_code=>'US',

   :location=>"Flippin, Arkansas, United States"},
 "FLT"=>
  {:iata=>"FLT",
   :name=>"Flat Airport",
   :icao=>"",
   :city=>"Flat",
   :country=>'United States', :country_code=>'US',

   :location=>"Flat, Alaska, United States"},
 "FLU"=>
  {:iata=>"FLU",
   :name=>"Flushing Airport",
   :icao=>"KFLU",
   :city=>"Flushing",
   :country=>'United States', :country_code=>'US',

   :location=>"Flushing, New York, United States"},
 "FLV"=>
  {:iata=>"FLV",
   :name=>"Sherman Army Airfield",
   :icao=>"KFLV",
   :city=>"Fort Leavenworth",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Leavenworth, Kansas, United States"},
 "FLX"=>
  {:iata=>"FLX",
   :name=>"Fallon Municipal Airport",
   :icao=>"KFLX",
   :city=>"Fallon",
   :country=>'United States', :country_code=>'US',

   :location=>"Fallon, Nevada, United States"},
 "FMC"=>
  {:iata=>"FMC",
   :name=>"Five Mile Airport (FAA: FVM)",
   :icao=>"PAFV",
   :city=>"Five Mile",
   :country=>'United States', :country_code=>'US',

   :location=>"Five Mile, Alaska, United States"},
 "FME"=>
  {:iata=>"FME",
   :name=>"Tipton Airport (Fort Meade)",
   :icao=>"KFME",
   :city=>"Odenton",
   :country=>'United States', :country_code=>'US',

   :location=>"Odenton, Maryland, United States"},
 "FMH"=>
  {:iata=>"FMH",
   :name=>"Otis ANGB (Cape Cod CGAS)",
   :icao=>"KFMH",
   :city=>"Falmouth",
   :country=>'United States', :country_code=>'US',

   :location=>"Falmouth, Massachusetts, United States"},
 "FMN"=>
  {:iata=>"FMN",
   :name=>"Four Corners Regional Airport",
   :icao=>"KFMN",
   :city=>"Farmington",
   :country=>'United States', :country_code=>'US',

   :location=>"Farmington, New Mexico, United States"},
 "FMS"=>
  {:iata=>"FMS",
   :name=>"Fort Madison Municipal Airport (FAA: FSW)",
   :icao=>"KFSW",
   :city=>"Fort Madison",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Madison, Iowa, United States"},
 "FMY"=>
  {:iata=>"FMY",
   :name=>"Page Field",
   :icao=>"KFMY",
   :city=>"Fort Myers",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Myers, Florida, United States"},
 "FNL"=>
  {:iata=>"FNL",
   :name=>"Fort Collins-Loveland Municipal Airport",
   :icao=>"KFNL",
   :city=>"Fort Collins/Loveland",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Collins/Loveland, Colorado, United States"},
 "FNR"=>
  {:iata=>"FNR",
   :name=>"Funter Bay Seaplane Base",
   :icao=>"PANR",
   :city=>"Funter Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Funter Bay, Alaska, United States"},
 "FNT"=>
  {:iata=>"FNT",
   :name=>"Bishop International Airport",
   :icao=>"KFNT",
   :city=>"Flint",
   :country=>'United States', :country_code=>'US',

   :location=>"Flint, Michigan, United States"},
 "FOB"=>
  {:iata=>"FOB",
   :name=>"Fort Bragg Airport (FAA: 82CL)",
   :icao=>"",
   :city=>"Fort Bragg",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Bragg, California, United States"},
 "FOD"=>
  {:iata=>"FOD",
   :name=>"Fort Dodge Regional Airport",
   :icao=>"KFOD",
   :city=>"Fort Dodge",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Dodge, Iowa, United States"},
 "FOE"=>
  {:iata=>"FOE",
   :name=>"Forbes Field",
   :icao=>"KFOE",
   :city=>"Topeka",
   :country=>'United States', :country_code=>'US',

   :location=>"Topeka, Kansas, United States"},
 "FOK"=>
  {:iata=>"FOK",
   :name=>"Francis S. Gabreski Airport",
   :icao=>"KFOK",
   :city=>"Westhampton Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Westhampton Beach, New York, United States"},
 "FOP"=>
  {:iata=>"FOP",
   :name=>"Morris Army Airfield (FAA: 65GA)",
   :icao=>"",
   :city=>"Fort Gillem",
   :country=>'USA', :country_code=>'US',
   :location=>"Fort Gillem, Forest Park, Georgia, USA"},
 "FPR"=>
  {:iata=>"FPR",
   :name=>"St. Lucie County International Airport",
   :icao=>"KFPR",
   :city=>"Fort Pierce",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Pierce, Florida, United States"},
 "FPY"=>
  {:iata=>"FPY",
   :name=>"Perry-Foley Airport (FAA: 40J)",
   :icao=>"",
   :city=>"Perry",
   :country=>'United States', :country_code=>'US',

   :location=>"Perry, Florida, United States"},
 "FRD"=>
  {:iata=>"FRD",
   :name=>"Friday Harbor Airport (FAA: FHR)",
   :icao=>"KFHR",
   :city=>"Friday Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Friday Harbor, Washington, United States"},
 "FRG"=>
  {:iata=>"FRG",
   :name=>"Republic Airport",
   :icao=>"KFRG",
   :city=>"East Farmingdale",
   :country=>'United States', :country_code=>'US',

   :location=>"East Farmingdale, New York, United States"},
 "FRH"=>
  {:iata=>"FRH",
   :name=>"French Lick Municipal Airport",
   :icao=>"KFRH",
   :city=>"French Lick",
   :country=>'United States', :country_code=>'US',

   :location=>"French Lick, Indiana, United States"},
 "FRI"=>
  {:iata=>"FRI",
   :name=>"Marshall Army Airfield (Fort Riley)",
   :icao=>"KFRI",
   :city=>"Junction City",
   :country=>'United States', :country_code=>'US',

   :location=>"Junction City, Kansas, United States"},
 "FRM"=>
  {:iata=>"FRM",
   :name=>"Fairmont Municipal Airport",
   :icao=>"KFRM",
   :city=>"Fairmont",
   :country=>'United States', :country_code=>'US',

   :location=>"Fairmont, Minnesota, United States"},
 "FRN"=>
  {:iata=>"FRN",
   :name=>"Bryant Army Heliport / Bryant AAF",
   :icao=>"PAFR",
   :city=>"Fort Richardson",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Richardson, Anchorage, Alaska, United States"},
 "FRR"=>
  {:iata=>"FRR",
   :name=>"Front Royal-Warren County Airport",
   :icao=>"KFRR",
   :city=>"Front Royal",
   :country=>'United States', :country_code=>'US',

   :location=>"Front Royal, Virginia, United States"},
 "FRY"=>
  {:iata=>"FRY",
   :name=>"Eastern Slopes Regional Airport (FAA: IZG)",
   :icao=>"KIZG",
   :city=>"Fryeburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Fryeburg, Maine, United States"},
 "FSD"=>
  {:iata=>"FSD",
   :name=>"Sioux Falls Regional Airport (Joe Foss Field)",
   :icao=>"KFSD",
   :city=>"Sioux Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Sioux Falls, South Dakota, United States"},
 "FSI"=>
  {:iata=>"FSI",
   :name=>"Henry Post Army Airfield (Fort Sill)",
   :icao=>"KFSI",
   :city=>"Fort Sill",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Sill, Oklahoma, United States"},
 "FSK"=>
  {:iata=>"FSK",
   :name=>"Fort Scott Municipal Airport",
   :icao=>"KFSK",
   :city=>"Fort Scott",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Scott, Kansas, United States"},
 "FSM"=>
  {:iata=>"FSM",
   :name=>"Fort Smith Regional Airport",
   :icao=>"KFSM",
   :city=>"Fort Smith",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Smith, Arkansas, United States"},
 "FST"=>
  {:iata=>"FST",
   :name=>"Fort Stockton-Pecos County Airport",
   :icao=>"KFST",
   :city=>"Fort Stockton",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Stockton, Texas, United States"},
 "FSU"=>
  {:iata=>"FSU",
   :name=>"Fort Sumner Municipal Airport",
   :icao=>"KFSU",
   :city=>"Fort Sumner",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Sumner, New Mexico, United States"},
 "FTK"=>
  {:iata=>"FTK",
   :name=>"Godman Army Airfield",
   :icao=>"KFTK",
   :city=>"Fort Knox",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Knox, Kentucky, United States"},
 "FTW"=>
  {:iata=>"FTW",
   :name=>"Fort Worth Meacham International Airport",
   :icao=>"KFTW",
   :city=>"Fort Worth",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Worth, Texas, United States"},
 "FTY"=>
  {:iata=>"FTY",
   :name=>"Fulton County Airport (Brown Field)",
   :icao=>"KFTY",
   :city=>"Atlanta",
   :country=>'United States', :country_code=>'US',

   :location=>"Atlanta, Georgia, United States"},
 "FUL"=>
  {:iata=>"FUL",
   :name=>"Fullerton Municipal Airport",
   :icao=>"KFUL",
   :city=>"Fullerton",
   :country=>'United States', :country_code=>'US',

   :location=>"Fullerton, California, United States"},
 "FWA"=>
  {:iata=>"FWA",
   :name=>"Fort Wayne International Airport",
   :icao=>"KFWA",
   :city=>"Fort Wayne",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Wayne, Indiana, United States"},
 "FWH"=>
  {:iata=>"FWH",
   :name=>"NAS JRB Fort Worth / Carswell Field (FAA: NFW)",
   :icao=>"KNFW",
   :city=>"Fort Worth",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Worth, Texas, United States"},
 "FWL"=>
  {:iata=>"FWL",
   :name=>"Farewell Airport",
   :icao=>"PAFW",
   :city=>"Farewell",
   :country=>'United States', :country_code=>'US',

   :location=>"Farewell, Alaska, United States"},
 "FXE"=>
  {:iata=>"FXE",
   :name=>"Fort Lauderdale Executive Airport",
   :icao=>"KFXE",
   :city=>"Fort Lauderdale",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Lauderdale, Florida, United States"},
 "FXY"=>
  {:iata=>"FXY",
   :name=>"Forest City Municipal Airport",
   :icao=>"KFXY",
   :city=>"Forest City",
   :country=>'United States', :country_code=>'US',

   :location=>"Forest City, Iowa, United States"},
 "FYM"=>
  {:iata=>"FYM",
   :name=>"Fayetteville Municipal Airport",
   :icao=>"KFYM",
   :city=>"Fayetteville",
   :country=>'United States', :country_code=>'US',

   :location=>"Fayetteville, Tennessee, United States"},
 "FYU"=>
  {:iata=>"FYU",
   :name=>"Fort Yukon Airport",
   :icao=>"PFYU",
   :city=>"Fort Yukon",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Yukon, Alaska, United States"},
 "FYV"=>
  {:iata=>"FYV",
   :name=>"Drake Field",
   :icao=>"KFYV",
   :city=>"Fayetteville",
   :country=>'United States', :country_code=>'US',

   :location=>"Fayetteville, Arkansas, United States"}}

end
