# encoding: UTF-8
def airp_12
  {"KEW"=>
  {:iata=>"KEW",
   :name=>"Keewaywin Airport (TC LID: CPV8)",
   :icao=>"",
   :city=>"Keewaywin",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Keewaywin, Ontario, Canada"},
 "KIF"=>
  {:iata=>"KIF",
   :name=>"Kingfisher Lake Airport",
   :icao=>"",
   :city=>"Kingfisher Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kingfisher Lake, Ontario, Canada"},
 "KES"=>
  {:iata=>"KES",
   :name=>"Kelsey Airport",
   :icao=>"CZEE",
   :city=>"Kelsey",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kelsey, Manitoba, Canada"},
 "KNY"=>
  {:iata=>"KNY",
   :name=>"Kinoosao Airport",
   :city=>"Kinoosao",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kinoosao, Canada"},
 "KNV"=>
  {:iata=>"KNV",
   :name=>"Knights Inlet Airport",
   :city=>"Knights Inlet",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Knights Inlet, Canada"},
 "KGQ"=>
  {:iata=>"KGQ",
   :name=>"Kangersuatsiaq Heliport",
   :icao=>"BGKS",
   :city=>"Kangersuatsiaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Kangersuatsiaq, Greenland"},
 "KHQ"=>
  {:iata=>"KHQ",
   :name=>"Kullorsuaq Heliport",
   :icao=>"BGKQ",
   :city=>"Kullorsuaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Kullorsuaq, Greenland"},
 "KUS"=>
  {:iata=>"KUS",
   :name=>"Kulusuk Airport",
   :icao=>"BGKK",
   :city=>"Kulusuk",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Kulusuk, Greenland"},
 "KUZ"=>
  {:iata=>"KUZ",
   :name=>"Kuummiit Heliport",
   :icao=>"BGKM",
   :city=>"Kuummiit",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Kuummiit, Greenland"},
 "KNA"=>
  {:iata=>"KNA",
   :name=>"Viña del Mar Airport",
   :icao=>"SCVM",
   :city=>"Viña del Mar",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Viña del Mar, Chile"},
 "KRG"=>
  {:iata=>"KRG",
   :name=>"Karasabai Airport",
   :icao=>"SYKS",
   :city=>"Karasabai",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Karasabai, Guyana"},
 "KAI"=>
  {:iata=>"KAI",
   :name=>"Kaieteur Airport",
   :icao=>"SYKA",
   :city=>"Kaieteur",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Kaieteur, Guyana"},
 "KAR"=>
  {:iata=>"KAR",
   :name=>"Kamarang Airport",
   :icao=>"SYKM",
   :city=>"Kamarang",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Kamarang, Guyana"},
 "KRM"=>
  {:iata=>"KRM",
   :name=>"Karanambo Airport",
   :icao=>"SYKR",
   :city=>"Karanambo",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Karanambo, Guyana"},
 "KTO"=>
  {:iata=>"KTO",
   :name=>"Kato Airport",
   :icao=>"SYKT",
   :city=>"Kato",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Kato, Guyana"},
 "KKG"=>
  {:iata=>"KKG",
   :name=>"Konawaruk Airport",
   :icao=>"",
   :city=>"Konawaruk",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Konawaruk, Guyana"},
 "KPG"=>
  {:iata=>"KPG",
   :name=>"Kurupung Airport",
   :icao=>"",
   :city=>"Kurupung",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Kurupung, Guyana"},
 "KCB"=>
  {:iata=>"KCB",
   :name=>"Tepoe Airstrip",
   :icao=>"",
   :city=>"Kasikasima",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Kasikasima, Suriname"},
 "KTV"=>
  {:iata=>"KTV",
   :name=>"Kamarata Airport",
   :icao=>"SVKM",
   :city=>"Kamarata",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Kamarata, Bolívar, Venezuela"},
 "KAV"=>
  {:iata=>"KAV",
   :name=>"Kavanayén Airport",
   :icao=>"SVKA",
   :city=>"Kavanayén",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Kavanayén, Bolívar, Venezuela"},
 "KFE"=>
  {:iata=>"KFE",
   :name=>"Dave Forest Airport",
   :icao=>"YFDF",
   :city=>"Cloudbreak /\nWestern Australia",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Cloudbreak /\nWestern Australia, Australia\n"},
 "KAX"=>
  {:iata=>"KAX",
   :name=>"Kalbarri Airport",
   :icao=>"YKBR",
   :city=>"Kalbarri",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kalbarri, Western Australia, Australia"},
 "KGI"=>
  {:iata=>"KGI",
   :name=>"Kalgoorlie-Boulder Airport",
   :icao=>"YPKG",
   :city=>"Kalgoorlie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kalgoorlie, Western Australia, Australia"},
 "KTA"=>
  {:iata=>"KTA",
   :name=>"Karratha Airport",
   :icao=>"YPKA",
   :city=>"Karratha / Dampier",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Karratha / Dampier, Western Australia, Australia"},
 "KRB"=>
  {:iata=>"KRB",
   :name=>"Karumba Airport",
   :icao=>"YKMB",
   :city=>"Karumba",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Karumba, Queensland, Australia"},
 "KTR"=>
  {:iata=>"KTR",
   :name=>"Tindal Airport",
   :icao=>"YPTN",
   :city=>"Katherine",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Katherine, Northern Territory, Australia"},
 "KNS"=>
  {:iata=>"KNS",
   :name=>"King Island Airport",
   :icao=>"YKII",
   :city=>"Currie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Currie, Tasmania, Australia"},
 "KGC"=>
  {:iata=>"KGC",
   :name=>"Kingscote Airport",
   :icao=>"YKSC",
   :city=>"Kingscote",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kingscote, South Australia, Australia"},
 "KWM"=>
  {:iata=>"KWM",
   :name=>"Kowanyama Airport",
   :icao=>"YKOW",
   :city=>"Kowanyama",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kowanyama, Queensland, Australia"},
 "KNX"=>
  {:iata=>"KNX",
   :name=>"Kununurra Airport",
   :icao=>"YPKU",
   :city=>"Kununurra",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kununurra, Western Australia, Australia"},
 "KCE"=>
  {:iata=>"KCE",
   :name=>"Collinsville Airport",
   :icao=>"YCSV",
   :city=>"Collinsville",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Collinsville, Queensland, Australia"},
 "KFG"=>
  {:iata=>"KFG",
   :name=>"Kalkurung Airport",
   :icao=>"YKKG",
   :city=>"Daguragu / Kalkaringi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Daguragu / Kalkaringi, Northern Territory, Australia"},
 "KPP"=>
  {:iata=>"KPP",
   :name=>"Kalpowar Airport",
   :icao=>"YKPR",
   :city=>"Kalpowar",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kalpowar, Queensland, Australia"},
 "KDS"=>
  {:iata=>"KDS",
   :name=>"Kamaran Downs Airport",
   :icao=>"",
   :city=>"Kamaran Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kamaran Downs, Queensland, Australia"},
 "KDB"=>
  {:iata=>"KDB",
   :name=>"Kambalda Airport",
   :icao=>"YKBL",
   :city=>"Kambalda",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kambalda, Western Australia, Australia"},
 "KML"=>
  {:iata=>"KML",
   :name=>"Kamileroi Airport",
   :icao=>"YKML",
   :city=>"Kamileroi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kamileroi, Queensland, Australia"},
 "KNI"=>
  {:iata=>"KNI",
   :name=>"Katanning Airport",
   :icao=>"YKNG",
   :city=>"Katanning",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Katanning, Western Australia, Australia"},
 "KPS"=>
  {:iata=>"KPS",
   :name=>"Kempsey Airport",
   :icao=>"YKMP",
   :city=>"Kempsey",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kempsey, New South Wales, Australia"},
 "KRA"=>
  {:iata=>"KRA",
   :name=>"Kerang Airport",
   :icao=>"YKER",
   :city=>"Kerang",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kerang, Victoria, Australia"},
 "KBD"=>
  {:iata=>"KBD",
   :name=>"Kimberley Downs Airport",
   :icao=>"",
   :city=>"Kimberley Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kimberley Downs, Western Australia, Australia"},
 "KGY"=>
  {:iata=>"KGY",
   :name=>"Kingaroy Airport",
   :icao=>"YKRY",
   :city=>"Kingaroy",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kingaroy, Queensland, Australia"},
 "KBJ"=>
  {:iata=>"KBJ",
   :name=>"Kings Canyon Airport",
   :icao=>"YKCA",
   :city=>"Kings Canyon",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kings Canyon, Northern Territory, Australia"},
 "KCS"=>
  {:iata=>"KCS",
   :name=>"Kings Creek Airport",
   :icao=>"YKCS",
   :city=>"Kings Creek",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kings Creek, Northern Territory, Australia"},
 "KBB"=>
  {:iata=>"KBB",
   :name=>"Kirkimbie Airport",
   :city=>"Kirkimbie",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kirkimbie, Australia"},
 "KOH"=>
  {:iata=>"KOH",
   :name=>"Koolatah Airport",
   :icao=>"YKLA",
   :city=>"Koolatah",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Koolatah, Queensland, Australia"},
 "KKP"=>
  {:iata=>"KKP",
   :name=>"Koolburra Airport",
   :icao=>"YKLB",
   :city=>"Koolburra",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Koolburra, Queensland, Australia"},
 "KQB"=>
  {:iata=>"KQB",
   :name=>"Koonibba Airport",
   :icao=>"",
   :city=>"Koonibba",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Koonibba, South Australia, Australia"},
 "KUG"=>
  {:iata=>"KUG",
   :name=>"Kubin Airport",
   :icao=>"YKUB",
   :city=>"Kubin",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kubin, Moa Island, Queensland, Australia"},
 "KGR"=>
  {:iata=>"KGR",
   :name=>"Kulgera Airport",
   :icao=>"",
   :city=>"Kulgera",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kulgera, Northern Territory, Australia"},
 "KRD"=>
  {:iata=>"KRD",
   :name=>"Kurundi Airport",
   :icao=>"",
   :city=>"Kurundi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kurundi, Northern Territory, Australia"},
 "KAH"=>
  {:iata=>"KAH",
   :name=>"Melbourne City Heliport",
   :city=>"Melbourne",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Melbourne, Australia"},
 "KSV"=>
  {:iata=>"KSV",
   :name=>"Springvale Airport, Queensland",
   :icao=>"YSPV",
   :city=>"Springvale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Springvale, Queensland, Australia"},
 "KBY"=>
  {:iata=>"KBY",
   :name=>"Streaky Bay Airport",
   :icao=>"YKBY",
   :city=>"Streaky Bay",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Streaky Bay, South Australia, Australia"},
 "KYI"=>
  {:iata=>"KYI",
   :name=>"Yalata Mission Airport",
   :icao=>"YYTA",
   :city=>"Yalata Mission",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Yalata Mission, South Australia, Australia"},
 "KYF"=>
  {:iata=>"KYF",
   :name=>"Yeelirrie Airport",
   :icao=>"YYLR",
   :city=>"Yeelirrie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Yeelirrie, Western Australia, Australia"},
 "KDV"=>
  {:iata=>"KDV",
   :name=>"Vunisea Airport (Kandavu Airport)",
   :icao=>"NFKD",
   :city=>"Vunisea",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Vunisea, Kadavu Island, Fiji"},
 "KXF"=>
  {:iata=>"KXF",
   :name=>"Koro Airport",
   :icao=>"NFNO",
   :city=>"Koro Island",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Koro Island, Fiji"},
 "KVU"=>
  {:iata=>"KVU",
   :name=>"Korolevu Airport",
   :icao=>"",
   :city=>"Korolevu",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Korolevu, Viti Levu, Fiji"},
 "KAY"=>
  {:iata=>"KAY",
   :name=>"Wakaya Island Airport",
   :icao=>"NFNW",
   :city=>"Wakaya Island",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Wakaya Island, Fiji"},
 "KXU"=>
  {:iata=>"KXU",
   :name=>"Katiu Airport",
   :city=>"Katiu",
   :icao=>"",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Katiu, Polynesia"},
 "KHZ"=>
  {:iata=>"KHZ",
   :name=>"Kauehi Airport",
   :icao=>"NTKA",
   :city=>"Kauehi",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Kauehi, French Polynesia"},
 "KKR"=>
  {:iata=>"KKR",
   :name=>"Kaukura Atoll Airport",
   :icao=>"NTGK",
   :city=>"Kaukura Atoll",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Kaukura Atoll, French Polynesia"},
 "KUC"=>
  {:iata=>"KUC",
   :name=>"Kuria Airport",
   :icao=>"NGKT",
   :city=>"Kuria",
   :country=>"Kiribati",
:country_code=>"KI",
   :location=>"Kuria, Kiribati"},
 "KWA"=>
  {:iata=>"KWA",
   :name=>"Bucholz Army Airfield",
   :icao=>"PKWA",
   :city=>"Kwajalein",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Kwajalein, Marshall Islands"},
 "KBT"=>
  {:iata=>"KBT",
   :name=>"Kaben Airport",
   :icao=>"",
   :city=>"Maloelap Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Maloelap Atoll, Marshall Islands"},
 "KIO"=>
  {:iata=>"KIO",
   :name=>"Kili Airport (FAA: Q51)",
   :icao=>"",
   :city=>"Kili Island",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Kili Island, Marshall Islands"},
 "KSA"=>
  {:iata=>"KSA",
   :name=>"Kosrae International Airport (FAA: TTK)",
   :icao=>"PTSA",
   :city=>"Kosrae",
   :country=>'Federated States of Micronesia', :country_code=>'FM',
   :location=>"Kosrae, Federated States of Micronesia"},
 "KNQ"=>
  {:iata=>"KNQ",
   :name=>"Koné Airport",
   :icao=>"NWWD",
   :city=>"Koné",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Koné, New Caledonia"},
 "KOC"=>
  {:iata=>"KOC",
   :name=>"Koumac Airport",
   :icao=>"NWWK",
   :city=>"Koumac",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Koumac, New Caledonia"},
 "KAT"=>
  {:iata=>"KAT",
   :name=>"Kaitaia Airport",
   :icao=>"NZKT",
   :city=>"Kaitaia",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Kaitaia, New Zealand"},
 "KKE"=>
  {:iata=>"KKE",
   :name=>"Bay of Islands Airport (Kerikeri Airport)",
   :icao=>"NZKK",
   :city=>"Kerikeri",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Kerikeri, New Zealand"},
 "KKO"=>
  {:iata=>"KKO",
   :name=>"Kaikohe Aerodrome",
   :icao=>"NZKO",
   :city=>"Kaikohe",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Kaikohe, New Zealand"},
 "KBZ"=>
  {:iata=>"KBZ",
   :name=>"Kaikoura Airport",
   :icao=>"NZKI",
   :city=>"Kaikoura",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Kaikoura, New Zealand"},
 "KUI"=>
  {:iata=>"KUI",
   :name=>"Kawau Island Airport",
   :icao=>"",
   :city=>"Kawau Island",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Kawau Island, New Zealand"},
 "KTF"=>
  {:iata=>"KTF",
   :name=>"Takaka Aerodrome",
   :icao=>"NZTK",
   :city=>"Takaka",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Takaka, New Zealand"},
 "KGE"=>
  {:iata=>"KGE",
   :name=>"Kagau Island Airport",
   :icao=>"AGKG",
   :city=>"Kagau Island",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Kagau Island, Solomon Islands"},
 "KUE"=>
  {:iata=>"KUE",
   :name=>"Kukundu Airport",
   :icao=>"AGKU",
   :city=>"Kolombangara island",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Kolombangara island, Western Province, Solomon Islands"},
 "KWR"=>
  {:iata=>"KWR",
   :name=>"Kwai Harbour Airport",
   :icao=>"",
   :city=>"Kwai Harbour",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Kwai Harbour, Solomon Islands"},
 "KIN"=>
  {:iata=>"KIN",
   :name=>"Norman Manley International Airport",
   :icao=>"MKJP",
   :city=>"Kingston",
   :country=>'Jamaica', :country_code=>'JM',
   :location=>"Kingston, Jamaica"},
 "KTP"=>
  {:iata=>"KTP",
   :name=>"Tinson Pen Aerodrome",
   :icao=>"MKTP",
   :city=>"Kingston",
   :country=>'Jamaica', :country_code=>'JM',
   :location=>"Kingston, Jamaica, Jamaica"},
 "KDF"=>
  {:iata=>"KDF",
   :name=>"Kouba Airport",
   :icao=>"",
   :city=>"Kouba",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Kouba, Algeria"},
 "KNP"=>
  {:iata=>"KNP",
   :name=>"Capanda Airport",
   :icao=>"FNCP",
   :city=>"Capanda",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Capanda, Angola"},
 "KDC"=>
  {:iata=>"KDC",
   :name=>"Kandi Airport",
   :icao=>"DBBK",
   :city=>"Kandi",
   :country=>'Benin', :country_code=>'BJ',
   :location=>"Kandi, Benin"},
 "KHW"=>
  {:iata=>"KHW",
   :name=>"Khwai River Lodge Airport",
   :icao=>"FBKR",
   :city=>"Khwai River Lodge",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Khwai River Lodge, Botswana"},
 "KRE"=>
  {:iata=>"KRE",
   :name=>"Kirundo Airport",
   :icao=>"HBBO",
   :city=>"Kirundo",
   :country=>'Burundi', :country_code=>'BI',
   :location=>"Kirundo, Burundi"},
 "KLE"=>
  {:iata=>"KLE",
   :name=>"Kaélé Airport",
   :icao=>"FKKH",
   :city=>"Kaélé",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Kaélé, Cameroon"},
 "KOB"=>
  {:iata=>"KOB",
   :name=>"Foumban Airport (Koutaba Airport)",
   :icao=>"FKKM",
   :city=>"Koutaba",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Koutaba, Cameroon"},
 "KBI"=>
  {:iata=>"KBI",
   :name=>"Kribi Airport",
   :icao=>"FKKB",
   :city=>"Kribi",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Kribi, Cameroon"},
 "KOL"=>
  {:iata=>"KOL",
   :name=>"Koumala Airport",
   :icao=>"",
   :city=>"Koumala",
   :country=>'Central African Republic', :country_code=>'CF',
   :location=>"Koumala, Central African Republic"},
 "KEE"=>
  {:iata=>"KEE",
   :name=>"Kelle Airport",
   :icao=>"FCOK",
   :city=>"Kelle",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Kelle, Republic of the Congo"},
 "KNJ"=>
  {:iata=>"KNJ",
   :name=>"Kindamba Airport",
   :icao=>"FCBK",
   :city=>"Kindamba",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Kindamba, Republic of the Congo"},
 "KMK"=>
  {:iata=>"KMK",
   :name=>"Makabana Airport",
   :icao=>"FCPA",
   :city=>"Makabana",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Makabana, Republic of the Congo"},
 "KEO"=>
  {:iata=>"KEO",
   :name=>"Odienné Airport",
   :icao=>"DIOD",
   :city=>"Odienné",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Odienné, Côte d'Ivoire"},
 "KTC"=>
  {:iata=>"KTC",
   :name=>"Katiola Airport",
   :icao=>"",
   :city=>"Katiola",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Katiola, Côte d'Ivoire"},
 "KOU"=>
  {:iata=>"KOU",
   :name=>"Koulamoutou Airport",
   :icao=>"FOGK",
   :city=>"Koulamoutou",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Koulamoutou, Gabon"},
 "KMD"=>
  {:iata=>"KMD",
   :name=>"Mandji Airport",
   :icao=>"",
   :city=>"Mandji",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Mandji, Gabon"},
 "KDN"=>
  {:iata=>"KDN",
   :name=>"Ndende Airport",
   :icao=>"FOGE",
   :city=>"Ndende",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Ndende, Gabon"},
 "KDJ"=>
  {:iata=>"KDJ",
   :name=>"Ville Airport (Ndjolé Airport)",
   :icao=>"FOGJ",
   :city=>"Ndjolé",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Ndjolé, Gabon"},
 "KMS"=>
  {:iata=>"KMS",
   :name=>"Kumasi Airport",
   :icao=>"DGSI",
   :city=>"Kumasi",
   :country=>'Ghana', :country_code=>'GH',
   :location=>"Kumasi, Ghana"},
 "KNN"=>
  {:iata=>"KNN",
   :name=>"Kankan Airport (Diankana Airport)",
   :icao=>"GUXN",
   :city=>"Kankan",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kankan, Guinea"},
 "KSI"=>
  {:iata=>"KSI",
   :name=>"Kissidougou Airport",
   :icao=>"GUKU",
   :city=>"Kissidougou",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kissidougou, Guinea"},
 "KIS"=>
  {:iata=>"KIS",
   :name=>"Kisumu Airport",
   :icao=>"HKKI",
   :city=>"Kisumu",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kisumu, Kenya"},
 "KTL"=>
  {:iata=>"KTL",
   :name=>"Kitale Airport",
   :icao=>"HKKT",
   :city=>"Kitale",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kitale, Kenya"},
 "KLK"=>
  {:iata=>"KLK",
   :name=>"Kalokol Airport",
   :icao=>"HKFG",
   :city=>"Kalokol",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kalokol, Kenya"},
 "KEY"=>
  {:iata=>"KEY",
   :name=>"Kericho Airport",
   :icao=>"HKKR",
   :city=>"Kericho",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kericho, Kenya"},
 "KRV"=>
  {:iata=>"KRV",
   :name=>"Kerio Valley Airport",
   :icao=>"",
   :city=>"Kerio Valley",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kerio Valley, Kenya"},
 "KIU"=>
  {:iata=>"KIU",
   :name=>"Kiunga Airport",
   :icao=>"",
   :city=>"Kiunga",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kiunga, Kenya"},
 "KWY"=>
  {:iata=>"KWY",
   :name=>"Kiwayu Airport",
   :icao=>"",
   :city=>"Kiwayu",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kiwayu, Kenya"},
 "KGJ"=>
  {:iata=>"KGJ",
   :name=>"Karonga Airport",
   :icao=>"FWKA",
   :city=>"Karonga",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Karonga, Malawi"},
 "KBQ"=>
  {:iata=>"KBQ",
   :name=>"Kasungu Airport",
   :icao=>"FWKG",
   :city=>"Kasungu",
   :country=>'Malawi', :country_code=>'MW',
   :location=>"Kasungu, Malawi"},
 "KYS"=>
  {:iata=>"KYS",
   :name=>"Kayes Airport (Dag Dag Airport)",
   :icao=>"GAKY",
   :city=>"Kayes",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Kayes, Mali"},
 "KNZ"=>
  {:iata=>"KNZ",
   :name=>"Kéniéba Airport",
   :icao=>"GAKA",
   :city=>"Kéniéba",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Kéniéba, Mali"},
 "KTX"=>
  {:iata=>"KTX",
   :name=>"Koutiala Airport",
   :icao=>"GAKO",
   :city=>"Koutiala",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Koutiala, Mali"},
 "KSS"=>
  {:iata=>"KSS",
   :name=>"Sikasso Airport",
   :icao=>"GASK",
   :city=>"Sikasso",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Sikasso, Mali"},
 "KED"=>
  {:iata=>"KED",
   :name=>"Kaédi Airport",
   :icao=>"GQNK",
   :city=>"Kaédi",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Kaédi, Mauritania"},
 "KFA"=>
  {:iata=>"KFA",
   :name=>"Kiffa Airport",
   :icao=>"GQNF",
   :city=>"Kiffa",
   :country=>'Mauritania', :country_code=>'MR',
   :location=>"Kiffa, Mauritania"},
 "KAS"=>
  {:iata=>"KAS",
   :name=>"Karasburg Airport",
   :icao=>"FYKB",
   :city=>"Karasburg",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Karasburg, Namibia"},
 "KMP"=>
  {:iata=>"KMP",
   :name=>"Keetmanshoop Airport",
   :icao=>"FYKT",
   :city=>"Keetmanshoop",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Keetmanshoop, Namibia"},
 "KAD"=>
  {:iata=>"KAD",
   :name=>"Kaduna Airport",
   :icao=>"DNKA",
   :city=>"Kaduna",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Kaduna, Nigeria"},
 "KAN"=>
  {:iata=>"KAN",
   :name=>"Mallam Aminu Kano International Airport",
   :icao=>"DNKN",
   :city=>"Kano",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Kano, Nigeria"},
 "KME"=>
  {:iata=>"KME",
   :name=>"Cyangugu Airport",
   :icao=>"HRZA",
   :city=>"Cyangugu",
   :country=>'Rwanda', :country_code=>'RW',
   :location=>"Cyangugu, Rwanda"},
 "KGL"=>
  {:iata=>"KGL",
   :name=>"Kigali International Airport (Kanombe Airport)",
   :icao=>"HRYR",
   :city=>"Kigali",
   :country=>'Rwanda', :country_code=>'RW',
   :location=>"Kigali, Rwanda"},
 "KLC"=>
  {:iata=>"KLC",
   :name=>"Kaolack Airport",
   :icao=>"GOOK",
   :city=>"Kaolack",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Kaolack, Senegal"},
 "KGG"=>
  {:iata=>"KGG",
   :name=>"Kédougou Airport",
   :icao=>"GOTK",
   :city=>"Kédougou",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Kédougou, Senegal"},
 "KDA"=>
  {:iata=>"KDA",
   :name=>"Kolda North Airport",
   :icao=>"GOGK",
   :city=>"Kolda",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Kolda, Senegal"},
 "KBS"=>
  {:iata=>"KBS",
   :name=>"Bo Airport",
   :icao=>"GFBO",
   :city=>"Bo",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Bo, Sierra Leone"},
 "KBA"=>
  {:iata=>"KBA",
   :name=>"Kabala Airport",
   :icao=>"GFKB",
   :city=>"Kabala",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Kabala, Sierra Leone"},
 "KEN"=>
  {:iata=>"KEN",
   :name=>"Kenema Airport",
   :icao=>"GFKE",
   :city=>"Kenema",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Kenema, Sierra Leone"},
 "KMU"=>
  {:iata=>"KMU",
   :name=>"Kisimayu Airport",
   :icao=>"HCMK",
   :city=>"Kisimayu",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Kisimayu, Somalia"},
 "KIM"=>
  {:iata=>"KIM",
   :name=>"Kimberley Airport",
   :icao=>"FAKM",
   :city=>"Kimberley",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Kimberley, South Africa"},
 "KHO"=>
  {:iata=>"KHO",
   :name=>"Khoka Moya Airport",
   :icao=>"",
   :city=>"Khoka Moya",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Khoka Moya, South Africa"},
 "KLZ"=>
  {:iata=>"KLZ",
   :name=>"Kleinzee Airport",
   :icao=>"FAKZ",
   :city=>"Kleinzee",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Kleinzee, South Africa"},
 "KXE"=>
  {:iata=>"KXE",
   :name=>"Klerksdorp Airport (P.C. Pelser Airport)",
   :icao=>"FAKD",
   :city=>"Klerksdorp",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Klerksdorp, South Africa"},
 "KIG"=>
  {:iata=>"KIG",
   :name=>"Koingnaas Airport",
   :icao=>"",
   :city=>"Koingnaas",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Koingnaas, South Africa"},
 "KOF"=>
  {:iata=>"KOF",
   :name=>"Komatipoort Airport",
   :icao=>"FAKP",
   :city=>"Komatipoort",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Komatipoort, South Africa"},
 "KMH"=>
  {:iata=>"KMH",
   :name=>"Johan Pienaar Airport",
   :icao=>"FAKU",
   :city=>"Kuruman",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Kuruman, South Africa"},
 "KSL"=>
  {:iata=>"KSL",
   :name=>"Kassala Airport",
   :icao=>"HSKA",
   :city=>"Kassala",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Kassala, Sudan"},
 "KRT"=>
  {:iata=>"KRT",
   :name=>"Khartoum International Airport",
   :icao=>"HSSS",
   :city=>"Khartoum",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Khartoum, Sudan"},
 "KST"=>
  {:iata=>"KST",
   :name=>"Kosti Airport",
   :icao=>"HSKI",
   :city=>"Kosti",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Kosti, Sudan"},
 "KMN"=>
  {:iata=>"KMN",
   :name=>"Kamina Air Base",
   :icao=>"FZSA",
   :city=>"Kamina",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kamina, Democratic Republic of the Congo"},
 "KGA"=>
  {:iata=>"KGA",
   :name=>"Kananga Airport",
   :icao=>"FZUA",
   :city=>"Kananga",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kananga, Democratic Republic of the Congo"},
 "KND"=>
  {:iata=>"KND",
   :name=>"Kindu Airport",
   :icao=>"FZOA",
   :city=>"Kindu",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kindu, Democratic Republic of the Congo"},
 "KWZ"=>
  {:iata=>"KWZ",
   :name=>"Kolwezi Airport",
   :icao=>"FZQM",
   :city=>"Kolwezi",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kolwezi, Lualaba District, Democratic Republic of the Congo"},
 "KOO"=>
  {:iata=>"KOO",
   :name=>"Kongolo Airport",
   :icao=>"FZRQ",
   :city=>"Kongolo",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kongolo, Democratic Republic of the Congo"},
 "KBO"=>
  {:iata=>"KBO",
   :name=>"Kabalo Airport",
   :icao=>"FZRM",
   :city=>"Kabalo",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kabalo, Democratic Republic of the Congo"},
 "KBN"=>
  {:iata=>"KBN",
   :name=>"Tunta Airport",
   :icao=>"FZWT",
   :city=>"Kabinda",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kabinda, Democratic Republic of the Congo"},
 "KLY"=>
  {:iata=>"KLY",
   :name=>"Kalima Airport (Kinkungwa Airport, Kakungwa Airport)",
   :icao=>"FZOD",
   :city=>"Kalima",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kalima, Democratic Republic of the Congo"},
 "KNM"=>
  {:iata=>"KNM",
   :name=>"Kaniama Airport",
   :icao=>"FZTK",
   :city=>"Kaniama",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kaniama, Democratic Republic of the Congo"},
 "KAP"=>
  {:iata=>"KAP",
   :name=>"Kapanga Airport",
   :icao=>"FZSK",
   :city=>"Kapanga",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kapanga, Democratic Republic of the Congo"},
 "KEC"=>
  {:iata=>"KEC",
   :name=>"Kasenga Airport",
   :icao=>"FZQG",
   :city=>"Kasenga",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kasenga, Democratic Republic of the Congo"},
 "KGN"=>
  {:iata=>"KGN",
   :name=>"Kasongo Lunda Airport",
   :icao=>"FZOK",
   :city=>"Kasongo Lunda",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kasongo Lunda, Democratic Republic of the Congo"},
 "KKW"=>
  {:iata=>"KKW",
   :name=>"Kikwit Airport",
   :icao=>"FZCA",
   :city=>"Kikwit",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kikwit, Democratic Republic of the Congo"},
 "KIL"=>
  {:iata=>"KIL",
   :name=>"Kilwa Airport",
   :icao=>"",
   :city=>"Kilwa",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kilwa, Democratic Republic of the Congo"},
 "KRZ"=>
  {:iata=>"KRZ",
   :name=>"Kiri Airport (Basango Mboliasa Airport)",
   :icao=>"FZBT",
   :city=>"Kiri",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kiri, Democratic Republic of the Congo"},
 "KLI"=>
  {:iata=>"KLI",
   :name=>"Kota Koli Airport",
   :icao=>"FZFP",
   :city=>"Kota Koli",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Kota Koli, Democratic Republic of the Congo"},
 "KSE"=>
  {:iata=>"KSE",
   :name=>"Kasese Airport",
   :icao=>"HUKS",
   :city=>"Kasese",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Kasese, Uganda"},
 "KBG"=>
  {:iata=>"KBG",
   :name=>"Kabalega Falls Airport",
   :icao=>"HUKF",
   :city=>"Kabalega Falls",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Kabalega Falls, Uganda"},
 "KCU"=>
  {:iata=>"KCU",
   :name=>"Masindi Airport",
   :icao=>"HUMI",
   :city=>"Masindi",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Masindi, Uganda"},
 "KIY"=>
  {:iata=>"KIY",
   :name=>"Kilwa Masoko Airport",
   :icao=>"HTKI",
   :city=>"Kilwa Masoko",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Kilwa Masoko, Tanzania"},
 "KAA"=>
  {:iata=>"KAA",
   :name=>"Kasama Airport",
   :icao=>"FLKS",
   :city=>"Kasama",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Kasama, Zambia"},
 "KLB"=>
  {:iata=>"KLB",
   :name=>"Kalabo Airport",
   :icao=>"FLKL",
   :city=>"Kalabo",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Kalabo, Zambia"},
 "KMZ"=>
  {:iata=>"KMZ",
   :name=>"Kaoma Airport",
   :icao=>"FLKO",
   :city=>"Kaoma",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Kaoma, Zambia"},
 "KIW"=>
  {:iata=>"KIW",
   :name=>"Southdowns Airport",
   :icao=>"FLSO",
   :city=>"Kitwe",
   :country=>'Zambia', :country_code=>'ZM',
   :location=>"Kitwe, Zambia"},
 "KAB"=>
  {:iata=>"KAB",
   :name=>"Kariba Airport",
   :icao=>"FVKB",
   :city=>"Kariba",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Kariba, Zimbabwe"},
 "KLU"=>
  {:iata=>"KLU",
   :name=>"Klagenfurt Airport (Klagenfurt/Wörthersee Airport)",
   :icao=>"LOWK",
   :city=>"Klagenfurt",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Klagenfurt, Austria"},
 "KJK"=>
  {:iata=>"KJK",
   :name=>"Kortrijk-Wevelgem International Airport",
   :icao=>"EBKT",
   :city=>"Wevelgem",
   :country=>'Belgium', :country_code=>'BE',
   :location=>"Wevelgem, Belgium"},
 "KLV"=>
  {:iata=>"KLV",
   :name=>"Karlovy Vary Airport",
   :icao=>"LKKV",
   :city=>"Karlovy Vary",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Karlovy Vary, Czech Republic"},
 "KRP"=>
  {:iata=>"KRP",
   :name=>"Karup Airport",
   :icao=>"EKKA",
   :city=>"Karup",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Karup, Denmark"},
 "KDL"=>
  {:iata=>"KDL",
   :name=>"Kärdla Airport",
   :icao=>"EEKA",
   :city=>"Kärdla",
   :country=>'Estonia', :country_code=>'EE',
   :location=>"Kärdla, Hiiumaa, Estonia"},
 "KAJ"=>
  {:iata=>"KAJ",
   :name=>"Kajaani Airport",
   :icao=>"EFKI",
   :city=>"Kajaani",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kajaani, Finland"},
 "KEM"=>
  {:iata=>"KEM",
   :name=>"Kemi-Tornio Airport",
   :icao=>"EFKE",
   :city=>"Kemi / Tornio",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kemi / Tornio, Finland"},
 "KTT"=>
  {:iata=>"KTT",
   :name=>"Kittilä Airport",
   :icao=>"EFKT",
   :city=>"Kittilä",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kittilä, Finland"},
 "KOK"=>
  {:iata=>"KOK",
   :name=>"Kokkola-Pietarsaari Airport",
   :icao=>"EFKK",
   :city=>"Kokkola / Jakobstad",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kokkola / Jakobstad, Finland"},
 "KUO"=>
  {:iata=>"KUO",
   :name=>"Kuopio Airport",
   :icao=>"EFKU",
   :city=>"Kuopio / Siilinjärvi",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kuopio / Siilinjärvi, Finland"},
 "KAO"=>
  {:iata=>"KAO",
   :name=>"Kuusamo Airport",
   :icao=>"EFKS",
   :city=>"Kuusamo",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kuusamo, Finland"},
 "KHJ"=>
  {:iata=>"KHJ",
   :name=>"Kauhajoki Airport",
   :icao=>"EFKJ",
   :city=>"Kauhajoki",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kauhajoki, Finland"},
 "KAU"=>
  {:iata=>"KAU",
   :name=>"Kauhava Airport",
   :icao=>"EFKA",
   :city=>"Kauhava",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kauhava, Finland"},
 "KTQ"=>
  {:iata=>"KTQ",
   :name=>"Kitee Airport",
   :icao=>"EFIT",
   :city=>"Kitee",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kitee, Finland"},
 "KEV"=>
  {:iata=>"KEV",
   :name=>"Halli Airport",
   :icao=>"EFHA",
   :city=>"Kuorevesi",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Kuorevesi, Finland"},
 "KUT"=>
  {:iata=>"KUT",
   :name=>"Kopitnari Airport (Kutaisi Airport)",
   :icao=>"UGKO",
   :city=>"Kutaisi",
   :country=>'Georgia', :country_code=>'GE',
   :location=>"Kutaisi, Imereti, Georgia"},
 "KSF"=>
  {:iata=>"KSF",
   :name=>"Kassel Calden Airport",
   :icao=>"EDVK",
   :city=>"Kassel",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Kassel, Hesse, Germany"},
 "KEL"=>
  {:iata=>"KEL",
   :name=>"Kiel Holtenau Airport",
   :icao=>"EDHK",
   :city=>"Kiel",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Kiel, Schleswig-Holstein, Germany"},
 "KLT"=>
  {:iata=>"KLT",
   :name=>"Kaiserslautern Airport",
   :city=>"Kaiserslautern",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Kaiserslautern, Germany"},
 "KZG"=>
  {:iata=>"KZG",
   :name=>"Kitzingen Airport",
   :icao=>"ETIN",
   :city=>"Kitzingen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Kitzingen, Bavaria, Germany"},
 "KOQ"=>
  {:iata=>"KOQ",
   :name=>"Koethen Airport",
   :icao=>"",
   :city=>"Koethen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Koethen, Germany"},
 "KLX"=>
  {:iata=>"KLX",
   :name=>"Kalamata Airport",
   :icao=>"LGKL",
   :city=>"Kalamata",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kalamata, Greece"},
 "KSJ"=>
  {:iata=>"KSJ",
   :name=>"Kasos Island Airport",
   :icao=>"LGKS",
   :city=>"Kasos Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kasos Island, Greece"},
 "KZS"=>
  {:iata=>"KZS",
   :name=>"Kastelorizo Island Public Airport",
   :icao=>"LGKJ",
   :city=>"Kastelorizo",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kastelorizo, Greece"},
 "KSO"=>
  {:iata=>"KSO",
   :name=>"Aristotelis Airport",
   :icao=>"LGKA",
   :city=>"Kastoria",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kastoria, Greece"},
 "KVA"=>
  {:iata=>"KVA",
   :name=>"Kavala International Airport, \"Megas Alexandros\"",
   :icao=>"LGKV",
   :city=>"Kavala",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kavala, Greece"},
 "KIT"=>
  {:iata=>"KIT",
   :name=>"Kithira Airport",
   :icao=>"LGKC",
   :city=>"Kithira",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kithira, Greece"},
 "KGS"=>
  {:iata=>"KGS",
   :name=>"Kos Island International Airport",
   :icao=>"LGKO",
   :city=>"Kos Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kos Island, Greece"},
 "KZI"=>
  {:iata=>"KZI",
   :name=>"Kozani National Airport \"Filippos\"",
   :icao=>"LGKZ",
   :city=>"Kozani",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kozani, Greece"},
 "KEF"=>
  {:iata=>"KEF",
   :name=>"Keflavík International Airport",
   :icao=>"BIKF",
   :city=>"Keflavík (near Reykjavík)",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Keflavík (near Reykjavík), Iceland"},
 "KIR"=>
  {:iata=>"KIR",
   :name=>"Kerry Airport",
   :icao=>"EIKY",
   :city=>"Tralee",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Tralee, County Kerry, Ireland"},
 "KKY"=>
  {:iata=>"KKY",
   :name=>"Kilkenny Airport",
   :icao=>"EIKL",
   :city=>"Kilkenny",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Kilkenny, Ireland"},
 "KUN"=>
  {:iata=>"KUN",
   :name=>"Kaunas International Airport",
   :icao=>"EYKA",
   :city=>"Kaunas",
   :country=>'Lithuania', :country_code=>'LT',
   :location=>"Kaunas, Lithuania"},
 "KLJ"=>
  {:iata=>"KLJ",
   :name=>"Klaipeda Airport",
   :icao=>"EYKL",
   :city=>"Klaipėda",
   :country=>'Lithuania', :country_code=>'LT',
   :location=>"Klaipėda, Lithuania"},
 "KKN"=>
  {:iata=>"KKN",
   :name=>"Kirkenes Airport, Høybuktmoen",
   :icao=>"ENKR",
   :city=>"Kirkenes",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Kirkenes, Finnmark, Norway"},
 "KRS"=>
  {:iata=>"KRS",
   :name=>"Kristiansand Airport, Kjevik",
   :icao=>"ENCN",
   :city=>"Kristiansand",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Kristiansand, Vest-Agder, Norway"},
 "KSU"=>
  {:iata=>"KSU",
   :name=>"Kristiansund Airport, Kvernberget",
   :icao=>"ENKB",
   :city=>"Kristiansund",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Kristiansund, Norway"},
 "KTW"=>
  {:iata=>"KTW",
   :name=>"Katowice Airport (Pyrzowice Airport)",
   :icao=>"EPKT",
   :city=>"Katowice / Pyrzowice",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Katowice / Pyrzowice, Poland"},
 "KRK"=>
  {:iata=>"KRK",
   :name=>"John Paul II International Airport (Kraków Airport)",
   :icao=>"EPKK",
   :city=>"Kraków / Balice",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Kraków / Balice, Poland"},
 "KIV"=>
  {:iata=>"KIV",
   :name=>"Chişinău International Airport",
   :icao=>"LUKK",
   :city=>"Chişinău",
   :country=>'Moldova', :country_code=>'MD',
   :location=>"Chişinău, Moldova"},
 "KGD"=>
  {:iata=>"KGD",
   :name=>"Khrabrovo Airport",
   :icao=>"UMKK",
   :city=>"Kaliningrad",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kaliningrad, Russia"},
 "KVR"=>
  {:iata=>"KVR",
   :name=>"Kavalerovo Airport",
   :city=>"Kavalerovo",
   :icao=>"",
   :country=>'Federation', :country_code=>'',
   :location=>"Kavalerovo, Federation"},
 "KZN"=>
  {:iata=>"KZN",
   :name=>"Kazan International Airport",
   :icao=>"UWKD",
   :city=>"Kazan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kazan, Tatarstan, Russia"},
 "KEJ"=>
  {:iata=>"KEJ",
   :name=>"Kemerovo Airport",
   :icao=>"UNEE",
   :city=>"Kemerovo",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kemerovo, Kemerovo Oblast, Russia"},
 "KPW"=>
  {:iata=>"KPW",
   :name=>"Keperveyem Airport",
   :city=>"Keperveyem",
   :icao=>"UHMK",
   :country=>'Federation', :country_code=>'',
   :location=>"Keperveyem, Federation"},
 "KHV"=>
  {:iata=>"KHV",
   :name=>"Khabarovsk Novy Airport",
   :icao=>"UHHH",
   :city=>"Khabarovsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Khabarovsk, Russia"},
 "KDY"=>
  {:iata=>"KDY",
   :name=>"Teply Klyuch Airport",
   :icao=>"",
   :city=>"Khadynga",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Khadynga, Sakha Republic, Russia"},
 "KCK"=>
  {:iata=>"KCK",
   :name=>"Kirensk Airport",
   :icao=>"UIKK",
   :city=>"Kirensk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kirensk, Irkutsk Oblast, Russia"},
 "KVX"=>
  {:iata=>"KVX",
   :name=>"Pobedilovo Airport (Kirov Airport)",
   :icao=>"USKK",
   :city=>"Kirov",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kirov, Kirov Oblast, Russia"},
 "KVK"=>
  {:iata=>"KVK",
   :name=>"Kirovsk Airport (Khibiny Airport)",
   :icao=>"ULMK",
   :city=>"Kirovsk / Apatity",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kirovsk / Apatity, Murmansk Oblast, Russia"},
 "KGP"=>
  {:iata=>"KGP",
   :name=>"Kogalym Airport",
   :icao=>"USRK",
   :city=>"Kogalym",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kogalym, Tyumen Oblast, Russia"},
 "KXK"=>
  {:iata=>"KXK",
   :name=>"Khurba Airport",
   :icao=>"UHKK",
   :city=>"Komsomolsk-on-Amur",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Komsomolsk-on-Amur, Khabarovsk Krai, Russia"},
 "KSZ"=>
  {:iata=>"KSZ",
   :name=>"Kotlas Airport",
   :icao=>"ULKK",
   :city=>"Kotlas",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kotlas, Arkhangelsk Oblast, Russia"},
 "KRR"=>
  {:iata=>"KRR",
   :name=>"Pashkovsky Airport",
   :icao=>"URKK",
   :city=>"Krasnodar",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Krasnodar, Russia"},
 "KJA"=>
  {:iata=>"KJA",
   :name=>"Krasnoyarsk Yemelyanovo Airport",
   :icao=>"UNKL",
   :city=>"Krasnoyarsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Krasnoyarsk, Russia"},
 "KKQ"=>
  {:iata=>"KKQ",
   :name=>"Krasnosel'Kup Airport",
   :city=>"Krasnosel'Kup",
   :icao=>"USDP",
   :country=>'Federation', :country_code=>'',
   :location=>"Krasnosel'Kup, Federation"},
 "KRO"=>
  {:iata=>"KRO",
   :name=>"Kurgan Airport",
   :icao=>"USUU",
   :city=>"Kurgan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kurgan, Russia"},
 "KYZ"=>
  {:iata=>"KYZ",
   :name=>"Kyzyl Airport",
   :icao=>"UNKY",
   :city=>"Kyzyl",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kyzyl, Tuva, Russia"},
 "KUF"=>
  {:iata=>"KUF",
   :name=>"Kurumoch Airport (Samara Airport)",
   :icao=>"UWWW",
   :city=>"Samara",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Samara, Russia"},
 "KLD"=>
  {:iata=>"KLD",
   :name=>"Migalovo Air Base",
   :icao=>"UUEM",
   :city=>"Tver Oblast",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tver Oblast, Russia"},
 "KLF"=>
  {:iata=>"KLF",
   :name=>"Grabtsevo Airport",
   :icao=>"UUBC",
   :city=>"Kaluga",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kaluga, Russia"},
 "KMW"=>
  {:iata=>"KMW",
   :name=>"Kostroma Airport",
   :icao=>"UUBA",
   :city=>"Kostroma",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kostroma, Russia"},
 "KSC"=>
  {:iata=>"KSC",
   :name=>"Košice Airport (Barca Airport)",
   :icao=>"LZKZ",
   :city=>"Košice",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Košice, Slovakia"},
 "KLR"=>
  {:iata=>"KLR",
   :name=>"Kalmar Airport",
   :icao=>"ESMQ",
   :city=>"Kalmar",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Kalmar, Sweden"},
 "KSD"=>
  {:iata=>"KSD",
   :name=>"Karlstad Airport",
   :icao=>"ESOK",
   :city=>"Karlstad",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Karlstad, Sweden"},
 "KRN"=>
  {:iata=>"KRN",
   :name=>"Kiruna Airport",
   :icao=>"ESNQ",
   :city=>"Kiruna",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Kiruna, Sweden"},
 "KRF"=>
  {:iata=>"KRF",
   :name=>"Kramfors-Sollefteå Airport",
   :icao=>"ESNK",
   :city=>"Kramfors / Sollefteå",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Kramfors / Sollefteå, Sweden"},
 "KID"=>
  {:iata=>"KID",
   :name=>"Kristianstad Airport",
   :icao=>"ESMK",
   :city=>"Kristianstad",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Kristianstad, Sweden"},
 "KSK"=>
  {:iata=>"KSK",
   :name=>"Karlskoga Airport",
   :icao=>"ESKK",
   :city=>"Karlskoga",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Karlskoga, Sweden"},
 "KVB"=>
  {:iata=>"KVB",
   :name=>"Skövde Airport",
   :icao=>"ESGR",
   :city=>"Skövde",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Skövde, Sweden"},
 "KCO"=>
  {:iata=>"KCO",
   :name=>"Cengiz Topel Naval Air Station",
   :icao=>"LTBQ",
   :city=>"Kocaeli",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Kocaeli, Turkey"},
 "KCM"=>
  {:iata=>"KCM",
   :name=>"Kahramanmaras Airport",
   :icao=>"LTCN",
   :city=>"Kahramanmaras",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Kahramanmaras, Turkey"},
 "KSY"=>
  {:iata=>"KSY",
   :name=>"Kars Airport",
   :icao=>"LTCF",
   :city=>"Kars",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Kars, Turkey"},
 "KFS"=>
  {:iata=>"KFS",
   :name=>"Kastamonu Airport",
   :icao=>"LTAL",
   :city=>"Kastamonu",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Kastamonu, Turkey"},
 "KYA"=>
  {:iata=>"KYA",
   :name=>"Konya Airport",
   :icao=>"LTAN",
   :city=>"Konya",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Konya, Turkey"},
 "KZR"=>
  {:iata=>"KZR",
   :name=>"Zafer Airport",
   :icao=>"LTBZ",
   :city=>"Kütahya",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Kütahya, Turkey"},
 "KBP"=>
  {:iata=>"KBP",
   :name=>"Boryspil International Airport",
   :icao=>"UKBB",
   :city=>"Kiev",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kiev, Ukraine"},
 "KHE"=>
  {:iata=>"KHE",
   :name=>"Kherson Airport",
   :icao=>"",
   :city=>"Kherson",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kherson, Ukraine"},
 "KCP"=>
  {:iata=>"KCP",
   :name=>"Kamenets-Podolskiy Airport",
   :icao=>"",
   :city=>"Kamianets-Podilskyi",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kamianets-Podilskyi, Ukraine"},
 "KHC"=>
  {:iata=>"KHC",
   :name=>"Kerch Airport (Voykovo Airport)",
   :icao=>"UKFK",
   :city=>"Kerch",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kerch, Ukraine"},
 "KGO"=>
  {:iata=>"KGO",
   :name=>"Kirovograd Airport",
   :icao=>"UKKG",
   :city=>"Kirovohrad",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kirovohrad, Ukraine"},
 "KRQ"=>
  {:iata=>"KRQ",
   :name=>"Kramatorsk Airport",
   :icao=>"UKCK",
   :city=>"Kramatorsk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kramatorsk, Donetsk Oblast, Ukraine"},
 "KHU"=>
  {:iata=>"KHU",
   :name=>"Kremenchuk Airport",
   :icao=>"",
   :city=>"Kremenchuk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kremenchuk, Ukraine"},
 "KWG"=>
  {:iata=>"KWG",
   :name=>"Lozovatka Airport",
   :icao=>"UKDR",
   :city=>"Kryvyi Rih (Krivoy Rog)",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kryvyi Rih (Krivoy Rog), Ukraine"},
 "KOI"=>
  {:iata=>"KOI",
   :name=>"Kirkwall Airport",
   :icao=>"EGPA",
   :city=>"Kirkwall",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Kirkwall, Orkney Islands, United Kingdom"},
 "KNF"=>
  {:iata=>"KNF",
   :name=>"RAF Marham",
   :icao=>"EGYM",
   :city=>"Marham",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Marham, Norfolk, East Anglia, United Kingdom"},
 "KYN"=>
  {:iata=>"KYN",
   :name=>"Milton Keynes Airport",
   :icao=>"",
   :city=>"Milton Keynes",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Milton Keynes, England, United Kingdom"},
 "KRH"=>
  {:iata=>"KRH",
   :name=>"Redhill Airport",
   :icao=>"EGKR",
   :city=>"Redhill",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Redhill, Surrey, England, United Kingdom"},
 "KBL"=>
  {:iata=>"KBL",
   :name=>"Kabul International Airport",
   :icao=>"OAKB",
   :city=>"Kabul",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Kabul, Afghanistan"},
 "KDH"=>
  {:iata=>"KDH",
   :name=>"Kandahar International Airport",
   :icao=>"OAKN",
   :city=>"Kandahar",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Kandahar, Afghanistan"},
 "KHT"=>
  {:iata=>"KHT",
   :name=>"Khost Airport",
   :icao=>"OAKS",
   :city=>"Khost",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Khost, Afghanistan"},
 "KWH"=>
  {:iata=>"KWH",
   :name=>"Khwahan Airport",
   :icao=>"OAHN",
   :city=>"Khwahan",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Khwahan, Afghanistan"},
 "KUR"=>
  {:iata=>"KUR",
   :name=>"Razer Airport",
   :icao=>"OARZ",
   :city=>"Kron Monjan (Karanomunjan)",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Kron Monjan (Karanomunjan), Afghanistan"},
 "KVD"=>
  {:iata=>"KVD",
   :name=>"Gyandzha Airport",
   :icao=>"UBBG",
   :city=>"Ganja",
   :country=>'Azerbaijan', :country_code=>'AZ',
   :location=>"Ganja, Azerbaijan"},
 "KHL"=>
  {:iata=>"KHL",
   :name=>"Khulna Airport",
   :icao=>"VGKN",
   :city=>"Khulna",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Khulna, Bangladesh"},
 "KZD"=>
  {:iata=>"KZD",
   :name=>"Krakor Airport",
   :icao=>"",
   :city=>"Krakor",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Krakor, Cambodia"},
 "KOS"=>
  {:iata=>"KOS",
   :name=>"Sihanoukville Airport (Kompong Som)",
   :icao=>"VDSV",
   :city=>"Sihanoukville",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Sihanoukville, Cambodia"},
 "KMT"=>
  {:iata=>"KMT",
   :name=>"Kampot Airport",
   :icao=>"",
   :city=>"Kampot",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Kampot, Kampot Province, Cambodia"},
 "KKZ"=>
  {:iata=>"KKZ",
   :name=>"Koh Kong Airport",
   :icao=>"VDKK",
   :city=>"Koh Kong",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Koh Kong, Koh Kong Province, Cambodia"},
 "KZK"=>
  {:iata=>"KZK",
   :name=>"Kompong Thom Airport",
   :icao=>"",
   :city=>"Kampong Thom City",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Kampong Thom City, Cambodia"},
 "KZC"=>
  {:iata=>"KZC",
   :name=>"Kampong Chhnang Airport",
   :icao=>"VDKH",
   :city=>"Kampong Chhnang",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Kampong Chhnang, Kampong Chhnang Province, Cambodia"},
 "KTI"=>
  {:iata=>"KTI",
   :name=>"Kratie Airport",
   :icao=>"VDKT",
   :city=>"Kratié",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Kratié, Cambodia"},
 "KWL"=>
  {:iata=>"KWL",
   :name=>"Guilin Liangjiang International Airport",
   :icao=>"ZGKL",
   :city=>"Guilin",
   :country=>'China', :country_code=>'CN',
   :location=>"Guilin, Guangxi, China"},
 "KWE"=>
  {:iata=>"KWE",
   :name=>"Guiyang Longdongbao International Airport",
   :icao=>"ZUGY",
   :city=>"Guiyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Guiyang, Guizhou, China"},
 "KMG"=>
  {:iata=>"KMG",
   :name=>"Kunming Changshui International Airport",
   :icao=>"ZPPP",
   :city=>"Kunming",
   :country=>'China', :country_code=>'CN',
   :location=>"Kunming, Yunnan, China"},
 "KHN"=>
  {:iata=>"KHN",
   :name=>"Nanchang Changbei International Airport",
   :icao=>"ZSCN",
   :city=>"Nanchang",
   :country=>'China', :country_code=>'CN',
   :location=>"Nanchang, Jiangxi, China"},
 "KJI"=>
  {:iata=>"KJI",
   :name=>"Kanas Airport",
   :icao=>"ZWKN",
   :city=>"Burqin County",
   :country=>'China', :country_code=>'CN',
   :location=>"Burqin County, Xinjiang, China"},
 "KOW"=>
  {:iata=>"KOW",
   :name=>"Ganzhou Huangjin Airport",
   :icao=>"ZSGZ",
   :city=>"Ganzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Ganzhou, Jiangxi, China"},
 "KJH"=>
  {:iata=>"KJH",
   :name=>"Kaili Huangping Airport",
   :icao=>"",
   :city=>"Kaili",
   :country=>'China', :country_code=>'CN',
   :location=>"Kaili, Guizhou, China"},
 "KGT"=>
  {:iata=>"KGT",
   :name=>"Kangding Airport",
   :city=>"Kangding",
   :icao=>"ZUKD",
   :country=>'China', :country_code=>'CN',
   :location=>"Kangding, China"},
 "KRY"=>
  {:iata=>"KRY",
   :name=>"Karamay Airport",
   :icao=>"ZWKM",
   :city=>"Karamay",
   :country=>'China', :country_code=>'CN',
   :location=>"Karamay, Xinjiang, China"},
 "KHG"=>
  {:iata=>"KHG",
   :name=>"Kashgar Airport (Kashi Airport)",
   :icao=>"ZWSH",
   :city=>"Kashgar",
   :country=>'China', :country_code=>'CN',
   :location=>"Kashgar, Xinjiang, China"},
 "KRL"=>
  {:iata=>"KRL",
   :name=>"Korla Airport",
   :icao=>"ZWKL",
   :city=>"Korla",
   :country=>'China', :country_code=>'CN',
   :location=>"Korla, Xinjiang, China"},
 "KCA"=>
  {:iata=>"KCA",
   :name=>"Kuqa Qiuci Airport",
   :icao=>"ZWKC",
   :city=>"Kuqa",
   :country=>'China', :country_code=>'CN',
   :location=>"Kuqa, Xinjiang, China"},
 "KNC"=>
  {:iata=>"KNC",
   :name=>"Ji'An Airport",
   :city=>"Ji'An",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Ji'An, China"},
 "KTZ"=>
  {:iata=>"KTZ",
   :name=>"Kwun Tong Airport",
   :city=>"Kwun Tong",
   :icao=>"",
   :country=>'Kong', :country_code=>'',
   :location=>"Kwun Tong, Kong"},
 "KNU"=>
  {:iata=>"KNU",
   :name=>"Kanpur Airport",
   :icao=>"VIKA",
   :city=>"Kanpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kanpur, Uttar Pradesh, India"},
 "KLH"=>
  {:iata=>"KLH",
   :name=>"Kolhapur Airport",
   :icao=>"VAKP",
   :city=>"Kolhapur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kolhapur, India"},
 "KUU"=>
  {:iata=>"KUU",
   :name=>"Bhuntar Airport (Kullu Airport)",
   :icao=>"VIBR",
   :city=>"Kullu / Bhuntar",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kullu / Bhuntar, Himachal Pradesh, India"},
 "KTU"=>
  {:iata=>"KTU",
   :name=>"Kota Airport",
   :icao=>"VIKO",
   :city=>"Kota",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kota, India"},
 "KNO"=>
  {:iata=>"KNO",
   :name=>"Kuala Namu International Airport",
   :icao=>"WIMM",
   :city=>"Medan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Medan, Indonesia"},
 "KNG"=>
  {:iata=>"KNG",
   :name=>"Kaimana Airport",
   :icao=>"WASK",
   :city=>"Kaimana",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kaimana, Papua, Indonesia"},
 "KAZ"=>
  {:iata=>"KAZ",
   :name=>"Kao Airport",
   :icao=>"WAMK",
   :city=>"Kao",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kao, Halmahera, North Maluku, Indonesia"},
 "KDI"=>
  {:iata=>"KDI",
   :name=>"Wolter Monginsidi Airport",
   :icao=>"WAWW",
   :city=>"Kendari",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kendari, Indonesia"},
 "KTG"=>
  {:iata=>"KTG",
   :name=>"Rahadi Usman Airport (Ketapang Airport)",
   :icao=>"WIOK",
   :city=>"Ketapang",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ketapang, West Kalimantan, Indonesia"},
 "KBU"=>
  {:iata=>"KBU",
   :name=>"Stagen Airport",
   :icao=>"WRBK",
   :city=>"Kotabaru",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kotabaru, Kalimantan, Indonesia"},
 "KOE"=>
  {:iata=>"KOE",
   :name=>"El Tari Airport",
   :icao=>"WATT",
   :city=>"Kupang",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kupang, East Nusa Tenggara, Indonesia"},
 "KBX"=>
  {:iata=>"KBX",
   :name=>"Kambuaya Airport",
   :icao=>"",
   :city=>"Kambuaya",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kambuaya, Indonesia"},
 "KCD"=>
  {:iata=>"KCD",
   :name=>"Kamur Airport",
   :icao=>"",
   :city=>"Kamur",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kamur, Indonesia"},
 "KWB"=>
  {:iata=>"KWB",
   :name=>"Karimunjawa Airport",
   :icao=>"",
   :city=>"Karimunjawa",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Karimunjawa, Indonesia"},
 "KBF"=>
  {:iata=>"KBF",
   :name=>"Karubaga Airport",
   :icao=>"",
   :city=>"Karubaga",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Karubaga, Indonesia"},
 "KEQ"=>
  {:iata=>"KEQ",
   :name=>"Kebar Airport",
   :icao=>"WASE",
   :city=>"Kebar",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kebar, Indonesia"},
 "KEA"=>
  {:iata=>"KEA",
   :name=>"Keisah Airport",
   :icao=>"",
   :city=>"Keisah",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Keisah, Indonesia"},
 "KLQ"=>
  {:iata=>"KLQ",
   :name=>"Keluang Airport",
   :icao=>"WIPV",
   :city=>"Keluang",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Keluang, Indonesia"},
 "KEI"=>
  {:iata=>"KEI",
   :name=>"Kepi Airport",
   :icao=>"WAKP",
   :city=>"Kepi",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kepi, Indonesia"},
 "KRC"=>
  {:iata=>"KRC",
   :name=>"Kerinci Airport",
   :icao=>"WIPH",
   :city=>"Kerinci",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kerinci, Indonesia"},
 "KMM"=>
  {:iata=>"KMM",
   :name=>"Kimam Airport",
   :icao=>"",
   :city=>"Kimam",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kimam, Indonesia"},
 "KOX"=>
  {:iata=>"KOX",
   :name=>"Kokonao Airport",
   :icao=>"WABN",
   :city=>"Kokonao",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kokonao, Indonesia"},
 "KCI"=>
  {:iata=>"KCI",
   :name=>"Kon Airport",
   :icao=>"",
   :city=>"Kon",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kon, Indonesia"},
 "KOD"=>
  {:iata=>"KOD",
   :name=>"Kotabangun Airport",
   :icao=>"",
   :city=>"Kotabangun",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Kotabangun, Indonesia"},
 "KLM"=>
  {:iata=>"KLM",
   :name=>"Kalaleh Airport",
   :city=>"Kalaleh",
   :icao=>"OINE",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Kalaleh, Iran"},
 "KNR"=>
  {:iata=>"KNR",
   :name=>"Jam Airport",
   :icao=>"OIBJ",
   :city=>"Kangan",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Kangan, Iran"},
 "KER"=>
  {:iata=>"KER",
   :name=>"Kerman Airport",
   :icao=>"OIKK",
   :city=>"Kerman",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Kerman, Iran"},
 "KSH"=>
  {:iata=>"KSH",
   :name=>"Shahid Ashrafi Esfahani Airport (Kermanshah Airport)",
   :icao=>"OICC",
   :city=>"Kermanshah",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Kermanshah, Iran"},
 "KHD"=>
  {:iata=>"KHD",
   :name=>"Khorramabad Airport",
   :icao=>"OICK",
   :city=>"Khorramabad",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Khorramabad, Iran"},
 "KHY"=>
  {:iata=>"KHY",
   :name=>"Khoy Airport",
   :city=>"Khoy",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Khoy, Iran"},
 "KIH"=>
  {:iata=>"KIH",
   :name=>"Kish International Airport",
   :icao=>"OIBK",
   :city=>"Kish Island",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Kish Island, Iran"},
 "KHA"=>
  {:iata=>"KHA",
   :name=>"Khaneh Airport (Piranshahr Airport)",
   :icao=>"OITH",
   :city=>"Khaneh",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Khaneh, Iran"},
 "KHK"=>
  {:iata=>"KHK",
   :name=>"Khark Island Airport",
   :icao=>"OIBQ",
   :city=>"Khark Island",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Khark Island, Iran"},
 "KOJ"=>
  {:iata=>"KOJ",
   :name=>"Kagoshima Airport",
   :icao=>"RJFK",
   :city=>"Kagoshima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kagoshima, Japan"},
 "KIX"=>
  {:iata=>"KIX",
   :name=>"Kansai International Airport",
   :icao=>"RJBB",
   :city=>"Osaka",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Osaka, Japan"},
 "KKX"=>
  {:iata=>"KKX",
   :name=>"Kikaiga Shima Airport",
   :icao=>"RJKI",
   :city=>"Kikaiga Shima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kikaiga Shima, Kikai-Shima Island, Japan"},
 "KKJ"=>
  {:iata=>"KKJ",
   :name=>"Kokura Airport",
   :icao=>"RJFR",
   :city=>"Kita Kyūshū",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kita Kyūshū, Kyūshū, Japan"},
 "KCZ"=>
  {:iata=>"KCZ",
   :name=>"Kōchi Ryōma Airport",
   :icao=>"RJOK",
   :city=>"Kōchi",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kōchi, Japan"},
 "KMQ"=>
  {:iata=>"KMQ",
   :name=>"Komatsu Airport (Kanazawa Airport)",
   :icao=>"RJNK",
   :city=>"Komatsu",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Komatsu, Ishikawa, Japan"},
 "KMJ"=>
  {:iata=>"KMJ",
   :name=>"Kumamoto Airport",
   :icao=>"RJFT",
   :city=>"Mashiki",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Mashiki, Kumamoto Prefecture, Japan"},
 "KUH"=>
  {:iata=>"KUH",
   :name=>"Kushiro Airport",
   :icao=>"RJCK",
   :city=>"Kushiro",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kushiro, Hokkaidō, Japan"},
 "KMI"=>
  {:iata=>"KMI",
   :name=>"Miyazaki Airport",
   :icao=>"RJFM",
   :city=>"Miyazaki",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Miyazaki, Miyazaki Prefecture, Japan"},
 "KIJ"=>
  {:iata=>"KIJ",
   :name=>"Niigata Airport",
   :icao=>"RJSN",
   :city=>"Niigata",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Niigata, Japan"},
 "KUM"=>
  {:iata=>"KUM",
   :name=>"Yakushima Airport",
   :icao=>"RJFC",
   :city=>"Yakushima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Yakushima, Kagoshima Prefecture, Japan"},
 "KJP"=>
  {:iata=>"KJP",
   :name=>"Kerama Airport",
   :icao=>"ROKR",
   :city=>"Kerama Islands",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kerama Islands, Okinawa, Japan"},
 "KTD"=>
  {:iata=>"KTD",
   :name=>"Kitadaito Airport",
   :icao=>"RORK",
   :city=>"Kitadaito",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kitadaito, Okinawa Prefecture, Japan"},
 "KUJ"=>
  {:iata=>"KUJ",
   :name=>"Kushimoto Airport",
   :icao=>"",
   :city=>"Kushimoto",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kushimoto, Honshū, Japan"},
 "KGF"=>
  {:iata=>"KGF",
   :name=>"Sary-Arka Airport",
   :icao=>"UAKK",
   :city=>"Karaganda",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Karaganda, Kazakhstan"},
 "KOV"=>
  {:iata=>"KOV",
   :name=>"Kokshetau Airport",
   :icao=>"UACK",
   :city=>"Kokshetau",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Kokshetau, Kazakhstan"},
 "KSN"=>
  {:iata=>"KSN",
   :name=>"Kostanay Airport (Narimanovka Airport)",
   :icao=>"UAUU",
   :city=>"Kostanay",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Kostanay, Kazakhstan"},
 "KZO"=>
  {:iata=>"KZO",
   :name=>"Kyzylorda Airport",
   :icao=>"UAOO",
   :city=>"Kyzylorda (Kzyl-Orda)",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Kyzylorda (Kzyl-Orda), Kazakhstan"},
 "KOG"=>
  {:iata=>"KOG",
   :name=>"Khong Airport",
   :icao=>"VLKG",
   :city=>"Khong",
   :country=>'Laos', :country_code=>'',
   :location=>"Khong, Laos"},
 "KUL"=>
  {:iata=>"KUL",
   :name=>"Kuala Lumpur International Airport",
   :icao=>"WMKK",
   :city=>"Sepang (near Kuala Lumpur)",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Sepang (near Kuala Lumpur), Malaysia"},
 "KTE"=>
  {:iata=>"KTE",
   :name=>"Kerteh Airport",
   :icao=>"WMKE",
   :city=>"Kerteh",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kerteh, Terengganu, Malaysia"},
 "KBR"=>
  {:iata=>"KBR",
   :name=>"Sultan Ismail Petra Airport",
   :icao=>"WMKC",
   :city=>"Kota Bharu",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kota Bharu, Kelantan, Malaysia"},
 "KUA"=>
  {:iata=>"KUA",
   :name=>"Sultan Haji Ahmad Shah Airport (RMAF Kuantan)",
   :icao=>"WMKD",
   :city=>"Kuantan",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kuantan, Pahang, Malaysia"},
 "KCH"=>
  {:iata=>"KCH",
   :name=>"Kuching International Airport",
   :icao=>"WBGG",
   :city=>"Kuching",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kuching, Sarawak, Malaysia"},
 "KUD"=>
  {:iata=>"KUD",
   :name=>"Kudat Airport",
   :icao=>"WBKT",
   :city=>"Kudat",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kudat, Sabah, Malaysia"},
 "KPI"=>
  {:iata=>"KPI",
   :name=>"Kapit Airport",
   :icao=>"WBGP",
   :city=>"Kapit",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kapit, Sarawak, Malaysia"},
 "KGU"=>
  {:iata=>"KGU",
   :name=>"Keningau Airport",
   :icao=>"WBKG",
   :city=>"Keningau",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Keningau, Sabah, Malaysia"},
 "KDM"=>
  {:iata=>"KDM",
   :name=>"Kaadedhdhoo Airport",
   :icao=>"VRMT",
   :city=>"Kaadedhdhoo Island",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Kaadedhdhoo Island, Gaafu Dhaalu Atoll, Maldives"},
 "KDO"=>
  {:iata=>"KDO",
   :name=>"Kadhdhoo Airport",
   :icao=>"VRMK",
   :city=>"Kadhdhoo Island",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Kadhdhoo Island, Laamu Atoll, Maldives"},
 "KHR"=>
  {:iata=>"KHR",
   :name=>"Kharkhorin Airport",
   :icao=>"ZMHH",
   :city=>"Kharkhorin",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Kharkhorin, Mongolia"},
 "KMV"=>
  {:iata=>"KMV",
   :name=>"Kalemyo Airport",
   :icao=>"VYKL",
   :city=>"Kalemyo",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Kalemyo, Myanmar (Burma)"},
 "KAW"=>
  {:iata=>"KAW",
   :name=>"Kawthaung Airport",
   :icao=>"VYKT",
   :city=>"Kawthaung",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Kawthaung, Myanmar (Burma)"},
 "KET"=>
  {:iata=>"KET",
   :name=>"Kengtung Airport",
   :icao=>"VYKG",
   :city=>"Kengtung",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Kengtung, Myanmar (Burma)"},
 "KHM"=>
  {:iata=>"KHM",
   :name=>"Khamti Airport",
   :icao=>"VYKI",
   :city=>"Khamti",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Khamti, Myanmar (Burma)"},
 "KYP"=>
  {:iata=>"KYP",
   :name=>"Kyaukpyu Airport",
   :icao=>"VYKP",
   :city=>"Kyaukpyu",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Kyaukpyu, Myanmar (Burma)"},
 "KYT"=>
  {:iata=>"KYT",
   :name=>"Kyauktaw Airport",
   :icao=>"VYKU",
   :city=>"Kyauktaw",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Kyauktaw, Myanmar (Burma)"},
 "KTM"=>
  {:iata=>"KTM",
   :name=>"Tribhuvan International Airport",
   :icao=>"VNKT",
   :city=>"Kathmandu",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Kathmandu, Nepal"},
 "KEP"=>
  {:iata=>"KEP",
   :name=>"Nepalgunj Airport (Mahendra Airport)",
   :icao=>"VNNG",
   :city=>"Nepalgunj",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Nepalgunj, Nepal"},
 "KCF"=>
  {:iata=>"KCF",
   :name=>"Kadanwari Airport",
   :icao=>"",
   :city=>"Kadanwari",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Kadanwari, Pakistan"},
 "KHI"=>
  {:iata=>"KHI",
   :name=>"Jinnah International Airport (Quaid-e-Azam Int'l)",
   :icao=>"OPKC",
   :city=>"Karachi",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Karachi, Pakistan"},
 "KDU"=>
  {:iata=>"KDU",
   :name=>"Skardu Airport",
   :icao=>"OPSD",
   :city=>"Skardu",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Skardu, Pakistan"},
 "KBH"=>
  {:iata=>"KBH",
   :name=>"Kalat Airport",
   :icao=>"OPKL",
   :city=>"Kalat",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Kalat, Pakistan"},
 "KDD"=>
  {:iata=>"KDD",
   :name=>"Khuzdar Airport",
   :icao=>"OPKH",
   :city=>"Khuzdar",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Khuzdar, Pakistan"},
 "KVG"=>
  {:iata=>"KVG",
   :name=>"Kavieng Airport",
   :icao=>"AYKV",
   :city=>"Kavieng",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kavieng, New Ireland Province, Papua New Guinea"},
 "KMA"=>
  {:iata=>"KMA",
   :name=>"Kerema Airport",
   :icao=>"AYKM",
   :city=>"Kerema",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kerema, Papua New Guinea"},
 "KKD"=>
  {:iata=>"KKD",
   :name=>"Kokoda Airport",
   :icao=>"AYKO",
   :city=>"Kokoda",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kokoda, Papua New Guinea"},
 "KBM"=>
  {:iata=>"KBM",
   :name=>"Kabwum Airport",
   :icao=>"AYKB",
   :city=>"Kabwum",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kabwum, Papua New Guinea"},
 "KGW"=>
  {:iata=>"KGW",
   :name=>"Kagi Airport",
   :icao=>"AYKQ",
   :city=>"Kagi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kagi, Papua New Guinea"},
 "KIA"=>
  {:iata=>"KIA",
   :name=>"Kaiapit Airport",
   :icao=>"",
   :city=>"Kaiapit",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kaiapit, Papua New Guinea"},
 "KZF"=>
  {:iata=>"KZF",
   :name=>"Kaintiba Airport",
   :icao=>"AYKT",
   :city=>"Kaintiba",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kaintiba, Papua New Guinea"},
 "KDQ"=>
  {:iata=>"KDQ",
   :name=>"Kamberatoro Airport",
   :icao=>"AYTO",
   :city=>"Kamberatoro",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kamberatoro, Papua New Guinea"},
 "KMF"=>
  {:iata=>"KMF",
   :name=>"Kamina Airport",
   :icao=>"AYKD",
   :city=>"Kamina",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kamina, Papua New Guinea"},
 "KJU"=>
  {:iata=>"KJU",
   :name=>"Kamiraba Airport",
   :icao=>"",
   :city=>"Kamiraba",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kamiraba, Papua New Guinea"},
 "KAQ"=>
  {:iata=>"KAQ",
   :name=>"Kamulai Airport",
   :city=>"Kamulai",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kamulai, Guinea"},
 "KUY"=>
  {:iata=>"KUY",
   :name=>"Kamusi Airport",
   :city=>"Kamusi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kamusi, Guinea"},
 "KEX"=>
  {:iata=>"KEX",
   :name=>"Kanabea Airport",
   :icao=>"AYNB",
   :city=>"Kanabea",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kanabea, Papua New Guinea"},
 "KNE"=>
  {:iata=>"KNE",
   :name=>"Kanainj Airport",
   :icao=>"AYKG",
   :city=>"Kanainj",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kanainj, Papua New Guinea"},
 "KDP"=>
  {:iata=>"KDP",
   :name=>"Kandep Airport",
   :icao=>"AYNN",
   :city=>"Kandep",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kandep, Papua New Guinea"},
 "KDR"=>
  {:iata=>"KDR",
   :name=>"Kandrian Airport",
   :icao=>"AYKC",
   :city=>"Kandrian",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kandrian, Papua New Guinea"},
 "KTK"=>
  {:iata=>"KTK",
   :name=>"Kanua Airport",
   :icao=>"",
   :city=>"Kanua",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kanua, Papua New Guinea"},
 "KPL"=>
  {:iata=>"KPL",
   :name=>"Kapal Airport",
   :icao=>"",
   :city=>"Kapal",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kapal, Papua New Guinea"},
 "KAK"=>
  {:iata=>"KAK",
   :name=>"Kar Airport",
   :icao=>"",
   :city=>"Kar",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kar, Papua New Guinea"},
 "KRX"=>
  {:iata=>"KRX",
   :name=>"Kar Kar Airport",
   :icao=>"AYKR",
   :city=>"Kar Kar",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kar Kar, Papua New Guinea"},
 "KAF"=>
  {:iata=>"KAF",
   :name=>"Karato Airport",
   :icao=>"",
   :city=>"Karato",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Karato, Papua New Guinea"},
 "KRJ"=>
  {:iata=>"KRJ",
   :name=>"Karawari Airport",
   :icao=>"AYQA",
   :city=>"Karawari",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Karawari, Papua New Guinea"},
 "KMR"=>
  {:iata=>"KMR",
   :name=>"Karimui Airport",
   :icao=>"AYRI",
   :city=>"Karimui",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Karimui, Papua New Guinea"},
 "KXR"=>
  {:iata=>"KXR",
   :name=>"Karoola Airport",
   :icao=>"",
   :city=>"Karoola",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Karoola, Papua New Guinea"},
 "KSB"=>
  {:iata=>"KSB",
   :name=>"Kasanombe Airport",
   :icao=>"AYNM",
   :city=>"Kasanombe",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kasanombe, Papua New Guinea"},
 "KWO"=>
  {:iata=>"KWO",
   :name=>"Kawito Airport",
   :icao=>"AYKW",
   :city=>"Kawito",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kawito, Papua New Guinea"},
 "KEG"=>
  {:iata=>"KEG",
   :name=>"Keglsugl Airport",
   :icao=>"AYLG",
   :city=>"Keglsugl",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Keglsugl, Papua New Guinea"},
 "KNL"=>
  {:iata=>"KNL",
   :name=>"Kelanoa Airport",
   :icao=>"",
   :city=>"Kelanoa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kelanoa, Papua New Guinea"},
 "KRU"=>
  {:iata=>"KRU",
   :name=>"Kerau Airport",
   :icao=>"AYEA",
   :city=>"Kerau",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kerau, Papua New Guinea"},
 "KII"=>
  {:iata=>"KII",
   :name=>"Kibuli Airport",
   :icao=>"AYLI",
   :city=>"Kibuli",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kibuli, Papua New Guinea"},
 "KIE"=>
  {:iata=>"KIE",
   :name=>"Aropa Airport",
   :icao=>"AYKT",
   :city=>"Kieta",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kieta, Bougainville Island, Papua New Guinea"},
 "KIZ"=>
  {:iata=>"KIZ",
   :name=>"Kikinonda Airport",
   :icao=>"",
   :city=>"Kikinonda",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kikinonda, Papua New Guinea"},
 "KRI"=>
  {:iata=>"KRI",
   :name=>"Kikori Airport",
   :icao=>"AYKK",
   :city=>"Kikori",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kikori, Papua New Guinea"},
 "KIQ"=>
  {:iata=>"KIQ",
   :name=>"Kira Airport",
   :icao=>"AYRA",
   :city=>"Kira",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kira, Papua New Guinea"},
 "KSG"=>
  {:iata=>"KSG",
   :name=>"Kisengan Airport",
   :icao=>"",
   :city=>"Kisengan",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kisengan, Papua New Guinea"},
 "KVE"=>
  {:iata=>"KVE",
   :name=>"Kitava Airport",
   :icao=>"",
   :city=>"Kitava",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kitava, Papua New Guinea"},
 "KWX"=>
  {:iata=>"KWX",
   :name=>"Kiwai Island Airport",
   :icao=>"",
   :city=>"Kiwai Island",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kiwai Island, Papua New Guinea"},
 "KMB"=>
  {:iata=>"KMB",
   :name=>"Koinambe Airport",
   :icao=>"",
   :city=>"Koinambe",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Koinambe, Papua New Guinea"},
 "KOR"=>
  {:iata=>"KOR",
   :name=>"Kokoro Airport",
   :icao=>"AYRO",
   :city=>"Kokoro",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kokoro, Papua New Guinea"},
 "KQL"=>
  {:iata=>"KQL",
   :name=>"Kol Airport",
   :icao=>"AYOL",
   :city=>"Kol",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kol, Papua New Guinea"},
 "KCJ"=>
  {:iata=>"KCJ",
   :name=>"Komaio Airport",
   :icao=>"",
   :city=>"Komaio",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Komaio, Papua New Guinea"},
 "KOM"=>
  {:iata=>"KOM",
   :name=>"Komo-Manda Airport",
   :icao=>"",
   :city=>"Komo-Manda",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Komo-Manda, Papua New Guinea"},
 "KPM"=>
  {:iata=>"KPM",
   :name=>"Kompiam Airport",
   :icao=>"AYAQ",
   :city=>"Kompiam",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kompiam, Papua New Guinea"},
 "KPF"=>
  {:iata=>"KPF",
   :name=>"Kondubol Airport",
   :icao=>"AYDL",
   :city=>"Kondubol",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kondubol, Papua New Guinea"},
 "KGB"=>
  {:iata=>"KGB",
   :name=>"Konge Airport",
   :icao=>"AYOE",
   :city=>"Konge",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Konge, Papua New Guinea"},
 "KPA"=>
  {:iata=>"KPA",
   :name=>"Kopiago Airport",
   :icao=>"AYKG",
   :city=>"Kopiago",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kopiago, Papua New Guinea"},
 "KDE"=>
  {:iata=>"KDE",
   :name=>"Koroba Airport",
   :icao=>"AYOW",
   :city=>"Koroba",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Koroba, Papua New Guinea"},
 "KSP"=>
  {:iata=>"KSP",
   :name=>"Kosipe Airport",
   :icao=>"AYOP",
   :city=>"Kosipe",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kosipe, Papua New Guinea"},
 "KUP"=>
  {:iata=>"KUP",
   :name=>"Kupiano Airport",
   :icao=>"",
   :city=>"Kupiano",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kupiano, Papua New Guinea"},
 "KUQ"=>
  {:iata=>"KUQ",
   :name=>"Kuri Airport",
   :icao=>"AYKU",
   :city=>"Kuri",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kuri, Papua New Guinea"},
 "KWV"=>
  {:iata=>"KWV",
   :name=>"Kurwina Airport",
   :icao=>"",
   :city=>"Kurwina",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Kurwina, Papua New Guinea"},
 "KUX"=>
  {:iata=>"KUX",
   :name=>"Kuyol Airport",
   :city=>"Kuyol",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kuyol, Guinea"},
 "KYX"=>
  {:iata=>"KYX",
   :name=>"Yalumet Airport",
   :icao=>"AYYE",
   :city=>"Yalumet",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Yalumet, Papua New Guinea"},
 "KPE"=>
  {:iata=>"KPE",
   :name=>"Yapsiei Airport",
   :icao=>"AYYP",
   :city=>"Yapsiei",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Yapsiei, Papua New Guinea"},
 "KSX"=>
  {:iata=>"KSX",
   :name=>"Yasuru Airport",
   :icao=>"AYYR",
   :city=>"Yasuru",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Yasuru, Papua New Guinea"},
 "KGH"=>
  {:iata=>"KGH",
   :name=>"Yongai Airport",
   :icao=>"AYJO",
   :city=>"Yongai",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Yongai, Papua New Guinea"},
 "KLO"=>
  {:iata=>"KLO",
   :name=>"Kalibo International Airport",
   :icao=>"RPVK",
   :city=>"Kalibo",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Kalibo, Aklan, Philippines"},
 "KHH"=>
  {:iata=>"KHH",
   :name=>"Kaohsiung International Airport",
   :icao=>"RCKH",
   :city=>"Kaohsiung",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Kaohsiung, Taiwan"},
 "KNH"=>
  {:iata=>"KNH",
   :name=>"Kinmen Airport",
   :icao=>"RCBS",
   :city=>"Kinmen",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Kinmen, Taiwan"},
 "KYD"=>
  {:iata=>"KYD",
   :name=>"Lanyu Airport",
   :icao=>"RCLY",
   :city=>"Orchid Island",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Orchid Island, Taitung County, Taiwan"},
 "KUV"=>
  {:iata=>"KUV",
   :name=>"Gunsan Airport",
   :icao=>"RKJK",
   :city=>"Gunsan",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Gunsan, South Korea"},
 "KWJ"=>
  {:iata=>"KWJ",
   :name=>"Gwangju Airport",
   :icao=>"RKJJ",
   :city=>"Gwangju (Kwangju)",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Gwangju (Kwangju), South Korea"},
 "KPO"=>
  {:iata=>"KPO",
   :name=>"Pohang Airport",
   :icao=>"RKTH",
   :city=>"Pohang",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Pohang, South Korea"},
 "KAG"=>
  {:iata=>"KAG",
   :name=>"Gangneung Airbase",
   :icao=>"RKNN",
   :city=>"Kangnung (Gangneung)",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Kangnung (Gangneung), South Korea"},
 "KDW"=>
  {:iata=>"KDW",
   :name=>"Victoria Reservoir Kandy Seaplane Base",
   :city=>"Kandy",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Kandy, Lanka"},
 "KDZ"=>
  {:iata=>"KDZ",
   :name=>"Polgolla Reservoir Airport",
   :city=>"Kandy",
   :icao=>"",
   :country=>'Lanka', :country_code=>'',
   :location=>"Kandy, Lanka"},
 "KCT"=>
  {:iata=>"KCT",
   :name=>"Koggala Airport",
   :icao=>"VCCK",
   :city=>"Galle",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Galle, Sri Lanka"},
 "KEZ"=>
  {:iata=>"KEZ",
   :name=>"Ali Al Salem Airport",
   :icao=>"",
   :city=>"Ali Al Salem",
   :country=>'Kuwait', :country_code=>'KW',
   :location=>"Ali Al Salem, Kuwait"},
 "KQT"=>
  {:iata=>"KQT",
   :name=>"Qurghonteppa International Airport",
   :city=>"Kurgon-Tyube",
   :icao=>"UTDT",
   :country=>'Tajikistan', :country_code=>'TJ',
   :location=>"Kurgon-Tyube, Tajikistan"},
 "KKC"=>
  {:iata=>"KKC",
   :name=>"Khon Kaen Airport",
   :icao=>"VTUK",
   :city=>"Khon Kaen",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Khon Kaen, Thailand"},
 "KBV"=>
  {:iata=>"KBV",
   :name=>"Krabi Airport",
   :icao=>"VTSG",
   :city=>"Krabi",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Krabi, Thailand"},
 "KOP"=>
  {:iata=>"KOP",
   :name=>"Nakhon Phanom Airport",
   :icao=>"VTUW",
   :city=>"Nakhon Phanom",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Nakhon Phanom, Thailand"},
 "KDT"=>
  {:iata=>"KDT",
   :name=>"Kamphaeng Saen Airport",
   :icao=>"VTBK",
   :city=>"Nakhon Pathom",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Nakhon Pathom, Thailand"},
 "KKM"=>
  {:iata=>"KKM",
   :name=>"Sa Pran Nak Airport",
   :icao=>"VTBH",
   :city=>"Lop Buri",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Lop Buri, Thailand"},
 "KRW"=>
  {:iata=>"KRW",
   :name=>"Turkmenbashi Airport",
   :icao=>"UTAK",
   :city=>"Türkmenbaşy",
   :country=>'Turkmenistan', :country_code=>'TM',
   :location=>"Türkmenbaşy, Turkmenistan, Turkmenistan"},
 "KSQ"=>
  {:iata=>"KSQ",
   :name=>"Karshi Airport / Karshi-Khanabad Air Base",
   :icao=>"UTSL",
   :city=>"Karshi",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Karshi, Uzbekistan"},
 "KON"=>
  {:iata=>"KON",
   :name=>"Kon Tum Airport",
   :icao=>"",
   :city=>"Kon Tum",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Kon Tum, Vietnam"},
 "KIK"=>
  {:iata=>"KIK",
   :name=>"Kirkuk Airport",
   :icao=>"ORKK",
   :city=>"Kirkuk",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Kirkuk, Iraq"},
 "KSW"=>
  {:iata=>"KSW",
   :name=>"Kiryat Shmona Airport (Qiryat Shemona Airport)",
   :icao=>"LLKS",
   :city=>"Kiryat Shmona (Qiryat Shemona)",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Kiryat Shmona (Qiryat Shemona), Israel"},
 "KWI"=>
  {:iata=>"KWI",
   :name=>"Kuwait International Airport",
   :icao=>"OKBK",
   :city=>"Kuwait City",
   :country=>'Kuwait', :country_code=>'KW',
   :location=>"Kuwait City, Kuwait"},
 "KYE"=>
  {:iata=>"KYE",
   :name=>"Rene Mouawad Air Base (Kleyate Airport)",
   :icao=>"OLKA",
   :city=>"Kleyate / Tripoli",
   :country=>'Lebanon', :country_code=>'LB',
   :location=>"Kleyate / Tripoli, Lebanon"},
 "KHS"=>
  {:iata=>"KHS",
   :name=>"Khasab Airport",
   :icao=>"OOKB",
   :city=>"Khasab",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Khasab, Oman"},
 "KAM"=>
  {:iata=>"KAM",
   :name=>"Kamaran Airport",
   :icao=>"ODKM",
   :city=>"Kamaran",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Kamaran, Yemen"},
 "KMC"=>
  {:iata=>"KMC",
   :name=>"King Khaled Military City Airport",
   :icao=>"",
   :city=>"King Khaled Military City",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"King Khaled Military City, Saudi Arabia"},
 "KMX"=>
  {:iata=>"KMX",
   :name=>"King Khaled Air Base",
   :icao=>"OEKM",
   :city=>"Khamis Mushait",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Khamis Mushait, Saudi Arabia"},
 "KAC"=>
  {:iata=>"KAC",
   :name=>"Kamishly Airport",
   :icao=>"OSKL",
   :city=>"Kamishly (Kameshli",
   :country=>'Syria', :country_code=>'SY',
   :location=>"Kamishly (Kameshli, Qamishli), Syria"},
 "KAE"=>
  {:iata=>"KAE",
   :name=>"Kake Airport (FAA: AFE)",
   :icao=>"PAFE",
   :city=>"Kake",
   :country=>'United States', :country_code=>'US',

   :location=>"Kake, Alaska, United States"},
 "KAL"=>
  {:iata=>"KAL",
   :name=>"Kaltag Airport",
   :icao=>"PAKV",
   :city=>"Kaltag",
   :country=>'United States', :country_code=>'US',

   :location=>"Kaltag, Alaska, United States"},
 "KBC"=>
  {:iata=>"KBC",
   :name=>"Birch Creek Airport (FAA: Z91)",
   :icao=>"",
   :city=>"Birch Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Birch Creek, Alaska, United States"},
 "KBE"=>
  {:iata=>"KBE",
   :name=>"Bell Island Hot Springs Seaplane Base",
   :icao=>"",
   :city=>"Bell Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Bell Island, Alaska, United States"},
 "KBW"=>
  {:iata=>"KBW",
   :name=>"Chignik Bay Seaplane Base (FAA: Z78)",
   :icao=>"",
   :city=>"Chignik",
   :country=>"United States", :country_code=>'US',
   :location=>"Chignik, Alaska, United States."},
 "KCC"=>
  {:iata=>"KCC",
   :name=>"Coffman Cove Seaplane Base",
   :icao=>"",
   :city=>"Coffman Cove",
   :country=>'United States', :country_code=>'US',

   :location=>"Coffman Cove, Alaska, United States"},
 "KCG"=>
  {:iata=>"KCG",
   :name=>"Chignik Fisheries Airport (closed)",
   :icao=>"",
   :city=>"Chignik",
   :country=>"United States",
   :country_code => "US",
   :location=>"Chignik, Alaska, United States."},
 "KCL"=>
  {:iata=>"KCL",
   :name=>"Chignik Lagoon Airport (Chignik Flats Airport)",
   :icao=>"",
   :city=>"Chignik Lagoon",
   :country=>'United States', :country_code=>'US',
   :location=>"Chignik Lagoon, Alaska, United States"},
 "KCN"=>
  {:iata=>"KCN",
   :name=>"Chernofski Harbor Seaplane Base",
   :icao=>"",
   :city=>"Chernofski Harbor",
   :country=>'United States', :country_code=>'US',

   :location=>"Chernofski Harbor, Alaska, United States"},
 "KCQ"=>
  {:iata=>"KCQ",
   :name=>"Chignik Lake Airport (FAA: A79)",
   :icao=>"",
   :city=>"Chignik Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Chignik Lake, Alaska, United States"},
 "KCR"=>
  {:iata=>"KCR",
   :name=>"Colorado Creek Airport",
   :icao=>"",
   :city=>"Colorado Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Colorado Creek, Alaska, United States"},
 "KDG"=>
  {:iata=>"KDG",
   :name=>"Kardjali Airport",
   :icao=>"",
   :city=>"Kardjali",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Kardjali, Bulgaria"},
 "KDK"=>
  {:iata=>"KDK",
   :name=>"Kodiak Municipal Airport",
   :icao=>"PAKD",
   :city=>"Kodiak",
   :country=>'United States', :country_code=>'US',

   :location=>"Kodiak, Alaska, United States"},
 "KEB"=>
  {:iata=>"KEB",
   :name=>"Nanwalek Airport (English Bay Airport)",
   :icao=>"",
   :city=>"Nanwalek (English Bay)",
   :country=>'United States', :country_code=>'US',

   :location=>"Nanwalek (English Bay), Alaska, United States"},
 "KEH"=>
  {:iata=>"KEH",
   :name=>"Kenmore Air Harbor (FAA: S60)",
   :icao=>"",
   :city=>"Kenmore",
   :country=>'United States', :country_code=>'US',

   :location=>"Kenmore, Washington, United States"},
 "KEK"=>
  {:iata=>"KEK",
   :name=>"Ekwok Airport",
   :icao=>"",
   :city=>"Ekwok",
   :country=>'United States', :country_code=>'US',

   :location=>"Ekwok, Alaska, United States"},
 "KFP"=>
  {:iata=>"KFP",
   :name=>"False Pass Airport",
   :icao=>"PAKF",
   :city=>"False Pass",
   :country=>'United States', :country_code=>'US',

   :location=>"False Pass, Alaska, United States"},
 "KGK"=>
  {:iata=>"KGK",
   :name=>"Koliganek Airport (FAA: JZZ)",
   :icao=>"PAJZ",
   :city=>"Koliganek",
   :country=>'United States', :country_code=>'US',

   :location=>"Koliganek, Alaska, United States"},
 "KGX"=>
  {:iata=>"KGX",
   :name=>"Grayling Airport",
   :icao=>"",
   :city=>"Grayling",
   :country=>'United States', :country_code=>'US',

   :location=>"Grayling, Alaska, United States"},
 "KGZ"=>
  {:iata=>"KGZ",
   :name=>"Glacier Creek Airport",
   :icao=>"",
   :city=>"Glacier Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Glacier Creek, Alaska, United States"},
 "KIB"=>
  {:iata=>"KIB",
   :name=>"Ivanof Bay Seaplane Base",
   :icao=>"",
   :city=>"Ivanof Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Ivanof Bay, Alaska, United States"},
 "KIC"=>
  {:iata=>"KIC",
   :name=>"Mesa Del Rey Airport",
   :icao=>"KKIC",
   :city=>"King City",
   :country=>'United States', :country_code=>'US',

   :location=>"King City, California, United States"},
 "KIP"=>
  {:iata=>"KIP",
   :name=>"Kickapoo Downtown Airport (FAA: CWC)",
   :icao=>"KCWC",
   :city=>"Wichita Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Wichita Falls, Texas, United States"},
 "KKA"=>
  {:iata=>"KKA",
   :name=>"Koyuk Alfred Adams Airport",
   :icao=>"PAKK",
   :city=>"Koyuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Koyuk, Alaska, United States"},
 "KKB"=>
  {:iata=>"KKB",
   :name=>"Kitoi Bay Seaplane Base",
   :icao=>"",
   :city=>"Kitoi Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Kitoi Bay, Alaska, United States"},
 "KKH"=>
  {:iata=>"KKH",
   :name=>"Kongiganak Airport (FAA: DUY)",
   :icao=>"PADY",
   :city=>"Kongiganak",
   :country=>'United States', :country_code=>'US',

   :location=>"Kongiganak, Alaska, United States"},
 "KKI"=>
  {:iata=>"KKI",
   :name=>"Akiachak Seaplane Base",
   :icao=>"",
   :city=>"Akiachak",
   :country=>'United States', :country_code=>'US',

   :location=>"Akiachak, Alaska, United States"},
 "KKK"=>
  {:iata=>"KKK",
   :name=>"Kalakaket Creek Air Station (FAA: 1KC)",
   :icao=>"",
   :city=>"Kalakaket Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Kalakaket Creek, Alaska, United States"},
 "KKL"=>
  {:iata=>"KKL",
   :name=>"Karluk Lake Seaplane Base",
   :icao=>"",
   :city=>"Karluk Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Karluk Lake, Alaska, United States"},
 "KKT"=>
  {:iata=>"KKT",
   :name=>"Kentland Municipal Airport (FAA: 50I)",
   :icao=>"",
   :city=>"Kentland",
   :country=>'United States', :country_code=>'US',

   :location=>"Kentland, Indiana, United States"},
 "KKU"=>
  {:iata=>"KKU",
   :name=>"Ekuk Airport",
   :icao=>"",
   :city=>"Ekuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Ekuk, Alaska, United States"},
 "KLA"=>
  {:iata=>"KLA",
   :name=>"Kampala Airport",
   :icao=>"HUKC",
   :city=>"Kampala",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Kampala, Uganda"},
 "KLG"=>
  {:iata=>"KLG",
   :name=>"Kalskag Airport",
   :icao=>"PALG",
   :city=>"Kalskag",
   :country=>'United States', :country_code=>'US',

   :location=>"Kalskag, Alaska, United States"},
 "KLL"=>
  {:iata=>"KLL",
   :name=>"Levelock Airport (FAA: 9Z8)",
   :icao=>"",
   :city=>"Levelock",
   :country=>'United States', :country_code=>'US',

   :location=>"Levelock, Alaska, United States"},
 "KLN"=>
  {:iata=>"KLN",
   :name=>"Larsen Bay Airport (FAA: 2A3)",
   :icao=>"PALB",
   :city=>"Larsen Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Larsen Bay, Alaska, United States"},
 "KLS"=>
  {:iata=>"KLS",
   :name=>"Southwest Washington Regional Airport (was Kelso-Longview)",
   :icao=>"KKLS",
   :city=>"Kelso",
   :country=>'United States', :country_code=>'US',

   :location=>"Kelso, Washington, United States"},
 "KLW"=>
  {:iata=>"KLW",
   :name=>"Klawock Airport (FAA: AKW)",
   :icao=>"PAKW",
   :city=>"Klawock",
   :country=>'United States', :country_code=>'US',

   :location=>"Klawock, Alaska, United States"},
 "KMO"=>
  {:iata=>"KMO",
   :name=>"Manokotak Airport (FAA: MBA)",
   :icao=>"PAMB",
   :city=>"Manokotak",
   :country=>'United States', :country_code=>'US',

   :location=>"Manokotak, Alaska, United States"},
 "KMY"=>
  {:iata=>"KMY",
   :name=>"Moser Bay Seaplane Base",
   :icao=>"",
   :city=>"Moser Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Moser Bay, Kodiak Island Borough, Alaska, United States"},
 "KNB"=>
  {:iata=>"KNB",
   :name=>"Kanab Municipal Airport",
   :icao=>"KKNB",
   :city=>"Kanab",
   :country=>'United States', :country_code=>'US',

   :location=>"Kanab, Utah, United States"},
 "KNK"=>
  {:iata=>"KNK",
   :name=>"Kokhanok Airport (FAA: 9K2)",
   :icao=>"PFKK",
   :city=>"Kokhanok",
   :country=>'United States', :country_code=>'US',

   :location=>"Kokhanok, Alaska, United States"},
 "KNT"=>
  {:iata=>"KNT",
   :name=>"Kennett Memorial Airport (FAA: TKX)",
   :icao=>"KTKX",
   :city=>"Kennett",
   :country=>'United States', :country_code=>'US',

   :location=>"Kennett, Missouri, United States"},
 "KNW"=>
  {:iata=>"KNW",
   :name=>"New Stuyahok Airport",
   :icao=>"PANW",
   :city=>"New Stuyahok",
   :country=>'United States', :country_code=>'US',

   :location=>"New Stuyahok, Alaska, United States"},
 "KOA"=>
  {:iata=>"KOA",
   :name=>"Kona International Airport",
   :icao=>"PHKO",
   :city=>"Kailua / Kona",
   :country=>'United States', :country_code=>'US',

   :location=>"Kailua / Kona, Hawaii, United States"},
 "KOT"=>
  {:iata=>"KOT",
   :name=>"Kotlik Airport (FAA: 2A9)",
   :icao=>"PFKO",
   :city=>"Kotlik",
   :country=>'United States', :country_code=>'US',

   :location=>"Kotlik, Alaska, United States"},
 "KOY"=>
  {:iata=>"KOY",
   :name=>"Olga Bay Seaplane Base",
   :icao=>"",
   :city=>"Olga Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Olga Bay, Kodiak Island Borough, Alaska, United States"},
 "KOZ"=>
  {:iata=>"KOZ",
   :name=>"Ouzinkie Airport (FAA: 4K5)",
   :icao=>"",
   :city=>"Ouzinkie",
   :country=>'United States', :country_code=>'US',

   :location=>"Ouzinkie, Alaska, United States"},
 "KPB"=>
  {:iata=>"KPB",
   :name=>"Point Baker Seaplane Base",
   :icao=>"",
   :city=>"Point Baker",
   :country=>'United States', :country_code=>'US',

   :location=>"Point Baker, Alaska, United States"},
 "KPC"=>
  {:iata=>"KPC",
   :name=>"Port Clarence Coast Guard Station",
   :icao=>"PAPC",
   :city=>"Port Clarence",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Clarence, Alaska, United States"},
 "KPH"=>
  {:iata=>"KPH",
   :name=>"Pauloff Harbor Seaplane Base",
   :icao=>"",
   :city=>"Sanak Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Sanak Island, Alaska, United States"},
 "KPN"=>
  {:iata=>"KPN",
   :name=>"Kipnuk Airport (FAA: IIK)",
   :icao=>"PAKI",
   :city=>"Kipnuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Kipnuk, Alaska, United States"},
 "KPR"=>
  {:iata=>"KPR",
   :name=>"Port Williams Seaplane Base",
   :icao=>"",
   :city=>"Port Williams",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Williams, Kodiak Island Borough, Alaska, United States"},
 "KPT"=>
  {:iata=>"KPT",
   :name=>"Jackpot Airport (Hayden Field) (FAA: 06U)",
   :icao=>"",
   :city=>"Jackpot",
   :country=>'United States', :country_code=>'US',

   :location=>"Jackpot, Nevada, United States"},
 "KPV"=>
  {:iata=>"KPV",
   :name=>"Perryville Airport (FAA: PEV)",
   :icao=>"PAPE",
   :city=>"Perryville",
   :country=>'United States', :country_code=>'US',

   :location=>"Perryville, Alaska, United States"},
 "KPY"=>
  {:iata=>"KPY",
   :name=>"Port Bailey Seaplane Base",
   :icao=>"",
   :city=>"Port Bailey",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Bailey, Kodiak Island Borough, Alaska, United States"},
 "KQA"=>
  {:iata=>"KQA",
   :name=>"Akutan Seaplane Base",
   :icao=>"",
   :city=>"Akutan",
   :country=>'United States', :country_code=>'US',

   :location=>"Akutan, Alaska, United States"},
 "KSM"=>
  {:iata=>"KSM",
   :name=>"St. Mary's Airport",
   :icao=>"PASM",
   :city=>"St. Mary's",
   :country=>'United States', :country_code=>'US',

   :location=>"St. Mary's, Alaska, United States"},
 "KTB"=>
  {:iata=>"KTB",
   :name=>"Thorne Bay Seaplane Base",
   :icao=>"",
   :city=>"Thorne Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Thorne Bay, Alaska, United States"},
 "KTH"=>
  {:iata=>"KTH",
   :name=>"Tikchik Lodge Seaplane Base (FAA: AK56)",
   :icao=>"",
   :city=>"Tikchik",
   :country=>'United States', :country_code=>'US',

   :location=>"Tikchik, Alaska, United States"},
 "KTN"=>
  {:iata=>"KTN",
   :name=>"Ketchikan International Airport",
   :icao=>"PAKT",
   :city=>"Ketchikan",
   :country=>'United States', :country_code=>'US',

   :location=>"Ketchikan, Alaska, United States"},
 "KTS"=>
  {:iata=>"KTS",
   :name=>"Brevig Mission Airport",
   :icao=>"PFKT",
   :city=>"Brevig Mission",
   :country=>'United States', :country_code=>'US',

   :location=>"Brevig Mission, Alaska, United States"},
 "KUK"=>
  {:iata=>"KUK",
   :name=>"Kasigluk Airport (FAA: Z09)",
   :icao=>"PFKA",
   :city=>"Kasigluk",
   :country=>'United States', :country_code=>'US',

   :location=>"Kasigluk, Alaska, United States"},
 "KVC"=>
  {:iata=>"KVC",
   :name=>"King Cove Airport",
   :icao=>"PAVC",
   :city=>"King Cove",
   :country=>'United States', :country_code=>'US',

   :location=>"King Cove, Alaska, United States"},
 "KVL"=>
  {:iata=>"KVL",
   :name=>"Kivalina Airport",
   :icao=>"PAVL",
   :city=>"Kivalina",
   :country=>'United States', :country_code=>'US',

   :location=>"Kivalina, Alaska, United States"},
 "KVM"=>
  {:iata=>"KVM",
   :name=>"Markovo Airport",
   :icao=>"UHMO",
   :city=>"Markovo",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Markovo, Chukotka Autonomous Okrug, Russia"},
 "KWF"=>
  {:iata=>"KWF",
   :name=>"Waterfall Seaplane Base",
   :icao=>"",
   :city=>"Waterfall",
   :country=>'United States', :country_code=>'US',

   :location=>"Waterfall, Alaska, United States"},
 "KWK"=>
  {:iata=>"KWK",
   :name=>"Kwigillingok Seaplane Base",
   :icao=>"",
   :city=>"Kwigillingok",
   :country=>'United States', :country_code=>'US',

   :location=>"Kwigillingok, Alaska, United States"},
 "KWN"=>
  {:iata=>"KWN",
   :name=>"Quinhagak Airport (FAA: AQH)",
   :icao=>"PAQH",
   :city=>"Quinhagak",
   :country=>'United States', :country_code=>'US',

   :location=>"Quinhagak, Alaska, United States"},
 "KWP"=>
  {:iata=>"KWP",
   :name=>"West Point Village Seaplane Base",
   :icao=>"",
   :city=>"West Point",
   :country=>'United States', :country_code=>'US',

   :location=>"West Point, Kodiak Island Borough, Alaska, United States"},
 "KWS"=>
  {:iata=>"KWS",
   :name=>"Kwailabesi Airport",
   :icao=>"",
   :city=>"Kwailabesi",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Kwailabesi, Solomon Islands"},
 "KWT"=>
  {:iata=>"KWT",
   :name=>"Kwethluk Airport",
   :icao=>"PFKW",
   :city=>"Kwethluk",
   :country=>'United States', :country_code=>'US',

   :location=>"Kwethluk, Alaska, United States"},
 "KXA"=>
  {:iata=>"KXA",
   :name=>"Kasaan Seaplane Base",
   :icao=>"",
   :city=>"Kasaan",
   :country=>'United States', :country_code=>'US',

   :location=>"Kasaan, Alaska, United States"},
 "KYK"=>
  {:iata=>"KYK",
   :name=>"Karluk Airport",
   :icao=>"PAKY",
   :city=>"Karluk",
   :country=>'United States', :country_code=>'US',

   :location=>"Karluk, Alaska, United States"},
 "KYU"=>
  {:iata=>"KYU",
   :name=>"Koyukuk Airport",
   :icao=>"PFKU",
   :city=>"Koyukuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Koyukuk, Alaska, United States"},
 "KZB"=>
  {:iata=>"KZB",
   :name=>"Zachar Bay Seaplane Base",
   :icao=>"",
   :city=>"Zachar Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Zachar Bay, Alaska, United States"}}

end
