# encoding: UTF-8
def airp_8
  {"GSL"=>
  {:iata=>"GSL",
   :name=>"Taltheilei Narrows Airport",
   :city=>"Taltheilei Narrows",
   :icao=>"CFA7",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Taltheilei Narrows, Canada"},
 "GOH"=>
  {:iata=>"GOH",
   :name=>"Nuuk Airport (Godthåb/Nuuk Airport)",
   :icao=>"BGGH",
   :city=>"Nuuk",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Nuuk, Greenland"},
 "GDL"=>
  {:iata=>"GDL",
   :name=>"Don Miguel Hidalgo y Costilla International Airport",
   :icao=>"MMGL",
   :city=>"Guadalajara",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Guadalajara, Mexico"},
 "GYM"=>
  {:iata=>"GYM",
   :name=>"General José María Yáñez International Airport",
   :icao=>"MMGM",
   :city=>"Guaymas",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Guaymas, Sonora, Mexico"},
 "GUB"=>
  {:iata=>"GUB",
   :name=>"Guerrero Negro Airport",
   :icao=>"MMGR",
   :city=>"Guerrero Negro",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Guerrero Negro, Baja California Sur, Mexico"},
 "GCC"=>
  {:iata=>"GCC",
   :name=>"Gillette-Campbell County Airport",
   :icao=>"KGCC",
   :city=>"Gillette",
   :country=>'United States', :country_code=>'US',

   :location=>"Gillette, Wyoming, United States"},
 "GEY"=>
  {:iata=>"GEY",
   :name=>"South Big Horn County Airport",
   :icao=>"KGEY",
   :city=>"Greybull",
   :country=>'United States', :country_code=>'US',

   :location=>"Greybull, Wyoming, United States"},
 "GNR"=>
  {:iata=>"GNR",
   :name=>"Dr. Arturo Umberto Illia Airport",
   :icao=>"SAHR",
   :city=>"General Roca",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"General Roca, Río Negro, Argentina"},
 "GGS"=>
  {:iata=>"GGS",
   :name=>"Gobernador Gregores Airport",
   :icao=>"SAWR",
   :city=>"Gobernador Gregores",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Gobernador Gregores, Santa Cruz, Argentina"},
 "GPO"=>
  {:iata=>"GPO",
   :name=>"General Pico Airport",
   :icao=>"SAZG",
   :city=>"General Pico",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"General Pico, La Pampa, Argentina"},
 "GHU"=>
  {:iata=>"GHU",
   :name=>"Gualeguaychú Airport",
   :icao=>"SAAG",
   :city=>"Gualeguaychú",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Gualeguaychú, Entre Ríos, Argentina"},
 "GYA"=>
  {:iata=>"GYA",
   :name=>"Guayaramerín Airport",
   :icao=>"SLGY",
   :city=>"Guayaramerín",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Guayaramerín, Bolivia"},
 "GIG"=>
  {:iata=>"GIG",
   :name=>"Rio de Janeiro-Galeão International Airport",
   :icao=>"SBGL",
   :city=>"Rio de Janeiro",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rio de Janeiro, Brazil"},
 "GRU"=>
  {:iata=>"GRU",
   :name=>"São Paulo-Guarulhos International Airport",
   :icao=>"SBGR",
   :city=>"Guarulhos (near São Paulo)",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guarulhos (near São Paulo), São Paulo (state), Brazil"},
 "GYN"=>
  {:iata=>"GYN",
   :name=>"Santa Genoveva Airport",
   :icao=>"SBGO",
   :city=>"Goiânia",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Goiânia, Goiás, Brazil"},
 "GVR"=>
  {:iata=>"GVR",
   :name=>"Governador Valadares Airport",
   :icao=>"SBGV",
   :city=>"Governador Valadares",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Governador Valadares, Minas Gerais, Brazil"},
 "GPB"=>
  {:iata=>"GPB",
   :name=>"Tancredo Thomas de Farias Airport",
   :icao=>"SBGU",
   :city=>"Guarapuava",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guarapuava, Paraná, Brazil"},
 "GEL"=>
  {:iata=>"GEL",
   :name=>"Sepé Tiaraju Airport",
   :icao=>"SBNM",
   :city=>"Santo Ângelo",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santo Ângelo, Rio Grande do Sul, Brazil"},
 "GCV"=>
  {:iata=>"GCV",
   :name=>"Gravatai Airport",
   :city=>"Gravatai",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Gravatai, Brazil"},
 "GDP"=>
  {:iata=>"GDP",
   :name=>"Guadalupe Airport",
   :icao=>"SNGD",
   :city=>"Guadalupe",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guadalupe, Piauí, Brazil"},
 "GJM"=>
  {:iata=>"GJM",
   :name=>"Guajara-Mirim Airport",
   :icao=>"SBGM",
   :city=>"Guajara-Mirim",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guajara-Mirim, Rondônia, Brazil"},
 "GNM"=>
  {:iata=>"GNM",
   :name=>"Guanambi Airport",
   :icao=>"SNGI",
   :city=>"Guanambi",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guanambi, Bahia, Brazil"},
 "GUZ"=>
  {:iata=>"GUZ",
   :name=>"Guarapari Airport",
   :icao=>"SNGA",
   :city=>"Guarapari",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guarapari, Espírito Santo, Brazil"},
 "GUJ"=>
  {:iata=>"GUJ",
   :name=>"Guaratingueta Airport",
   :icao=>"SBGW",
   :city=>"Guaratingueta",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guaratingueta, São Paulo, Brazil"},
 "GMS"=>
  {:iata=>"GMS",
   :name=>"Guimarães Airport",
   :icao=>"SNGM",
   :city=>"Guimarães",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Guimarães, Maranhão, Brazil"},
 "GRP"=>
  {:iata=>"GRP",
   :name=>"Gurupi Airport",
   :icao=>"SWGI",
   :city=>"Gurupi",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Gurupi, Goiás, Brazil"},
 "GXQ"=>
  {:iata=>"GXQ",
   :name=>"Teniente Vidal Airport",
   :icao=>"SCCY",
   :city=>"Coyhaique",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Coyhaique, Chile"},
 "GRA"=>
  {:iata=>"GRA",
   :name=>"Gamarra Airport",
   :icao=>"",
   :city=>"Gamarra",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Gamarra, Colombia"},
 "GPI"=>
  {:iata=>"GPI",
   :name=>"Guapi Airport",
   :icao=>"SKGP",
   :city=>"Guapi",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Guapi, Colombia"},
 "GGL"=>
  {:iata=>"GGL",
   :name=>"Gilgal Airport",
   :city=>"Gilgal",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Gilgal, Colombia"},
 "GIR"=>
  {:iata=>"GIR",
   :name=>"Santiago Vila Airport",
   :icao=>"SKGI",
   :city=>"Girardot",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Girardot, Colombia"},
 "GCA"=>
  {:iata=>"GCA",
   :name=>"Guacamaya Airport",
   :icao=>"",
   :city=>"Guacamaya",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Guacamaya, Colombia"},
 "GAA"=>
  {:iata=>"GAA",
   :name=>"Guamal Airport",
   :icao=>"",
   :city=>"Guamal",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Guamal, Colombia"},
 "GMC"=>
  {:iata=>"GMC",
   :name=>"Guerima Airport",
   :icao=>"",
   :city=>"Guerima",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Guerima, Colombia"},
 "GPS"=>
  {:iata=>"GPS",
   :name=>"Seymour Airport",
   :icao=>"SEGS",
   :city=>"Baltra Island",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Baltra Island, Galápagos Islands, Ecuador"},
 "GYE"=>
  {:iata=>"GYE",
   :name=>"José Joaquín de Olmedo International Airport",
   :icao=>"SEGU",
   :city=>"Santiago de Guayaquil",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Santiago de Guayaquil, Ecuador"},
 "GEO"=>
  {:iata=>"GEO",
   :name=>"Cheddi Jagan International Airport (Timehri Int'l)",
   :icao=>"SYCJ",
   :city=>"Georgetown",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Georgetown, Guyana"},
 "GFO"=>
  {:iata=>"GFO",
   :name=>"Bartica Airport",
   :icao=>"SYBT",
   :city=>"Bartica",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Bartica, Guyana"},
 "GUQ"=>
  {:iata=>"GUQ",
   :name=>"Guanare Airport",
   :icao=>"SVGU",
   :city=>"Guanare",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Guanare, Venezuela"},
 "GDO"=>
  {:iata=>"GDO",
   :name=>"Guasdualito Airport (Vare Maria Airport)",
   :icao=>"SVGD",
   :city=>"Guasdualito",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Guasdualito, Venezuela"},
 "GUI"=>
  {:iata=>"GUI",
   :name=>"Guiria Airport",
   :icao=>"SVGI",
   :city=>"Guiria",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Guiria, Venezuela"},
 "GYL"=>
  {:iata=>"GYL",
   :name=>"Argyle Airport",
   :icao=>"YARG",
   :city=>"Argyle",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Argyle, Western Australia, Australia"},
 "GET"=>
  {:iata=>"GET",
   :name=>"Geraldton Airport",
   :icao=>"YGEL",
   :city=>"Geraldton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Geraldton, Western Australia, Australia"},
 "GLT"=>
  {:iata=>"GLT",
   :name=>"Gladstone Airport",
   :icao=>"YGLA",
   :city=>"Gladstone",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gladstone, Queensland, Australia"},
 "GOV"=>
  {:iata=>"GOV",
   :name=>"Nhulunbuy Airport",
   :icao=>"YPGV",
   :city=>"Gove",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gove, Northern Territory, Australia"},
 "GFN"=>
  {:iata=>"GFN",
   :name=>"Grafton Airport",
   :icao=>"YGFN",
   :city=>"Grafton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Grafton, New South Wales, Australia"},
 "GTS"=>
  {:iata=>"GTS",
   :name=>"Granite Downs Airport",
   :icao=>"YGDW",
   :city=>"Granite Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Granite Downs, South Australia, Australia"},
 "GFF"=>
  {:iata=>"GFF",
   :name=>"Griffith Airport",
   :icao=>"YGTH",
   :city=>"Griffith",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Griffith, New South Wales, Australia"},
 "GTE"=>
  {:iata=>"GTE",
   :name=>"Groote Eylandt Airport",
   :icao=>"YGTE",
   :city=>"Groote Eylandt",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Groote Eylandt, Northern Territory, Australia"},
 "GPD"=>
  {:iata=>"GPD",
   :name=>"Mount Gordon Mine Airport",
   :city=>"Mount Gordon",
   :icao=>"YGON",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mount Gordon, Australia"},
 "GIC"=>
  {:iata=>"GIC",
   :name=>"Boigu Island Airport",
   :icao=>"YBOI",
   :city=>"Boigu Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Boigu Island, Queensland, Australia"},
 "GBP"=>
  {:iata=>"GBP",
   :name=>"Gamboola Airport",
   :icao=>"YGAM",
   :city=>"Gamboola",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gamboola, Queensland, Australia"},
 "GPN"=>
  {:iata=>"GPN",
   :name=>"Garden Point Airport",
   :icao=>"YGPT",
   :city=>"Pirlangimpi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Pirlangimpi, Northern Territory, Australia"},
 "GSC"=>
  {:iata=>"GSC",
   :name=>"Gascoyne Junction Airport",
   :icao=>"YGSC",
   :city=>"Gascoyne Junction",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gascoyne Junction, Western Australia, Australia"},
 "GAH"=>
  {:iata=>"GAH",
   :name=>"Gayndah Airport",
   :icao=>"YGAY",
   :city=>"Gayndah",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gayndah, Queensland, Australia"},
 "GEX"=>
  {:iata=>"GEX",
   :name=>"Geelong Airport",
   :icao=>"YGLG",
   :city=>"Grovedale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Grovedale, Victoria, Australia"},
 "GEE"=>
  {:iata=>"GEE",
   :name=>"George Town Aerodrome",
   :icao=>"YGTO",
   :city=>"George Town",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"George Town, Tasmania, Australia"},
 "GTT"=>
  {:iata=>"GTT",
   :name=>"Georgetown Airport",
   :icao=>"YGTN",
   :city=>"Georgetown",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Georgetown, Queensland, Australia"},
 "GBV"=>
  {:iata=>"GBV",
   :name=>"Gibb River Airport",
   :icao=>"YGIB",
   :city=>"Gibb River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gibb River, Western Australia, Australia"},
 "GLI"=>
  {:iata=>"GLI",
   :name=>"Glen Innes Airport",
   :icao=>"YGLI",
   :city=>"Glen Innes",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Glen Innes, New South Wales, Australia"},
 "GLG"=>
  {:iata=>"GLG",
   :name=>"Glengyle Airport",
   :icao=>"YGLE",
   :city=>"Glengyle Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Glengyle Station, Queensland, Australia"},
 "GLM"=>
  {:iata=>"GLM",
   :name=>"Glenormiston Airport",
   :icao=>"YGLO",
   :city=>"Glenormiston",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Glenormiston, Queensland, Australia"},
 "GLY"=>
  {:iata=>"GLY",
   :name=>"Goldsworthy Airport",
   :icao=>"",
   :city=>"Goldsworthy",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Goldsworthy, Western Australia, Australia"},
 "GOO"=>
  {:iata=>"GOO",
   :name=>"Goondiwindi Airport",
   :icao=>"YGDI",
   :city=>"Goondiwindi",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Goondiwindi, Queensland, Australia"},
 "GDD"=>
  {:iata=>"GDD",
   :name=>"Gordon Downs Airport",
   :icao=>"YGDN",
   :city=>"Gordon Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gordon Downs, Western Australia, Australia"},
 "GOS"=>
  {:iata=>"GOS",
   :name=>"Gosford Airport",
   :icao=>"",
   :city=>"Gosford",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gosford, New South Wales, Australia"},
 "GUL"=>
  {:iata=>"GUL",
   :name=>"Goulburn Airport",
   :icao=>"YGLB",
   :city=>"Goulburn",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Goulburn, New South Wales, Australia"},
 "GBL"=>
  {:iata=>"GBL",
   :name=>"Goulburn Island Airport",
   :icao=>"YGBI",
   :city=>"Goulburn Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Goulburn Island, Northern Territory, Australia"},
 "GKL"=>
  {:iata=>"GKL",
   :name=>"Great Keppel Island Airport",
   :icao=>"YGKL",
   :city=>"Great Keppel Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Great Keppel Island, Queensland, Australia"},
 "GVP"=>
  {:iata=>"GVP",
   :name=>"Greenvale Airport",
   :icao=>"YGNV",
   :city=>"Greenvale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Greenvale, Queensland, Australia"},
 "GGD"=>
  {:iata=>"GGD",
   :name=>"Gregory Downs Airport",
   :icao=>"YGDS",
   :city=>"Gregory Downs",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gregory Downs, Queensland, Australia"},
 "GFE"=>
  {:iata=>"GFE",
   :name=>"Grenfell Airport",
   :city=>"Grenfell",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Grenfell, Australia"},
 "GUH"=>
  {:iata=>"GUH",
   :name=>"Gunnedah Airport",
   :icao=>"YGDH",
   :city=>"Gunnedah",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gunnedah, New South Wales, Australia"},
 "GYP"=>
  {:iata=>"GYP",
   :name=>"Gympie Airport",
   :icao=>"YGYM",
   :city=>"Gympie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Gympie, Queensland, Australia"},
 "GSN"=>
  {:iata=>"GSN",
   :name=>"Mount Gunson Airport",
   :icao=>"YMGN",
   :city=>"Mount Gunson",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mount Gunson, South Australia, Australia"},
 "GMR"=>
  {:iata=>"GMR",
   :name=>"Totegegie Airport (Gambier Island Airport)",
   :icao=>"NTGJ",
   :city=>"Mangareva",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Mangareva, Gambier Islands, French Polynesia"},
 "GUM"=>
  {:iata=>"GUM",
   :name=>"Antonio B. Won Pat International Airport (Guam International)",
   :icao=>"PGUM",
   :city=>"Hagåtña",
   :country=>'Guam', :country_code=>'GU',
   :location=>"Hagåtña, Guam"},
 "GEA"=>
  {:iata=>"GEA",
   :name=>"Nouméa Magenta Airport",
   :icao=>"NWWM",
   :city=>"Nouméa",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Nouméa, New Caledonia"},
 "GIS"=>
  {:iata=>"GIS",
   :name=>"Gisborne Airport",
   :icao=>"NZGS",
   :city=>"Gisborne",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Gisborne, New Zealand"},
 "GBZ"=>
  {:iata=>"GBZ",
   :name=>"Claris Airfield (Great Barrier Island Airport)",
   :icao=>"NZGB",
   :city=>"Great Barrier Island",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Great Barrier Island, New Zealand"},
 "GMN"=>
  {:iata=>"GMN",
   :name=>"Greymouth Airport",
   :icao=>"NZGM",
   :city=>"Greymouth",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Greymouth, New Zealand"},
 "GTN"=>
  {:iata=>"GTN",
   :name=>"Glentanner Aerodrome",
   :icao=>"NZGT",
   :city=>"Mount Cook",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Mount Cook, New Zealand"},
 "GBS"=>
  {:iata=>"GBS",
   :name=>"Port Fitzroy Seaplane Base",
   :city=>"Port Fitzroy",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Port Fitzroy, Zealand"},
 "GTA"=>
  {:iata=>"GTA",
   :name=>"Gatokae Airport",
   :icao=>"",
   :city=>"Gatokae",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Gatokae, Solomon Islands"},
 "GZO"=>
  {:iata=>"GZO",
   :name=>"Nusatupe Airport",
   :icao=>"AGGN",
   :city=>"Gizo / Nusatupe",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Gizo / Nusatupe, Western Province, Solomon Islands"},
 "GEF"=>
  {:iata=>"GEF",
   :name=>"Geva Airstrip",
   :icao=>"AGEV",
   :city=>"Liangia",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Liangia, Vella Lavella Island, Solomon Islands"},
 "GSI"=>
  {:iata=>"GSI",
   :name=>"Guadalcanal Airport",
   :icao=>"",
   :city=>"Guadalcanal",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Guadalcanal, Solomon Islands"},
 "GBA"=>
  {:iata=>"GBA",
   :name=>"Big Bay Airport",
   :city=>"Big Bay",
   :icao=>"",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Big Bay, Vanuatu"},
 "GGT"=>
  {:iata=>"GGT",
   :name=>"Exuma International Airport",
   :icao=>"MYEF",
   :city=>"Moss Town",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Moss Town, Great Exuma Island, Bahamas"},
 "GHB"=>
  {:iata=>"GHB",
   :name=>"Governor's Harbour Airport",
   :icao=>"MYEM",
   :city=>"Governor's Harbour",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Governor's Harbour, Eleuthera, Bahamas"},
 "GBI"=>
  {:iata=>"GBI",
   :name=>"Aux Ab Airport",
   :city=>"Grand Bahama",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Grand Bahama, Bahamas"},
 "GHC"=>
  {:iata=>"GHC",
   :name=>"Great Harbour Cay Airport",
   :icao=>"MYBG",
   :city=>"Bullock Harbour",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Bullock Harbour, Berry Islands, Bahamas"},
 "GTC"=>
  {:iata=>"GTC",
   :name=>"Green Turtle Airport",
   :icao=>"",
   :city=>"Green Turtle",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Green Turtle, Bahamas"},
 "GCM"=>
  {:iata=>"GCM",
   :name=>"Owen Roberts International Airport",
   :icao=>"MWCR",
   :city=>"Georgetown",
   :country=>'Cayman Islands', :country_code=>'KY',
   :location=>"Georgetown, Cayman Islands"},
 "GAO"=>
  {:iata=>"GAO",
   :name=>"Mariana Grajales Airport (Los Canos Airport)",
   :icao=>"MUGT",
   :city=>"Guantánamo",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Guantánamo, Cuba"},
 "GER"=>
  {:iata=>"GER",
   :name=>"Rafael Perez Airport",
   :icao=>"MUNG",
   :city=>"Nueva Gerona",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Nueva Gerona, Cuba"},
 "GND"=>
  {:iata=>"GND",
   :name=>"Maurice Bishop International Airport",
   :icao=>"TGPY",
   :city=>"St. George's",
   :country=>'Grenada', :country_code=>'GD',
   :location=>"St. George's, Grenada"},
 "GBJ"=>
  {:iata=>"GBJ",
   :name=>"Marie Galante Airport (Les Bases)",
   :icao=>"TFFM",
   :city=>"Marie Galante",
   :country=>'Guadeloupe', :country_code=>'GP',
   :location=>"Marie Galante, Grand Bourg, Guadeloupe"},
 "GDT"=>
  {:iata=>"GDT",
   :name=>"J.A.G.S. McCartney International Airport (Grand Turk Int'l)",
   :icao=>"MBGT",
   :city=>"Grand Turk Island",
   :country=>'Turks and Caicos Islands', :country_code=>'TC',
   :location=>"Grand Turk Island, Turks and Caicos Islands"},
 "GHA"=>
  {:iata=>"GHA",
   :name=>"Noumérat – Moufdi Zakaria Airport",
   :icao=>"DAUG",
   :city=>"Ghardaia",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Ghardaia, Algeria"},
 "GJL"=>
  {:iata=>"GJL",
   :name=>"Jijel Ferhat Abbas Airport",
   :icao=>"DAAV",
   :city=>"Jijel",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Jijel, Algeria"},
 "GGC"=>
  {:iata=>"GGC",
   :name=>"Lumbala N'guimbo Airport",
   :icao=>"",
   :city=>"Lumbala N'guimbo",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Lumbala N'guimbo, Angola"},
 "GXG"=>
  {:iata=>"GXG",
   :name=>"Negage Airport",
   :icao=>"FNNG",
   :city=>"Negage",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Negage, Angola"},
 "GBE"=>
  {:iata=>"GBE",
   :name=>"Sir Seretse Khama International Airport",
   :icao=>"FBSK",
   :city=>"Gaborone",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Gaborone, Botswana"},
 "GNZ"=>
  {:iata=>"GNZ",
   :name=>"Ghanzi Airport",
   :icao=>"FBGZ",
   :city=>"Ghanzi",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Ghanzi, Botswana"},
 "GID"=>
  {:iata=>"GID",
   :name=>"Gitega Airport",
   :icao=>"HBBE",
   :city=>"Gitega",
   :country=>'Burundi', :country_code=>'BI',
   :location=>"Gitega, Burundi"},
 "GOU"=>
  {:iata=>"GOU",
   :name=>"Garoua International Airport",
   :icao=>"FKKR",
   :city=>"Garoua",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Garoua, Cameroon"},
 "GXX"=>
  {:iata=>"GXX",
   :name=>"Yagoua Airport",
   :icao=>"FKKJ",
   :city=>"Yagoua",
   :country=>'Cameroon', :country_code=>'CM',
   :location=>"Yagoua, Cameroon"},
 "GDI"=>
  {:iata=>"GDI",
   :name=>"Gordil Airport",
   :icao=>"",
   :city=>"Gordil",
   :country=>'Central African Republic', :country_code=>'CF',
   :location=>"Gordil, Central African Republic"},
 "GDA"=>
  {:iata=>"GDA",
   :name=>"Gounda Airport",
   :icao=>"",
   :city=>"Gounda",
   :country=>'Central African Republic', :country_code=>'CF',
   :location=>"Gounda, Central African Republic"},
 "GMM"=>
  {:iata=>"GMM",
   :name=>"Gamboma Airport",
   :icao=>"FCOG",
   :city=>"Gamboma",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Gamboma, Republic of the Congo"},
 "GGN"=>
  {:iata=>"GGN",
   :name=>"Gagnoa Airport",
   :icao=>"DIGA",
   :city=>"Gagnoa",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Gagnoa, Côte d'Ivoire"},
 "GGO"=>
  {:iata=>"GGO",
   :name=>"Guiglo Airport",
   :icao=>"DIGL",
   :city=>"Guiglo",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Guiglo, Côte d'Ivoire"},
 "GMB"=>
  {:iata=>"GMB",
   :name=>"Gambela Airport",
   :icao=>"HAGM",
   :city=>"Gambela",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Gambela, Ethiopia"},
 "GDE"=>
  {:iata=>"GDE",
   :name=>"Gode Airport (Iddidole Airport)",
   :icao=>"HAGO",
   :city=>"Gode",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Gode, Ethiopia"},
 "GDQ"=>
  {:iata=>"GDQ",
   :name=>"Gondar Airport",
   :icao=>"HAGN",
   :city=>"Gondar",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Gondar, Ethiopia"},
 "GLC"=>
  {:iata=>"GLC",
   :name=>"Geladi Airport",
   :icao=>"",
   :city=>"Geladi",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Geladi, Ethiopia"},
 "GHD"=>
  {:iata=>"GHD",
   :name=>"Ghimbi Airport",
   :icao=>"",
   :city=>"Ghimbi",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Ghimbi, Ethiopia"},
 "GNN"=>
  {:iata=>"GNN",
   :name=>"Ghinnir Airport",
   :icao=>"HAGH",
   :city=>"Ghinnir",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Ghinnir, Ethiopia"},
 "GOB"=>
  {:iata=>"GOB",
   :name=>"Robe Airport",
   :icao=>"HAGB",
   :city=>"Goba",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Goba, Ethiopia"},
 "GOR"=>
  {:iata=>"GOR",
   :name=>"Gore Airport",
   :icao=>"HAGR",
   :city=>"Gore",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Gore, Ethiopia"},
 "GAX"=>
  {:iata=>"GAX",
   :name=>"Gamba Airport",
   :icao=>"",
   :city=>"Gamba",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Gamba, Gabon"},
 "GKO"=>
  {:iata=>"GKO",
   :name=>"Kongoboumba Airport",
   :icao=>"",
   :city=>"Kongoboumba",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Kongoboumba, Gabon"},
 "GIM"=>
  {:iata=>"GIM",
   :name=>"Miele Mimbale Airport",
   :icao=>"",
   :city=>"Miele Mimbale",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Miele Mimbale, Gabon"},
 "GII"=>
  {:iata=>"GII",
   :name=>"Siguiri Airport",
   :icao=>"GUSI",
   :city=>"Siguiri",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Siguiri, Guinea"},
 "GGM"=>
  {:iata=>"GGM",
   :name=>"Kakamega Airport",
   :city=>"Kakamega",
   :icao=>"HKKG",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kakamega, Kenya"},
 "GAS"=>
  {:iata=>"GAS",
   :name=>"Garissa Airport",
   :icao=>"HKGA",
   :city=>"Garissa",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Garissa, Kenya"},
 "GRC"=>
  {:iata=>"GRC",
   :name=>"Grand Cess Airport",
   :icao=>"",
   :city=>"Grand Cess",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Grand Cess, Liberia"},
 "GHT"=>
  {:iata=>"GHT",
   :name=>"Ghat Airport",
   :icao=>"HLGT",
   :city=>"Ghat",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Ghat, Libya"},
 "GAQ"=>
  {:iata=>"GAQ",
   :name=>"Gao International Airport",
   :icao=>"GAGO",
   :city=>"Gao",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Gao, Mali"},
 "GUD"=>
  {:iata=>"GUD",
   :name=>"Goundam Airport",
   :icao=>"GAGM",
   :city=>"Goundam",
   :country=>'Mali', :country_code=>'ML',
   :location=>"Goundam, Mali"},
 "GLN"=>
  {:iata=>"GLN",
   :name=>"Goulimime Airport",
   :icao=>"",
   :city=>"Goulimime",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Goulimime, Morocco"},
 "GOG"=>
  {:iata=>"GOG",
   :name=>"Gobabis Airport",
   :icao=>"FYGB",
   :city=>"Gobabis",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Gobabis, Namibia"},
 "GFY"=>
  {:iata=>"GFY",
   :name=>"Grootfontein Airport",
   :icao=>"FYGF",
   :city=>"Grootfontein",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Grootfontein, Namibia"},
 "GMO"=>
  {:iata=>"GMO",
   :name=>"Gombe Lawanti International Airport",
   :city=>"Gombe",
   :icao=>"DNGO",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Gombe, Nigeria"},
 "GYI"=>
  {:iata=>"GYI",
   :name=>"Gisenyi Airport",
   :icao=>"HRYG",
   :city=>"Gisenyi",
   :country=>'Rwanda', :country_code=>'RW',
   :location=>"Gisenyi, Rwanda"},
 "GBK"=>
  {:iata=>"GBK",
   :name=>"Gbangbatok Airport",
   :icao=>"GFGK",
   :city=>"Gbangbatok",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Gbangbatok, Sierra Leone"},
 "GLK"=>
  {:iata=>"GLK",
   :name=>"Galcaio Airport",
   :icao=>"HCMR",
   :city=>"Galcaio",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Galcaio, Somalia"},
 "GBM"=>
  {:iata=>"GBM",
   :name=>"Garba Harre Airport (Garbaharey Airport)",
   :icao=>"",
   :city=>"Garba Harre",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Garba Harre, Somalia"},
 "GSR"=>
  {:iata=>"GSR",
   :name=>"Gardo Airport",
   :icao=>"HCMG",
   :city=>"Gardo",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Gardo, Somalia"},
 "GGR"=>
  {:iata=>"GGR",
   :name=>"Garoe Airport",
   :icao=>"",
   :city=>"Garoe",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Garoe, Somalia"},
 "GRJ"=>
  {:iata=>"GRJ",
   :name=>"George Airport",
   :icao=>"FAGG",
   :city=>"George",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"George, South Africa"},
 "GIY"=>
  {:iata=>"GIY",
   :name=>"Giyani Airport",
   :icao=>"FAGI",
   :city=>"Giyani",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Giyani, South Africa"},
 "GCJ"=>
  {:iata=>"GCJ",
   :name=>"Grand Central Airport",
   :icao=>"FAGC",
   :city=>"Johannesburg",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Johannesburg, South Africa"},
 "GSS"=>
  {:iata=>"GSS",
   :name=>"Sabi Sabi Airport",
   :icao=>"",
   :city=>"Sabi Sabi",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Sabi Sabi, South Africa"},
 "GSU"=>
  {:iata=>"GSU",
   :name=>"Azaza Airport",
   :icao=>"HSGF",
   :city=>"Gedaref",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Gedaref, Sudan"},
 "GBU"=>
  {:iata=>"GBU",
   :name=>"Khashm El Girba Airport",
   :icao=>"HSKG",
   :city=>"Khashm El Girba",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Khashm El Girba, Sudan"},
 "GMA"=>
  {:iata=>"GMA",
   :name=>"Gemana Airport",
   :icao=>"FZFK",
   :city=>"Gemana",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Gemana, Democratic Republic of the Congo"},
 "GOM"=>
  {:iata=>"GOM",
   :name=>"Goma Airport",
   :icao=>"FZNA",
   :city=>"Goma",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Goma, Democratic Republic of the Congo"},
 "GDJ"=>
  {:iata=>"GDJ",
   :name=>"Gandajika Airport",
   :icao=>"FZWC",
   :city=>"Gandajika",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Gandajika, Democratic Republic of the Congo"},
 "GAE"=>
  {:iata=>"GAE",
   :name=>"Gabès - Matmata International Airport",
   :icao=>"DTTG",
   :city=>"Gabès",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Gabès, Tunisia"},
 "GAF"=>
  {:iata=>"GAF",
   :name=>"Gafsa - Ksar International Airport",
   :icao=>"DTTF",
   :city=>"Gafsa",
   :country=>'Tunisia', :country_code=>'TN',
   :location=>"Gafsa, Tunisia"},
 "GTZ"=>
  {:iata=>"GTZ",
   :name=>"Kirawira B Aerodrome",
   :city=>"Grumeti Game Reserve",
   :icao=>"",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Grumeti Game Reserve, Tanzania"},
 "GIT"=>
  {:iata=>"GIT",
   :name=>"Geita Airport",
   :icao=>"",
   :city=>"Geita",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Geita, Tanzania"},
 "GWE"=>
  {:iata=>"GWE",
   :name=>"Thornhill Air Base",
   :icao=>"FVTL",
   :city=>"Gweru",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Gweru, Zimbabwe"},
 "GRZ"=>
  {:iata=>"GRZ",
   :name=>"Graz Airport (Thalerhof Airport)",
   :icao=>"LOWG",
   :city=>"Graz",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Graz, Austria"},
 "GME"=>
  {:iata=>"GME",
   :name=>"Gomel Airport",
   :icao=>"UMGG",
   :city=>"Gomel",
   :country=>'Belarus', :country_code=>'BY',
   :location=>"Gomel, Belarus"},
 "GNA"=>
  {:iata=>"GNA",
   :name=>"Obukhovo Airport",
   :icao=>"UMMG",
   :city=>"Grodno",
   :country=>'Belarus', :country_code=>'BY',
   :location=>"Grodno, Belarus"},
 "GNE"=>
  {:iata=>"GNE",
   :name=>"St. Denijs-Westrem Airport (Ghent Airport)",
   :icao=>"EBGT",
   :city=>"Ghent",
   :country=>'Belgium', :country_code=>'BE',
   :location=>"Ghent, Belgium"},
 "GOZ"=>
  {:iata=>"GOZ",
   :name=>"Gorna Oryahovitsa Airport",
   :icao=>"LBGO",
   :city=>"Gorna Oryahovitsa",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Gorna Oryahovitsa, Bulgaria"},
 "GEC"=>
  {:iata=>"GEC",
   :name=>"Lefkoniko Airport",
   :icao=>"",
   :city=>"Lefkoniko",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Lefkoniko, Cyprus"},
 "GTW"=>
  {:iata=>"GTW",
   :name=>"Holešov Airport",
   :icao=>"LKHO",
   :city=>"Holešov",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Holešov, Zlín, Czech Republic"},
 "GNB"=>
  {:iata=>"GNB",
   :name=>"Grenoble-Isère Airport",
   :icao=>"LFLS",
   :city=>"Grenoble",
   :country=>'France', :country_code=>'FR',
   :location=>"Grenoble, France"},
 "GAT"=>
  {:iata=>"GAT",
   :name=>"Tallard Airport",
   :icao=>"LFNA",
   :city=>"Gap",
   :country=>'France', :country_code=>'FR',
   :location=>"Gap, France"},
 "GFR"=>
  {:iata=>"GFR",
   :name=>"Granville Airport",
   :icao=>"LFRF",
   :city=>"Granville",
   :country=>'France', :country_code=>'FR',
   :location=>"Granville, France"},
 "GWT"=>
  {:iata=>"GWT",
   :name=>"Sylt Airport (Westerland Airport)",
   :icao=>"EDXW",
   :city=>"Westerland",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Westerland, Germany"},
 "GWW"=>
  {:iata=>"GWW",
   :name=>"RAF Gatow",
   :icao=>"EDBG",
   :city=>"Berlin",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Berlin, Germany"},
 "GTI"=>
  {:iata=>"GTI",
   :name=>"Rügen Airport",
   :icao=>"EDCG",
   :city=>"Güttin",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Güttin, Mecklenburg-Vorpommern, Germany"},
 "GKE"=>
  {:iata=>"GKE",
   :name=>"NATO Air Base Geilenkirchen",
   :icao=>"ETNG",
   :city=>"Geilenkirchen",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Geilenkirchen, North Rhine-Westphalia, Germany"},
 "GHF"=>
  {:iata=>"GHF",
   :name=>"Giebelstadt Airport",
   :icao=>"ETEU",
   :city=>"Giebelstadt",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Giebelstadt, Germany"},
 "GUT"=>
  {:iata=>"GUT",
   :name=>"RAF Gütersloh",
   :icao=>"ETUO",
   :city=>"Gütersloh",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Gütersloh, North Rhine-Westphalia, Germany"},
 "GMY"=>
  {:iata=>"GMY",
   :name=>"Rheindahlen Airport",
   :city=>"Rheindahlen",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Rheindahlen, Germany"},
 "GIB"=>
  {:iata=>"GIB",
   :name=>"Gibraltar Airport (North Front Airport)",
   :icao=>"LXGB",
   :city=>"Gibraltar",
   :country=>'Gibraltar', :country_code=>'GI',
   :location=>"Gibraltar"},
 "GPA"=>
  {:iata=>"GPA",
   :name=>"Araxos Airport",
   :icao=>"LGRX",
   :city=>"Araxos / Patras",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Araxos / Patras, Greece"},
 "GJR"=>
  {:iata=>"GJR",
   :name=>"Gjögur Airport",
   :icao=>"BIGJ",
   :city=>"Gjögur",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Gjögur, Iceland"},
 "GRY"=>
  {:iata=>"GRY",
   :name=>"Grímsey Airport",
   :icao=>"BIGR",
   :city=>"Grímsey",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Grímsey, Iceland"},
 "GUU"=>
  {:iata=>"GUU",
   :name=>"Grundarfjörður Airport",
   :icao=>"BIGF",
   :city=>"Grundarfjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Grundarfjörður, Iceland"},
 "GWY"=>
  {:iata=>"GWY",
   :name=>"Galway Airport",
   :icao=>"EICM",
   :city=>"Galway",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Galway, Ireland"},
 "GOA"=>
  {:iata=>"GOA",
   :name=>"Cristoforo Colombo Airport",
   :icao=>"LIMJ",
   :city=>"Genoa",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Genoa, Italy"},
 "GRS"=>
  {:iata=>"GRS",
   :name=>"Grosseto Airport (Baccarini Airport)",
   :icao=>"LIRS",
   :city=>"Grosseto",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Grosseto, Italy"},
 "GBN"=>
  {:iata=>"GBN",
   :name=>"San Giovanni Rotondo Airport",
   :city=>"San Giovanni Rotondo",
   :icao=>"",
   :country=>'Italy', :country_code=>'IT',
   :location=>"San Giovanni Rotondo, Italy"},
 "GZM"=>
  {:iata=>"GZM",
   :name=>"Xewkija Heliport (Gozo Heliport)",
   :icao=>"LMMG",
   :city=>"Xewkija",
   :country=>'Malta', :country_code=>'MT',
   :location=>"Xewkija, Gozo, Malta"},
 "GRQ"=>
  {:iata=>"GRQ",
   :name=>"Groningen Airport Eelde",
   :icao=>"EHGG",
   :city=>"Groningen / Eelde",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Groningen / Eelde, Netherlands"},
 "GLZ"=>
  {:iata=>"GLZ",
   :name=>"Gilze-Rijen Air Base",
   :icao=>"EHGR",
   :city=>"Breda",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Breda, Netherlands"},
 "GLL"=>
  {:iata=>"GLL",
   :name=>"Gol Airport, Klanten",
   :icao=>"ENKL",
   :city=>"Gol",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Gol, Norway"},
 "GDN"=>
  {:iata=>"GDN",
   :name=>"Gdańsk Lech Wałęsa Airport (Rebiechowo Airport)",
   :icao=>"EPGD",
   :city=>"Gdańsk",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Gdańsk, Poland"},
 "GRW"=>
  {:iata=>"GRW",
   :name=>"Graciosa Island Airport",
   :icao=>"LPGR",
   :city=>"Graciosa Island",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Graciosa Island, Azores, Portugal"},
 "GDZ"=>
  {:iata=>"GDZ",
   :name=>"Gelendzhik Airport",
   :icao=>"URKG",
   :city=>"Gelendzhik",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Gelendzhik, Krasnodarskiy, Russia"},
 "GRV"=>
  {:iata=>"GRV",
   :name=>"Grozny Airport",
   :icao=>"URMG",
   :city=>"Grozny",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Grozny, Russia"},
 "GDX"=>
  {:iata=>"GDX",
   :name=>"Sokol Airport",
   :icao=>"UHMM",
   :city=>"Magadan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Magadan, Russia"},
 "GYG"=>
  {:iata=>"GYG",
   :name=>"Magan Airport",
   :icao=>"UEMM",
   :city=>"Magan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Magan, Russia, Sakha Republic, Russia"},
 "GOJ"=>
  {:iata=>"GOJ",
   :name=>"Strigino Airport",
   :icao=>"UWGG",
   :city=>"Nizhny Novgorod",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Nizhny Novgorod, Russia"},
 "GDG"=>
  {:iata=>"GDG",
   :name=>"Magdagachi Airport",
   :icao=>"UHBI",
   :city=>"Magdagachi",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Magdagachi, Russia"},
 "GRO"=>
  {:iata=>"GRO",
   :name=>"Girona-Costa Brava Airport",
   :icao=>"LEGE",
   :city=>"Girona",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Girona, Spain"},
 "GRX"=>
  {:iata=>"GRX",
   :name=>"Granada Jaén Airport",
   :icao=>"LEGR",
   :city=>"Granada",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Granada, Spain"},
 "GMZ"=>
  {:iata=>"GMZ",
   :name=>"La Gomera Airport",
   :icao=>"GCGM",
   :city=>"Alajeró / San Sebastián",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Alajeró / San Sebastián, Canary Islands, Spain"},
 "GEN"=>
  {:iata=>"GEN",
   :name=>"Puente Genil Airport",
   :city=>"Puente Genil",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Puente Genil, Islands"},
 "GOT"=>
  {:iata=>"GOT",
   :name=>"Gothenburg-Landvetter Airport",
   :icao=>"ESGG",
   :city=>"Gothenburg",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Gothenburg, Sweden"},
 "GEV"=>
  {:iata=>"GEV",
   :name=>"Gällivare Airport",
   :icao=>"ESNG",
   :city=>"Gällivare",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Gällivare, Sweden"},
 "GSE"=>
  {:iata=>"GSE",
   :name=>"Gothenburg City Airport (Göteborg City Airport)",
   :icao=>"ESGP",
   :city=>"Gothenburg (Göteborg)",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Gothenburg (Göteborg), Sweden"},
 "GVX"=>
  {:iata=>"GVX",
   :name=>"Gävle-Sandviken Airport",
   :icao=>"ESSK",
   :city=>"Gävle-Sandviken",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Gävle-Sandviken, Sweden"},
 "GVA"=>
  {:iata=>"GVA",
   :name=>"Cointrin International Airport",
   :icao=>"LSGG",
   :city=>"Geneva",
   :country=>'Switzerland', :country_code=>'CH',
   :location=>"Geneva, Switzerland"},
 "GZT"=>
  {:iata=>"GZT",
   :name=>"Oğuzeli Airport",
   :icao=>"LTAJ",
   :city=>"Gaziantep",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Gaziantep, Turkey"},
 "GZP"=>
  {:iata=>"GZP",
   :name=>"Gazipasa Airport",
   :city=>"Gazipasa",
   :icao=>"LTFG",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Gazipasa, Turkey"},
 "GNY"=>
  {:iata=>"GNY",
   :name=>"Şanlıurfa GAP Airport",
   :icao=>"LTCS",
   :city=>"Şanlıurfa",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Şanlıurfa, Turkey"},
 "GLA"=>
  {:iata=>"GLA",
   :name=>"Glasgow International Airport",
   :icao=>"EGPF",
   :city=>"Glasgow",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Glasgow, Scotland, United Kingdom"},
 "GLO"=>
  {:iata=>"GLO",
   :name=>"Gloucester Airport",
   :icao=>"EGBJ",
   :city=>"Gloucester / Cheltenham",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Gloucester / Cheltenham, England, United Kingdom"},
 "GCI"=>
  {:iata=>"GCI",
   :name=>"Guernsey Airport",
   :icao=>"EGJB",
   :city=>"Guernsey",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Guernsey, Channel Islands, United Kingdom"},
 "GSY"=>
  {:iata=>"GSY",
   :name=>"RAF Binbrook",
   :icao=>"EGXB",
   :city=>"Grimsby",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Grimsby, England, United Kingdom"},
 "GQJ"=>
  {:iata=>"GQJ",
   :name=>"Machrihanish Airport",
   :city=>"Machrihanish",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Machrihanish, Kingdom"},
 "GRG"=>
  {:iata=>"GRG",
   :name=>"Gardez Airport",
   :icao=>"OAGZ",
   :city=>"Gardez",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Gardez, Afghanistan"},
 "GZI"=>
  {:iata=>"GZI",
   :name=>"Ghazni Airport",
   :icao=>"OAGN",
   :city=>"Ghazni",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Ghazni, Afghanistan"},
 "GYD"=>
  {:iata=>"GYD",
   :name=>"Heydar Aliyev International Airport (Bina Int'l)",
   :icao=>"UBBB",
   :city=>"Baku",
   :country=>'Azerbaijan', :country_code=>'AZ',
   :location=>"Baku, Azerbaijan"},
 "GBB"=>
  {:iata=>"GBB",
   :name=>"Gara Djebilet Airport",
   :icao=>"",
   :city=>"Gara Djebilet",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Gara Djebilet, Algeria"},
 "GOQ"=>
  {:iata=>"GOQ",
   :name=>"Golmud Airport",
   :icao=>"ZLGM",
   :city=>"Golmud",
   :country=>'China', :country_code=>'CN',
   :location=>"Golmud, Qinghai, China"},
 "GYS"=>
  {:iata=>"GYS",
   :name=>"Guangyuan Airport",
   :icao=>"ZUGU",
   :city=>"Guangyuan",
   :country=>'China', :country_code=>'CN',
   :location=>"Guangyuan, Sichuan, China"},
 "GYU"=>
  {:iata=>"GYU",
   :name=>"Guyuan Liupanshan Airport",
   :city=>"Guyuan",
   :icao=>"ZLGY",
   :country=>'China', :country_code=>'CN',
   :location=>"Guyuan, China"},
 "GXH"=>
  {:iata=>"GXH",
   :name=>"Gannan Xiahe Airport",
   :icao=>"",
   :city=>"Xiahe",
   :country=>'China', :country_code=>'CN',
   :location=>"Xiahe, Gansu, China"},
 "GHN"=>
  {:iata=>"GHN",
   :name=>"Guanghan Airport",
   :icao=>"ZUGH",
   :city=>"Guanghan",
   :country=>'China', :country_code=>'CN',
   :location=>"Guanghan, Sichuan, China"},
 "GAY"=>
  {:iata=>"GAY",
   :name=>"Gaya Airport",
   :icao=>"VEGY",
   :city=>"Gaya",
   :country=>"India",
:country_code=>"IN",
   :location=>"Gaya, India"},
 "GOI"=>
  {:iata=>"GOI",
   :name=>"Goa International Airport (Dabolim Airport)",
   :icao=>"VOGO",
   :city=>"Dabolim",
   :country=>"India",
:country_code=>"IN",
   :location=>"Dabolim, Goa, India"},
 "GOP"=>
  {:iata=>"GOP",
   :name=>"Gorakhpur Airport",
   :icao=>"VEGK",
   :city=>"Gorakhpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Gorakhpur, India"},
 "GAU"=>
  {:iata=>"GAU",
   :name=>"Lokpriya Gopinath Bordoloi International Airport",
   :icao=>"VEGT",
   :city=>"Guwahati",
   :country=>"India",
:country_code=>"IN",
   :location=>"Guwahati, India"},
 "GWL"=>
  {:iata=>"GWL",
   :name=>"Gwalior Airport",
   :icao=>"VIGR",
   :city=>"Gwalior",
   :country=>"India",
:country_code=>"IN",
   :location=>"Gwalior, India"},
 "GUX"=>
  {:iata=>"GUX",
   :name=>"Guna Airport",
   :icao=>"VAGN",
   :city=>"Guna",
   :country=>"India",
:country_code=>"IN",
   :location=>"Guna, India"},
 "GLX"=>
  {:iata=>"GLX",
   :name=>"Gamarmalamo Airport (Galela Airport)",
   :icao=>"WAMA",
   :city=>"Galela",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Galela, North Maluku, Indonesia"},
 "GTO"=>
  {:iata=>"GTO",
   :name=>"Jalaluddin Airport",
   :icao=>"WAMG",
   :city=>"Gorontalo",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Gorontalo, Indonesia"},
 "GNS"=>
  {:iata=>"GNS",
   :name=>"Binaka Airport",
   :icao=>"WIMB",
   :city=>"Gunungsitoli",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Gunungsitoli, Nias Island, Indonesia"},
 "GAV"=>
  {:iata=>"GAV",
   :name=>"Gag Island Airport",
   :icao=>"",
   :city=>"Gag Island",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Gag Island, West Papua, Indonesia"},
 "GEB"=>
  {:iata=>"GEB",
   :name=>"Gebe Airport",
   :icao=>"WAMJ",
   :city=>"Gebe",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Gebe, Maluku, Indonesia"},
 "GCH"=>
  {:iata=>"GCH",
   :name=>"Gachsaran Airport",
   :city=>"Gachsaran",
   :icao=>"OIAH",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Gachsaran, Iran"},
 "GBT"=>
  {:iata=>"GBT",
   :name=>"Gorgon Airport",
   :city=>"Gorgon",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Gorgon, Iran"},
 "GSM"=>
  {:iata=>"GSM",
   :name=>"Gheshm Airport",
   :icao=>"OIKQ",
   :city=>"Gheshm",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Gheshm, Iran"},
 "GZW"=>
  {:iata=>"GZW",
   :name=>"Ghazvin Airport",
   :city=>"Ghazvin",
   :icao=>"OIIK",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Ghazvin, Iran"},
 "GAJ"=>
  {:iata=>"GAJ",
   :name=>"Yamagata Airport (Junmachi Airport)",
   :icao=>"RJSC",
   :city=>"Yamagata",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Yamagata, Honshū, Japan"},
 "GUW"=>
  {:iata=>"GUW",
   :name=>"Atyrau Airport",
   :icao=>"UATG",
   :city=>"Atyrau",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Atyrau, Kazakhstan"},
 "GTB"=>
  {:iata=>"GTB",
   :name=>"Genting Airport",
   :icao=>"",
   :city=>"Genting",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Genting, Malaysia"},
 "GSA"=>
  {:iata=>"GSA",
   :name=>"Long Pasia Airport",
   :icao=>"WBKN",
   :city=>"Long Pasia",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Long Pasia, Sabah, Malaysia"},
 "GTK"=>
  {:iata=>"GTK",
   :name=>"Sungei Tekai Airport",
   :icao=>"",
   :city=>"Sungei Tekai",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Sungei Tekai, Malaysia"},
 "GAN"=>
  {:iata=>"GAN",
   :name=>"Gan Island Airport",
   :icao=>"VRMG",
   :city=>"Gan Island",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Gan Island, Seenu Atoll, Maldives"},
 "GKK"=>
  {:iata=>"GKK",
   :name=>"Kooddoo Island Airport",
   :city=>"Kooddoo Island",
   :icao=>"VRMO",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Kooddoo Island, Maldives"},
 "GAW"=>
  {:iata=>"GAW",
   :name=>"Gangaw Airport",
   :icao=>"VYGG",
   :city=>"Gangaw",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Gangaw, Myanmar (Burma)"},
 "GWA"=>
  {:iata=>"GWA",
   :name=>"Gwa Airport",
   :icao=>"VYGW",
   :city=>"Gwa",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Gwa, Myanmar (Burma)"},
 "GKH"=>
  {:iata=>"GKH",
   :name=>"Gorkha Airport",
   :icao=>"VNGK",
   :city=>"Gorkha",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Gorkha, Nepal"},
 "GIL"=>
  {:iata=>"GIL",
   :name=>"Gilgit Airport",
   :icao=>"OPGT",
   :city=>"Gilgit",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Gilgit, Pakistan"},
 "GWD"=>
  {:iata=>"GWD",
   :name=>"Gwadar Airport",
   :icao=>"OPGD",
   :city=>"Gwadar",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Gwadar, Pakistan"},
 "GRT"=>
  {:iata=>"GRT",
   :name=>"Gujrat Airport",
   :icao=>"",
   :city=>"Gujrat",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Gujrat, Pakistan"},
 "GUR"=>
  {:iata=>"GUR",
   :name=>"Gurney Airport",
   :icao=>"AYGN",
   :city=>"Alotau",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Alotau, Papua New Guinea"},
 "GKA"=>
  {:iata=>"GKA",
   :name=>"Goroka Airport",
   :icao=>"AYGA",
   :city=>"Goroka",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Goroka, Papua New Guinea"},
 "GAR"=>
  {:iata=>"GAR",
   :name=>"Garaina Airport",
   :icao=>"AYGI",
   :city=>"Garaina",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Garaina, Papua New Guinea"},
 "GRL"=>
  {:iata=>"GRL",
   :name=>"Garasa Airport",
   :icao=>"AYGG",
   :city=>"Garasa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Garasa, Papua New Guinea"},
 "GRH"=>
  {:iata=>"GRH",
   :name=>"Garuahi Airport",
   :icao=>"",
   :city=>"Garuahi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Garuahi, Papua New Guinea"},
 "GMI"=>
  {:iata=>"GMI",
   :name=>"Gasmata Airport",
   :icao=>"AYGT",
   :city=>"Gasmata Island",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gasmata Island, Papua New Guinea"},
 "GBC"=>
  {:iata=>"GBC",
   :name=>"Gasuke Airport",
   :icao=>"AYGS",
   :city=>"Gasuke",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gasuke, Papua New Guinea"},
 "GEW"=>
  {:iata=>"GEW",
   :name=>"Gewoia Airport",
   :icao=>"AYGC",
   :city=>"Gewoia",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gewoia, Papua New Guinea"},
 "GWN"=>
  {:iata=>"GWN",
   :name=>"Gnarowein Airport",
   :icao=>"",
   :city=>"Gnarowein",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gnarowein, Papua New Guinea"},
 "GOE"=>
  {:iata=>"GOE",
   :name=>"Gonalia Airport",
   :icao=>"",
   :city=>"Gonalia",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gonalia, Papua New Guinea"},
 "GOC"=>
  {:iata=>"GOC",
   :name=>"Gora Airport",
   :icao=>"AYGX",
   :city=>"Gora",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gora, Papua New Guinea"},
 "GEI"=>
  {:iata=>"GEI",
   :name=>"Green Islands Airport",
   :icao=>"",
   :city=>"Green Islands",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Green Islands, Papua New Guinea"},
 "GVI"=>
  {:iata=>"GVI",
   :name=>"Green River Airport",
   :icao=>"AYGV",
   :city=>"Green River",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Green River, Papua New Guinea"},
 "GUG"=>
  {:iata=>"GUG",
   :name=>"Guari Airport",
   :icao=>"AYGF",
   :city=>"Guari",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Guari, Papua New Guinea"},
 "GAZ"=>
  {:iata=>"GAZ",
   :name=>"Guasopa Airport",
   :icao=>"",
   :city=>"Guasopa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Guasopa, Papua New Guinea"},
 "GLP"=>
  {:iata=>"GLP",
   :name=>"Gulgubip Airport",
   :icao=>"AYUP",
   :city=>"Gulgubip",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gulgubip, Papua New Guinea"},
 "GUE"=>
  {:iata=>"GUE",
   :name=>"Guriaso Airport",
   :icao=>"",
   :city=>"Guriaso",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Guriaso, Papua New Guinea"},
 "GAP"=>
  {:iata=>"GAP",
   :name=>"Gusap Airport",
   :icao=>"AYGP",
   :city=>"Gusap",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Gusap, Papua New Guinea"},
 "GUV"=>
  {:iata=>"GUV",
   :name=>"Mougulu Airport",
   :icao=>"AYML",
   :city=>"Mougulu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Mougulu, Papua New Guinea"},
 "GBF"=>
  {:iata=>"GBF",
   :name=>"Negarbo Airport",
   :icao=>"AYNE",
   :city=>"Negarbo",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Negarbo, Papua New Guinea"},
 "GES"=>
  {:iata=>"GES",
   :name=>"General Santos International Airport (Tambler Airport)",
   :icao=>"RPMR",
   :city=>"General Santos City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"General Santos City, Philippines"},
 "GNI"=>
  {:iata=>"GNI",
   :name=>"Lyudao Airport (Green Island Airport)",
   :icao=>"RCGI",
   :city=>"Lyudao (Green Island)",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Lyudao (Green Island), Taiwan"},
 "GMP"=>
  {:iata=>"GMP",
   :name=>"Gimpo International Airport (Kimpo Airport)",
   :icao=>"RKSS",
   :city=>"Seoul",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Seoul, South Korea"},
 "GIU"=>
  {:iata=>"GIU",
   :name=>"Sigiriya Slaf Base",
   :city=>"Sigiriya",
   :icao=>"VCCS",
   :country=>'Lanka', :country_code=>'',
   :location=>"Sigiriya, Lanka"},
 "GLF"=>
  {:iata=>"GLF",
   :name=>"Golfito Airport",
   :icao=>"MRGF",
   :city=>"Golfito",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Golfito, Costa Rica"},
 "GPL"=>
  {:iata=>"GPL",
   :name=>"Guápiles Airport",
   :icao=>"MRGP",
   :city=>"Guápiles",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Guápiles, Costa Rica"},
 "GUA"=>
  {:iata=>"GUA",
   :name=>"La Aurora International Airport",
   :icao=>"MGGT",
   :city=>"Guatemala City",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Guatemala City, Guatemala"},
 "GJA"=>
  {:iata=>"GJA",
   :name=>"Guanaja Airport",
   :icao=>"MHNJ",
   :city=>"Guanaja",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Guanaja, Bay Islands, Honduras"},
 "GAC"=>
  {:iata=>"GAC",
   :name=>"Gracias Airport",
   :icao=>"",
   :city=>"Gracias",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Gracias, Honduras"},
 "GUO"=>
  {:iata=>"GUO",
   :name=>"Gualaco Airport",
   :city=>"Gualaco",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Gualaco, Honduras"},
 "GHE"=>
  {:iata=>"GHE",
   :name=>"Garachiné Airport",
   :icao=>"",
   :city=>"Garachiné",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Garachiné, Panama"},
 "GBQ"=>
  {:iata=>"GBQ",
   :name=>"Muharraq",
   :city=>"Muharraq",
   :icao=>"",
   :country=>'Bahrain', :country_code=>'BH',
   :location=>"Muharraq, Bahrain"},
 "GSQ"=>
  {:iata=>"GSQ",
   :name=>"Sharq Al-Owainat Airport",
   :icao=>"HEOW",
   :city=>"Sharq Al-Owainat",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Sharq Al-Owainat, Egypt"},
 "GHK"=>
  {:iata=>"GHK",
   :name=>"Gush Katif Airport (closed)",
   :icao=>"LLAZ",
   :city=>"Gush Katif",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Gush Katif, Israel"},
 "GZA"=>
  {:iata=>"GZA",
   :name=>"Yaser Arafat International Airport",
   :icao=>"LVGZ",
   :city=>"Gaza",
   :country=>'Palestine', :country_code=>'PS',
   :location=>"Gaza, Palestine"},
 "GXF"=>
  {:iata=>"GXF",
   :name=>"Seiyun Airport",
   :icao=>"OYSY",
   :city=>"Seiyun",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Seiyun, Yemen"},
 "GIZ"=>
  {:iata=>"GIZ",
   :name=>"Prince Abdullah Bin Abdulaziz Airport (Gizan Airport)",
   :icao=>"OEGN",
   :city=>"Jazan",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Jazan, Saudi Arabia"},
 "GAB"=>
  {:iata=>"GAB",
   :name=>"Gabbs Airport",
   :icao=>"KGAB",
   :city=>"Gabbs",
   :country=>'United States', :country_code=>'US',

   :location=>"Gabbs, Nevada, United States"},
 "GAD"=>
  {:iata=>"GAD",
   :name=>"Northeast Alabama Regional Airport",
   :icao=>"KGAD",
   :city=>"Gadsden",
   :country=>'United States', :country_code=>'US',

   :location=>"Gadsden, Alabama, United States"},
 "GAG"=>
  {:iata=>"GAG",
   :name=>"Gage Airport",
   :icao=>"KGAG",
   :city=>"Gage",
   :country=>'United States', :country_code=>'US',

   :location=>"Gage, Oklahoma, United States"},
 "GAI"=>
  {:iata=>"GAI",
   :name=>"Montgomery County Airpark",
   :icao=>"KGAI",
   :city=>"Gaithersburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Gaithersburg, Maryland, United States"},
 "GAL"=>
  {:iata=>"GAL",
   :name=>"Edward G. Pitka Sr. Airport",
   :icao=>"PAGA",
   :city=>"Galena",
   :country=>'United States', :country_code=>'US',

   :location=>"Galena, Alaska, United States"},
 "GAM"=>
  {:iata=>"GAM",
   :name=>"Gambell Airport",
   :icao=>"PAGM",
   :city=>"Gambell",
   :country=>'United States', :country_code=>'US',

   :location=>"Gambell, Alaska, United States"},
 "GBD"=>
  {:iata=>"GBD",
   :name=>"Great Bend Municipal Airport",
   :icao=>"KGBD",
   :city=>"Great Bend",
   :country=>'United States', :country_code=>'US',

   :location=>"Great Bend, Kansas, United States"},
 "GBG"=>
  {:iata=>"GBG",
   :name=>"Galesburg Municipal Airport",
   :icao=>"KGBG",
   :city=>"Galesburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Galesburg, Illinois, United States"},
 "GBH"=>
  {:iata=>"GBH",
   :name=>"Galbraith Lake Airport",
   :icao=>"PAGB",
   :city=>"Galbraith Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Galbraith Lake, Alaska, United States"},
 "GBR"=>
  {:iata=>"GBR",
   :name=>"Walter J. Koladza Airport",
   :icao=>"KGBR",
   :city=>"Great Barrington",
   :country=>'United States', :country_code=>'US',

   :location=>"Great Barrington, Massachusetts, United States"},
 "GCK"=>
  {:iata=>"GCK",
   :name=>"Garden City Regional Airport",
   :icao=>"KGCK",
   :city=>"Garden City",
   :country=>'United States', :country_code=>'US',

   :location=>"Garden City, Kansas, United States"},
 "GCN"=>
  {:iata=>"GCN",
   :name=>"Grand Canyon National Park Airport",
   :icao=>"KGCN",
   :city=>"Tusayan",
   :country=>'United States', :country_code=>'US',

   :location=>"Tusayan, Arizona, United States"},
 "GCY"=>
  {:iata=>"GCY",
   :name=>"Greeneville-Greene County Municipal Airport",
   :icao=>"KGCY",
   :city=>"Greeneville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greeneville, Tennessee, United States"},
 "GDC"=>
  {:iata=>"GDC",
   :name=>"Donaldson Center Airport (FAA: GYH)",
   :icao=>"KGYH",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, South Carolina, United States"},
 "GDH"=>
  {:iata=>"GDH",
   :name=>"Golden Horn Lodge Seaplane Base (FAA: 3Z8)",
   :icao=>"",
   :city=>"Golden Horn Lodge",
   :country=>'United States', :country_code=>'US',

   :location=>"Golden Horn Lodge, Alaska, United States"},
 "GDM"=>
  {:iata=>"GDM",
   :name=>"Gardner Municipal Airport",
   :icao=>"KGDM",
   :city=>"Gardner",
   :country=>'United States', :country_code=>'US',

   :location=>"Gardner, Massachusetts, United States"},
 "GDV"=>
  {:iata=>"GDV",
   :name=>"Dawson Community Airport",
   :icao=>"KGDV",
   :city=>"Glendive",
   :country=>'United States', :country_code=>'US',

   :location=>"Glendive, Montana, United States"},
 "GDW"=>
  {:iata=>"GDW",
   :name=>"Gladwin Zettel Memorial Airport",
   :icao=>"KGDW",
   :city=>"Gladwin",
   :country=>'United States', :country_code=>'US',

   :location=>"Gladwin, Michigan, United States"},
 "GED"=>
  {:iata=>"GED",
   :name=>"Sussex County Airport",
   :icao=>"KGED",
   :city=>"Georgetown",
   :country=>'United States', :country_code=>'US',

   :location=>"Georgetown, Delaware, United States"},
 "GEG"=>
  {:iata=>"GEG",
   :name=>"Spokane International Airport",
   :icao=>"KGEG",
   :city=>"Spokane",
   :country=>'United States', :country_code=>'US',

   :location=>"Spokane, Washington, United States"},
 "GFA"=>
  {:iata=>"GFA",
   :name=>"Malmstrom Air Force Base (heliport)",
   :icao=>"KGFA",
   :city=>"Great Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Great Falls, Montana, United States"},
 "GFD"=>
  {:iata=>"GFD",
   :name=>"Pope Field",
   :icao=>"KGFD",
   :city=>"Greenfield",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenfield, Indiana, United States"},
 "GFK"=>
  {:iata=>"GFK",
   :name=>"Grand Forks International Airport",
   :icao=>"KGFK",
   :city=>"Grand Forks",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Forks, North Dakota, United States"},
 "GFL"=>
  {:iata=>"GFL",
   :name=>"Floyd Bennett Memorial Airport",
   :icao=>"KGFL",
   :city=>"Glens Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Glens Falls, New York, United States"},
 "GGE"=>
  {:iata=>"GGE",
   :name=>"Georgetown County Airport",
   :icao=>"KGGE",
   :city=>"Georgetown",
   :country=>'United States', :country_code=>'US',

   :location=>"Georgetown, South Carolina, United States"},
 "GGG"=>
  {:iata=>"GGG",
   :name=>"East Texas Regional Airport",
   :icao=>"KGGG",
   :city=>"Longview",
   :country=>'United States', :country_code=>'US',

   :location=>"Longview, Texas, United States"},
 "GGW"=>
  {:iata=>"GGW",
   :name=>"Glasgow Airport (Wokal Field)",
   :icao=>"KGGW",
   :city=>"Glasgow",
   :country=>'United States', :country_code=>'US',

   :location=>"Glasgow, Montana, United States"},
 "GHM"=>
  {:iata=>"GHM",
   :name=>"Centerville Municipal Airport",
   :icao=>"KGHM",
   :city=>"Centerville",
   :country=>'United States', :country_code=>'US',

   :location=>"Centerville, Tennessee, United States"},
 "GIF"=>
  {:iata=>"GIF",
   :name=>"Winter Haven's Gilbert Airport",
   :icao=>"KGIF",
   :city=>"Winter Haven",
   :country=>'United States', :country_code=>'US',

   :location=>"Winter Haven, Florida, United States"},
 "GJT"=>
  {:iata=>"GJT",
   :name=>"Grand Junction Regional Airport (Walker Field)",
   :icao=>"KGJT",
   :city=>"Grand Junction",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Junction, Colorado, United States"},
 "GKD"=>
  {:iata=>"GKD",
   :name=>"Gökçeada Airport",
   :icao=>"LTFK",
   :city=>"Gökçeada",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Gökçeada, Turkey"},
 "GKN"=>
  {:iata=>"GKN",
   :name=>"Gulkana Airport",
   :icao=>"PAGK",
   :city=>"Gulkana",
   :country=>'United States', :country_code=>'US',

   :location=>"Gulkana, Alaska, United States"},
 "GKT"=>
  {:iata=>"GKT",
   :name=>"Gatlinburg-Pigeon Forge Airport",
   :icao=>"KGKT",
   :city=>"Sevierville",
   :country=>'United States', :country_code=>'US',

   :location=>"Sevierville, Tennessee, United States"},
 "GLD"=>
  {:iata=>"GLD",
   :name=>"Goodland Municipal Airport (Renner Field)",
   :icao=>"KGLD",
   :city=>"Goodland",
   :country=>'United States', :country_code=>'US',

   :location=>"Goodland, Kansas, United States"},
 "GLE"=>
  {:iata=>"GLE",
   :name=>"Gainesville Municipal Airport",
   :icao=>"KGLE",
   :city=>"Gainesville",
   :country=>'United States', :country_code=>'US',

   :location=>"Gainesville, Texas, United States"},
 "GLH"=>
  {:iata=>"GLH",
   :name=>"Mid-Delta Regional Airport",
   :icao=>"KGLH",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, Mississippi, United States"},
 "GLR"=>
  {:iata=>"GLR",
   :name=>"Gaylord Regional Airport",
   :icao=>"KGLR",
   :city=>"Gaylord",
   :country=>'United States', :country_code=>'US',

   :location=>"Gaylord, Michigan, United States"},
 "GLS"=>
  {:iata=>"GLS",
   :name=>"Scholes International Airport at Galveston",
   :icao=>"KGLS",
   :city=>"Galveston",
   :country=>'United States', :country_code=>'US',

   :location=>"Galveston, Texas, United States"},
 "GLV"=>
  {:iata=>"GLV",
   :name=>"Golovin Airport",
   :icao=>"PAGL",
   :city=>"Golovin",
   :country=>'United States', :country_code=>'US',

   :location=>"Golovin, Alaska, United States"},
 "GLW"=>
  {:iata=>"GLW",
   :name=>"Glasgow Municipal Airport",
   :icao=>"KGLW",
   :city=>"Glasgow",
   :country=>'United States', :country_code=>'US',

   :location=>"Glasgow, Kentucky, United States"},
 "GMT"=>
  {:iata=>"GMT",
   :name=>"Granite Mountain Air Station (FAA: GSZ)",
   :icao=>"PAGZ",
   :city=>"Granite Mountain",
   :country=>'United States', :country_code=>'US',

   :location=>"Granite Mountain, Alaska, United States"},
 "GMU"=>
  {:iata=>"GMU",
   :name=>"Greenville Downtown Airport",
   :icao=>"KGMU",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, South Carolina, United States"},
 "GMV"=>
  {:iata=>"GMV",
   :name=>"Monument Valley Airport (FAA: UT25)",
   :icao=>"",
   :city=>"Monument Valley",
   :country=>'United States', :country_code=>'US',

   :location=>"Monument Valley, Utah, United States"},
 "GNG"=>
  {:iata=>"GNG",
   :name=>"Gooding Municipal Airport",
   :icao=>"KGNG",
   :city=>"Gooding",
   :country=>'United States', :country_code=>'US',

   :location=>"Gooding, Idaho, United States"},
 "GNT"=>
  {:iata=>"GNT",
   :name=>"Grants-Milan Municipal Airport",
   :icao=>"KGNT",
   :city=>"Grants",
   :country=>'United States', :country_code=>'US',

   :location=>"Grants, New Mexico, United States"},
 "GNU"=>
  {:iata=>"GNU",
   :name=>"Goodnews Airport",
   :icao=>"",
   :city=>"Goodnews",
   :country=>'United States', :country_code=>'US',

   :location=>"Goodnews, Alaska, United States"},
 "GNV"=>
  {:iata=>"GNV",
   :name=>"Gainesville Regional Airport",
   :icao=>"KGNV",
   :city=>"Gainesville",
   :country=>'United States', :country_code=>'US',

   :location=>"Gainesville, Florida, United States"},
 "GOF"=>
  {:iata=>"GOF",
   :name=>"Goodfellow Air Force Base",
   :icao=>"",
   :city=>"San Angelo",
   :country=>'United States', :country_code=>'US',

   :location=>"San Angelo, Texas, United States"},
 "GOK"=>
  {:iata=>"GOK",
   :name=>"Guthrie-Edmond Regional Airport (was Guthrie Municipal)",
   :icao=>"KGOK",
   :city=>"Guthrie",
   :country=>'United States', :country_code=>'US',

   :location=>"Guthrie, Oklahoma, United States"},
 "GOL"=>
  {:iata=>"GOL",
   :name=>"Gold Beach Municipal Airport (FAA: 4S1)",
   :icao=>"",
   :city=>"Gold Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Gold Beach, Oregon, United States"},
 "GON"=>
  {:iata=>"GON",
   :name=>"Groton-New London Airport",
   :icao=>"KGON",
   :city=>"Groton",
   :country=>'United States', :country_code=>'US',

   :location=>"Groton, Connecticut, United States"},
 "GPT"=>
  {:iata=>"GPT",
   :name=>"Gulfport-Biloxi International Airport",
   :icao=>"KGPT",
   :city=>"Gulfport",
   :country=>'United States', :country_code=>'US',

   :location=>"Gulfport, Mississippi, United States"},
 "GPZ"=>
  {:iata=>"GPZ",
   :name=>"Grand Rapids/Itasca County Airport (Gordon Newstrom Field)",
   :icao=>"KGPZ",
   :city=>"Grand Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Rapids, Minnesota, United States"},
 "GQQ"=>
  {:iata=>"GQQ",
   :name=>"Galion Municipal Airport",
   :icao=>"KGQQ",
   :city=>"Galion",
   :country=>'United States', :country_code=>'US',

   :location=>"Galion, Ohio, United States"},
 "GRB"=>
  {:iata=>"GRB",
   :name=>"Austin Straubel International Airport",
   :icao=>"KGRB",
   :city=>"Green Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Green Bay, Wisconsin, United States"},
 "GRD"=>
  {:iata=>"GRD",
   :name=>"Greenwood County Airport",
   :icao=>"KGRD",
   :city=>"Greenwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenwood, South Carolina, United States"},
 "GRE"=>
  {:iata=>"GRE",
   :name=>"Greenville Airport",
   :icao=>"KGRE",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, Illinois, United States"},
 "GRF"=>
  {:iata=>"GRF",
   :name=>"Gray Army Airfield (Fort Lewis)",
   :icao=>"KGRF",
   :city=>"Tacoma",
   :country=>'United States', :country_code=>'US',

   :location=>"Tacoma, Washington, United States"},
 "GRI"=>
  {:iata=>"GRI",
   :name=>"Central Nebraska Regional Airport",
   :icao=>"KGRI",
   :city=>"Grand Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Island, Nebraska, United States"},
 "GRK"=>
  {:iata=>"GRK",
   :name=>"Killeen-Fort Hood Regional Airport (Robert Gray Army Airfield)",
   :icao=>"KGRK",
   :city=>"Fort Hood / Killeen",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Hood / Killeen, Texas, United States"},
 "GRM"=>
  {:iata=>"GRM",
   :name=>"Grand Marais/Cook County Airport (FAA: CKC)",
   :icao=>"KCKC",
   :city=>"Grand Marais",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Marais, Minnesota, United States"},
 "GRN"=>
  {:iata=>"GRN",
   :name=>"Gordon Municipal Airport",
   :icao=>"KGRN",
   :city=>"Gordon",
   :country=>'United States', :country_code=>'US',

   :location=>"Gordon, Nebraska, United States"},
 "GRR"=>
  {:iata=>"GRR",
   :name=>"Gerald R. Ford International Airport",
   :icao=>"KGRR",
   :city=>"Grand Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Rapids, Michigan, United States"},
 "GSB"=>
  {:iata=>"GSB",
   :name=>"Seymour Johnson Air Force Base",
   :icao=>"KGSB",
   :city=>"Goldsboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Goldsboro, North Carolina, United States"},
 "GSH"=>
  {:iata=>"GSH",
   :name=>"Goshen Municipal Airport",
   :icao=>"KGSH",
   :city=>"Goshen",
   :country=>'United States', :country_code=>'US',

   :location=>"Goshen, Indiana, United States"},
 "GSO"=>
  {:iata=>"GSO",
   :name=>"Piedmont Triad International Airport",
   :icao=>"KGSO",
   :city=>"Greensboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Greensboro, North Carolina, United States"},
 "GSP"=>
  {:iata=>"GSP",
   :name=>"Greenville-Spartanburg International Airport",
   :icao=>"KGSP",
   :city=>"Greenville / Spartanburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville / Spartanburg, South Carolina, United States"},
 "GST"=>
  {:iata=>"GST",
   :name=>"Gustavus Airport",
   :icao=>"PAGS",
   :city=>"Gustavus",
   :country=>'United States', :country_code=>'US',

   :location=>"Gustavus, Alaska, United States"},
 "GTF"=>
  {:iata=>"GTF",
   :name=>"Great Falls International Airport",
   :icao=>"KGTF",
   :city=>"Great Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Great Falls, Montana, United States"},
 "GTG"=>
  {:iata=>"GTG",
   :name=>"Grantsburg Municipal Airport",
   :icao=>"KGTG",
   :city=>"Grantsburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Grantsburg, Wisconsin, United States"},
 "GTR"=>
  {:iata=>"GTR",
   :name=>"Golden Triangle Regional Airport",
   :icao=>"KGTR",
   :city=>"Columbus/West Point/Starkville",
   :country=>'United States', :country_code=>'US',

   :location=>"Columbus/West Point/Starkville, Mississippi, United States"},
 "GTY"=>
  {:iata=>"GTY",
   :name=>"Gettysburg Regional Airport (FAA: W05)",
   :icao=>"",
   :city=>"Gettysburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Gettysburg, Pennsylvania, United States"},
 "GUC"=>
  {:iata=>"GUC",
   :name=>"Gunnison-Crested Butte Regional Airport",
   :icao=>"KGUC",
   :city=>"Gunnison",
   :country=>'United States', :country_code=>'US',

   :location=>"Gunnison, Colorado, United States"},
 "GUF"=>
  {:iata=>"GUF",
   :name=>"Jack Edwards Airport (FAA: JKA)",
   :icao=>"KJKA",
   :city=>"Gulf Shores",
   :country=>'United States', :country_code=>'US',

   :location=>"Gulf Shores, Alabama, United States"},
 "GUP"=>
  {:iata=>"GUP",
   :name=>"Gallup Municipal Airport",
   :icao=>"KGUP",
   :city=>"Gallup",
   :country=>'United States', :country_code=>'US',

   :location=>"Gallup, New Mexico, United States"},
 "GUS"=>
  {:iata=>"GUS",
   :name=>"Grissom Air Reserve Base",
   :icao=>"KGUS",
   :city=>"Peru",
   :country=>'United States', :country_code=>'US',

   :location=>"Peru, Indiana, United States"},
 "GUY"=>
  {:iata=>"GUY",
   :name=>"Guymon Municipal Airport",
   :icao=>"KGUY",
   :city=>"Guymon",
   :country=>'United States', :country_code=>'US',

   :location=>"Guymon, Oklahoma, United States"},
 "GVE"=>
  {:iata=>"GVE",
   :name=>"Gordonsville Municipal Airport",
   :icao=>"KGVE",
   :city=>"Gordonsville",
   :country=>'United States', :country_code=>'US',

   :location=>"Gordonsville, Virginia, United States"},
 "GVL"=>
  {:iata=>"GVL",
   :name=>"Lee Gilmer Memorial Airport",
   :icao=>"KGVL",
   :city=>"Gainesville",
   :country=>'United States', :country_code=>'US',

   :location=>"Gainesville, Georgia, United States"},
 "GVT"=>
  {:iata=>"GVT",
   :name=>"Majors Airport",
   :icao=>"KGVT",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, Texas, United States"},
 "GWO"=>
  {:iata=>"GWO",
   :name=>"Greenwood-Leflore Airport",
   :icao=>"KGWO",
   :city=>"Greenwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenwood, Mississippi, United States"},
 "GWS"=>
  {:iata=>"GWS",
   :name=>"Glenwood Springs Municipal Airport",
   :icao=>"KGWS",
   :city=>"Glenwood Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Glenwood Springs, Colorado, United States"},
 "GWV"=>
  {:iata=>"GWV",
   :name=>"Glendale Fokker Field (FAA: WV66)",
   :icao=>"",
   :city=>"Glendale",
   :country=>'United States', :country_code=>'US',

   :location=>"Glendale, West Virginia, United States"},
 "GXY"=>
  {:iata=>"GXY",
   :name=>"Greeley-Weld County Airport",
   :icao=>"KGXY",
   :city=>"Greeley",
   :country=>'United States', :country_code=>'US',

   :location=>"Greeley, Colorado, United States"},
 "GYR"=>
  {:iata=>"GYR",
   :name=>"Phoenix Goodyear Airport",
   :icao=>"KGYR",
   :city=>"Goodyear",
   :country=>'United States', :country_code=>'US',

   :location=>"Goodyear, Arizona, United States"},
 "GYY"=>
  {:iata=>"GYY",
   :name=>"Gary/Chicago International Airport",
   :icao=>"KGYY",
   :city=>"Gary",
   :country=>'United States', :country_code=>'US',

   :location=>"Gary, Indiana (near Chicago), United States"}}

end
