# encoding: UTF-8
def airp_11
  {"JHL"=>
  {:iata=>"JHL",
   :name=>"Albian Aerodrome",
   :city=>"Fort MacKay",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Fort MacKay, Canada"},
 "JEG"=>
  {:iata=>"JEG",
   :name=>"Aasiaat Airport",
   :icao=>"BGAA",
   :city=>"Aasiaat",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Aasiaat, Greenland"},
 "JAV"=>
  {:iata=>"JAV",
   :name=>"Ilulissat Airport",
   :icao=>"BGJN",
   :city=>"Ilulissat",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Ilulissat, Greenland"},
 "JSU"=>
  {:iata=>"JSU",
   :name=>"Maniitsoq Airport",
   :icao=>"BGMQ",
   :city=>"Maniitsoq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Maniitsoq, Greenland"},
 "JNN"=>
  {:iata=>"JNN",
   :name=>"Nanortalik Heliport",
   :icao=>"BGNN",
   :city=>"Nanortalik",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Nanortalik, Greenland"},
 "JNS"=>
  {:iata=>"JNS",
   :name=>"Narsaq Heliport",
   :icao=>"BGNS",
   :city=>"Narsaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Narsaq, Greenland"},
 "JUU"=>
  {:iata=>"JUU",
   :name=>"Nuugaatsiaq Heliport",
   :icao=>"BGNQ",
   :city=>"Nuugaatsiaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Nuugaatsiaq, Greenland"},
 "JFR"=>
  {:iata=>"JFR",
   :name=>"Paamiut Airport",
   :icao=>"BGPT",
   :city=>"Paamiut",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Paamiut, Greenland"},
 "JQA"=>
  {:iata=>"JQA",
   :name=>"Qaarsut Airport (Uummannaq Airport)",
   :icao=>"BGUQ",
   :city=>"Qaarsut / Uummannaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qaarsut / Uummannaq, Greenland"},
 "JJU"=>
  {:iata=>"JJU",
   :name=>"Qaqortoq Heliport",
   :icao=>"BGJH",
   :city=>"Qaqortoq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qaqortoq, Greenland"},
 "JCH"=>
  {:iata=>"JCH",
   :name=>"Qasigiannguit Heliport",
   :icao=>"BGCH",
   :city=>"Qasigiannguit",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qasigiannguit, Greenland"},
 "JGO"=>
  {:iata=>"JGO",
   :name=>"Qeqertarsuaq Heliport",
   :icao=>"BGGN",
   :city=>"Qeqertarsuaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qeqertarsuaq, Greenland"},
 "JHS"=>
  {:iata=>"JHS",
   :name=>"Sisimiut Airport",
   :icao=>"BGSS",
   :city=>"Sisimiut",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Sisimiut, Greenland"},
 "JUK"=>
  {:iata=>"JUK",
   :name=>"Ukkusissat Heliport",
   :icao=>"BGUT",
   :city=>"Ukkusissat",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Ukkusissat, Greenland"},
 "JUV"=>
  {:iata=>"JUV",
   :name=>"Upernavik Airport",
   :icao=>"BGUK",
   :city=>"Upernavik",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Upernavik, Greenland"},
 "JRK"=>
  {:iata=>"JRK",
   :name=>"Arsuk Airport",
   :icao=>"BGAR",
   :city=>"Arsuk",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Arsuk, Greenland"},
 "JGR"=>
  {:iata=>"JGR",
   :name=>"Kangilinnguit Heliport (Grønnedal Heliport)",
   :icao=>"BGGD",
   :city=>"Kangilinnguit (Grønnedal)",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Kangilinnguit (Grønnedal), Greenland"},
 "JAL"=>
  {:iata=>"JAL",
   :name=>"El Lencero Airport",
   :icao=>"MMJA",
   :city=>"Jalapa",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Jalapa, Veracruz, Mexico"},
 "JON"=>
  {:iata=>"JON",
   :name=>"Johnston Atoll Airport",
   :icao=>"PJON",
   :city=>"Johnston Atoll",
   :country=>'U.S. Minor Outlying Islands', :country_code=>'UM',
   :location=>"Johnston Atoll, U.S. Minor Outlying Islands"},
 "JAC"=>
  {:iata=>"JAC",
   :name=>"Jackson Hole Airport",
   :icao=>"KJAC",
   :city=>"Jackson",
   :country=>'United States', :country_code=>'US',

   :location=>"Jackson, Wyoming, United States"},
 "JUJ"=>
  {:iata=>"JUJ",
   :name=>"Gobernador Horacio Guzmán International Airport",
   :icao=>"SASJ",
   :city=>"San Salvador de Jujuy",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Salvador de Jujuy, Jujuy, Argentina"},
 "JSM"=>
  {:iata=>"JSM",
   :name=>"José de San Martín Airport",
   :icao=>"SAWS",
   :city=>"José de San Martín",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"José de San Martín, Chubut, Argentina"},
 "JNI"=>
  {:iata=>"JNI",
   :name=>"Junín Airport",
   :icao=>"SAAJ",
   :city=>"Junín",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Junín, Buenos Aires, Argentina"},
 "JTC"=>
  {:iata=>"JTC",
   :name=>"Bauru-Arealva Airport",
   :city=>"Baura-Arealva",
   :icao=>"SJTC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Baura-Arealva, Brazil"},
 "JPR"=>
  {:iata=>"JPR",
   :name=>"Ji-Paraná Airport",
   :icao=>"SWJI",
   :city=>"Ji-Paraná",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ji-Paraná, Rondônia, Brazil"},
 "JCB"=>
  {:iata=>"JCB",
   :name=>"Joaçaba Airport",
   :icao=>"SSJA",
   :city=>"Joaçaba",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Joaçaba, Santa Catarina, Brazil"},
 "JPA"=>
  {:iata=>"JPA",
   :name=>"Presidente Castro Pinto International Airport",
   :icao=>"SBJP",
   :city=>"João Pessoa",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"João Pessoa, Paraíba, Brazil"},
 "JOI"=>
  {:iata=>"JOI",
   :name=>"Joinville Airport (Cubatao Airport)",
   :icao=>"SBJV",
   :city=>"Joinville",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Joinville, Santa Catarina, Brazil"},
 "JDO"=>
  {:iata=>"JDO",
   :name=>"Cariri Regional Airport",
   :icao=>"SBJU",
   :city=>"Juazeiro do Norte",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juazeiro do Norte, Ceará, Brazil"},
 "JDF"=>
  {:iata=>"JDF",
   :name=>"Francisco Alvares de Assis Airport",
   :icao=>"SBJF",
   :city=>"Juiz de Fora",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juiz de Fora, Minas Gerais, Brazil"},
 "JDR"=>
  {:iata=>"JDR",
   :name=>"Sao Joao Del Rei Airport",
   :city=>"Sao Joao Del Rei",
   :icao=>"SNJR",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Sao Joao Del Rei, Brazil"},
 "JCR"=>
  {:iata=>"JCR",
   :name=>"Jacareacanga Airport",
   :icao=>"SBEK",
   :city=>"Jacareacanga",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Jacareacanga, Pará, Brazil"},
 "JCM"=>
  {:iata=>"JCM",
   :name=>"Jacobina Airport",
   :icao=>"SNJB",
   :city=>"Jacobina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Jacobina, Bahia, Brazil"},
 "JLS"=>
  {:iata=>"JLS",
   :name=>"Jales Airport",
   :icao=>"",
   :city=>"Jales",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Jales, São Paulo, Brazil"},
 "JNA"=>
  {:iata=>"JNA",
   :name=>"Januária Airport",
   :icao=>"SNJN",
   :city=>"Januária",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Januária, Minas Gerais, Brazil"},
 "JTI"=>
  {:iata=>"JTI",
   :name=>"Jatai Airport",
   :icao=>"",
   :city=>"Jatai",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Jatai, Goiás, Brazil"},
 "JEQ"=>
  {:iata=>"JEQ",
   :name=>"Jequié Airport",
   :icao=>"SNJK",
   :city=>"Jequié",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Jequié, Bahia, Brazil"},
 "JUA"=>
  {:iata=>"JUA",
   :name=>"Juara Airport",
   :icao=>"SIZX",
   :city=>"Juara",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juara, Mato Grosso, Brazil"},
 "JIA"=>
  {:iata=>"JIA",
   :name=>"Juina Airport",
   :icao=>"SWJN",
   :city=>"Juina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juina, Mato Grosso, Brazil"},
 "JRN"=>
  {:iata=>"JRN",
   :name=>"Juruena Airport",
   :icao=>"SWJU",
   :city=>"Juruena",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juruena, Mato Grosso, Brazil"},
 "JUO"=>
  {:iata=>"JUO",
   :name=>"Juradó Airport",
   :icao=>"",
   :city=>"Juradó",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Juradó, Colombia"},
 "JIP"=>
  {:iata=>"JIP",
   :name=>"Jipijapa Airport",
   :icao=>"SEJI",
   :city=>"Jipijapa",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Jipijapa, Ecuador"},
 "JAU"=>
  {:iata=>"JAU",
   :name=>"Francisco Carle Airport",
   :icao=>"SPJJ",
   :city=>"Jauja",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Jauja, Peru"},
 "JUL"=>
  {:iata=>"JUL",
   :name=>"Inca Manco Capac Airport",
   :icao=>"SPJL",
   :city=>"Juliaca",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Juliaca, Peru"},
 "JJI"=>
  {:iata=>"JJI",
   :name=>"Juanjuí Airport",
   :icao=>"SPJI",
   :city=>"Juanjuí",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Juanjuí, Peru"},
 "JCK"=>
  {:iata=>"JCK",
   :name=>"Julia Creek Airport",
   :icao=>"YJLC",
   :city=>"Julia Creek",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Julia Creek, Queensland, Australia"},
 "JFM"=>
  {:iata=>"JFM",
   :name=>"Fremantle Heliport",
   :icao=>"",
   :city=>"Fremantle",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Fremantle, Western Australia, Australia"},
 "JAB"=>
  {:iata=>"JAB",
   :name=>"Jabiru Airport",
   :icao=>"YJAB",
   :city=>"Jabiru",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Jabiru, Northern Territory, Australia"},
 "JAD"=>
  {:iata=>"JAD",
   :name=>"Jandakot Airport",
   :icao=>"YPJT",
   :city=>"Jandakot",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Jandakot, Western Australia, Australia"},
 "JUN"=>
  {:iata=>"JUN",
   :name=>"Jundah Airport",
   :icao=>"YJDA",
   :city=>"Jundah",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Jundah, Queensland, Australia"},
 "JUR"=>
  {:iata=>"JUR",
   :name=>"Jurien Bay Airport",
   :icao=>"YJNB",
   :city=>"Jurien Bay",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Jurien Bay, Western Australia, Australia"},
 "JHQ"=>
  {:iata=>"JHQ",
   :name=>"Shute Harbour Heliport",
   :city=>"Shute Harbour",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Shute Harbour, Australia"},
 "JEJ"=>
  {:iata=>"JEJ",
   :name=>"Jeh Airport",
   :icao=>"",
   :city=>"Ailinglaplap Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Ailinglaplap Atoll, Marshall Islands"},
 "JAT"=>
  {:iata=>"JAT",
   :name=>"Jabot Airport",
   :icao=>"",
   :city=>"Jabat Island",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Jabat Island, Marshall Islands"},
 "JJA"=>
  {:iata=>"JJA",
   :name=>"Jajao Airport",
   :city=>"Santa Isabel Island",
   :icao=>"AGJO",
   :country=>'Islands', :country_code=>'',
   :location=>"Santa Isabel Island, Islands"},
 "JBQ"=>
  {:iata=>"JBQ",
   :name=>"La Isabela International Airport",
   :icao=>"MDJB",
   :city=>"La Isabela",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"La Isabela, Dominican Republic"},
 "JAK"=>
  {:iata=>"JAK",
   :name=>"Jacmel Airport",
   :icao=>"MTJA",
   :city=>"Jacmel",
   :country=>'Haiti', :country_code=>'HT',
   :location=>"Jacmel, Haiti"},
 "JEE"=>
  {:iata=>"JEE",
   :name=>"Jérémie Airport",
   :icao=>"MTJE",
   :city=>"Jérémie",
   :country=>'Haiti', :country_code=>'HT',
   :location=>"Jérémie, Haiti"},
 "JCD"=>
  {:iata=>"JCD",
   :name=>"St. Croix Downtown Heliport",
   :city=>"Saint Croix",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Saint Croix, Islands"},
 "JMB"=>
  {:iata=>"JMB",
   :name=>"Jamba Airport",
   :icao=>"",
   :city=>"Jamba",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Jamba, Huíla, Angola"},
 "JWA"=>
  {:iata=>"JWA",
   :name=>"Jwaneng Airport",
   :icao=>"FBJW",
   :city=>"Jwaneng",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Jwaneng, Botswana"},
 "JIB"=>
  {:iata=>"JIB",
   :name=>"Ambouli Airport",
   :icao=>"HDAM",
   :city=>"Djibouti",
   :country=>'Djibouti', :country_code=>'DJ',
   :location=>"Djibouti, Djibouti"},
 "JIJ"=>
  {:iata=>"JIJ",
   :name=>"Jijiga Airport",
   :icao=>"HAJJ",
   :city=>"Jijiga",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Jijiga, Ethiopia"},
 "JIM"=>
  {:iata=>"JIM",
   :name=>"Aba Segud Airport",
   :icao=>"HAJM",
   :city=>"Jimma",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Jimma, Ethiopia"},
 "JJM"=>
  {:iata=>"JJM",
   :name=>"Mulika Lodge",
   :city=>"Meru",
   :icao=>"HKMK",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Meru, Kenya"},
 "JVA"=>
  {:iata=>"JVA",
   :name=>"Ankavandra Airport",
   :icao=>"FMMK",
   :city=>"Ankavandra",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ankavandra, Madagascar"},
 "JOS"=>
  {:iata=>"JOS",
   :name=>"Jos Airport (Yakubu Gowon Airport)",
   :icao=>"DNJO",
   :city=>"Jos",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Jos, Nigeria"},
 "JMY"=>
  {:iata=>"JMY",
   :name=>"Mammy Yoko Heliport",
   :icao=>"",
   :city=>"Freetown",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Freetown, Sierra Leone"},
 "JNB"=>
  {:iata=>"JNB",
   :name=>"OR Tambo International Airport",
   :icao=>"FAOR",
   :city=>"Johannesburg",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Johannesburg, Gauteng, South Africa"},
 "JOH"=>
  {:iata=>"JOH",
   :name=>"Port Saint Johns Airport",
   :icao=>"FAPJ",
   :city=>"Port Saint Johns",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Port Saint Johns, South Africa"},
 "JUB"=>
  {:iata=>"JUB",
   :name=>"Juba Airport",
   :icao=>"HSSJ",
   :city=>"Juba",
   :country=>'South Sudan', :country_code=>'SS',
   :location=>"Juba, South Sudan"},
 "JIN"=>
  {:iata=>"JIN",
   :name=>"Jinja Airport",
   :icao=>"HUJI",
   :city=>"Jinja",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Jinja, Uganda"},
 "JRO"=>
  {:iata=>"JRO",
   :name=>"Kilimanjaro International Airport",
   :icao=>"HTKJ",
   :city=>"Kilimanjaro",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Kilimanjaro, Tanzania"},
 "JOM"=>
  {:iata=>"JOM",
   :name=>"Njombe Airport",
   :icao=>"HTNJ",
   :city=>"Njombe",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Njombe, Tanzania"},
 "JAM"=>
  {:iata=>"JAM",
   :name=>"Bezmer Air Base",
   :icao=>"",
   :city=>"Yambol (Jambol)",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Yambol (Jambol), Bulgaria"},
 "JOE"=>
  {:iata=>"JOE",
   :name=>"Joensuu Airport",
   :icao=>"EFJO",
   :city=>"Joensuu",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Joensuu, Finland"},
 "JYV"=>
  {:iata=>"JYV",
   :name=>"Jyväskylä Airport",
   :icao=>"EFJY",
   :city=>"Jyväskylä",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Jyväskylä, Finland"},
 "JCA"=>
  {:iata=>"JCA",
   :name=>"Croisette Heliport",
   :icao=>"",
   :city=>"Cannes",
   :country=>'France', :country_code=>'FR',
   :location=>"Cannes, Côte d'Azur, France"},
 "JAH"=>
  {:iata=>"JAH",
   :name=>"Agora Helipad",
   :icao=>"",
   :city=>"Aubagne",
   :country=>'France', :country_code=>'FR',
   :location=>"Aubagne, France"},
 "JEV"=>
  {:iata=>"JEV",
   :name=>"Évry Heliport",
   :icao=>"",
   :city=>"Évry",
   :country=>'France', :country_code=>'FR',
   :location=>"Évry, Essonne, France"},
 "JLP"=>
  {:iata=>"JLP",
   :name=>"Juan-les-Pins Airport",
   :icao=>"",
   :city=>"Juan-les-Pins",
   :country=>'France', :country_code=>'FR',
   :location=>"Juan-les-Pins, France"},
 "JDP"=>
  {:iata=>"JDP",
   :name=>"Paris - Issy-les-Moulineaux Heliport",
   :icao=>"LFPI",
   :city=>"Issy-les-Moulineaux / Paris",
   :country=>'France', :country_code=>'FR',
   :location=>"Issy-les-Moulineaux / Paris, France"},
 "JPU"=>
  {:iata=>"JPU",
   :name=>"La Défense Heliport",
   :icao=>"",
   :city=>"Paris",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris, France"},
 "JUI"=>
  {:iata=>"JUI",
   :name=>"Juist Airport",
   :icao=>"EDWJ",
   :city=>"Juist",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Juist, Lower Saxony, Germany"},
 "JTY"=>
  {:iata=>"JTY",
   :name=>"Astypalaia Airport",
   :icao=>"LGPL",
   :city=>"Astypalaia Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Astypalaia Island, Greece"},
 "JKH"=>
  {:iata=>"JKH",
   :name=>"Chios Island National Airport",
   :icao=>"LGHI",
   :city=>"Chios Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Chios Island, Greece"},
 "JIK"=>
  {:iata=>"JIK",
   :name=>"Ikaria Airport",
   :icao=>"LGIK",
   :city=>"Ikaria",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Ikaria, Greece"},
 "JKL"=>
  {:iata=>"JKL",
   :name=>"Kalymnos Island National Airport",
   :city=>"Kalymnos",
   :icao=>"LGKY",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Kalymnos, Greece"},
 "JMK"=>
  {:iata=>"JMK",
   :name=>"Mykonos Island National Airport",
   :icao=>"LGMK",
   :city=>"Mykonos Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Mykonos Island, Greece"},
 "JNX"=>
  {:iata=>"JNX",
   :name=>"Naxos Island National Airport",
   :icao=>"LGNX",
   :city=>"Naxos Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Naxos Island, Greece"},
 "JSH"=>
  {:iata=>"JSH",
   :name=>"Sitia Public Airport",
   :icao=>"LGST",
   :city=>"Sitia",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Sitia, Crete, Greece"},
 "JSI"=>
  {:iata=>"JSI",
   :name=>"Skiathos Island National Airport",
   :icao=>"LGSK",
   :city=>"Skiathos Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Skiathos Island, Greece"},
 "JSY"=>
  {:iata=>"JSY",
   :name=>"Syros Island Airport",
   :icao=>"LGSO",
   :city=>"Syros Island",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Syros Island, Greece"},
 "JTR"=>
  {:iata=>"JTR",
   :name=>"Santorini Airport",
   :icao=>"LGSR",
   :city=>"Santorini",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Santorini, Thira, Greece"},
 "JSS"=>
  {:iata=>"JSS",
   :name=>"Spetses Heliport",
   :icao=>"",
   :city=>"Spetses",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Spetses, Greece"},
 "JLO"=>
  {:iata=>"JLO",
   :name=>"Jesolo Airport",
   :icao=>"",
   :city=>"Jesolo",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Jesolo, Italy"},
 "JCO"=>
  {:iata=>"JCO",
   :name=>"Comino Heliport",
   :icao=>"",
   :city=>"Comino",
   :country=>'Malta', :country_code=>'MT',
   :location=>"Comino, Malta"},
 "JOK"=>
  {:iata=>"JOK",
   :name=>"Yoshkar-Ola Airport",
   :icao=>"UWKJ",
   :city=>"Yoshkar-Ola",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Yoshkar-Ola, Russia"},
 "JCU"=>
  {:iata=>"JCU",
   :name=>"Ceuta Heliport",
   :icao=>"GECE",
   :city=>"Ceuta",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Ceuta, Spain"},
 "JKG"=>
  {:iata=>"JKG",
   :name=>"Jönköping Airport",
   :icao=>"ESGJ",
   :city=>"Jönköping",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Jönköping, Sweden"},
 "JHE"=>
  {:iata=>"JHE",
   :name=>"Hamnen Heliport",
   :icao=>"ESHH",
   :city=>"Helsingborg",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Helsingborg, Sweden"},
 "JLD"=>
  {:iata=>"JLD",
   :name=>"Landskrona Heliport",
   :icao=>"ESML",
   :city=>"Landskrona",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Landskrona, Sweden"},
 "JMM"=>
  {:iata=>"JMM",
   :name=>"Malmö Harbour Heliport",
   :icao=>"ESHM",
   :city=>"Malmö",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Malmö, Sweden"},
 "JSO"=>
  {:iata=>"JSO",
   :name=>"Södertälje Heliport",
   :icao=>"",
   :city=>"Södertälje",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Södertälje, Sweden"},
 "JER"=>
  {:iata=>"JER",
   :name=>"Jersey Airport",
   :icao=>"EGJJ",
   :city=>"Jersey",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Jersey, Channel Islands, United Kingdom"},
 "JAA"=>
  {:iata=>"JAA",
   :name=>"Jalalabad Airport",
   :icao=>"OAJL",
   :city=>"Jalalabad",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Jalalabad, Afghanistan"},
 "JSR"=>
  {:iata=>"JSR",
   :name=>"Jessore Airport",
   :icao=>"VGJR",
   :city=>"Jessore",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Jessore, Bangladesh"},
 "JUH"=>
  {:iata=>"JUH",
   :name=>"Chizhou Jiuhuashan Airport",
   :icao=>"",
   :city=>"Chizhou and Tongling",
   :country=>'China', :country_code=>'CN',
   :location=>"Chizhou and Tongling, Anhui, China"},
 "JGS"=>
  {:iata=>"JGS",
   :name=>"Jinggangshan Airport",
   :icao=>"ZSJA",
   :city=>"Ji'an",
   :country=>'China', :country_code=>'CN',
   :location=>"Ji'an, Jiangxi, China"},
 "JGD"=>
  {:iata=>"JGD",
   :name=>"Jiagedaqi Airport",
   :city=>"Jiagedaqi District",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Jiagedaqi District, China"},
 "JMU"=>
  {:iata=>"JMU",
   :name=>"Jiamusi Dongjiao Airport",
   :icao=>"ZYJM",
   :city=>"Jiamusi",
   :country=>'China', :country_code=>'CN',
   :location=>"Jiamusi, Heilongjiang, China"},
 "JGN"=>
  {:iata=>"JGN",
   :name=>"Jiayuguan Airport",
   :icao=>"ZLJQ",
   :city=>"Jiayuguan",
   :country=>'China', :country_code=>'CN',
   :location=>"Jiayuguan, Gansu, China"},
 "JIC"=>
  {:iata=>"JIC",
   :name=>"Jinchang Jinchuan Airport",
   :icao=>"ZLJC",
   :city=>"Jinchang",
   :country=>'China', :country_code=>'CN',
   :location=>"Jinchang, Gansu, China"},
 "JDZ"=>
  {:iata=>"JDZ",
   :name=>"Jingdezhen Airport",
   :icao=>"ZSJD",
   :city=>"Jingdezhen",
   :country=>'China', :country_code=>'CN',
   :location=>"Jingdezhen, Jiangxi, China"},
 "JHG"=>
  {:iata=>"JHG",
   :name=>"Xishuangbanna Gasa Airport",
   :icao=>"ZPJH",
   :city=>"Jinghong",
   :country=>'China', :country_code=>'CN',
   :location=>"Jinghong, Xishuangbanna, Yunnan, China"},
 "JNG"=>
  {:iata=>"JNG",
   :name=>"Jining Airport",
   :icao=>"ZLJN",
   :city=>"Jining",
   :country=>'China', :country_code=>'CN',
   :location=>"Jining, Shandong, China"},
 "JJN"=>
  {:iata=>"JJN",
   :name=>"Quanzhou Jinjiang Airport",
   :icao=>"ZSQZ",
   :city=>"Jinjiang City",
   :country=>'China', :country_code=>'CN',
   :location=>"Jinjiang City, Quanzhou, Fujian, China"},
 "JNZ"=>
  {:iata=>"JNZ",
   :name=>"Jinzhou Airport",
   :icao=>"ZYJZ",
   :city=>"Jinzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Jinzhou, Liaoning, China"},
 "JIU"=>
  {:iata=>"JIU",
   :name=>"Jiujiang Lushan Airport",
   :icao=>"ZSJJ",
   :city=>"Jiujiang",
   :country=>'China', :country_code=>'CN',
   :location=>"Jiujiang, Jiangxi, China"},
 "JXA"=>
  {:iata=>"JXA",
   :name=>"Jixi Xingkaihu Airport",
   :icao=>"ZYJX",
   :city=>"Jixi",
   :country=>'China', :country_code=>'CN',
   :location=>"Jixi, Heilongjiang, China"},
 "JIQ"=>
  {:iata=>"JIQ",
   :name=>"Qianjiang Zhoubai Airport",
   :icao=>"",
   :city=>"Qianjiang",
   :country=>'China', :country_code=>'CN',
   :location=>"Qianjiang, Chongqing, China"},
 "JUZ"=>
  {:iata=>"JUZ",
   :name=>"Quzhou Airport",
   :icao=>"ZSJU",
   :city=>"Quzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Quzhou, Zhejiang, China"},
 "JZH"=>
  {:iata=>"JZH",
   :name=>"Jiuzhaigou Huanglong Airport",
   :icao=>"ZUJZ",
   :city=>"Songpan County",
   :country=>'China', :country_code=>'CN',
   :location=>"Songpan County, Sichuan, China"},
 "JIL"=>
  {:iata=>"JIL",
   :name=>"Jilin Ertaizi Airport",
   :icao=>"ZYJL",
   :city=>"Jilin City",
   :country=>'China', :country_code=>'CN',
   :location=>"Jilin City, Jilin, China"},
 "JLR"=>
  {:iata=>"JLR",
   :name=>"Jabalpur Airport",
   :icao=>"VAJB",
   :city=>"Jabalpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jabalpur, Madhya Pradesh, India"},
 "JAI"=>
  {:iata=>"JAI",
   :name=>"Jaipur Airport (Sanganer Airport)",
   :icao=>"VIJP",
   :city=>"Jaipur / Sanganer",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jaipur / Sanganer, India"},
 "JSA"=>
  {:iata=>"JSA",
   :name=>"Jaisalmer Airport",
   :icao=>"VIJR",
   :city=>"Jaisalmer",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jaisalmer, India"},
 "JGA"=>
  {:iata=>"JGA",
   :name=>"Jamnagar Airport",
   :icao=>"VAJM",
   :city=>"Jamnagar",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jamnagar, Gujurat, India"},
 "JDH"=>
  {:iata=>"JDH",
   :name=>"Jodhpur Airport",
   :icao=>"VIJO",
   :city=>"Jodhpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jodhpur, Rajasthan, India"},
 "JRH"=>
  {:iata=>"JRH",
   :name=>"Jorhat Airport",
   :icao=>"VEJT",
   :city=>"Jorhat",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jorhat, India"},
 "JGB"=>
  {:iata=>"JGB",
   :name=>"Jagdalpur Airport",
   :icao=>"",
   :city=>"Jagdalpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jagdalpur, India"},
 "JBB"=>
  {:iata=>"JBB",
   :name=>"Jember Noto Hadinegoro Airport",
   :icao=>"",
   :city=>"Jember",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Jember, Jember Regency, Indonesia"},
 "JOG"=>
  {:iata=>"JOG",
   :name=>"Adisucipto International Airport",
   :icao=>"WIIJ",
   :city=>"Yogyakarta",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Yogyakarta, Indonesia"},
 "JAR"=>
  {:iata=>"JAR",
   :name=>"Jahrom Airport",
   :city=>"Jahrom",
   :icao=>"OISJ",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Jahrom, Iran"},
 "JWN"=>
  {:iata=>"JWN",
   :name=>"Zanjan Airport",
   :city=>"Zanjan",
   :icao=>"OITZ",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Zanjan, Iran"},
 "JYR"=>
  {:iata=>"JYR",
   :name=>"Jiroft Airport",
   :city=>"Jiroft",
   :icao=>"OIKJ",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Jiroft, Iran"},
 "JHB"=>
  {:iata=>"JHB",
   :name=>"Sultan Ismail International Airport",
   :icao=>"WMKJ",
   :city=>"Johor Bahru",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Johor Bahru, Malaysia"},
 "JKR"=>
  {:iata=>"JKR",
   :name=>"Janakpur Airport",
   :icao=>"VNJP",
   :city=>"Janakpur",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Janakpur, Nepal"},
 "JMO"=>
  {:iata=>"JMO",
   :name=>"Jomsom Airport",
   :icao=>"VNJS",
   :city=>"Jomsom",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Jomsom, Nepal"},
 "JUM"=>
  {:iata=>"JUM",
   :name=>"Jumla Airport",
   :icao=>"VNJL",
   :city=>"Jumla",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Jumla, Nepal"},
 "JIR"=>
  {:iata=>"JIR",
   :name=>"Jiri Airport",
   :icao=>"VNJI",
   :city=>"Jiri",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Jiri, Nepal"},
 "JAG"=>
  {:iata=>"JAG",
   :name=>"Jacobabad Air Base (Shahbaz Air Base)",
   :icao=>"OPJA",
   :city=>"Jacobabad",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Jacobabad, Pakistan"},
 "JIW"=>
  {:iata=>"JIW",
   :name=>"Jiwani Airport",
   :icao=>"OPJI",
   :city=>"Jiwani",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Jiwani, Pakistan"},
 "JAQ"=>
  {:iata=>"JAQ",
   :name=>"Jacquinot Bay Airport",
   :icao=>"",
   :city=>"Jacquinot Bay",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Jacquinot Bay, Papua New Guinea"},
 "JOP"=>
  {:iata=>"JOP",
   :name=>"Josephstaal Airport",
   :icao=>"",
   :city=>"Josephstaal",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Josephstaal, Papua New Guinea"},
 "JOL"=>
  {:iata=>"JOL",
   :name=>"Jolo Airport",
   :icao=>"RPMJ",
   :city=>"Jolo",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Jolo, Sulu, Philippines"},
 "JGE"=>
  {:iata=>"JGE",
   :name=>"Geoje Airport",
   :icao=>"",
   :city=>"Geoje",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Geoje, South Korea"},
 "JCN"=>
  {:iata=>"JCN",
   :name=>"Incheon Heliport",
   :city=>"Incheon",
   :icao=>"",
   :country=>'Korea', :country_code=>'',
   :location=>"Incheon, Korea"},
 "JCJ"=>
  {:iata=>"JCJ",
   :name=>"Chuja Heliport",
   :city=>"Jeju",
   :icao=>"",
   :country=>'Korea', :country_code=>'',
   :location=>"Jeju, Korea"},
 "JSP"=>
  {:iata=>"JSP",
   :name=>"Sogwipo Heliport",
   :icao=>"",
   :city=>"Sogwipo (Seogwipo)",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Sogwipo (Seogwipo), Cheju (Jeju), South Korea"},
 "JAF"=>
  {:iata=>"JAF",
   :name=>"Jaffna Airport",
   :icao=>"VCCJ",
   :city=>"Jaffna",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Jaffna, Sri Lanka"},
 "JAP"=>
  {:iata=>"JAP",
   :name=>"Punta Renes Airport",
   :city=>"Punta Renes",
   :icao=>"",
   :country=>'Rica', :country_code=>'',
   :location=>"Punta Renes, Rica"},
 "JUT"=>
  {:iata=>"JUT",
   :name=>"Juticalpa Airport",
   :icao=>"MHJU",
   :city=>"Juticalpa",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Juticalpa, Honduras"},
 "JQE"=>
  {:iata=>"JQE",
   :name=>"Jaqué Airport",
   :icao=>"MPJE",
   :city=>"Jaqué",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Jaqué, Panama"},
 "JRS"=>
  {:iata=>"JRS",
   :name=>"Atarot Airport (Jerusalem International Airport)",
   :icao=>"OJJR",
   :city=>"Jerusalem",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Jerusalem, Israel"},
 "JNJ"=>
  {:iata=>"JNJ",
   :name=>"Duqm Jaaluni Airport",
   :icao=>"",
   :city=>"Duqm",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Duqm, Oman"},
 "JED"=>
  {:iata=>"JED",
   :name=>"King Abdulaziz International Airport",
   :icao=>"OEJN",
   :city=>"Jeddah",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Jeddah, Saudi Arabia"},
 "JAN"=>
  {:iata=>"JAN",
   :name=>"Jackson-Evers International Airport",
   :icao=>"KJAN",
   :city=>"Jackson",
   :country=>'United States', :country_code=>'US',

   :location=>"Jackson, Mississippi, United States"},
 "JAS"=>
  {:iata=>"JAS",
   :name=>"Jasper County Airport (Bell Field)",
   :icao=>"KJAS",
   :city=>"Jasper",
   :country=>'United States', :country_code=>'US',

   :location=>"Jasper, Texas, United States"},
 "JAX"=>
  {:iata=>"JAX",
   :name=>"Jacksonville International Airport",
   :icao=>"KJAX",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Florida, United States"},
 "JBP"=>
  {:iata=>"JBP",
   :name=>"Commerce Business Park Heliport (FAA: 2CL0)",
   :icao=>"",
   :city=>"Commerce",
   :country=>'United States', :country_code=>'US',

   :location=>"Commerce, California, United States"},
 "JBR"=>
  {:iata=>"JBR",
   :name=>"Jonesboro Municipal Airport",
   :icao=>"KJBR",
   :city=>"Jonesboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Jonesboro, Arkansas, United States"},
 "JBT"=>
  {:iata=>"JBT",
   :name=>"Bethel Seaplane Base (FAA: Z59)",
   :icao=>"",
   :city=>"Bethel",
   :country=>'United States', :country_code=>'US',

   :location=>"Bethel, Alaska, United States"},
 "JCE"=>
  {:iata=>"JCE",
   :name=>"Oakland Convention Center Heliport (FAA: CL41)",
   :icao=>"",
   :city=>"Oakland",
   :country=>'United States', :country_code=>'US',

   :location=>"Oakland, California, United States"},
 "JCI"=>
  {:iata=>"JCI",
   :name=>"New Century AirCenter (FAA: IXD)",
   :icao=>"KIXD",
   :city=>"Olathe",
   :country=>'United States', :country_code=>'US',

   :location=>"Olathe, Kansas, United States"},
 "JCT"=>
  {:iata=>"JCT",
   :name=>"Kimble County Airport",
   :icao=>"KJCT",
   :city=>"Junction",
   :country=>'United States', :country_code=>'US',

   :location=>"Junction, Texas, United States"},
 "JCY"=>
  {:iata=>"JCY",
   :name=>"LBJ Ranch Airport (FAA: 0TE7)",
   :icao=>"",
   :city=>"Johnson City",
   :country=>'United States', :country_code=>'US',

   :location=>"Johnson City, Texas, United States"},
 "JDA"=>
  {:iata=>"JDA",
   :name=>"Grant County Regional Airport (Ogilvie Field) (FAA: GCD)",
   :icao=>"KGCD",
   :city=>"John Day",
   :country=>'United States', :country_code=>'US',

   :location=>"John Day, Oregon, United States"},
 "JDB"=>
  {:iata=>"JDB",
   :name=>"Dallas CBD Vertiport (Dallas Downtown Heliport) (FAA: 49T)",
   :icao=>"",
   :city=>"Dallas",
   :country=>'United States', :country_code=>'US',

   :location=>"Dallas, Texas, United States"},
 "JDG"=>
  {:iata=>"JDG",
   :name=>"Jungseok Airport",
   :icao=>"RKPD",
   :city=>"Jeju province",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Jeju province, South Korea"},
 "JDM"=>
  {:iata=>"JDM",
   :name=>"Miami Downtown Heliport (FAA: X48)",
   :icao=>"",
   :city=>"Miami",
   :country=>'United States', :country_code=>'US',

   :location=>"Miami, Florida, United States"},
 "JDN"=>
  {:iata=>"JDN",
   :name=>"Jordan Airport",
   :icao=>"KJDN",
   :city=>"Jordan",
   :country=>'United States', :country_code=>'US',

   :location=>"Jordan, Montana, United States"},
 "JDT"=>
  {:iata=>"JDT",
   :name=>"Minneapolis Downtown Heliport",
   :icao=>"",
   :city=>"Minneapolis",
   :country=>'United States', :country_code=>'US',

   :location=>"Minneapolis, Minnesota, United States"},
 "JDX"=>
  {:iata=>"JDX",
   :name=>"Houston Central Business District Heliport",
   :icao=>"",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "JDY"=>
  {:iata=>"JDY",
   :name=>"Downey Heliport",
   :icao=>"",
   :city=>"Downey",
   :country=>'United States', :country_code=>'US',

   :location=>"Downey, California, United States"},
 "JEF"=>
  {:iata=>"JEF",
   :name=>"Jefferson City Memorial Airport",
   :icao=>"KJEF",
   :city=>"Jefferson City",
   :country=>'United States', :country_code=>'US',

   :location=>"Jefferson City, Missouri, United States"},
 "JEM"=>
  {:iata=>"JEM",
   :name=>"Emeryville Heliport",
   :icao=>"",
   :city=>"Emeryville",
   :country=>'United States', :country_code=>'US',

   :location=>"Emeryville, California, United States"},
 "JFK"=>
  {:iata=>"JFK",
   :name=>"John F. Kennedy International Airport",
   :icao=>"KJFK",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "JFN"=>
  {:iata=>"JFN",
   :name=>"Ashtabula County Airport (FAA: HZY)",
   :icao=>"KHZY",
   :city=>"Ashtabula",
   :country=>'United States', :country_code=>'US',

   :location=>"Ashtabula, Ohio, United States"},
 "JGC"=>
  {:iata=>"JGC",
   :name=>"Grand Canyon Heliport",
   :icao=>"",
   :city=>"Grand Canyon",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Canyon, Arizona, United States"},
 "JGL"=>
  {:iata=>"JGL",
   :name=>"Galleria Heliport (FAA: 16GA)",
   :icao=>"",
   :city=>"Marietta",
   :country=>'United States', :country_code=>'US',

   :location=>"Marietta, Georgia, United States"},
 "JGP"=>
  {:iata=>"JGP",
   :name=>"Greenway Plaza Heliport",
   :icao=>"",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "JGQ"=>
  {:iata=>"JGQ",
   :name=>"Transco Tower Garage Heliport (FAA: TS31)",
   :icao=>"",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "JGX"=>
  {:iata=>"JGX",
   :name=>"Glendale Heliport",
   :icao=>"",
   :city=>"Glendale",
   :country=>'United States', :country_code=>'US',

   :location=>"Glendale, California, United States"},
 "JHC"=>
  {:iata=>"JHC",
   :name=>"Island Heliport",
   :icao=>"",
   :city=>"Garden City",
   :country=>'United States', :country_code=>'US',

   :location=>"Garden City, New York, United States"},
 "JHM"=>
  {:iata=>"JHM",
   :name=>"Kapalua Airport",
   :icao=>"PHJH",
   :city=>"Lahaina",
   :country=>'United States', :country_code=>'US',

   :location=>"Lahaina, Hawaii, United States"},
 "JHW"=>
  {:iata=>"JHW",
   :name=>"Chautauqua County-Jamestown Airport",
   :icao=>"KJHW",
   :city=>"Jamestown",
   :country=>'United States', :country_code=>'US',

   :location=>"Jamestown, New York, United States"},
 "JID"=>
  {:iata=>"JID",
   :name=>"Recreation and Conference Center Heliport (FAA: 9CA3)",
   :icao=>"",
   :city=>"City of Industry",
   :country=>'United States', :country_code=>'US',

   :location=>"City of Industry, California, United States"},
 "JIO"=>
  {:iata=>"JIO",
   :name=>"Ontario International Heliport",
   :icao=>"",
   :city=>"Ontario",
   :country=>'United States', :country_code=>'US',

   :location=>"Ontario, California, United States"},
 "JJC"=>
  {:iata=>"JJC",
   :name=>"Jorge Jiménez Cantú National Airport",
   :icao=>"MMJC",
   :city=>"Atizapán de Zaragoza",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Atizapán de Zaragoza, Mexico"},
 "JKT"=>
  {:iata=>"JKT",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Jakarta",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Jakarta, Java, Indonesia"},
 "JKV"=>
  {:iata=>"JKV",
   :name=>"Cherokee County Airport (FAA: JSO)",
   :icao=>"KJSO",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Texas, United States"},
 "JLA"=>
  {:iata=>"JLA",
   :name=>"Quartz Creek Airport",
   :icao=>"",
   :city=>"Cooper Landing",
   :country=>'United States', :country_code=>'US',

   :location=>"Cooper Landing, Alaska, United States"},
 "JLB"=>
  {:iata=>"JLB",
   :name=>"Long Beach Heliport",
   :icao=>"",
   :city=>"Long Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Long Beach, California, United States"},
 "JLN"=>
  {:iata=>"JLN",
   :name=>"Joplin Regional Airport",
   :icao=>"KJLN",
   :city=>"Joplin",
   :country=>'United States', :country_code=>'US',

   :location=>"Joplin, Missouri, United States"},
 "JLX"=>
  {:iata=>"JLX",
   :name=>"Los Angeles Union Station Heliport (FAA: 54L)",
   :icao=>"",
   :city=>"Los Angeles",
   :country=>'United States', :country_code=>'US',

   :location=>"Los Angeles, California, United States"},
 "JMC"=>
  {:iata=>"JMC",
   :name=>"Commodore Center Heliport",
   :icao=>"KJMC",
   :city=>"Sausalito",
   :country=>'United States', :country_code=>'US',

   :location=>"Sausalito, California, United States"},
 "JMD"=>
  {:iata=>"JMD",
   :name=>"Market Centre Heliport",
   :icao=>"",
   :city=>"Dallas",
   :country=>'United States', :country_code=>'US',

   :location=>"Dallas, Texas, United States"},
 "JMN"=>
  {:iata=>"JMN",
   :name=>"Mankato Municipal Heliport",
   :icao=>"",
   :city=>"Mankato",
   :country=>'United States', :country_code=>'US',

   :location=>"Mankato, Minnesota, United States"},
 "JMS"=>
  {:iata=>"JMS",
   :name=>"Jamestown Regional Airport",
   :icao=>"KJMS",
   :city=>"Jamestown",
   :country=>'United States', :country_code=>'US',

   :location=>"Jamestown, North Dakota, United States"},
 "JNP"=>
  {:iata=>"JNP",
   :name=>"Newport Beach Heliport",
   :icao=>"",
   :city=>"Newport Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport Beach, California, United States"},
 "JNU"=>
  {:iata=>"JNU",
   :name=>"Juneau International Airport",
   :icao=>"PAJN",
   :city=>"Juneau",
   :country=>'United States', :country_code=>'US',

   :location=>"Juneau, Alaska, United States"},
 "JOR"=>
  {:iata=>"JOR",
   :name=>"Choc Heliport (FAA: 4CA5)",
   :icao=>"",
   :city=>"Orange",
   :country=>'United States', :country_code=>'US',

   :location=>"Orange, California, United States"},
 "JOT"=>
  {:iata=>"JOT",
   :name=>"Joliet Regional Airport",
   :icao=>"KJOT",
   :city=>"Joliet",
   :country=>'United States', :country_code=>'US',

   :location=>"Joliet, Illinois, United States"},
 "JPD"=>
  {:iata=>"JPD",
   :name=>"Pasadena Heliport",
   :icao=>"",
   :city=>"Pasadena",
   :country=>'United States', :country_code=>'US',

   :location=>"Pasadena, California, United States"},
 "JPN"=>
  {:iata=>"JPN",
   :name=>"Pentagon Army Heliport",
   :icao=>"KJPN",
   :city=>"Washington",
   :country=>'United States', :country_code=>'US',

   :location=>"Washington, D.C., United States"},
 "JRA"=>
  {:iata=>"JRA",
   :name=>"West 30th Street Heliport",
   :icao=>"KJRA",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "JRB"=>
  {:iata=>"JRB",
   :name=>"Downtown Manhattan Heliport (Wall St. Heliport)",
   :icao=>"KJRB",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "JRC"=>
  {:iata=>"JRC",
   :name=>"Rochester Municipal Heliport",
   :icao=>"",
   :city=>"Rochester",
   :country=>'United States', :country_code=>'US',

   :location=>"Rochester, Minnesota, United States"},
 "JRD"=>
  {:iata=>"JRD",
   :name=>"Riverside Metro Center Heliport (FAA: CA81)",
   :icao=>"",
   :city=>"Riverside",
   :country=>'United States', :country_code=>'US',

   :location=>"Riverside, California, United States"},
 "JRE"=>
  {:iata=>"JRE",
   :name=>"East 60th Street Heliport",
   :icao=>"",
   :city=>"New York City",
   :country=>'United States', :country_code=>'US',

   :location=>"New York City, New York, United States"},
 "JSD"=>
  {:iata=>"JSD",
   :name=>"Sikorsky Heliport",
   :icao=>"KJSD",
   :city=>"Stratford",
   :country=>'United States', :country_code=>'US',

   :location=>"Stratford, Connecticut, United States"},
 "JSG"=>
  {:iata=>"JSG",
   :name=>"San Rafael Heliport",
   :icao=>"",
   :city=>"San Rafael",
   :country=>'United States', :country_code=>'US',

   :location=>"San Rafael, California, United States"},
 "JSK"=>
  {:iata=>"JSK",
   :name=>"St. Cloud Municipal Heliport",
   :icao=>"",
   :city=>"St. Cloud",
   :country=>'United States', :country_code=>'US',

   :location=>"St. Cloud, Minnesota, United States"},
 "JSL"=>
  {:iata=>"JSL",
   :name=>"Steel Pier Taj Mahal Heliport (FAA: 28NJ)",
   :icao=>"",
   :city=>"Atlantic City",
   :country=>'United States', :country_code=>'US',

   :location=>"Atlantic City, New Jersey, United States"},
 "JSN"=>
  {:iata=>"JSN",
   :name=>"Sherman Oaks Community Hospital Heliport (FAA: CL80)",
   :icao=>"",
   :city=>"Sherman Oaks",
   :country=>'United States', :country_code=>'US',

   :location=>"Sherman Oaks, California, United States"},
 "JST"=>
  {:iata=>"JST",
   :name=>"John Murtha Johnstown-Cambria County Airport",
   :icao=>"KJST",
   :city=>"Johnstown",
   :country=>'United States', :country_code=>'US',

   :location=>"Johnstown, Pennsylvania, United States"},
 "JSZ"=>
  {:iata=>"JSZ",
   :name=>"Saint-Tropez Heliport",
   :icao=>"",
   :city=>"Saint-Tropez",
   :country=>'France', :country_code=>'FR',
   :location=>"Saint-Tropez, France"},
 "JTO"=>
  {:iata=>"JTO",
   :name=>"Thousand Oaks Heliport",
   :icao=>"",
   :city=>"Thousand Oaks",
   :country=>'United States', :country_code=>'US',

   :location=>"Thousand Oaks, California, United States"},
 "JVI"=>
  {:iata=>"JVI",
   :name=>"Central Jersey Regional Airport (FAA: 47N)",
   :icao=>"",
   :city=>"Manville",
   :country=>'United States', :country_code=>'US',

   :location=>"Manville, New Jersey, United States"},
 "JVL"=>
  {:iata=>"JVL",
   :name=>"Southern Wisconsin Regional Airport",
   :icao=>"KJVL",
   :city=>"Janesville",
   :country=>'United States', :country_code=>'US',

   :location=>"Janesville, Wisconsin, United States"},
 "JWC"=>
  {:iata=>"JWC",
   :name=>"Warner Center Plaza One Heliport (FAA: 96CA)",
   :icao=>"",
   :city=>"Woodland Hills",
   :country=>'United States', :country_code=>'US',

   :location=>"Woodland Hills, California, United States"},
 "JWH"=>
  {:iata=>"JWH",
   :name=>"Westchase Hilton Heliport (FAA: TS24)",
   :icao=>"",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "JXN"=>
  {:iata=>"JXN",
   :name=>"Jackson County Airport (Reynolds Field)",
   :icao=>"KJXN",
   :city=>"Jackson",
   :country=>'United States', :country_code=>'US',

   :location=>"Jackson, Michigan, United States"},
 "JYO"=>
  {:iata=>"JYO",
   :name=>"Leesburg Executive Airport",
   :icao=>"KJYO",
   :city=>"Leesburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Leesburg, Virginia, United States"}}

end
