# encoding: UTF-8
def airp_17
  {"PIW"=>
  {:iata=>"PIW",
   :name=>"Pikwitonei Airport",
   :city=>"Pikwitonei",
   :icao=>"CZMN",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Pikwitonei, Canada"},
 "PQT"=>
  {:iata=>"PQT",
   :name=>"Qeqertaq Heliport",
   :icao=>"BGQE",
   :city=>"Qeqertaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Qeqertaq, Greenland"},
 "PQM"=>
  {:iata=>"PQM",
   :name=>"Palenque International Airport",
   :city=>"Palenque",
   :icao=>"MMPQ",
   :country=>'Mexico', :country_code=>'MX',
   :location=>"Palenque, Mexico"},
 "PDS"=>
  {:iata=>"PDS",
   :name=>"Piedras Negras International Airport",
   :icao=>"MMPG",
   :city=>"Piedras Negras",
   :country=>'Mexico', :country_code=>'MX',
   :location=>"Piedras Negras, Coahuila, Mexico"},
 "PAZ"=>
  {:iata=>"PAZ",
   :name=>"El Tajín National Airport",
   :icao=>"MMPA",
   :city=>"Poza Rica",
   :country=>'Mexico', :country_code=>'MX',
   :location=>"Poza Rica, Veracruz, Mexico"},
 "PBC"=>
  {:iata=>"PBC",
   :name=>"Hermanos Serdán International Airport",
   :icao=>"MMPB",
   :city=>"Puebla",
   :country=>'Mexico', :country_code=>'MX',
   :location=>"Puebla, Mexico"},
 "PXM"=>
  {:iata=>"PXM",
   :name=>"Puerto Escondido International Airport",
   :icao=>"MMPS",
   :city=>"Puerto Escondido",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Puerto Escondido, Oaxaca, Mexico"},
 "PPE"=>
  {:iata=>"PPE",
   :name=>"Mar de Cortés International Airport",
   :icao=>"KPPE",
   :city=>"La Jolla de Cortes",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"La Jolla de Cortes, Sonora, Mexico"},
 "PVR"=>
  {:iata=>"PVR",
   :name=>"Lic. Gustavo Díaz Ordaz International Airport",
   :icao=>"MMPR",
   :city=>"Puerto Vallarta",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Puerto Vallarta, Jalisco, Mexico"},
 "PNO"=>
  {:iata=>"PNO",
   :name=>"Pinotepa Nacional Airport",
   :city=>"Pinotepa Nacional",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Pinotepa Nacional, Mexico"},
 "PCM"=>
  {:iata=>"PCM",
   :name=>"Playa del Carmen Airport",
   :icao=>"",
   :city=>"Playa del Carmen",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Playa del Carmen, Mexico"},
 "PUH"=>
  {:iata=>"PUH",
   :name=>"Pochutla Airport",
   :city=>"Pochutla",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Pochutla, Mexico"},
 "PJZ"=>
  {:iata=>"PJZ",
   :name=>"Puerto Juarez Airport",
   :icao=>"",
   :city=>"Puerto Juárez",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Puerto Juárez, Quintana Roo, Mexico"},
 "PCV"=>
  {:iata=>"PCV",
   :name=>"Punta Chivato Airport",
   :city=>"Punta Chivato",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Punta Chivato, Mexico"},
 "PCO"=>
  {:iata=>"PCO",
   :name=>"Punta Colorada Airport",
   :city=>"Punta Colorada",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Punta Colorada, Mexico"},
 "POY"=>
  {:iata=>"POY",
   :name=>"Powell Municipal Airport",
   :icao=>"KPOY",
   :city=>"Powell",
   :country=>'United States', :country_code=>'US',

   :location=>"Powell, Wyoming, United States"},
 "PRA"=>
  {:iata=>"PRA",
   :name=>"General Justo José de Urquiza Airport",
   :icao=>"SAAP",
   :city=>"Paraná",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Paraná, Entre Ríos, Argentina"},
 "PMQ"=>
  {:iata=>"PMQ",
   :name=>"Perito Moreno Airport",
   :icao=>"SAWP",
   :city=>"Perito Moreno",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Perito Moreno, Santa Cruz, Argentina"},
 "PSS"=>
  {:iata=>"PSS",
   :name=>"Libertador General José de San Martín Airport",
   :icao=>"SARP",
   :city=>"Posadas",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Posadas, Argentina"},
 "PUD"=>
  {:iata=>"PUD",
   :name=>"Puerto Deseado Airport",
   :icao=>"SAWD",
   :city=>"Puerto Deseado",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Puerto Deseado, Santa Cruz Province, Argentina"},
 "PMY"=>
  {:iata=>"PMY",
   :name=>"El Tehuelche Airport",
   :icao=>"SAVY",
   :city=>"Puerto Madryn",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Puerto Madryn, Argentina"},
 "PEH"=>
  {:iata=>"PEH",
   :name=>"Comodoro P. Zanni Airport",
   :icao=>"SAZP",
   :city=>"Pehuajó",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Pehuajó, Argentina"},
 "PRQ"=>
  {:iata=>"PRQ",
   :name=>"Termal Airport (Pres. Roque Saenz Pena Airport)",
   :icao=>"SARS",
   :city=>"Presidencia Roque Sáenz Peña",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Presidencia Roque Sáenz Peña, Chaco, Argentina"},
 "POI"=>
  {:iata=>"POI",
   :name=>"Captain Nicolas Rojas Airport",
   :city=>"Potosi",
   :icao=>"SLPO",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Potosi, Bolivia"},
 "PSZ"=>
  {:iata=>"PSZ",
   :name=>"Puerto Suárez International Airport",
   :icao=>"SLPS",
   :city=>"Puerto Suárez",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Puerto Suárez, Bolivia"},
 "PUR"=>
  {:iata=>"PUR",
   :name=>"Puerto Rico Airport",
   :city=>"Puerto Rico",
   :icao=>"",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Puerto Rico, Bolivia"},
 "POA"=>
  {:iata=>"POA",
   :name=>"Salgado Filho International Airport",
   :icao=>"SBPA",
   :city=>"Porto Alegre",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto Alegre, Rio Grande do Sul, Brazil"},
 "PLU"=>
  {:iata=>"PLU",
   :name=>"Pampulha Domestic Airport",
   :icao=>"SBBH",
   :city=>"Belo Horizonte",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Belo Horizonte, Brazil"},
 "PMW"=>
  {:iata=>"PMW",
   :name=>"Palmas Airport",
   :icao=>"SBPJ",
   :city=>"Palmas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Palmas, Tocantins, Brazil"},
 "PIN"=>
  {:iata=>"PIN",
   :name=>"Julio Belem Airport",
   :icao=>"SWPI",
   :city=>"Parintins",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Parintins, Amazonas, Brazil"},
 "PHB"=>
  {:iata=>"PHB",
   :name=>"Parnaíba-Prefeito Dr. João Silva Filho International Airport",
   :icao=>"SBPB",
   :city=>"Parnaiba",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Parnaiba, Piaui, Brazil"},
 "PFB"=>
  {:iata=>"PFB",
   :name=>"Lauro Kurtz Airport (Passo Fundo Airport)",
   :icao=>"SBPF",
   :city=>"Passo Fundo",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Passo Fundo, Rio Grande do Sul, Brazil"},
 "POJ"=>
  {:iata=>"POJ",
   :name=>"Patos de Minas Airport",
   :icao=>"",
   :city=>"Patos de Minas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Patos de Minas, Minas Gerais, Brazil"},
 "PAV"=>
  {:iata=>"PAV",
   :name=>"Paulo Afonso Airport",
   :city=>"Paulo Afonso",
   :icao=>"SBUF",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Paulo Afonso, Brazil"},
 "PET"=>
  {:iata=>"PET",
   :name=>"Pelotas International Airport",
   :icao=>"SBPK",
   :city=>"Pelotas",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pelotas, Rio Grande do Sul, Brazil"},
 "PNZ"=>
  {:iata=>"PNZ",
   :name=>"Senador Nilo Coelho Airport",
   :icao=>"SBPL",
   :city=>"Petrolina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Petrolina, Pernambuco, Brazil"},
 "PLL"=>
  {:iata=>"PLL",
   :name=>"Ponta Pelada Airport",
   :icao=>"SBMN",
   :city=>"Manaus",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Manaus, Amazonas, Brazil"},
 "PVH"=>
  {:iata=>"PVH",
   :name=>"Governador Jorge Teixeira de Oliveira International Airport",
   :icao=>"SBPV",
   :city=>"Porto Velho",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto Velho, Brazil"},
 "PPB"=>
  {:iata=>"PPB",
   :name=>"Adhemar de Barros Airport",
   :icao=>"SBDN",
   :city=>"Presidente Prudente",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Presidente Prudente, São Paulo, Brazil"},
 "PNG"=>
  {:iata=>"PNG",
   :name=>"Paranagua Municipal Airport",
   :city=>"Paranagua",
   :icao=>"SSPG",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Paranagua, Brazil"},
 "PBB"=>
  {:iata=>"PBB",
   :name=>"Paranaiba Airport",
   :city=>"Paranaiba",
   :icao=>"SSPN",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Paranaiba, Brazil"},
 "PVI"=>
  {:iata=>"PVI",
   :name=>"Paranavia Airport",
   :city=>"Paranavia",
   :icao=>"SSPI",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Paranavia, Brazil"},
 "PSW"=>
  {:iata=>"PSW",
   :name=>"Passos Airport",
   :city=>"Passos",
   :icao=>"SNOS",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Passos, Brazil"},
 "PTO"=>
  {:iata=>"PTO",
   :name=>"Pato Branco Municipal Airport",
   :city=>"Pato Branco",
   :icao=>"SSPB",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pato Branco, Brazil"},
 "PCS"=>
  {:iata=>"PCS",
   :name=>"Picos Airport",
   :city=>"Picos",
   :icao=>"SNPC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Picos, Brazil"},
 "PBQ"=>
  {:iata=>"PBQ",
   :name=>"Pimenta Bueno Airport",
   :city=>"Pimenta Bueno",
   :icao=>"SWPM",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pimenta Bueno, Brazil"},
 "PHI"=>
  {:iata=>"PHI",
   :name=>"Pinheiro Airport",
   :city=>"Pinheiro",
   :icao=>"SNYE",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pinheiro, Brazil"},
 "PIV"=>
  {:iata=>"PIV",
   :name=>"Pirapora Airport",
   :city=>"Pirapora",
   :icao=>"SNRA",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pirapora, Brazil"},
 "PIG"=>
  {:iata=>"PIG",
   :name=>"Pitinga Airport",
   :city=>"Pitinga",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pitinga, Brazil"},
 "POO"=>
  {:iata=>"POO",
   :name=>"Pocos De Caldas Airport",
   :city=>"Pocos De Caldas",
   :icao=>"SBPC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pocos De Caldas, Brazil"},
 "PGZ"=>
  {:iata=>"PGZ",
   :name=>"Sant'Ana Airport",
   :city=>"Ponta Grossa",
   :icao=>"SBGS",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ponta Grossa, Brazil"},
 "PMG"=>
  {:iata=>"PMG",
   :name=>"Ponta Porã International Airport",
   :icao=>"SBPP",
   :city=>"Ponta Porã",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ponta Porã, Mato Grosso do Sul, Brazil"},
 "PBX"=>
  {:iata=>"PBX",
   :name=>"Porto Alegre do Norte Airport",
   :icao=>"",
   :city=>"Porto Alegre do Norte",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto Alegre do Norte, Mato Grosso, Brazil"},
 "PBV"=>
  {:iata=>"PBV",
   :name=>"Porto dos Gauchos Airport",
   :icao=>"",
   :city=>"Porto dos Gaúchos",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto dos Gaúchos, Mato Grosso, Brazil"},
 "PNB"=>
  {:iata=>"PNB",
   :name=>"Porto Nacional Airport",
   :city=>"Porto Nacional",
   :icao=>"SBPN",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto Nacional, Brazil"},
 "PTQ"=>
  {:iata=>"PTQ",
   :name=>"Porto de Moz Airport",
   :city=>"Porto de Moz",
   :icao=>"SBMZ",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Porto de Moz, Brazil"},
 "PPY"=>
  {:iata=>"PPY",
   :name=>"Pouso Alegre Airport",
   :city=>"Pouso Alegre",
   :icao=>"SNZA",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Pouso Alegre, Brazil"},
 "PDF"=>
  {:iata=>"PDF",
   :name=>"Prado Airport",
   :city=>"Prado",
   :icao=>"SNRD",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Prado, Brazil"},
 "PDR"=>
  {:iata=>"PDR",
   :name=>"Presidente Dutra Municipal Airport",
   :city=>"Presidente Dutra",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Presidente Dutra, Brazil"},
 "PGG"=>
  {:iata=>"PGG",
   :name=>"Progresso Airport",
   :city=>"Progresso",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Progresso, Brazil"},
 "PMC"=>
  {:iata=>"PMC",
   :name=>"El Tepual Airport",
   :icao=>"SCTE",
   :city=>"Puerto Montt",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Puerto Montt, Chile"},
 "PNT"=>
  {:iata=>"PNT",
   :name=>"Teniente Julio Gallardo Airport",
   :icao=>"SCNT",
   :city=>"Puerto Natales",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Puerto Natales, Chile"},
 "PUQ"=>
  {:iata=>"PUQ",
   :name=>"Carlos Ibanez Del Campo International Airport",
   :icao=>"SCCI",
   :city=>"Punta Arenas",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Punta Arenas, Chile"},
 "PUX"=>
  {:iata=>"PUX",
   :name=>"Puerto Varas Airport",
   :city=>"Puerto Varas",
   :icao=>"",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Puerto Varas, Chile"},
 "PSO"=>
  {:iata=>"PSO",
   :name=>"Antonio Nariño Airport",
   :icao=>"SKPS",
   :city=>"Pasto",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Pasto, Colombia"},
 "PEI"=>
  {:iata=>"PEI",
   :name=>"Matecaña International Airport",
   :icao=>"SKPE",
   :city=>"Pereira",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Pereira, Colombia"},
 "PPN"=>
  {:iata=>"PPN",
   :name=>"Guillermo León Valencia Airport",
   :icao=>"SKPP",
   :city=>"Popayán",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Popayán, Colombia"},
 "PVA"=>
  {:iata=>"PVA",
   :name=>"El Embrujo Airport",
   :icao=>"SKPV",
   :city=>"Providencia Island",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Providencia Island, Colombia"},
 "PUU"=>
  {:iata=>"PUU",
   :name=>"Tres de Mayo Airport",
   :icao=>"SKAS",
   :city=>"Puerto Asís",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Asís, Colombia"},
 "PCR"=>
  {:iata=>"PCR",
   :name=>"Puerto Carreño Airport",
   :icao=>"",
   :city=>"Puerto Carreño",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Carreño, Colombia"},
 "PDA"=>
  {:iata=>"PDA",
   :name=>"Obando Airport",
   :icao=>"SKPD",
   :city=>"Puerto Inírida",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Inírida, Colombia"},
 "PAL"=>
  {:iata=>"PAL",
   :name=>"Palanquero Airport",
   :city=>"Palanquero",
   :icao=>"SKPQ",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Palanquero, Colombia"},
 "PYN"=>
  {:iata=>"PYN",
   :name=>"Payan Airport",
   :city=>"Payan",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Payan, Colombia"},
 "PZA"=>
  {:iata=>"PZA",
   :name=>"Casanare Airport",
   :city=>"Paz De Ariporo",
   :icao=>"SKPZ",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Paz De Ariporo, Colombia"},
 "PTX"=>
  {:iata=>"PTX",
   :name=>"Pitalito Airport",
   :city=>"Pitalito",
   :icao=>"SKPI",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Pitalito, Colombia"},
 "PLA"=>
  {:iata=>"PLA",
   :name=>"Planadas Airport",
   :city=>"Planadas",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Planadas, Colombia"},
 "PLC"=>
  {:iata=>"PLC",
   :name=>"Planeta Rica Airport",
   :city=>"Planeta Rica",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Planeta Rica, Colombia"},
 "PLT"=>
  {:iata=>"PLT",
   :name=>"Plato Airport",
   :city=>"Plato",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Plato, Colombia"},
 "PRE"=>
  {:iata=>"PRE",
   :name=>"Pore Airport",
   :city=>"Pore",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Pore, Colombia"},
 "PBE"=>
  {:iata=>"PBE",
   :name=>"Puerto Berrio Airport",
   :city=>"Puerto Berrio",
   :icao=>"SKPR",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Berrio, Colombia"},
 "PYA"=>
  {:iata=>"PYA",
   :name=>"Puerto Boyaca Airport",
   :city=>"Puerto Boyaca",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Boyaca, Colombia"},
 "PCC"=>
  {:iata=>"PCC",
   :name=>"Puerto Rico Airport",
   :city=>"Puerto Rico",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Puerto Rico, Colombia"},
 "PVO"=>
  {:iata=>"PVO",
   :name=>"Reales Tamarindos Airport",
   :icao=>"SEPV",
   :city=>"Portoviejo",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Portoviejo, Ecuador"},
 "PTZ"=>
  {:iata=>"PTZ",
   :name=>"Rio Amazonas Airport",
   :icao=>"SEPA",
   :city=>"Shell Mera",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Shell Mera, Ecuador"},
 "PYO"=>
  {:iata=>"PYO",
   :name=>"Putumayo Airport",
   :city=>"Putumayo",
   :icao=>"",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Putumayo, Ecuador"},
 "PSY"=>
  {:iata=>"PSY",
   :name=>"Port Stanley Airport",
   :icao=>"SFAL",
   :city=>"Stanley",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Stanley, Falkland Islands, United Kingdom"},
 "PMT"=>
  {:iata=>"PMT",
   :name=>"Paramakotoi Airport",
   :city=>"Paramakotoi",
   :icao=>"",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Paramakotoi, Guyana"},
 "PRR"=>
  {:iata=>"PRR",
   :name=>"Paruima Airport",
   :icao=>"SYPR",
   :city=>"Paruima",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Paruima, Guyana"},
 "PIQ"=>
  {:iata=>"PIQ",
   :name=>"Pipillipai Airport",
   :city=>"Pipillipai",
   :icao=>"",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Pipillipai, Guyana"},
 "PKM"=>
  {:iata=>"PKM",
   :name=>"Port Kaituma Airport",
   :city=>"Port Kaituma",
   :icao=>"",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Port Kaituma, Guyana"},
 "PJC"=>
  {:iata=>"PJC",
   :name=>"Dr. Augusto Roberto Fuster International Airport",
   :icao=>"SGPJ",
   :city=>"Pedro Juan Caballero",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Pedro Juan Caballero, Paraguay"},
 "PIL"=>
  {:iata=>"PIL",
   :name=>"Carlos Miguel Jiménez Airport",
   :icao=>"SGPI",
   :city=>"Pilar",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Pilar, Paraguay"},
 "PCJ"=>
  {:iata=>"PCJ",
   :name=>"Puerto La Victoria Airport",
   :city=>"Puerto La Victoria",
   :icao=>"",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Puerto La Victoria, Paraguay"},
 "PBT"=>
  {:iata=>"PBT",
   :name=>"Puerto Leda Airport",
   :city=>"Puerto Leda",
   :icao=>"",
   :country=>"Paraguay",
:country_code=>"PY",
   :location=>"Puerto Leda, Paraguay"},
 "PIO"=>
  {:iata=>"PIO",
   :name=>"Capitán FAP Renán Elías Olivera Airport",
   :icao=>"SPSO",
   :city=>"Pisco",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Pisco, Peru"},
 "PIU"=>
  {:iata=>"PIU",
   :name=>"Piura Airport",
   :icao=>"SPUR",
   :city=>"Piura",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Piura, Peru"},
 "PCL"=>
  {:iata=>"PCL",
   :name=>"Captain Rolden International Airport",
   :icao=>"SPCL",
   :city=>"Pucallpa",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Pucallpa, Peru"},
 "PEM"=>
  {:iata=>"PEM",
   :name=>"Puerto Maldonado International Airport",
   :icao=>"SPTU",
   :city=>"Puerto Maldonado",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Puerto Maldonado, Peru"},
 "PBM"=>
  {:iata=>"PBM",
   :name=>"Johan Adolf Pengel International Airport",
   :icao=>"SMJP",
   :city=>"Zanderij (near Paramaribo)",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Zanderij (near Paramaribo), Suriname"},
 "PDP"=>
  {:iata=>"PDP",
   :name=>"C/C Carlos A. Curbelo de Laguna del Sauce International Airport",
   :icao=>"SULS",
   :city=>"Maldonado/Punta del Este",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Maldonado/Punta del Este, Maldonado, Uruguay"},
 "PDU"=>
  {:iata=>"PDU",
   :name=>"Tydeo Larre Borges International Airport",
   :icao=>"SUPU",
   :city=>"Paysandú",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Paysandú, Paysandú, Uruguay"},
 "PMV"=>
  {:iata=>"PMV",
   :name=>"Del Caribe International General Santiago Marino Airport",
   :icao=>"SVMG",
   :city=>"Porlamar",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Porlamar, Venezuela"},
 "PYH"=>
  {:iata=>"PYH",
   :name=>"Cacique Aramare Airport",
   :icao=>"SVPA",
   :city=>"Puerto Ayacucho",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Puerto Ayacucho, Venezuela"},
 "PBL"=>
  {:iata=>"PBL",
   :name=>"General Bartolome Salom International Airport",
   :city=>"Puerto Cabello",
   :icao=>"SVPC",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Puerto Cabello, Venezuela"},
 "PZO"=>
  {:iata=>"PZO",
   :name=>"Manuel Carlos Piar Guayana Airport",
   :icao=>"SVPR",
   :city=>"Ciudad Guayana",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Ciudad Guayana, Venezuela"},
 "PTM"=>
  {:iata=>"PTM",
   :name=>"Palmarito Airport",
   :city=>"Palmarito",
   :icao=>"SVPT",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Palmarito, Venezuela"},
 "PDZ"=>
  {:iata=>"PDZ",
   :name=>"Pedernales Airport",
   :city=>"Pedernales",
   :icao=>"",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Pedernales, Venezuela"},
 "PPH"=>
  {:iata=>"PPH",
   :name=>"Peraitepuy Airport",
   :city=>"Peraitepuy",
   :icao=>"",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Peraitepuy, Venezuela"},
 "PPZ"=>
  {:iata=>"PPZ",
   :name=>"Puerto Paez Airport",
   :city=>"Puerto Paez",
   :icao=>"",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Puerto Paez, Venezuela"},
 "PPG"=>
  {:iata=>"PPG",
   :name=>"Pago Pago International Airport",
   :icao=>"NSTU",
   :city=>"Pago Pago",
   :country=>'American Samoa', :country_code=>'AS',
   :location=>"Pago Pago, American Samoa"},
 "PER"=>
  {:iata=>"PER",
   :name=>"Perth Airport",
   :icao=>"YPPH",
   :city=>"Perth",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Perth, Western Australia, Australia"},
 "PMK"=>
  {:iata=>"PMK",
   :name=>"Palm Island Airport",
   :city=>"Palm Island",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Palm Island, Australia"},
 "PBO"=>
  {:iata=>"PBO",
   :name=>"Paraburdoo Airport",
   :icao=>"YPBO",
   :city=>"Paraburdoo",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Paraburdoo, Western Australia, Australia"},
 "PKE"=>
  {:iata=>"PKE",
   :name=>"Parkes Airport",
   :city=>"Parkes",
   :icao=>"YPKS",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Parkes, Australia"},
 "PUG"=>
  {:iata=>"PUG",
   :name=>"Port Augusta Airport",
   :city=>"Port Augusta",
   :icao=>"YPAG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Augusta, Australia"},
 "PHE"=>
  {:iata=>"PHE",
   :name=>"Port Hedland International Airport",
   :icao=>"YPPD",
   :city=>"Port Hedland",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Hedland, Western Australia, Australia"},
 "PLO"=>
  {:iata=>"PLO",
   :name=>"Port Lincoln Airport",
   :city=>"Port Lincoln",
   :icao=>"YPLC",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Lincoln, Australia"},
 "PQQ"=>
  {:iata=>"PQQ",
   :name=>"Port Macquarie Airport",
   :icao=>"YPMQ",
   :city=>"Port Macquarie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Macquarie, New South Wales, Australia"},
 "PTJ"=>
  {:iata=>"PTJ",
   :name=>"Portland Airport",
   :icao=>"YPOD",
   :city=>"Portland",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Portland, Victoria, Australia"},
 "PPP"=>
  {:iata=>"PPP",
   :name=>"Whitsunday Coast Airport",
   :icao=>"YBPN",
   :city=>"Proserpine",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Proserpine, Queensland, Australia"},
 "PDE"=>
  {:iata=>"PDE",
   :name=>"Pandie Pandie Airport",
   :city=>"Pandie Pandie",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Pandie Pandie, Australia"},
 "PRD"=>
  {:iata=>"PRD",
   :name=>"Pardoo Airport",
   :city=>"Pardoo",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Pardoo, Australia"},
 "PDN"=>
  {:iata=>"PDN",
   :name=>"Parndana Airport",
   :city=>"Parndana",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Parndana, Australia"},
 "PEA"=>
  {:iata=>"PEA",
   :name=>"Penneshaw Airport",
   :city=>"Penneshaw",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Penneshaw, Australia"},
 "PEY"=>
  {:iata=>"PEY",
   :name=>"Penong Airport",
   :city=>"Penong",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Penong, Australia"},
 "PBY"=>
  {:iata=>"PBY",
   :name=>"Hamilton/Prosperine Airport",
   :city=>"Peppers Palm Bay (Island Resort)",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Peppers Palm Bay (Island Resort), Australia"},
 "PEP"=>
  {:iata=>"PEP",
   :name=>"Peppimenarti Airport",
   :city=>"Peppimenarti",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Peppimenarti, Australia"},
 "PTI"=>
  {:iata=>"PTI",
   :name=>"Port Douglas Airport",
   :city=>"Port Douglas",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Douglas, Australia"},
 "PHJ"=>
  {:iata=>"PHJ",
   :name=>"Port Hunter Airport",
   :city=>"Port Hunter",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Hunter, Australia"},
 "PKT"=>
  {:iata=>"PKT",
   :name=>"Port Keats Airfield",
   :icao=>"YKPT",
   :city=>"Wadeye",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wadeye, Northern Territory, Australia"},
 "PPI"=>
  {:iata=>"PPI",
   :name=>"Port Pirie Airport",
   :icao=>"YPIR",
   :city=>"Port Pirie",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Pirie, South Australia, Australia"},
 "PTE"=>
  {:iata=>"PTE",
   :name=>"Port Stephens Airport",
   :city=>"Port Stephens",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Port Stephens, Australia"},
 "PYE"=>
  {:iata=>"PYE",
   :name=>"Penrhyn Island Airport",
   :city=>"Penrhyn Island",
   :icao=>"NCPY",
   :country=>'Islands', :country_code=>'',
   :location=>"Penrhyn Island, Islands"},
 "PZK"=>
  {:iata=>"PZK",
   :name=>"Pukapuka Island Airport",
   :city=>"Pukapuka Atoll",
   :icao=>"NCPK",
   :country=>'Islands', :country_code=>'',
   :location=>"Pukapuka Atoll, Islands"},
 "PTF"=>
  {:iata=>"PTF",
   :name=>"Malololailai Airport",
   :city=>"Malololailai",
   :icao=>"NFFO",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Malololailai, Fiji"},
 "PHR"=>
  {:iata=>"PHR",
   :name=>"Pacific Harbor Airport",
   :city=>"Pacific Harbor",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Pacific Harbor, Fiji"},
 "PPT"=>
  {:iata=>"PPT",
   :name=>"Faa'a International Airport",
   :icao=>"NTAA",
   :city=>"Papeete",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Papeete, Tahiti, French Polynesia"},
 "PKP"=>
  {:iata=>"PKP",
   :name=>"Puka Puka Airport",
   :city=>"Puka Puka",
   :icao=>"NTGP",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Puka Puka, Polynesia"},
 "PUK"=>
  {:iata=>"PUK",
   :name=>"Pukarua Airport",
   :icao=>"NTGQ",
   :city=>"Pukarua",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Pukarua, Tuamotus, French Polynesia"},
 "PNI"=>
  {:iata=>"PNI",
   :name=>"Pohnpei International Airport",
   :icao=>"PTPN",
   :city=>"Kolonia",
   :country=>'Federated States of Micronesia', :country_code=>'FM',
   :location=>"Kolonia, Federated States of Micronesia"},
 "PDC"=>
  {:iata=>"PDC",
   :name=>"Mueo Airport",
   :icao=>"NWWQ",
   :city=>"Mueo",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Mueo, New Caledonia"},
 "PUV"=>
  {:iata=>"PUV",
   :name=>"Poum Airport",
   :city=>"Poum",
   :icao=>"",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Poum, Caledonia"},
 "PMR"=>
  {:iata=>"PMR",
   :name=>"Palmerston North International Airport",
   :icao=>"NZPM",
   :city=>"Palmerston North",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Palmerston North, New Zealand"},
 "PPQ"=>
  {:iata=>"PPQ",
   :name=>"Paraparaumu Airport",
   :icao=>"NZPP",
   :city=>"Paraparaumu Beach",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Paraparaumu Beach, New Zealand"},
 "PKL"=>
  {:iata=>"PKL",
   :name=>"Pakatoa Island Airport",
   :city=>"Pakatoa Island",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Pakatoa Island, Zealand"},
 "PCN"=>
  {:iata=>"PCN",
   :name=>"Koromiko Airport",
   :city=>"Picton",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Picton, Zealand"},
 "PRS"=>
  {:iata=>"PRS",
   :name=>"Parasi Airport",
   :city=>"Parasi",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Parasi, Islands"},
 "PBJ"=>
  {:iata=>"PBJ",
   :name=>"Paama Airport",
   :city=>"Paama",
   :icao=>"",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Paama, Vanuatu"},
 "PID"=>
  {:iata=>"PID",
   :name=>"Paradise Island Airport",
   :icao=>"MYPI",
   :city=>"Paradise Island",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Paradise Island, Bahamas"},
 "PWN"=>
  {:iata=>"PWN",
   :name=>"Pitts Town Airport",
   :city=>"Pitts Town",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Pitts Town, Bahamas"},
 "PPO"=>
  {:iata=>"PPO",
   :name=>"La Porte Municipal Airport",
   :icao=>"KPPO",
   :city=>"La Porte",
   :country=>'United States', :country_code=>'US',

   :location=>"La Porte, Indiana, United States"},
 "PST"=>
  {:iata=>"PST",
   :name=>"Preston Airport",
   :icao=>"",
   :city=>"Guatemala",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Guatemala, Cuba"},
 "POP"=>
  {:iata=>"POP",
   :name=>"Puerto Plata Airport",
   :icao=>"MDPP",
   :city=>"San Felipe de Puerto Plata",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"San Felipe de Puerto Plata, Dominican Republic"},
 "PUJ"=>
  {:iata=>"PUJ",
   :name=>"Punta Cana International Airport",
   :icao=>"MDPC",
   :city=>"Punta Cana",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"Punta Cana, Dominican Republic"},
 "PTP"=>
  {:iata=>"PTP",
   :name=>"Guadeloupe Pôle Caraïbes Airport",
   :icao=>"TFFR",
   :city=>"Pointe-à-Pitre",
   :country=>'Guadeloupe', :country_code=>'GP',
   :location=>"Pointe-à-Pitre, Guadeloupe"},
 "PAP"=>
  {:iata=>"PAP",
   :name=>"Port-au-Prince International Airport",
   :icao=>"MTPP",
   :city=>"Port-au-Prince",
   :country=>'Haiti', :country_code=>'HT',
   :location=>"Port-au-Prince, Haiti"},
 "PAX"=>
  {:iata=>"PAX",
   :name=>"Port De Paix Airport",
   :city=>"Port De Paix",
   :icao=>"MTPX",
   :country=>'Haiti', :country_code=>'HT',
   :location=>"Port De Paix, Haiti"},
 "POT"=>
  {:iata=>"POT",
   :name=>"Ken Jones Aerodrome",
   :icao=>"MKKJ",
   :city=>"Port Antonio",
   :country=>'Jamaica', :country_code=>'JM',
   :location=>"Port Antonio, Jamaica"},
 "PSE"=>
  {:iata=>"PSE",
   :name=>"Mercedita Airport",
   :icao=>"TJPS",
   :city=>"Ponce",
   :country=>"Puerto Rico",
:country_code=>"PR",
   :location=>"Ponce, Puerto Rico"},
 "PPD"=>
  {:iata=>"PPD",
   :name=>"Palmas Del Mar Air Strip",
   :city=>"Humacao",
   :icao=>"",
   :country=>'Rico', :country_code=>'',
   :location=>"Humacao, Rico"},
 "PLI"=>
  {:iata=>"PLI",
   :name=>"Palm Island Airport",
   :city=>"Palm Island",
   :icao=>"",
   :country=>'Grenadines', :country_code=>'',
   :location=>"Palm Island, Grenadines"},
 "POS"=>
  {:iata=>"POS",
   :name=>"Piarco International Airport",
   :icao=>"TTPP",
   :city=>"Piarco (near Port of Spain)",
   :country=>'Trinidad and Tobago', :country_code=>'TT',
   :location=>"Piarco (near Port of Spain), Trinidad and Tobago"},
 "PLS"=>
  {:iata=>"PLS",
   :name=>"Providenciales International Airport",
   :icao=>"MBPV",
   :city=>"Providenciales",
   :country=>'Turks and Caicos Islands', :country_code=>'TC',
   :location=>"Providenciales, Turks and Caicos Islands"},
 "PIC"=>
  {:iata=>"PIC",
   :name=>"Pine Cay Airport",
   :city=>"Pine Cay",
   :icao=>"MBPI",
   :country=>'Islands', :country_code=>'',
   :location=>"Pine Cay, Islands"},
 "PGI"=>
  {:iata=>"PGI",
   :name=>"Chitato Airport",
   :city=>"Chitato",
   :icao=>"",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Chitato, Angola"},
 "PBN"=>
  {:iata=>"PBN",
   :name=>"Porto Amboim Airport",
   :city=>"Porto Amboim",
   :icao=>"FNPA",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Porto Amboim, Angola"},
 "PKO"=>
  {:iata=>"PKO",
   :name=>"Parakou Airport",
   :icao=>"DBBP",
   :city=>"Parakou",
   :country=>'Benin', :country_code=>'BJ',
   :location=>"Parakou, Benin"},
 "PKW"=>
  {:iata=>"PKW",
   :name=>"Selebi Phikwe Airport",
   :icao=>"FBSP",
   :city=>"Selebi Phikwe",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Selebi Phikwe, Botswana"},
 "PUP"=>
  {:iata=>"PUP",
   :name=>"Pô Airport",
   :icao=>"DFCP",
   :city=>"Pô",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Pô, Burkina Faso"},
 "PLF"=>
  {:iata=>"PLF",
   :name=>"Pala Airport",
   :city=>"Pala",
   :icao=>"FTTP",
   :country=>'Chad', :country_code=>'TD',
   :location=>"Pala, Chad"},
 "PNR"=>
  {:iata=>"PNR",
   :name=>"Pointe Noire Airport",
   :icao=>"FCPP",
   :city=>"Pointe-Noire",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Pointe-Noire, Republic of the Congo"},
 "PWI"=>
  {:iata=>"PWI",
   :name=>"Beles Airport",
   :city=>"Pawi",
   :icao=>"",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Pawi, Ethiopia"},
 "POG"=>
  {:iata=>"POG",
   :name=>"Port Gentil Airport",
   :icao=>"FOOG",
   :city=>"Port Gentil",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Port Gentil, Gabon"},
 "PEL"=>
  {:iata=>"PEL",
   :name=>"Pelaneng Airport",
   :city=>"Pelaneng",
   :icao=>"",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Pelaneng, Lesotho"},
 "POL"=>
  {:iata=>"POL",
   :name=>"Pemba Airport",
   :icao=>"FQPB",
   :city=>"Pemba/Porto Amelia",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Pemba/Porto Amelia, Mozambique"},
 "PEB"=>
  {:iata=>"PEB",
   :name=>"Pebane Airport",
   :city=>"Pebane",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Pebane, Mozambique"},
 "PDD"=>
  {:iata=>"PDD",
   :name=>"Ponta De Ouro",
   :city=>"Ponta De Ouro",
   :icao=>"FQPO",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Ponta De Ouro, Mozambique"},
 "PHC"=>
  {:iata=>"PHC",
   :name=>"Port Harcourt International Airport (Omagwa Int'l)",
   :icao=>"DNPO",
   :city=>"Port Harcourt",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Port Harcourt, Nigeria"},
 "PHG"=>
  {:iata=>"PHG",
   :name=>"Port Harcourt City Airport",
   :city=>"Port Harcourt",
   :icao=>"",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Port Harcourt, Nigeria"},
 "PGP"=>
  {:iata=>"PGP",
   :name=>"Porto Alegre Airport",
   :city=>"Porto Alegre",
   :icao=>"",
   :country=>'Principe', :country_code=>'ST',
   :location=>"Porto Alegre, Principe"},
 "PCP"=>
  {:iata=>"PCP",
   :name=>"Principe Airport",
   :city=>"Principe",
   :icao=>"FPPR",
   :country=>'Principe', :country_code=>'ST',
   :location=>"Principe, Principe"},
 "POD"=>
  {:iata=>"POD",
   :name=>"Podor Airport",
   :icao=>"GOSP",
   :city=>"Podor",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Podor, Senegal"},
 "PRI"=>
  {:iata=>"PRI",
   :name=>"Praslin Island Airport",
   :icao=>"",
   :city=>"Praslin Island",
   :country=>'Seychelles', :country_code=>'SC',
   :location=>"Praslin Island, Seychelles"},
 "PHW"=>
  {:iata=>"PHW",
   :name=>"Hendrik Van Eck Airport",
   :icao=>"FAPH",
   :city=>"Phalaborwa",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Phalaborwa, South Africa"},
 "PZB"=>
  {:iata=>"PZB",
   :name=>"Pietermaritzburg Airport",
   :icao=>"FAPM",
   :city=>"Pietermaritzburg",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Pietermaritzburg, South Africa"},
 "PBZ"=>
  {:iata=>"PBZ",
   :name=>"Plettenberg Bay Airport",
   :city=>"Plettenberg Bay",
   :icao=>"KPBZ",
   :country=>'Africa', :country_code=>'',
   :location=>"Plettenberg Bay, Africa"},
 "PTG"=>
  {:iata=>"PTG",
   :name=>"Polokwane International Airport",
   :icao=>"FAPP",
   :city=>"Polokwane",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Polokwane, South Africa"},
 "PLZ"=>
  {:iata=>"PLZ",
   :name=>"Port Elizabeth Airport",
   :icao=>"FAPE",
   :city=>"Port Elizabeth",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Port Elizabeth, South Africa"},
 "PZL"=>
  {:iata=>"PZL",
   :name=>"Zulu Inyala Airport",
   :city=>"Phinda",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Phinda, Africa"},
 "PRY"=>
  {:iata=>"PRY",
   :name=>"Wonderboom Airport",
   :icao=>"FAWB",
   :city=>"Pretoria",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Pretoria, South Africa"},
 "PRK"=>
  {:iata=>"PRK",
   :name=>"Prieska Airport",
   :city=>"Prieska",
   :icao=>"FAPK",
   :country=>'Africa', :country_code=>'',
   :location=>"Prieska, Africa"},
 "PZU"=>
  {:iata=>"PZU",
   :name=>"Port Sudan New International Airport",
   :icao=>"HSPN",
   :city=>"Port Sudan",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Port Sudan, Sudan"},
 "PFR"=>
  {:iata=>"PFR",
   :name=>"Ilebo Airport",
   :city=>"Ilebo",
   :icao=>"FZVS",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Ilebo, Congo"},
 "PUN"=>
  {:iata=>"PUN",
   :name=>"Punia Airport",
   :city=>"Punia",
   :icao=>"FZOP",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Punia, Congo"},
 "PWO"=>
  {:iata=>"PWO",
   :name=>"Pweto Airport",
   :city=>"Pweto",
   :icao=>"FZQC",
   :country=>'Congo', :country_code=>'CG',
   :location=>"Pweto, Congo"},
 "PAF"=>
  {:iata=>"PAF",
   :name=>"Pakuba Airport",
   :icao=>"HUPA",
   :city=>"Pakuba",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Pakuba, Uganda"},
 "PMA"=>
  {:iata=>"PMA",
   :name=>"Wawi Airport",
   :city=>"Pemba",
   :icao=>"HTPE",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Pemba, Tanzania"},
 "PDV"=>
  {:iata=>"PDV",
   :name=>"Plovdiv International Airport",
   :icao=>"LBPD",
   :city=>"Plovdiv",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Plovdiv, Bulgaria"},
 "PVN"=>
  {:iata=>"PVN",
   :name=>"Pleven Airport",
   :icao=>"",
   :city=>"Pleven",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Pleven, Bulgaria"},
 "PUY"=>
  {:iata=>"PUY",
   :name=>"Pula Airport",
   :icao=>"LDPL",
   :city=>"Pula",
   :country=>'Croatia', :country_code=>'HR',
   :location=>"Pula, Croatia"},
 "PFO"=>
  {:iata=>"PFO",
   :name=>"Paphos International Airport",
   :icao=>"LCPH",
   :city=>"Paphos",
   :country=>'Cyprus', :country_code=>'CY',
   :location=>"Paphos, Cyprus"},
 "PRG"=>
  {:iata=>"PRG",
   :name=>"Václav Havel Airport Prague",
   :icao=>"LKPR",
   :city=>"Prague",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Prague, Czech Republic"},
 "PED"=>
  {:iata=>"PED",
   :name=>"Pardubice Airport",
   :icao=>"LKPD",
   :city=>"Pardubice",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Pardubice, Czech Republic"},
 "PRV"=>
  {:iata=>"PRV",
   :name=>"Prerov Airport",
   :city=>"Prerov",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Prerov, Republic"},
 "POR"=>
  {:iata=>"POR",
   :name=>"Pori Airport",
   :icao=>"EFPO",
   :city=>"Pori",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Pori, Finland"},
 "PUF"=>
  {:iata=>"PUF",
   :name=>"Pau Pyrénées Airport",
   :icao=>"LFBP",
   :city=>"Pau",
   :country=>'France', :country_code=>'FR',
   :location=>"Pau, France"},
 "PGX"=>
  {:iata=>"PGX",
   :name=>"Périgueux Bassillac Airport",
   :icao=>"",
   :city=>"Périgueux",
   :country=>'France', :country_code=>'FR',
   :location=>"Périgueux, France"},
 "PGF"=>
  {:iata=>"PGF",
   :name=>"Perpignan – Rivesaltes Airport",
   :icao=>"LFMP",
   :city=>"Perpignan",
   :country=>'France', :country_code=>'FR',
   :location=>"Perpignan, France"},
 "PIS"=>
  {:iata=>"PIS",
   :name=>"Poitiers - Biard Airport",
   :icao=>"LFBI",
   :city=>"Poitiers",
   :country=>'France', :country_code=>'FR',
   :location=>"Poitiers, France"},
 "PAR"=>
  {:iata=>"PAR",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Paris",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris, France"},
 "POX"=>
  {:iata=>"POX",
   :name=>"Pontoise Airport",
   :icao=>"LFPT",
   :city=>"Paris",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris, France"},
 "PRP"=>
  {:iata=>"PRP",
   :name=>"Propriano Airport",
   :icao=>"LFKO",
   :city=>"Propriano",
   :country=>'France', :country_code=>'FR',
   :location=>"Propriano, France"},
 "PAD"=>
  {:iata=>"PAD",
   :name=>"Paderborn/Lippstadt Airport",
   :icao=>"EDLP",
   :city=>"Paderborn",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Paderborn, Germany"},
 "PHM"=>
  {:iata=>"PHM",
   :name=>"Boeblingen Airport",
   :city=>"Boeblingen",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Boeblingen, Germany"},
 "PEF"=>
  {:iata=>"PEF",
   :name=>"Peenemuende Airport",
   :city=>"Peenemuende",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Peenemuende, Germany"},
 "PSH"=>
  {:iata=>"PSH",
   :name=>"St. Peter Airport",
   :city=>"Saint Peter",
   :icao=>"EDXO",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Saint Peter, Germany"},
 "PAS"=>
  {:iata=>"PAS",
   :name=>"Paros National Airport",
   :icao=>"LGPA",
   :city=>"Paros",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Paros, Greece"},
 "PVK"=>
  {:iata=>"PVK",
   :name=>"Aktion Airport",
   :icao=>"LGPZ",
   :city=>"Preveza",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Preveza, Greece"},
 "PKH"=>
  {:iata=>"PKH",
   :name=>"Porto Cheli Airport",
   :icao=>"LGHL",
   :city=>"Porto Cheli",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Porto Cheli, Argolis, Greece"},
 "PYR"=>
  {:iata=>"PYR",
   :name=>"Andravida Airport",
   :city=>"Pyrgos",
   :icao=>"LGAD",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Pyrgos, Greece"},
 "PFJ"=>
  {:iata=>"PFJ",
   :name=>"Patreksfjörður Airport",
   :icao=>"BIPA",
   :city=>"Patreksfjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Patreksfjörður, Iceland"},
 "PMO"=>
  {:iata=>"PMO",
   :name=>"Palermo Airport (Falcone-Borsellino Airport)",
   :icao=>"LICJ",
   :city=>"Punta Raisi (near Palermo)",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Punta Raisi (near Palermo), Italy"},
 "PNL"=>
  {:iata=>"PNL",
   :name=>"Pantelleria Airport",
   :city=>"Pantelleria",
   :icao=>"LICG",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Pantelleria, Italy"},
 "PMF"=>
  {:iata=>"PMF",
   :name=>"Parma Airport (Parma \"Giuseppe Verdi\" Airport)",
   :icao=>"LIMP",
   :city=>"Parma",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Parma, Italy"},
 "PEG"=>
  {:iata=>"PEG",
   :name=>"San Egidio Airport",
   :icao=>"LIRZ",
   :city=>"Perugia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Perugia, Italy"},
 "PSR"=>
  {:iata=>"PSR",
   :name=>"Pescara Airport",
   :icao=>"LIBP",
   :city=>"Pescara",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Pescara, Italy"},
 "PSA"=>
  {:iata=>"PSA",
   :name=>"Galileo Galilei Airport",
   :icao=>"LIRP",
   :city=>"Pisa",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Pisa, Italy"},
 "PRJ"=>
  {:iata=>"PRJ",
   :name=>"Capri Airport",
   :city=>"Capri",
   :icao=>"",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Capri, Italy"},
 "PEJ"=>
  {:iata=>"PEJ",
   :name=>"Peschiei Airport",
   :city=>"Peschiei",
   :icao=>"",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Peschiei, Italy"},
 "PLQ"=>
  {:iata=>"PLQ",
   :name=>"Palanga International Airport",
   :icao=>"EYPA",
   :city=>"Palanga",
   :country=>'Lithuania', :country_code=>'LT',
   :location=>"Palanga, Lithuania"},
 "PNV"=>
  {:iata=>"PNV",
   :name=>"Panevezys Airport",
   :city=>"Panevezys",
   :icao=>"",
   :country=>'Lithuania', :country_code=>'LT',
   :location=>"Panevezys, Lithuania"},
 "POZ"=>
  {:iata=>"POZ",
   :name=>"Poznań-Ławica Airport",
   :icao=>"EPPO",
   :city=>"Poznań",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Poznań, Poland"},
 "PIX"=>
  {:iata=>"PIX",
   :name=>"Pico Airport",
   :icao=>"LPPI",
   :city=>"Pico Island",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Pico Island, Azores, Portugal"},
 "PDL"=>
  {:iata=>"PDL",
   :name=>"João Paulo II Airport (Ponta Delgada Airport)",
   :icao=>"LPPD",
   :city=>"Ponta Delgada",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Ponta Delgada, Azores, Portugal"},
 "PXO"=>
  {:iata=>"PXO",
   :name=>"Porto Santo Airport",
   :icao=>"LPPS",
   :city=>"Porto Santo",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Porto Santo, Madeira, Portugal"},
 "PRM"=>
  {:iata=>"PRM",
   :name=>"Portimão Airport",
   :icao=>"LPPM",
   :city=>"Portimão",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Portimão, Algarve, Portugal"},
 "PRN"=>
  {:iata=>"PRN",
   :name=>"Pristina International Airport Adem Jashari",
   :icao=>"BKPR",
   :city=>"Pristina",
   :country=>'Kosovo', :country_code=>'',
   :location=>"Pristina, Kosovo"},
 "PEX"=>
  {:iata=>"PEX",
   :name=>"Pechora Airport",
   :icao=>"UUYP",
   :city=>"Pechora",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Pechora, Komi Republic, Russia"},
 "PEZ"=>
  {:iata=>"PEZ",
   :name=>"Penza Airport",
   :icao=>"UWPP",
   :city=>"Penza",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Penza, Russia"},
 "PEE"=>
  {:iata=>"PEE",
   :name=>"Bolshoye Savino Airport",
   :icao=>"USPP",
   :city=>"Perm",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Perm, Russia"},
 "PKC"=>
  {:iata=>"PKC",
   :name=>"Yelizovo Airport",
   :icao=>"UHPP",
   :city=>"Petropavlovsk-Kamchatsky",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Petropavlovsk-Kamchatsky, Russia"},
 "PES"=>
  {:iata=>"PES",
   :name=>"Besovets Airport",
   :icao=>"ULPB",
   :city=>"Petrozavodsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Petrozavodsk, Russia"},
 "PWE"=>
  {:iata=>"PWE",
   :name=>"Pevek Airport",
   :icao=>"UHMP",
   :city=>"Pevek",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Pevek, Russia"},
 "PYJ"=>
  {:iata=>"PYJ",
   :name=>"Polyarny Airport",
   :icao=>"UERP",
   :city=>"Polyarny",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Polyarny, Yakutia, Russia"},
 "PKV"=>
  {:iata=>"PKV",
   :name=>"Pskov Airport",
   :icao=>"ULOO",
   :city=>"Pskov",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Pskov, Russia"},
 "PVS"=>
  {:iata=>"PVS",
   :name=>"Provideniya Bay Airport",
   :icao=>"UHMD",
   :city=>"Provideniya",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Provideniya, Chukotka, Russia"},
 "PZY"=>
  {:iata=>"PZY",
   :name=>"Pieštany Airport",
   :icao=>"LZPP",
   :city=>"Piešťany",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Piešťany, Slovakia"},
 "POV"=>
  {:iata=>"POV",
   :name=>"Presov Airport",
   :city=>"Presov",
   :icao=>"LZPW",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Presov, Slovakia"},
 "POW"=>
  {:iata=>"POW",
   :name=>"Portorož Airport",
   :icao=>"LJPZ",
   :city=>"Portorož",
   :country=>'Slovenia', :country_code=>'SI',
   :location=>"Portorož, Slovenia"},
 "PMI"=>
  {:iata=>"PMI",
   :name=>"Palma de Mallorca Airport (Son Sant Joan Airport)",
   :icao=>"LEPA",
   :city=>"Palma de Mallorca",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Palma de Mallorca, Spain"},
 "PNA"=>
  {:iata=>"PNA",
   :name=>"Pamplona Airport",
   :icao=>"LEPP",
   :city=>"Pamplona",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Pamplona, Spain"},
 "PXS"=>
  {:iata=>"PXS",
   :name=>"Puerto De Santa Maria Airport",
   :city=>"Puerto De Santa Maria",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Puerto De Santa Maria, Islands"},
 "PJA"=>
  {:iata=>"PJA",
   :name=>"Pajala Airport",
   :city=>"Pajala",
   :icao=>"ESUP",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Pajala, Sweden"},
 "PLV"=>
  {:iata=>"PLV",
   :name=>"Poltava Airport",
   :city=>"Poltava",
   :icao=>"UKHP",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Poltava, Ukraine"},
 "PIK"=>
  {:iata=>"PIK",
   :name=>"Glasgow Prestwick International Airport",
   :icao=>"EGPK",
   :city=>"Prestwick (near Glasgow)",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Prestwick (near Glasgow), Scotland, United Kingdom"},
 "PPW"=>
  {:iata=>"PPW",
   :name=>"Papa Westray Airport",
   :city=>"Papa Westray",
   :icao=>"EGEP",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Papa Westray, Kingdom"},
 "PZE"=>
  {:iata=>"PZE",
   :name=>"Penzance Heliport",
   :city=>"Penzance",
   :icao=>"EGHK",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Penzance, Kingdom"},
 "PLH"=>
  {:iata=>"PLH",
   :name=>"Plymouth City Airport (closed 2011)",
   :icao=>"EGHD",
   :city=>"Plymouth",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Plymouth, United Kingdom"},
 "PSV"=>
  {:iata=>"PSV",
   :name=>"Papa Stour Airport",
   :city=>"Papa Stour",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Papa Stour, Kingdom"},
 "PSL"=>
  {:iata=>"PSL",
   :name=>"Perth Airport",
   :icao=>"EGPT",
   :city=>"Perth",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Perth, Scotland, United Kingdom"},
 "PME"=>
  {:iata=>"PME",
   :name=>"Portsmouth Airport",
   :city=>"Portsmouth",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Portsmouth, Kingdom"},
 "PBH"=>
  {:iata=>"PBH",
   :name=>"Paro Airport",
   :icao=>"VQPR",
   :city=>"Paro",
   :country=>'Bhutan', :country_code=>'BT',
   :location=>"Paro, Bhutan"},
 "PNH"=>
  {:iata=>"PNH",
   :name=>"Phnom Penh International Airport",
   :icao=>"VDPP",
   :city=>"Phnom Penh",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Phnom Penh, Cambodia"},
 "PAI"=>
  {:iata=>"PAI",
   :name=>"Pailin Airport",
   :city=>"Pailin",
   :icao=>"",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Pailin, Cambodia"},
 "PEK"=>
  {:iata=>"PEK",
   :name=>"Beijing Capital International Airport",
   :icao=>"ZBAA",
   :city=>"Beijing",
   :country=>"People's Republic of China", :country_code=>'',
   :location=>"Beijing, People's Republic of China"},
 "PVG"=>
  {:iata=>"PVG",
   :name=>"Shanghai Pudong International Airport",
   :icao=>"ZSPD",
   :city=>"Shanghai",
   :country=>"People's Republic of China", :country_code=>'',
   :location=>"Shanghai, People's Republic of China"},
 "PZI"=>
  {:iata=>"PZI",
   :name=>"Pan Zhi Hua Bao An Ying",
   :city=>"Pan Zhi Hua",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Pan Zhi Hua, China"},
 "PNJ"=>
  {:iata=>"PNJ",
   :name=>"Sha He Kou Airport",
   :city=>"Peng Lai",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Peng Lai, China"},
 "PGH"=>
  {:iata=>"PGH",
   :name=>"Pantnagar Airport",
   :city=>"Pantnagar",
   :icao=>"VIPT",
   :country=>"India",
:country_code=>"IN",
   :location=>"Pantnagar, India"},
 "PAT"=>
  {:iata=>"PAT",
   :name=>"Lok Nayak Jayaprakash Airport (Patna Airport)",
   :icao=>"VEPT",
   :city=>"Patna",
   :country=>"India",
:country_code=>"IN",
   :location=>"Patna, India"},
 "PNY"=>
  {:iata=>"PNY",
   :name=>"Pondicherry Airport",
   :icao=>"VOTY",
   :city=>"Puducherry",
   :country=>"India",
:country_code=>"IN",
   :location=>"Puducherry, India"},
 "PBD"=>
  {:iata=>"PBD",
   :name=>"Porbandar Airport",
   :city=>"Porbandar",
   :icao=>"VAPR",
   :country=>"India",
:country_code=>"IN",
   :location=>"Porbandar, India"},
 "PNQ"=>
  {:iata=>"PNQ",
   :name=>"Pune International Airport",
   :icao=>"VAPO",
   :city=>"Pune",
   :country=>"India",
:country_code=>"IN",
   :location=>"Pune, India"},
 "PAB"=>
  {:iata=>"PAB",
   :name=>"Bilaspur Airport",
   :icao=>"VABI",
   :city=>"Bilaspur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Bilaspur, Chhattisgarh, India"},
 "PYB"=>
  {:iata=>"PYB",
   :name=>"Jeypore Airport",
   :city=>"Jeypore",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jeypore, India"},
 "PUT"=>
  {:iata=>"PUT",
   :name=>"Puttaprathi Airport",
   :city=>"Puttaparthi",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Puttaparthi, India"},
 "PDG"=>
  {:iata=>"PDG",
   :name=>"Minangkabau International Airport",
   :icao=>"WIPT",
   :city=>"Ketaping",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ketaping, West Sumatra, Indonesia"},
 "PKY"=>
  {:iata=>"PKY",
   :name=>"Palangkaraya Airport",
   :city=>"Palangkaraya",
   :icao=>"WRBP",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Palangkaraya, Indonesia"},
 "PLM"=>
  {:iata=>"PLM",
   :name=>"Sultan Mahmud Badaruddin II Airport",
   :icao=>"WIPP",
   :city=>"Palembang",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Palembang, Sumatra, Indonesia"},
 "PLW"=>
  {:iata=>"PLW",
   :name=>"Mutiara Airport",
   :city=>"Palu",
   :icao=>"WAML",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Palu, Indonesia"},
 "PKN"=>
  {:iata=>"PKN",
   :name=>"Pangkalanbuun Airport",
   :city=>"Pangkalanbuun",
   :icao=>"WRBI",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pangkalanbuun, Indonesia"},
 "PGK"=>
  {:iata=>"PGK",
   :name=>"Pangkalpinang Airport",
   :city=>"Pangkalpinang",
   :icao=>"WIKK",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pangkalpinang, Indonesia"},
 "PKU"=>
  {:iata=>"PKU",
   :name=>"Sultan Syarif Kasim II Airport",
   :icao=>"WIBB",
   :city=>"Pekanbaru",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pekanbaru, Sumatra, Indonesia"},
 "PUM"=>
  {:iata=>"PUM",
   :name=>"Pomala Airport",
   :city=>"Pomala",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pomala, Indonesia"},
 "PNK"=>
  {:iata=>"PNK",
   :name=>"Supadio Airport",
   :icao=>"WIOO",
   :city=>"Pontianak",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pontianak, Kalimantan, Indonesia"},
 "PSU"=>
  {:iata=>"PSU",
   :name=>"Putussibau Airport",
   :city=>"Putussibau",
   :icao=>"WIOP",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Putussibau, Indonesia"},
 "PPR"=>
  {:iata=>"PPR",
   :name=>"Pasir Pangarayan Airport",
   :city=>"Pasir Pangarayan",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pasir Pangarayan, Indonesia"},
 "PDO"=>
  {:iata=>"PDO",
   :name=>"Pendopo Airport",
   :city=>"Pendopo",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pendopo, Indonesia"},
 "PCB"=>
  {:iata=>"PCB",
   :name=>"Pondok Cabe Airport",
   :city=>"Pondok Cabe",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pondok Cabe, Indonesia"},
 "PSJ"=>
  {:iata=>"PSJ",
   :name=>"Kasiguncu Airport",
   :city=>"Poso",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Poso, Indonesia"},
 "PPJ"=>
  {:iata=>"PPJ",
   :name=>"Pulau Panjang Airport",
   :city=>"Pulau Panjang",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Pulau Panjang, Indonesia"},
 "PWL"=>
  {:iata=>"PWL",
   :name=>"Purwokerto Airport",
   :icao=>"",
   :city=>"Wirasaba",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Wirasaba, Central Java, Indonesia"},
 "PGU"=>
  {:iata=>"PGU",
   :name=>"Ala'Marvdasht Airport",
   :city=>"Ala'Marvdasht",
   :icao=>"OIBP",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Ala'Marvdasht, Iran"},
 "PFQ"=>
  {:iata=>"PFQ",
   :name=>"Parsabad Moghan Airport",
   :city=>"Parsabad",
   :icao=>"OITP",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Parsabad, Iran"},
 "PWQ"=>
  {:iata=>"PWQ",
   :name=>"Pavlodar Airport",
   :icao=>"UASP",
   :city=>"Pavlodar",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Pavlodar, Kazakhstan"},
 "PPK"=>
  {:iata=>"PPK",
   :name=>"Petropavlovsk Airport",
   :icao=>"UACP",
   :city=>"Petropavl",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Petropavl, Kazakhstan"},
 "PLX"=>
  {:iata=>"PLX",
   :name=>"Semey Airport",
   :icao=>"UASS",
   :city=>"Semey",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Semey, Kazakhstan"},
 "PKZ"=>
  {:iata=>"PKZ",
   :name=>"Pakse Airport",
   :city=>"Pakse",
   :icao=>"VLPS",
   :country=>'Republic', :country_code=>'',
   :location=>"Pakse, Republic"},
 "PKS"=>
  {:iata=>"PKS",
   :name=>"Paksane Airport",
   :city=>"Paksane",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Paksane, Republic"},
 "PCQ"=>
  {:iata=>"PCQ",
   :name=>"Bounneua Airport",
   :city=>"Phongsaly",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Phongsaly, Republic"},
 "PEN"=>
  {:iata=>"PEN",
   :name=>"Penang International Airport",
   :icao=>"WMKP",
   :city=>"Penang",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Penang, Malaysia"},
 "PKG"=>
  {:iata=>"PKG",
   :name=>"Pangkor Airport",
   :city=>"Pangkor Island",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Pangkor Island, Malaysia"},
 "PAY"=>
  {:iata=>"PAY",
   :name=>"Pamol Airport",
   :city=>"Pamol",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Pamol, Malaysia"},
 "PKK"=>
  {:iata=>"PKK",
   :name=>"Pakokku Airport",
   :city=>"Pakokku",
   :icao=>"VYPU",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Pakokku, Myanmar"},
 "PBU"=>
  {:iata=>"PBU",
   :name=>"Putao Airport",
   :city=>"Putao",
   :icao=>"VYPT",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Putao, Myanmar"},
 "PAA"=>
  {:iata=>"PAA",
   :name=>"Pa-an Airport",
   :city=>"Pa-an",
   :icao=>"VYPA",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Pa-an, Myanmar"},
 "PPU"=>
  {:iata=>"PPU",
   :name=>"Papun Airport",
   :city=>"Papun",
   :icao=>"VYPP",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Papun, Myanmar"},
 "PAU"=>
  {:iata=>"PAU",
   :name=>"Pauk Airport",
   :city=>"Pauk",
   :icao=>"VYPK",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Pauk, Myanmar"},
 "PRU"=>
  {:iata=>"PRU",
   :name=>"Prome Airport",
   :city=>"Prome",
   :icao=>"VYPY",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Prome, Myanmar"},
 "PPL"=>
  {:iata=>"PPL",
   :name=>"Phaplu Airport",
   :icao=>"VNPL",
   :city=>"Phaplu",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Phaplu, Nepal"},
 "PKR"=>
  {:iata=>"PKR",
   :name=>"Pokhara Airport",
   :icao=>"VNPK",
   :city=>"Pokhara",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Pokhara, Nepal"},
 "PJG"=>
  {:iata=>"PJG",
   :name=>"Panjgur Airport",
   :icao=>"OPPG",
   :city=>"Panjgur",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Panjgur, Pakistan"},
 "PEW"=>
  {:iata=>"PEW",
   :name=>"Peshawar Airport",
   :icao=>"OPPS",
   :city=>"Peshawar",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Peshawar, Pakistan"},
 "PZH"=>
  {:iata=>"PZH",
   :name=>"Zhob Airport",
   :icao=>"OPZB",
   :city=>"Zhob",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Zhob, Pakistan"},
 "PAJ"=>
  {:iata=>"PAJ",
   :name=>"Para Chinar Airport",
   :city=>"Para Chinar",
   :icao=>"OPPC",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Para Chinar, Pakistan"},
 "PSI"=>
  {:iata=>"PSI",
   :name=>"Pasni Airport",
   :city=>"Pasni",
   :icao=>"OPPI",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Pasni, Pakistan"},
 "PNP"=>
  {:iata=>"PNP",
   :name=>"Girua Airport",
   :city=>"Popondetta",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Popondetta, Guinea"},
 "POM"=>
  {:iata=>"POM",
   :name=>"Jacksons International Airport (Port Moresby Airport)",
   :icao=>"AYPY",
   :city=>"Port Moresby",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Port Moresby, Papua New Guinea"},
 "PLE"=>
  {:iata=>"PLE",
   :name=>"Paiela Airport",
   :icao=>"",
   :city=>"Paiela",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Paiela, Papua New Guinea"},
 "PAW"=>
  {:iata=>"PAW",
   :name=>"Pambwa Airport",
   :city=>"Pambwa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Pambwa, Guinea"},
 "PGB"=>
  {:iata=>"PGB",
   :name=>"Panaoa Airport",
   :city=>"Panaoa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Panaoa, Guinea"},
 "PGN"=>
  {:iata=>"PGN",
   :name=>"Pangia Airport",
   :city=>"Pangia",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Pangia, Guinea"},
 "PPX"=>
  {:iata=>"PPX",
   :name=>"Param Airport",
   :city=>"Param",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Param, Guinea"},
 "PMP"=>
  {:iata=>"PMP",
   :name=>"Pimaga Airport",
   :icao=>"",
   :city=>"Pimaga",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Pimaga, Papua New Guinea"},
 "PDI"=>
  {:iata=>"PDI",
   :name=>"Pindiu Airport",
   :city=>"Pindiu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Pindiu, Guinea"},
 "PUA"=>
  {:iata=>"PUA",
   :name=>"Puas Airport",
   :city=>"Puas",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Puas, Guinea"},
 "PMN"=>
  {:iata=>"PMN",
   :name=>"Pumani Airport",
   :city=>"Pumani",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Pumani, Guinea"},
 "PUI"=>
  {:iata=>"PUI",
   :name=>"Purini Airport",
   :icao=>"",
   :city=>"Purini",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Purini, Papua New Guinea"},
 "PGE"=>
  {:iata=>"PGE",
   :name=>"Yegepa Airport",
   :icao=>"",
   :city=>"Yegepa",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Yegepa, Papua New Guinea"},
 "PAG"=>
  {:iata=>"PAG",
   :name=>"Pagadian Airport",
   :icao=>"RPMP",
   :city=>"Pagadian City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Pagadian City, Zamboanga del Sur, Philippines"},
 "PPS"=>
  {:iata=>"PPS",
   :name=>"Puerto Princesa Airport",
   :icao=>"RPVP",
   :city=>"Puerto Princesa City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Puerto Princesa City, Philippines"},
 "PIF"=>
  {:iata=>"PIF",
   :name=>"Pingtung Airport",
   :city=>"Pingtung",
   :icao=>"RCDC",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Pingtung, Taiwan"},
 "PUS"=>
  {:iata=>"PUS",
   :name=>"Gimhae International Airport",
   :icao=>"RKPK",
   :city=>"Busan",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Busan, South Korea"},
 "PYY"=>
  {:iata=>"PYY",
   :name=>"Pai Airport",
   :icao=>"",
   :city=>"Pai",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Pai, Thailand"},
 "PHS"=>
  {:iata=>"PHS",
   :name=>"Phitsanulok Airport",
   :city=>"Phitsanulok",
   :icao=>"VTPP",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phitsanulok, Thailand"},
 "PRH"=>
  {:iata=>"PRH",
   :name=>"Phrae Airport",
   :icao=>"VTCP",
   :city=>"Phrae",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phrae, Thailand"},
 "PBS"=>
  {:iata=>"PBS",
   :name=>"Patong Beach Airport",
   :city=>"Patong Beach",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Patong Beach, Thailand"},
 "PAN"=>
  {:iata=>"PAN",
   :name=>"Pattani Airport",
   :icao=>"VTSK",
   :city=>"Pattani",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Pattani, Thailand"},
 "PYX"=>
  {:iata=>"PYX",
   :name=>"Pattaya Airport",
   :city=>"Pattaya",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Pattaya, Thailand"},
 "PMM"=>
  {:iata=>"PMM",
   :name=>"Phanom Sarakham Airport",
   :city=>"Phanom Sarakham",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phanom Sarakham, Thailand"},
 "PHY"=>
  {:iata=>"PHY",
   :name=>"Phetchabun Airport",
   :icao=>"VTPB",
   :city=>"Phetchabun",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phetchabun, Thailand"},
 "PHZ"=>
  {:iata=>"PHZ",
   :name=>"Phi Phi Island Airport",
   :city=>"Phi Phi Island",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phi Phi Island, Thailand"},
 "PXR"=>
  {:iata=>"PXR",
   :name=>"Surin Airport",
   :city=>"Surin",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Surin, Thailand"},
 "PQC"=>
  {:iata=>"PQC",
   :name=>"Duong Dang Airport",
   :city=>"Phu Quoc",
   :icao=>"VVPQ",
   :country=>'Nam', :country_code=>'',
   :location=>"Phu Quoc, Nam"},
 "PXU"=>
  {:iata=>"PXU",
   :name=>"Pleiku Airport",
   :city=>"Pleiku",
   :icao=>"VVPK",
   :country=>'Nam', :country_code=>'',
   :location=>"Pleiku, Nam"},
 "PHA"=>
  {:iata=>"PHA",
   :name=>"Phan Rang Airport",
   :city=>"Phan Rang",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Phan Rang, Nam"},
 "PHH"=>
  {:iata=>"PHH",
   :name=>"Phan Thiet Airport",
   :city=>"Phan Thiet",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Phan Thiet, Nam"},
 "PHU"=>
  {:iata=>"PHU",
   :name=>"Phu Vinh Airport",
   :city=>"Phu Vinh",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Phu Vinh, Nam"},
 "PLJ"=>
  {:iata=>"PLJ",
   :name=>"Placencia Airport",
   :icao=>"",
   :city=>"Placencia",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Placencia, Belize"},
 "PND"=>
  {:iata=>"PND",
   :name=>"Punta Gorda Airport",
   :city=>"Punta Gorda",
   :icao=>"",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Punta Gorda, Belize"},
 "PMZ"=>
  {:iata=>"PMZ",
   :name=>"Palmar Sur Airport",
   :icao=>"MRPM",
   :city=>"Palmar Sur",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Palmar Sur, Costa Rica"},
 "PLD"=>
  {:iata=>"PLD",
   :name=>"Playa Samara Airport",
   :city=>"Playa Samara",
   :icao=>"",
   :country=>'Rica', :country_code=>'',
   :location=>"Playa Samara, Rica"},
 "PJM"=>
  {:iata=>"PJM",
   :name=>"Puerto Jimenez Airport",
   :icao=>"MRPJ",
   :city=>"Puerto Jimenez",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Puerto Jimenez, Costa Rica"},
 "PBP"=>
  {:iata=>"PBP",
   :name=>"Punta Islita Airport",
   :icao=>"MRIA",
   :city=>"Punta Islita",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Punta Islita, Costa Rica"},
 "PCG"=>
  {:iata=>"PCG",
   :name=>"Paso Caballos Airport",
   :city=>"Paso Caballos",
   :icao=>"",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Paso Caballos, Guatemala"},
 "PKJ"=>
  {:iata=>"PKJ",
   :name=>"Playa Grande Airport",
   :city=>"Playa Grande",
   :icao=>"",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Playa Grande, Guatemala"},
 "PON"=>
  {:iata=>"PON",
   :name=>"Poptun Airport",
   :city=>"Poptun",
   :icao=>"MGPP",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Poptun, Guatemala"},
 "PBR"=>
  {:iata=>"PBR",
   :name=>"Puerto Barrios Airport",
   :city=>"Puerto Barrios",
   :icao=>"MGPB",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Puerto Barrios, Guatemala"},
 "PEU"=>
  {:iata=>"PEU",
   :name=>"Puerto Lempira Airport",
   :city=>"Puerto Lempira",
   :icao=>"MHPL",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Puerto Lempira, Honduras"},
 "PCH"=>
  {:iata=>"PCH",
   :name=>"Palacios Airport",
   :city=>"Palacios",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Palacios, Honduras"},
 "PUZ"=>
  {:iata=>"PUZ",
   :name=>"Puerto Cabezas Airport",
   :icao=>"MNPC",
   :city=>"Puerto Cabezas",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"Puerto Cabezas, Nicaragua"},
 "PTY"=>
  {:iata=>"PTY",
   :name=>"Tocumen International Airport",
   :icao=>"MPTO",
   :city=>"Panama City",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Panama City, Panama"},
 "PVE"=>
  {:iata=>"PVE",
   :name=>"El Porvenir Airport",
   :city=>"El Porvenir",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"El Porvenir, Panama"},
 "PLP"=>
  {:iata=>"PLP",
   :name=>"La Palma Airport",
   :city=>"La Palma",
   :icao=>"MPLP",
   :country=>'Panama', :country_code=>'PA',
   :location=>"La Palma, Panama"},
 "PAC"=>
  {:iata=>"PAC",
   :name=>"Albrook \"Marcos A. Gelabert\" International Airport",
   :icao=>"MPMG",
   :city=>"Panama City",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Panama City, Panama"},
 "PDM"=>
  {:iata=>"PDM",
   :name=>"Capt.  Justiniano Montenegro Airport",
   :city=>"Pedasi",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Pedasi, Panama"},
 "PYC"=>
  {:iata=>"PYC",
   :name=>"Playón Chico Airport",
   :icao=>"",
   :city=>"Ukupseni",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Ukupseni, Guna Yala, Panama"},
 "PUE"=>
  {:iata=>"PUE",
   :name=>"Puerto Obaldia Airport",
   :city=>"Puerto Obaldia",
   :icao=>"MPOA",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Puerto Obaldia, Panama"},
 "PYV"=>
  {:iata=>"PYV",
   :name=>"Yaviza Airport",
   :city=>"Yaviza",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Yaviza, Panama"},
 "PSD"=>
  {:iata=>"PSD",
   :name=>"Port Said Airport",
   :city=>"Port Said",
   :icao=>"HEPS",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Port Said, Egypt"},
 "PMS"=>
  {:iata=>"PMS",
   :name=>"Palmyra Airport",
   :icao=>"OSPR",
   :city=>"Palmyra",
   :country=>'Syria', :country_code=>'SY',
   :location=>"Palmyra, Syria"},
 "PAE"=>
  {:iata=>"PAE",
   :name=>"Snohomish County Airport (Paine Field)",
   :icao=>"KPAE",
   :city=>"Everett",
   :country=>'United States', :country_code=>'US',

   :location=>"Everett, Washington, United States"},
 "PAH"=>
  {:iata=>"PAH",
   :name=>"Barkley Regional Airport",
   :icao=>"KPAH",
   :city=>"Paducah",
   :country=>'United States', :country_code=>'US',

   :location=>"Paducah, Kentucky, United States"},
 "PAK"=>
  {:iata=>"PAK",
   :name=>"Port Allen Airport",
   :icao=>"",
   :city=>"Hanapepe",
   :country=>'United States', :country_code=>'US',

   :location=>"Hanapepe, Hawaii, United States"},
 "PAM"=>
  {:iata=>"PAM",
   :name=>"Tyndall Air Force Base",
   :icao=>"KPAM",
   :city=>"Panama City",
   :country=>'United States', :country_code=>'US',

   :location=>"Panama City, Florida, United States"},
 "PAO"=>
  {:iata=>"PAO",
   :name=>"Palo Alto Airport",
   :icao=>"KPAO",
   :city=>"Palo Alto",
   :country=>'United States', :country_code=>'US',

   :location=>"Palo Alto, California, United States"},
 "PAQ"=>
  {:iata=>"PAQ",
   :name=>"Palmer Municipal Airport",
   :icao=>"PAAQ",
   :city=>"Palmer",
   :country=>'United States', :country_code=>'US',

   :location=>"Palmer, Alaska, United States"},
 "PBF"=>
  {:iata=>"PBF",
   :name=>"Grider Field",
   :icao=>"KPBF",
   :city=>"Pine Bluff",
   :country=>'United States', :country_code=>'US',

   :location=>"Pine Bluff, Arkansas, United States"},
 "PBG"=>
  {:iata=>"PBG",
   :name=>"Plattsburgh International Airport",
   :icao=>"KPBG",
   :city=>"Plattsburgh",
   :country=>'United States', :country_code=>'US',

   :location=>"Plattsburgh, New York, United States"},
 "PBI"=>
  {:iata=>"PBI",
   :name=>"Palm Beach International Airport",
   :icao=>"KPBI",
   :city=>"West Palm Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"West Palm Beach, Florida, United States"},
 "PCA"=>
  {:iata=>"PCA",
   :name=>"Portage Creek Airport (FAA: A14)",
   :icao=>"PAOC",
   :city=>"Portage Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Portage Creek, Alaska, United States"},
 "PCD"=>
  {:iata=>"PCD",
   :name=>"Prairie du Chien Municipal Airport (FAA: PDC)",
   :icao=>"KPDC",
   :city=>"Prairie du Chien",
   :country=>'United States', :country_code=>'US',

   :location=>"Prairie du Chien, Wisconsin, United States"},
 "PCK"=>
  {:iata=>"PCK",
   :name=>"Porcupine Creek Airport",
   :icao=>"",
   :city=>"Porcupine Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Porcupine Creek, Alaska, United States"},
 "PCT"=>
  {:iata=>"PCT",
   :name=>"Princeton Airport (FAA: 39N)",
   :icao=>"",
   :city=>"Princeton/Rocky Hill",
   :country=>'United States', :country_code=>'US',

   :location=>"Princeton/Rocky Hill, New Jersey, United States"},
 "PDB"=>
  {:iata=>"PDB",
   :name=>"Pedro Bay Airport (FAA: 4K0)",
   :icao=>"",
   :city=>"Pedro Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Pedro Bay, Alaska, United States"},
 "PDK"=>
  {:iata=>"PDK",
   :name=>"DeKalb-Peachtree Airport",
   :icao=>"KPDK",
   :city=>"Atlanta",
   :country=>'United States', :country_code=>'US',

   :location=>"Atlanta, Georgia, United States"},
 "PDT"=>
  {:iata=>"PDT",
   :name=>"Eastern Oregon Regional Airport",
   :icao=>"KPDT",
   :city=>"Pendleton",
   :country=>'United States', :country_code=>'US',

   :location=>"Pendleton, Oregon, United States"},
 "PDX"=>
  {:iata=>"PDX",
   :name=>"Portland International Airport",
   :icao=>"KPDX",
   :city=>"Portland",
   :country=>'United States', :country_code=>'US',

   :location=>"Portland, Oregon, United States"},
 "PEQ"=>
  {:iata=>"PEQ",
   :name=>"Pecos Municipal Airport",
   :icao=>"KPEQ",
   :city=>"Pecos",
   :country=>'United States', :country_code=>'US',

   :location=>"Pecos, Texas, United States"},
 "PFC"=>
  {:iata=>"PFC",
   :name=>"Pacific City State Airport",
   :icao=>"KPFC",
   :city=>"Pacific City",
   :country=>'United States', :country_code=>'US',

   :location=>"Pacific City, Oregon, United States"},
 "PFN"=>
  {:iata=>"PFN",
   :name=>"Panama City-Bay County International Airport",
   :icao=>"KPFN",
   :city=>"Panama City",
   :country=>'United States', :country_code=>'US',

   :location=>"Panama City, Florida, United States"},
 "PGA"=>
  {:iata=>"PGA",
   :name=>"Page Municipal Airport",
   :icao=>"KPGA",
   :city=>"Page",
   :country=>'United States', :country_code=>'US',

   :location=>"Page, Arizona, United States"},
 "PGC"=>
  {:iata=>"PGC",
   :name=>"Grant County Airport (FAA: W99)",
   :icao=>"",
   :city=>"Petersburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Petersburg, West Virginia, United States"},
 "PGD"=>
  {:iata=>"PGD",
   :name=>"Punta Gorda Airport (formerly Charlotte County Airport)",
   :icao=>"KPGD",
   :city=>"Punta Gorda",
   :country=>'United States', :country_code=>'US',

   :location=>"Punta Gorda, Florida, United States"},
 "PGL"=>
  {:iata=>"PGL",
   :name=>"Trent Lott International Airport (FAA: PQL)",
   :icao=>"KPQL",
   :city=>"Pascagoula",
   :country=>'United States', :country_code=>'US',

   :location=>"Pascagoula, Mississippi, United States"},
 "PGM"=>
  {:iata=>"PGM",
   :name=>"Port Graham Airport",
   :icao=>"",
   :city=>"Port Graham",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Graham, Alaska, United States"},
 "PGO"=>
  {:iata=>"PGO",
   :name=>"Stevens Field (FAA: PSO)",
   :icao=>"KPSO",
   :city=>"Pagosa Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Pagosa Springs, Colorado, United States"},
 "PGR"=>
  {:iata=>"PGR",
   :name=>"Kirk Field",
   :icao=>"KPGR",
   :city=>"Paragould",
   :country=>'United States', :country_code=>'US',

   :location=>"Paragould, Arkansas, United States"},
 "PGS"=>
  {:iata=>"PGS",
   :name=>"Grand Canyon Caverns Airport (FAA: L37)",
   :icao=>"",
   :city=>"Peach Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Peach Springs, Arizona, United States"},
 "PGV"=>
  {:iata=>"PGV",
   :name=>"Pitt-Greenville Airport",
   :icao=>"KPGV",
   :city=>"Greenville",
   :country=>'United States', :country_code=>'US',

   :location=>"Greenville, North Carolina, United States"},
 "PHD"=>
  {:iata=>"PHD",
   :name=>"Harry Clever Field",
   :icao=>"KPHD",
   :city=>"New Philadelphia",
   :country=>'United States', :country_code=>'US',

   :location=>"New Philadelphia, Ohio, United States"},
 "PHF"=>
  {:iata=>"PHF",
   :name=>"Newport News/Williamsburg International Airport",
   :icao=>"KPHF",
   :city=>"Newport News",
   :country=>'United States', :country_code=>'US',

   :location=>"Newport News, Virginia, United States"},
 "PHK"=>
  {:iata=>"PHK",
   :name=>"Palm Beach County Glades Airport",
   :icao=>"KPHK",
   :city=>"Pahokee",
   :country=>'United States', :country_code=>'US',

   :location=>"Pahokee, Florida, United States"},
 "PHL"=>
  {:iata=>"PHL",
   :name=>"Philadelphia International Airport",
   :icao=>"KPHL",
   :city=>"Philadelphia",
   :country=>'United States', :country_code=>'US',

   :location=>"Philadelphia, Pennsylvania, United States"},
 "PHN"=>
  {:iata=>"PHN",
   :name=>"St. Clair County International Airport",
   :icao=>"KPHN",
   :city=>"Port Huron",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Huron, Michigan, United States"},
 "PHO"=>
  {:iata=>"PHO",
   :name=>"Point Hope Airport",
   :icao=>"PAPO",
   :city=>"Point Hope",
   :country=>'United States', :country_code=>'US',

   :location=>"Point Hope, Alaska, United States"},
 "PHP"=>
  {:iata=>"PHP",
   :name=>"Philip Airport",
   :icao=>"KPHP",
   :city=>"Philip",
   :country=>'United States', :country_code=>'US',

   :location=>"Philip, South Dakota, United States"},
 "PHT"=>
  {:iata=>"PHT",
   :name=>"Henry County Airport",
   :icao=>"KPHT",
   :city=>"Paris",
   :country=>'United States', :country_code=>'US',

   :location=>"Paris, Tennessee, United States"},
 "PHX"=>
  {:iata=>"PHX",
   :name=>"Phoenix Sky Harbor International Airport",
   :icao=>"KPHX",
   :city=>"Phoenix",
   :country=>'United States', :country_code=>'US',

   :location=>"Phoenix, Arizona, United States"},
 "PIA"=>
  {:iata=>"PIA",
   :name=>"Greater Peoria Regional Airport",
   :icao=>"KPIA",
   :city=>"Peoria",
   :country=>'United States', :country_code=>'US',

   :location=>"Peoria, Illinois, United States"},
 "PIB"=>
  {:iata=>"PIB",
   :name=>"Hattiesburg-Laurel Regional Airport",
   :icao=>"KPIB",
   :city=>"Hattiesburg/Laurel",
   :country=>'United States', :country_code=>'US',

   :location=>"Hattiesburg/Laurel, Mississippi, United States"},
 "PIE"=>
  {:iata=>"PIE",
   :name=>"St. Petersburg-Clearwater International Airport",
   :icao=>"KPIE",
   :city=>"Pinellas County",
   :country=>'United States', :country_code=>'US',

   :location=>
    "Pinellas County, Florida (near St. Petersburg and Clearwater), United States"},
 "PIH"=>
  {:iata=>"PIH",
   :name=>"Pocatello Regional Airport",
   :icao=>"KPIH",
   :city=>"Pocatello",
   :country=>'United States', :country_code=>'US',

   :location=>"Pocatello, Idaho, United States"},
 "PIM"=>
  {:iata=>"PIM",
   :name=>"Callaway Gardens-Harris County Airport",
   :icao=>"KPIM",
   :city=>"Pine Mountain",
   :country=>'United States', :country_code=>'US',

   :location=>"Pine Mountain, Georgia, United States"},
 "PIP"=>
  {:iata=>"PIP",
   :name=>"Pilot Point Airport (FAA: PNP)",
   :icao=>"PAPN",
   :city=>"Pilot Point",
   :country=>'United States', :country_code=>'US',

   :location=>"Pilot Point, Alaska, United States"},
 "PIR"=>
  {:iata=>"PIR",
   :name=>"Pierre Regional Airport",
   :icao=>"KPIR",
   :city=>"Pierre",
   :country=>'United States', :country_code=>'US',

   :location=>"Pierre, South Dakota, United States"},
 "PIT"=>
  {:iata=>"PIT",
   :name=>"Pittsburgh International Airport",
   :icao=>"KPIT",
   :city=>"Findlay (near Pittsburgh)",
   :country=>'United States', :country_code=>'US',

   :location=>"Findlay (near Pittsburgh), Pennsylvania, United States"},
 "PIZ"=>
  {:iata=>"PIZ",
   :name=>"Point Lay LRRS Airport",
   :icao=>"PPIZ",
   :city=>"Point Lay",
   :country=>'United States', :country_code=>'US',

   :location=>"Point Lay, Alaska, United States"},
 "PJB"=>
  {:iata=>"PJB",
   :name=>"Payson Airport (FAA: PAN)",
   :icao=>"KPAN",
   :city=>"Payson",
   :country=>'United States', :country_code=>'US',

   :location=>"Payson, Arizona, United States"},
 "PKA"=>
  {:iata=>"PKA",
   :name=>"Napaskiak Airport",
   :icao=>"PAPK",
   :city=>"Napaskiak",
   :country=>'United States', :country_code=>'US',

   :location=>"Napaskiak, Alaska, United States"},
 "PKB"=>
  {:iata=>"PKB",
   :name=>"Mid-Ohio Valley Regional Airport",
   :icao=>"KPKB",
   :city=>"Parkersburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Parkersburg, West Virginia, United States"},
 "PKD"=>
  {:iata=>"PKD",
   :name=>"Park Rapids Municipal Airport (Konshok Field)",
   :icao=>"KPKD",
   :city=>"Park Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Park Rapids, Minnesota, United States"},
 "PKF"=>
  {:iata=>"PKF",
   :name=>"Park Falls Municipal Airport",
   :icao=>"KPKF",
   :city=>"Park Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Park Falls, Wisconsin, United States"},
 "PLB"=>
  {:iata=>"PLB",
   :name=>"Clinton County Airport (closed)",
   :icao=>"KPLB",
   :city=>"Plattsburgh",
   :country=>'United States', :country_code=>'US',

   :location=>"Plattsburgh, New York, United States"},
 "PLK"=>
  {:iata=>"PLK",
   :name=>"M. Graham Clark Downtown Airport",
   :icao=>"KPLK",
   :city=>"Point Lookout",
   :country=>'United States', :country_code=>'US',

   :location=>"Point Lookout, Missouri, United States"},
 "PLN"=>
  {:iata=>"PLN",
   :name=>"Pellston Regional Airport",
   :icao=>"KPLN",
   :city=>"Pellston",
   :country=>'United States', :country_code=>'US',

   :location=>"Pellston, Michigan, United States"},
 "PLR"=>
  {:iata=>"PLR",
   :name=>"St. Clair County Airport",
   :icao=>"KPLR",
   :city=>"Pell City",
   :country=>'United States', :country_code=>'US',

   :location=>"Pell City, Alabama, United States"},
 "PLY"=>
  {:iata=>"PLY",
   :name=>"Plymouth Municipal Airport (FAA: C65)",
   :icao=>"",
   :city=>"Plymouth",
   :country=>'United States', :country_code=>'US',

   :location=>"Plymouth, Indiana, United States"},
 "PMB"=>
  {:iata=>"PMB",
   :name=>"Pembina Municipal Airport",
   :icao=>"KPMB",
   :city=>"Pembina",
   :country=>'United States', :country_code=>'US',

   :location=>"Pembina, North Dakota, United States"},
 "PMD"=>
  {:iata=>"PMD",
   :name=>"LA/Palmdale Regional Airport",
   :icao=>"KPMD",
   :city=>"Palmdale",
   :country=>'United States', :country_code=>'US',

   :location=>"Palmdale, California, United States"},
 "PMH"=>
  {:iata=>"PMH",
   :name=>"Greater Portsmouth Regional Airport",
   :icao=>"KPMH",
   :city=>"Portsmouth",
   :country=>'United States', :country_code=>'US',

   :location=>"Portsmouth, Ohio, United States"},
 "PML"=>
  {:iata=>"PML",
   :name=>"Port Moller Airport (FAA: 1AK3)",
   :icao=>"PAAL",
   :city=>"Cold Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Cold Bay, Alaska, United States"},
 "PNC"=>
  {:iata=>"PNC",
   :name=>"Ponca City Regional Airport",
   :icao=>"KPNC",
   :city=>"Ponca City",
   :country=>'United States', :country_code=>'US',

   :location=>"Ponca City, Oklahoma, United States"},
 "PNE"=>
  {:iata=>"PNE",
   :name=>"Northeast Philadelphia Airport",
   :icao=>"KPNE",
   :city=>"Philadelphia",
   :country=>'United States', :country_code=>'US',

   :location=>"Philadelphia, Pennsylvania, United States"},
 "PNN"=>
  {:iata=>"PNN",
   :name=>"Princeton Municipal Airport",
   :icao=>"KPNN",
   :city=>"Princeton",
   :country=>'United States', :country_code=>'US',

   :location=>"Princeton, Maine, United States"},
 "PNS"=>
  {:iata=>"PNS",
   :name=>"Pensacola International Airport",
   :icao=>"KPNS",
   :city=>"Pensacola",
   :country=>'United States', :country_code=>'US',

   :location=>"Pensacola, Florida, United States"},
 "PNU"=>
  {:iata=>"PNU",
   :name=>"Panguitch Municipal Airport (FAA: U55)",
   :icao=>"",
   :city=>"Panguitch",
   :country=>'United States', :country_code=>'US',

   :location=>"Panguitch, Utah, United States"},
 "PNX"=>
  {:iata=>"PNX",
   :name=>"North Texas Regional Airport (FAA: GYI)",
   :icao=>"KGYI",
   :city=>"Sherman/Denison",
   :country=>'United States', :country_code=>'US',

   :location=>"Sherman/Denison, Texas, United States"},
 "POB"=>
  {:iata=>"POB",
   :name=>"Pope Air Force Base",
   :icao=>"KPOB",
   :city=>"Fayetteville",
   :country=>'United States', :country_code=>'US',

   :location=>"Fayetteville, North Carolina, United States"},
 "POC"=>
  {:iata=>"POC",
   :name=>"Brackett Field",
   :icao=>"KPOC",
   :city=>"La Verne",
   :country=>'United States', :country_code=>'US',

   :location=>"La Verne, California, United States"},
 "POE"=>
  {:iata=>"POE",
   :name=>"Polk Army Airfield",
   :icao=>"KPOE",
   :city=>"Fort Polk",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Polk, Louisiana, United States"},
 "POF"=>
  {:iata=>"POF",
   :name=>"Poplar Bluff Municipal Airport",
   :icao=>"KPOF",
   :city=>"Poplar Bluff",
   :country=>'United States', :country_code=>'US',

   :location=>"Poplar Bluff, Missouri, United States"},
 "POH"=>
  {:iata=>"POH",
   :name=>"Pocahontas Municipal Airport",
   :icao=>"KPOH",
   :city=>"Pocahontas",
   :country=>'United States', :country_code=>'US',

   :location=>"Pocahontas, Iowa, United States"},
 "POU"=>
  {:iata=>"POU",
   :name=>"Dutchess County Airport",
   :icao=>"KPOU",
   :city=>"Poughkeepsie",
   :country=>'United States', :country_code=>'US',

   :location=>"Poughkeepsie, New York, United States"},
 "PPA"=>
  {:iata=>"PPA",
   :name=>"Perry Lefors Field",
   :icao=>"KPPA",
   :city=>"Pampa",
   :country=>'United States', :country_code=>'US',

   :location=>"Pampa, Texas, United States"},
 "PPC"=>
  {:iata=>"PPC",
   :name=>"Prospect Creek Airport",
   :icao=>"PAPR",
   :city=>"Prospect Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Prospect Creek, Alaska, United States"},
 "PPF"=>
  {:iata=>"PPF",
   :name=>"Tri-City Airport",
   :icao=>"KPPF",
   :city=>"Parsons",
   :country=>'United States', :country_code=>'US',

   :location=>"Parsons, Kansas, United States"},
 "PPM"=>
  {:iata=>"PPM",
   :name=>"Pompano Beach Airpark (FAA: PMP)",
   :icao=>"KPMP",
   :city=>"Pompano Beach",
   :country=>'United States', :country_code=>'US',

   :location=>"Pompano Beach, Florida, United States"},
 "PPV"=>
  {:iata=>"PPV",
   :name=>"Port Protection Seaplane Base (FAA: 19P)",
   :icao=>"",
   :city=>"Port Protection",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Protection, Alaska, United States"},
 "PQI"=>
  {:iata=>"PQI",
   :name=>"Northern Maine Regional Airport at Presque Isle",
   :icao=>"KPQI",
   :city=>"Presque Isle",
   :country=>'United States', :country_code=>'US',

   :location=>"Presque Isle, Maine, United States"},
 "PQS"=>
  {:iata=>"PQS",
   :name=>"Pilot Station Airport (FAA: 0AK)",
   :icao=>"",
   :city=>"Pilot Station",
   :country=>'United States', :country_code=>'US',

   :location=>"Pilot Station, Alaska, United States"},
 "PRB"=>
  {:iata=>"PRB",
   :name=>"Paso Robles Municipal Airport",
   :icao=>"KPRB",
   :city=>"Paso Robles",
   :country=>'United States', :country_code=>'US',

   :location=>"Paso Robles, California, United States"},
 "PRC"=>
  {:iata=>"PRC",
   :name=>"Ernest A. Love Field",
   :icao=>"KPRC",
   :city=>"Prescott",
   :country=>'United States', :country_code=>'US',

   :location=>"Prescott, Arizona, United States"},
 "PRO"=>
  {:iata=>"PRO",
   :name=>"Perry Municipal Airport",
   :icao=>"KPRO",
   :city=>"Perry",
   :country=>'United States', :country_code=>'US',

   :location=>"Perry, Iowa, United States"},
 "PRW"=>
  {:iata=>"PRW",
   :name=>"Prentice Airport (FAA: 5N2)",
   :icao=>"",
   :city=>"Prentice",
   :country=>'United States', :country_code=>'US',

   :location=>"Prentice, Wisconsin, United States"},
 "PRX"=>
  {:iata=>"PRX",
   :name=>"Cox Field",
   :icao=>"KPRX",
   :city=>"Paris",
   :country=>'United States', :country_code=>'US',

   :location=>"Paris, Texas, United States"},
 "PRZ"=>
  {:iata=>"PRZ",
   :name=>"Prineville Airport (FAA: S39)",
   :icao=>"",
   :city=>"Prineville",
   :country=>'United States', :country_code=>'US',

   :location=>"Prineville, Oregon, United States"},
 "PSB"=>
  {:iata=>"PSB",
   :name=>"Mid-State Airport",
   :icao=>"KPSB",
   :city=>"Philipsburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Philipsburg, Pennsylvania, United States"},
 "PSC"=>
  {:iata=>"PSC",
   :name=>"Tri-Cities Airport",
   :icao=>"KPSC",
   :city=>"Pasco",
   :country=>'United States', :country_code=>'US',

   :location=>"Pasco, Washington, United States"},
 "PSF"=>
  {:iata=>"PSF",
   :name=>"Pittsfield Municipal Airport",
   :icao=>"KPSF",
   :city=>"Pittsfield",
   :country=>'United States', :country_code=>'US',

   :location=>"Pittsfield, Massachusetts, United States"},
 "PSG"=>
  {:iata=>"PSG",
   :name=>"Petersburg James A. Johnson Airport",
   :icao=>"PAPG",
   :city=>"Petersburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Petersburg, Alaska, United States"},
 "PSK"=>
  {:iata=>"PSK",
   :name=>"New River Valley Airport",
   :icao=>"KPSK",
   :city=>"Dublin",
   :country=>'United States', :country_code=>'US',

   :location=>"Dublin, Virginia, United States"},
 "PSM"=>
  {:iata=>"PSM",
   :name=>"Pease International Tradeport",
   :icao=>"KPSM",
   :city=>"Portsmouth",
   :country=>'United States', :country_code=>'US',

   :location=>"Portsmouth, New Hampshire, United States"},
 "PSN"=>
  {:iata=>"PSN",
   :name=>"Palestine Municipal Airport",
   :icao=>"KPSN",
   :city=>"Palestine",
   :country=>'United States', :country_code=>'US',

   :location=>"Palestine, Texas, United States"},
 "PSP"=>
  {:iata=>"PSP",
   :name=>"Palm Springs International Airport",
   :icao=>"KPSP",
   :city=>"Palm Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Palm Springs, California, United States"},
 "PSQ"=>
  {:iata=>"PSQ",
   :name=>"Philadelphia Seaplane Base (FAA: 9N2)",
   :icao=>"",
   :city=>"Essington",
   :country=>'United States', :country_code=>'US',

   :location=>"Essington, Pennsylvania, United States"},
 "PSX"=>
  {:iata=>"PSX",
   :name=>"Palacios Municipal Airport",
   :icao=>"KPSX",
   :city=>"Palacios",
   :country=>'United States', :country_code=>'US',

   :location=>"Palacios, Texas, United States"},
 "PTA"=>
  {:iata=>"PTA",
   :name=>"Port Alsworth Airport (FAA: TPO)",
   :icao=>"PALJ",
   :city=>"Port Alsworth",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Alsworth, Alaska, United States"},
 "PTB"=>
  {:iata=>"PTB",
   :name=>"Dinwiddie County Airport",
   :icao=>"KPTB",
   :city=>"Petersburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Petersburg, Virginia, United States"},
 "PTC"=>
  {:iata=>"PTC",
   :name=>"Port Alice Seaplane Base (FAA: 16K)",
   :icao=>"",
   :city=>"Port Alice",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Alice, Alaska, United States"},
 "PTD"=>
  {:iata=>"PTD",
   :name=>"Port Alexander Seaplane Base (FAA: AHP)",
   :icao=>"PAAP",
   :city=>"Port Alexander",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Alexander, Alaska, United States"},
 "PTH"=>
  {:iata=>"PTH",
   :name=>"Port Heiden Airport",
   :icao=>"PAPH",
   :city=>"Port Heiden",
   :country=>'United States', :country_code=>'US',

   :location=>"Port Heiden, Alaska, United States"},
 "PTK"=>
  {:iata=>"PTK",
   :name=>"Oakland County International Airport",
   :icao=>"KPTK",
   :city=>"Waterford",
   :country=>'United States', :country_code=>'US',

   :location=>"Waterford, Michigan, United States"},
 "PTN"=>
  {:iata=>"PTN",
   :name=>"Harry P. Williams Memorial Airport",
   :icao=>"KPTN",
   :city=>"Patterson",
   :country=>'United States', :country_code=>'US',

   :location=>"Patterson, Louisiana, United States"},
 "PTR"=>
  {:iata=>"PTR",
   :name=>"Pleasant Harbour Airport",
   :icao=>"",
   :city=>"Uganik Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Uganik Island, United States"},
 "PTS"=>
  {:iata=>"PTS",
   :name=>"Atkinson Municipal Airport",
   :icao=>"KPTS",
   :city=>"Pittsburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Pittsburg, Kansas, United States"},
 "PTT"=>
  {:iata=>"PTT",
   :name=>"Pratt Industrial Airport",
   :icao=>"KPTT",
   :city=>"Pratt",
   :country=>'United States', :country_code=>'US',

   :location=>"Pratt, Kansas, United States"},
 "PTU"=>
  {:iata=>"PTU",
   :name=>"Platinum Airport",
   :icao=>"PAPM",
   :city=>"Platinum",
   :country=>'United States', :country_code=>'US',

   :location=>"Platinum, Alaska, United States"},
 "PTV"=>
  {:iata=>"PTV",
   :name=>"Porterville Municipal Airport",
   :icao=>"KPTV",
   :city=>"Porterville",
   :country=>'United States', :country_code=>'US',

   :location=>"Porterville, California, United States"},
 "PTW"=>
  {:iata=>"PTW",
   :name=>"Pottstown Limerick Airport",
   :icao=>"KPTW",
   :city=>"Pottstown",
   :country=>'United States', :country_code=>'US',

   :location=>"Pottstown, Pennsylvania, United States"},
 "PUB"=>
  {:iata=>"PUB",
   :name=>"Pueblo Memorial Airport",
   :icao=>"KPUB",
   :city=>"Pueblo",
   :country=>'United States', :country_code=>'US',

   :location=>"Pueblo, Colorado, United States"},
 "PUC"=>
  {:iata=>"PUC",
   :name=>"Carbon County Airport",
   :icao=>"KPUC",
   :city=>"Price",
   :country=>'United States', :country_code=>'US',

   :location=>"Price, Utah, United States"},
 "PUL"=>
  {:iata=>"PUL",
   :name=>"Port of Poulsbo Marina Moorage Seaplane Base (FAA: 83Q)",
   :icao=>"",
   :city=>"Poulsbo",
   :country=>'United States', :country_code=>'US',

   :location=>"Poulsbo, Washington, United States"},
 "PUO"=>
  {:iata=>"PUO",
   :name=>"Northstar Heliport (FAA: 90AK)",
   :icao=>"",
   :city=>"Prudhoe Bay/Deadhorse",
   :country=>'United States', :country_code=>'US',

   :location=>"Prudhoe Bay/Deadhorse, Alaska, United States"},
 "PUW"=>
  {:iata=>"PUW",
   :name=>"Pullman-Moscow Regional Airport",
   :icao=>"KPUW",
   :city=>"Pullman",
   :country=>'United States', :country_code=>'US',

   :location=>"Pullman, Washington (near Moscow, Idaho), United States"},
 "PVC"=>
  {:iata=>"PVC",
   :name=>"Provincetown Municipal Airport",
   :icao=>"KPVC",
   :city=>"Provincetown",
   :country=>'United States', :country_code=>'US',

   :location=>"Provincetown, Massachusetts, United States"},
 "PVD"=>
  {:iata=>"PVD",
   :name=>"Theodore Francis Green State Airport",
   :icao=>"KPVD",
   :city=>"Providence",
   :country=>'United States', :country_code=>'US',

   :location=>"Providence, Rhode Island, United States"},
 "PVF"=>
  {:iata=>"PVF",
   :name=>"Placerville Airport",
   :icao=>"KPVF",
   :city=>"Placerville",
   :country=>'United States', :country_code=>'US',

   :location=>"Placerville, California, United States"},
 "PVU"=>
  {:iata=>"PVU",
   :name=>"Provo Municipal Airport",
   :icao=>"KPVU",
   :city=>"Provo",
   :country=>'United States', :country_code=>'US',

   :location=>"Provo, Utah, United States"},
 "PVW"=>
  {:iata=>"PVW",
   :name=>"Hale County Airport",
   :icao=>"KPVW",
   :city=>"Plainview",
   :country=>'United States', :country_code=>'US',

   :location=>"Plainview, Texas, United States"},
 "PWA"=>
  {:iata=>"PWA",
   :name=>"Wiley Post Airport",
   :icao=>"KPWA",
   :city=>"Oklahoma City",
   :country=>'United States', :country_code=>'US',

   :location=>"Oklahoma City, Oklahoma, United States"},
 "PWD"=>
  {:iata=>"PWD",
   :name=>"Sher-Wood Airport",
   :icao=>"KPWD",
   :city=>"Plentywood",
   :country=>'United States', :country_code=>'US',

   :location=>"Plentywood, Montana, United States"},
 "PWK"=>
  {:iata=>"PWK",
   :name=>"Palwaukee Municipal Airport",
   :icao=>"KPWK",
   :city=>"Chicago/Prospect Heights/Wheeling",
   :country=>'United States', :country_code=>'US',

   :location=>"Chicago/Prospect Heights/Wheeling, Illinois, United States"},
 "PWM"=>
  {:iata=>"PWM",
   :name=>"Portland International Jetport",
   :icao=>"KPWM",
   :city=>"Portland",
   :country=>'United States', :country_code=>'US',

   :location=>"Portland, Maine, United States"},
 "PWT"=>
  {:iata=>"PWT",
   :name=>"Bremerton National Airport",
   :icao=>"KPWT",
   :city=>"Bremerton",
   :country=>'United States', :country_code=>'US',

   :location=>"Bremerton, Washington, United States"},
 "PWY"=>
  {:iata=>"PWY",
   :name=>"Ralph Wenz Field",
   :icao=>"KPNA",
   :city=>"Pinedale",
   :country=>'United States', :country_code=>'US',

   :location=>"Pinedale, Wyoming, United States"},
 "PXL"=>
  {:iata=>"PXL",
   :name=>"Polacca Airport (FAA: P10)",
   :icao=>"",
   :city=>"Polacca",
   :country=>'United States', :country_code=>'US',

   :location=>"Polacca, Arizona, United States"},
 "PYM"=>
  {:iata=>"PYM",
   :name=>"Plymouth Municipal Airport",
   :icao=>"KPYM",
   :city=>"Plymouth",
   :country=>'United States', :country_code=>'US',

   :location=>"Plymouth, Massachusetts, United States"}}

end
