# encoding: UTF-8
def airp_24
  {"WNN"=>
  {:iata=>"WNN",
   :name=>"Wunnummin Lake Airport",
   :city=>"Wunnummin Lake",
   :icao=>"CKL3",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Wunnummin Lake, Canada"},
 "WPC"=>
  {:iata=>"WPC",
   :name=>"Pincher Creek Airport",
   :icao=>"CZPC",
   :city=>"Pincher Creek",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Pincher Creek, Alberta, Canada"},
 "WPL"=>
  {:iata=>"WPL",
   :name=>"Powell Lake Airport",
   :city=>"Powell Lake",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Powell Lake, Canada"},
 "WRL"=>
  {:iata=>"WRL",
   :name=>"Worland Municipal Airport",
   :icao=>"KWRL",
   :city=>"Worland",
   :country=>'United States', :country_code=>'US',

   :location=>"Worland, Wyoming, United States"},
 "WAP"=>
  {:iata=>"WAP",
   :name=>"Alto Palena Airport",
   :city=>"Alto Palena",
   :icao=>"",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Alto Palena, Chile"},
 "WCA"=>
  {:iata=>"WCA",
   :name=>"Gamboa Airport",
   :icao=>"SCST",
   :city=>"Castro",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Castro, Chile"},
 "WCH"=>
  {:iata=>"WCH",
   :name=>"Chaitén Airport",
   :icao=>"SCTN",
   :city=>"Chaitén",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Chaitén, Los Lagos, Chile"},
 "WPR"=>
  {:iata=>"WPR",
   :name=>"Porvenir Airport",
   :city=>"Porvenir",
   :icao=>"SCFM",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Porvenir, Chile"},
 "WPA"=>
  {:iata=>"WPA",
   :name=>"Puerto Aisén Airport",
   :icao=>"SCAS",
   :city=>"Puerto Aisén",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Puerto Aisén, Chile"},
 "WPU"=>
  {:iata=>"WPU",
   :name=>"Puerto Williams Airport",
   :city=>"Puerto Williams",
   :icao=>"SCGZ",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Puerto Williams, Chile"},
 "WGL"=>
  {:iata=>"WGL",
   :name=>"Off-Line Point",
   :city=>"Isle Balta",
   :icao=>"",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Isle Balta, Ecuador"},
 "WSO"=>
  {:iata=>"WSO",
   :name=>"Washabo Airport",
   :icao=>"",
   :city=>"Washabo",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Washabo, Suriname"},
 "WOK"=>
  {:iata=>"WOK",
   :name=>"Wonken Airport",
   :city=>"Wonken",
   :icao=>"",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Wonken, Venezuela"},
 "WLE"=>
  {:iata=>"WLE",
   :name=>"Miles Airport",
   :icao=>"",
   :city=>"Miles",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Miles, Queensland, Australia"},
 "WGA"=>
  {:iata=>"WGA",
   :name=>"Wagga Wagga Airport",
   :icao=>"YSWG",
   :city=>"Wagga Wagga",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wagga Wagga, New South Wales, Australia"},
 "WEI"=>
  {:iata=>"WEI",
   :name=>"Weipa Airport",
   :icao=>"YBWP",
   :city=>"Weipa",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Weipa, Queensland, Australia"},
 "WLP"=>
  {:iata=>"WLP",
   :name=>"West Angelas Airport",
   :city=>"West Angelas",
   :icao=>"YANG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"West Angelas, Australia"},
 "WYA"=>
  {:iata=>"WYA",
   :name=>"Whyalla Airport",
   :city=>"Whyalla",
   :icao=>"YWHA",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Whyalla, Australia"},
 "WRN"=>
  {:iata=>"WRN",
   :name=>"Windarling Airport",
   :icao=>"",
   :city=>"Windarling",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Windarling, Australia"},
 "WNR"=>
  {:iata=>"WNR",
   :name=>"Windorah Airport",
   :city=>"Windorah",
   :icao=>"YWDH",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Windorah, Australia"},
 "WIN"=>
  {:iata=>"WIN",
   :name=>"Winton Airport",
   :city=>"Winton",
   :icao=>"YWTN",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Winton, Australia"},
 "WSY"=>
  {:iata=>"WSY",
   :name=>"Whitsunday Airport",
   :icao=>"YWHI",
   :city=>"Airlie Beach",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Airlie Beach, Australia"},
 "WME"=>
  {:iata=>"WME",
   :name=>"Mount Keith Airport",
   :icao=>"YMNE",
   :city=>"Mount Keith",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mount Keith, Western Australia, Australia"},
 "WUI"=>
  {:iata=>"WUI",
   :name=>"Murrin Murrin Airport",
   :icao=>"",
   :city=>"Murrin Murrin Joint Venture",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Murrin Murrin Joint Venture, Western Australia, Australia"},
 "WLC"=>
  {:iata=>"WLC",
   :name=>"Walcha Airport",
   :city=>"Walcha",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Walcha, Australia"},
 "WGE"=>
  {:iata=>"WGE",
   :name=>"Walgett Airport",
   :city=>"Walgett",
   :icao=>"YWLG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Walgett, Australia"},
 "WLA"=>
  {:iata=>"WLA",
   :name=>"Wallal Downs Airport",
   :city=>"Wallal Downs",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wallal Downs, Australia"},
 "WGT"=>
  {:iata=>"WGT",
   :name=>"Wangaratta Airport",
   :city=>"Wangaratta",
   :icao=>"YWGT",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wangaratta, Australia"},
 "WKB"=>
  {:iata=>"WKB",
   :name=>"Warracknabeal Airport",
   :city=>"Warracknabeal",
   :icao=>"YWKB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Warracknabeal, Australia"},
 "WRW"=>
  {:iata=>"WRW",
   :name=>"All airports in Warsaw",
   :icao=>"",
   :city=>"Warsaw",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Warsaw, Poland"},
 "WMB"=>
  {:iata=>"WMB",
   :name=>"Warrnambool Airport",
   :icao=>"YWBL",
   :city=>"Warrnambool",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Warrnambool, Victoria, Australia"},
 "WAZ"=>
  {:iata=>"WAZ",
   :name=>"Warwick Airport",
   :city=>"Warwick",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Warwick, Australia"},
 "WLO"=>
  {:iata=>"WLO",
   :name=>"Waterloo Airport",
   :icao=>"YWTL",
   :city=>"Waterloo",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Waterloo, Northern Territory, Australia"},
 "WAU"=>
  {:iata=>"WAU",
   :name=>"Wauchope Airport",
   :city=>"Wauchope",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wauchope, Australia"},
 "WAV"=>
  {:iata=>"WAV",
   :name=>"Kalkgurung Airport",
   :city=>"Wave Hill",
   :icao=>"YWAV",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wave Hill, Australia"},
 "WAN"=>
  {:iata=>"WAN",
   :name=>"Waverney Airport",
   :city=>"Waverney",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Waverney, Australia"},
 "WEW"=>
  {:iata=>"WEW",
   :name=>"Wee Waa Airport",
   :city=>"Wee Waa",
   :icao=>"YWWA",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wee Waa, Australia"},
 "WHL"=>
  {:iata=>"WHL",
   :name=>"Welshpool Airport",
   :city=>"Welshpool",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Welshpool, Australia"},
 "WWY"=>
  {:iata=>"WWY",
   :name=>"West Wyalong Airport",
   :icao=>"YWWL",
   :city=>"West Wyalong",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"West Wyalong, New South Wales, Australia"},
 "WIO"=>
  {:iata=>"WIO",
   :name=>"Wilcannia Airport",
   :city=>"Wilcannia",
   :icao=>"YWCA",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wilcannia, Australia"},
 "WUN"=>
  {:iata=>"WUN",
   :name=>"Wiluna Airport",
   :city=>"Wiluna",
   :icao=>"YWLU",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wiluna, Australia"},
 "WND"=>
  {:iata=>"WND",
   :name=>"Windarra Airport",
   :city=>"Windarra",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Windarra, Australia"},
 "WIT"=>
  {:iata=>"WIT",
   :name=>"Wittenoom Airport",
   :city=>"Wittenoom",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wittenoom, Australia"},
 "WLL"=>
  {:iata=>"WLL",
   :name=>"Wollogorang Airport",
   :icao=>"YWOR",
   :city=>"Wollogorang Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wollogorang Station, Northern Territory, Australia"},
 "WOL"=>
  {:iata=>"WOL",
   :name=>"Illawarra Regional Airport (Wollongong Airport)",
   :icao=>"YWOL",
   :city=>"Shellharbour",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Shellharbour, Wollongong, New South Wales, Australia"},
 "WDI"=>
  {:iata=>"WDI",
   :name=>"Wondai Airport",
   :city=>"Wondai",
   :icao=>"YWND",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wondai, Australia"},
 "WON"=>
  {:iata=>"WON",
   :name=>"Wondoola Airport",
   :city=>"Wondoola",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wondoola, Australia"},
 "WOG"=>
  {:iata=>"WOG",
   :name=>"Woodgreen Airport",
   :city=>"Woodgreen",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Woodgreen, Australia"},
 "WWI"=>
  {:iata=>"WWI",
   :name=>"Woodie Woodie Airport",
   :city=>"Woodie Woodie",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Woodie Woodie, Australia"},
 "WPK"=>
  {:iata=>"WPK",
   :name=>"Wrotham Park Airport",
   :city=>"Wrotham Park",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wrotham Park, Australia"},
 "WUD"=>
  {:iata=>"WUD",
   :name=>"Wudinna Airport",
   :city=>"Wudinna",
   :icao=>"YWUD",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wudinna, Australia"},
 "WYN"=>
  {:iata=>"WYN",
   :name=>"Wyndham Airport",
   :city=>"Wyndham",
   :icao=>"YWYM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Wyndham, Australia"},
 "WJA"=>
  {:iata=>"WJA",
   :name=>"Woja Airport",
   :icao=>"",
   :city=>"Woja",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Woja, Marshall Islands"},
 "WTO"=>
  {:iata=>"WTO",
   :name=>"Wotho Airport",
   :icao=>"",
   :city=>"Wotho",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Wotho, Marshall Islands"},
 "WTE"=>
  {:iata=>"WTE",
   :name=>"Wotje Airport (FAA: N36)",
   :icao=>"",
   :city=>"Wotje (Wotje Atoll)",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Wotje (Wotje Atoll), Marshall Islands"},
 "WLG"=>
  {:iata=>"WLG",
   :name=>"Wellington International Airport",
   :icao=>"NZWN",
   :city=>"Wellington",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Wellington, New Zealand"},
 "WKA"=>
  {:iata=>"WKA",
   :name=>"Wanaka Airport",
   :icao=>"NZWF",
   :city=>"Wanaka",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Wanaka, New Zealand"},
 "WAG"=>
  {:iata=>"WAG",
   :name=>"Wanganui Airport",
   :icao=>"NZWU",
   :city=>"Wanganui",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Wanganui, New Zealand"},
 "WSZ"=>
  {:iata=>"WSZ",
   :name=>"Westport Airport",
   :icao=>"NZWS",
   :city=>"Westport",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Westport, New Zealand"},
 "WHK"=>
  {:iata=>"WHK",
   :name=>"Whakatane Airport",
   :icao=>"NZWK",
   :city=>"Whakatane",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Whakatane, New Zealand"},
 "WRE"=>
  {:iata=>"WRE",
   :name=>"Whangarei Airport",
   :icao=>"NZWR",
   :city=>"Whangarei",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Whangarei, New Zealand"},
 "WHO"=>
  {:iata=>"WHO",
   :name=>"Franz Josef Airport",
   :city=>"Franz Josef",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Franz Josef, Zealand"},
 "WIK"=>
  {:iata=>"WIK",
   :name=>"Waiheke Reeve Airport",
   :city=>"Surfdale",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Surfdale, Zealand"},
 "WIR"=>
  {:iata=>"WIR",
   :name=>"Wairoa Airport",
   :city=>"Wairoa",
   :icao=>"NZWO",
   :country=>'Zealand', :country_code=>'',
   :location=>"Wairoa, Zealand"},
 "WGN"=>
  {:iata=>"WGN",
   :name=>"Waitangi Airport",
   :city=>"Waitangi",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Waitangi, Zealand"},
 "WTZ"=>
  {:iata=>"WTZ",
   :name=>"Whitianga Airport",
   :city=>"Whitianga",
   :icao=>"",
   :country=>'Zealand', :country_code=>'',
   :location=>"Whitianga, Zealand"},
 "WLH"=>
  {:iata=>"WLH",
   :name=>"Walaha Airport",
   :city=>"Walaha",
   :icao=>"NVSW",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Walaha, Vanuatu"},
 "WLS"=>
  {:iata=>"WLS",
   :name=>"Wallis Island",
   :icao=>"NLWW",
   :city=>"Wallis and Futuna Islands",
   :country=>'Wallis and Futuna Islands', :country_code=>'WF',
   :location=>"Wallis and Futuna Islands"},
 "WZY"=>
  {:iata=>"WZY",
   :name=>"Paradise Island-Seaplane Base",
   :city=>"Nassau",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Nassau, Bahamas"},
 "WKR"=>
  {:iata=>"WKR",
   :name=>"Walkers Cay Airport",
   :city=>"Walkers Cay",
   :icao=>"",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Walkers Cay, Bahamas"},
 "WTD"=>
  {:iata=>"WTD",
   :name=>"West End Airport",
   :icao=>"MYGW",
   :city=>"Grand Bahama",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Grand Bahama, Bahamas"},
 "WAC"=>
  {:iata=>"WAC",
   :name=>"Waca Airport",
   :city=>"Waca",
   :icao=>"HAWC",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Waca, Ethiopia"},
 "WRA"=>
  {:iata=>"WRA",
   :name=>"Warder Airport",
   :city=>"Warder",
   :icao=>"",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Warder, Ethiopia"},
 "WGY"=>
  {:iata=>"WGY",
   :name=>"Wagny Airport",
   :city=>"Wagny",
   :icao=>"",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Wagny, Gabon"},
 "WNE"=>
  {:iata=>"WNE",
   :name=>"Wora Na Ye Airport",
   :city=>"Wora Na Ye",
   :icao=>"",
   :country=>'Ghana', :country_code=>'GH',
   :location=>"Wora Na Ye, Ghana"},
 "WIL"=>
  {:iata=>"WIL",
   :name=>"Wilson Airport",
   :icao=>"HKNW",
   :city=>"Nairobi",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Nairobi, Kenya"},
 "WJR"=>
  {:iata=>"WJR",
   :name=>"Wajir Airport",
   :city=>"Wajir",
   :icao=>"HKWJ",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Wajir, Kenya"},
 "WES"=>
  {:iata=>"WES",
   :name=>"Weasua Airport",
   :city=>"Weasua",
   :icao=>"",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Weasua, Liberia"},
 "WOI"=>
  {:iata=>"WOI",
   :name=>"Wologissi Airport",
   :city=>"Wologissi",
   :icao=>"",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Wologissi, Liberia"},
 "WAX"=>
  {:iata=>"WAX",
   :name=>"Zwara Airport",
   :city=>"Zwara",
   :icao=>"",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Zwara, Libya"},
 "WAM"=>
  {:iata=>"WAM",
   :name=>"Ambatondrazaka Airport",
   :city=>"Ambatondrazaka",
   :icao=>"FMMZ",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ambatondrazaka, Madagascar"},
 "WAQ"=>
  {:iata=>"WAQ",
   :name=>"Antsalova Airport",
   :city=>"Antsalova",
   :icao=>"FMMG",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Antsalova, Madagascar"},
 "WAI"=>
  {:iata=>"WAI",
   :name=>"Antsohihy Airport",
   :city=>"Antsohihy",
   :icao=>"FMNW",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Antsohihy, Madagascar"},
 "WFI"=>
  {:iata=>"WFI",
   :name=>"Fianarantsoa Airport",
   :icao=>"FMSF",
   :city=>"Fianarantsoa",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Fianarantsoa, Madagascar"},
 "WMR"=>
  {:iata=>"WMR",
   :name=>"Mananara Nord Airport",
   :city=>"Mananara",
   :icao=>"FMNC",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Mananara, Madagascar"},
 "WMN"=>
  {:iata=>"WMN",
   :name=>"Maroantsetra Airport",
   :city=>"Maroantsetra",
   :icao=>"FMNR",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Maroantsetra, Madagascar"},
 "WTS"=>
  {:iata=>"WTS",
   :name=>"Tsiroanomandidy Airport",
   :icao=>"FMMK",
   :city=>"Tsiroanomandidy",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Tsiroanomandidy, Madagascar"},
 "WAD"=>
  {:iata=>"WAD",
   :name=>"Andriamena Airport",
   :icao=>"",
   :city=>"Andriamena",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Andriamena, Madagascar"},
 "WAK"=>
  {:iata=>"WAK",
   :name=>"Ankazoabo Airport",
   :city=>"Ankazoabo",
   :icao=>"FMSZ",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ankazoabo, Madagascar"},
 "WOR"=>
  {:iata=>"WOR",
   :name=>"Moramba Airport",
   :city=>"Ankorefo",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ankorefo, Madagascar"},
 "WBE"=>
  {:iata=>"WBE",
   :name=>"Bealanana Airport",
   :city=>"Bealanana",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Bealanana, Madagascar"},
 "WBD"=>
  {:iata=>"WBD",
   :name=>"Befandriana Airport",
   :city=>"Befandriana",
   :icao=>"FMNF",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Befandriana, Madagascar"},
 "WBO"=>
  {:iata=>"WBO",
   :name=>"Beroroha Airport",
   :city=>"Beroroha",
   :icao=>"FMSB",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Beroroha, Madagascar"},
 "WMV"=>
  {:iata=>"WMV",
   :name=>"Madirovalo Airport",
   :city=>"Madirovalo",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Madirovalo, Madagascar"},
 "WML"=>
  {:iata=>"WML",
   :name=>"Malaimbandy Airport",
   :icao=>"FMMC",
   :city=>"Malaimbandy",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Malaimbandy, Madagascar"},
 "WMP"=>
  {:iata=>"WMP",
   :name=>"Mampikony Airport",
   :city=>"Mampikony",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Mampikony, Madagascar"},
 "WVK"=>
  {:iata=>"WVK",
   :name=>"Manakara Airport",
   :city=>"Manakara",
   :icao=>"FMSK",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Manakara, Madagascar"},
 "WMD"=>
  {:iata=>"WMD",
   :name=>"Mandabe Airport",
   :city=>"Mandabe",
   :icao=>"FMSC",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Mandabe, Madagascar"},
 "WMA"=>
  {:iata=>"WMA",
   :name=>"Mandritsara Airport",
   :icao=>"FMNX",
   :city=>"Mandritsara",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Mandritsara, Madagascar"},
 "WPB"=>
  {:iata=>"WPB",
   :name=>"Port Bergé Airport",
   :icao=>"FMNG",
   :city=>"Port Bergé",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Port Bergé, Madagascar"},
 "WTA"=>
  {:iata=>"WTA",
   :name=>"Tambohorano Airport",
   :icao=>"FMMU",
   :city=>"Tambohorano",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Tambohorano, Madagascar"},
 "WVB"=>
  {:iata=>"WVB",
   :name=>"Walvis Bay Airport",
   :icao=>"FYWB",
   :city=>"Walvis Bay",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Walvis Bay, Namibia"},
 "WDH"=>
  {:iata=>"WDH",
   :name=>"Windhoek Hosea Kutako International Airport",
   :icao=>"FYWH",
   :city=>"Windhoek",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Windhoek, Namibia"},
 "WYE"=>
  {:iata=>"WYE",
   :name=>"Yengema Airport",
   :icao=>"GFYE",
   :city=>"Yengema",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Yengema, Kono District, Sierra Leone"},
 "WKF"=>
  {:iata=>"WKF",
   :name=>"Waterkloof (FAWK)",
   :city=>"Waterkloof",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Waterkloof, Africa"},
 "WEL"=>
  {:iata=>"WEL",
   :name=>"Welkom Airport",
   :city=>"Welkom",
   :icao=>"FAWM",
   :country=>'Africa', :country_code=>'',
   :location=>"Welkom, Africa"},
 "WUU"=>
  {:iata=>"WUU",
   :name=>"Wau Airport",
   :icao=>"HSWW",
   :city=>"Wau",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Wau, Sudan"},
 "WHF"=>
  {:iata=>"WHF",
   :name=>"Wadi Halfa Airport",
   :icao=>"HWHF",
   :city=>"Wadi Halfa",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Wadi Halfa, Sudan"},
 "WKI"=>
  {:iata=>"WKI",
   :name=>"Hwange Airport",
   :city=>"Hwange",
   :icao=>"FVWT",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Hwange, Zimbabwe"},
 "WBG"=>
  {:iata=>"WBG",
   :name=>"Fliegerhorst Schleswig",
   :icao=>"ETNS",
   :city=>"Schleswig",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Schleswig, Germany"},
 "WIE"=>
  {:iata=>"WIE",
   :name=>"Wiesbaden Army Airfield",
   :icao=>"ETOU",
   :city=>"Wiesbaden",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Wiesbaden, Hessen, Germany"},
 "WID"=>
  {:iata=>"WID",
   :name=>"Wildenrath Airport",
   :city=>"Wildenrath",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Wildenrath, Germany"},
 "WVN"=>
  {:iata=>"WVN",
   :name=>"JadeWeser Airport",
   :icao=>"EDWI",
   :city=>"Wilhelmshaven",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Wilhelmshaven, Lower Saxony, Germany"},
 "WAT"=>
  {:iata=>"WAT",
   :name=>"Waterford Airport",
   :icao=>"EIWF",
   :city=>"Waterford",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Waterford, Ireland"},
 "WEX"=>
  {:iata=>"WEX",
   :name=>"Castlebridge Airport",
   :city=>"Wexford",
   :icao=>"",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Wexford, Ireland"},
 "WOE"=>
  {:iata=>"WOE",
   :name=>"Woensdrecht Air Base",
   :icao=>"EHWO",
   :city=>"Woensdrecht",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Woensdrecht, Netherlands"},
 "WAW"=>
  {:iata=>"WAW",
   :name=>"Frederic Chopin International Airport",
   :icao=>"EPWA",
   :city=>"Warsaw",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Warsaw, Poland"},
 "WRO"=>
  {:iata=>"WRO",
   :name=>"Copernicus Airport Wroclaw",
   :icao=>"EPWR",
   :city=>"Wroclaw",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Wroclaw, Poland"},
 "WMI"=>
  {:iata=>"WMI",
   :name=>"Modlin Airport",
   :icao=>"EPMO",
   :city=>"Warsaw",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Warsaw, Poland"},
 "WRY"=>
  {:iata=>"WRY",
   :name=>"Westray Airport",
   :city=>"Westray",
   :icao=>"EGEW",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Westray, Kingdom"},
 "WIC"=>
  {:iata=>"WIC",
   :name=>"Wick Airport",
   :icao=>"EGPC",
   :city=>"Wick",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Wick, Scotland, United Kingdom"},
 "WXF"=>
  {:iata=>"WXF",
   :name=>"MDPGA Wethersfield",
   :icao=>"EGVT",
   :city=>"Braintree",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Braintree, England, United Kingdom"},
 "WOB"=>
  {:iata=>"WOB",
   :name=>"Woodbridge RAF",
   :city=>"Suttonheath",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Suttonheath, Kingdom"},
 "WTN"=>
  {:iata=>"WTN",
   :name=>"Royal Air Force Station",
   :city=>"Waddington",
   :icao=>"EGXW",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Waddington, Kingdom"},
 "WEM"=>
  {:iata=>"WEM",
   :name=>"West Malling Airport",
   :city=>"West Malling",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"West Malling, Kingdom"},
 "WHS"=>
  {:iata=>"WHS",
   :name=>"Whalsay Airport",
   :city=>"Whalsay",
   :icao=>"EGEH",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Whalsay, Kingdom"},
 "WFD"=>
  {:iata=>"WFD",
   :name=>"Manchester Woodford Airport",
   :city=>"Woodford",
   :icao=>"EGCD",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Woodford, Kingdom"},
 "WNZ"=>
  {:iata=>"WNZ",
   :name=>"Wenzhou Yongqiang Airport",
   :icao=>"ZSWZ",
   :city=>"Wenzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Wenzhou, Zhejiang, China"},
 "WUH"=>
  {:iata=>"WUH",
   :name=>"Wuhan Tianhe International Airport",
   :icao=>"ZHHH",
   :city=>"Wuhan",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuhan, Hubei, China"},
 "WXN"=>
  {:iata=>"WXN",
   :name=>"Wanzhou Wuqiao Airport",
   :icao=>"ZUWX",
   :city=>"Wanzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Wanzhou, Chongqing, China"},
 "WEF"=>
  {:iata=>"WEF",
   :name=>"Weifang Airport",
   :icao=>"ZSWF",
   :city=>"Weifang",
   :country=>'China', :country_code=>'CN',
   :location=>"Weifang, Shandong, China"},
 "WEH"=>
  {:iata=>"WEH",
   :name=>"Weihai Dashuibo Airport",
   :icao=>"ZSWH",
   :city=>"Weihai",
   :country=>'China', :country_code=>'CN',
   :location=>"Weihai, Shandong, China"},
 "WNH"=>
  {:iata=>"WNH",
   :name=>"Wenshan Airport",
   :icao=>"ZPWS",
   :city=>"Wenshan",
   :country=>'China', :country_code=>'CN',
   :location=>"Wenshan, Yunnan, China"},
 "WUA"=>
  {:iata=>"WUA",
   :name=>"Wuhai Airport",
   :icao=>"ZBUH",
   :city=>"Wuhai",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuhai, Inner Mongolia, China"},
 "WUX"=>
  {:iata=>"WUX",
   :name=>"Sunan Shuofang International Airport",
   :icao=>"ZSWX",
   :city=>"Wuxi/Suzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuxi/Suzhou, Jiangsu, China"},
 "WUS"=>
  {:iata=>"WUS",
   :name=>"Fujian Province Airport",
   :city=>"Wuyishan",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuyishan, China"},
 "WUZ"=>
  {:iata=>"WUZ",
   :name=>"Wuzhou Changzhoudao Airport",
   :icao=>"ZGWZ",
   :city=>"Wuzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuzhou, Guangxi, China"},
 "WHU"=>
  {:iata=>"WHU",
   :name=>"Wuhu Air Base",
   :city=>"Wuhu",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Wuhu, China"},
 "WGC"=>
  {:iata=>"WGC",
   :name=>"Warangal Airport",
   :city=>"Warangal",
   :icao=>"VOWA",
   :country=>"India",
:country_code=>"IN",
   :location=>"Warangal, India"},
 "WGP"=>
  {:iata=>"WGP",
   :name=>"Mau Hau Airport (former ICAO: WRRW)",
   :icao=>"WADW",
   :city=>"Waingapu",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Waingapu, Sumba, East Nusa Tenggara, Indonesia"},
 "WMX"=>
  {:iata=>"WMX",
   :name=>"Wamena Airport",
   :city=>"Wamena",
   :icao=>"WAJW",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Wamena, Indonesia"},
 "WET"=>
  {:iata=>"WET",
   :name=>"Wagethe Airport",
   :city=>"Wagethe",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Wagethe, Indonesia"},
 "WBA"=>
  {:iata=>"WBA",
   :name=>"Wahai Airport",
   :city=>"Wahai",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Wahai, Indonesia"},
 "WAR"=>
  {:iata=>"WAR",
   :name=>"Waris Airport",
   :city=>"Waris",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Waris, Indonesia"},
 "WSR"=>
  {:iata=>"WSR",
   :name=>"Wasior Airport",
   :city=>"Wasior",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Wasior, Indonesia"},
 "WKJ"=>
  {:iata=>"WKJ",
   :name=>"Wakkanai Airport",
   :icao=>"RJCW",
   :city=>"Wakkanai",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Wakkanai, Hokkaido, Japan"},
 "WNS"=>
  {:iata=>"WNS",
   :name=>"Nawabshah Airport",
   :city=>"Nawabshah",
   :icao=>"OPNH",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Nawabshah, Pakistan"},
 "WGB"=>
  {:iata=>"WGB",
   :name=>"Bahawalnagar Airport",
   :icao=>"OPBR",
   :city=>"Bahawalnagar",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Bahawalnagar, Pakistan"},
 "WAF"=>
  {:iata=>"WAF",
   :name=>"Wana Airport",
   :city=>"Wana",
   :icao=>"",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Wana, Pakistan"},
 "WBM"=>
  {:iata=>"WBM",
   :name=>"Wapenamanda Airport",
   :city=>"Wapenamanda",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wapenamanda, Guinea"},
 "WWK"=>
  {:iata=>"WWK",
   :name=>"Boram Airport",
   :city=>"Wewak",
   :icao=>"AYWK",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wewak, Guinea"},
 "WPM"=>
  {:iata=>"WPM",
   :name=>"Wipim Airport",
   :city=>"Wipim",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wipim, Guinea"},
 "WTP"=>
  {:iata=>"WTP",
   :name=>"Woitape Airport",
   :city=>"Woitape",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Woitape, Guinea"},
 "WAB"=>
  {:iata=>"WAB",
   :name=>"Wabag Airport",
   :city=>"Wabag",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wabag, Guinea"},
 "WAO"=>
  {:iata=>"WAO",
   :name=>"Wabo Airport",
   :city=>"Wabo",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wabo, Guinea"},
 "WGU"=>
  {:iata=>"WGU",
   :name=>"Wagau Airport",
   :city=>"Wagau",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wagau, Guinea"},
 "WKN"=>
  {:iata=>"WKN",
   :name=>"Wakunai Airport",
   :city=>"Wakunai",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wakunai, Guinea"},
 "WTT"=>
  {:iata=>"WTT",
   :name=>"Wantoat Airport",
   :city=>"Wantoat",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wantoat, Guinea"},
 "WNU"=>
  {:iata=>"WNU",
   :name=>"Wanuma Airport",
   :city=>"Wanuma",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wanuma, Guinea"},
 "WBC"=>
  {:iata=>"WBC",
   :name=>"Wapolu Airport",
   :city=>"Wapolu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wapolu, Guinea"},
 "WSU"=>
  {:iata=>"WSU",
   :name=>"Wasu Airport",
   :city=>"Wasu",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wasu, Guinea"},
 "WSA"=>
  {:iata=>"WSA",
   :name=>"Wasua Airport",
   :city=>"Wasua",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wasua, Guinea"},
 "WUM"=>
  {:iata=>"WUM",
   :name=>"West New Britain Airport",
   :city=>"Wasum",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wasum, Guinea"},
 "WUG"=>
  {:iata=>"WUG",
   :name=>"Wau Airport",
   :city=>"Wau",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wau, Guinea"},
 "WAJ"=>
  {:iata=>"WAJ",
   :name=>"Wawoi Falls Airport",
   :city=>"Wawoi Falls",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wawoi Falls, Guinea"},
 "WEP"=>
  {:iata=>"WEP",
   :name=>"Weam Airport",
   :city=>"Weam",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Weam, Guinea"},
 "WED"=>
  {:iata=>"WED",
   :name=>"Wedau Airport",
   :city=>"Wedau",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wedau, Guinea"},
 "WIU"=>
  {:iata=>"WIU",
   :name=>"Witu Airport",
   :city=>"Witu",
   :icao=>"WITU",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Witu, Guinea"},
 "WOA"=>
  {:iata=>"WOA",
   :name=>"Wonenara Airport",
   :city=>"Wonenara",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wonenara, Guinea"},
 "WUV"=>
  {:iata=>"WUV",
   :name=>"Wuvulu Island Airport",
   :city=>"Wuvulu Island",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Wuvulu Island, Guinea"},
 "WNP"=>
  {:iata=>"WNP",
   :name=>"Naga Airport (Pili Airport)",
   :icao=>"RPUN",
   :city=>"Pili",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Pili, Camarines Sur, Philippines"},
 "WOT"=>
  {:iata=>"WOT",
   :name=>"Wang-an Airport",
   :icao=>"RCWA",
   :city=>"Wang-an",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Wang-an, Penghu (Pescadores), Republic of China"},
 "WJU"=>
  {:iata=>"WJU",
   :name=>"Wonju Airport",
   :icao=>"RKNW",
   :city=>"Wonju",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Wonju, South Korea"},
 "WRZ"=>
  {:iata=>"WRZ",
   :name=>"Weerawila Airport",
   :icao=>"VCCW",
   :city=>"Weerawila",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Weerawila, Sri Lanka"},
 "WSP"=>
  {:iata=>"WSP",
   :name=>"Waspam Airport",
   :icao=>"MNWP",
   :city=>"Waspam",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"Waspam, Nicaragua"},
 "WWG"=>
  {:iata=>"WWG",
   :name=>"Al Koude Airport",
   :city=>"Al Koude",
   :icao=>"",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Al Koude, Oman"},
 "WDA"=>
  {:iata=>"WDA",
   :name=>"Wadi Ain Airport",
   :icao=>"",
   :city=>"Wadi Ain",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Wadi Ain, Yemen"},
 "WAE"=>
  {:iata=>"WAE",
   :name=>"Wadi Ad Dawasir Airport",
   :city=>"Wadi Ad Dawasir",
   :icao=>"OEWD",
   :country=>'Arabia', :country_code=>'',
   :location=>"Wadi Ad Dawasir, Arabia"},
 "WAA"=>
  {:iata=>"WAA",
   :name=>"Wales Airport (FAA: IWK)",
   :icao=>"PAIW",
   :city=>"Wales",
   :country=>'United States', :country_code=>'US',

   :location=>"Wales, Alaska, United States"},
 "WAH"=>
  {:iata=>"WAH",
   :name=>"Harry Stern Airport (FAA: BWP)",
   :icao=>"KBWP",
   :city=>"Wahpeton",
   :country=>'United States', :country_code=>'US',

   :location=>"Wahpeton, North Dakota, United States"},
 "WAL"=>
  {:iata=>"WAL",
   :name=>"Wallops Flight Facility Airport",
   :icao=>"KWAL",
   :city=>"Wallops Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Wallops Island, Virginia, United States"},
 "WAS"=>
  {:iata=>"WAS",
   :name=>"All airports",
   :icao=>"",
   :city=>"Washington",
   :country=>'United States', :country_code=>'US',

   :location=>"Washington, D.C., United States"},
 "WAY"=>
  {:iata=>"WAY",
   :name=>"Greene County Airport",
   :icao=>"KWAY",
   :city=>"Waynesburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Waynesburg, Pennsylvania, United States"},
 "WBB"=>
  {:iata=>"WBB",
   :name=>"Stebbins Airport",
   :icao=>"",
   :city=>"Stebbins",
   :country=>'United States', :country_code=>'US',

   :location=>"Stebbins, Alaska, United States"},
 "WBQ"=>
  {:iata=>"WBQ",
   :name=>"Beaver Airport",
   :icao=>"PAWB",
   :city=>"Beaver",
   :country=>'United States', :country_code=>'US',

   :location=>"Beaver, Alaska, United States"},
 "WBR"=>
  {:iata=>"WBR",
   :name=>"Roben-Hood Airport (FAA: RQB)",
   :icao=>"KRQB",
   :city=>"Big Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Big Rapids, Michigan, United States"},
 "WBU"=>
  {:iata=>"WBU",
   :name=>"Boulder Municipal Airport (FAA: BDU)",
   :icao=>"KBDU",
   :city=>"Boulder",
   :country=>'United States', :country_code=>'US',

   :location=>"Boulder, Colorado, United States"},
 "WBW"=>
  {:iata=>"WBW",
   :name=>"Wilkes-Barre Wyoming Valley Airport",
   :icao=>"KWBW",
   :city=>"Wilkes-Barre",
   :country=>'United States', :country_code=>'US',

   :location=>"Wilkes-Barre, Pennsylvania, United States"},
 "WCR"=>
  {:iata=>"WCR",
   :name=>"Chandalar Lake Airport",
   :icao=>"PALR",
   :city=>"Chandalar Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Chandalar Lake, Alaska, United States"},
 "WDG"=>
  {:iata=>"WDG",
   :name=>"Enid Woodring Regional Airport",
   :icao=>"KWDG",
   :city=>"Enid",
   :country=>'United States', :country_code=>'US',

   :location=>"Enid, Oklahoma, United States"},
 "WDR"=>
  {:iata=>"WDR",
   :name=>"Barrow County Airport",
   :icao=>"KWDR",
   :city=>"Winder",
   :country=>'United States', :country_code=>'US',

   :location=>"Winder, Georgia, United States"},
 "WEA"=>
  {:iata=>"WEA",
   :name=>"Parker County Airport",
   :icao=>"KWEA",
   :city=>"Weatherford",
   :country=>'United States', :country_code=>'US',

   :location=>"Weatherford, Texas, United States"},
 "WFB"=>
  {:iata=>"WFB",
   :name=>"Ketchikan Harbor Seaplane Base (FAA: 5KE)",
   :icao=>"",
   :city=>"Ketchikan",
   :country=>'United States', :country_code=>'US',

   :location=>"Ketchikan, Alaska, United States"},
 "WFK"=>
  {:iata=>"WFK",
   :name=>"Northern Aroostook Regional Airport (FAA: FVE)",
   :icao=>"KFVE",
   :city=>"Frenchville",
   :country=>'United States', :country_code=>'US',

   :location=>"Frenchville, Maine, United States"},
 "WGO"=>
  {:iata=>"WGO",
   :name=>"Winchester Regional Airport (FAA: OKV)",
   :icao=>"KOKV",
   :city=>"Winchester",
   :country=>'United States', :country_code=>'US',

   :location=>"Winchester, Virginia, United States"},
 "WHD"=>
  {:iata=>"WHD",
   :name=>"Hyder Seaplane Base (FAA: 4Z7)",
   :icao=>"",
   :city=>"Hyder",
   :country=>'United States', :country_code=>'US',

   :location=>"Hyder, Alaska, United States"},
 "WHP"=>
  {:iata=>"WHP",
   :name=>"Whiteman Airport",
   :icao=>"KWHP",
   :city=>"Los Angeles",
   :country=>'United States', :country_code=>'US',

   :location=>"Los Angeles, California, United States"},
 "WHT"=>
  {:iata=>"WHT",
   :name=>"Wharton Regional Airport (FAA: ARM)",
   :icao=>"KARM",
   :city=>"Wharton",
   :country=>'United States', :country_code=>'US',

   :location=>"Wharton, Texas, United States"},
 "WJF"=>
  {:iata=>"WJF",
   :name=>"General William J. Fox Airfield",
   :icao=>"KWJF",
   :city=>"Lancaster",
   :country=>'United States', :country_code=>'US',

   :location=>"Lancaster, California, United States"},
 "WKK"=>
  {:iata=>"WKK",
   :name=>"Aleknagik Airport (FAA: 5A8)",
   :icao=>"",
   :city=>"Aleknagik",
   :country=>'United States', :country_code=>'US',

   :location=>"Aleknagik, Alaska, United States"},
 "WKL"=>
  {:iata=>"WKL",
   :name=>"Waikoloa Heliport (FAA: HI07)",
   :icao=>"",
   :city=>"Waikoloa Village",
   :country=>'United States', :country_code=>'US',

   :location=>"Waikoloa Village, Hawaii, United States"},
 "WLD"=>
  {:iata=>"WLD",
   :name=>"Strother Field",
   :icao=>"KWLD",
   :city=>"Winfield/Arkansas City",
   :country=>'United States', :country_code=>'US',

   :location=>"Winfield/Arkansas City, Kansas, United States"},
 "WLK"=>
  {:iata=>"WLK",
   :name=>"Selawik Airport",
   :icao=>"PASK",
   :city=>"Selawik",
   :country=>'United States', :country_code=>'US',

   :location=>"Selawik, Alaska, United States"},
 "WLM"=>
  {:iata=>"WLM",
   :name=>"Prospect Hill Heliport (FAA: MA92)",
   :icao=>"",
   :city=>"Waltham",
   :country=>'United States', :country_code=>'US',

   :location=>"Waltham, Massachusetts, United States"},
 "WLR"=>
  {:iata=>"WLR",
   :name=>"Loring Seaplane Base (FAA: 13Z)",
   :icao=>"",
   :city=>"Loring",
   :country=>'United States', :country_code=>'US',

   :location=>"Loring, Alaska, United States"},
 "WLW"=>
  {:iata=>"WLW",
   :name=>"Willows-Glenn County Airport",
   :icao=>"KWLW",
   :city=>"Willows",
   :country=>'United States', :country_code=>'US',

   :location=>"Willows, California, United States"},
 "WMC"=>
  {:iata=>"WMC",
   :name=>"Winnemucca Municipal Airport",
   :icao=>"KWMC",
   :city=>"Winnemucca",
   :country=>'United States', :country_code=>'US',

   :location=>"Winnemucca, Nevada, United States"},
 "WMH"=>
  {:iata=>"WMH",
   :name=>"Ozark Regional Airport (FAA: BPK)",
   :icao=>"KBPK",
   :city=>"Mountain Home",
   :country=>'United States', :country_code=>'US',

   :location=>"Mountain Home, Arkansas, United States"},
 "WMK"=>
  {:iata=>"WMK",
   :name=>"Meyers Chuck Seaplane Base (FAA: 84K)",
   :icao=>"",
   :city=>"Meyers Chuck",
   :country=>'United States', :country_code=>'US',

   :location=>"Meyers Chuck, Alaska, United States"},
 "WMO"=>
  {:iata=>"WMO",
   :name=>"White Mountain Airport",
   :icao=>"PAWM",
   :city=>"White Mountain",
   :country=>'United States', :country_code=>'US',

   :location=>"White Mountain, Alaska, United States"},
 "WNA"=>
  {:iata=>"WNA",
   :name=>"Napakiak Airport",
   :icao=>"PANA",
   :city=>"Napakiak",
   :country=>'United States', :country_code=>'US',

   :location=>"Napakiak, Alaska, United States"},
 "WNC"=>
  {:iata=>"WNC",
   :name=>"Naukati Bay Seaplane Base (FAA: AK62)",
   :icao=>"",
   :city=>"Tuxekan Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Tuxekan Island, Alaska, United States"},
 "WOW"=>
  {:iata=>"WOW",
   :name=>"Willow Airport (FAA: UUO)",
   :icao=>"PAUO",
   :city=>"Willow",
   :country=>'United States', :country_code=>'US',

   :location=>"Willow, Alaska, United States"},
 "WPO"=>
  {:iata=>"WPO",
   :name=>"North Fork Valley Airport (FAA: 7V2)",
   :icao=>"",
   :city=>"Paonia",
   :country=>'United States', :country_code=>'US',

   :location=>"Paonia, Colorado, United States"},
 "WRB"=>
  {:iata=>"WRB",
   :name=>"Robins Air Force Base",
   :icao=>"KWRB",
   :city=>"Warner Robins",
   :country=>'United States', :country_code=>'US',

   :location=>"Warner Robins, Georgia, United States"},
 "WRG"=>
  {:iata=>"WRG",
   :name=>"Wrangell Airport",
   :icao=>"PAWG",
   :city=>"Wrangell",
   :country=>'United States', :country_code=>'US',

   :location=>"Wrangell, Alaska, United States"},
 "WRI"=>
  {:iata=>"WRI",
   :name=>"McGuire Air Force Base",
   :icao=>"KWRI",
   :city=>"Wrightstown",
   :country=>'United States', :country_code=>'US',

   :location=>"Wrightstown, New Jersey, United States"},
 "WRT"=>
  {:iata=>"WRT",
   :name=>"Warton Aerodrome",
   :icao=>"EGNO",
   :city=>"Warton",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Warton, Lancashire, England, United Kingdom"},
 "WSD"=>
  {:iata=>"WSD",
   :name=>"Condron Army Airfield",
   :icao=>"KWSD",
   :city=>"White Sands",
   :country=>'United States', :country_code=>'US',

   :location=>"White Sands, New Mexico, United States"},
 "WSG"=>
  {:iata=>"WSG",
   :name=>"Washington County Airport (FAA: AFJ)",
   :icao=>"KAFJ",
   :city=>"Washington",
   :country=>'United States', :country_code=>'US',

   :location=>"Washington, Pennsylvania, United States"},
 "WSH"=>
  {:iata=>"WSH",
   :name=>"Brookhaven Airport (FAA: HWV)",
   :icao=>"KHWV",
   :city=>"Shirley",
   :country=>'United States', :country_code=>'US',

   :location=>"Shirley, New York, United States"},
 "WSM"=>
  {:iata=>"WSM",
   :name=>"Wiseman Airport",
   :icao=>"",
   :city=>"Wiseman",
   :country=>'United States', :country_code=>'US',

   :location=>"Wiseman, Alaska, United States"},
 "WSN"=>
  {:iata=>"WSN",
   :name=>"South Naknek Nr 2 Airport",
   :icao=>"PFWS",
   :city=>"South Naknek",
   :country=>'United States', :country_code=>'US',

   :location=>"South Naknek, Alaska, United States"},
 "WST"=>
  {:iata=>"WST",
   :name=>"Westerly Airport",
   :icao=>"KWST",
   :city=>"Westerly",
   :country=>'United States', :country_code=>'US',

   :location=>"Westerly, Rhode Island, United States"},
 "WSX"=>
  {:iata=>"WSX",
   :name=>"Westsound/WSX Seaplane Base (FAA: WA83)",
   :icao=>"",
   :city=>"Westsound",
   :country=>'United States', :country_code=>'US',

   :location=>"Westsound, Orcas Island, Washington, United States"},
 "WTK"=>
  {:iata=>"WTK",
   :name=>"Noatak Airport",
   :icao=>"PAWN",
   :city=>"Noatak",
   :country=>'United States', :country_code=>'US',

   :location=>"Noatak, Alaska, United States"},
 "WTL"=>
  {:iata=>"WTL",
   :name=>"Tuntutuliak Airport (FAA: A61)",
   :icao=>"",
   :city=>"Tuntutuliak",
   :country=>'United States', :country_code=>'US',

   :location=>"Tuntutuliak, Alaska, United States"},
 "WTR"=>
  {:iata=>"WTR",
   :name=>"Whiteriver Airport (FAA: E24)",
   :icao=>"",
   :city=>"Whiteriver",
   :country=>'United States', :country_code=>'US',

   :location=>"Whiteriver, Arizona, United States"},
 "WVI"=>
  {:iata=>"WVI",
   :name=>"Watsonville Municipal Airport",
   :icao=>"KWVI",
   :city=>"Watsonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Watsonville, California, United States"},
 "WVL"=>
  {:iata=>"WVL",
   :name=>"Waterville Robert LaFleur Airport",
   :icao=>"KWVL",
   :city=>"Waterville",
   :country=>'United States', :country_code=>'US',

   :location=>"Waterville, Maine, United States"},
 "WWA"=>
  {:iata=>"WWA",
   :name=>"Wasilla Airport (FAA: IYS)",
   :icao=>"PAWS",
   :city=>"Wasilla",
   :country=>'United States', :country_code=>'US',

   :location=>"Wasilla, Alaska, United States"},
 "WWD"=>
  {:iata=>"WWD",
   :name=>"Cape May Airport",
   :icao=>"KWWD",
   :city=>"Wildwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Wildwood, New Jersey, United States"},
 "WWP"=>
  {:iata=>"WWP",
   :name=>"North Whale Seaplane Base (FAA: 96Z)",
   :icao=>"",
   :city=>"North Whale Pass",
   :country=>'United States', :country_code=>'US',

   :location=>"North Whale Pass, Alaska, United States"},
 "WWR"=>
  {:iata=>"WWR",
   :name=>"West Woodward Airport",
   :icao=>"KWWR",
   :city=>"Woodward",
   :country=>'United States', :country_code=>'US',

   :location=>"Woodward, Oklahoma, United States"},
 "WWT"=>
  {:iata=>"WWT",
   :name=>"Newtok Airport (FAA: EWU)",
   :icao=>"PAEW",
   :city=>"Newtok",
   :country=>'United States', :country_code=>'US',

   :location=>"Newtok, Alaska, United States"},
 "WYB"=>
  {:iata=>"WYB",
   :name=>"Yes Bay Lodge Seaplane Base (FAA: 78K)",
   :icao=>"",
   :city=>"Yes Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Yes Bay, Alaska, United States"},
 "WYS"=>
  {:iata=>"WYS",
   :name=>"Yellowstone Airport",
   :icao=>"KWYS",
   :city=>"West Yellowstone",
   :country=>'United States', :country_code=>'US',

   :location=>"West Yellowstone, Montana, United States"}}

end
