# encoding: UTF-8
def airp_10
  {"ILF"=>
  {:iata=>"ILF",
   :name=>"Ilford Airport",
   :icao=>"CZBD",
   :city=>"Ilford",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Ilford, Manitoba, Canada"},
 "IUM"=>
  {:iata=>"IUM",
   :name=>"Summit Lake Airport",
   :icao=>"",
   :city=>"Summit Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Summit Lake, British Columbia, Canada"},
 "IKE"=>
  {:iata=>"IKE",
   :name=>"Ikerasak Heliport",
   :icao=>"BGIA",
   :city=>"Ikerasak",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Ikerasak, Greenland"},
 "IOT"=>
  {:iata=>"IOT",
   :name=>"Illorsuit Heliport",
   :city=>"Illorsuit",
   :icao=>"BGLL",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Illorsuit, Greenland"},
 "IUI"=>
  {:iata=>"IUI",
   :name=>"Innaarsuit Heliport",
   :icao=>"BGIN",
   :city=>"Innaarsuit",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Innaarsuit, Greenland"},
 "IOQ"=>
  {:iata=>"IOQ",
   :name=>"Isortoq Heliport",
   :icao=>"BGIS",
   :city=>"Isortoq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Isortoq, Greenland"},
 "ISJ"=>
  {:iata=>"ISJ",
   :name=>"Isla Mujeres Airport",
   :icao=>"MMIM",
   :city=>"Isla Mujeres",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Isla Mujeres, Quintana Roo, Mexico"},
 "IZT"=>
  {:iata=>"IZT",
   :name=>"Ixtepec Airport",
   :icao=>"MMIT",
   :city=>"Ixtepec",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Ixtepec, Oaxaca, Mexico"},
 "IGR"=>
  {:iata=>"IGR",
   :name=>"Cataratas del Iguazú International Airport",
   :icao=>"SARI",
   :city=>"Puerto Iguazú",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Puerto Iguazú, Misiones, Argentina"},
 "IRJ"=>
  {:iata=>"IRJ",
   :name=>"Capitán Vicente Almandos Almonacid Airport",
   :icao=>"SANL",
   :city=>"La Rioja",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"La Rioja, Argentina"},
 "ING"=>
  {:iata=>"ING",
   :name=>"Lago Argentino Airport (closed 2006)",
   :icao=>"SAWA",
   :city=>"El Calafate",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"El Calafate, Santa Cruz, Argentina"},
 "IGB"=>
  {:iata=>"IGB",
   :name=>"C. FAA H.R. Borden Airport (Ingeniero Jacobacci Airport)",
   :icao=>"SAVJ",
   :city=>"Ingeniero Jacobacci",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Ingeniero Jacobacci, Río Negro, Argentina"},
 "IGU"=>
  {:iata=>"IGU",
   :name=>"Foz do Iguaçu International Airport",
   :icao=>"SBFI",
   :city=>"Foz do Iguaçu",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Foz do Iguaçu, Paraná, Brazil"},
 "IOS"=>
  {:iata=>"IOS",
   :name=>"Ilhéus Jorge Amado Airport",
   :icao=>"SBIL",
   :city=>"Ilhéus",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ilhéus, Bahia, Brazil"},
 "IMP"=>
  {:iata=>"IMP",
   :name=>"Imperatriz Airport",
   :icao=>"SBIZ",
   :city=>"Imperatriz",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Imperatriz, Maranhão, Brazil"},
 "IPN"=>
  {:iata=>"IPN",
   :name=>"Usiminas Airport",
   :icao=>"SBIP",
   :city=>"Ipatinga / Santana do Paraiso",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ipatinga / Santana do Paraiso, Minas Gerais, Brazil"},
 "ITA"=>
  {:iata=>"ITA",
   :name=>"Itacoiatiara Airport",
   :icao=>"SBIC",
   :city=>"Itacoiatiara",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itacoiatiara, Amazonas, Brazil"},
 "ITB"=>
  {:iata=>"ITB",
   :name=>"Itaituba Airport",
   :icao=>"SBIH",
   :city=>"Itaituba",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itaituba, Pará, Brazil"},
 "IZA"=>
  {:iata=>"IZA",
   :name=>"Zona da Mata Regional Airport",
   :icao=>"SBZM",
   :city=>"Juiz de Fora",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Juiz de Fora, Brazil"},
 "IRZ"=>
  {:iata=>"IRZ",
   :name=>"Santa Isabel Rio Negro Airport",
   :city=>"Santa Isabel Rio Negro",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santa Isabel Rio Negro, Brazil"},
 "IJU"=>
  {:iata=>"IJU",
   :name=>"Ijuí Airport (J. Batista Bos Filho Airport)",
   :icao=>"SSIJ",
   :city=>"Ijuí",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ijuí, Rio Grande do Sul, Brazil"},
 "ILB"=>
  {:iata=>"ILB",
   :name=>"Ilha Solteira Airport",
   :icao=>"",
   :city=>"Ilha Solteira",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ilha Solteira, São Paulo, Brazil"},
 "IPU"=>
  {:iata=>"IPU",
   :name=>"Ipiaú Airport",
   :icao=>"SNIU",
   :city=>"Ipiaú",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ipiaú, Bahia, Brazil"},
 "IPG"=>
  {:iata=>"IPG",
   :name=>"Ipiranga Airport",
   :icao=>"SWII",
   :city=>"Santo Antônio do Içá",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santo Antônio do Içá, Amazonas, Brazil"},
 "IRE"=>
  {:iata=>"IRE",
   :name=>"Irecê Airport",
   :icao=>"SNIC",
   :city=>"Irecê",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Irecê, Bahia, Brazil"},
 "ITN"=>
  {:iata=>"ITN",
   :name=>"Itabuna Airport",
   :icao=>"SNHA",
   :city=>"Itabuna",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itabuna, Bahia, Brazil"},
 "ITI"=>
  {:iata=>"ITI",
   :name=>"Itambacuri Airport",
   :icao=>"SNYH",
   :city=>"Itambacuri",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itambacuri, Minas Gerais, Brazil"},
 "ITP"=>
  {:iata=>"ITP",
   :name=>"Itaperuna Airport",
   :icao=>"SDUN",
   :city=>"Itaperuna",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itaperuna, Rio de Janeiro, Brazil"},
 "ITQ"=>
  {:iata=>"ITQ",
   :name=>"Itaqui Airport",
   :icao=>"SSIQ",
   :city=>"Itaqui",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itaqui, Rio Grande do Sul, Brazil"},
 "ITE"=>
  {:iata=>"ITE",
   :name=>"Ituberá Airport",
   :icao=>"SNZW",
   :city=>"Ituberá",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ituberá, Bahia, Brazil"},
 "ITR"=>
  {:iata=>"ITR",
   :name=>"Itumbiara Airport",
   :icao=>"SBIT",
   :city=>"Itumbiara",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itumbiara, Goiás, Brazil"},
 "IDO"=>
  {:iata=>"IDO",
   :name=>"Santa Isabel do Morro Airport",
   :icao=>"SWIY",
   :city=>"Santa Isabel do Morro",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santa Isabel do Morro, Tocantins, Brazil"},
 "IPC"=>
  {:iata=>"IPC",
   :name=>"Mataveri International Airport",
   :icao=>"SCIP",
   :city=>"Easter Island",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Easter Island, Chile"},
 "IQQ"=>
  {:iata=>"IQQ",
   :name=>"Diego Aracena International Airport",
   :icao=>"SCDA",
   :city=>"Iquique",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Iquique, Chile"},
 "IBE"=>
  {:iata=>"IBE",
   :name=>"Perales Airport",
   :icao=>"SKIB",
   :city=>"Ibagué",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Ibagué, Colombia"},
 "IPI"=>
  {:iata=>"IPI",
   :name=>"San Luis Airport",
   :icao=>"SKIP",
   :city=>"Ipiales",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Ipiales, Colombia"},
 "IGO"=>
  {:iata=>"IGO",
   :name=>"Chigorodó Airport",
   :icao=>"SKIG",
   :city=>"Chigorodó",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Chigorodó, Colombia"},
 "IVO"=>
  {:iata=>"IVO",
   :name=>"Chivolo Airport",
   :icao=>"",
   :city=>"Chivolo",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Chivolo, Colombia"},
 "ISD"=>
  {:iata=>"ISD",
   :name=>"Iscuande Airport",
   :icao=>"",
   :city=>"Iscuande",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Iscuande, Colombia"},
 "IMB"=>
  {:iata=>"IMB",
   :name=>"Imbaimadai Airport",
   :icao=>"SYIB",
   :city=>"Imbaimadai",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Imbaimadai, Guyana"},
 "IQT"=>
  {:iata=>"IQT",
   :name=>"Crnl. FAP Francisco Secada Vignetta International Airport",
   :icao=>"SPQT",
   :city=>"Iquitos",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Iquitos, Loreto, Peru"},
 "IBP"=>
  {:iata=>"IBP",
   :name=>"Iberia Airport",
   :icao=>"SPBR",
   :city=>"Iberia",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Iberia, Peru"},
 "ILQ"=>
  {:iata=>"ILQ",
   :name=>"Ilo Airport",
   :icao=>"SPLO",
   :city=>"Ilo",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Ilo, Moquegua Region, Peru"},
 "ICK"=>
  {:iata=>"ICK",
   :name=>"Nieuw-Nickerie Airport (Maj. Fernandes Airport)",
   :icao=>"SMNI",
   :city=>"Nieuw-Nickerie",
   :country=>"Suriname",
:country_code=>"SR",
   :location=>"Nieuw-Nickerie, Suriname"},
 "ICA"=>
  {:iata=>"ICA",
   :name=>"Icabaru Airport",
   :icao=>"SVIC",
   :city=>"Icabaru",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Icabaru, Venezuela"},
 "IRG"=>
  {:iata=>"IRG",
   :name=>"Lockhart River Airport",
   :icao=>"YLHR",
   :city=>"Lockhart River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lockhart River, Queensland, Australia"},
 "ISA"=>
  {:iata=>"ISA",
   :name=>"Mount Isa Airport",
   :icao=>"YBMA",
   :city=>"Mount Isa",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mount Isa, Queensland, Australia"},
 "IFF"=>
  {:iata=>"IFF",
   :name=>"Iffley Airport",
   :icao=>"YIFY",
   :city=>"Iffley",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Iffley, Queensland, Australia"},
 "IDK"=>
  {:iata=>"IDK",
   :name=>"Indulkana Airport",
   :icao=>"YIDK",
   :city=>"Indulkana",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Indulkana, South Australia, Australia"},
 "IGH"=>
  {:iata=>"IGH",
   :name=>"Ingham Airport",
   :icao=>"YIGM",
   :city=>"Ingham",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ingham, Queensland, Australia"},
 "INJ"=>
  {:iata=>"INJ",
   :name=>"Injune Airport",
   :icao=>"YINJ",
   :city=>"Injune",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Injune, Queensland, Australia"},
 "IKP"=>
  {:iata=>"IKP",
   :name=>"Inkerman Airport",
   :icao=>"YIKM",
   :city=>"Inkerman",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Inkerman, Queensland, Australia"},
 "INM"=>
  {:iata=>"INM",
   :name=>"Innamincka Airport",
   :icao=>"YINN",
   :city=>"Innamincka",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Innamincka, South Australia, Australia"},
 "IFL"=>
  {:iata=>"IFL",
   :name=>"Innisfail Airport",
   :icao=>"YIFL",
   :city=>"Innisfail",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Innisfail, Queensland, Australia"},
 "IVR"=>
  {:iata=>"IVR",
   :name=>"Inverell Airport",
   :icao=>"YIVL",
   :city=>"Inverell",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Inverell, New South Wales, Australia"},
 "IVW"=>
  {:iata=>"IVW",
   :name=>"Inverway Airport",
   :icao=>"YINW",
   :city=>"Inverway",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Inverway, Northern Territory, Australia"},
 "ISI"=>
  {:iata=>"ISI",
   :name=>"Isisford Airport",
   :icao=>"YISF",
   :city=>"Isisford",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Isisford, Queensland, Australia"},
 "ICI"=>
  {:iata=>"ICI",
   :name=>"Cicia Airport",
   :icao=>"NFCI",
   :city=>"Cicia",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Cicia, Fiji"},
 "IMI"=>
  {:iata=>"IMI",
   :name=>"Ine Airport (FAA: N20)",
   :icao=>"",
   :city=>"Ine",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Ine, Arno Atoll, Marshall Islands"},
 "INU"=>
  {:iata=>"INU",
   :name=>"Nauru International Airport",
   :icao=>"ANYN",
   :city=>"Yaren",
   :country=>'Nauru', :country_code=>'NR',
   :location=>"Yaren, Nauru"},
 "ILP"=>
  {:iata=>"ILP",
   :name=>"Moué Airport (Île des Pins Airport)",
   :icao=>"NWWE",
   :city=>"Île des Pins",
   :country=>'New Caledonia', :country_code=>'NC',
   :location=>"Île des Pins, New Caledonia"},
 "IOU"=>
  {:iata=>"IOU",
   :name=>"Ile Ouen Airport",
   :city=>"Ile Ouen",
   :icao=>"",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Ile Ouen, Caledonia"},
 "IVC"=>
  {:iata=>"IVC",
   :name=>"Invercargill Airport",
   :icao=>"NZNV",
   :city=>"Invercargill",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Invercargill, New Zealand"},
 "IUE"=>
  {:iata=>"IUE",
   :name=>"Hanan International Airport",
   :icao=>"NIUE",
   :city=>"Alofi",
   :country=>'Niue', :country_code=>'NU',
   :location=>"Alofi, Niue"},
 "IRA"=>
  {:iata=>"IRA",
   :name=>"Ngorangora Airport (Kirakira Airport)",
   :icao=>"AGGK",
   :city=>"Kirakira",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Kirakira, Makira Island, Solomon Islands"},
 "IPA"=>
  {:iata=>"IPA",
   :name=>"Ipota Airport",
   :icao=>"NVVI",
   :city=>"Ipota",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Ipota, Erromango, Vanuatu"},
 "IGA"=>
  {:iata=>"IGA",
   :name=>"Matthew Town Airport (Inagua Airport)",
   :icao=>"MYIG",
   :city=>"Matthew Town",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Matthew Town, Great Inagua Island, Bahamas"},
 "ICR"=>
  {:iata=>"ICR",
   :name=>"Nicaro Airport",
   :icao=>"MUNC",
   :city=>"Nicaro",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Nicaro, Cuba"},
 "IAM"=>
  {:iata=>"IAM",
   :name=>"In Amenas Airport",
   :icao=>"DAUZ",
   :city=>"In Amenas",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"In Amenas, Algeria"},
 "INZ"=>
  {:iata=>"INZ",
   :name=>"In Salah Airport",
   :icao=>"DAUI",
   :city=>"In Salah",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"In Salah, Algeria"},
 "INF"=>
  {:iata=>"INF",
   :name=>"In Guezzam Airport",
   :icao=>"DATG",
   :city=>"In Guezzam",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"In Guezzam, Algeria"},
 "IRO"=>
  {:iata=>"IRO",
   :name=>"Birao Airport",
   :icao=>"FEFI",
   :city=>"Birao",
   :country=>'Central African Republic', :country_code=>'CF',
   :location=>"Birao, Central African Republic"},
 "IMO"=>
  {:iata=>"IMO",
   :name=>"Zemio Airport",
   :icao=>"FEFZ",
   :city=>"Zemio",
   :country=>'Central African Republic', :country_code=>'CF',
   :location=>"Zemio, Central African Republic"},
 "ION"=>
  {:iata=>"ION",
   :name=>"Impfondo Airport",
   :icao=>"FCOI",
   :city=>"Impfondo",
   :country=>'Republic of the Congo', :country_code=>'CD',
   :location=>"Impfondo, Republic of the Congo"},
 "IGE"=>
  {:iata=>"IGE",
   :name=>"Iguela Airport",
   :icao=>"FOOI",
   :city=>"Iguela",
   :country=>'Gabon', :country_code=>'GA',
   :location=>"Iguela, Gabon"},
 "ILU"=>
  {:iata=>"ILU",
   :name=>"Kilaguni Airport",
   :icao=>"HKKL",
   :city=>"Kilaguni",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Kilaguni, Kenya"},
 "IVA"=>
  {:iata=>"IVA",
   :name=>"Ambanja Airport",
   :icao=>"FMNJ",
   :city=>"Ambanja",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ambanja, Madagascar"},
 "IHO"=>
  {:iata=>"IHO",
   :name=>"Ihosy Airport",
   :icao=>"FMSI",
   :city=>"Ihosy",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ihosy, Madagascar"},
 "ILK"=>
  {:iata=>"ILK",
   :name=>"Atsinanana Airport (Ilaka Airport)",
   :icao=>"FMMQ",
   :city=>"Ilaka",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Ilaka, Madagascar"},
 "INH"=>
  {:iata=>"INH",
   :name=>"Inhambane Airport",
   :icao=>"FQIN",
   :city=>"Inhambane",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Inhambane, Mozambique"},
 "INE"=>
  {:iata=>"INE",
   :name=>"Chinde Airport",
   :icao=>"",
   :city=>"Chinde",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Chinde, Mozambique"},
 "IBO"=>
  {:iata=>"IBO",
   :name=>"Ibo Airport",
   :icao=>"",
   :city=>"Ibo",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Ibo, Mozambique"},
 "IHC"=>
  {:iata=>"IHC",
   :name=>"Inhaca Airport",
   :city=>"Inhaca",
   :icao=>"FQIA",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Inhaca, Mozambique"},
 "IMG"=>
  {:iata=>"IMG",
   :name=>"Inhaminga Airport",
   :icao=>"",
   :city=>"Inhaminga",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Inhaminga, Mozambique"},
 "IBA"=>
  {:iata=>"IBA",
   :name=>"Ibadan Airport",
   :icao=>"DNIB",
   :city=>"Ibadan",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Ibadan, Nigeria"},
 "ILR"=>
  {:iata=>"ILR",
   :name=>"Ilorin Airport",
   :icao=>"DNIL",
   :city=>"Ilorin",
   :country=>'Nigeria', :country_code=>'NG',
   :location=>"Ilorin, Nigeria"},
 "INY"=>
  {:iata=>"INY",
   :name=>"Inyati Airport",
   :icao=>"",
   :city=>"Inyati",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Inyati, South Africa"},
 "IRP"=>
  {:iata=>"IRP",
   :name=>"Matari Airport",
   :icao=>"FZJH",
   :city=>"Isiro",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Isiro, Democratic Republic of the Congo"},
 "IDF"=>
  {:iata=>"IDF",
   :name=>"Idiofa Airport",
   :icao=>"FZCB",
   :city=>"Idiofa",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Idiofa, Democratic Republic of the Congo"},
 "IKL"=>
  {:iata=>"IKL",
   :name=>"Ikela Airport",
   :icao=>"FZGV",
   :city=>"Ikela",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Ikela, Democratic Republic of the Congo"},
 "INO"=>
  {:iata=>"INO",
   :name=>"Inongo Airport",
   :icao=>"FZBA",
   :city=>"Inongo",
   :country=>'Democratic Republic of the Congo', :country_code=>'',
   :location=>"Inongo, Democratic Republic of the Congo"},
 "IRI"=>
  {:iata=>"IRI",
   :name=>"Iringa Airport (Nduli Airport)",
   :icao=>"HTIR",
   :city=>"Iringa",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Iringa, Tanzania"},
 "INN"=>
  {:iata=>"INN",
   :name=>"Innsbruck Airport (Kranebitten Airport)",
   :icao=>"LOWI",
   :city=>"Innsbruck",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Innsbruck, Austria"},
 "IVL"=>
  {:iata=>"IVL",
   :name=>"Ivalo Airport",
   :icao=>"EFIV",
   :city=>"Ivalo",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Ivalo, Finland"},
 "IDY"=>
  {:iata=>"IDY",
   :name=>"Île d'Yeu Airport",
   :icao=>"LFEY",
   :city=>"Île d'Yeu",
   :country=>'France', :country_code=>'FR',
   :location=>"Île d'Yeu, France"},
 "IES"=>
  {:iata=>"IES",
   :name=>"Göhlis Airport",
   :icao=>"EDAU",
   :city=>"Riesa",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Riesa, Germany"},
 "IOA"=>
  {:iata=>"IOA",
   :name=>"Ioannina National Airport",
   :icao=>"LGIO",
   :city=>"Ioannina",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Ioannina, Greece"},
 "IFJ"=>
  {:iata=>"IFJ",
   :name=>"Ísafjörður Airport",
   :icao=>"BIIS",
   :city=>"Ísafjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Ísafjörður, Iceland"},
 "INQ"=>
  {:iata=>"INQ",
   :name=>"Inisheer Airport",
   :icao=>"EIIR",
   :city=>"Inisheer",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Inisheer, Ireland"},
 "IIA"=>
  {:iata=>"IIA",
   :name=>"Inishmaan Airport",
   :icao=>"EIMN",
   :city=>"Inishmaan",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Inishmaan, Ireland"},
 "IOR"=>
  {:iata=>"IOR",
   :name=>"Inishmore Aerodrome (Kilronan Airport)",
   :icao=>"EIIM",
   :city=>"Kilronan",
   :country=>'Ireland', :country_code=>'IE',
   :location=>"Kilronan, Inishmore, Ireland"},
 "ISH"=>
  {:iata=>"ISH",
   :name=>"Ischia Airport",
   :icao=>"",
   :city=>"Ischia",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Ischia, Italy"},
 "IVG"=>
  {:iata=>"IVG",
   :name=>"Berane Airport (Dolac Airport, Ivangrad)",
   :icao=>"LYBR",
   :city=>"Berane",
   :country=>'Montenegro', :country_code=>'ME',
   :location=>"Berane, Montenegro"},
 "IEG"=>
  {:iata=>"IEG",
   :name=>"Zielona Góra Airport (Babimost Air Base)",
   :icao=>"EPZG",
   :city=>"Zielona Góra",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Zielona Góra, Poland"},
 "INI"=>
  {:iata=>"INI",
   :name=>"Niš Constantine the Great Airport",
   :icao=>"LYNI",
   :city=>"Niš",
   :country=>'Serbia', :country_code=>'RS',
   :location=>"Niš, Serbia"},
 "IAS"=>
  {:iata=>"IAS",
   :name=>"Iași International Airport",
   :icao=>"LRIA",
   :city=>"Iași",
   :country=>'Romania', :country_code=>'RO',
   :location=>"Iași, Romania"},
 "IAA"=>
  {:iata=>"IAA",
   :name=>"Igarka Airport",
   :icao=>"UOII",
   :city=>"Igarka",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Igarka, Russia"},
 "IRM"=>
  {:iata=>"IRM",
   :name=>"Igrim Airport",
   :city=>"Igrim",
   :icao=>"USHI",
   :country=>'Federation', :country_code=>'',
   :location=>"Igrim, Federation"},
 "INA"=>
  {:iata=>"INA",
   :name=>"Inta Airport",
   :icao=>"UUYI",
   :city=>"Inta",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Inta, Russia"},
 "IKT"=>
  {:iata=>"IKT",
   :name=>"Irkutsk International Airport",
   :icao=>"UIII",
   :city=>"Irkutsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Irkutsk, Russia"},
 "IWA"=>
  {:iata=>"IWA",
   :name=>"Yuzhny Airport",
   :icao=>"UUBI",
   :city=>"Ivanovo",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ivanovo, Russia"},
 "IJK"=>
  {:iata=>"IJK",
   :name=>"Izhevsk Airport",
   :icao=>"USII",
   :city=>"Izhevsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Izhevsk, Udmurt Republic, Russia"},
 "IGT"=>
  {:iata=>"IGT",
   :name=>"Magas Airport",
   :icao=>"",
   :city=>"Magas",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Magas, Republic of Ingushetia, Russia"},
 "IKS"=>
  {:iata=>"IKS",
   :name=>"Tiksi Airport",
   :icao=>"UEST",
   :city=>"Tiksi",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Tiksi, Russia"},
 "IAR"=>
  {:iata=>"IAR",
   :name=>"Yaroslavl Airport",
   :icao=>"UUDL",
   :city=>"Yaroslavl",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Yaroslavl, Russia"},
 "ILZ"=>
  {:iata=>"ILZ",
   :name=>"Žilina Airport",
   :icao=>"LZZI",
   :city=>"Žilina",
   :country=>'Slovakia', :country_code=>'SK',
   :location=>"Žilina, Slovakia"},
 "ILD"=>
  {:iata=>"ILD",
   :name=>"Lleida-Alguaire Airport",
   :icao=>"LEDA",
   :city=>"Lleida",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Lleida, Spain"},
 "IBZ"=>
  {:iata=>"IBZ",
   :name=>"Ibiza Airport",
   :icao=>"LEIB",
   :city=>"Ibiza",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Ibiza, Spain"},
 "IDB"=>
  {:iata=>"IDB",
   :name=>"Idre Airport",
   :icao=>"ESUE",
   :city=>"Idre",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Idre, Sweden"},
 "IST"=>
  {:iata=>"IST",
   :name=>"Istanbul Atatürk Airport (Yesilköy International)",
   :icao=>"LTBA",
   :city=>"Istanbul",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Istanbul, Turkey"},
 "IGD"=>
  {:iata=>"IGD",
   :name=>"Igdir Airport",
   :city=>"Igdir",
   :icao=>"LTCT",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Igdir, Turkey"},
 "ISE"=>
  {:iata=>"ISE",
   :name=>"Suleyman Demirel Airport",
   :icao=>"LTFC",
   :city=>"Isparta",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Isparta, Turkey"},
 "IGL"=>
  {:iata=>"IGL",
   :name=>"Çiğli Airport (Çiğli Air Base)",
   :icao=>"LTBL",
   :city=>"Çiğli / İzmir",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Çiğli / İzmir, Turkey"},
 "IFO"=>
  {:iata=>"IFO",
   :name=>"Ivano-Frankivsk Airport",
   :icao=>"UKLI",
   :city=>"Ivano-Frankivsk",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Ivano-Frankivsk, Ukraine"},
 "IEV"=>
  {:iata=>"IEV",
   :name=>"Kiev International Airport",
   :icao=>"UKKK",
   :city=>"Kiev",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kiev, Ukraine"},
 "INV"=>
  {:iata=>"INV",
   :name=>"Inverness Airport",
   :icao=>"EGPE",
   :city=>"Inverness",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Inverness, Scotland, United Kingdom"},
 "ILY"=>
  {:iata=>"ILY",
   :name=>"Port Ellen Airport (Glenegedale Airport)",
   :icao=>"EGPI",
   :city=>"Islay",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Islay, Scotland, United Kingdom"},
 "IOM"=>
  {:iata=>"IOM",
   :name=>"Isle of Man Airport",
   :icao=>"EGNS",
   :city=>"Ronaldsway",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Ronaldsway, Isle of Man, United Kingdom"},
 "ISC"=>
  {:iata=>"ISC",
   :name=>"St Mary's Airport",
   :icao=>"EGHE",
   :city=>"St Mary's",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"St Mary's, Isles of Scilly, United Kingdom"},
 "IPW"=>
  {:iata=>"IPW",
   :name=>"Ipswich Airport (closed 1996)",
   :icao=>"EGSE",
   :city=>"Ipswich",
   :country=>'England', :country_code=>'',
   :location=>"Ipswich, England"},
 "IMZ"=>
  {:iata=>"IMZ",
   :name=>"Nimroz Airport",
   :icao=>"",
   :city=>"Nimroz",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Nimroz, Afghanistan"},
 "IRD"=>
  {:iata=>"IRD",
   :name=>"Ishhurdi Airport",
   :icao=>"VGIS",
   :city=>"Ishhurdi",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Ishhurdi, Bangladesh"},
 "IQM"=>
  {:iata=>"IQM",
   :name=>"Qiemo Airport",
   :icao=>"ZWCM",
   :city=>"Qiemo",
   :country=>'China', :country_code=>'CN',
   :location=>"Qiemo, Xinjiang, China"},
 "IQN"=>
  {:iata=>"IQN",
   :name=>"Qingyang Airport",
   :icao=>"ZLQY",
   :city=>"Qingyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Qingyang, Gansu, China"},
 "INC"=>
  {:iata=>"INC",
   :name=>"Yinchuan Airport (Hedong Airport)",
   :icao=>"ZLIC",
   :city=>"Yinchuan",
   :country=>'China', :country_code=>'CN',
   :location=>"Yinchuan, Ningxia, China"},
 "IXA"=>
  {:iata=>"IXA",
   :name=>"Agartala Airport (Singerbhil Airport)",
   :icao=>"VEAT",
   :city=>"Agartala",
   :country=>"India",
:country_code=>"IN",
   :location=>"Agartala, India"},
 "IXD"=>
  {:iata=>"IXD",
   :name=>"Allahabad Airport / Bamrauli Air Force Base",
   :icao=>"VIAL",
   :city=>"Allahabad",
   :country=>"India",
:country_code=>"IN",
   :location=>"Allahabad, India"},
 "IXU"=>
  {:iata=>"IXU",
   :name=>"Aurangabad Airport (Chikkalthana Airport)",
   :icao=>"VAAU",
   :city=>"Aurangabad",
   :country=>"India",
:country_code=>"IN",
   :location=>"Aurangabad, Maharashtra, India"},
 "IXB"=>
  {:iata=>"IXB",
   :name=>"Bagdogra Airport",
   :icao=>"VEBD",
   :city=>"Bagdogra",
   :country=>"India",
:country_code=>"IN",
   :location=>"Bagdogra, India"},
 "IXG"=>
  {:iata=>"IXG",
   :name=>"Belgaum Airport",
   :icao=>"VABM",
   :city=>"Belgaum",
   :country=>"India",
:country_code=>"IN",
   :location=>"Belgaum, India"},
 "IXC"=>
  {:iata=>"IXC",
   :name=>"Chandigarh Airport",
   :icao=>"VICG",
   :city=>"Chandigarh",
   :country=>"India",
:country_code=>"IN",
   :location=>"Chandigarh, India"},
 "IMF"=>
  {:iata=>"IMF",
   :name=>"Tulihal Airport",
   :icao=>"VEIM",
   :city=>"Imphal",
   :country=>"India",
:country_code=>"IN",
   :location=>"Imphal, India"},
 "IDR"=>
  {:iata=>"IDR",
   :name=>"Devi Ahilyabai Holkar International Airport",
   :icao=>"VAID",
   :city=>"Indore",
   :country=>"India",
:country_code=>"IN",
   :location=>"Indore, Madhya Pradesh, India"},
 "IXJ"=>
  {:iata=>"IXJ",
   :name=>"Jammu Airport (Satwari Airport)",
   :icao=>"VIJU",
   :city=>"Jammu",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jammu, India"},
 "IXY"=>
  {:iata=>"IXY",
   :name=>"Kandla Airport (Gandhidham Airport)",
   :icao=>"VAKE",
   :city=>"Gandhidham / Kandla",
   :country=>"India",
:country_code=>"IN",
   :location=>"Gandhidham / Kandla, India"},
 "IXL"=>
  {:iata=>"IXL",
   :name=>"Leh Kushok Bakula Rimpochee Airport",
   :icao=>"VILH",
   :city=>"Leh",
   :country=>"India",
:country_code=>"IN",
   :location=>"Leh, India"},
 "IXI"=>
  {:iata=>"IXI",
   :name=>"Lilabari Airport (North Lakhimpur Airport)",
   :icao=>"VELR",
   :city=>"Assam",
   :country=>"India",
:country_code=>"IN",
   :location=>"Assam, India"},
 "IXM"=>
  {:iata=>"IXM",
   :name=>"Madurai Airport",
   :icao=>"VOMD",
   :city=>"Madurai",
   :country=>"India",
:country_code=>"IN",
   :location=>"Madurai, India"},
 "IXE"=>
  {:iata=>"IXE",
   :name=>"Mangalore International Airport",
   :icao=>"VOML",
   :city=>"Mangalore",
   :country=>"India",
:country_code=>"IN",
   :location=>"Mangalore, India"},
 "ISK"=>
  {:iata=>"ISK",
   :name=>"Ozar Airport",
   :icao=>"VAOZ",
   :city=>"Nashik",
   :country=>"India",
:country_code=>"IN",
   :location=>"Nashik, India"},
 "IXP"=>
  {:iata=>"IXP",
   :name=>"Pathankot Airport",
   :icao=>"VIPK",
   :city=>"Pathankot",
   :country=>"India",
:country_code=>"IN",
   :location=>"Pathankot, India"},
 "IXZ"=>
  {:iata=>"IXZ",
   :name=>"Vir Savarkar Airport (Port Blair Airport)",
   :icao=>"VOPB",
   :city=>"Port Blair",
   :country=>"India",
:country_code=>"IN",
   :location=>"Port Blair, India"},
 "IXR"=>
  {:iata=>"IXR",
   :name=>"Birsa Munda Airport (Ranchi Airport)",
   :icao=>"VERC",
   :city=>"Ranchi",
   :country=>"India",
:country_code=>"IN",
   :location=>"Ranchi, India"},
 "IXS"=>
  {:iata=>"IXS",
   :name=>"Silchar Airport (Kumbhirgram Airport)",
   :icao=>"VEKU",
   :city=>"Silchar",
   :country=>"India",
:country_code=>"IN",
   :location=>"Silchar, India"},
 "IXV"=>
  {:iata=>"IXV",
   :name=>"Along Airport",
   :icao=>"VEAN",
   :city=>"Along",
   :country=>"India",
:country_code=>"IN",
   :location=>"Along, Arunachal Pradesh, India"},
 "IXW"=>
  {:iata=>"IXW",
   :name=>"Sonari Airport",
   :icao=>"VEJS",
   :city=>"Jamshedpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Jamshedpur, India"},
 "IXH"=>
  {:iata=>"IXH",
   :name=>"Kailashahar Airport",
   :icao=>"VEKR",
   :city=>"Kailashahar",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kailashahar, India"},
 "IXQ"=>
  {:iata=>"IXQ",
   :name=>"Kamalpur Airport",
   :icao=>"VEKM",
   :city=>"Kamalpur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Kamalpur, India"},
 "IXK"=>
  {:iata=>"IXK",
   :name=>"Junagadh Airport (Keshod Airport)",
   :icao=>"VAKS",
   :city=>"Keshod",
   :country=>"India",
:country_code=>"IN",
   :location=>"Keshod, India"},
 "IXN"=>
  {:iata=>"IXN",
   :name=>"Khowai Airport",
   :icao=>"VEKW",
   :city=>"Khowai",
   :country=>"India",
:country_code=>"IN",
   :location=>"Khowai, India"},
 "IXT"=>
  {:iata=>"IXT",
   :name=>"Pasighat Airport (Passighat Airport)",
   :icao=>"VEPG",
   :city=>"Pasighat (Passighat)",
   :country=>"India",
:country_code=>"IN",
   :location=>"Pasighat (Passighat), India"},
 "ILA"=>
  {:iata=>"ILA",
   :name=>"Illaga Airport",
   :icao=>"WABL",
   :city=>"Illaga",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Illaga, Indonesia"},
 "IUL"=>
  {:iata=>"IUL",
   :name=>"Ilu Airport",
   :icao=>"",
   :city=>"Ilu",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ilu, Indonesia"},
 "INX"=>
  {:iata=>"INX",
   :name=>"Inanwatan Airport",
   :icao=>"WASI",
   :city=>"Inanwatan",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Inanwatan, Indonesia"},
 "IIL"=>
  {:iata=>"IIL",
   :name=>"Ilaam Airport",
   :city=>"Ilaam",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Ilaam, Iran"},
 "IHR"=>
  {:iata=>"IHR",
   :name=>"Iran Shahr Airport",
   :city=>"Iran Shahr",
   :icao=>"OIZI",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Iran Shahr, Iran"},
 "IFN"=>
  {:iata=>"IFN",
   :name=>"Esfahan Shahid Beheshti International Airport",
   :icao=>"OIFM",
   :city=>"Isfahan",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Isfahan, Iran"},
 "IKA"=>
  {:iata=>"IKA",
   :name=>"Tehran Imam Khomeini International Airport",
   :icao=>"OIIE",
   :city=>"Tehran",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Tehran, Iran"},
 "IAQ"=>
  {:iata=>"IAQ",
   :name=>"Bahregan Airport",
   :icao=>"",
   :city=>"Bahregan",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Bahregan, Iran"},
 "IFH"=>
  {:iata=>"IFH",
   :name=>"Hesa Airport",
   :city=>"Hesa",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Hesa, Iran"},
 "ITM"=>
  {:iata=>"ITM",
   :name=>"Osaka International Airport (Itami Airport)",
   :icao=>"RJOO",
   :city=>"Itami (near Osaka)",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Itami (near Osaka), Japan"},
 "IKI"=>
  {:iata=>"IKI",
   :name=>"Iki Airport",
   :icao=>"RJDB",
   :city=>"Iki",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Iki, Iki Island, Japan"},
 "ISG"=>
  {:iata=>"ISG",
   :name=>"Ishigaki Airport",
   :icao=>"ROIG",
   :city=>"Ishigaki",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Ishigaki, Okinawa Prefecture, Japan"},
 "IWK"=>
  {:iata=>"IWK",
   :name=>"Iwakuni Kintaikyo Airport",
   :city=>"Iwakuni",
   :icao=>"RJOI",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Iwakuni, Japan"},
 "IWO"=>
  {:iata=>"IWO",
   :name=>"Iwo Jima Air Base",
   :icao=>"RJAW",
   :city=>"Iwo Jima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Iwo Jima, Bonin Islands, Japan"},
 "IZO"=>
  {:iata=>"IZO",
   :name=>"Izumo Airport",
   :icao=>"RJOC",
   :city=>"Izumo",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Izumo, Shimane, Japan"},
 "IWJ"=>
  {:iata=>"IWJ",
   :name=>"Iwami Airport (Hagi-Iwami Airport)",
   :icao=>"RJOW",
   :city=>"Masuda",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Masuda, Shimane, Japan, Japan"},
 "IBR"=>
  {:iata=>"IBR",
   :name=>"Ibaraki Airport",
   :city=>"Omitami",
   :icao=>"RJAH",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Omitami, Japan"},
 "IEJ"=>
  {:iata=>"IEJ",
   :name=>"Iejima Airport",
   :icao=>"RORE",
   :city=>"Iejima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Iejima, Japan"},
 "IHA"=>
  {:iata=>"IHA",
   :name=>"Niihama Airport",
   :icao=>"",
   :city=>"Niihama",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Niihama, Shikoku, Japan"},
 "IIN"=>
  {:iata=>"IIN",
   :name=>"Nishinoomote Airport",
   :icao=>"",
   :city=>"Nishinoomote",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Nishinoomote, Osumi Islands, Japan"},
 "IPH"=>
  {:iata=>"IPH",
   :name=>"Sultan Azlan Shah Airport",
   :icao=>"WMKI",
   :city=>"Ipoh",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Ipoh, Perak, Malaysia"},
 "IMK"=>
  {:iata=>"IMK",
   :name=>"Simikot Airport",
   :icao=>"VNST",
   :city=>"Simikot",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Simikot, Nepal"},
 "ISB"=>
  {:iata=>"ISB",
   :name=>"Benazir Bhutto International Airport (Islamabad International)",
   :icao=>"OPRN",
   :city=>"Islamabad / Rawalpindi",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Islamabad / Rawalpindi, Pakistan"},
 "IMA"=>
  {:iata=>"IMA",
   :name=>"Iamalele Airport",
   :icao=>"",
   :city=>"Iamalele",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Iamalele, Papua New Guinea"},
 "IAU"=>
  {:iata=>"IAU",
   :name=>"Iaura Airport",
   :icao=>"",
   :city=>"Iaura",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Iaura, Papua New Guinea"},
 "IBI"=>
  {:iata=>"IBI",
   :name=>"Iboki Airport",
   :icao=>"",
   :city=>"Iboki",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Iboki, Papua New Guinea"},
 "IHU"=>
  {:iata=>"IHU",
   :name=>"Ihu Airport",
   :icao=>"",
   :city=>"Ihu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Ihu, Papua New Guinea"},
 "IMN"=>
  {:iata=>"IMN",
   :name=>"Imane Airport",
   :icao=>"",
   :city=>"Imane",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Imane, Papua New Guinea"},
 "IMD"=>
  {:iata=>"IMD",
   :name=>"Imonda Airport",
   :icao=>"",
   :city=>"Imonda",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Imonda, Papua New Guinea"},
 "IDN"=>
  {:iata=>"IDN",
   :name=>"Indagen Airport",
   :icao=>"",
   :city=>"Indagen",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Indagen, Papua New Guinea"},
 "IUS"=>
  {:iata=>"IUS",
   :name=>"Inus Airport",
   :icao=>"",
   :city=>"Inus",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Inus, Papua New Guinea"},
 "IOK"=>
  {:iata=>"IOK",
   :name=>"Iokea Airport",
   :icao=>"",
   :city=>"Iokea",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Iokea, Papua New Guinea"},
 "IOP"=>
  {:iata=>"IOP",
   :name=>"Ioma Airport",
   :icao=>"",
   :city=>"Ioma",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Ioma, Papua New Guinea"},
 "ITK"=>
  {:iata=>"ITK",
   :name=>"Itokama Airport",
   :icao=>"",
   :city=>"Itokama",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Itokama, Papua New Guinea"},
 "IIS"=>
  {:iata=>"IIS",
   :name=>"Nissan Island Airport",
   :icao=>"",
   :city=>"Nissan Island",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Nissan Island, Papua New Guinea"},
 "IAO"=>
  {:iata=>"IAO",
   :name=>"Sayak Airport",
   :city=>"Del Carmin",
   :icao=>"RPNS",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Del Carmin, Philippines"},
 "ILO"=>
  {:iata=>"ILO",
   :name=>"Iloilo International Airport",
   :icao=>"RPVI",
   :city=>"Cabatuan / Santa Barbara",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Cabatuan / Santa Barbara, Iloilo, Philippines"},
 "IGN"=>
  {:iata=>"IGN",
   :name=>"Maria Cristina Airport (Iligan Airport)",
   :icao=>"RPMI",
   :city=>"Baloi",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Baloi, Lanao del Norte, Philippines"},
 "IPE"=>
  {:iata=>"IPE",
   :name=>"Ipil Airport",
   :icao=>"RPMV",
   :city=>"Ipil",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Ipil, Zamboanga Sibugay, Philippines"},
 "ICO"=>
  {:iata=>"ICO",
   :name=>"Sicogon Airport",
   :icao=>"RPSG",
   :city=>"Carles",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Carles, Iloilo, Philippines"},
 "ICN"=>
  {:iata=>"ICN",
   :name=>"Incheon International Airport",
   :icao=>"RKSI",
   :city=>"Incheon (near Seoul)",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Incheon (near Seoul), South Korea"},
 "INB"=>
  {:iata=>"INB",
   :name=>"Independence Airport",
   :icao=>"",
   :city=>"Independence",
   :country=>'Belize', :country_code=>'BZ',
   :location=>"Independence, Belize"},
 "IRN"=>
  {:iata=>"IRN",
   :name=>"Iriona Airport",
   :icao=>"",
   :city=>"Iriona",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Iriona, Honduras"},
 "ISU"=>
  {:iata=>"ISU",
   :name=>"Sulaimaniyah International Airport",
   :icao=>"ORSU",
   :city=>"Sulaimaniyah",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Sulaimaniyah, Kurdistan, Iraq"},
 "IHN"=>
  {:iata=>"IHN",
   :name=>"Qishn Airport",
   :icao=>"OYQN",
   :city=>"Qishn",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Qishn, Yemen"},
 "IAB"=>
  {:iata=>"IAB",
   :name=>"McConnell Air Force Base",
   :icao=>"KIAB",
   :city=>"Wichita",
   :country=>'United States', :country_code=>'US',

   :location=>"Wichita, Kansas, United States"},
 "IAD"=>
  {:iata=>"IAD",
   :name=>"Washington Dulles International Airport",
   :icao=>"KIAD",
   :city=>"Washington",
   :country=>'United States', :country_code=>'US',

   :location=>"Washington, D.C. / Virginia, United States"},
 "IAG"=>
  {:iata=>"IAG",
   :name=>"Niagara Falls International Airport",
   :icao=>"KIAG",
   :city=>"Niagara Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Niagara Falls, New York, United States"},
 "IAH"=>
  {:iata=>"IAH",
   :name=>"George Bush Intercontinental Airport",
   :icao=>"KIAH",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "IAL"=>
  {:iata=>"IAL",
   :name=>"Ialibu Airport",
   :icao=>"",
   :city=>"Ialibu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Ialibu, Papua New Guinea"},
 "IAN"=>
  {:iata=>"IAN",
   :name=>"Bob Baker Memorial Airport",
   :icao=>"PAIK",
   :city=>"Kiana",
   :country=>'United States', :country_code=>'US',

   :location=>"Kiana, Alaska, United States"},
 "IBL"=>
  {:iata=>"IBL",
   :name=>"Indigo Bay Lodge Airport",
   :icao=>"",
   :city=>"Bazaruto Island",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Bazaruto Island, Mozambique"},
 "ICL"=>
  {:iata=>"ICL",
   :name=>"Schenck Field",
   :icao=>"KICL",
   :city=>"Clarinda",
   :country=>'United States', :country_code=>'US',

   :location=>"Clarinda, Iowa, United States"},
 "ICT"=>
  {:iata=>"ICT",
   :name=>"Wichita Mid-Continent Airport",
   :icao=>"KICT",
   :city=>"Wichita",
   :country=>'United States', :country_code=>'US',

   :location=>"Wichita, Kansas, United States"},
 "ICY"=>
  {:iata=>"ICY",
   :name=>"Icy Bay Airport (FAA: 19AK)",
   :icao=>"",
   :city=>"Icy Bay",
   :country=>'United States', :country_code=>'US',

   :location=>"Icy Bay, Alaska, United States"},
 "IDA"=>
  {:iata=>"IDA",
   :name=>"Idaho Falls Regional Airport",
   :icao=>"KIDA",
   :city=>"Idaho Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Idaho Falls, Idaho, United States"},
 "IDG"=>
  {:iata=>"IDG",
   :name=>"Ida Grove Municipal Airport",
   :icao=>"KIDG",
   :city=>"Ida Grove",
   :country=>'United States', :country_code=>'US',

   :location=>"Ida Grove, Iowa, United States"},
 "IDI"=>
  {:iata=>"IDI",
   :name=>"Indiana County Airport (Jimmy Stewart Field)",
   :icao=>"KIDI",
   :city=>"Indiana",
   :country=>'United States', :country_code=>'US',

   :location=>"Indiana, Pennsylvania, United States"},
 "IDP"=>
  {:iata=>"IDP",
   :name=>"Independence Municipal Airport",
   :icao=>"KIDP",
   :city=>"Independence",
   :country=>'United States', :country_code=>'US',

   :location=>"Independence, Kansas, United States"},
 "IFA"=>
  {:iata=>"IFA",
   :name=>"Iowa Falls Municipal Airport",
   :icao=>"KIFA",
   :city=>"Iowa Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Iowa Falls, Iowa, United States"},
 "IFP"=>
  {:iata=>"IFP",
   :name=>"Laughlin/Bullhead International Airport",
   :icao=>"KIFP",
   :city=>"Bullhead City",
   :country=>'United States', :country_code=>'US',

   :location=>"Bullhead City, Arizona, United States"},
 "IGG"=>
  {:iata=>"IGG",
   :name=>"Igiugig Airport",
   :icao=>"PAIG",
   :city=>"Igiugig",
   :country=>'United States', :country_code=>'US',

   :location=>"Igiugig, Alaska, United States"},
 "IGM"=>
  {:iata=>"IGM",
   :name=>"Kingman Airport",
   :icao=>"KIGM",
   :city=>"Kingman",
   :country=>'United States', :country_code=>'US',

   :location=>"Kingman, Arizona, United States"},
 "IGS"=>
  {:iata=>"IGS",
   :name=>"Ingolstadt Manching Airport",
   :icao=>"ETSI",
   :city=>"Ingolstadt",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Ingolstadt, Germany"},
 "IJX"=>
  {:iata=>"IJX",
   :name=>"Jacksonville Municipal Airport (not Imeson Field)",
   :icao=>"KIJX",
   :city=>"Jacksonville",
   :country=>'United States', :country_code=>'US',

   :location=>"Jacksonville, Illinois, United States"},
 "IKB"=>
  {:iata=>"IKB",
   :name=>"Wilkes County Airport (FAA: UKF)",
   :icao=>"KUKF",
   :city=>"North Wilkesboro",
   :country=>'United States', :country_code=>'US',

   :location=>"North Wilkesboro, North Carolina, United States"},
 "IKK"=>
  {:iata=>"IKK",
   :name=>"Greater Kankakee Airport",
   :icao=>"KIKK",
   :city=>"Kankakee",
   :country=>'United States', :country_code=>'US',

   :location=>"Kankakee, Illinois, United States"},
 "IKO"=>
  {:iata=>"IKO",
   :name=>"Nikolski Air Station",
   :icao=>"PAKO",
   :city=>"Nikolski",
   :country=>'United States', :country_code=>'US',

   :location=>"Nikolski, Alaska, United States"},
 "IKV"=>
  {:iata=>"IKV",
   :name=>"Ankeny Regional Airport",
   :icao=>"KIKV",
   :city=>"Ankeny",
   :country=>'United States', :country_code=>'US',

   :location=>"Ankeny, Iowa, United States"},
 "ILE"=>
  {:iata=>"ILE",
   :name=>"Skylark Field",
   :icao=>"KILE",
   :city=>"Killeen",
   :country=>'United States', :country_code=>'US',

   :location=>"Killeen, Texas, United States"},
 "ILG"=>
  {:iata=>"ILG",
   :name=>"New Castle Airport",
   :icao=>"KILG",
   :city=>"Wilmington",
   :country=>'United States', :country_code=>'US',

   :location=>"Wilmington, Delaware, United States"},
 "ILH"=>
  {:iata=>"ILH",
   :name=>"Illisheim Army Airfield",
   :icao=>"ETIK",
   :city=>"Illisheim",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Illisheim, Bavaria, Germany"},
 "ILI"=>
  {:iata=>"ILI",
   :name=>"Iliamna Airport",
   :icao=>"PAIL",
   :city=>"Iliamna",
   :country=>'United States', :country_code=>'US',

   :location=>"Iliamna, Alaska, United States"},
 "ILL"=>
  {:iata=>"ILL",
   :name=>"Willmar Municipal Airport (John L. Rice Field) (closed 2006)",
   :icao=>"KILL",
   :city=>"Willmar",
   :country=>'United States', :country_code=>'US',

   :location=>"Willmar, Minnesota, United States"},
 "ILM"=>
  {:iata=>"ILM",
   :name=>"Wilmington International Airport",
   :icao=>"KILM",
   :city=>"Wilmington",
   :country=>'United States', :country_code=>'US',

   :location=>"Wilmington, North Carolina, United States"},
 "ILN"=>
  {:iata=>"ILN",
   :name=>"Airborne Airpark",
   :icao=>"KILN",
   :city=>"Wilmington",
   :country=>'United States', :country_code=>'US',

   :location=>"Wilmington, Ohio, United States"},
 "ILX"=>
  {:iata=>"ILX",
   :name=>"Ileg Airport",
   :icao=>"",
   :city=>"Ileg",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Ileg, Papua New Guinea"},
 "IML"=>
  {:iata=>"IML",
   :name=>"Imperial Municipal Airport",
   :icao=>"KIML",
   :city=>"Imperial",
   :country=>'United States', :country_code=>'US',

   :location=>"Imperial, Nebraska, United States"},
 "IMM"=>
  {:iata=>"IMM",
   :name=>"Immokalee Airport",
   :icao=>"KIMM",
   :city=>"Immokalee",
   :country=>'United States', :country_code=>'US',

   :location=>"Immokalee, Florida, United States"},
 "IMT"=>
  {:iata=>"IMT",
   :name=>"Ford Airport",
   :icao=>"KIMT",
   :city=>"Iron Mountain / Kingsford",
   :country=>'United States', :country_code=>'US',

   :location=>"Iron Mountain / Kingsford, Michigan, United States"},
 "IND"=>
  {:iata=>"IND",
   :name=>"Indianapolis International Airport",
   :icao=>"KIND",
   :city=>"Indianapolis",
   :country=>'United States', :country_code=>'US',

   :location=>"Indianapolis, Indiana, United States"},
 "INK"=>
  {:iata=>"INK",
   :name=>"Winkler County Airport",
   :icao=>"KINK",
   :city=>"Wink",
   :country=>'United States', :country_code=>'US',

   :location=>"Wink, Texas, United States"},
 "INL"=>
  {:iata=>"INL",
   :name=>"Falls International Airport",
   :icao=>"KINL",
   :city=>"International Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"International Falls, Minnesota, United States"},
 "INR"=>
  {:iata=>"INR",
   :name=>"Kincheloe Air Force Base (closed 1977)",
   :icao=>"",
   :city=>"Sault Ste. Marie",
   :country=>'United States', :country_code=>'US',

   :location=>"Sault Ste. Marie, Michigan, United States"},
 "INS"=>
  {:iata=>"INS",
   :name=>"Creech Air Force Base",
   :icao=>"KINS",
   :city=>"Indian Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Indian Springs, Nevada, United States"},
 "INT"=>
  {:iata=>"INT",
   :name=>"Smith Reynolds Airport",
   :icao=>"KINT",
   :city=>"Winston-Salem",
   :country=>'United States', :country_code=>'US',

   :location=>"Winston-Salem, North Carolina, United States"},
 "INW"=>
  {:iata=>"INW",
   :name=>"Winslow-Lindbergh Regional Airport",
   :icao=>"KINW",
   :city=>"Winslow",
   :country=>'United States', :country_code=>'US',

   :location=>"Winslow, Arizona, United States"},
 "IOW"=>
  {:iata=>"IOW",
   :name=>"Iowa City Municipal Airport",
   :icao=>"KIOW",
   :city=>"Iowa City",
   :country=>'United States', :country_code=>'US',

   :location=>"Iowa City, Iowa, United States"},
 "IPL"=>
  {:iata=>"IPL",
   :name=>"Imperial County Airport",
   :icao=>"KIPL",
   :city=>"Imperial",
   :country=>'United States', :country_code=>'US',

   :location=>"Imperial, California, United States"},
 "IPT"=>
  {:iata=>"IPT",
   :name=>"Williamsport Regional Airport",
   :icao=>"KIPT",
   :city=>"Williamsport",
   :country=>'United States', :country_code=>'US',

   :location=>"Williamsport, Pennsylvania, United States"},
 "IRB"=>
  {:iata=>"IRB",
   :name=>"Iraan Municipal Airport (FAA: 2F0)",
   :icao=>"",
   :city=>"Iraan",
   :country=>'United States', :country_code=>'US',

   :location=>"Iraan, Texas, United States"},
 "IRC"=>
  {:iata=>"IRC",
   :name=>"Circle City (New) Airport (FAA: CRC)",
   :icao=>"PACR",
   :city=>"Circle",
   :country=>'United States', :country_code=>'US',

   :location=>"Circle, Alaska, United States"},
 "IRK"=>
  {:iata=>"IRK",
   :name=>"Kirksville Regional Airport",
   :icao=>"KIRK",
   :city=>"Kirksville",
   :country=>'United States', :country_code=>'US',

   :location=>"Kirksville, Missouri, United States"},
 "IRS"=>
  {:iata=>"IRS",
   :name=>"Kirsch Municipal Airport",
   :icao=>"KIRS",
   :city=>"Sturgis",
   :country=>'United States', :country_code=>'US',

   :location=>"Sturgis, Michigan, United States"},
 "IRU"=>
  {:iata=>"IRU",
   :name=>"Iranamadu Waterdrome",
   :icao=>"",
   :city=>"Kilinochchi",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Kilinochchi, Sri Lanka"},
 "ISM"=>
  {:iata=>"ISM",
   :name=>"Kissimmee Gateway Airport",
   :icao=>"KISM",
   :city=>"Orlando",
   :country=>'United States', :country_code=>'US',

   :location=>"Orlando, Florida, United States"},
 "ISN"=>
  {:iata=>"ISN",
   :name=>"Sloulin Field International Airport",
   :icao=>"KISN",
   :city=>"Williston",
   :country=>'United States', :country_code=>'US',

   :location=>"Williston, North Dakota, United States"},
 "ISO"=>
  {:iata=>"ISO",
   :name=>"Kinston Regional Jetport at Stallings Field",
   :icao=>"KISO",
   :city=>"Kinston",
   :country=>'United States', :country_code=>'US',

   :location=>"Kinston, North Carolina, United States"},
 "ISP"=>
  {:iata=>"ISP",
   :name=>"Long Island MacArthur Airport",
   :icao=>"KISP",
   :city=>"Islip",
   :country=>'United States', :country_code=>'US',

   :location=>"Islip, New York, United States"},
 "ISQ"=>
  {:iata=>"ISQ",
   :name=>"Schoolcraft County Airport",
   :icao=>"KISQ",
   :city=>"Manistique",
   :country=>'United States', :country_code=>'US',

   :location=>"Manistique, Michigan, United States"},
 "ISS"=>
  {:iata=>"ISS",
   :name=>"Wiscasset Airport (FAA: IWI)",
   :icao=>"KIWI",
   :city=>"Wiscasset",
   :country=>'United States', :country_code=>'US',

   :location=>"Wiscasset, Maine, United States"},
 "ISW"=>
  {:iata=>"ISW",
   :name=>"South Wood County Airport (Alexander Field)",
   :icao=>"KISW",
   :city=>"Wisconsin Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Wisconsin Rapids, Wisconsin, United States"},
 "ITH"=>
  {:iata=>"ITH",
   :name=>"Ithaca Tompkins Regional Airport",
   :icao=>"KITH",
   :city=>"Ithaca",
   :country=>'United States', :country_code=>'US',

   :location=>"Ithaca, New York, United States"},
 "ITJ"=>
  {:iata=>"ITJ",
   :name=>"Itajaí Airport",
   :icao=>"",
   :city=>"Itajaí",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Itajaí, Santa Catarina, Brazil"},
 "ITO"=>
  {:iata=>"ITO",
   :name=>"Hilo International Airport",
   :icao=>"PHTO",
   :city=>"Hilo",
   :country=>'United States', :country_code=>'US',

   :location=>"Hilo, Hawaii, United States"},
 "IUD"=>
  {:iata=>"IUD",
   :name=>"Al Udeid Air Base",
   :icao=>"OTBH",
   :city=>"Doha",
   :country=>'Qatar', :country_code=>'QA',
   :location=>"Doha, Qatar"},
 "IWD"=>
  {:iata=>"IWD",
   :name=>"Gogebic-Iron County Airport",
   :icao=>"KIWD",
   :city=>"Ironwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Ironwood, Michigan, United States"},
 "IWS"=>
  {:iata=>"IWS",
   :name=>"West Houston Airport",
   :icao=>"KIWS",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',

   :location=>"Houston, Texas, United States"},
 "IYK"=>
  {:iata=>"IYK",
   :name=>"Inyokern Airport",
   :icao=>"KIYK",
   :city=>"Inyokern",
   :country=>'United States', :country_code=>'US',

   :location=>"Inyokern, California, United States"}}

end
