# encoding: UTF-8
def airp_19
  {"REX"=>
  {:iata=>"REX",
   :name=>"General Lucio Blanco International Airport",
   :icao=>"MMRX",
   :city=>"Reynosa",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Reynosa, Mexico"},
 "RWL"=>
  {:iata=>"RWL",
   :name=>"Rawlins Municipal Airport (Harvey Field)",
   :icao=>"KRWL",
   :city=>"Rawlins",
   :country=>'United States', :country_code=>'US',

   :location=>"Rawlins, Wyoming, United States"},
 "RIW"=>
  {:iata=>"RIW",
   :name=>"Riverton Regional Airport",
   :icao=>"KRIW",
   :city=>"Riverton",
   :country=>'United States', :country_code=>'US',

   :location=>"Riverton, Wyoming, United States"},
 "RKS"=>
  {:iata=>"RKS",
   :name=>"Rock Springs – Sweetwater County Airport",
   :icao=>"KRKS",
   :city=>"Rock Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Rock Springs, Wyoming, United States"},
 "RES"=>
  {:iata=>"RES",
   :name=>"Resistencia International Airport",
   :icao=>"SARE",
   :city=>"Resistencia",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Resistencia, Chaco, Argentina"},
 "RCU"=>
  {:iata=>"RCU",
   :name=>"Aeropuerto de Río Cuarto",
   :icao=>"SAOC",
   :city=>"Río Cuarto",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Río Cuarto, Córdoba, Argentina"},
 "RGL"=>
  {:iata=>"RGL",
   :name=>"Piloto Civil Norberto Fernández International Airport",
   :icao=>"SAWG",
   :city=>"Río Gallegos",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Río Gallegos, Santa Cruz, Argentina"},
 "RGA"=>
  {:iata=>"RGA",
   :name=>"Hermes Quijada International Airport",
   :icao=>"SAWE",
   :city=>"Río Grande",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Río Grande, Tierra del Fuego, Argentina"},
 "RYO"=>
  {:iata=>"RYO",
   :name=>"Rio Turbio Airport",
   :city=>"Rio Turbio",
   :icao=>"SAWT",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Rio Turbio, Argentina"},
 "ROS"=>
  {:iata=>"ROS",
   :name=>"Rosario - Islas Malvinas International Airport",
   :icao=>"SAAR",
   :city=>"Rosario",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Rosario, Argentina"},
 "RZA"=>
  {:iata=>"RZA",
   :name=>"Santa Cruz Airport",
   :city=>"Santa Cruz",
   :icao=>"SAWU",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Santa Cruz, Argentina"},
 "RSA"=>
  {:iata=>"RSA",
   :name=>"Santa Rosa Airport",
   :icao=>"SAZR",
   :city=>"Santa Rosa",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Santa Rosa, Argentina"},
 "REL"=>
  {:iata=>"REL",
   :name=>"Almirante Marco Andrés Zar Airport",
   :icao=>"SAVT",
   :city=>"Trelew",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Trelew, Chubut, Argentina"},
 "RLO"=>
  {:iata=>"RLO",
   :name=>"Aeropuerto Internacional Valle del Mercosur S.A.",
   :city=>"Merlo",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Merlo, Argentina"},
 "RCQ"=>
  {:iata=>"RCQ",
   :name=>"Reconquista Airport",
   :icao=>"SATR",
   :city=>"Reconquista",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Reconquista, Santa Fe, Argentina"},
 "RDS"=>
  {:iata=>"RDS",
   :name=>"Rincon de Los Sauces Airport",
   :city=>"Rincon de Los Sauces",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Rincon de Los Sauces, Argentina"},
 "RHD"=>
  {:iata=>"RHD",
   :name=>"Rio Hondo Airport",
   :city=>"Rio Hondo",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Rio Hondo, Argentina"},
 "ROY"=>
  {:iata=>"ROY",
   :name=>"Rio Mayo Airport",
   :city=>"Rio Mayo",
   :icao=>"SAWM",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Rio Mayo, Argentina"},
 "RIB"=>
  {:iata=>"RIB",
   :name=>"Riberalta Airport",
   :icao=>"SLRI",
   :city=>"Riberalta",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Riberalta, Bolivia"},
 "RBQ"=>
  {:iata=>"RBQ",
   :name=>"Rurrenabaque Airport",
   :icao=>"SLRQ",
   :city=>"Rurrenabaque",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Rurrenabaque, Bolivia"},
 "REY"=>
  {:iata=>"REY",
   :name=>"Reyes Airport",
   :city=>"Reyes",
   :icao=>"SLRY",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Reyes, Bolivia"},
 "RBO"=>
  {:iata=>"RBO",
   :name=>"Robore Airport",
   :city=>"Robore",
   :icao=>"SLRB",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Robore, Bolivia"},
 "REC"=>
  {:iata=>"REC",
   :name=>"Guararapes International Airport",
   :icao=>"SBRF",
   :city=>"Recife",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Recife, Brazil"},
 "REZ"=>
  {:iata=>"REZ",
   :name=>"Resende Airport",
   :city=>"Resende",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Resende, Brazil"},
 "RAO"=>
  {:iata=>"RAO",
   :name=>"Leite Lopes Airport",
   :icao=>"SBRP",
   :city=>"Ribeirão Preto",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ribeirão Preto, São Paulo, Brazil"},
 "RBR"=>
  {:iata=>"RBR",
   :name=>"Rio Branco International Airport (Presidente Medici Airport)",
   :icao=>"SBRB",
   :city=>"Rio Branco",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rio Branco, Acre, Brazil"},
 "RIG"=>
  {:iata=>"RIG",
   :name=>"Rio Grande Airport",
   :icao=>"SBRG",
   :city=>"Rio Grande",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rio Grande, Brazil"},
 "RVD"=>
  {:iata=>"RVD",
   :name=>"Rio Verde Airport",
   :city=>"Rio Verde",
   :icao=>"SWLC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rio Verde, Brazil"},
 "ROO"=>
  {:iata=>"ROO",
   :name=>"Rondonopolis Airport",
   :city=>"Rondonopolis",
   :icao=>"SWRD",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rondonopolis, Brazil"},
 "RIA"=>
  {:iata=>"RIA",
   :name=>"Santa Maria Airport",
   :icao=>"SBSM",
   :city=>"Santa Maria",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Santa Maria, Rio Grande do Sul, Brazil"},
 "RBB"=>
  {:iata=>"RBB",
   :name=>"Borba Airport",
   :icao=>"SWBR",
   :city=>"Borba",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Borba, Amazonas, Brazil"},
 "RDC"=>
  {:iata=>"RDC",
   :name=>"Redencao Airport",
   :city=>"Redencao",
   :icao=>"SNDC",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Redencao, Brazil"},
 "RRN"=>
  {:iata=>"RRN",
   :name=>"Serra Do Norte Airport",
   :city=>"Serra Do Norte",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Serra Do Norte, Brazil"},
 "RSG"=>
  {:iata=>"RSG",
   :name=>"Serra Pelada Airport",
   :city=>"Serra Pelada",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Serra Pelada, Brazil"},
 "RWS"=>
  {:iata=>"RWS",
   :name=>"Sumare Airport",
   :city=>"Sumare",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Sumare, Brazil"},
 "RCH"=>
  {:iata=>"RCH",
   :name=>"Almirante Padilla Airport",
   :icao=>"SKRH",
   :city=>"Riohacha",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Riohacha, Colombia"},
 "RVE"=>
  {:iata=>"RVE",
   :name=>"Los Colonizadores Airport",
   :icao=>"SKSA",
   :city=>"Saravena",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Saravena, Colombia"},
 "RAV"=>
  {:iata=>"RAV",
   :name=>"Cravo Norte Airport",
   :city=>"Cravo Norte",
   :icao=>"SKCN",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Cravo Norte, Colombia"},
 "RON"=>
  {:iata=>"RON",
   :name=>"Rondon Airport",
   :city=>"Rondon",
   :icao=>"",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Rondon, Colombia"},
 "REI"=>
  {:iata=>"REI",
   :name=>"Regina Airport",
   :city=>"Regina",
   :icao=>"",
   :country=>'Guiana', :country_code=>'',
   :location=>"Regina, Guiana"},
 "RIJ"=>
  {:iata=>"RIJ",
   :name=>"Rioja Airport",
   :city=>"Rioja",
   :icao=>"SBJA",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Rioja, Peru"},
 "RIM"=>
  {:iata=>"RIM",
   :name=>"Rodriguez De Mendoza Airport",
   :city=>"Rodriguez De Mendoza",
   :icao=>"SPLN",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Rodriguez De Mendoza, Peru"},
 "RVY"=>
  {:iata=>"RVY",
   :name=>"Pte. Gral. Óscar D. Gestido International Airport",
   :icao=>"SURV",
   :city=>"Rivera",
   :country=>"Uruguay",
:country_code=>"UY",
   :location=>"Rivera, Rivera, Uruguay"},
 "RVT"=>
  {:iata=>"RVT",
   :name=>"Ravensthorpe Airport",
   :city=>"Ravensthorpe",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ravensthorpe, Australia"},
 "RCM"=>
  {:iata=>"RCM",
   :name=>"Richmond Airport",
   :icao=>"YRMD",
   :city=>"Richmond",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Richmond, Queensland, Australia"},
 "ROK"=>
  {:iata=>"ROK",
   :name=>"Rockhampton Airport",
   :icao=>"YBRK",
   :city=>"Rockhampton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rockhampton, Queensland, Australia"},
 "RMA"=>
  {:iata=>"RMA",
   :name=>"Roma Airport",
   :city=>"Roma",
   :icao=>"YROM",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roma, Australia"},
 "RCN"=>
  {:iata=>"RCN",
   :name=>"American River Airport",
   :city=>"American River",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"American River, Australia"},
 "RRE"=>
  {:iata=>"RRE",
   :name=>"Marree Airport",
   :city=>"Marree",
   :icao=>"YMRE",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Marree, Australia"},
 "RTY"=>
  {:iata=>"RTY",
   :name=>"Merty Airport",
   :city=>"Merty",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Merty, Australia"},
 "RPM"=>
  {:iata=>"RPM",
   :name=>"Ngukurr Airport",
   :city=>"Ngukurr",
   :icao=>"YNGU",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ngukurr, Australia"},
 "RBS"=>
  {:iata=>"RBS",
   :name=>"Orbost Airport",
   :city=>"Orbost",
   :icao=>"YORB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Orbost, Australia"},
 "RAM"=>
  {:iata=>"RAM",
   :name=>"Ramingining Airport",
   :city=>"Ramingining",
   :icao=>"YRNG",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Ramingining, Australia"},
 "RMK"=>
  {:iata=>"RMK",
   :name=>"Renmark Airport",
   :icao=>"YREN",
   :city=>"Renmark",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Renmark, South Australia, Australia"},
 "ROH"=>
  {:iata=>"ROH",
   :name=>"Robinhood Airport",
   :city=>"Robinhood",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Robinhood, Australia"},
 "RRV"=>
  {:iata=>"RRV",
   :name=>"Robinson River Airport",
   :city=>"Robinson River",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Robinson River, Australia"},
 "RBC"=>
  {:iata=>"RBC",
   :name=>"Robinvale Airport",
   :icao=>"YROI",
   :city=>"Robinvale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Robinvale, Victoria, Australia"},
 "RDA"=>
  {:iata=>"RDA",
   :name=>"Rockhampton Downs Airport",
   :city=>"Rockhampton Downs",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rockhampton Downs, Australia"},
 "RBU"=>
  {:iata=>"RBU",
   :name=>"Roebourne Airport",
   :city=>"Roebourne",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roebourne, Australia"},
 "RKY"=>
  {:iata=>"RKY",
   :name=>"Rokeby Airport",
   :city=>"Rokeby",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rokeby, Australia"},
 "RPB"=>
  {:iata=>"RPB",
   :name=>"Roper Bar Airport",
   :icao=>"YRRB",
   :city=>"Roper Bar",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roper Bar, Northern Territory, Australia"},
 "RPV"=>
  {:iata=>"RPV",
   :name=>"Roper Valley Airport",
   :city=>"Roper Valley",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roper Valley, Australia"},
 "RSB"=>
  {:iata=>"RSB",
   :name=>"Roseberth Airport",
   :city=>"Roseberth",
   :icao=>"YRSB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roseberth, Australia"},
 "RLP"=>
  {:iata=>"RLP",
   :name=>"Rosella Plains Airport",
   :city=>"Rosella Plains",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rosella Plains, Australia"},
 "RTS"=>
  {:iata=>"RTS",
   :name=>"Rottnest Island Airport",
   :icao=>"YRTI",
   :city=>"Rottnest Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rottnest Island, Western Australia, Australia"},
 "RHL"=>
  {:iata=>"RHL",
   :name=>"Roy Hill Airport",
   :city=>"Roy Hill",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Roy Hill, Australia"},
 "RTP"=>
  {:iata=>"RTP",
   :name=>"Rutland Plains Airport",
   :city=>"Rutland Plains",
   :icao=>"YRTP",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Rutland Plains, Australia"},
 "RSE"=>
  {:iata=>"RSE",
   :name=>"Au-Rose Bay Airport",
   :city=>"Sydney",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Sydney, Australia"},
 "RAR"=>
  {:iata=>"RAR",
   :name=>"Rarotonga International Airport",
   :icao=>"NCRG",
   :city=>"Avarua",
   :country=>"Cook Islands",
:country_code=>"CK",
   :location=>"Avarua, Cook Islands"},
 "RTA"=>
  {:iata=>"RTA",
   :name=>"Rotuma Island Airport",
   :city=>"Rotuma Island",
   :icao=>"NFNR",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Rotuma Island, Fiji"},
 "RBI"=>
  {:iata=>"RBI",
   :name=>"Rabi Airport",
   :city=>"Rabi",
   :icao=>"",
   :country=>"Fiji",
:country_code=>"FJ",
   :location=>"Rabi, Fiji"},
 "RKA"=>
  {:iata=>"RKA",
   :name=>"Aratika-Nord Airport",
   :city=>"Aratika",
   :icao=>"NTKK",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Aratika, Polynesia"},
 "RFP"=>
  {:iata=>"RFP",
   :name=>"Raiatea Airport",
   :city=>"Raiatea",
   :icao=>"NTTR",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Raiatea, Polynesia"},
 "RVV"=>
  {:iata=>"RVV",
   :name=>"Raivavae Airport",
   :icao=>"",
   :city=>"Rairua",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Rairua, French Polynesia"},
 "RGI"=>
  {:iata=>"RGI",
   :name=>"Rangiroa Airport",
   :city=>"Rangiroa",
   :icao=>"NTTG",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Rangiroa, Polynesia"},
 "RRR"=>
  {:iata=>"RRR",
   :name=>"Raroia Airport",
   :icao=>"NTKO",
   :city=>"Raroia",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Raroia, French Polynesia"},
 "REA"=>
  {:iata=>"REA",
   :name=>"Reao Airport",
   :city=>"Reao, Tuamoto Island",
   :icao=>"NTGE",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Reao, Tuamoto Island, Polynesia"},
 "RMT"=>
  {:iata=>"RMT",
   :name=>"Rimatara Airport",
   :city=>"Rimatara",
   :icao=>"NTAM",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Rimatara, Polynesia"},
 "RUR"=>
  {:iata=>"RUR",
   :name=>"Rurutu Airport",
   :icao=>"NTAR",
   :city=>"Rurutu",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Rurutu, French Polynesia"},
 "RNP"=>
  {:iata=>"RNP",
   :name=>"Rongelap Airport",
   :icao=>"",
   :city=>"Rongelap Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Rongelap Atoll, Marshall Islands"},
 "ROT"=>
  {:iata=>"ROT",
   :name=>"Rotorua Airport",
   :icao=>"NZRO",
   :city=>"Rotorua",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Rotorua, New Zealand"},
 "RAG"=>
  {:iata=>"RAG",
   :name=>"Raglan Airfield",
   :city=>"Raglan",
   :icao=>"NZRA",
   :country=>'Zealand', :country_code=>'',
   :location=>"Raglan, Zealand"},
 "ROP"=>
  {:iata=>"ROP",
   :name=>"Rota International Airport (FAA: GRO)",
   :icao=>"PGRO",
   :city=>"Rota Island",
   :country=>'Northern Mariana Islands', :country_code=>'MP',
   :location=>"Rota Island, Northern Mariana Islands"},
 "ROR"=>
  {:iata=>"ROR",
   :name=>"Babelthuap Airport",
   :icao=>"PTRO",
   :city=>"Koror",
   :country=>'Palau', :country_code=>'PW',
   :location=>"Koror, Palau"},
 "RNA"=>
  {:iata=>"RNA",
   :name=>"Ulawa Airport",
   :icao=>"AGAR",
   :city=>"Arona",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Arona, Ulawa Island, Solomon Islands"},
 "RUS"=>
  {:iata=>"RUS",
   :name=>"Marau Sound Airport",
   :icao=>"",
   :city=>"Marau Sound",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Marau Sound, Solomon Islands"},
 "RBV"=>
  {:iata=>"RBV",
   :name=>"Ramata Airport",
   :city=>"Ramata",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Ramata, Islands"},
 "RNL"=>
  {:iata=>"RNL",
   :name=>"Rennell Airport",
   :city=>"Rennell",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Rennell, Islands"},
 "RRI"=>
  {:iata=>"RRI",
   :name=>"Barora Airport",
   :city=>"Barora",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Barora, Islands"},
 "RIN"=>
  {:iata=>"RIN",
   :name=>"Ringi Cove Airport",
   :city=>"Ringi Cove",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Ringi Cove, Islands"},
 "RCL"=>
  {:iata=>"RCL",
   :name=>"Redcliffe Airport",
   :city=>"Redcliffe",
   :icao=>"NVSR",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Redcliffe, Vanuatu"},
 "RSD"=>
  {:iata=>"RSD",
   :name=>"South Eleuthera Airport",
   :city=>"Rock Sound",
   :icao=>"MYER",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Rock Sound, Bahamas"},
 "RCY"=>
  {:iata=>"RCY",
   :name=>"New Port Nelson Airport",
   :city=>"Rum Cay",
   :icao=>"MYRP",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Rum Cay, Bahamas"},
 "RAD"=>
  {:iata=>"RAD",
   :name=>"Road Town Seaplane Base",
   :city=>"Tortola",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Tortola, Islands"},
 "RAI"=>
  {:iata=>"RAI",
   :name=>"Praia International Airport",
   :icao=>"GVNP",
   :city=>"Praia",
   :country=>'Cape Verde', :country_code=>'CV',
   :location=>"Praia, Cape Verde"},
 "RFA"=>
  {:iata=>"RFA",
   :name=>"Rafai Airport",
   :city=>"Rafai",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Rafai, Republic"},
 "RBT"=>
  {:iata=>"RBT",
   :name=>"Marsabit Airport",
   :city=>"Marsabit",
   :icao=>"HKMB",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Marsabit, Kenya"},
 "ROB"=>
  {:iata=>"ROB",
   :name=>"Roberts International Airport",
   :icao=>"GLRB",
   :city=>"Monrovia",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Monrovia, Liberia"},
 "RVC"=>
  {:iata=>"RVC",
   :name=>"Rivercess Airport",
   :city=>"Rivercess",
   :icao=>"",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Rivercess, Liberia"},
 "RVA"=>
  {:iata=>"RVA",
   :name=>"Farafangana Airport",
   :city=>"Farafangana",
   :icao=>"FMSG",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Farafangana, Madagascar"},
 "RLR"=>
  {:iata=>"RLR",
   :name=>"Relais de la Reine Airport",
   :city=>"Isalo",
   :icao=>"",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Isalo, Madagascar"},
 "RRG"=>
  {:iata=>"RRG",
   :name=>"Sir Gaëtan Duval Airport",
   :icao=>"FIMR",
   :city=>"Rodrigues Island",
   :country=>'Mauritius', :country_code=>'MU',
   :location=>"Rodrigues Island, Mauritius"},
 "RAK"=>
  {:iata=>"RAK",
   :name=>"Menara International Airport",
   :icao=>"GMMX",
   :city=>"Marrakech",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Marrakech, Morocco"},
 "RBA"=>
  {:iata=>"RBA",
   :name=>"Sale Airport",
   :icao=>"GMME",
   :city=>"Rabat",
   :country=>'Morocco', :country_code=>'MA',
   :location=>"Rabat, Morocco"},
 "RRM"=>
  {:iata=>"RRM",
   :name=>"Marromeu Airport",
   :city=>"Marromeu",
   :icao=>"",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Marromeu, Mozambique"},
 "RHN"=>
  {:iata=>"RHN",
   :name=>"Rosh Pina Airport",
   :city=>"Rosh Pina",
   :icao=>"",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Rosh Pina, Namibia"},
 "RLT"=>
  {:iata=>"RLT",
   :name=>"Arlit Airport",
   :icao=>"DRZL",
   :city=>"Arlit",
   :country=>'Niger', :country_code=>'NE',
   :location=>"Arlit, Niger"},
 "RUN"=>
  {:iata=>"RUN",
   :name=>"Roland Garros Airport",
   :icao=>"FMEE",
   :city=>"St Denis",
   :country=>'France', :country_code=>'FR',
   :location=>"St Denis, Réunion, France"},
 "RHG"=>
  {:iata=>"RHG",
   :name=>"Ruhengeri Airport",
   :city=>"Ruhengeri",
   :icao=>"HRYU",
   :country=>'Rwanda', :country_code=>'RW',
   :location=>"Ruhengeri, Rwanda"},
 "RDT"=>
  {:iata=>"RDT",
   :name=>"Richard Toll Airport",
   :icao=>"GOSR",
   :city=>"Richard Toll",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Richard Toll, Senegal"},
 "RCB"=>
  {:iata=>"RCB",
   :name=>"Richards Bay Airport",
   :icao=>"FARB",
   :city=>"Richards Bay",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Richards Bay, KwaZulu-Natal, South Africa"},
 "RVO"=>
  {:iata=>"RVO",
   :name=>"Reivilo Airport",
   :city=>"Reivilo",
   :icao=>"FARI",
   :country=>'Africa', :country_code=>'',
   :location=>"Reivilo, Africa"},
 "ROD"=>
  {:iata=>"ROD",
   :name=>"Robertson Airport",
   :city=>"Robertson",
   :icao=>"FARS",
   :country=>'Africa', :country_code=>'',
   :location=>"Robertson, Africa"},
 "RBX"=>
  {:iata=>"RBX",
   :name=>"Rumbek Airport",
   :city=>"Rumbek",
   :icao=>"HSMK",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Rumbek, Sudan"},
 "RSS"=>
  {:iata=>"RSS",
   :name=>"Roseires Airport",
   :city=>"Roseires",
   :icao=>"",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Roseires, Sudan"},
 "RUA"=>
  {:iata=>"RUA",
   :name=>"Arua Airport",
   :icao=>"HUAR",
   :city=>"Arua",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Arua, Uganda"},
 "ROU"=>
  {:iata=>"ROU",
   :name=>"Rousse Airport",
   :icao=>"LBRS",
   :city=>"Rousse",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Rousse, Bulgaria"},
 "RJK"=>
  {:iata=>"RJK",
   :name=>"Rijeka Airport",
   :icao=>"LDRI",
   :city=>"Rijeka",
   :country=>'Croatia', :country_code=>'HR',
   :location=>"Rijeka, Croatia"},
 "RNN"=>
  {:iata=>"RNN",
   :name=>"Bornholm Airport",
   :icao=>"EKRN",
   :city=>"Rønne",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Rønne, Denmark"},
 "RKE"=>
  {:iata=>"RKE",
   :name=>"Roskilde Airport",
   :icao=>"EKRK",
   :city=>"Roskilde (near Copenhagen)",
   :country=>'Denmark', :country_code=>'DK',
   :location=>"Roskilde (near Copenhagen), Denmark"},
 "RVN"=>
  {:iata=>"RVN",
   :name=>"Rovaniemi Airport",
   :icao=>"EFRO",
   :city=>"Rovaniemi",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Rovaniemi, Finland"},
 "RNS"=>
  {:iata=>"RNS",
   :name=>"St. Jacques Airport",
   :icao=>"LFRN",
   :city=>"Rennes",
   :country=>'France', :country_code=>'FR',
   :location=>"Rennes, France"},
 "RDZ"=>
  {:iata=>"RDZ",
   :name=>"Rodez-Marcillac Airport",
   :icao=>"LFCR",
   :city=>"Salles-La-Source",
   :country=>'France', :country_code=>'FR',
   :location=>"Salles-La-Source, Aveyron, France"},
 "RHE"=>
  {:iata=>"RHE",
   :name=>"Reims Champagne Airport",
   :icao=>"LFSR",
   :city=>"Reims",
   :country=>'France', :country_code=>'FR',
   :location=>"Reims, France"},
 "RNE"=>
  {:iata=>"RNE",
   :name=>"Renaison Airport",
   :icao=>"",
   :city=>"Renaison",
   :country=>'France', :country_code=>'FR',
   :location=>"Renaison, France"},
 "RCO"=>
  {:iata=>"RCO",
   :name=>"Saint Agnant Airport",
   :city=>"Rochefort",
   :icao=>"LFDN",
   :country=>'France', :country_code=>'FR',
   :location=>"Rochefort, France"},
 "RYN"=>
  {:iata=>"RYN",
   :name=>"Medis Airport",
   :icao=>"LFCY",
   :city=>"Royan",
   :country=>'France', :country_code=>'FR',
   :location=>"Royan, France"},
 "RMS"=>
  {:iata=>"RMS",
   :name=>"Ramstein Air Base",
   :icao=>"ETAR",
   :city=>"Ramstein",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Ramstein, Germany"},
 "RLG"=>
  {:iata=>"RLG",
   :name=>"Rostock Laage Airport",
   :icao=>"ETNL",
   :city=>"Rostock",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Rostock, Germany"},
 "REB"=>
  {:iata=>"REB",
   :name=>"Rechlin Airport",
   :city=>"Rechlin",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Rechlin, Germany"},
 "RBM"=>
  {:iata=>"RBM",
   :name=>"Straubing Wallmuhle Airport",
   :icao=>"EDMS",
   :city=>"Straubing",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Straubing, Bavaria, Germany"},
 "RHO"=>
  {:iata=>"RHO",
   :name=>"Rhodes International Airport",
   :icao=>"LGRP",
   :city=>"Rhodes",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Rhodes, Greece"},
 "RKV"=>
  {:iata=>"RKV",
   :name=>"Reykjavík Airport",
   :icao=>"BIRK",
   :city=>"Reykjavík",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Reykjavík, Iceland"},
 "RFN"=>
  {:iata=>"RFN",
   :name=>"Raufarhofn Airport",
   :city=>"Raufarhofn",
   :icao=>"BIRG",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Raufarhofn, Iceland"},
 "RHA"=>
  {:iata=>"RHA",
   :name=>"Reykholar Airport",
   :city=>"Reykholar",
   :icao=>"",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Reykholar, Iceland"},
 "REG"=>
  {:iata=>"REG",
   :name=>"Reggio Calabria Airport",
   :icao=>"LICR",
   :city=>"Reggio Calabria",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Reggio Calabria, Italy"},
 "RMI"=>
  {:iata=>"RMI",
   :name=>"Federico Fellini International Airport",
   :icao=>"LIPR",
   :city=>"Rimini",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Rimini, Italy"},
 "RAN"=>
  {:iata=>"RAN",
   :name=>"La Spreta Airport",
   :city=>"Ravenna",
   :icao=>"LIDR",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Ravenna, Italy"},
 "RRO"=>
  {:iata=>"RRO",
   :name=>"Sorrento Airport",
   :city=>"Sorrento",
   :icao=>"",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Sorrento, Italy"},
 "RIX"=>
  {:iata=>"RIX",
   :name=>"Riga International Airport",
   :icao=>"EVRA",
   :city=>"Riga",
   :country=>'Latvia', :country_code=>'LV',
   :location=>"Riga, Latvia"},
 "RTM"=>
  {:iata=>"RTM",
   :name=>"Rotterdam The Hague Airport",
   :icao=>"EHRD",
   :city=>"Rotterdam",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Rotterdam, Netherlands"},
 "RVK"=>
  {:iata=>"RVK",
   :name=>"Rørvik Airport, Ryum",
   :icao=>"ENRM",
   :city=>"Rørvik",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Rørvik, Norway"},
 "RRS"=>
  {:iata=>"RRS",
   :name=>"Røros Airport",
   :icao=>"ENRO",
   :city=>"Røros",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Røros, Norway"},
 "RET"=>
  {:iata=>"RET",
   :name=>"Røst Airport",
   :icao=>"ENRS",
   :city=>"Røst",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Røst, Nordland, Norway"},
 "RYG"=>
  {:iata=>"RYG",
   :name=>"Moss Airport, Rygge / Rygge Air Station",
   :icao=>"ENRY",
   :city=>"Rygge (near Moss)",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Rygge (near Moss), Norway"},
 "RZE"=>
  {:iata=>"RZE",
   :name=>"Rzeszów-Jasionka Airport",
   :icao=>"EPRZ",
   :city=>"Rzeszów",
   :country=>'Poland', :country_code=>'PL',
   :location=>"Rzeszów, Poland"},
 "RGK"=>
  {:iata=>"RGK",
   :name=>"Gorno-Altaysk Airport",
   :city=>"Gorno-Altaysk",
   :icao=>"UNBG",
   :country=>'Federation', :country_code=>'',
   :location=>"Gorno-Altaysk, Federation"},
 "REN"=>
  {:iata=>"REN",
   :name=>"Orenburg Tsentralny Airport",
   :icao=>"UWOO",
   :city=>"Orenburg",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Orenburg, Russia"},
 "ROV"=>
  {:iata=>"ROV",
   :name=>"Rostov-on-Don Airport",
   :icao=>"URRR",
   :city=>"Rostov-on-Don",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Rostov-on-Don, Russia"},
 "RTW"=>
  {:iata=>"RTW",
   :name=>"Saratov Tsentralny Airport",
   :icao=>"UWSS",
   :city=>"Saratov",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Saratov, Russia"},
 "RAT"=>
  {:iata=>"RAT",
   :name=>"Raduzhny Airport",
   :icao=>"USNR",
   :city=>"Raduzhny",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Raduzhny, Khanty-Mansi Autonomous Okrug, Russia"},
 "RZN"=>
  {:iata=>"RZN",
   :name=>"Turlatovo Airport",
   :icao=>"UUWR",
   :city=>"Ryazan",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ryazan, Russia"},
 "RYB"=>
  {:iata=>"RYB",
   :name=>"Staroselye Airport",
   :icao=>"UUBK",
   :city=>"Rybinsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Rybinsk, Yaroslavl Oblast, Russia"},
 "RVH"=>
  {:iata=>"RVH",
   :name=>"Rzhevka Airport",
   :icao=>"ULSS",
   :city=>"Saint Petersburg",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Saint Petersburg, Russia"},
 "RGS"=>
  {:iata=>"RGS",
   :name=>"Burgos Airport",
   :icao=>"LEBG",
   :city=>"Burgos",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Burgos, Spain"},
 "RJL"=>
  {:iata=>"RJL",
   :name=>"Logroño-Agoncillo Airport",
   :icao=>"LELO",
   :city=>"Logroño",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Logroño, Spain"},
 "REU"=>
  {:iata=>"REU",
   :name=>"Reus Airport",
   :icao=>"LERS",
   :city=>"Reus (near Tarragona)",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Reus (near Tarragona), Spain"},
 "RRA"=>
  {:iata=>"RRA",
   :name=>"Ronda Airport",
   :city=>"Ronda",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Ronda, Islands"},
 "RNB"=>
  {:iata=>"RNB",
   :name=>"Ronneby Airport",
   :icao=>"ESDF",
   :city=>"Ronneby",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Ronneby, Sweden"},
 "RWN"=>
  {:iata=>"RWN",
   :name=>"Rovno Airport",
   :icao=>"UKLR",
   :city=>"Rivne",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Rivne, Ukraine"},
 "RCS"=>
  {:iata=>"RCS",
   :name=>"Rochester Airport",
   :icao=>"EGTO",
   :city=>"Rochester",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Rochester, Kent, England, United Kingdom"},
 "RAY"=>
  {:iata=>"RAY",
   :name=>"Rothsay Heliport",
   :city=>"Rothsay",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Rothsay, Kingdom"},
 "RJH"=>
  {:iata=>"RJH",
   :name=>"Shah Makhdum Airport",
   :icao=>"VGRJ",
   :city=>"Rajshahi",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Rajshahi, Bangladesh"},
 "RAU"=>
  {:iata=>"RAU",
   :name=>"Rangpur Airport",
   :city=>"Rangpur",
   :icao=>"",
   :country=>'Bangladesh', :country_code=>'BD',
   :location=>"Rangpur, Bangladesh"},
 "REP"=>
  {:iata=>"REP",
   :name=>"Angkor International Airport",
   :icao=>"VDSR",
   :city=>"Siem Reap",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Siem Reap, Cambodia"},
 "RBE"=>
  {:iata=>"RBE",
   :name=>"Ratanakiri Airport",
   :icao=>"VDRK",
   :city=>"Ratanakiri",
   :country=>'Cambodia', :country_code=>'KH',
   :location=>"Ratanakiri, Cambodia"},
 "RHT"=>
  {:iata=>"RHT",
   :name=>"Alxa Right Banner Badanjilin Airport",
   :icao=>"",
   :city=>"Alxa Right Banner",
   :country=>'China', :country_code=>'CN',
   :location=>"Alxa Right Banner, Inner Mongolia, China"},
 "RLK"=>
  {:iata=>"RLK",
   :name=>"Bayannur Tianjitai Airport",
   :city=>"Bayannur",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Bayannur, China"},
 "RKZ"=>
  {:iata=>"RKZ",
   :name=>"Shigatse Peace Airport",
   :icao=>"ZURK",
   :city=>"Shigatse",
   :country=>'China', :country_code=>'CN',
   :location=>"Shigatse, Tibet Autonomous Region, China"},
 "RUG"=>
  {:iata=>"RUG",
   :name=>"Rugao Air Base",
   :icao=>"ZSRG",
   :city=>"Rugao",
   :country=>'China', :country_code=>'CN',
   :location=>"Rugao, Jiangsu, China"},
 "RPR"=>
  {:iata=>"RPR",
   :name=>"Raipur Airport",
   :icao=>"VARP",
   :city=>"Raipur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Raipur, India"},
 "RJA"=>
  {:iata=>"RJA",
   :name=>"Rajahmundry Airport",
   :city=>"Rajahmundry",
   :icao=>"VORY",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rajahmundry, India"},
 "RAJ"=>
  {:iata=>"RAJ",
   :name=>"Rajkot Airport",
   :icao=>"VARK",
   :city=>"Rajkot",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rajkot, India"},
 "RUP"=>
  {:iata=>"RUP",
   :name=>"Rupsi Airport",
   :icao=>"VERU",
   :city=>"Rupsi",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rupsi, Meghalaya, India"},
 "RGH"=>
  {:iata=>"RGH",
   :name=>"Balurghat Airport",
   :city=>"Balurghat",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Balurghat, India"},
 "RJI"=>
  {:iata=>"RJI",
   :name=>"Rajouri Airport",
   :city=>"Rajouri",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rajouri, India"},
 "RMD"=>
  {:iata=>"RMD",
   :name=>"Ramagundam Airport",
   :icao=>"VORG",
   :city=>"Ramagundam",
   :country=>"India",
:country_code=>"IN",
   :location=>"Ramagundam, Andhra Pradesh, India"},
 "RTC"=>
  {:iata=>"RTC",
   :name=>"Ratnagiri Airport",
   :icao=>"VARG",
   :city=>"Ratnagiri",
   :country=>"India",
:country_code=>"IN",
   :location=>"Ratnagiri, India"},
 "REW"=>
  {:iata=>"REW",
   :name=>"Rewa Airport",
   :city=>"Rewa",
   :icao=>"",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rewa, India"},
 "RRK"=>
  {:iata=>"RRK",
   :name=>"Rourkela Airport",
   :icao=>"VERK",
   :city=>"Rourkela",
   :country=>"India",
:country_code=>"IN",
   :location=>"Rourkela, India"},
 "RTG"=>
  {:iata=>"RTG",
   :name=>"Frans Sales Lega Airport",
   :city=>"Ruteng",
   :icao=>"WATG",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ruteng, Indonesia"},
 "RDE"=>
  {:iata=>"RDE",
   :name=>"Merdey Airport",
   :city=>"Merdey",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Merdey, Indonesia"},
 "RAQ"=>
  {:iata=>"RAQ",
   :name=>"Sugimanuru Airport",
   :city=>"Raha",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Raha, Indonesia"},
 "RSK"=>
  {:iata=>"RSK",
   :name=>"Ransiki Airport",
   :city=>"Ransiki",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ransiki, Indonesia"},
 "RGT"=>
  {:iata=>"RGT",
   :name=>"Japura Airport",
   :city=>"Rengat",
   :icao=>"WIPR",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Rengat, Indonesia"},
 "RKI"=>
  {:iata=>"RKI",
   :name=>"Rokot Airport",
   :icao=>"WIBR",
   :city=>"Sipura",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Sipura, Indonesia"},
 "RTI"=>
  {:iata=>"RTI",
   :name=>"Roti Airport",
   :city=>"Roti",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Roti, Indonesia"},
 "RKO"=>
  {:iata=>"RKO",
   :name=>"Sipora Airport",
   :city=>"Sipora",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Sipora, Indonesia"},
 "RUF"=>
  {:iata=>"RUF",
   :name=>"Yuruf, Irian Jaya Airport",
   :city=>"Yuruf, Irian Jaya",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Yuruf, Irian Jaya, Indonesia"},
 "RZR"=>
  {:iata=>"RZR",
   :name=>"Ramsar Airport",
   :city=>"Ramsar",
   :icao=>"OINR",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Ramsar, Iran"},
 "RAS"=>
  {:iata=>"RAS",
   :name=>"Rasht Airport",
   :city=>"Rasht",
   :icao=>"OIGG",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Rasht, Iran"},
 "RUD"=>
  {:iata=>"RUD",
   :name=>"Shahroud Airport",
   :city=>"Shahroud",
   :icao=>"OIMJ",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Shahroud, Iran"},
 "RJN"=>
  {:iata=>"RJN",
   :name=>"Rafsanjan Airport",
   :city=>"Rafsanjan",
   :icao=>"OIKR",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Rafsanjan, Iran"},
 "RIS"=>
  {:iata=>"RIS",
   :name=>"Rishiri Airport",
   :city=>"Rishiri",
   :icao=>"RJER",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Rishiri, Japan"},
 "RNJ"=>
  {:iata=>"RNJ",
   :name=>"Yoron Airport",
   :city=>"Yoronjima",
   :icao=>"RORY",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Yoronjima, Japan"},
 "RBJ"=>
  {:iata=>"RBJ",
   :name=>"Rebun Airport",
   :city=>"Rebun",
   :icao=>"RJCR",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Rebun, Japan"},
 "RDN"=>
  {:iata=>"RDN",
   :name=>"LTS Pulau Redang Airport",
   :city=>"Redang",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Redang, Malaysia"},
 "RNU"=>
  {:iata=>"RNU",
   :name=>"Ranau Airport",
   :city=>"Ranau",
   :icao=>"",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Ranau, Malaysia"},
 "RGN"=>
  {:iata=>"RGN",
   :name=>"Yangon International Airport",
   :icao=>"VYYY",
   :city=>"Yangon",
   :country=>'Myanmar', :country_code=>'MM',
   :location=>"Yangon, Myanmar"},
 "RHP"=>
  {:iata=>"RHP",
   :name=>"Ramechhap Airport",
   :icao=>"VNRC",
   :city=>"Ramechhap",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Ramechhap, Nepal"},
 "RUM"=>
  {:iata=>"RUM",
   :name=>"Rumjatar Airport",
   :icao=>"VNRT",
   :city=>"Rumjatar",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Rumjatar, Nepal"},
 "RJB"=>
  {:iata=>"RJB",
   :name=>"Rajbiraj Airport",
   :city=>"Rajbiraj",
   :icao=>"VNRB",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Rajbiraj, Nepal"},
 "RPA"=>
  {:iata=>"RPA",
   :name=>"Rolpa Airport",
   :city=>"Rolpa",
   :icao=>"",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Rolpa, Nepal"},
 "RUK"=>
  {:iata=>"RUK",
   :name=>"Rukumkot Airport",
   :icao=>"VNRK",
   :city=>"Rukumkot",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Rukumkot, Nepal"},
 "RYK"=>
  {:iata=>"RYK",
   :name=>"Rahim Yar Khan Airport",
   :city=>"Rahim Yar Khan",
   :icao=>"OPRK",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Rahim Yar Khan, Pakistan"},
 "RZS"=>
  {:iata=>"RZS",
   :name=>"Sawan Airport",
   :city=>"Sawan",
   :icao=>"",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Sawan, Pakistan"},
 "RAZ"=>
  {:iata=>"RAZ",
   :name=>"Rawala Kot Airport",
   :city=>"Rawala Kot",
   :icao=>"OPRT",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Rawala Kot, Pakistan"},
 "RAB"=>
  {:iata=>"RAB",
   :name=>"Tokua Airport",
   :icao=>"AYTK",
   :city=>"Rabaul",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Rabaul, Papua New Guinea"},
 "RAW"=>
  {:iata=>"RAW",
   :name=>"Arawa Airport",
   :city=>"Arawa",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Arawa, Guinea"},
 "RAX"=>
  {:iata=>"RAX",
   :name=>"Oram Airport",
   :city=>"Oram",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Oram, Guinea"},
 "RGE"=>
  {:iata=>"RGE",
   :name=>"Porgera Airport",
   :city=>"Porgera",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Porgera, Guinea"},
 "RBP"=>
  {:iata=>"RBP",
   :name=>"Raba Raba Airport",
   :city=>"Rabaraba",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Rabaraba, Guinea"},
 "RAA"=>
  {:iata=>"RAA",
   :name=>"Rakanda Airport",
   :city=>"Rakanda",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Rakanda, Guinea"},
 "RNR"=>
  {:iata=>"RNR",
   :name=>"Robinson River Airport",
   :city=>"Robinson River",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Robinson River, Guinea"},
 "RMN"=>
  {:iata=>"RMN",
   :name=>"Rumginae Airport",
   :icao=>"",
   :city=>"Rumginae",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Rumginae, Papua New Guinea"},
 "RUU"=>
  {:iata=>"RUU",
   :name=>"Ruti Airport",
   :city=>"Ruti",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Ruti, Guinea"},
 "RKU"=>
  {:iata=>"RKU",
   :name=>"Kairuku Airport",
   :city=>"Yule Island",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Yule Island, Guinea"},
 "RXS"=>
  {:iata=>"RXS",
   :name=>"Roxas Airport",
   :icao=>"RPVR",
   :city=>"Roxas City",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Roxas City, Capiz, Philippines"},
 "RZP"=>
  {:iata=>"RZP",
   :name=>"Cesar Lim Rodriguez (Taytay-Sandoval) Airport",
   :icao=>"RPSD",
   :city=>"Taytay",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Taytay, Palawan, Philippines"},
 "RMQ"=>
  {:iata=>"RMQ",
   :name=>"Taichung Ching Chuan Kang Airport",
   :icao=>"RCMQ",
   :city=>"Taichung",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Taichung, Taiwan, Taiwan"},
 "RSU"=>
  {:iata=>"RSU",
   :name=>"Yeosu Airport",
   :city=>"Yeosu",
   :icao=>"RKJY",
   :country=>'Korea', :country_code=>'',
   :location=>"Yeosu, Korea"},
 "RML"=>
  {:iata=>"RML",
   :name=>"Ratmalana Airport",
   :icao=>"VCCC",
   :city=>"Ratmalana",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Ratmalana, Sri Lanka"},
 "ROI"=>
  {:iata=>"ROI",
   :name=>"Roi Et Airport",
   :city=>"Roi Et",
   :icao=>"",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Roi Et, Thailand"},
 "RIK"=>
  {:iata=>"RIK",
   :name=>"Carrillo Airport",
   :icao=>"MRCR",
   :city=>"Carrillo",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Carrillo, Costa Rica"},
 "RFR"=>
  {:iata=>"RFR",
   :name=>"Rio Frio Airport",
   :city=>"Rio Frio",
   :icao=>"",
   :country=>'Rica', :country_code=>'',
   :location=>"Rio Frio, Rica"},
 "RER"=>
  {:iata=>"RER",
   :name=>"Retalhuleu Airport",
   :icao=>"MGRT",
   :city=>"Retalhuleu",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Retalhuleu, Guatemala"},
 "RUV"=>
  {:iata=>"RUV",
   :name=>"Rubelsanto Airport",
   :city=>"Rubelsanto",
   :icao=>"",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Rubelsanto, Guatemala"},
 "RTB"=>
  {:iata=>"RTB",
   :name=>"Juan Manuel Gálvez International Airport",
   :icao=>"MHRO",
   :city=>"Roatán",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Roatán, Honduras"},
 "RUY"=>
  {:iata=>"RUY",
   :name=>"Copan Airport",
   :city=>"Copan",
   :icao=>"",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Copan, Honduras"},
 "RNI"=>
  {:iata=>"RNI",
   :name=>"Corn Island Airport",
   :icao=>"MNCI",
   :city=>"Corn Island",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"Corn Island, Nicaragua"},
 "RFS"=>
  {:iata=>"RFS",
   :name=>"Rosita Airport",
   :city=>"Rosita",
   :icao=>"",
   :country=>'Nicaragua', :country_code=>'NI',
   :location=>"Rosita, Nicaragua"},
 "RIH"=>
  {:iata=>"RIH",
   :name=>"Río Hato Airport",
   :icao=>"MPSM",
   :city=>"Cocle",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Cocle, Panama"},
 "RSI"=>
  {:iata=>"RSI",
   :name=>"Rio Sidra Airport",
   :city=>"Rio Sidra",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Rio Sidra, Panama"},
 "RIZ"=>
  {:iata=>"RIZ",
   :name=>"Rio Alzucar Airport",
   :city=>"Rio Alzucar",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Rio Alzucar, Panama"},
 "RIT"=>
  {:iata=>"RIT",
   :name=>"Rio Tigre Airport",
   :city=>"Rio Tigre",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Rio Tigre, Panama"},
 "RMF"=>
  {:iata=>"RMF",
   :name=>"Marsa Alam",
   :icao=>"HEMA",
   :city=>"Marsa Alam",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Marsa Alam, Egypt"},
 "RAF"=>
  {:iata=>"RAF",
   :name=>"Ras an-Naqb Airport",
   :icao=>"",
   :city=>"Ras an-Naqb",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Ras an-Naqb, Egypt"},
 "RPN"=>
  {:iata=>"RPN",
   :name=>"Rosh Pina Airport",
   :icao=>"LLIB",
   :city=>"Rosh Pina",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Rosh Pina, Israel"},
 "RMB"=>
  {:iata=>"RMB",
   :name=>"Buraimi Airport",
   :city=>"Buraimi",
   :icao=>"",
   :country=>'Oman', :country_code=>'OM',
   :location=>"Buraimi, Oman"},
 "RIY"=>
  {:iata=>"RIY",
   :name=>"Riyan Airport",
   :city=>"Riyan",
   :icao=>"OYRN",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Riyan, Yemen"},
 "RXA"=>
  {:iata=>"RXA",
   :name=>"Raudha Airport",
   :city=>"Raudha",
   :icao=>"",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Raudha, Yemen"},
 "RUH"=>
  {:iata=>"RUH",
   :name=>"King Khalid International Airport",
   :icao=>"OERK",
   :city=>"Riyadh",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Riyadh, Saudi Arabia"},
 "RAE"=>
  {:iata=>"RAE",
   :name=>"Arar Airport",
   :city=>"Arar",
   :icao=>"OERR",
   :country=>'Arabia', :country_code=>'',
   :location=>"Arar, Arabia"},
 "RAH"=>
  {:iata=>"RAH",
   :name=>"Rafha Airport",
   :city=>"Rafha",
   :icao=>"OERF",
   :country=>'Arabia', :country_code=>'',
   :location=>"Rafha, Arabia"},
 "RKT"=>
  {:iata=>"RKT",
   :name=>"Ras Al Khaimah International Airport",
   :icao=>"OMRK",
   :city=>"Ras Al Khaimah",
   :country=>"United Arab Emirates",
:country_code=>"AE",
   :location=>"Ras Al Khaimah, United Arab Emirates"},
 "RAC"=>
  {:iata=>"RAC",
   :name=>"John H. Batten Airport",
   :icao=>"KRAC",
   :city=>"Racine",
   :country=>'United States', :country_code=>'US',

   :location=>"Racine, Wisconsin, United States"},
 "RAL"=>
  {:iata=>"RAL",
   :name=>"Riverside Municipal Airport",
   :icao=>"KRAL",
   :city=>"Riverside",
   :country=>'United States', :country_code=>'US',

   :location=>"Riverside, California, United States"},
 "RAP"=>
  {:iata=>"RAP",
   :name=>"Rapid City Regional Airport",
   :icao=>"KRAP",
   :city=>"Rapid City",
   :country=>'United States', :country_code=>'US',

   :location=>"Rapid City, South Dakota, United States"},
 "RBD"=>
  {:iata=>"RBD",
   :name=>"Dallas Executive Airport",
   :icao=>"KRBD",
   :city=>"Dallas",
   :country=>'United States', :country_code=>'US',

   :location=>"Dallas, Texas, United States"},
 "RBG"=>
  {:iata=>"RBG",
   :name=>"Roseburg Regional Airport",
   :icao=>"KRBG",
   :city=>"Roseburg",
   :country=>'United States', :country_code=>'US',

   :location=>"Roseburg, Oregon, United States"},
 "RBL"=>
  {:iata=>"RBL",
   :name=>"Red Bluff Municipal Airport",
   :icao=>"KRBL",
   :city=>"Red Bluff",
   :country=>'United States', :country_code=>'US',

   :location=>"Red Bluff, California, United States"},
 "RBW"=>
  {:iata=>"RBW",
   :name=>"Lowcountry Regional Airport",
   :icao=>"KRBW",
   :city=>"Walterboro",
   :country=>'United States', :country_code=>'US',

   :location=>"Walterboro, South Carolina, United States"},
 "RBY"=>
  {:iata=>"RBY",
   :name=>"Ruby Airport",
   :icao=>"PARY",
   :city=>"Ruby",
   :country=>'United States', :country_code=>'US',

   :location=>"Ruby, Alaska, United States"},
 "RCA"=>
  {:iata=>"RCA",
   :name=>"Ellsworth Air Force Base",
   :icao=>"KRCA",
   :city=>"Rapid City",
   :country=>'United States', :country_code=>'US',

   :location=>"Rapid City, South Dakota, United States"},
 "RCE"=>
  {:iata=>"RCE",
   :name=>"Roche Harbor Seaplane Base",
   :icao=>"",
   :city=>"San Juan Island",
   :country=>'United States', :country_code=>'US',

   :location=>"San Juan Island, Washington, United States"},
 "RCK"=>
  {:iata=>"RCK",
   :name=>"H. H. Coffield Regional Airport",
   :icao=>"KRCK",
   :city=>"Rockdale",
   :country=>'United States', :country_code=>'US',

   :location=>"Rockdale, Texas, United States"},
 "RCR"=>
  {:iata=>"RCR",
   :name=>"Fulton County Airport",
   :icao=>"KRCR",
   :city=>"Rochester",
   :country=>'United States', :country_code=>'US',

   :location=>"Rochester, Indiana, United States"},
 "RCT"=>
  {:iata=>"RCT",
   :name=>"Nartron Field",
   :icao=>"KRCT",
   :city=>"Reed City",
   :country=>'United States', :country_code=>'US',

   :location=>"Reed City, Michigan, United States"},
 "RDB"=>
  {:iata=>"RDB",
   :name=>"Red Dog Airport",
   :icao=>"PADG",
   :city=>"Red Dog",
   :country=>'United States', :country_code=>'US',

   :location=>"Red Dog, Alaska, United States"},
 "RDD"=>
  {:iata=>"RDD",
   :name=>"Redding Municipal Airport",
   :icao=>"KRDD",
   :city=>"Redding",
   :country=>'United States', :country_code=>'US',

   :location=>"Redding, California, United States"},
 "RDG"=>
  {:iata=>"RDG",
   :name=>"Reading Regional Airport (Carl A. Spaatz Field)",
   :icao=>"KRDG",
   :city=>"Reading",
   :country=>'United States', :country_code=>'US',

   :location=>"Reading, Pennsylvania, United States"},
 "RDM"=>
  {:iata=>"RDM",
   :name=>"Roberts Field",
   :icao=>"KRDM",
   :city=>"Redmond",
   :country=>'United States', :country_code=>'US',

   :location=>"Redmond, Oregon, United States"},
 "RDR"=>
  {:iata=>"RDR",
   :name=>"Grand Forks Air Force Base",
   :icao=>"KRDR",
   :city=>"Grand Forks",
   :country=>'United States', :country_code=>'US',

   :location=>"Grand Forks, North Dakota, United States"},
 "RDU"=>
  {:iata=>"RDU",
   :name=>"Raleigh–Durham International Airport",
   :icao=>"KRDU",
   :city=>"Raleigh / Durham",
   :country=>'United States', :country_code=>'US',

   :location=>"Raleigh / Durham, North Carolina, United States"},
 "RDV"=>
  {:iata=>"RDV",
   :name=>"Red Devil Airport",
   :icao=>"",
   :city=>"Red Devil",
   :country=>'United States', :country_code=>'US',

   :location=>"Red Devil, Alaska, United States"},
 "RED"=>
  {:iata=>"RED",
   :name=>"Mifflin County Airport (FAA: RVL)",
   :icao=>"KRVL",
   :city=>"Reedsville",
   :country=>'United States', :country_code=>'US',

   :location=>"Reedsville, Pennsylvania, United States"},
 "REK"=>
  {:iata=>"REK",
   :name=>"Reykjavík Metropolitan Area",
   :icao=>"",
   :city=>"Reykjavík",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Reykjavík, Iceland"},
 "REO"=>
  {:iata=>"REO",
   :name=>"Rome State Airport",
   :icao=>"KREO",
   :city=>"Rome",
   :country=>'United States', :country_code=>'US',

   :location=>"Rome, Oregon, United States"},
 "RFD"=>
  {:iata=>"RFD",
   :name=>"Chicago Rockford International Airport (Greater Rockford Airport)",
   :icao=>"KRFD",
   :city=>"Rockford",
   :country=>'United States', :country_code=>'US',

   :location=>"Rockford, Illinois, United States"},
 "RFG"=>
  {:iata=>"RFG",
   :name=>"Rooke Field",
   :icao=>"KRFG",
   :city=>"Refugio",
   :country=>'United States', :country_code=>'US',

   :location=>"Refugio, Texas, United States"},
 "RGO"=>
  {:iata=>"RGO",
   :name=>"Chongjin Airport",
   :icao=>"",
   :city=>"Chongjin",
   :country=>'China', :country_code=>'CN',
   :location=>"Chongjin, North Korea, China"},
 "RHI"=>
  {:iata=>"RHI",
   :name=>"Rhinelander-Oneida County Airport",
   :icao=>"KRHI",
   :city=>"Rhinelander",
   :country=>'United States', :country_code=>'US',

   :location=>"Rhinelander, Wisconsin, United States"},
 "RHV"=>
  {:iata=>"RHV",
   :name=>"Reid-Hillview Airport of Santa Clara County",
   :icao=>"KRHV",
   :city=>"San Jose",
   :country=>'United States', :country_code=>'US',

   :location=>"San Jose, California, United States"},
 "RIC"=>
  {:iata=>"RIC",
   :name=>"Richmond International Airport",
   :icao=>"KRIC",
   :city=>"Richmond",
   :country=>'United States', :country_code=>'US',

   :location=>"Richmond, Virginia, United States"},
 "RID"=>
  {:iata=>"RID",
   :name=>"Richmond Municipal Airport",
   :icao=>"KRID",
   :city=>"Richmond",
   :country=>'United States', :country_code=>'US',

   :location=>"Richmond, Indiana, United States"},
 "RIE"=>
  {:iata=>"RIE",
   :name=>"Rice Lake Regional Airport (Carl's Field) (FAA: RPD)",
   :icao=>"KRPD",
   :city=>"Rice Lake",
   :country=>'United States', :country_code=>'US',

   :location=>"Rice Lake, Wisconsin, United States"},
 "RIF"=>
  {:iata=>"RIF",
   :name=>"Richfield Municipal Airport",
   :icao=>"KRIF",
   :city=>"Richfield",
   :country=>'United States', :country_code=>'US',

   :location=>"Richfield, Utah, United States"},
 "RIL"=>
  {:iata=>"RIL",
   :name=>"Garfield County Regional Airport",
   :icao=>"KRIL",
   :city=>"Rifle",
   :country=>'United States', :country_code=>'US',

   :location=>"Rifle, Colorado, United States"},
 "RIO"=>
  {:iata=>"RIO",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Rio de Janeiro",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Rio de Janeiro, Brazil"},
 "RIR"=>
  {:iata=>"RIR",
   :name=>"Flabob Airport",
   :icao=>"KRIR",
   :city=>"Riverside/Rubidoux",
   :country=>'United States', :country_code=>'US',

   :location=>"Riverside/Rubidoux, California, United States"},
 "RIV"=>
  {:iata=>"RIV",
   :name=>"March Air Reserve Base",
   :icao=>"KRIV",
   :city=>"Riverside",
   :country=>'United States', :country_code=>'US',

   :location=>"Riverside, California, United States"},
 "RKC"=>
  {:iata=>"RKC",
   :name=>"Montague Airport (Yreka Rohrer Field) (FAA: 1O5)",
   :icao=>"",
   :city=>"Montague",
   :country=>'United States', :country_code=>'US',

   :location=>"Montague, California, United States"},
 "RKD"=>
  {:iata=>"RKD",
   :name=>"Knox County Regional Airport",
   :icao=>"KRKD",
   :city=>"Rockland",
   :country=>'United States', :country_code=>'US',

   :location=>"Rockland, Maine, United States"},
 "RKP"=>
  {:iata=>"RKP",
   :name=>"Aransas County Airport",
   :icao=>"KRKP",
   :city=>"Rockport",
   :country=>'United States', :country_code=>'US',

   :location=>"Rockport, Texas, United States"},
 "RKR"=>
  {:iata=>"RKR",
   :name=>"Robert S. Kerr Airport",
   :icao=>"KRKR",
   :city=>"Poteau",
   :country=>'United States', :country_code=>'US',

   :location=>"Poteau, Oklahoma, United States"},
 "RKW"=>
  {:iata=>"RKW",
   :name=>"Rockwood Municipal Airport",
   :icao=>"KRKW",
   :city=>"Rockwood",
   :country=>'United States', :country_code=>'US',

   :location=>"Rockwood, Tennessee, United States"},
 "RLD"=>
  {:iata=>"RLD",
   :name=>"Richland Airport",
   :icao=>"KRLD",
   :city=>"Richland",
   :country=>'United States', :country_code=>'US',

   :location=>"Richland, Washington, United States"},
 "RME"=>
  {:iata=>"RME",
   :name=>"Griffiss Airpark",
   :icao=>"KRME",
   :city=>"Rome",
   :country=>'United States', :country_code=>'US',

   :location=>"Rome, New York, United States"},
 "RMG"=>
  {:iata=>"RMG",
   :name=>"Richard B. Russell Airport",
   :icao=>"KRMG",
   :city=>"Rome",
   :country=>'United States', :country_code=>'US',

   :location=>"Rome, Georgia, United States"},
 "RMP"=>
  {:iata=>"RMP",
   :name=>"Rampart Airport",
   :icao=>"",
   :city=>"Rampart",
   :country=>'United States', :country_code=>'US',

   :location=>"Rampart, Alaska, United States"},
 "RNC"=>
  {:iata=>"RNC",
   :name=>"Warren County Memorial Airport",
   :icao=>"KRNC",
   :city=>"McMinnville",
   :country=>'United States', :country_code=>'US',

   :location=>"McMinnville, Tennessee, United States"},
 "RND"=>
  {:iata=>"RND",
   :name=>"Randolph Air Force Base",
   :icao=>"KRND",
   :city=>"Universal City",
   :country=>'United States', :country_code=>'US',

   :location=>"Universal City, Texas, United States"},
 "RNH"=>
  {:iata=>"RNH",
   :name=>"New Richmond Regional Airport",
   :icao=>"KRNH",
   :city=>"New Richmond",
   :country=>'United States', :country_code=>'US',

   :location=>"New Richmond, Wisconsin, United States"},
 "RNO"=>
  {:iata=>"RNO",
   :name=>"Reno-Tahoe International Airport",
   :icao=>"KRNO",
   :city=>"Reno",
   :country=>'United States', :country_code=>'US',

   :location=>"Reno, Nevada, United States"},
 "RNT"=>
  {:iata=>"RNT",
   :name=>"Renton Municipal Airport",
   :icao=>"KRNT",
   :city=>"Renton",
   :country=>'United States', :country_code=>'US',

   :location=>"Renton, Washington, United States"},
 "RNZ"=>
  {:iata=>"RNZ",
   :name=>"Jasper County Airport (FAA: RZL)",
   :icao=>"KRZL",
   :city=>"Rensselaer",
   :country=>'United States', :country_code=>'US',

   :location=>"Rensselaer, Indiana, United States"},
 "ROA"=>
  {:iata=>"ROA",
   :name=>"Roanoke Regional Airport (Woodrum Field)",
   :icao=>"KROA",
   :city=>"Roanoke",
   :country=>'United States', :country_code=>'US',

   :location=>"Roanoke, Virginia, United States"},
 "ROC"=>
  {:iata=>"ROC",
   :name=>"Greater Rochester International Airport",
   :icao=>"KROC",
   :city=>"Rochester",
   :country=>'United States', :country_code=>'US',

   :location=>"Rochester, New York, United States"},
 "ROG"=>
  {:iata=>"ROG",
   :name=>"Rogers Municipal Airport (Carter Field)",
   :icao=>"KROG",
   :city=>"Rogers",
   :country=>'United States', :country_code=>'US',

   :location=>"Rogers, Arkansas, United States"},
 "ROL"=>
  {:iata=>"ROL",
   :name=>"Roosevelt Municipal Airport",
   :icao=>"",
   :city=>"Roosevelt",
   :country=>'United States', :country_code=>'US',

   :location=>"Roosevelt, Utah, United States"},
 "ROM"=>
  {:iata=>"ROM",
   :name=>"All Airports",
   :icao=>"",
   :city=>"Rome",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Rome, Italy"},
 "ROW"=>
  {:iata=>"ROW",
   :name=>"Roswell International Air Center",
   :icao=>"KROW",
   :city=>"Roswell",
   :country=>'United States', :country_code=>'US',

   :location=>"Roswell, New Mexico, United States"},
 "ROX"=>
  {:iata=>"ROX",
   :name=>"Roseau Municipal Airport (Rudy Billberg Field)",
   :icao=>"KROX",
   :city=>"Roseau",
   :country=>'United States', :country_code=>'US',

   :location=>"Roseau, Minnesota, United States"},
 "RPX"=>
  {:iata=>"RPX",
   :name=>"Roundup Airport",
   :icao=>"KRPX",
   :city=>"Roundup",
   :country=>'United States', :country_code=>'US',

   :location=>"Roundup, Montana, United States"},
 "RRL"=>
  {:iata=>"RRL",
   :name=>"Merrill Municipal Airport",
   :icao=>"KRRL",
   :city=>"Merrill",
   :country=>'United States', :country_code=>'US',

   :location=>"Merrill, Wisconsin, United States"},
 "RRT"=>
  {:iata=>"RRT",
   :name=>"Warroad International Airport (Swede Carlson Field)",
   :icao=>"KRRT",
   :city=>"Warroad",
   :country=>'United States', :country_code=>'US',

   :location=>"Warroad, Minnesota, United States"},
 "RSH"=>
  {:iata=>"RSH",
   :name=>"Russian Mission Airport",
   :icao=>"PARS",
   :city=>"Russian Mission",
   :country=>'United States', :country_code=>'US',

   :location=>"Russian Mission, Alaska, United States"},
 "RSJ"=>
  {:iata=>"RSJ",
   :name=>"Rosario Seaplane Base",
   :icao=>"",
   :city=>"Orcas Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Orcas Island, Washington, United States"},
 "RSL"=>
  {:iata=>"RSL",
   :name=>"Russell Municipal Airport",
   :icao=>"KRSL",
   :city=>"Russell",
   :country=>'United States', :country_code=>'US',

   :location=>"Russell, Kansas, United States"},
 "RSN"=>
  {:iata=>"RSN",
   :name=>"Ruston Regional Airport",
   :icao=>"KRSN",
   :city=>"Ruston",
   :country=>'United States', :country_code=>'US',

   :location=>"Ruston, Louisiana, United States"},
 "RST"=>
  {:iata=>"RST",
   :name=>"Rochester International Airport",
   :icao=>"KRST",
   :city=>"Rochester",
   :country=>'United States', :country_code=>'US',

   :location=>"Rochester, Minnesota, United States"},
 "RSW"=>
  {:iata=>"RSW",
   :name=>"Southwest Florida International Airport",
   :icao=>"KRSW",
   :city=>"Fort Myers",
   :country=>'United States', :country_code=>'US',

   :location=>"Fort Myers, Florida, United States"},
 "RTN"=>
  {:iata=>"RTN",
   :name=>"Raton Municipal Airport (Crews Field)",
   :icao=>"KRTN",
   :city=>"Raton",
   :country=>'United States', :country_code=>'US',

   :location=>"Raton, New Mexico, United States"},
 "RUT"=>
  {:iata=>"RUT",
   :name=>"Rutland State Airport",
   :icao=>"KRUT",
   :city=>"Rutland",
   :country=>'United States', :country_code=>'US',

   :location=>"Rutland, Vermont, United States"},
 "RVS"=>
  {:iata=>"RVS",
   :name=>"Richard Lloyd Jones Jr. Airport",
   :icao=>"KRVS",
   :city=>"Tulsa",
   :country=>'United States', :country_code=>'US',

   :location=>"Tulsa, Oklahoma, United States"},
 "RWF"=>
  {:iata=>"RWF",
   :name=>"Redwood Falls Municipal Airport",
   :icao=>"KRWF",
   :city=>"Redwood Falls",
   :country=>'United States', :country_code=>'US',

   :location=>"Redwood Falls, Minnesota, United States"},
 "RWI"=>
  {:iata=>"RWI",
   :name=>"Rocky Mount-Wilson Regional Airport",
   :icao=>"KRWI",
   :city=>"Rocky Mount",
   :country=>'United States', :country_code=>'US',

   :location=>"Rocky Mount, North Carolina, United States"},
 "RZZ"=>
  {:iata=>"RZZ",
   :name=>"Halifax County Airport",
   :icao=>"KRZZ",
   :city=>"Roanoke Rapids",
   :country=>'United States', :country_code=>'US',

   :location=>"Roanoke Rapids, North Carolina, United States"}}

end
