# encoding: UTF-8
def airp_25
  {"XBE"=>
  {:iata=>"XBE",
   :name=>"Bearskin Lake Airport",
   :icao=>"",
   :city=>"Bearskin Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Bearskin Lake, Ontario, Canada"},
 "XBR"=>
  {:iata=>"XBR",
   :name=>"Brockville Regional Tackaberry Airport",
   :icao=>"",
   :city=>"Brockville",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Brockville, Ontario, Canada"},
 "XGR"=>
  {:iata=>"XGR",
   :name=>"Kangiqsualujjuaq (Georges River) Airport",
   :icao=>"CYLU",
   :city=>"Kangiqsualujjuaq",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kangiqsualujjuaq, Quebec, Canada"},
 "XKS"=>
  {:iata=>"XKS",
   :name=>"Kasabonika Airport",
   :icao=>"CYAQ",
   :city=>"Kasabonika First Nation",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kasabonika First Nation, Ontario, Canada"},
 "XLB"=>
  {:iata=>"XLB",
   :name=>"Lac Brochet Airport",
   :icao=>"CZWH",
   :city=>"Lac Brochet",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Lac Brochet, Manitoba, Canada"},
 "XQU"=>
  {:iata=>"XQU",
   :name=>"Qualicum Beach Airport",
   :icao=>"",
   :city=>"Qualicum Beach",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Qualicum Beach, British Columbia, Canada"},
 "XSI"=>
  {:iata=>"XSI",
   :name=>"South Indian Lake Airport",
   :icao=>"CZSN",
   :city=>"South Indian Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"South Indian Lake, Manitoba, Canada"},
 "XTL"=>
  {:iata=>"XTL",
   :name=>"Tadoule Lake Airport",
   :icao=>"CYBQ",
   :city=>"Tadoule Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Tadoule Lake, Manitoba, Canada"},
 "XBB"=>
  {:iata=>"XBB",
   :name=>"Blubber Bay Airport",
   :icao=>"",
   :city=>"Blubber Bay",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Blubber Bay, British Columbia, Canada"},
 "XCM"=>
  {:iata=>"XCM",
   :name=>"Chatham-Kent Airport",
   :icao=>"",
   :city=>"Chatham-Kent",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Chatham-Kent, Ontario, Canada"},
 "XCL"=>
  {:iata=>"XCL",
   :name=>"Cluff Lake Airport",
   :icao=>"",
   :city=>"Cluff Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Cluff Lake, Saskatchewan, Canada"},
 "XGL"=>
  {:iata=>"XGL",
   :name=>"Granville Lake Airport",
   :icao=>"",
   :city=>"Granville Lake",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Granville Lake, Manitoba, Canada"},
 "XKO"=>
  {:iata=>"XKO",
   :name=>"Kemano Airport",
   :icao=>"",
   :city=>"Kemano",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Kemano, British Columbia, Canada"},
 "XLF"=>
  {:iata=>"XLF",
   :name=>"Leaf Bay Airport",
   :city=>"Leaf Bay",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Leaf Bay, Canada"},
 "XFZ"=>
  {:iata=>"XFZ",
   :name=>"Charny Station",
   :city=>"Levis",
   :icao=>"",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Levis, Canada"},
 "XMP"=>
  {:iata=>"XMP",
   :name=>"Macmillan Pass Airport",
   :city=>"Macmillan Pass",
   :icao=>"CFC4",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Macmillan Pass, Canada"},
 "XPP"=>
  {:iata=>"XPP",
   :name=>"Poplar River Airport",
   :icao=>"CZNG",
   :city=>"Poplar River",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Poplar River, Manitoba, Canada"},
 "XPK"=>
  {:iata=>"XPK",
   :name=>"Pukatawagan Airport",
   :icao=>"CZFG",
   :city=>"Pukatawagan",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Pukatawagan, Manitoba, Canada"},
 "XRR"=>
  {:iata=>"XRR",
   :name=>"Ross River Airport",
   :icao=>"CYDM",
   :city=>"Ross River",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Ross River, Yukon, Canada"},
 "XIQ"=>
  {:iata=>"XIQ",
   :name=>"Ilimanaq Harbour Airport",
   :city=>"Ilimanaq",
   :icao=>"",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Ilimanaq, Greenland"},
 "XEQ"=>
  {:iata=>"XEQ",
   :name=>"Tasiusaq Heliport (Kujalleq)",
   :icao=>"BGTQ",
   :city=>"Tasiusaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Tasiusaq, Kujalleq, Greenland"},
 "XEO"=>
  {:iata=>"XEO",
   :name=>"Oquatsut Harbour Airport",
   :city=>"Oquatsut",
   :icao=>"",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Oquatsut, Greenland"},
 "XAL"=>
  {:iata=>"XAL",
   :name=>"Álamos Airport",
   :icao=>"",
   :city=>"Álamos",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Álamos, Sonora, Mexico"},
 "XPD"=>
  {:iata=>"XPD",
   :name=>"San Pedro",
   :city=>"San Pedro",
   :icao=>"",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Pedro, Argentina"},
 "XAP"=>
  {:iata=>"XAP",
   :name=>"Chapecó Airport",
   :icao=>"SBCH",
   :city=>"Chapecó",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Chapecó, Brazil"},
 "XIG"=>
  {:iata=>"XIG",
   :name=>"Xinguara Municipal Airport",
   :icao=>"",
   :city=>"Xinguara",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Xinguara, Pará, Brazil"},
 "XMS"=>
  {:iata=>"XMS",
   :name=>"Macas Airport (Edmundo Carvajal Airport)",
   :icao=>"SEMC",
   :city=>"Macas",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Macas, Ecuador"},
 "XAU"=>
  {:iata=>"XAU",
   :name=>"Saül Airport",
   :icao=>"SOOS",
   :city=>"Saül",
   :country=>'French Guiana', :country_code=>'GF',
   :location=>"Saül, French Guiana"},
 "XTG"=>
  {:iata=>"XTG",
   :name=>"Thargomindah Airport",
   :icao=>"YTGM",
   :city=>"Thargomindah",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Thargomindah, Queensland, Australia"},
 "XCO"=>
  {:iata=>"XCO",
   :name=>"Colac Airport",
   :icao=>"YOLA",
   :city=>"Colac",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Colac, Victoria, Australia"},
 "XMC"=>
  {:iata=>"XMC",
   :name=>"Mallacoota Airport",
   :city=>"Mallacoota",
   :icao=>"YMCO",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mallacoota, Australia"},
 "XML"=>
  {:iata=>"XML",
   :name=>"Minlaton Airport",
   :icao=>"YMIN",
   :city=>"Minlaton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Minlaton, South Australia, Australia"},
 "XRH"=>
  {:iata=>"XRH",
   :name=>"Richmond Air Force Base",
   :city=>"Richmond",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Richmond, Australia"},
 "XTR"=>
  {:iata=>"XTR",
   :name=>"Tara Airport",
   :icao=>"YTAA",
   :city=>"Tara",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Tara, Queensland, Australia"},
 "XTO"=>
  {:iata=>"XTO",
   :name=>"Taroom Airport",
   :icao=>"YTAM",
   :city=>"Taroom",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Taroom, Queensland, Australia"},
 "XMY"=>
  {:iata=>"XMY",
   :name=>"Yam Island Airport",
   :icao=>"YYMI",
   :city=>"Yam Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Yam Island, Queensland, Australia"},
 "XCH"=>
  {:iata=>"XCH",
   :name=>"Christmas Island Airport",
   :icao=>"YPXM",
   :city=>"Christmas Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Christmas Island, Australia"},
 "XMH"=>
  {:iata=>"XMH",
   :name=>"Manihi Airport",
   :icao=>"NTGI",
   :city=>"Manihi",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Manihi, French Polynesia"},
 "XYA"=>
  {:iata=>"XYA",
   :name=>"Yandina Airport",
   :icao=>"AGGY",
   :city=>"Yandina",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Yandina, Solomon Islands"},
 "XSC"=>
  {:iata=>"XSC",
   :name=>"South Caicos Airport",
   :icao=>"MBSC",
   :city=>"South Caicos",
   :country=>'Turks and Caicos Islands', :country_code=>'TC',
   :location=>"South Caicos, Turks and Caicos Islands"},
 "XGN"=>
  {:iata=>"XGN",
   :name=>"Xangongo Airport",
   :icao=>"FNXA",
   :city=>"Xangongo",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Xangongo, Angola"},
 "XAR"=>
  {:iata=>"XAR",
   :name=>"Aribinda Airport",
   :icao=>"DFOY",
   :city=>"Aribinda",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Aribinda, Burkina Faso"},
 "XBG"=>
  {:iata=>"XBG",
   :name=>"Bogande Airport",
   :icao=>"DFEB",
   :city=>"Bogande",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Bogande, Burkina Faso"},
 "XBO"=>
  {:iata=>"XBO",
   :name=>"Boulsa Airport",
   :icao=>"DFEA",
   :city=>"Boulsa",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Boulsa, Burkina Faso"},
 "XDE"=>
  {:iata=>"XDE",
   :name=>"Diebougou Airport",
   :icao=>"DFOU",
   :city=>"Diebougou",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Diebougou, Burkina Faso"},
 "XDJ"=>
  {:iata=>"XDJ",
   :name=>"Djibo Airport",
   :icao=>"DFCJ",
   :city=>"Djibo",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Djibo, Burkina Faso"},
 "XGA"=>
  {:iata=>"XGA",
   :name=>"Gaoua Airport",
   :icao=>"DFOG",
   :city=>"Gaoua",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Gaoua, Burkina Faso"},
 "XGG"=>
  {:iata=>"XGG",
   :name=>"Gorom Gorom Airport",
   :icao=>"DFEG",
   :city=>"Gorom Gorom",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Gorom Gorom, Burkina Faso"},
 "XKA"=>
  {:iata=>"XKA",
   :name=>"Kantchari Airport",
   :icao=>"DFEL",
   :city=>"Kantchari",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Kantchari, Burkina Faso"},
 "XKY"=>
  {:iata=>"XKY",
   :name=>"Kaya Airport",
   :icao=>"DFCA",
   :city=>"Kaya",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Kaya, Burkina Faso"},
 "XLU"=>
  {:iata=>"XLU",
   :name=>"Leo Airport",
   :icao=>"DFCL",
   :city=>"Leo",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Leo, Burkina Faso"},
 "XNU"=>
  {:iata=>"XNU",
   :name=>"Nouna Airport",
   :icao=>"DFON",
   :city=>"Nouna",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Nouna, Burkina Faso"},
 "XPA"=>
  {:iata=>"XPA",
   :name=>"Pama Airport",
   :icao=>"DFEP",
   :city=>"Pama",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Pama, Burkina Faso"},
 "XSE"=>
  {:iata=>"XSE",
   :name=>"Sebba Airport",
   :icao=>"DFES",
   :city=>"Sebba",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Sebba, Burkina Faso"},
 "XZA"=>
  {:iata=>"XZA",
   :name=>"Zabré Airport",
   :icao=>"DFEZ",
   :city=>"Zabré",
   :country=>'Burkina Faso', :country_code=>'BF',
   :location=>"Zabré, Burkina Faso"},
 "XBL"=>
  {:iata=>"XBL",
   :name=>"Bedele Airport",
   :icao=>"HABB",
   :city=>"Bedele",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Bedele, Ethiopia"},
 "XSA"=>
  {:iata=>"XSA",
   :name=>"AFC Airport",
   :city=>"Sinoe",
   :icao=>"",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Sinoe, Liberia"},
 "XLS"=>
  {:iata=>"XLS",
   :name=>"Saint-Louis Airport",
   :icao=>"GOSS",
   :city=>"Saint-Louis",
   :country=>'Senegal', :country_code=>'SN',
   :location=>"Saint-Louis, Senegal"},
 "XMI"=>
  {:iata=>"XMI",
   :name=>"Masasi Airport",
   :icao=>"HTMI",
   :city=>"Masasi",
   :country=>'Tanzania', :country_code=>'TZ',
   :location=>"Masasi, Tanzania"},
 "XCR"=>
  {:iata=>"XCR",
   :name=>"Vatry International Airport",
   :icao=>"LFOK",
   :city=>"Vatry",
   :country=>'France', :country_code=>'FR',
   :location=>"Vatry, France"},
 "XEX"=>
  {:iata=>"XEX",
   :name=>"Aerogare des Invalides",
   :city=>"Paris",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris, France"},
 "XGB"=>
  {:iata=>"XGB",
   :name=>"Gare Montparnasse Station",
   :city=>"Paris",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Paris, France"},
 "XPZ"=>
  {:iata=>"XPZ",
   :name=>"Saint Tropez Harbour Ferry Service",
   :city=>"Saint Tropez",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Saint Tropez, France"},
 "XYT"=>
  {:iata=>"XYT",
   :name=>"Montaudran Airport",
   :city=>"Toulouse",
   :icao=>"",
   :country=>'France', :country_code=>'FR',
   :location=>"Toulouse, France"},
 "XFW"=>
  {:iata=>"XFW",
   :name=>"Hamburg Finkenwerder Airport",
   :icao=>"EDHI",
   :city=>"Hamburg",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Hamburg, Germany"},
 "XLW"=>
  {:iata=>"XLW",
   :name=>"Lemwerder Airport",
   :icao=>"EDWD",
   :city=>"Lemwerder",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Lemwerder, Lower Saxony, Germany"},
 "XZD"=>
  {:iata=>"XZD",
   :name=>"Kongsvinger Airport",
   :city=>"Kongsvinger",
   :icao=>"",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Kongsvinger, Norway"},
 "XRY"=>
  {:iata=>"XRY",
   :name=>"Jerez Airport (La Parra Airport)",
   :icao=>"LEJR",
   :city=>"Jerez de la Frontera",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Jerez de la Frontera, Spain"},
 "XMN"=>
  {:iata=>"XMN",
   :name=>"Xiamen Gaoqi International Airport",
   :icao=>"ZSAM",
   :city=>"Xiamen",
   :country=>'China', :country_code=>'CN',
   :location=>"Xiamen, Fujian, China"},
 "XIY"=>
  {:iata=>"XIY",
   :name=>"Xi'an Xianyang International Airport",
   :icao=>"ZLXY",
   :city=>"Xianyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Xianyang, Shaanxi, China"},
 "XFN"=>
  {:iata=>"XFN",
   :name=>"Xiangfan Airport",
   :icao=>"ZHXF",
   :city=>"Xiangfan",
   :country=>'China', :country_code=>'CN',
   :location=>"Xiangfan, Hubei, China"},
 "XIC"=>
  {:iata=>"XIC",
   :name=>"Xichang Qingshan Airport",
   :icao=>"ZUXC",
   :city=>"Qingshan",
   :country=>'China', :country_code=>'CN',
   :location=>"Qingshan, China"},
 "XIL"=>
  {:iata=>"XIL",
   :name=>"Xilinhot Airport",
   :icao=>"ZBXH",
   :city=>"Xilinhot",
   :country=>'China', :country_code=>'CN',
   :location=>"Xilinhot, Inner Mongolia, China"},
 "XNN"=>
  {:iata=>"XNN",
   :name=>"Xining Caojiabu Airport",
   :icao=>"ZLXN",
   :city=>"Xining",
   :country=>'China', :country_code=>'CN',
   :location=>"Xining, Qinghai, China"},
 "XUZ"=>
  {:iata=>"XUZ",
   :name=>"Xuzhou Airport",
   :icao=>"ZSXZ",
   :city=>"Xuzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Xuzhou, Jiangsu, China"},
 "XEN"=>
  {:iata=>"XEN",
   :name=>"Xingcheng Airport",
   :icao=>"ZYXC",
   :city=>"Xingcheng",
   :country=>'China', :country_code=>'CN',
   :location=>"Xingcheng, Liaoning, China"},
 "XIN"=>
  {:iata=>"XIN",
   :name=>"Xingning Airport",
   :icao=>"ZGXN",
   :city=>"Xingning",
   :country=>'China', :country_code=>'CN',
   :location=>"Xingning, China"},
 "XNT"=>
  {:iata=>"XNT",
   :name=>"Xingtai Airport",
   :icao=>"ZBXT",
   :city=>"Xingtai",
   :country=>'China', :country_code=>'CN',
   :location=>"Xingtai, Hebei, China"},
 "XBJ"=>
  {:iata=>"XBJ",
   :name=>"Birjand Airport",
   :icao=>"OIMB",
   :city=>"Birjand",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Birjand, Iran"},
 "XKH"=>
  {:iata=>"XKH",
   :name=>"Xieng Khouang Airport",
   :icao=>"VLXK",
   :city=>"Xieng Khouang",
   :country=>'Laos', :country_code=>'',
   :location=>"Xieng Khouang, Laos"},
 "XAY"=>
  {:iata=>"XAY",
   :name=>"Xayabury Airport",
   :city=>"Xayabury",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Xayabury, Republic"},
 "XIE"=>
  {:iata=>"XIE",
   :name=>"Xienglom Airport",
   :city=>"Xienglom",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Xienglom, Republic"},
 "XYE"=>
  {:iata=>"XYE",
   :name=>"Ye Airport",
   :icao=>"VYYE",
   :city=>"Ye",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Ye, Mon State, Myanmar (Burma)"},
 "XMG"=>
  {:iata=>"XMG",
   :name=>"Mahendranagar Airport",
   :icao=>"VNMN",
   :city=>"Mahendranagar",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Mahendranagar, Mahakali, Nepal"},
 "XBN"=>
  {:iata=>"XBN",
   :name=>"Biniguni Airport",
   :icao=>"",
   :city=>"Biniguni",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Biniguni, Papua New Guinea"},
 "XYR"=>
  {:iata=>"XYR",
   :name=>"Yellow River Airport",
   :city=>"Yellow River",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Yellow River, Guinea"},
 "XCN"=>
  {:iata=>"XCN",
   :name=>"Pacific Air-VAL Coron Airport",
   :icao=>"",
   :city=>"Coron",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Coron, Palawan, Philippines"},
 "XMA"=>
  {:iata=>"XMA",
   :name=>"Maramag Airport",
   :icao=>"",
   :city=>"Maramag",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Maramag, Bukidnon, Philippines"},
 "XSO"=>
  {:iata=>"XSO",
   :name=>"Siocon Airport",
   :icao=>"RPNO",
   :city=>"Siocon",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Siocon, Zamboanga del Norte, Philippines"},
 "XSP"=>
  {:iata=>"XSP",
   :name=>"Seletar Airport",
   :icao=>"WSSL",
   :city=>"Seletar",
   :country=>'Singapore', :country_code=>'SG',
   :location=>"Seletar, Singapore"},
 "XLO"=>
  {:iata=>"XLO",
   :name=>"Long Xuyen Airport",
   :icao=>"",
   :city=>"Long Xuyen",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Long Xuyen, Vietnam"},
 "XNG"=>
  {:iata=>"XNG",
   :name=>"Quang Ngai Airport",
   :city=>"Quang Ngai",
   :icao=>"",
   :country=>'Nam', :country_code=>'',
   :location=>"Quang Ngai, Nam"},
 "XVL"=>
  {:iata=>"XVL",
   :name=>"Vinh Long Airport",
   :icao=>"",
   :city=>"Vinh Long",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Vinh Long, Vietnam"},
 "XQP"=>
  {:iata=>"XQP",
   :name=>"Quepos Managua Airport",
   :icao=>"MRQP",
   :city=>"Quepos",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Quepos, Costa Rica"},
 "XPL"=>
  {:iata=>"XPL",
   :name=>"Palmerola Air Base (Soto Cano Air Base)",
   :icao=>"MHSC",
   :city=>"Comayagua",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Comayagua, Honduras"},
 "XQC"=>
  {:iata=>"XQC",
   :name=>"Balad Airbase",
   :city=>"Balad",
   :icao=>"ORBD",
   :country=>'Iraq', :country_code=>'IQ',
   :location=>"Balad, Iraq"},
 "XJD"=>
  {:iata=>"XJD",
   :name=>"Al Udeid Air Base",
   :city=>"Doha",
   :icao=>"OTBH",
   :country=>'Qatar', :country_code=>'QA',
   :location=>"Doha, Qatar"},
 "XSB"=>
  {:iata=>"XSB",
   :name=>"Yas Island Airport",
   :city=>"Sir Bani Yas Island",
   :icao=>"OMBY",
   :country=>'Emirates', :country_code=>'',
   :location=>"Sir Bani Yas Island, Emirates"},
 "XMB"=>
  {:iata=>"XMB",
   :name=>"Marina Mall Airport",
   :icao=>"",
   :city=>"Marina Mall",
   :country=>"UAE",
:country_code=>"AE",
   :location=>"Marina Mall, Dubai, UAE"},
 "XAB"=>
  {:iata=>"XAB",
   :name=>"Abbeville - Buigny-Saint-Maclou Aerodrome",
   :icao=>"LFOI",
   :city=>"Abbeville",
   :country=>'France', :country_code=>'FR',
   :location=>"Abbeville, France"},
 "XAC"=>
  {:iata=>"XAC",
   :name=>"Arcachon – La Teste-de-Buch Airport",
   :icao=>"LFCH",
   :city=>"Arcachon",
   :country=>'France', :country_code=>'FR',
   :location=>"Arcachon, France"},
 "XBK"=>
  {:iata=>"XBK",
   :name=>"Bourg - Ceyzériat Airport",
   :icao=>"LFHS",
   :city=>"Bourg-en-Bresse",
   :country=>'France', :country_code=>'FR',
   :location=>"Bourg-en-Bresse, France"},
 "XCY"=>
  {:iata=>"XCY",
   :name=>"Château-Thierry Belleau Airport",
   :icao=>"LFFH",
   :city=>"Château-Thierry",
   :country=>'France', :country_code=>'FR',
   :location=>"Château-Thierry, France"},
 "XDA"=>
  {:iata=>"XDA",
   :name=>"Dax - Seyresse Airport",
   :icao=>"LFBY",
   :city=>"Dax",
   :country=>'France', :country_code=>'FR',
   :location=>"Dax, France"},
 "XDK"=>
  {:iata=>"XDK",
   :name=>"Dunkerque - Les Moëres Airport",
   :icao=>"LFAK",
   :city=>"Dunkerque",
   :country=>'France', :country_code=>'FR',
   :location=>"Dunkerque, France"},
 "XEP"=>
  {:iata=>"XEP",
   :name=>"Épernay - Plivot Airport",
   :icao=>"LFSW",
   :city=>"Épernay",
   :country=>'France', :country_code=>'FR',
   :location=>"Épernay, France"},
 "XES"=>
  {:iata=>"XES",
   :name=>"Grand Geneva Resort Airport (FAA: C02)",
   :icao=>"",
   :city=>"Lake Geneva",
   :country=>'United States', :country_code=>'US',

   :location=>"Lake Geneva, Wisconsin, United States"},
 "XKL"=>
  {:iata=>"XKL",
   :name=>"KL City Air Terminal",
   :icao=>"",
   :city=>"Kuala Lumpur",
   :country=>'Malaysia', :country_code=>'MY',
   :location=>"Kuala Lumpur, Malaysia"},
 "XMD"=>
  {:iata=>"XMD",
   :name=>"Madison Municipal Airport (FAA: MDS)",
   :icao=>"KMDS",
   :city=>"Madison",
   :country=>'United States', :country_code=>'US',

   :location=>"Madison, South Dakota, United States"},
 "XMF"=>
  {:iata=>"XMF",
   :name=>"Montbéliard Courcelles Airport",
   :icao=>"LFSM",
   :city=>"Montbéliard",
   :country=>'France', :country_code=>'FR',
   :location=>"Montbéliard, France"},
 "XMU"=>
  {:iata=>"XMU",
   :name=>"Moulins - Montbeugny Airport",
   :icao=>"LFHY",
   :city=>"Moulins",
   :country=>'France', :country_code=>'FR',
   :location=>"Moulins, Allier, France"},
 "XNA"=>
  {:iata=>"XNA",
   :name=>"Northwest Arkansas Regional Airport",
   :icao=>"KXNA",
   :city=>"Fayetteville/Springdale",
   :country=>'United States', :country_code=>'US',

   :location=>"Fayetteville/Springdale, Arkansas, United States"},
 "XOG"=>
  {:iata=>"XOG",
   :name=>"Orange-Caritat Air Base",
   :icao=>"LFMO",
   :city=>"Orange",
   :country=>'France', :country_code=>'FR',
   :location=>"Orange, France"},
 "XPR"=>
  {:iata=>"XPR",
   :name=>"Pine Ridge Airport (FAA: IEN)",
   :icao=>"KIEN",
   :city=>"Pine Ridge",
   :country=>'United States', :country_code=>'US',

   :location=>"Pine Ridge, South Dakota, United States"},
 "XSD"=>
  {:iata=>"XSD",
   :name=>"Tonopah Test Range Airport (FAA: TNX)",
   :icao=>"KTNX",
   :city=>"Tonopah",
   :country=>'United States', :country_code=>'US',

   :location=>"Tonopah, Nevada, United States"},
 "XVS"=>
  {:iata=>"XVS",
   :name=>"Valenciennes - Denain Aerodrome",
   :icao=>"LFAV",
   :city=>"Valenciennes",
   :country=>'France', :country_code=>'FR',
   :location=>"Valenciennes, France"}}

end
