# encoding: UTF-8
def airp_22
  {"UAK"=>
  {:iata=>"UAK",
   :name=>"Narsarsuaq Airport",
   :icao=>"BGBW",
   :city=>"Narsarsuaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Narsarsuaq, Greenland"},
 "UPK"=>
  {:iata=>"UPK",
   :name=>"Upernavik Kujalleq Heliport",
   :city=>"Upernavik Kujalleq",
   :icao=>"BGKL",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Upernavik Kujalleq, Greenland"},
 "UMD"=>
  {:iata=>"UMD",
   :name=>"Uummannaq Heliport",
   :icao=>"BGUM",
   :city=>"Uummannaq",
   :country=>"Greenland",
:country_code=>"GL",
   :location=>"Uummannaq, Greenland"},
 "UPN"=>
  {:iata=>"UPN",
   :name=>"Lic. y Gen. Ignacio López Rayón International Airport",
   :icao=>"MMPN",
   :city=>"Uruapan",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Uruapan, Michoacán, Mexico"},
 "UAC"=>
  {:iata=>"UAC",
   :name=>"San Luis Rio Colorado Airport",
   :city=>"San Luis Rio Colorado",
   :icao=>"",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"San Luis Rio Colorado, Mexico"},
 "UAQ"=>
  {:iata=>"UAQ",
   :name=>"Domingo Faustino Sarmiento Airport",
   :icao=>"SANU",
   :city=>"San Juan Province",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Juan Province, Argentina"},
 "ULA"=>
  {:iata=>"ULA",
   :name=>"San Julian Airport",
   :city=>"San Julian",
   :icao=>"SAWJ",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"San Julian, Argentina"},
 "USH"=>
  {:iata=>"USH",
   :name=>"Ushuaia - Malvinas Argentinas International Airport",
   :icao=>"SAWH",
   :city=>"Ushuaia",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Ushuaia, Tierra del Fuego, Argentina"},
 "UZU"=>
  {:iata=>"UZU",
   :name=>"Curuzú Cuatiá Airport",
   :icao=>"SATU",
   :city=>"Curuzú Cuatiá",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Curuzú Cuatiá, Corrientes, Argentina"},
 "UYU"=>
  {:iata=>"UYU",
   :name=>"Joya Andina Airport",
   :icao=>"SLUY",
   :city=>"Uyuni",
   :country=>"Bolivia",
:country_code=>"BO",
   :location=>"Uyuni, Potosí, Bolivia"},
 "UBA"=>
  {:iata=>"UBA",
   :name=>"Mário de Almeida Franco Airport",
   :icao=>"SBUR",
   :city=>"Uberaba",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Uberaba, Minas Gerais, Brazil"},
 "UDI"=>
  {:iata=>"UDI",
   :name=>"Uberlandia Airport",
   :icao=>"SBUL",
   :city=>"Uberlândia",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Uberlândia, Minas Gerais, Brazil"},
 "UNA"=>
  {:iata=>"UNA",
   :name=>"Una Airport",
   :city=>"Una",
   :icao=>"",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Una, Brazil"},
 "URG"=>
  {:iata=>"URG",
   :name=>"Rubem Berta International Airport",
   :icao=>"SBUG",
   :city=>"Uruguaiana",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Uruguaiana, Rio Grande do Sul, Brazil"},
 "UBT"=>
  {:iata=>"UBT",
   :name=>"Ubatuba Airport",
   :city=>"Ubatuba",
   :icao=>"SDUB",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Ubatuba, Brazil"},
 "UMU"=>
  {:iata=>"UMU",
   :name=>"Ernesto Geisel Airport",
   :city=>"Umuarama",
   :icao=>"SSUM",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Umuarama, Brazil"},
 "URB"=>
  {:iata=>"URB",
   :name=>"Ernesto Pochler Airport",
   :city=>"Urubupunga",
   :icao=>"SBUP",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Urubupunga, Brazil"},
 "ULC"=>
  {:iata=>"ULC",
   :name=>"Los Cerrillos Airport",
   :city=>"Santiago",
   :icao=>"SCTI",
   :country=>"Chile",
:country_code=>"CL",
   :location=>"Santiago, Chile"},
 "UIB"=>
  {:iata=>"UIB",
   :name=>"El Caraño Airport",
   :icao=>"SKUI",
   :city=>"Quibdó",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Quibdó, Colombia"},
 "ULS"=>
  {:iata=>"ULS",
   :name=>"Mulatos Airport",
   :icao=>"",
   :city=>"Mulatos",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Mulatos, Colombia"},
 "ULQ"=>
  {:iata=>"ULQ",
   :name=>"Farfan Airport",
   :city=>"Tulua",
   :icao=>"SKUL",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Tulua, Colombia"},
 "UNC"=>
  {:iata=>"UNC",
   :name=>"Unguía Airport",
   :icao=>"",
   :city=>"Unguía",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Unguía, Colombia"},
 "URI"=>
  {:iata=>"URI",
   :name=>"Uribe Airport",
   :icao=>"",
   :city=>"Uribe",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Uribe, Colombia"},
 "URR"=>
  {:iata=>"URR",
   :name=>"Urrao Airport",
   :city=>"Urrao",
   :icao=>"SKUR",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Urrao, Colombia"},
 "UIO"=>
  {:iata=>"UIO",
   :name=>"Mariscal Sucre International Airport",
   :icao=>"SEQM",
   :city=>"Quito",
   :country=>"Ecuador",
:country_code=>"EC",
   :location=>"Quito, Ecuador"},
 "USI"=>
  {:iata=>"USI",
   :name=>"Mabaruma Airport",
   :icao=>"SYMB",
   :city=>"Mabaruma",
   :country=>"Guyana",
:country_code=>"GY",
   :location=>"Mabaruma, Guyana"},
 "UMI"=>
  {:iata=>"UMI",
   :name=>"Quincemil Airport",
   :city=>"Quincemil",
   :icao=>"SPIL",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Quincemil, Peru"},
 "UPC"=>
  {:iata=>"UPC",
   :name=>"Puerto La Cruz Airport",
   :city=>"Puerto La Cruz",
   :icao=>"",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Puerto La Cruz, Venezuela"},
 "URM"=>
  {:iata=>"URM",
   :name=>"Uriman Airport",
   :city=>"Uriman",
   :icao=>"SVUM",
   :country=>"Venezuela",
:country_code=>"VE",
   :location=>"Uriman, Venezuela"},
 "ULP"=>
  {:iata=>"ULP",
   :name=>"Quilpie Airport",
   :city=>"Quilpie",
   :icao=>"YQLP",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Quilpie, Australia"},
 "UBU"=>
  {:iata=>"UBU",
   :name=>"Kalumburu Airport",
   :city=>"Kalumburu",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Kalumburu, Australia"},
 "UBB"=>
  {:iata=>"UBB",
   :name=>"Mabuiag Island Airport",
   :city=>"Mabuiag Island",
   :icao=>"YMAA",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Mabuiag Island, Australia"},
 "UTB"=>
  {:iata=>"UTB",
   :name=>"Muttaburra Airport",
   :city=>"Muttaburra",
   :icao=>"YMTB",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Muttaburra, Australia"},
 "UTD"=>
  {:iata=>"UTD",
   :name=>"Nutwood Downs Airport",
   :city=>"Nutwood Downs",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Nutwood Downs, Australia"},
 "UEE"=>
  {:iata=>"UEE",
   :name=>"Queenstown Airport",
   :city=>"Queenstown",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Queenstown, Australia"},
 "UIR"=>
  {:iata=>"UIR",
   :name=>"Quirindi Airport",
   :city=>"Quirindi",
   :icao=>"YQDI",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Quirindi, Australia"},
 "UDA"=>
  {:iata=>"UDA",
   :name=>"Undarra Airport",
   :city=>"Undarra",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Undarra, Australia"},
 "USL"=>
  {:iata=>"USL",
   :name=>"Useless Loop Airport",
   :city=>"Useless Loop",
   :icao=>"",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Useless Loop, Australia"},
 "UMR"=>
  {:iata=>"UMR",
   :name=>"Woomera Airport",
   :city=>"Woomera",
   :icao=>"YPWR",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Woomera, Australia"},
 "UAI"=>
  {:iata=>"UAI",
   :name=>"Suai Airport",
   :city=>"Suai",
   :icao=>"",
   :country=>'Timor', :country_code=>'TL',
   :location=>"Suai, Timor"},
 "UAH"=>
  {:iata=>"UAH",
   :name=>"Ua Huka Airport",
   :city=>"Ua Huka",
   :icao=>"NTMU",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Ua Huka, Polynesia"},
 "UAP"=>
  {:iata=>"UAP",
   :name=>"Ua Pou Airport",
   :city=>"Ua Pou, Marquesas Island",
   :icao=>"NTMP",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Ua Pou, Marquesas Island, Polynesia"},
 "UAM"=>
  {:iata=>"UAM",
   :name=>"Andersen Air Force Base",
   :icao=>"PGUA",
   :city=>"Agana",
   :country=>'Guam', :country_code=>'GU',
   :location=>"Agana, Guam"},
 "UIT"=>
  {:iata=>"UIT",
   :name=>"Jaluit Airport (FAA: N55)",
   :icao=>"",
   :city=>"Jaluit Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Jaluit Atoll, Marshall Islands"},
 "UJE"=>
  {:iata=>"UJE",
   :name=>"Ujae Airport",
   :icao=>"",
   :city=>"Ujae Atoll",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Ujae Atoll, Marshall Islands"},
 "UTK"=>
  {:iata=>"UTK",
   :name=>"Utirik Airport (FAA: 03N)",
   :icao=>"",
   :city=>"Utirik Island",
   :country=>"Marshall Islands",
:country_code=>"MH",
   :location=>"Utirik Island, Marshall Islands"},
 "ULI"=>
  {:iata=>"ULI",
   :name=>"Falalop Island Airport (FAA: TT02)",
   :icao=>"",
   :city=>"Falalop Island",
   :country=>'Federated States of Micronesia', :country_code=>'FM',
   :location=>"Falalop Island, Yap, Federated States of Micronesia"},
 "UVE"=>
  {:iata=>"UVE",
   :name=>"Ouvea Airport",
   :city=>"Ouvea",
   :icao=>"NWWV",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Ouvea, Caledonia"},
 "ULB"=>
  {:iata=>"ULB",
   :name=>"Ulei Airport",
   :city=>"Ulei",
   :icao=>"NVSU",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Ulei, Vanuatu"},
 "UIQ"=>
  {:iata=>"UIQ",
   :name=>"Quoin Hill Airport",
   :icao=>"NVVQ",
   :city=>"Quoin Hill",
   :country=>"Vanuatu",
:country_code=>"VU",
   :location=>"Quoin Hill, Vanuatu"},
 "UPB"=>
  {:iata=>"UPB",
   :name=>"Playa Baracoa Airport",
   :city=>"Havana",
   :icao=>"MUPB",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Havana, Cuba"},
 "UPA"=>
  {:iata=>"UPA",
   :name=>"Punta Alegre Airport",
   :city=>"Punta Alegre",
   :icao=>"",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Punta Alegre, Cuba"},
 "USS"=>
  {:iata=>"USS",
   :name=>"Sancti Spiritus Airport",
   :city=>"Sancti Spiritus",
   :icao=>"",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Sancti Spiritus, Cuba"},
 "UVF"=>
  {:iata=>"UVF",
   :name=>"Hewanorra International Airport",
   :icao=>"TLPL",
   :city=>"Vieux-Fort",
   :country=>'Saint Lucia', :country_code=>'LC',
   :location=>"Vieux-Fort, Saint Lucia"},
 "UNI"=>
  {:iata=>"UNI",
   :name=>"Union Island Airport",
   :icao=>"TVSU",
   :city=>"Union Island",
   :country=>'Saint Vincent and the Grenadines', :country_code=>'VC',
   :location=>"Union Island, Saint Vincent and the Grenadines"},
 "UAL"=>
  {:iata=>"UAL",
   :name=>"Luau Airport",
   :icao=>"FNUA",
   :city=>"Luau",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Luau, Moxico, Angola"},
 "UGO"=>
  {:iata=>"UGO",
   :name=>"Uige Airport",
   :city=>"Uige",
   :icao=>"FNUG",
   :country=>'Angola', :country_code=>'AO',
   :location=>"Uige, Angola"},
 "UAS"=>
  {:iata=>"UAS",
   :name=>"Samburu Airport",
   :city=>"Samburu",
   :icao=>"HKSB",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Samburu, Kenya"},
 "UKA"=>
  {:iata=>"UKA",
   :name=>"Ukunda Airport",
   :city=>"Ukunda",
   :icao=>"",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Ukunda, Kenya"},
 "UNE"=>
  {:iata=>"UNE",
   :name=>"Qachas Airport",
   :city=>"Qachas",
   :icao=>"FXQN",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Qachas, Lesotho"},
 "UTG"=>
  {:iata=>"UTG",
   :name=>"Quthing Airport",
   :city=>"Quthing",
   :icao=>"",
   :country=>'Lesotho', :country_code=>'LS',
   :location=>"Quthing, Lesotho"},
 "UCN"=>
  {:iata=>"UCN",
   :name=>"Buchanan Airport",
   :icao=>"GLBU",
   :city=>"Buchanan",
   :country=>'Liberia', :country_code=>'LR',
   :location=>"Buchanan, Liberia"},
 "UEL"=>
  {:iata=>"UEL",
   :name=>"Quelimane Airport",
   :icao=>"FQQL",
   :city=>"Quelimane",
   :country=>'Mozambique', :country_code=>'MZ',
   :location=>"Quelimane, Mozambique"},
 "UTT"=>
  {:iata=>"UTT",
   :name=>"Mthatha Airport",
   :icao=>"FAUT",
   :city=>"Mthatha",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Mthatha, South Africa"},
 "UTN"=>
  {:iata=>"UTN",
   :name=>"Upington Airport",
   :icao=>"FAUP",
   :city=>"Upington",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Upington, South Africa"},
 "UTE"=>
  {:iata=>"UTE",
   :name=>"Butterworth Airport",
   :icao=>"FABU",
   :city=>"Butterworth",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Butterworth, South Africa"},
 "UTW"=>
  {:iata=>"UTW",
   :name=>"Queenstown Airport",
   :city=>"Queenstown",
   :icao=>"FAQT",
   :country=>'Africa', :country_code=>'',
   :location=>"Queenstown, Africa"},
 "ULD"=>
  {:iata=>"ULD",
   :name=>"Prince Mangosuthu Buthelezi Airport",
   :city=>"Ulundi",
   :icao=>"FAUL",
   :country=>'Africa', :country_code=>'',
   :location=>"Ulundi, Africa"},
 "ULX"=>
  {:iata=>"ULX",
   :name=>"Ulusaba Airport",
   :city=>"Ulusaba",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Ulusaba, Africa"},
 "UYL"=>
  {:iata=>"UYL",
   :name=>"Nyala Airport",
   :icao=>"HSNN",
   :city=>"Nyala",
   :country=>'Sudan', :country_code=>'SD',
   :location=>"Nyala, South Darfur, Sudan"},
 "ULU"=>
  {:iata=>"ULU",
   :name=>"Gulu Airport",
   :city=>"Gulu",
   :icao=>"HUGU",
   :country=>'Uganda', :country_code=>'UG',
   :location=>"Gulu, Uganda"},
 "UTA"=>
  {:iata=>"UTA",
   :name=>"Mutare Airport",
   :icao=>"FVMU",
   :city=>"Mutare",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Mutare, Zimbabwe"},
 "UHE"=>
  {:iata=>"UHE",
   :name=>"Kunovice Airport",
   :icao=>"LKKU",
   :city=>"Uherské Hradiště",
   :country=>'Czech Republic', :country_code=>'CZ',
   :location=>"Uherské Hradiště, Czech Republic"},
 "URE"=>
  {:iata=>"URE",
   :name=>"Kuressaare Airport",
   :icao=>"EEKE",
   :city=>"Kuressaare",
   :country=>'Estonia', :country_code=>'EE',
   :location=>"Kuressaare, Saaremaa, Estonia"},
 "UTI"=>
  {:iata=>"UTI",
   :name=>"Utti Airport",
   :icao=>"EFUT",
   :city=>"Utti / Valkeala",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Utti / Valkeala, Finland"},
 "UIP"=>
  {:iata=>"UIP",
   :name=>"Quimper - Cornouaille Airport",
   :icao=>"LFRQ",
   :city=>"Quimper",
   :country=>'France', :country_code=>'FR',
   :location=>"Quimper, France"},
 "URO"=>
  {:iata=>"URO",
   :name=>"Rouen Vallée de Seine Airport",
   :icao=>"LFOP",
   :city=>"Rouen",
   :country=>'France', :country_code=>'FR',
   :location=>"Rouen, France"},
 "URD"=>
  {:iata=>"URD",
   :name=>"Burg Feuerstein Airport",
   :city=>"Burg Feuerstein",
   :icao=>"EDQE",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Burg Feuerstein, Germany"},
 "UPF"=>
  {:iata=>"UPF",
   :name=>"Pforheim Airport",
   :city=>"Pforheim",
   :icao=>"",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Pforheim, Germany"},
 "UDN"=>
  {:iata=>"UDN",
   :name=>"Udine Airfield",
   :city=>"Udine",
   :icao=>"LIPD",
   :country=>'Italy', :country_code=>'IT',
   :location=>"Udine, Italy"},
 "UDE"=>
  {:iata=>"UDE",
   :name=>"Volkel Air Base",
   :icao=>"EHVK",
   :city=>"Uden",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Uden, Noord-Brabant, Netherlands"},
 "UTC"=>
  {:iata=>"UTC",
   :name=>"Soesterberg Airport",
   :city=>"Utrecht",
   :icao=>"EHSB",
   :country=>'Netherlands', :country_code=>'NL',
   :location=>"Utrecht, Netherlands"},
 "UZC"=>
  {:iata=>"UZC",
   :name=>"Užice-Ponikve Airport",
   :icao=>"LYUZ",
   :city=>"Užice",
   :country=>'Serbia', :country_code=>'RS',
   :location=>"Užice, Serbia"},
 "ULV"=>
  {:iata=>"ULV",
   :name=>"Ulyanovsk Baratayevka Airport",
   :icao=>"UWLL",
   :city=>"Ulyanovsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ulyanovsk, Russia"},
 "UUA"=>
  {:iata=>"UUA",
   :name=>"Bugulma Airport",
   :icao=>"UWKB",
   :city=>"Bugulma",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Bugulma, Republic of Tatarstan, Russia"},
 "URS"=>
  {:iata=>"URS",
   :name=>"Kursk Vostochny Airport",
   :icao=>"UUOK",
   :city=>"Kursk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Kursk, Russia"},
 "ULK"=>
  {:iata=>"ULK",
   :name=>"Lensk Airport",
   :city=>"Lensk",
   :icao=>"UERL",
   :country=>'Federation', :country_code=>'',
   :location=>"Lensk, Federation"},
 "UFA"=>
  {:iata=>"UFA",
   :name=>"Ufa Airport",
   :icao=>"UWUU",
   :city=>"Ufa",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ufa, Bashkortostan, Russia"},
 "UCT"=>
  {:iata=>"UCT",
   :name=>"Ukhta Airport",
   :icao=>"UUYH",
   :city=>"Ukhta / Sosnogorsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ukhta / Sosnogorsk, Komi Republic, Russia"},
 "UUD"=>
  {:iata=>"UUD",
   :name=>"Ulan-Ude Airport",
   :icao=>"UIUU",
   :city=>"Ulan-Ude",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ulan-Ude, Republic of Buryatia, Russia"},
 "ULY"=>
  {:iata=>"ULY",
   :name=>"Ulyanovsk Vostochny Airport",
   :icao=>"UWLW",
   :city=>"Ulyanovsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ulyanovsk, Russia"},
 "URJ"=>
  {:iata=>"URJ",
   :name=>"Uray Airport",
   :icao=>"USHU",
   :city=>"Uray",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Uray, Khanty–Mansi Autonomous Okrug, Russia"},
 "USK"=>
  {:iata=>"USK",
   :name=>"Usinsk Airport",
   :city=>"Usinsk",
   :icao=>"UUYS",
   :country=>'Federation', :country_code=>'',
   :location=>"Usinsk, Federation"},
 "UKX"=>
  {:iata=>"UKX",
   :name=>"Ust-Kut Airport",
   :icao=>"UITT",
   :city=>"Ust-Kut",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ust-Kut, Irkutsk Oblast, Russia"},
 "UKG"=>
  {:iata=>"UKG",
   :name=>"Ust-Kuyga Airport",
   :icao=>"",
   :city=>"Ust-Kuyga",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ust-Kuyga, Sakha Republic, Russia"},
 "UMS"=>
  {:iata=>"UMS",
   :name=>"Ust-Maya Airport",
   :icao=>"",
   :city=>"Ust-Maya",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ust-Maya, Ust-Maysky District, Sakha Republic, Russia"},
 "USR"=>
  {:iata=>"USR",
   :name=>"Ust-Nera Airport",
   :icao=>"",
   :city=>"Ust-Nera",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ust-Nera, Sakha Republic, Russia"},
 "UTS"=>
  {:iata=>"UTS",
   :name=>"Ust-Tsylma Airport",
   :city=>"Ust-Tsylma",
   :icao=>"UUYX",
   :country=>'Federation', :country_code=>'',
   :location=>"Ust-Tsylma, Federation"},
 "UUS"=>
  {:iata=>"UUS",
   :name=>"Yuzhno-Sakhalinsk Airport",
   :icao=>"UHSS",
   :city=>"Yuzhno-Sakhalinsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Yuzhno-Sakhalinsk, Sakhalin Island, Russia"},
 "UIK"=>
  {:iata=>"UIK",
   :name=>"Ust-Ilimsk Airport",
   :icao=>"UIBS",
   :city=>"Ust-Ilimsk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Ust-Ilimsk, Irkutsk Oblast, Russia"},
 "UER"=>
  {:iata=>"UER",
   :name=>"Puertollano Airport",
   :city=>"Puertollano",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Puertollano, Islands"},
 "UTL"=>
  {:iata=>"UTL",
   :name=>"Torremolinos Station",
   :city=>"Torremolinos",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Torremolinos, Islands"},
 "UME"=>
  {:iata=>"UME",
   :name=>"Umeå City Airport",
   :icao=>"ESNU",
   :city=>"Umeå",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Umeå, Sweden"},
 "USQ"=>
  {:iata=>"USQ",
   :name=>"Usak Airport",
   :icao=>"LTBO",
   :city=>"Usak",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Usak, Turkey"},
 "UAB"=>
  {:iata=>"UAB",
   :name=>"Adana-Incirlik Airbase",
   :city=>"Adana",
   :icao=>"LTAG",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Adana, Turkey"},
 "UKS"=>
  {:iata=>"UKS",
   :name=>"Belbek Airport",
   :city=>"Sevastopol",
   :icao=>"",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Sevastopol, Ukraine"},
 "UDJ"=>
  {:iata=>"UDJ",
   :name=>"Uzhhorod International Airport",
   :city=>"Uzhgorod",
   :icao=>"UKLU",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Uzhgorod, Ukraine"},
 "UCK"=>
  {:iata=>"UCK",
   :name=>"Lutsk Airport",
   :city=>"Lutsk",
   :icao=>"",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Lutsk, Ukraine"},
 "UMY"=>
  {:iata=>"UMY",
   :name=>"Sumy Airport",
   :city=>"Sumy",
   :icao=>"",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Sumy, Ukraine"},
 "UNT"=>
  {:iata=>"UNT",
   :name=>"Unst Airport",
   :city=>"Baltasound",
   :icao=>"EGPW",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Baltasound, Kingdom"},
 "ULL"=>
  {:iata=>"ULL",
   :name=>"Mull Airport",
   :city=>"Mull",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Mull, Kingdom"},
 "UPV"=>
  {:iata=>"UPV",
   :name=>"Upavon Airport",
   :city=>"Upavon",
   :icao=>"EGDJ",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Upavon, Kingdom"},
 "UHF"=>
  {:iata=>"UHF",
   :name=>"Upper Heyford RAF Station",
   :city=>"Upper Heyford",
   :icao=>"",
   :country=>'Kingdom', :country_code=>'',
   :location=>"Upper Heyford, Kingdom"},
 "UND"=>
  {:iata=>"UND",
   :name=>"Kunduz Airport",
   :icao=>"OAUZ",
   :city=>"Kunduz",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Kunduz, Afghanistan"},
 "URN"=>
  {:iata=>"URN",
   :name=>"Urgoon Airport",
   :city=>"Urgoon",
   :icao=>"",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Urgoon, Afghanistan"},
 "URZ"=>
  {:iata=>"URZ",
   :name=>"Uruzgan Airport",
   :city=>"Uruzgan",
   :icao=>"",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Uruzgan, Afghanistan"},
 "URC"=>
  {:iata=>"URC",
   :name=>"Ürümqi Diwopu International Airport",
   :icao=>"ZWWW",
   :city=>"Ürümqi",
   :country=>'China', :country_code=>'CN',
   :location=>"Ürümqi, Xinjiang, China"},
 "UYN"=>
  {:iata=>"UYN",
   :name=>"Yulin Yuyang Airport",
   :city=>"Yulin",
   :icao=>"",
   :country=>'China', :country_code=>'CN',
   :location=>"Yulin, China"},
 "UDR"=>
  {:iata=>"UDR",
   :name=>"Udaipur Airport",
   :icao=>"VAUD",
   :city=>"Udaipur",
   :country=>"India",
:country_code=>"IN",
   :location=>"Udaipur, India"},
 "UPG"=>
  {:iata=>"UPG",
   :name=>"Sultan Hasanuddin International Airport",
   :icao=>"WAAA",
   :city=>"Makassar",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Makassar, Indonesia"},
 "UOL"=>
  {:iata=>"UOL",
   :name=>"Buol Airport",
   :icao=>"",
   :city=>"Buol",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Buol, Indonesia"},
 "UBR"=>
  {:iata=>"UBR",
   :name=>"Ubrub, Irian Jaya Airport",
   :city=>"Ubrub, Irian Jaya",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Ubrub, Irian Jaya, Indonesia"},
 "UGU"=>
  {:iata=>"UGU",
   :name=>"Zugapa, Irian Jaya Airport",
   :city=>"Zugapa, Irian Jaya",
   :icao=>"",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Zugapa, Irian Jaya, Indonesia"},
 "UKB"=>
  {:iata=>"UKB",
   :name=>"Kobe Airport",
   :icao=>"RJBE",
   :city=>"Kobe",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kobe, Hyōgo Prefecture, Japan"},
 "UEO"=>
  {:iata=>"UEO",
   :name=>"Kume-jima Airport",
   :city=>"Kume-jima",
   :icao=>"ROKJ",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kume-jima, Japan"},
 "UBJ"=>
  {:iata=>"UBJ",
   :name=>"Yamaguchi Ube Airport",
   :icao=>"RJDC",
   :city=>"Ube",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Ube, Yamaguchi Prefecture, Japan"},
 "UKY"=>
  {:iata=>"UKY",
   :name=>"Kyoto Airport",
   :city=>"Kyoto",
   :icao=>"",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Kyoto, Japan"},
 "URA"=>
  {:iata=>"URA",
   :name=>"Oral Ak Zhol Airport",
   :icao=>"UARR",
   :city=>"Oral (Uralsk)",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Oral (Uralsk), Kazakhstan"},
 "UZR"=>
  {:iata=>"UZR",
   :name=>"Urzhar Airport",
   :icao=>"",
   :city=>"Urzhar",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Urzhar, East Kazakhstan Province, Kazakhstan"},
 "UKK"=>
  {:iata=>"UKK",
   :name=>"Oskemen Airport",
   :icao=>"UASK",
   :city=>"Oskemen (Ust-Kamenogorsk)",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Oskemen (Ust-Kamenogorsk), Kazakhstan"},
 "UON"=>
  {:iata=>"UON",
   :name=>"Muong Sai Airport",
   :city=>"Muong Sai",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Muong Sai, Republic"},
 "UDO"=>
  {:iata=>"UDO",
   :name=>"Udomxay Airport",
   :city=>"Udomxay",
   :icao=>"",
   :country=>'Republic', :country_code=>'',
   :location=>"Udomxay, Republic"},
 "ULN"=>
  {:iata=>"ULN",
   :name=>"Chinggis Khaan International Airport",
   :icao=>"ZMUB",
   :city=>"Ulan Bator",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Ulan Bator, Mongolia"},
 "ULO"=>
  {:iata=>"ULO",
   :name=>"Ulaangom Airport",
   :icao=>"ZMUG",
   :city=>"Ulaangom",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Ulaangom, Uvs Province, Mongolia"},
 "ULG"=>
  {:iata=>"ULG",
   :name=>"Ölgii Airport",
   :icao=>"ZMUL",
   :city=>"Bayan-Ölgii Province",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Bayan-Ölgii Province, Mongolia"},
 "ULZ"=>
  {:iata=>"ULZ",
   :name=>"Uliastai Airport",
   :city=>"Uliastai",
   :icao=>"",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Uliastai, Mongolia"},
 "UGT"=>
  {:iata=>"UGT",
   :name=>"Umnugobitour Airport",
   :city=>"Umnugobitour",
   :icao=>"",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Umnugobitour, Mongolia"},
 "UUN"=>
  {:iata=>"UUN",
   :name=>"Baruun-Urt Airport",
   :city=>"Baruun-Urt",
   :icao=>"ZMBU",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Baruun-Urt, Mongolia"},
 "UGA"=>
  {:iata=>"UGA",
   :name=>"Bulgan Airport",
   :icao=>"ZMBN",
   :city=>"Bulgan",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Bulgan, Mongolia"},
 "UNR"=>
  {:iata=>"UNR",
   :name=>"Öndörkhaan Airport",
   :icao=>"ZMUH",
   :city=>"Öndörkhaan",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Öndörkhaan, Khentii, Mongolia"},
 "UET"=>
  {:iata=>"UET",
   :name=>"Quetta International Airport",
   :icao=>"OPQT",
   :city=>"Quetta",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Quetta, Pakistan"},
 "UNG"=>
  {:iata=>"UNG",
   :name=>"Kiunga Airport",
   :city=>"Kiunga",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Kiunga, Guinea"},
 "UBI"=>
  {:iata=>"UBI",
   :name=>"Buin Airport",
   :city=>"Buin",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Buin, Guinea"},
 "UUU"=>
  {:iata=>"UUU",
   :name=>"Manumu Airport",
   :icao=>"",
   :city=>"Manumu",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Manumu, Papua New Guinea"},
 "UAE"=>
  {:iata=>"UAE",
   :name=>"Mount Aue Airport",
   :city=>"Mount Aue",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Mount Aue, Guinea"},
 "UKU"=>
  {:iata=>"UKU",
   :name=>"Nuku Airport",
   :city=>"Nuku",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Nuku, Guinea"},
 "ULE"=>
  {:iata=>"ULE",
   :name=>"Sule Airport",
   :city=>"Sule",
   :icao=>"SULE",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Sule, Guinea"},
 "UMC"=>
  {:iata=>"UMC",
   :name=>"Umba Airport",
   :city=>"Umba",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Umba, Guinea"},
 "UPR"=>
  {:iata=>"UPR",
   :name=>"Upiara Airport",
   :city=>"Upiara",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Upiara, Guinea"},
 "URU"=>
  {:iata=>"URU",
   :name=>"Oro Province Airport",
   :city=>"Uroubi",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Uroubi, Guinea"},
 "USO"=>
  {:iata=>"USO",
   :name=>"Usino Airport",
   :city=>"Usino",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Usino, Guinea"},
 "UVO"=>
  {:iata=>"UVO",
   :name=>"Uvol Airport",
   :city=>"Uvol",
   :icao=>"",
   :country=>'Guinea', :country_code=>'GN',
   :location=>"Uvol, Guinea"},
 "USU"=>
  {:iata=>"USU",
   :name=>"Busuanga Airport",
   :icao=>"RPVV",
   :city=>"Coron",
   :country=>'Philippines', :country_code=>'PH',
   :location=>"Coron, Palawan, Philippines"},
 "USN"=>
  {:iata=>"USN",
   :name=>"Ulsan Airport",
   :city=>"Ulsan",
   :icao=>"RKPU",
   :country=>'Korea', :country_code=>'',
   :location=>"Ulsan, Korea"},
 "USM"=>
  {:iata=>"USM",
   :name=>"Samui Airport",
   :icao=>"VTSM",
   :city=>"Ko Samui",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Ko Samui, Surat Thani, Thailand"},
 "UNN"=>
  {:iata=>"UNN",
   :name=>"Ranong Airport",
   :icao=>"VTSR",
   :city=>"Ranong",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Ranong, Thailand"},
 "URT"=>
  {:iata=>"URT",
   :name=>"Surat Thani Airport",
   :icao=>"VTSB",
   :city=>"Surat Thani",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Surat Thani, Thailand"},
 "UBP"=>
  {:iata=>"UBP",
   :name=>"Ubon Ratchathani Airport",
   :icao=>"VTUU",
   :city=>"Ubon Ratchathani",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Ubon Ratchathani, Thailand"},
 "UTH"=>
  {:iata=>"UTH",
   :name=>"Udon Thani International Airport",
   :icao=>"VTUD",
   :city=>"Udon Thani",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Udon Thani, Thailand"},
 "UTP"=>
  {:iata=>"UTP",
   :name=>"U-Tapao International Airport",
   :icao=>"VTBU",
   :city=>"Rayong",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Rayong, Thailand"},
 "UTR"=>
  {:iata=>"UTR",
   :name=>"Uttaradit Airport",
   :city=>"Uttaradit",
   :icao=>"VTPU",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Uttaradit, Thailand"},
 "UGC"=>
  {:iata=>"UGC",
   :name=>"Urgench International Airport",
   :icao=>"UTNU",
   :city=>"Urgench",
   :country=>'Uzbekistan', :country_code=>'UZ',
   :location=>"Urgench, Uzbekistan"},
 "UIH"=>
  {:iata=>"UIH",
   :name=>"Phu Cat Airport",
   :icao=>"VVPC",
   :city=>"Qui Nhơn",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Qui Nhơn, Binh Dinh, Vietnam"},
 "UPL"=>
  {:iata=>"UPL",
   :name=>"Upala Airport",
   :icao=>"MRUP",
   :city=>"Upala",
   :country=>'Costa Rica', :country_code=>'CR',
   :location=>"Upala, Costa Rica"},
 "UAX"=>
  {:iata=>"UAX",
   :name=>"Uaxactun Airport",
   :city=>"Uaxactun",
   :icao=>"",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Uaxactun, Guatemala"},
 "UII"=>
  {:iata=>"UII",
   :name=>"Utila Airport",
   :city=>"Utila",
   :icao=>"MHUT",
   :country=>'Honduras', :country_code=>'HN',
   :location=>"Utila, Honduras"},
 "UTU"=>
  {:iata=>"UTU",
   :name=>"Ustupo Airport",
   :city=>"Ustupo",
   :icao=>"",
   :country=>'Panama', :country_code=>'PA',
   :location=>"Ustupo, Panama"},
 "UVL"=>
  {:iata=>"UVL",
   :name=>"Kharga Airport",
   :city=>"New Valley",
   :icao=>"HENY",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"New Valley, Egypt"},
 "UKR"=>
  {:iata=>"UKR",
   :name=>"Mukeiras Airport",
   :city=>"Mukeiras",
   :icao=>"OYMK",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Mukeiras, Yemen"},
 "ULH"=>
  {:iata=>"ULH",
   :name=>"Prince Abdul Majeed bin Abdulaziz Airport",
   :city=>"Al Ula",
   :icao=>"OEAO",
   :country=>'Arabia', :country_code=>'',
   :location=>"Al Ula, Arabia"},
 "URY"=>
  {:iata=>"URY",
   :name=>"Gurayat Airport",
   :city=>"Gurayat",
   :icao=>"OEGT",
   :country=>'Arabia', :country_code=>'',
   :location=>"Gurayat, Arabia"},
 "UZH"=>
  {:iata=>"UZH",
   :name=>"Unayzah Airport",
   :city=>"Unayzah",
   :icao=>"",
   :country=>'Arabia', :country_code=>'',
   :location=>"Unayzah, Arabia"},
 "UBS"=>
  {:iata=>"UBS",
   :name=>"Columbus-Lowndes County Airport",
   :icao=>"KUBS",
   :city=>"Columbus",
   :country=>'United States', :country_code=>'US',

   :location=>"Columbus, Mississippi, United States"},
 "UCA"=>
  {:iata=>"UCA",
   :name=>"Oneida County Airport",
   :icao=>"KUCA",
   :city=>"Utica",
   :country=>'United States', :country_code=>'US',

   :location=>"Utica, New York, United States"},
 "UCC"=>
  {:iata=>"UCC",
   :name=>"Yucca Airstrip (FAA: NV11)",
   :icao=>"KUCC",
   :city=>"Mercury",
   :country=>'United States', :country_code=>'US',

   :location=>"Mercury, Nevada, United States"},
 "UCE"=>
  {:iata=>"UCE",
   :name=>"Eunice Airport (FAA: 4R7)",
   :icao=>"",
   :city=>"Eunice",
   :country=>'United States', :country_code=>'US',

   :location=>"Eunice, Louisiana, United States"},
 "UCY"=>
  {:iata=>"UCY",
   :name=>"Everett-Stewart Airport",
   :icao=>"KUCY",
   :city=>"Union City",
   :country=>'United States', :country_code=>'US',

   :location=>"Union City, Tennessee, United States"},
 "UDD"=>
  {:iata=>"UDD",
   :name=>"Bermuda Dunes Airport",
   :icao=>"KUDD",
   :city=>"Palm Springs",
   :country=>'United States', :country_code=>'US',

   :location=>"Palm Springs, California, United States"},
 "UES"=>
  {:iata=>"UES",
   :name=>"Waukesha County Airport",
   :icao=>"KUES",
   :city=>"Waukesha",
   :country=>'United States', :country_code=>'US',

   :location=>"Waukesha, Wisconsin, United States"},
 "UGB"=>
  {:iata=>"UGB",
   :name=>"Ugashik Bay Airport",
   :icao=>"",
   :city=>"Pilot Point",
   :country=>'United States', :country_code=>'US',

   :location=>"Pilot Point, Alaska, United States"},
 "UGI"=>
  {:iata=>"UGI",
   :name=>"Uganik Airport",
   :icao=>"",
   :city=>"Uganik Island",
   :country=>'United States', :country_code=>'US',

   :location=>"Uganik Island, United States"},
 "UGN"=>
  {:iata=>"UGN",
   :name=>"Waukegan Regional Airport",
   :icao=>"KUGN",
   :city=>"Chicago / Waukegan",
   :country=>'United States', :country_code=>'US',

   :location=>"Chicago / Waukegan, Illinois, United States"},
 "UGS"=>
  {:iata=>"UGS",
   :name=>"Ugashik Airport (FAA: 9A8)",
   :icao=>"",
   :city=>"Ugashik",
   :country=>'United States', :country_code=>'US',

   :location=>"Ugashik, Alaska, United States"},
 "UIL"=>
  {:iata=>"UIL",
   :name=>"Quillayute Airport",
   :icao=>"KUIL",
   :city=>"Forks",
   :country=>'United States', :country_code=>'US',

   :location=>"Forks, Washington, United States"},
 "UIN"=>
  {:iata=>"UIN",
   :name=>"Quincy Regional Airport (Baldwin Field)",
   :icao=>"KUIN",
   :city=>"Quincy",
   :country=>'United States', :country_code=>'US',

   :location=>"Quincy, Illinois, United States"},
 "UKI"=>
  {:iata=>"UKI",
   :name=>"Ukiah Municipal Airport",
   :icao=>"KUKI",
   :city=>"Ukiah",
   :country=>'United States', :country_code=>'US',

   :location=>"Ukiah, California, United States"},
 "UKN"=>
  {:iata=>"UKN",
   :name=>"Waukon Municipal Airport (FAA: Y01)",
   :icao=>"",
   :city=>"Waukon",
   :country=>'United States', :country_code=>'US',

   :location=>"Waukon, Iowa, United States"},
 "UKT"=>
  {:iata=>"UKT",
   :name=>"Quakertown Airport",
   :icao=>"KUKT",
   :city=>"Quakertown",
   :country=>'United States', :country_code=>'US',

   :location=>"Quakertown, Pennsylvania, United States"},
 "ULM"=>
  {:iata=>"ULM",
   :name=>"New Ulm Municipal Airport",
   :icao=>"KULM",
   :city=>"New Ulm",
   :country=>'United States', :country_code=>'US',

   :location=>"New Ulm, Minnesota, United States"},
 "UMA"=>
  {:iata=>"UMA",
   :name=>"Punta de Maisi Airport",
   :icao=>"",
   :city=>"Maisí",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Maisí, Guantánamo Province, Cuba"},
 "UMM"=>
  {:iata=>"UMM",
   :name=>"Summit Airport",
   :icao=>"PAST",
   :city=>"Summit",
   :country=>'United States', :country_code=>'US',

   :location=>"Summit, Alaska, United States"},
 "UMT"=>
  {:iata=>"UMT",
   :name=>"Umiat Airport",
   :icao=>"PAUM",
   :city=>"Umiat",
   :country=>'United States', :country_code=>'US',

   :location=>"Umiat, Alaska, United States"},
 "UNK"=>
  {:iata=>"UNK",
   :name=>"Unalakleet Airport",
   :icao=>"PAUN",
   :city=>"Unalakleet",
   :country=>'United States', :country_code=>'US',

   :location=>"Unalakleet, Alaska, United States"},
 "UNU"=>
  {:iata=>"UNU",
   :name=>"Dodge County Airport",
   :icao=>"KUNU",
   :city=>"Juneau",
   :country=>'United States', :country_code=>'US',

   :location=>"Juneau, Wisconsin, United States"},
 "UOS"=>
  {:iata=>"UOS",
   :name=>"Franklin County Airport",
   :icao=>"KUOS",
   :city=>"Sewanee",
   :country=>'United States', :country_code=>'US',

   :location=>"Sewanee, Tennessee, United States"},
 "UOX"=>
  {:iata=>"UOX",
   :name=>"University-Oxford Airport",
   :icao=>"KUOX",
   :city=>"Oxford",
   :country=>'United States', :country_code=>'US',

   :location=>"Oxford, Mississippi, United States"},
 "UPP"=>
  {:iata=>"UPP",
   :name=>"Upolu Airport",
   :icao=>"PHUP",
   :city=>"Hawi",
   :country=>'United States', :country_code=>'US',

   :location=>"Hawi, Hawaii, United States"},
 "USA"=>
  {:iata=>"USA",
   :name=>"Concord Regional Airport",
   :icao=>"KJQF",
   :city=>"Concord",
   :country=>'United States', :country_code=>'US',

   :location=>"Concord, North Carolina, United States"},
 "UST"=>
  {:iata=>"UST",
   :name=>"St. Augustine Airport (FAA: SGJ)",
   :icao=>"KSGJ",
   :city=>"St. Augustine",
   :country=>'United States', :country_code=>'US',

   :location=>"St. Augustine, Florida, United States"},
 "UTM"=>
  {:iata=>"UTM",
   :name=>"Tunica Municipal Airport (FAA: UTA)",
   :icao=>"KUTA",
   :city=>"Tunica",
   :country=>'United States', :country_code=>'US',

   :location=>"Tunica, Mississippi, United States"},
 "UTO"=>
  {:iata=>"UTO",
   :name=>"Indian Mountain LRRS Airport",
   :icao=>"PAIM",
   :city=>"Utopia Creek",
   :country=>'United States', :country_code=>'US',

   :location=>"Utopia Creek, Alaska, United States"},
 "UUK"=>
  {:iata=>"UUK",
   :name=>"Ugnu-Kuparuk Airport (FAA: UBW)",
   :icao=>"PAKU",
   :city=>"Kuparuk",
   :country=>'United States', :country_code=>'US',

   :location=>"Kuparuk, Alaska, United States"},
 "UVA"=>
  {:iata=>"UVA",
   :name=>"Garner Field",
   :icao=>"KUVA",
   :city=>"Uvalde",
   :country=>'United States', :country_code=>'US',

   :location=>"Uvalde, Texas, United States"},
 "UWA"=>
  {:iata=>"UWA",
   :name=>"Ware Airport (FAA: MA53)",
   :icao=>"",
   :city=>"Ware",
   :country=>'United States', :country_code=>'US',

   :location=>"Ware, Massachusetts, United States"}}

end
