# encoding: UTF-8
def airp_9
  {"HZP"=>
  {:iata=>"HZP",
   :name=>"Fort MacKay/Horizon Airport",
   :city=>"Fort MacKay",
   :icao=>"CYNR",
   :country=>"Canada",
:country_code=>"CA",
   :location=>"Fort MacKay, Canada"},
 "HMO"=>
  {:iata=>"HMO",
   :name=>"General Ignacio Pesqueira Garcia International Airport",
   :icao=>"MMHO",
   :city=>"Hermosillo",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Hermosillo, Sonora, Mexico"},
 "HUX"=>
  {:iata=>"HUX",
   :name=>"Huatulco International Airport",
   :icao=>"MMBT",
   :city=>"Huatulco (Bahías de Huatulco)",
   :country=>'Mexico', :country_code=>'MX',

   :location=>"Huatulco (Bahías de Huatulco), Oaxaca, Mexico"},
 "HNX"=>
  {:iata=>"HNX",
   :name=>"Hanna Airport",
   :city=>"Hanna",
   :icao=>"",
   :country=>'States', :country_code=>'',
   :location=>"Hanna, States"},
 "HOS"=>
  {:iata=>"HOS",
   :name=>"Chos Malal Airport (Oscar Reguera Airport)",
   :icao=>"SAHC",
   :city=>"Chos Malal",
   :country=>"Argentina",
:country_code=>"AR",
   :location=>"Chos Malal, Neuquén, Argentina"},
 "HUW"=>
  {:iata=>"HUW",
   :name=>"Humaita Airport",
   :city=>"Humaita",
   :icao=>"SWHT",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Humaita, Brazil"},
 "HRZ"=>
  {:iata=>"HRZ",
   :name=>"Horizontina Airport",
   :icao=>"",
   :city=>"Horizontina",
   :country=>"Brazil",
:country_code=>"BR",
   :location=>"Horizontina, Rio Grande do Sul, Brazil"},
 "HTZ"=>
  {:iata=>"HTZ",
   :name=>"Hato Corozal Airport",
   :icao=>"SKHC",
   :city=>"Hato Corozal",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Hato Corozal, Colombia"},
 "HRR"=>
  {:iata=>"HRR",
   :name=>"Herrera Airport",
   :icao=>"",
   :city=>"Herrera",
   :country=>"Colombia",
:country_code=>"CO",
   :location=>"Herrera, Colombia"},
 "HUU"=>
  {:iata=>"HUU",
   :name=>"Alférez FAP David Figueroa Fernandini Airport",
   :icao=>"SPNC",
   :city=>"Huánuco",
   :country=>"Peru",
:country_code=>"PE",
   :location=>"Huánuco, Huánuco Region, Peru"},
 "HLT"=>
  {:iata=>"HLT",
   :name=>"Hamilton Airport",
   :icao=>"YHML",
   :city=>"Hamilton",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hamilton, Victoria, Australia"},
 "HTI"=>
  {:iata=>"HTI",
   :name=>"Great Barrier Reef Airport",
   :icao=>"YBHM",
   :city=>"Hamilton Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hamilton Island, Queensland, Australia"},
 "HIS"=>
  {:iata=>"HIS",
   :name=>"Hayman Island Resort Seaplace Base",
   :icao=>"",
   :city=>"Hayman Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hayman Island, Queensland, Australia"},
 "HVB"=>
  {:iata=>"HVB",
   :name=>"Hervey Bay Airport",
   :icao=>"YHBA",
   :city=>"Hervey Bay",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hervey Bay, Queensland, Australia"},
 "HBA"=>
  {:iata=>"HBA",
   :name=>"Hobart Airport",
   :icao=>"YMHB",
   :city=>"Hobart",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hobart, Tasmania, Australia"},
 "HID"=>
  {:iata=>"HID",
   :name=>"Horn Island Airport",
   :icao=>"YHID",
   :city=>"Horn Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Horn Island, Queensland, Australia"},
 "HGD"=>
  {:iata=>"HGD",
   :name=>"Hughenden Airport",
   :icao=>"YHUG",
   :city=>"Hughenden",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hughenden, Queensland, Australia"},
 "HCQ"=>
  {:iata=>"HCQ",
   :name=>"Halls Creek Airport",
   :icao=>"YHLC",
   :city=>"Halls Creek",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Halls Creek, Western Australia, Australia"},
 "HWK"=>
  {:iata=>"HWK",
   :name=>"Wilpena Pound",
   :icao=>"YHAW",
   :city=>"Hawker",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hawker, South Australia, Australia"},
 "HXX"=>
  {:iata=>"HXX",
   :name=>"Hay Airport",
   :icao=>"YHAY",
   :city=>"Hay",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hay, New South Wales, Australia"},
 "HIP"=>
  {:iata=>"HIP",
   :name=>"Headingly Airport",
   :icao=>"YHDY",
   :city=>"Headingly Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Headingly Station, Queensland, Australia"},
 "HAT"=>
  {:iata=>"HAT",
   :name=>"Heathlands Airport",
   :icao=>"YHTL",
   :city=>"Heathlands",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Heathlands, Queensland, Australia"},
 "HLV"=>
  {:iata=>"HLV",
   :name=>"Helenvale Airport",
   :icao=>"",
   :city=>"Helenvale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Helenvale, Queensland, Australia"},
 "HRY"=>
  {:iata=>"HRY",
   :name=>"Henbury Airport",
   :icao=>"YHBY",
   :city=>"Henbury Station",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Henbury Station, Northern Territory, Australia"},
 "HMG"=>
  {:iata=>"HMG",
   :name=>"Hermannsburg Airport",
   :icao=>"YHMB",
   :city=>"Hermannsburg",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hermannsburg, Northern Territory, Australia"},
 "HRN"=>
  {:iata=>"HRN",
   :name=>"Heron Island Heliport",
   :icao=>"",
   :city=>"Heron Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Heron Island, Queensland, Australia"},
 "HIG"=>
  {:iata=>"HIG",
   :name=>"Highbury Airport",
   :icao=>"YHHY",
   :city=>"Highbury",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Highbury, Queensland, Australia"},
 "HLL"=>
  {:iata=>"HLL",
   :name=>"Hillside Airport",
   :icao=>"YHIL",
   :city=>"Hillside",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hillside, Western Australia, Australia"},
 "HNK"=>
  {:iata=>"HNK",
   :name=>"Hinchinbrook Island Airport",
   :icao=>"",
   :city=>"Hinchinbrook Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hinchinbrook Island, Queensland, Australia"},
 "HIH"=>
  {:iata=>"HIH",
   :name=>"Hook Island Airport",
   :icao=>"",
   :city=>"Hook Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hook Island, Queensland, Australia"},
 "HOK"=>
  {:iata=>"HOK",
   :name=>"Lajamanu Airport (Hooker Creek Airport)",
   :icao=>"YHOO",
   :city=>"Lajamanu",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Lajamanu, Northern Territory, Australia"},
 "HPE"=>
  {:iata=>"HPE",
   :name=>"Hope Vale Airport",
   :icao=>"",
   :city=>"Hope Vale",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hope Vale, Queensland, Australia"},
 "HTU"=>
  {:iata=>"HTU",
   :name=>"Hopetoun Airport",
   :icao=>"YHPN",
   :city=>"Hopetoun",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Hopetoun, Victoria, Australia"},
 "HSM"=>
  {:iata=>"HSM",
   :name=>"Horsham Airport",
   :icao=>"YHSM",
   :city=>"Horsham",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Horsham, Victoria, Australia"},
 "HUB"=>
  {:iata=>"HUB",
   :name=>"Humbert River Airport",
   :icao=>"YHBR",
   :city=>"Humbert River",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Humbert River, Northern Territory, Australia"},
 "HAP"=>
  {:iata=>"HAP",
   :name=>"Long Island Airport",
   :icao=>"",
   :city=>"Long Island",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"Long Island, Queensland, Australia"},
 "HLS"=>
  {:iata=>"HLS",
   :name=>"St. Helens Airport",
   :icao=>"YSTH",
   :city=>"St. Helens",
   :country=>"Australia",
:country_code=>"AU",
   :location=>"St. Helens, Tasmania, Australia"},
 "HOI"=>
  {:iata=>"HOI",
   :name=>"Hao Airport",
   :icao=>"NTTO",
   :city=>"Hao",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Hao, Tuamotu Island, French Polynesia"},
 "HHZ"=>
  {:iata=>"HHZ",
   :name=>"Hikueru Atoll Airport",
   :icao=>"NTGH",
   :city=>"Hikueru Atoll",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Hikueru Atoll, French Polynesia"},
 "HUH"=>
  {:iata=>"HUH",
   :name=>"Fare Airport",
   :icao=>"NTTH",
   :city=>"Huahine",
   :country=>"French Polynesia",
:country_code=>"PF",
   :location=>"Huahine, Society Islands, French Polynesia"},
 "HIX"=>
  {:iata=>"HIX",
   :name=>"Hiva Oa Airport",
   :city=>"Hiva Oa",
   :icao=>"NTMN",
   :country=>'Polynesia', :country_code=>'PF',
   :location=>"Hiva Oa, Polynesia"},
 "HNG"=>
  {:iata=>"HNG",
   :name=>"Hienghene Airport",
   :city=>"Hienghene",
   :icao=>"",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Hienghene, Caledonia"},
 "HLU"=>
  {:iata=>"HLU",
   :name=>"Houailou Airport",
   :city=>"Houailou",
   :icao=>"NWWH",
   :country=>'Caledonia', :country_code=>'',
   :location=>"Houailou, Caledonia"},
 "HLZ"=>
  {:iata=>"HLZ",
   :name=>"Hamilton International Airport",
   :icao=>"NZHN",
   :city=>"Hamilton",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Hamilton, New Zealand"},
 "HKK"=>
  {:iata=>"HKK",
   :name=>"Hokitika Airport",
   :icao=>"NZHK",
   :city=>"Hokitika",
   :country=>"New Zealand",
:country_code=>"NZ",
   :location=>"Hokitika, New Zealand"},
 "HIR"=>
  {:iata=>"HIR",
   :name=>"Honiara International Airport",
   :icao=>"AGGH",
   :city=>"Honiara",
   :country=>"Solomon Islands",
:country_code=>"SB",
   :location=>"Honiara, Guadalcanal Island, Solomon Islands"},
 "HPA"=>
  {:iata=>"HPA",
   :name=>"Salote Pilolevu Airport",
   :icao=>"NFTL",
   :city=>"Lifuka",
   :country=>'Tonga', :country_code=>'TO',
   :location=>"Lifuka, Ha'apai, Tonga"},
 "HBI"=>
  {:iata=>"HBI",
   :name=>"Harbour Island Airport",
   :icao=>"",
   :city=>"Harbour Island",
   :country=>"Bahamas",
:country_code=>"BS",
   :location=>"Harbour Island, Bahamas"},
 "HAV"=>
  {:iata=>"HAV",
   :name=>"José Martí International Airport",
   :icao=>"MUHA",
   :city=>"Havana",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Havana, Cuba"},
 "HOG"=>
  {:iata=>"HOG",
   :name=>"Frank País Airport",
   :icao=>"MUHG",
   :city=>"Holguín",
   :country=>"Cuba",
:country_code=>"CU",
   :location=>"Holguín, Cuba"},
 "HEX"=>
  {:iata=>"HEX",
   :name=>"Herrera International Airport (closed)",
   :icao=>"MDHE",
   :city=>"Santo Domingo",
   :country=>"Dominican Republic",
:country_code=>"DO",
   :location=>"Santo Domingo, Dominican Republic"},
 "HTB"=>
  {:iata=>"HTB",
   :name=>"Terre-de-Bas Airport",
   :icao=>"",
   :city=>"Terre-de-Bas",
   :country=>'Guadeloupe', :country_code=>'GP',
   :location=>"Terre-de-Bas, Guadeloupe"},
 "HUC"=>
  {:iata=>"HUC",
   :name=>"Humacao Airport",
   :icao=>"",
   :city=>"Humacao",
   :country=>'United States', :country_code=>'US',
   :location=>"Humacao, Puerto Rico, United States"},
 "HME"=>
  {:iata=>"HME",
   :name=>"Oued Irara Airport",
   :icao=>"DAUH",
   :city=>"Hassi Messaoud",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Hassi Messaoud, Algeria"},
 "HRM"=>
  {:iata=>"HRM",
   :name=>"Tilrempt Airport",
   :icao=>"DAFH",
   :city=>"Hassi R'Mel",
   :country=>"Algeria",
:country_code=>"DZ",
   :location=>"Hassi R'Mel, Algeria"},
 "HUK"=>
  {:iata=>"HUK",
   :name=>"Hukuntsi Airport",
   :icao=>"",
   :city=>"Hukuntsi",
   :country=>'Botswana', :country_code=>'BW',
   :location=>"Hukuntsi, Botswana"},
 "HAH"=>
  {:iata=>"HAH",
   :name=>"Prince Said Ibrahim International Airport",
   :icao=>"FMCH",
   :city=>"Moroni",
   :country=>'Comoros', :country_code=>'KM',
   :location=>"Moroni, Comoros"},
 "HGO"=>
  {:iata=>"HGO",
   :name=>"Korhogo Airport",
   :icao=>"DIKO",
   :city=>"Korhogo",
   :country=>"Côte d'Ivoire", :country_code=>'CI',
   :location=>"Korhogo, Côte d'Ivoire"},
 "HUE"=>
  {:iata=>"HUE",
   :name=>"Humera Airport",
   :icao=>"HAHU",
   :city=>"Humera",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Humera, Ethiopia"},
 "HIL"=>
  {:iata=>"HIL",
   :name=>"Shilabo Airport",
   :icao=>"",
   :city=>"Shilabo",
   :country=>'Ethiopia', :country_code=>'ET',
   :location=>"Shilabo, Ethiopia"},
 "HOA"=>
  {:iata=>"HOA",
   :name=>"Hola Airport",
   :icao=>"HKHO",
   :city=>"Hola",
   :country=>'Kenya', :country_code=>'KE',
   :location=>"Hola, Kenya"},
 "HUQ"=>
  {:iata=>"HUQ",
   :name=>"Hun Airport",
   :icao=>"HLON",
   :city=>"Hun",
   :country=>'Libya', :country_code=>'LY',
   :location=>"Hun, Libya"},
 "HVA"=>
  {:iata=>"HVA",
   :name=>"Analalava Airport",
   :icao=>"FMNL",
   :city=>"Analalava",
   :country=>'Madagascar', :country_code=>'MG',
   :location=>"Analalava, Madagascar"},
 "HAL"=>
  {:iata=>"HAL",
   :name=>"Halali Airport",
   :icao=>"FYHI",
   :city=>"Halali",
   :country=>'Namibia', :country_code=>'NA',
   :location=>"Halali, Namibia"},
 "HGS"=>
  {:iata=>"HGS",
   :name=>"Hastings Airport",
   :icao=>"GFHA",
   :city=>"Freetown",
   :country=>'Sierra Leone', :country_code=>'SL',
   :location=>"Freetown, Sierra Leone"},
 "HGA"=>
  {:iata=>"HGA",
   :name=>"Egal International Airport",
   :icao=>"HCMH",
   :city=>"Hargeisa",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Hargeisa, Somalia"},
 "HCM"=>
  {:iata=>"HCM",
   :name=>"Eil Airport",
   :icao=>"HCME",
   :city=>"Eil",
   :country=>'Somalia', :country_code=>'SO',
   :location=>"Eil, Somalia"},
 "HDS"=>
  {:iata=>"HDS",
   :name=>"Hoedspruit Airport",
   :icao=>"FAHS",
   :city=>"Hoedspruit",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Hoedspruit, South Africa"},
 "HLA"=>
  {:iata=>"HLA",
   :name=>"Lanseria Airport",
   :icao=>"FALA",
   :city=>"Lanseria",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Lanseria, South Africa"},
 "HRS"=>
  {:iata=>"HRS",
   :name=>"Harrismith Airport",
   :icao=>"FAHR",
   :city=>"Harrismith",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Harrismith, South Africa"},
 "HZV"=>
  {:iata=>"HZV",
   :name=>"Hazyview Airport",
   :icao=>"FAHW",
   :city=>"Hazyview",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Hazyview, South Africa"},
 "HLW"=>
  {:iata=>"HLW",
   :name=>"Hluhluwe Airport",
   :icao=>"FAHL",
   :city=>"Hluhluwe",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Hluhluwe, South Africa"},
 "HCS"=>
  {:iata=>"HCS",
   :name=>"Randburg Heliport",
   :city=>"Johannesburg",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Johannesburg, Africa"},
 "HIC"=>
  {:iata=>"HIC",
   :name=>"Iscor Heliport",
   :city=>"Pretoria",
   :icao=>"",
   :country=>'Africa', :country_code=>'',
   :location=>"Pretoria, Africa"},
 "HPR"=>
  {:iata=>"HPR",
   :name=>"Pretoria Central Heliport",
   :icao=>"",
   :city=>"Pretoria",
   :country=>'South Africa', :country_code=>'ZA',
   :location=>"Pretoria, South Africa"},
 "HRE"=>
  {:iata=>"HRE",
   :name=>"Harare International Airport",
   :icao=>"FVHA",
   :city=>"Harare",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Harare, Zimbabwe"},
 "HWN"=>
  {:iata=>"HWN",
   :name=>"Hwange National Park Airport",
   :icao=>"FVWN",
   :city=>"Hwange National Park",
   :country=>'Zimbabwe', :country_code=>'ZW',
   :location=>"Hwange National Park, Zimbabwe"},
 "HOH"=>
  {:iata=>"HOH",
   :name=>"Hohenems-Dornbirn Airport",
   :icao=>"LOIH",
   :city=>"Hohenems",
   :country=>'Austria', :country_code=>'AU',
   :location=>"Hohenems, Austria"},
 "HKV"=>
  {:iata=>"HKV",
   :name=>"Haskovo Malevo Airport",
   :icao=>"LBHS",
   :city=>"Haskovo",
   :country=>'Bulgaria', :country_code=>'BG',
   :location=>"Haskovo, Bulgaria"},
 "HEL"=>
  {:iata=>"HEL",
   :name=>"Helsinki Airport",
   :icao=>"EFHK",
   :city=>"Helsinki / Vantaa",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Helsinki / Vantaa, Finland"},
 "HEM"=>
  {:iata=>"HEM",
   :name=>"Helsinki-Malmi Airport",
   :icao=>"EFHF",
   :city=>"Helsinki / Malmi",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Helsinki / Malmi, Finland"},
 "HYV"=>
  {:iata=>"HYV",
   :name=>"Hyvinkää Airport",
   :icao=>"EFHV",
   :city=>"Hyvinkää",
   :country=>'Finland', :country_code=>'FI',
   :location=>"Hyvinkää, Finland"},
 "HZB"=>
  {:iata=>"HZB",
   :name=>"Merville - Calonne Airport",
   :icao=>"LFQT",
   :city=>"Merville / Calonne",
   :country=>'France', :country_code=>'FR',
   :location=>"Merville / Calonne, France"},
 "HAM"=>
  {:iata=>"HAM",
   :name=>"Hamburg Airport (Fuhlsbüttel Airport)",
   :icao=>"EDDH",
   :city=>"Hamburg / Fuhlsbüttel",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Hamburg / Fuhlsbüttel, Germany"},
 "HAJ"=>
  {:iata=>"HAJ",
   :name=>"Hannover Airport",
   :icao=>"EDDV",
   :city=>"Hanover",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Hanover, Lower Saxony, Germany"},
 "HHN"=>
  {:iata=>"HHN",
   :name=>"Frankfurt-Hahn Airport",
   :icao=>"EDFH",
   :city=>"Rhineland-Palatinate",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Rhineland-Palatinate, Germany"},
 "HGL"=>
  {:iata=>"HGL",
   :name=>"Düne Airport (Helgoland Airport)",
   :icao=>"EDXH",
   :city=>"Düne",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Düne, Helgoland, Schleswig-Holstein, Germany"},
 "HDF"=>
  {:iata=>"HDF",
   :name=>"Heringsdorf Airport",
   :icao=>"EDAH",
   :city=>"Heringsdorf",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Heringsdorf, Mecklenburg-Vorpommern, Germany"},
 "HOQ"=>
  {:iata=>"HOQ",
   :name=>"Hof Airport (Plauen Airport)",
   :icao=>"EDQM",
   :city=>"Hof",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Hof, Bavaria, Germany"},
 "HEI"=>
  {:iata=>"HEI",
   :name=>"Heide-Büsum Airport",
   :icao=>"EDXB",
   :city=>"Heide",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Heide, Schleswig-Holstein, Germany"},
 "HDB"=>
  {:iata=>"HDB",
   :name=>"Heidelberg Airport",
   :icao=>"EDIU",
   :city=>"Heidelberg",
   :country=>'Germany', :country_code=>'DE',
   :location=>"Heidelberg, Baden-Württemberg, Germany"},
 "HER"=>
  {:iata=>"HER",
   :name=>"Heraklion International Airport, \"Nikos Kazantzakis\"",
   :icao=>"LGIR",
   :city=>"Heraklion",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Heraklion, Crete, Greece"},
 "HEW"=>
  {:iata=>"HEW",
   :name=>"Athens Hellinikon Airport",
   :city=>"Athens",
   :icao=>"",
   :country=>'Greece', :country_code=>'GR',
   :location=>"Athens, Greece"},
 "HVK"=>
  {:iata=>"HVK",
   :name=>"Hólmavík Airport",
   :icao=>"BIHK",
   :city=>"Hólmavík",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Hólmavík, Iceland"},
 "HFN"=>
  {:iata=>"HFN",
   :name=>"Hornafjörður Airport",
   :icao=>"BIHN",
   :city=>"Höfn",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Höfn, Iceland"},
 "HZK"=>
  {:iata=>"HZK",
   :name=>"Húsavík Airport",
   :icao=>"BIHU",
   :city=>"Húsavík",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Húsavík, Iceland"},
 "HVM"=>
  {:iata=>"HVM",
   :name=>"Krókstaðarmelar Airport (Krokstadarmelar)",
   :icao=>"BIHV",
   :city=>"Hvammstangi",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Hvammstangi, Iceland"},
 "HNO"=>
  {:iata=>"HNO",
   :name=>"Herceg-Novi Airport",
   :city=>"Hercegnovi",
   :icao=>"",
   :country=>'Montenegro', :country_code=>'ME',
   :location=>"Hercegnovi, Montenegro"},
 "HFT"=>
  {:iata=>"HFT",
   :name=>"Hammerfest Airport",
   :icao=>"ENHF",
   :city=>"Hammerfest",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Hammerfest, Finnmark, Norway"},
 "HAA"=>
  {:iata=>"HAA",
   :name=>"Hasvik Airport",
   :icao=>"ENHK",
   :city=>"Hasvik",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Hasvik, Norway"},
 "HAU"=>
  {:iata=>"HAU",
   :name=>"Haugesund Airport, Karmøy",
   :icao=>"ENHD",
   :city=>"Haugesund / Karmøy",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Haugesund / Karmøy, Norway"},
 "HVG"=>
  {:iata=>"HVG",
   :name=>"Honningsvåg Airport, Valan",
   :icao=>"ENHV",
   :city=>"Nordkapp",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Nordkapp, Finnmark, Norway"},
 "HOV"=>
  {:iata=>"HOV",
   :name=>"Ørsta/Volda Airport, Hovden",
   :icao=>"ENOV",
   :city=>"Ørsta / Volda / Hovden",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Ørsta / Volda / Hovden, Møre og Romsdal, Norway"},
 "HMR"=>
  {:iata=>"HMR",
   :name=>"Hamar Airport, Stafsberg",
   :icao=>"ENHA",
   :city=>"Hamar",
   :country=>'Norway', :country_code=>'NO',
   :location=>"Hamar, Norway"},
 "HOR"=>
  {:iata=>"HOR",
   :name=>"Horta Airport",
   :icao=>"LPHR",
   :city=>"Horta",
   :country=>'Portugal', :country_code=>'PT',
   :location=>"Horta, Azores, Portugal"},
 "HTA"=>
  {:iata=>"HTA",
   :name=>"Kadala Airport",
   :icao=>"UIAA",
   :city=>"Chita",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Chita, Russia"},
 "HMA"=>
  {:iata=>"HMA",
   :name=>"Khanty-Mansiysk Airport",
   :icao=>"USHH",
   :city=>"Khanty-Mansiysk",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Khanty-Mansiysk, Russia"},
 "HTG"=>
  {:iata=>"HTG",
   :name=>"Hatanga Airport",
   :icao=>"UOHH",
   :city=>"Khatanga",
   :country=>'Russia', :country_code=>'RU',
   :location=>"Khatanga, Krasnoyarsk Krai, Russia"},
 "HEV"=>
  {:iata=>"HEV",
   :name=>"Huelva Airport",
   :city=>"Huelva",
   :icao=>"",
   :country=>'Islands', :country_code=>'',
   :location=>"Huelva, Islands"},
 "HSK"=>
  {:iata=>"HSK",
   :name=>"Huesca-Pirineos Airport",
   :icao=>"LEHC",
   :city=>"Huesca",
   :country=>'Spain', :country_code=>'ES',
   :location=>"Huesca, Spain"},
 "HFS"=>
  {:iata=>"HFS",
   :name=>"Hagfors Airport",
   :icao=>"ESOH",
   :city=>"Hagfors",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Hagfors, Sweden"},
 "HAD"=>
  {:iata=>"HAD",
   :name=>"Halmstad Airport",
   :icao=>"ESMT",
   :city=>"Halmstad",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Halmstad, Sweden"},
 "HMV"=>
  {:iata=>"HMV",
   :name=>"Hemavan Airport",
   :icao=>"ESUT",
   :city=>"Hemavan",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Hemavan, Sweden"},
 "HUV"=>
  {:iata=>"HUV",
   :name=>"Hudiksvall Airport",
   :icao=>"ESNH",
   :city=>"Hudiksvall",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Hudiksvall, Sweden"},
 "HLF"=>
  {:iata=>"HLF",
   :name=>"Hultsfred-Vimmerby Air Base",
   :icao=>"ESSF",
   :city=>"Hultsfred / Vimmerby",
   :country=>'Sweden', :country_code=>'SE',
   :location=>"Hultsfred / Vimmerby, Sweden"},
 "HTY"=>
  {:iata=>"HTY",
   :name=>"Hatay Airport",
   :icao=>"LTDA",
   :city=>"Hatay",
   :country=>'Turkey', :country_code=>'TR',
   :location=>"Hatay, Turkey"},
 "HRK"=>
  {:iata=>"HRK",
   :name=>"Kharkiv International Airport (Osnova Airport)",
   :icao=>"UKHH",
   :city=>"Kharkiv",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Kharkiv, Ukraine"},
 "HMJ"=>
  {:iata=>"HMJ",
   :name=>"Khmelnytsky Airport",
   :icao=>"UKLH",
   :city=>"Khmelnytsky",
   :country=>'Ukraine', :country_code=>'UA',
   :location=>"Khmelnytsky, Ukraine"},
 "HUY"=>
  {:iata=>"HUY",
   :name=>"Humberside Airport",
   :icao=>"EGNJ",
   :city=>"North Lincolnshire",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"North Lincolnshire, United Kingdom"},
 "HRT"=>
  {:iata=>"HRT",
   :name=>"Linton-On-Ouse Airport",
   :icao=>"EGXU",
   :city=>"Harrogate",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Harrogate, England, United Kingdom"},
 "HTF"=>
  {:iata=>"HTF",
   :name=>"Hatfield Aerodrome (closed 1990s)",
   :icao=>"EGTH",
   :city=>"Hatfield",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Hatfield, Hertfordshire, England, United Kingdom"},
 "HAW"=>
  {:iata=>"HAW",
   :name=>"Haverfordwest Aerodrome",
   :icao=>"EGFE",
   :city=>"Haverfordwest",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Haverfordwest, Wales, United Kingdom"},
 "HYC"=>
  {:iata=>"HYC",
   :name=>"RAF High Wycombe",
   :icao=>"EGUH",
   :city=>"High Wycombe",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"High Wycombe, Buckinghamshire, England, United Kingdom"},
 "HLY"=>
  {:iata=>"HLY",
   :name=>"Anglesey Airport (Maes Awyr Môn) / RAF Valley",
   :icao=>"EGOV",
   :city=>"Anglesey",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Anglesey, Wales, United Kingdom"},
 "HOY"=>
  {:iata=>"HOY",
   :name=>"Hoy Airport",
   :icao=>"",
   :city=>"Longhope",
   :country=>'United Kingdom', :country_code=>'GB',
   :location=>"Longhope, Scotland, United Kingdom"},
 "HEA"=>
  {:iata=>"HEA",
   :name=>"Herat Airport",
   :icao=>"OAHR",
   :city=>"Herat",
   :country=>'Afghanistan', :country_code=>'AF',
   :location=>"Herat, Afghanistan"},
 "HAK"=>
  {:iata=>"HAK",
   :name=>"Haikou Meilan International Airport",
   :icao=>"ZJHK",
   :city=>"Haikou",
   :country=>'China', :country_code=>'CN',
   :location=>"Haikou, Hainan, China"},
 "HGH"=>
  {:iata=>"HGH",
   :name=>"Hangzhou Xiaoshan International Airport",
   :icao=>"ZSHC",
   :city=>"Hangzhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Hangzhou, China"},
 "HRB"=>
  {:iata=>"HRB",
   :name=>"Harbin Taiping International Airport",
   :icao=>"ZYHB",
   :city=>"Harbin",
   :country=>'China', :country_code=>'CN',
   :location=>"Harbin, Heilongjiang, China"},
 "HET"=>
  {:iata=>"HET",
   :name=>"Hohhot Baita International Airport",
   :icao=>"ZBHH",
   :city=>"Hohhot",
   :country=>'China', :country_code=>'CN',
   :location=>"Hohhot, Inner Mongolia, China"},
 "HXD"=>
  {:iata=>"HXD",
   :name=>"Delingha Airport",
   :icao=>"",
   :city=>"Delingha",
   :country=>'China', :country_code=>'CN',
   :location=>"Delingha, Qinghai, China"},
 "HLD"=>
  {:iata=>"HLD",
   :name=>"Hailar Dongshan Airport",
   :icao=>"ZBLA",
   :city=>"Hailar",
   :country=>'China', :country_code=>'CN',
   :location=>"Hailar, Inner Mongolia, China"},
 "HMI"=>
  {:iata=>"HMI",
   :name=>"Hami Airport",
   :icao=>"ZWHM",
   :city=>"Hami City",
   :country=>'China', :country_code=>'CN',
   :location=>"Hami City, Xinjiang, China"},
 "HDG"=>
  {:iata=>"HDG",
   :name=>"Handan Airport",
   :icao=>"ZBHD",
   :city=>"Handan",
   :country=>'China', :country_code=>'CN',
   :location=>"Handan, Hebei, China"},
 "HZG"=>
  {:iata=>"HZG",
   :name=>"Hanzhong Airport",
   :icao=>"ZLHZ",
   :city=>"Hanzhong",
   :country=>'China', :country_code=>'CN',
   :location=>"Hanzhong, Shaanxi, China"},
 "HCJ"=>
  {:iata=>"HCJ",
   :name=>"Hechi Airport",
   :icao=>"",
   :city=>"Hechi",
   :country=>'China', :country_code=>'CN',
   :location=>"Hechi, Guangxi, China"},
 "HFE"=>
  {:iata=>"HFE",
   :name=>"Hefei Luogang International Airport",
   :icao=>"ZSOF",
   :city=>"Hefei",
   :country=>'China', :country_code=>'CN',
   :location=>"Hefei, Anhui, China"},
 "HEK"=>
  {:iata=>"HEK",
   :name=>"Heihe Airport",
   :icao=>"ZYHE",
   :city=>"Heihe",
   :country=>'China', :country_code=>'CN',
   :location=>"Heihe, Heilongjiang, China"},
 "HPG"=>
  {:iata=>"HPG",
   :name=>"Shennongjia Hongping Airport",
   :icao=>"",
   :city=>"Shennongjia",
   :country=>'China', :country_code=>'CN',
   :location=>"Shennongjia, Hubei, China"},
 "HTN"=>
  {:iata=>"HTN",
   :name=>"Hotan Airport",
   :icao=>"ZWTN",
   :city=>"Hotan",
   :country=>'China', :country_code=>'CN',
   :location=>"Hotan, Xinjiang, China"},
 "HIA"=>
  {:iata=>"HIA",
   :name=>"Huai'an Lianshui Airport",
   :icao=>"ZSSH",
   :city=>"Huai'an",
   :country=>'China', :country_code=>'CN',
   :location=>"Huai'an, Jiangsu, China"},
 "HJJ"=>
  {:iata=>"HJJ",
   :name=>"Zhijiang Airport",
   :icao=>"",
   :city=>"Zhijiang",
   :country=>'China', :country_code=>'CN',
   :location=>"Zhijiang, Hubei, China"},
 "HZH"=>
  {:iata=>"HZH",
   :name=>"Liping Airport",
   :icao=>"ZUNP",
   :city=>"Liping County",
   :country=>'China', :country_code=>'CN',
   :location=>"Liping County, Guizhou, China"},
 "HYN"=>
  {:iata=>"HYN",
   :name=>"Taizhou Luqiao Airport",
   :icao=>"ZSLQ",
   :city=>"Taizhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Taizhou, Zhejiang, China"},
 "HLH"=>
  {:iata=>"HLH",
   :name=>"Ulanhot Airport",
   :icao=>"ZBUL",
   :city=>"Ulanhot",
   :country=>'China', :country_code=>'CN',
   :location=>"Ulanhot, China"},
 "HSN"=>
  {:iata=>"HSN",
   :name=>"Zhoushan Putuoshan Airport",
   :icao=>"ZSZS",
   :city=>"Zhoushan",
   :country=>'China', :country_code=>'CN',
   :location=>"Zhoushan, Zhejiang, China"},
 "HNY"=>
  {:iata=>"HNY",
   :name=>"Hengyang Airport",
   :icao=>"ZGHY",
   :city=>"Hengyang",
   :country=>'China', :country_code=>'CN',
   :location=>"Hengyang, Hunan, China"},
 "HUZ"=>
  {:iata=>"HUZ",
   :name=>"Huizhou Airport",
   :icao=>"ZGHZ",
   :city=>"Huizhou",
   :country=>'China', :country_code=>'CN',
   :location=>"Huizhou, Guangdong, China"},
 "HSC"=>
  {:iata=>"HSC",
   :name=>"Shaoguan Airport",
   :icao=>"",
   :city=>"Shaoguan",
   :country=>'China', :country_code=>'CN',
   :location=>"Shaoguan, Guangdong, China"},
 "HKG"=>
  {:iata=>"HKG",
   :name=>"Hong Kong International Airport (succeeded Kai Tak Airport)",
   :icao=>"VHHH",
   :city=>"Chek Lap Kok",
   :country=>'Hong Kong', :country_code=>'HK',
   :location=>"Chek Lap Kok, Hong Kong"},
 "HHP"=>
  {:iata=>"HHP",
   :name=>"Shun Tak Heliport",
   :icao=>"VHST",
   :city=>"Sheung Wan",
   :country=>'China', :country_code=>'CN',
   :location=>"Sheung Wan, China"},
 "HYD"=>
  {:iata=>"HYD",
   :name=>"Rajiv Gandhi International Airport (succeeded Begumpet Airport)",
   :icao=>"VOHS",
   :city=>"Hyderabad",
   :country=>"India",
:country_code=>"IN",
   :location=>"Hyderabad, India"},
 "HBX"=>
  {:iata=>"HBX",
   :name=>"Hubli Airport",
   :icao=>"VAHB",
   :city=>"Hubli",
   :country=>"India",
:country_code=>"IN",
   :location=>"Hubli, India"},
 "HJR"=>
  {:iata=>"HJR",
   :name=>"Khajuraho Airport",
   :icao=>"VAKJ",
   :city=>"Khajuraho",
   :country=>"India",
:country_code=>"IN",
   :location=>"Khajuraho, India"},
 "HSS"=>
  {:iata=>"HSS",
   :name=>"Hissar Airport",
   :icao=>"VIHR",
   :city=>"Hissar",
   :country=>"India",
:country_code=>"IN",
   :location=>"Hissar, India"},
 "HLP"=>
  {:iata=>"HLP",
   :name=>"Halim Perdanakusuma International Airport",
   :icao=>"WIHH",
   :city=>"Jakarta",
   :country=>'Indonesia', :country_code=>'ID',
   :location=>"Jakarta, Indonesia"},
 "HDM"=>
  {:iata=>"HDM",
   :name=>"Hamadan Airport",
   :icao=>"OIHH",
   :city=>"Hamadan",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Hamadan, Iran"},
 "HDR"=>
  {:iata=>"HDR",
   :name=>"Havadarya Airport",
   :city=>"Havadarya",
   :icao=>"",
   :country=>'Iran', :country_code=>'IR',
   :location=>"Havadarya, Iran"},
 "HND"=>
  {:iata=>"HND",
   :name=>"Haneda Airport (Haneda Airport)",
   :icao=>"RJTT",
   :city=>"Tokyo",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Tokyo, Honshū, Japan"},
 "HAC"=>
  {:iata=>"HAC",
   :name=>"Hachijojima Airport (Hachijo Jima Airport)",
   :icao=>"RJTH",
   :city=>"Hachijojima (Hachijo Jima)",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hachijojima (Hachijo Jima), Tokyo, Japan"},
 "HKD"=>
  {:iata=>"HKD",
   :name=>"Hakodate Airport",
   :icao=>"RJCH",
   :city=>"Hakodate",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hakodate, Hokkaidō, Japan"},
 "HNA"=>
  {:iata=>"HNA",
   :name=>"Hanamaki Airport",
   :icao=>"RJSI",
   :city=>"Morioka",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Morioka, Honshū, Japan"},
 "HIJ"=>
  {:iata=>"HIJ",
   :name=>"Hiroshima Airport",
   :icao=>"RJOA",
   :city=>"Hiroshima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hiroshima, Honshū, Japan"},
 "HSG"=>
  {:iata=>"HSG",
   :name=>"Saga Airport",
   :icao=>"RJFS",
   :city=>"Saga",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Saga, Kyūshū, Japan"},
 "HHE"=>
  {:iata=>"HHE",
   :name=>"Hachinohe Air Base",
   :icao=>"RJSH",
   :city=>"Hachinohe",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hachinohe, Honshū, Japan"},
 "HTR"=>
  {:iata=>"HTR",
   :name=>"Hateruma Airport",
   :icao=>"RORH",
   :city=>"Hateruma",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hateruma, Okinawa, Japan"},
 "HIW"=>
  {:iata=>"HIW",
   :name=>"Hiroshima West Airport",
   :icao=>"RJBH",
   :city=>"Hiroshima",
   :country=>'Japan', :country_code=>'JP',
   :location=>"Hiroshima, Honshū, Japan"},
 "HRC"=>
  {:iata=>"HRC",
   :name=>"Zhairem Airport",
   :icao=>"",
   :city=>"Zhairem",
   :country=>'Kazakhstan', :country_code=>'KZ',
   :location=>"Zhairem, Kazakhstan"},
 "HOE"=>
  {:iata=>"HOE",
   :name=>"Ban Huoeisay Airport",
   :icao=>"VLHS",
   :city=>"Houeisay",
   :country=>'Laos', :country_code=>'',
   :location=>"Houeisay, Laos"},
 "HAQ"=>
  {:iata=>"HAQ",
   :name=>"Hanimaadhoo Airport",
   :icao=>"VRMH",
   :city=>"Hanimaadhoo",
   :country=>'Maldives', :country_code=>'MV',
   :location=>"Hanimaadhoo, Haa Dhaalu Atoll, Maldives"},
 "HBU"=>
  {:iata=>"HBU",
   :name=>"Bulgan Airport, Khovd",
   :city=>"Bulgan",
   :icao=>"ZMBS",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Bulgan, Mongolia"},
 "HTM"=>
  {:iata=>"HTM",
   :name=>"Khatgal Airport",
   :city=>"Khatgal",
   :icao=>"",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Khatgal, Mongolia"},
 "HVD"=>
  {:iata=>"HVD",
   :name=>"Khovd Airport",
   :icao=>"ZMKD",
   :city=>"Khovd",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Khovd, Mongolia"},
 "HJT"=>
  {:iata=>"HJT",
   :name=>"Khujirt Airport",
   :icao=>"ZMHU",
   :city=>"Khujirt",
   :country=>'Mongolia', :country_code=>'MN',
   :location=>"Khujirt, Övörkhangai, Mongolia"},
 "HEH"=>
  {:iata=>"HEH",
   :name=>"Heho Airport",
   :icao=>"VYHH",
   :city=>"Heho",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Heho, Myanmar (Burma)"},
 "HEB"=>
  {:iata=>"HEB",
   :name=>"Henzada Airport",
   :icao=>"VBHD",
   :city=>"Henzada",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Henzada, Myanmar (Burma)"},
 "HOX"=>
  {:iata=>"HOX",
   :name=>"Hommalinn Airport",
   :icao=>"VYHL",
   :city=>"Hommalinn",
   :country=>"Myanmar (Burma)", :country_code=>'MM',
   :location=>"Hommalinn, Myanmar (Burma)"},
 "HRJ"=>
  {:iata=>"HRJ",
   :name=>"Chaurjhari Airport",
   :icao=>"VNCJ",
   :city=>"Chaurjhari",
   :country=>'Nepal', :country_code=>'NP',
   :location=>"Chaurjhari, Nepal"},
 "HDD"=>
  {:iata=>"HDD",
   :name=>"Hyderabad Airport",
   :icao=>"OPKD",
   :city=>"Hyderabad",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Hyderabad, Pakistan"},
 "HRA"=>
  {:iata=>"HRA",
   :name=>"Mansehra Airport",
   :icao=>"",
   :city=>"Mansehra",
   :country=>'Pakistan', :country_code=>'PK',
   :location=>"Mansehra, Pakistan"},
 "HNN"=>
  {:iata=>"HNN",
   :name=>"Honinabi Airport",
   :icao=>"",
   :city=>"Honinabi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Honinabi, Papua New Guinea"},
 "HKN"=>
  {:iata=>"HKN",
   :name=>"Kimbe Airport",
   :icao=>"AYHK",
   :city=>"Hoskins",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Hoskins, Papua New Guinea"},
 "HGU"=>
  {:iata=>"HGU",
   :name=>"Mount Hagen Airport",
   :icao=>"AYMH",
   :city=>"Mount Hagen",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Mount Hagen, Papua New Guinea"},
 "HBD"=>
  {:iata=>"HBD",
   :name=>"Habi Airport",
   :icao=>"",
   :city=>"Habi",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Habi, Papua New Guinea"},
 "HEO"=>
  {:iata=>"HEO",
   :name=>"Haelogo Airport",
   :icao=>"",
   :city=>"Haelogo",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Haelogo, Papua New Guinea"},
 "HAZ"=>
  {:iata=>"HAZ",
   :name=>"Hatzfeldthaven Airport",
   :icao=>"",
   :city=>"Hatzfeldthaven",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Hatzfeldthaven, Papua New Guinea"},
 "HWA"=>
  {:iata=>"HWA",
   :name=>"Hawabango Airport",
   :icao=>"",
   :city=>"Hawabango",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Hawabango, Papua New Guinea"},
 "HYF"=>
  {:iata=>"HYF",
   :name=>"Hayfields Airport",
   :icao=>"",
   :city=>"Hayfields",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Hayfields, Papua New Guinea"},
 "HNI"=>
  {:iata=>"HNI",
   :name=>"Heiweni Airport",
   :icao=>"",
   :city=>"Heiweni",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Heiweni, Papua New Guinea"},
 "HIT"=>
  {:iata=>"HIT",
   :name=>"Hivaro Airport",
   :icao=>"",
   :city=>"Hivaro",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Hivaro, Papua New Guinea"},
 "HOC"=>
  {:iata=>"HOC",
   :name=>"Komako Airport",
   :icao=>"",
   :city=>"Komako",
   :country=>'Papua New Guinea', :country_code=>'PG',
   :location=>"Komako, Papua New Guinea"},
 "HCN"=>
  {:iata=>"HCN",
   :name=>"Hengchun Airport",
   :icao=>"RCKW",
   :city=>"Hengchun",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Hengchun, Taiwan"},
 "HUN"=>
  {:iata=>"HUN",
   :name=>"Hualien Airport",
   :icao=>"RCYU",
   :city=>"Hualien",
   :country=>'Republic of China', :country_code=>'',
   :location=>"Hualien, Taiwan, Republic of China"},
 "HSZ"=>
  {:iata=>"HSZ",
   :name=>"Hsinchu Airport",
   :icao=>"RCPO",
   :city=>"Hsinchu",
   :country=>'Taiwan', :country_code=>'TW',
   :location=>"Hsinchu, Taiwan"},
 "HIN"=>
  {:iata=>"HIN",
   :name=>"Sacheon Airport / Sacheon Air Base",
   :icao=>"RKPS",
   :city=>"Sacheon",
   :country=>'South Korea', :country_code=>'KR',
   :location=>"Sacheon, South Korea"},
 "HRI"=>
  {:iata=>"HRI",
   :name=>"Mattala Rajapaksa International Airport",
   :icao=>"VCRI",
   :city=>"Hambantota",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Hambantota, Sri Lanka"},
 "HBT"=>
  {:iata=>"HBT",
   :name=>"Hambantota Sea Plane Base",
   :icao=>"",
   :city=>"Hambantota",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Hambantota, Sri Lanka"},
 "HIM"=>
  {:iata=>"HIM",
   :name=>"Minneriya Airport (Polonnaruwa Airport)",
   :icao=>"",
   :city=>"Polonnaruwa",
   :country=>'Sri Lanka', :country_code=>'LK',
   :location=>"Polonnaruwa, Sri Lanka"},
 "HKT"=>
  {:iata=>"HKT",
   :name=>"Phuket International Airport",
   :icao=>"VTSP",
   :city=>"Phuket",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Phuket, Thailand"},
 "HDY"=>
  {:iata=>"HDY",
   :name=>"Hat Yai International Airport",
   :icao=>"VTSS",
   :city=>"Hat Yai",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Hat Yai, Songkhla Province, Thailand"},
 "HGN"=>
  {:iata=>"HGN",
   :name=>"Mae Hong Son Airport",
   :icao=>"VTCH",
   :city=>"Mae Hong Son",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Mae Hong Son, Thailand"},
 "HHQ"=>
  {:iata=>"HHQ",
   :name=>"Hua Hin Airport",
   :icao=>"VTPH",
   :city=>"Hua Hin",
   :country=>'Thailand', :country_code=>'TH',
   :location=>"Hua Hin, Thailand"},
 "HAN"=>
  {:iata=>"HAN",
   :name=>"Noi Bai International Airport",
   :icao=>"VVNB",
   :city=>"Hanoi",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Hanoi, Vietnam"},
 "HPH"=>
  {:iata=>"HPH",
   :name=>"Cat Bi International Airport",
   :icao=>"VVCI",
   :city=>"Haiphong",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Haiphong, Vietnam"},
 "HUI"=>
  {:iata=>"HUI",
   :name=>"Phu Bai International Airport",
   :icao=>"VVPB",
   :city=>"Huế",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Huế, Thừa Thiên–Huế, Vietnam"},
 "HBN"=>
  {:iata=>"HBN",
   :name=>"Phu Bon Airport",
   :icao=>"",
   :city=>"Phu Bon",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Phu Bon, Vietnam"},
 "HOO"=>
  {:iata=>"HOO",
   :name=>"Nhon Co Airport",
   :icao=>"",
   :city=>"Quanduc (Quang Duc)",
   :country=>'Vietnam', :country_code=>'VN',
   :location=>"Quanduc (Quang Duc), Vietnam"},
 "HUG"=>
  {:iata=>"HUG",
   :name=>"Huehuetenango Airport",
   :icao=>"MGHT",
   :city=>"Huehuetenango",
   :country=>'Guatemala', :country_code=>'GT',
   :location=>"Huehuetenango, Huehuetenango, Guatemala"},
 "HBE"=>
  {:iata=>"HBE",
   :name=>"Borg El Arab Airport",
   :icao=>"HEBA",
   :city=>"Alexandria / Borg El Arab",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Alexandria / Borg El Arab, Egypt"},
 "HRG"=>
  {:iata=>"HRG",
   :name=>"Hurghada International Airport",
   :icao=>"HEGN",
   :city=>"Hurghada",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Hurghada, Egypt"},
 "HMB"=>
  {:iata=>"HMB",
   :name=>"Mubarak International Airport",
   :city=>"Sohag",
   :icao=>"HEMK",
   :country=>'Egypt', :country_code=>'EG',
   :location=>"Sohag, Egypt"},
 "HFA"=>
  {:iata=>"HFA",
   :name=>"Haifa Airport (Uri Michaeli Airport)",
   :icao=>"LLHA",
   :city=>"Haifa",
   :country=>'Israel', :country_code=>'IL',
   :location=>"Haifa, Israel"},
 "HOD"=>
  {:iata=>"HOD",
   :name=>"Hodeida International Airport",
   :icao=>"OYHD",
   :city=>"Al Hudaydah (Hodeida)",
   :country=>'Yemen', :country_code=>'YE',
   :location=>"Al Hudaydah (Hodeida), Yemen"},
 "HAS"=>
  {:iata=>"HAS",
   :name=>"Ha'il Regional Airport",
   :icao=>"OEHL",
   :city=>"Ha'il",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Ha'il, Saudi Arabia"},
 "HOF"=>
  {:iata=>"HOF",
   :name=>"al-Ahsa Airport (al-Hasa Airport)",
   :icao=>"OEAH",
   :city=>"Hofuf",
   :country=>'Saudi Arabia', :country_code=>'SA',
   :location=>"Hofuf, Saudi Arabia"},
 "HAB"=>
  {:iata=>"HAB",
   :name=>"Marion County - Rankin Fite Airport",
   :icao=>"KHAB",
   :city=>"Hamilton",
   :country=>'United States', :country_code=>'US',
   :location=>"Hamilton, Alabama, United States"},
 "HAE"=>
  {:iata=>"HAE",
   :name=>"Lava Falls Heliport (FAA: AZ15) (Havasupai Airport)",
   :icao=>"",
   :city=>"Supai Village",
   :country=>'United States', :country_code=>'US',
   :location=>"Supai Village, Arizona, United States"},
 "HAF"=>
  {:iata=>"HAF",
   :name=>"Half Moon Bay Airport",
   :icao=>"KHAF",
   :city=>"Half Moon Bay",
   :country=>'United States', :country_code=>'US',
   :location=>"Half Moon Bay, California, United States"},
 "HAI"=>
  {:iata=>"HAI",
   :name=>"Three Rivers Municipal Airport (Dr. Haines Flying Field)",
   :icao=>"KHAI",
   :city=>"Three Rivers",
   :country=>'United States', :country_code=>'US',
   :location=>"Three Rivers, Michigan, United States"},
 "HAO"=>
  {:iata=>"HAO",
   :name=>"Butler County Regional Airport",
   :icao=>"KHAO",
   :city=>"Hamilton",
   :country=>'United States', :country_code=>'US',
   :location=>"Hamilton, Ohio, United States"},
 "HAR"=>
  {:iata=>"HAR",
   :name=>"Capital City Airport (FAA: CXY)",
   :icao=>"KCXY",
   :city=>"Harrisburg",
   :country=>'United States', :country_code=>'US',
   :location=>"Harrisburg, Pennsylvania, United States"},
 "HAX"=>
  {:iata=>"HAX",
   :name=>"Hatbox Field",
   :icao=>"KHAX",
   :city=>"Muskogee",
   :country=>'United States', :country_code=>'US',
   :location=>"Muskogee, Oklahoma, United States"},
 "HAY"=>
  {:iata=>"HAY",
   :name=>"Haycock Airport",
   :icao=>"",
   :city=>"Haycock",
   :country=>'United States', :country_code=>'US',
   :location=>"Haycock, Alaska, United States"},
 "HBB"=>
  {:iata=>"HBB",
   :name=>"Industrial Airpark (FAA: NM83)",
   :icao=>"",
   :city=>"Hobbs",
   :country=>'United States', :country_code=>'US',
   :location=>"Hobbs, New Mexico, United States"},
 "HBG"=>
  {:iata=>"HBG",
   :name=>"Bobby L. Chain Municipal Airport",
   :icao=>"KHBG",
   :city=>"Hattiesburg",
   :country=>'United States', :country_code=>'US',
   :location=>"Hattiesburg, Mississippi, United States"},
 "HBH"=>
  {:iata=>"HBH",
   :name=>"Entrance Island Seaplane Base (Hobart Bay) (FAA: 2Z1)",
   :icao=>"",
   :city=>"Entrance Island",
   :country=>'United States', :country_code=>'US',
   :location=>"Entrance Island, Alaska, United States"},
 "HBR"=>
  {:iata=>"HBR",
   :name=>"Hobart Municipal Airport",
   :icao=>"KHBR",
   :city=>"Hobart",
   :country=>'United States', :country_code=>'US',
   :location=>"Hobart, Oklahoma, United States"},
 "HCA"=>
  {:iata=>"HCA",
   :name=>"Howard County Airport",
   :icao=>"",
   :city=>"Big Spring",
   :country=>'United States', :country_code=>'US',
   :location=>"Big Spring, Texas, United States"},
 "HCC"=>
  {:iata=>"HCC",
   :name=>"Columbia County Airport (FAA: 1B1)",
   :icao=>"",
   :city=>"Hudson",
   :country=>'United States', :country_code=>'US',
   :location=>"Hudson, New York, United States"},
 "HCW"=>
  {:iata=>"HCW",
   :name=>"Cheraw Municipal Airport / Lynch Bellinger Field (FAA: CQW)",
   :icao=>"KCQW",
   :city=>"Cheraw",
   :country=>'United States', :country_code=>'US',
   :location=>"Cheraw, South Carolina, United States"},
 "HCR"=>
  {:iata=>"HCR",
   :name=>"Holy Cross Airport (FAA: HCA)",
   :icao=>"PAHC",
   :city=>"Holy Cross",
   :country=>'United States', :country_code=>'US',
   :location=>"Holy Cross, Alaska, United States"},
 "HDE"=>
  {:iata=>"HDE",
   :name=>"Brewster Field",
   :icao=>"KHDE",
   :city=>"Holdrege",
   :country=>'United States', :country_code=>'US',
   :location=>"Holdrege, Nebraska, United States"},
 "HDH"=>
  {:iata=>"HDH",
   :name=>"Dillingham Airfield",
   :icao=>"PHDH",
   :city=>"Mokuleia",
   :country=>'United States', :country_code=>'US',
   :location=>"Mokuleia, Hawaii, United States"},
 "HDN"=>
  {:iata=>"HDN",
   :name=>"Yampa Valley Airport",
   :icao=>"KHDN",
   :city=>"Hayden",
   :country=>'United States', :country_code=>'US',
   :location=>"Hayden, Colorado, United States"},
 "HDO"=>
  {:iata=>"HDO",
   :name=>"Hondo Municipal Airport (former Hondo AAF)",
   :icao=>"KHDO",
   :city=>"Hondo",
   :country=>'United States', :country_code=>'US',
   :location=>"Hondo, Texas, United States"},
 "HED"=>
  {:iata=>"HED",
   :name=>"Herendeen Bay Airport (FAA: AK33)",
   :icao=>"",
   :city=>"Herendeen Bay",
   :country=>'United States', :country_code=>'US',
   :location=>"Herendeen Bay, Alaska, United States"},
 "HEE"=>
  {:iata=>"HEE",
   :name=>"Thompson-Robbins Airport",
   :icao=>"KHEE",
   :city=>"Helena / West Helena",
   :country=>'United States', :country_code=>'US',
   :location=>"Helena / West Helena, Arkansas, United States"},
 "HEF"=>
  {:iata=>"HEF",
   :name=>"Manassas Regional Airport (Harry P. Davis Field)",
   :icao=>"KHEF",
   :city=>"Manassas",
   :country=>'United States', :country_code=>'US',
   :location=>"Manassas, Virginia, United States"},
 "HES"=>
  {:iata=>"HES",
   :name=>"Hermiston Municipal Airport (FAA: HRI)",
   :icao=>"KHRI",
   :city=>"Hermiston",
   :country=>'United States', :country_code=>'US',
   :location=>"Hermiston, Oregon, United States"},
 "HEY"=>
  {:iata=>"HEY",
   :name=>"Hanchey Army Heliport",
   :icao=>"KHEY",
   :city=>"Fort Rucker",
   :country=>'United States', :country_code=>'US',
   :location=>"Fort Rucker, Dale County, Alabama, United States"},
 "HEZ"=>
  {:iata=>"HEZ",
   :name=>"Natchez-Adams County Airport (Hardy-Anders Field)",
   :icao=>"KHEZ",
   :city=>"Natchez",
   :country=>'United States', :country_code=>'US',
   :location=>"Natchez, Mississippi, United States"},
 "HFD"=>
  {:iata=>"HFD",
   :name=>"Hartford-Brainard Airport",
   :icao=>"KHFD",
   :city=>"Hartford",
   :country=>'United States', :country_code=>'US',
   :location=>"Hartford, Connecticut, United States"},
 "HFF"=>
  {:iata=>"HFF",
   :name=>"Mackall Army Airfield",
   :icao=>"KHFF",
   :city=>"Camp Mackall",
   :country=>'United States', :country_code=>'US',
   :location=>"Camp Mackall, North Carolina, United States"},
 "HGR"=>
  {:iata=>"HGR",
   :name=>"Hagerstown Regional Airport (Richard A. Henson Field)",
   :icao=>"KHGR",
   :city=>"Hagerstown",
   :country=>'United States', :country_code=>'US',
   :location=>"Hagerstown, Maryland, United States"},
 "HGT"=>
  {:iata=>"HGT",
   :name=>"Tusi Army Heliport",
   :icao=>"KHGT",
   :city=>"Fort Hunter Liggett / Jolon",
   :country=>'United States', :country_code=>'US',
   :location=>"Fort Hunter Liggett / Jolon, California, United States"},
 "HGZ"=>
  {:iata=>"HGZ",
   :name=>"Hog River Airport (FAA: 2AK6)",
   :icao=>"",
   :city=>"Hogatza",
   :country=>'United States', :country_code=>'US',
   :location=>"Hogatza, Alaska, United States"},
 "HHH"=>
  {:iata=>"HHH",
   :name=>"Hilton Head Airport (FAA: HXD)",
   :icao=>"KHXD",
   :city=>"Hilton Head Island",
   :country=>'United States', :country_code=>'US',
   :location=>"Hilton Head Island, South Carolina, United States"},
 "HHI"=>
  {:iata=>"HHI",
   :name=>"Wheeler Army Airfield",
   :icao=>"PHHI",
   :city=>"Wahiawa",
   :country=>'United States', :country_code=>'US',
   :location=>"Wahiawa, Hawaii, United States"},
 "HHR"=>
  {:iata=>"HHR",
   :name=>"Hawthorne Municipal Airport (Jack Northrop Field)",
   :icao=>"KHHR",
   :city=>"Hawthorne",
   :country=>'United States', :country_code=>'US',
   :location=>"Hawthorne, California, United States"},
 "HIB"=>
  {:iata=>"HIB",
   :name=>"Chisholm-Hibbing Airport",
   :icao=>"KHIB",
   :city=>"Hibbing",
   :country=>'United States', :country_code=>'US',
   :location=>"Hibbing, Minnesota, United States"},
 "HIE"=>
  {:iata=>"HIE",
   :name=>"Mount Washington Regional Airport",
   :icao=>"KHIE",
   :city=>"Whitefield",
   :country=>'United States', :country_code=>'US',
   :location=>"Whitefield, New Hampshire, United States"},
 "HIF"=>
  {:iata=>"HIF",
   :name=>"Hill Air Force Base",
   :icao=>"KHIF",
   :city=>"Ogden",
   :country=>'United States', :country_code=>'US',
   :location=>"Ogden, Utah, United States"},
 "HII"=>
  {:iata=>"HII",
   :name=>"Lake Havasu City Airport",
   :icao=>"KHII",
   :city=>"Lake Havasu City",
   :country=>'United States', :country_code=>'US',
   :location=>"Lake Havasu City, Arizona, United States"},
 "HIK"=>
  {:iata=>"HIK",
   :name=>"Hickam Air Force Base",
   :icao=>"PHIK",
   :city=>"Honolulu",
   :country=>'United States', :country_code=>'US',
   :location=>"Honolulu, Hawaii, United States"},
 "HIO"=>
  {:iata=>"HIO",
   :name=>"Portland-Hillsboro Airport",
   :icao=>"KHIO",
   :city=>"Hillsboro / Portland",
   :country=>'United States', :country_code=>'US',
   :location=>"Hillsboro / Portland, Oregon, United States"},
 "HKA"=>
  {:iata=>"HKA",
   :name=>"Blytheville Municipal Airport",
   :icao=>"KHKA",
   :city=>"Blytheville",
   :country=>'United States', :country_code=>'US',
   :location=>"Blytheville, Arkansas, United States"},
 "HKB"=>
  {:iata=>"HKB",
   :name=>"Healy Lake Airport",
   :icao=>"",
   :city=>"Healy Lake",
   :country=>'United States', :country_code=>'US',
   :location=>"Healy Lake, Alaska, United States"},
 "HKS"=>
  {:iata=>"HKS",
   :name=>"Hawkins Field",
   :icao=>"KHKS",
   :city=>"Jackson",
   :country=>'United States', :country_code=>'US',
   :location=>"Jackson, Mississippi, United States"},
 "HKY"=>
  {:iata=>"HKY",
   :name=>"Hickory Regional Airport",
   :icao=>"KHKY",
   :city=>"Hickory",
   :country=>'United States', :country_code=>'US',
   :location=>"Hickory, North Carolina, United States"},
 "HLB"=>
  {:iata=>"HLB",
   :name=>"Hillenbrand Industries Airport",
   :icao=>"KHLB",
   :city=>"Batesville",
   :country=>'United States', :country_code=>'US',
   :location=>"Batesville, Indiana, United States"},
 "HLC"=>
  {:iata=>"HLC",
   :name=>"Hill City Municipal Airport",
   :icao=>"KHLC",
   :city=>"Hill City",
   :country=>'United States', :country_code=>'US',
   :location=>"Hill City, Kansas, United States"},
 "HLG"=>
  {:iata=>"HLG",
   :name=>"Wheeling Ohio County Airport",
   :icao=>"KHLG",
   :city=>"Wheeling",
   :country=>'United States', :country_code=>'US',
   :location=>"Wheeling, West Virginia, United States"},
 "HLI"=>
  {:iata=>"HLI",
   :name=>"Hollister Municipal Airport (FAA: CVH)",
   :icao=>"KCVH",
   :city=>"Hollister",
   :country=>'United States', :country_code=>'US',
   :location=>"Hollister, California, United States"},
 "HLM"=>
  {:iata=>"HLM",
   :name=>"Park Township Airport",
   :icao=>"KHLM",
   :city=>"Holland",
   :country=>'United States', :country_code=>'US',
   :location=>"Holland, Michigan, United States"},
 "HLN"=>
  {:iata=>"HLN",
   :name=>"Helena Regional Airport",
   :icao=>"KHLN",
   :city=>"Helena",
   :country=>'United States', :country_code=>'US',
   :location=>"Helena, Montana, United States"},
 "HLO"=>
  {:iata=>"HLO",
   :name=>"Ingjaldssanður Airport (Ingjaldssandur)",
   :icao=>"BIID",
   :city=>"Onundarfjörður",
   :country=>'Iceland', :country_code=>'IS',
   :location=>"Onundarfjörður, Iceland"},
 "HLR"=>
  {:iata=>"HLR",
   :name=>"Hood Army Airfield",
   :icao=>"KHLR",
   :city=>"Fort Hood / Killeen",
   :country=>'United States', :country_code=>'US',
   :location=>"Fort Hood / Killeen, Texas, United States"},
 "HMN"=>
  {:iata=>"HMN",
   :name=>"Holloman Air Force Base",
   :icao=>"KHMN",
   :city=>"Alamogordo",
   :country=>'United States', :country_code=>'US',
   :location=>"Alamogordo, New Mexico, United States"},
 "HMT"=>
  {:iata=>"HMT",
   :name=>"Hemet-Ryan Airport",
   :icao=>"KHMT",
   :city=>"Hemet",
   :country=>'United States', :country_code=>'US',
   :location=>"Hemet, California, United States"},
 "HNB"=>
  {:iata=>"HNB",
   :name=>"Huntingburg Airport",
   :icao=>"KHNB",
   :city=>"Huntingburg",
   :country=>'United States', :country_code=>'US',
   :location=>"Huntingburg, Indiana, United States"},
 "HNC"=>
  {:iata=>"HNC",
   :name=>"Billy Mitchell Airport (FAA: HSE)",
   :icao=>"KHSE",
   :city=>"Hatteras",
   :country=>'United States', :country_code=>'US',
   :location=>"Hatteras, North Carolina, United States"},
 "HNE"=>
  {:iata=>"HNE",
   :name=>"Tahneta Pass Airport (closed)",
   :icao=>"PAHE",
   :city=>"Tahneta Pass Lodge",
   :country=>'United States', :country_code=>'US',
   :location=>"Tahneta Pass Lodge, Alaska, United States"},
 "HNH"=>
  {:iata=>"HNH",
   :name=>"Hoonah Airport",
   :icao=>"PAOH",
   :city=>"Hoonah",
   :country=>'United States', :country_code=>'US',
   :location=>"Hoonah, Alaska, United States"},
 "HNL"=>
  {:iata=>"HNL",
   :name=>"Honolulu International Airport",
   :icao=>"PHNL",
   :city=>"Honolulu",
   :country=>'United States', :country_code=>'US',
   :location=>"Honolulu, Hawaii, United States"},
 "HNM"=>
  {:iata=>"HNM",
   :name=>"Hana Airport",
   :icao=>"PHHN",
   :city=>"Hana",
   :country=>'United States', :country_code=>'US',
   :location=>"Hana, Hawaii, United States"},
 "HNS"=>
  {:iata=>"HNS",
   :name=>"Haines Airport",
   :icao=>"PAHN",
   :city=>"Haines",
   :country=>'United States', :country_code=>'US',
   :location=>"Haines, Alaska, United States"},
 "HOB"=>
  {:iata=>"HOB",
   :name=>"Lea County Regional Airport",
   :icao=>"KHOB",
   :city=>"Hobbs",
   :country=>'United States', :country_code=>'US',
   :location=>"Hobbs, New Mexico, United States"},
 "HOM"=>
  {:iata=>"HOM",
   :name=>"Homer Airport",
   :icao=>"PAHO",
   :city=>"Homer",
   :country=>'United States', :country_code=>'US',
   :location=>"Homer, Alaska, United States"},
 "HON"=>
  {:iata=>"HON",
   :name=>"Huron Regional Airport",
   :icao=>"KHON",
   :city=>"Huron",
   :country=>'United States', :country_code=>'US',
   :location=>"Huron, South Dakota, United States"},
 "HOP"=>
  {:iata=>"HOP",
   :name=>"Campbell Army Airfield",
   :icao=>"KHOP",
   :city=>"Fort Campbell / Hopkinsville",
   :country=>'United States', :country_code=>'US',
   :location=>"Fort Campbell / Hopkinsville, Kentucky, United States"},
 "HOT"=>
  {:iata=>"HOT",
   :name=>"Memorial Field Airport",
   :icao=>"KHOT",
   :city=>"Hot Springs",
   :country=>'United States', :country_code=>'US',
   :location=>"Hot Springs, Arkansas, United States"},
 "HOU"=>
  {:iata=>"HOU",
   :name=>"William P. Hobby Airport",
   :icao=>"KHOU",
   :city=>"Houston",
   :country=>'United States', :country_code=>'US',
   :location=>"Houston, Texas, United States"},
 "HPB"=>
  {:iata=>"HPB",
   :name=>"Hooper Bay Airport",
   :icao=>"PAHP",
   :city=>"Hooper Bay",
   :country=>'United States', :country_code=>'US',
   :location=>"Hooper Bay, Alaska, United States"},
 "HPN"=>
  {:iata=>"HPN",
   :name=>"Westchester County Airport",
   :icao=>"KHPN",
   :city=>"White Plains",
   :country=>'United States', :country_code=>'US',
   :location=>"White Plains, New York, United States"},
 "HPT"=>
  {:iata=>"HPT",
   :name=>"Hampton Municipal Airport",
   :icao=>"KHPT",
   :city=>"Hampton",
   :country=>'United States', :country_code=>'US',
   :location=>"Hampton, Iowa, United States"},
 "HPV"=>
  {:iata=>"HPV",
   :name=>"Princeville Airport (FAA: HI01)",
   :icao=>"",
   :city=>"Hanalei",
   :country=>'United States', :country_code=>'US',
   :location=>"Hanalei, Hawaii, United States"},
 "HPY"=>
  {:iata=>"HPY",
   :name=>"Baytown Airport",
   :icao=>"KHPY",
   :city=>"Baytown",
   :country=>'United States', :country_code=>'US',
   :location=>"Baytown, Texas, United States"},
 "HQM"=>
  {:iata=>"HQM",
   :name=>"Bowerman Airport",
   :icao=>"KHQM",
   :city=>"Hoquiam",
   :country=>'United States', :country_code=>'US',
   :location=>"Hoquiam, Washington, United States"},
 "HRL"=>
  {:iata=>"HRL",
   :name=>"Valley International Airport",
   :icao=>"KHRL",
   :city=>"Harlingen",
   :country=>'United States', :country_code=>'US',
   :location=>"Harlingen, Texas, United States"},
 "HRO"=>
  {:iata=>"HRO",
   :name=>"Boone County Airport",
   :icao=>"KHRO",
   :city=>"Harrison",
   :country=>'United States', :country_code=>'US',
   :location=>"Harrison, Arkansas, United States"},
 "HSB"=>
  {:iata=>"HSB",
   :name=>"Harrisburg-Raleigh Airport",
   :icao=>"KHSB",
   :city=>"Harrisburg",
   :country=>'United States', :country_code=>'US',
   :location=>"Harrisburg, Illinois, United States"},
 "HSH"=>
  {:iata=>"HSH",
   :name=>"Henderson Executive Airport (FAA: HND)",
   :icao=>"KHND",
   :city=>"Henderson",
   :country=>'United States', :country_code=>'US',
   :location=>"Henderson, United States"},
 "HSI"=>
  {:iata=>"HSI",
   :name=>"Hastings Municipal Airport",
   :icao=>"KHSI",
   :city=>"Hastings",
   :country=>'United States', :country_code=>'US',
   :location=>"Hastings, Nebraska, United States"},
 "HSL"=>
  {:iata=>"HSL",
   :name=>"Huslia Airport (FAA: HLA)",
   :icao=>"PAHL",
   :city=>"Huslia",
   :country=>'United States', :country_code=>'US',
   :location=>"Huslia, Alaska, United States"},
 "HSP"=>
  {:iata=>"HSP",
   :name=>"Ingalls Field",
   :icao=>"KHSP",
   :city=>"Hot Springs",
   :country=>'United States', :country_code=>'US',
   :location=>"Hot Springs, Virginia, United States"},
 "HST"=>
  {:iata=>"HST",
   :name=>"Homestead Air Reserve Base",
   :icao=>"KHST",
   :city=>"Homestead",
   :country=>'United States', :country_code=>'US',
   :location=>"Homestead, Florida, United States"},
 "HSV"=>
  {:iata=>"HSV",
   :name=>"Huntsville International Airport (Carl T. Jones Field)",
   :icao=>"KHSV",
   :city=>"Huntsville / Decatur",
   :country=>'United States', :country_code=>'US',
   :location=>"Huntsville / Decatur, Alabama, United States"},
 "HTH"=>
  {:iata=>"HTH",
   :name=>"Hawthorne Industrial Airport",
   :icao=>"KHTH",
   :city=>"Hawthorne",
   :country=>'United States', :country_code=>'US',
   :location=>"Hawthorne, Nevada, United States"},
 "HTL"=>
  {:iata=>"HTL",
   :name=>"Roscommon County - Blodgett Memorial Airport",
   :icao=>"KHTL",
   :city=>"Houghton Lake",
   :country=>'United States', :country_code=>'US',
   :location=>"Houghton Lake, Michigan, United States"},
 "HTO"=>
  {:iata=>"HTO",
   :name=>"East Hampton Airport",
   :icao=>"KHTO",
   :city=>"East Hampton",
   :country=>'United States', :country_code=>'US',
   :location=>"East Hampton, New York, United States"},
 "HTS"=>
  {:iata=>"HTS",
   :name=>"Tri-State Airport (Milton J. Ferguson Field)",
   :icao=>"KHTS",
   :city=>"Huntington",
   :country=>'United States', :country_code=>'US',
   :location=>"Huntington, West Virginia, United States"},
 "HTV"=>
  {:iata=>"HTV",
   :name=>"Huntsville Municipal Airport",
   :icao=>"KUTS",
   :city=>"Huntsville",
   :country=>'United States', :country_code=>'US',
   :location=>"Huntsville, Texas, United States"},
 "HTW"=>
  {:iata=>"HTW",
   :name=>"Lawrence County Airpark",
   :icao=>"KHTW",
   :city=>"Chesapeake",
   :country=>'United States', :country_code=>'US',
   :location=>"Chesapeake, Ohio / Huntington, West Virginia, United States"},
 "HUA"=>
  {:iata=>"HUA",
   :name=>"Redstone Army Airfield",
   :icao=>"KHUA",
   :city=>"Redstone Arsenal (near Huntsville)",
   :country=>'United States', :country_code=>'US',
   :location=>"Redstone Arsenal (near Huntsville), Alabama, United States"},
 "HUD"=>
  {:iata=>"HUD",
   :name=>"Humboldt Municipal Airport (FAA: 0K7)",
   :icao=>"",
   :city=>"Humboldt",
   :country=>'United States', :country_code=>'US',
   :location=>"Humboldt, Iowa, United States"},
 "HUF"=>
  {:iata=>"HUF",
   :name=>"Terre Haute International Airport (Hulman Field)",
   :icao=>"KHUF",
   :city=>"Terre Haute",
   :country=>'United States', :country_code=>'US',
   :location=>"Terre Haute, Indiana, United States"},
 "HUJ"=>
  {:iata=>"HUJ",
   :name=>"Stan Stamper Municipal Airport (FAA: HHW)",
   :icao=>"KHHW",
   :city=>"Hugo",
   :country=>'United States', :country_code=>'US',
   :location=>"Hugo, Oklahoma, United States"},
 "HUL"=>
  {:iata=>"HUL",
   :name=>"Houlton International Airport",
   :icao=>"KHUL",
   :city=>"Houlton",
   :country=>'United States', :country_code=>'US',
   :location=>"Houlton, Maine, United States"},
 "HUM"=>
  {:iata=>"HUM",
   :name=>"Houma-Terrebonne Airport",
   :icao=>"KHUM",
   :city=>"Houma",
   :country=>'United States', :country_code=>'US',
   :location=>"Houma, Louisiana, United States"},
 "HUS"=>
  {:iata=>"HUS",
   :name=>"Hughes Airport",
   :icao=>"PAHU",
   :city=>"Hughes",
   :country=>'United States', :country_code=>'US',
   :location=>"Hughes, Alaska, United States"},
 "HUT"=>
  {:iata=>"HUT",
   :name=>"Hutchinson Municipal Airport",
   :icao=>"KHUT",
   :city=>"Hutchinson",
   :country=>'United States', :country_code=>'US',
   :location=>"Hutchinson, Kansas, United States"},
 "HVE"=>
  {:iata=>"HVE",
   :name=>"Hanksville Airport",
   :icao=>"KHVE",
   :city=>"Hanksville",
   :country=>'United States', :country_code=>'US',
   :location=>"Hanksville, Utah, United States"},
 "HVN"=>
  {:iata=>"HVN",
   :name=>"Tweed-New Haven Airport",
   :icao=>"KHVN",
   :city=>"New Haven",
   :country=>'United States', :country_code=>'US',
   :location=>"New Haven, Connecticut, United States"},
 "HVR"=>
  {:iata=>"HVR",
   :name=>"Havre City-County Airport",
   :icao=>"KHVR",
   :city=>"Havre",
   :country=>'United States', :country_code=>'US',
   :location=>"Havre, Montana, United States"},
 "HVS"=>
  {:iata=>"HVS",
   :name=>"Hartsville Regional Airport",
   :icao=>"KHVS",
   :city=>"Hartsville",
   :country=>'United States', :country_code=>'US',
   :location=>"Hartsville, South Carolina, United States"},
 "HWD"=>
  {:iata=>"HWD",
   :name=>"Hayward Executive Airport",
   :icao=>"KHWD",
   :city=>"Hayward",
   :country=>'United States', :country_code=>'US',
   :location=>"Hayward, California, United States"},
 "HWI"=>
  {:iata=>"HWI",
   :name=>"Hawk Inlet Seaplane Base",
   :icao=>"",
   :city=>"Hawk Inlet",
   :country=>'United States', :country_code=>'US',
   :location=>"Hawk Inlet, Alaska, United States"},
 "HWO"=>
  {:iata=>"HWO",
   :name=>"North Perry Airport",
   :icao=>"KHWO",
   :city=>"Hollywood",
   :country=>'United States', :country_code=>'US',
   :location=>"Hollywood, Florida, United States"},
 "HYA"=>
  {:iata=>"HYA",
   :name=>"Barnstable Municipal Airport (Boardman/Polando Field)",
   :icao=>"KHYA",
   :city=>"Hyannis",
   :country=>'United States', :country_code=>'US',
   :location=>"Hyannis, Massachusetts, United States"},
 "HYG"=>
  {:iata=>"HYG",
   :name=>"Hydaburg Seaplane Base",
   :icao=>"PAHY",
   :city=>"Hydaburg",
   :country=>'United States', :country_code=>'US',
   :location=>"Hydaburg, Alaska, United States"},
 "HYL"=>
  {:iata=>"HYL",
   :name=>"Hollis Seaplane Base",
   :icao=>"",
   :city=>"Hollis",
   :country=>'United States', :country_code=>'US',
   :location=>"Hollis, Alaska, United States"},
 "HYR"=>
  {:iata=>"HYR",
   :name=>"Sawyer County Airport",
   :icao=>"KHYR",
   :city=>"Hayward",
   :country=>'United States', :country_code=>'US',
   :location=>"Hayward, Wisconsin, United States"},
 "HYS"=>
  {:iata=>"HYS",
   :name=>"Hays Regional Airport",
   :icao=>"KHYS",
   :city=>"Hays",
   :country=>'United States', :country_code=>'US',
   :location=>"Hays, Kansas, United States"},
 "HZL"=>
  {:iata=>"HZL",
   :name=>"Hazleton Municipal Airport",
   :icao=>"KHZL",
   :city=>"Hazleton",
   :country=>'United States', :country_code=>'US',
   :location=>"Hazleton, Pennsylvania, United States"},
 "HZR"=>
  {:iata=>"HZR",
   :name=>"False River Regional Airport",
   :icao=>"KHZR",
   :city=>"New Roads",
   :country=>'United States', :country_code=>'US',
   :location=>"New Roads, Louisiana, United States"}}

end
